### ISSUE TITLE
システム上のウィンドウタイトルが変わっていない

### ISSUE THREAD

**Issue by sevenc-nanashi** [VOICEVOX/voicevox#1011]
## 不具合の内容

現在、Windowsのシステム上のウィンドウタイトル（タスクバーのアイコンをホバーしたり、Win+Tabを開いたりすると確認できる）が`voicevox`に固定されてしまっています。

### 現象・ログ

（内容を参照）

### 再現手順

Windows：
1. 起動する。
2. タスクバーのアイコンをホバーする

### 期待動作

MenuBarのタイトルと同期している。

## VOICEVOXのバージョン

（全て）

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

## その他

Macなどでも同じ問題が起きてるかも？（Macを持っていないのでわからない）

**Comment by PickledChair** [comment]
macOS でも多分同じと思われる挙動に以前から気づいていましたが、スルーしていました……。

Mission Control を表示した時のウィンドウ上の表示と、メニューバーのメニュー項目の表示が `voicevox-cpu` になります（macOS 版は CPU 版しかないため）。

<img width="1440" alt="mission_control" src="https://user-images.githubusercontent.com/41382894/200009462-edbb3a0a-6ce7-4cd9-afbc-ff6e3c69bb0b.png">
<img width="258" alt="menubar" src="https://user-images.githubusercontent.com/41382894/200009488-0b55475d-b145-4bc2-ac58-e09bf38e40fe.png">

Dock 上のアイコンに表示されるアプリケーション名は `VOICEVOX.app` から名前が取られるようなので `VOICEVOX` という名前になります（これは期待通りの挙動です）。

<img width="511" alt="dock" src="https://user-images.githubusercontent.com/41382894/200009864-550e1840-636f-446c-9f81-89a5c23d2637.png">

期待動作として

> MenuBarのタイトルと同期している。

と提案されていますが、おそらくアプリケーション名（`VOICEVOX`）が表示される方が良い気がしています（ただし、あまりよく知らないのですが Windows で一般的に期待される挙動が「MenuBarのタイトルと同期」ということであれば、Windows ではそのようにするのが良いのかもしれません。他のアプリケーションではどのような挙動になっていそうでしょうか？）。

**Comment by Hiroshiba** [comment]
VOICEVOXの場合、よくあるアプリケーションはたしかにwindowタイトルが表示されてますね！
macも、同一アプリで複数ウィンドウが開いているときとかはタイトルが表示されるかも？
（なんでしたっけ、指３本を上にスワイプして出てくる･･･mission control･･･？）
