### ISSUE TITLE
`electron-store`における、音声出力サンプリングレートの保存方法の変更

### ISSUE THREAD

**Issue by y-chan** [VOICEVOX/voicevox#1044]
## 内容

- #925 にて、エンジンのデフォルトサンプリングレートを使うようにする機能が実装されました。
- これに関して[Discordコミュニティ](https://discord.gg/WHRXf2R9Pu)において、`default`文字列をelectron-storeに保存する実装が適切でない可能性が指摘されました。
  - 代替案として、以下のようなオブジェクトを保存するようにし、マイグレーションを行う案が提案されました。
  ```typescript
  {
    isDefaultSamplingRate: boolean,
    samplingRate: number
  }
  ```
  - 現状、マルチエンジン対応がなされたVOICEVOXはリリースされていないので、現状の使用を想定しないでマイグレーション処理を書くことができると思います。
- このような案の提案を受け、**ここでは`electron-store`における、音声出力サンプリングレートの保存方法の変更を議論します。**
  - 先ほどの案が最適であるかは不明であるため、更に良い案がないか考えたいです。

### Pros 良くなる点

現状のあまり良くないと思わしき仕様を改善することができる。

### Cons 悪くなる点

おそらくマイグレーションを行うことが必須である。

## VOICEVOXのバージョン

0.14.0 (Development)

**Comment by Hiroshiba** [comment]
> マイグレーション

現状でも24000Hzのときに"default"にする処理が↓に書いてあるので、ここ書き換えればOKだと思います！
https://github.com/VOICEVOX/voicevox/blob/72b61d9d8dde0008f8090a7f1bcec3f5d59d81d5/src/background.ts#L535-L540

**Comment by Hiroshiba** [comment]
問題はVuex側・API側のデータ構造がオブジェクトになっていないという点ですね･･･。
現状、electron-storeとVuexは`outputSamplingRate: number | "default"`型で、APIは`outputSamplingRate: number`です。

Vuex←→APIでデータ構造の変換が必要ですが、これはここに書いてます。
https://github.com/VOICEVOX/voicevox/blob/65ad4137b8617d77da99b81085206ef54fa71517/src/store/proxy.ts#L36-L47

同様にelectron-store←→Vuexでデータ構造を変換するか、Vuex側をelectron-storeと同じオブジェクトにするか、という感じでしょうか。

**Comment by Hiroshiba** [comment]
ちなみに１回変換が必要なコードを書いたのですが、ややこしいなと思って保存側をUI側と同じ型にして型変換不要にしてみて、今に至ります！
[`f686ac7` (#973)](https://github.com/VOICEVOX/voicevox/pull/973/commits/f686ac7b7d1aebd5a494711b3eb32c4cca225137)

**Comment by Hiroshiba** [comment]
@yamachu さんの意見も伺いたいです 🙏

**Comment by Hiroshiba** [comment]
個人的な温度感はこんな感じです

* `electron-store`←→Vuexでの型変換はなるべく避けたい
  * （実装の複雑度が上がってより初学者からの難度が上がるため）
* numberとstring literalの型で保存するのはそこまで悪くないと思う
  * （`electron-store`が依存してるJSON SchemaもTypeScriptも対応してるため）
* Vuexのstateの型がObject型になるのは別に良い
  * （TypeScriptが守ってくれるため）
* `{isDefault: boolean, samplingRate: number}`は ややこしい気がする
  * 正確な型は`{isDefault: false, samplingRate: number} | {isDefault: true, samplingRate: undefined}`とかになり、JSON Schemaがより複雑になりそう

**Comment by yamachu** [comment]
samplingRateに関する値をAPIとどのようにやり取りをしているのか、またengineのmanifestからどんな感じでengineが使用するdefaultのsamplingRateを取得するのかなど確認しました。
それを踏まえて…

- ゆるい型は逆に実装難易度を上げる（ように感じる）ので別に型変換しても良いのでは？
  - 諸説あります
  - reviewコストを下げる上でもモデリングして型に落とし込んだ方が結果的に後々効きそう
    - とは言えそんなに変わる場所じゃないし正直頑張らなくていいと思う
- `number | 'default'` みたいな型でも別にいいんじゃないか
  - とは言え、`default` が何を指しているのかが分かりづらい気がする
  - saveingSettings で管理しているものがEditorに関するものが多い中、このsamplingRateのdefaultはなんのdefaultを示しているのかパッと分かりづらいように感じる
    - 例えば `engineDefault` なのか…？うーん
    - とは言えEditorで音声は合成はしていない（Editorにffmpegとかつけて、そこでEditorDefaultのsamplingRateでre-samplingとかしませんよね？いやどうだろう、ありそうにも思える）
- もしもオブジェクトなら `{ useEngineDefault: true } | { useEngineDefault: false, samplingRate: number}` にしそう
  - samplingRateのmemberをOmitしているので、そもそも補完に出てこないし、そのmemberについては考慮しないを明示できるので

**Comment by Hiroshiba** [comment]
ありがとうございます！！

`engineDefault`、賛成です（たしかに何指すのかわかりづらそうだったので）
冗長かもですがそんなに複雑でもないので良さそう！

`number | 'engineDefault'`で行くか`{ useEngineDefault: true } | { useEngineDefault: false, samplingRate: number}`で行くかですが、

> これで進めてしまって良いんじゃないか

に僕も賛成です！

とりあえずこの形で進めてみたいと思います。
`engineDefault`にするPRを作ります！

**Comment by Hiroshiba** [comment]
- https://github.com/VOICEVOX/voicevox/pull/1056

@y-chan @yamachu 作成してみました！
