### ISSUE TITLE
すべての音声をつなげて書き出す機能を付ける

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#107]
現状だと音声ファイルが１つ１つ出力されますが、用途によっては全部つながっていたほうが便利です。
see https://twitter.com/syunin_san/status/1427039253981130754

エンジン側に音声結合機能をもたせるか、Node.jsで音声をつなげれば実現できそうです。

まず https://github.com/Hiroshiba/voicevox/issues/106 の実装が先になりそうです。

**Comment by takana-v** [comment]
エンジン側で実装する場合は以下のようになるかなと思います

- ファイル名連番のwavが入ったzipをpost
- 一つに纏まったwavを返却

ファイル名ではなく、jsonファイル等で順番を管理してもいいかもしれません
また、wavの代わりにAudioQueryのjsonをzipに入れた場合は音声合成を行ってくれると便利かもしれませんね

例：001.wav、002.wav、003.jsonが入ったzipをpost→003.jsonを元にエンジン側で音声合成し、001-003を一つにしたwavを返す

**Comment by Hiroshiba** [comment]
良いですね！！

ファイル名は連番でもjson別渡しでも、どちらも良いと思いました！

また、zipで渡す以外にも、multipartとして複数ファイルをpostするでもありかなと思いました。
localhost通信なので転送量はあまり問題にならなそうなので、単純にzipを作成・展開するコードを省け嬉しいかもしれません。

json渡した場合は音声合成にすると転送量が抑えられるので、webサービスとして作るときに便利そうですね！

**Comment by takana-v** [comment]
fastapiについて調べたところ、wavをbase64エンコードしてjsonで渡す実装が楽そうです

/connect_wavesに
```
["wavをbase64エンコードしたもの", ...]
```
を投げる感じで考えてます

若干転送量が増えますが、localhost通信なので問題ないと思います

後、これならリストの順番に繋げればいいのでファイル名云々は考えなくて良くなります

**Comment by Hiroshiba** [comment]
base64エンコードにちょっと処理時間がかかりそうですが、そんなに問題にならないと思うので、そちらの方法がスマートで良いなと感じました！
もしよろしければプルリクエスト頂けると幸いです！

**Comment by Hiroshiba** [comment]
こちらの機能について要望を頂いたのでメモ
https://twitter.com/rike1019/status/1464499708236156935

**Comment by y-chan** [comment]
こちらちょっと取り掛かってみたいと思いますー

**Comment by Hiroshiba** [comment]
了解です、お願いします！

**Comment by Hiroshiba** [comment]
おお、ありがとうございます！　assignします、難しくなったりしたら言って頂ければ！ @y-chan
