### ISSUE TITLE
AudioItemの複製ができるようにする

### ISSUE THREAD

**Issue by k-chop** [VOICEVOX/voicevox#1095]
## 内容

- 選択中のAudioItemを複製できるようにする
- 複製とは：
   - イントネーションや長さ、プリセットの状態等のパラメータすべてを維持したままコピーを作成する

### Pros 良くなる点

- こんなケースで有効
   - 良い感じにできた調声をスナップショットとして一時的に確保しておきたい・再利用したい
      - 途中で方向性を間違ったときにそこに戻りたい
   - 複製した上で末尾や先頭をちょっとだけ変更したい
      - 超絶単純な例：「〇〇さん、こんにちは」の「こんにちは」の調声を維持したまま「〇〇さん」の部分を複数用意したい

### Cons 悪くなる点
- ショートカットキーが1つ埋まる

### 想定問答
- Ctrl+Zを使って戻れば良いのでは？ （「スナップショットを確保しておきたい」というユースケースに対して）
   - 間に他の操作が挟まったり、操作回数が嵩んだときに狙った状態へ戻るのが難しい

### 実現方法
- 既に実装済みなのでこの後PR出し ~ます~ ました #1096 

## その他
- twitterで検索すると要望自体はある様子
   - https://twitter.com/search?q=voicevox%20複製&src=typed_query&f=top

**Comment by k-chop** [comment]
#1096 でPR作成しています

**Comment by Hiroshiba** [comment]
issue＆PRの作成ありがとうございます！！

実は全く同じissueを過去に作っていました！ https://github.com/VOICEVOX/voicevox/issues/978
（descriptionも似ていますね･･･！）
せっかくPR作ってくださったのとこちらのほうが詳しいので、過去の方をとりあえずcloseしたいと思います！

**Comment by k-chop** [comment]
しまった、重複気付いてませんでした。失礼しました 🙇
