### ISSUE TITLE
メニューなどがタイトルバーに被った際、被った部分でマウス操作が出来ない

### ISSUE THREAD

**Issue by mes51** [VOICEVOX/voicevox#1110]
## 不具合の内容

https://github.com/VOICEVOX/voicevox/pull/1030#issuecomment-1382733274 で報告した物になります

キャラクター選択等、メニューやポップアップなどのUIがタイトルバーに被った際、マウス操作が被った要素ではなくタイトルバーに持って行かれてしまい、タイトルバーに被った部分のUIの操作ができません

(現在のバージョンでは極端な使い方をしないと遭遇しません)

### 現象・ログ

https://user-images.githubusercontent.com/936617/212470580-dbdb24cc-dd1c-4fa4-8548-d4b9bb4802a6.mp4

### 再現手順

0.13.3での再現方法(これ以外のバージョンでもおそらく可能)

1. テキスト欄のキャラクター選択のメニューを表示する
2. ウインドウを縦方向に縮める
    * テキスト欄がなくなるくらい(縦272pxくらい?)
    * メニューが上方向に伸びれば再現完了
3. タイトルバーに被った部分でキャラクターが選択できず、 タイトルバーに操作が持って行かれる

### 期待動作

タイトルバーにUIが被っても、被った側のUIが操作できる

## VOICEVOXのバージョン

0.13.3

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

Windows 11 Pro 64bit 21H2 (22000.1455)

## その他

軽く試しましたが、z-indexを操作して要素を手前に持って行っても問答無用でマウス操作を持って行くようです。
回避するには上に被さる可能性がある要素(`q-menu`や`q-select`、あるいはその中の`q-item`)に`-webkit-app-region: no-drag`を付けて回る必要がありそう?

関連: https://github.com/electron/electron/issues/1354

**Comment by Hiroshiba** [comment]
詳細なissue作成ありがとうございます！！
