### ISSUE TITLE
辞書単語登録時にスペースがあっても登録できてしまう

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1115]
## 不具合の内容

スペース付きのを登録して反映されないと不具合報告されている方がいらっしゃいました。
https://twitter.com/quokkaChannel/status/1615279752788717569

音声認識結果というコーナーケースですが、まあエラーを出してもいいかなと思いました。

この辺りで半角スペースを全角スペースに変換すると良さそう？
https://github.com/VOICEVOX/voicevox/blob/4a84ac75f9e19468a33d221bfdcde484d66501d1/src/components/DictionaryManageDialog.vue#L384-L389

### 再現手順

スペース付きで単語登録

### 期待動作

エラーが出る

## その他

エンジン側

- https://github.com/VOICEVOX/voicevox_engine/issues/576

**Comment by tunamaguro** [comment]
すみません。間違えてフォークじゃない方にpushしちゃいました

**Comment by tunamaguro** [comment]
気の所為でした

**Comment by Hiroshiba** [comment]
修正ありがとうございました！！
もしよかったら別のissueなどもぜひ･･････！！
