### ISSUE TITLE
vvpp 読み込みを設定後、起動時に毎回「追加キャラクターの紹介」ダイアログが出る

### ISSUE THREAD

**Issue by PickledChair** [VOICEVOX/voicevox#1117]
## 不具合の内容

エディタの 0.14.0-preview.4 が公開されたので vvpp 周りの動作確認をしてみました（SHAREVOX の Mac 版の vvpp をダウンロードして使いました）。vvpp の設定を行なって以降、起動時に毎回「追加キャラクターの紹介」のダイアログが表示されます。

### 現象・ログ

動画のように、vvpp の設定が行われているエディタにおいて、起動時に毎回「追加キャラクターの紹介」が表示される。

https://user-images.githubusercontent.com/41382894/212922122-e70b1123-618f-48c4-aeba-04feedc7334a.mp4

### 再現手順

1. [エディタの 0.14.0-preview.4](https://github.com/VOICEVOX/voicevox/releases/tag/0.14.0-preview.4)をインストール＆起動
2. [sharevox_engine の 0.2.0-preview.3](https://github.com/SHAREVOX/sharevox_engine/releases/tag/0.2.0-preview.3) で公開されている vvpp をダウンロードし、任意のディレクトリに配置
3. エディタ側で「エンジンの管理」メニューから追加のエンジンとして 2\. の vvpp を設定
4. 再起動を促すダイアログが出るのでボタンを押して再起動
5. 起動後、「追加キャラクターの紹介」ダイアログが出る（ここまでは想定通りの動作と思われる）
6. エディタを閉じる
7. もう一度エディタを起動する
8. 起動後、「追加キャラクターの紹介」ダイアログが出る（以後、起動のたびにこのダイアログが表示される）

### 期待動作

vvpp の設定後、初回の起動以外で「追加キャラクターの紹介」ダイアログが表示されないようになる

## VOICEVOXのバージョン

0.14.0-preview.4
0.14.0-preview.5

## OSの種類/ディストリ/バージョン

- [x] Windows https://github.com/VOICEVOX/voicevox/issues/1117#issuecomment-1385659192
- [x] macOS (macOS Monterey 12.6.2)
- [x] Linux https://github.com/VOICEVOX/voicevox/issues/1117#issuecomment-1385629169

**Comment by madosuki** [comment]
Windowsでは再現しませんでしたが、Linuxでも再現しました。
[https://semver.npmjs.com/](https://semver.npmjs.com/)でチェックすると、`>=1.0.0-rc`としないと`rc`のものが含まれないため、
https://github.com/VOICEVOX/voicevox/blob/main/src/background/configMigration014.ts#L32 のところも`0.14.0-preview`みたいにしてpreview文字列を入れる必要がありそうです。

**Comment by Hiroshiba** [comment]
詳細な調査ありがとうございます！！

configのマイグレーションが原因かもしれません。
今までは対応デバイスによって設定の保存場所が違っていたのですが、今回から旧DirectML版のとこに統一されました。
なのでCPU版を起動した時、旧CPU版の設定を読み込んでるかもです。

もちろん設定が0.14以上ならマイグレーションしないようにしてるのですが、プレビュー版だから壊れてるかもです…。
https://github.com/VOICEVOX/voicevox/blob/main/src/background/configMigration014.ts

（いっぱいログ出すようにしてるので、ひんとになるかもです🙇‍♂️）

**Comment by madosuki** [comment]
[https://github.com/madosuki/test_semver](https://github.com/madosuki/test_semver)
```JavaScript
const semver = require("semver");

const compareTargetArray = ["0.14.0-preview.5", "0.14.0"];
const compareTargetPreview = ">=0.14.0-preview";
const compareTagetRelease = ">=0.14";

for (const i of compareTargetArray) {
    const compareTargetPreviewResult = semver.satisfies(i, compareTargetPreview);
    console.log(`compare ${i} and ${compareTargetPreview} is ${compareTargetPreviewResult}`);

    const compareTagetReleaseResult = semver.satisfies(i, compareTagetRelease);
    console.log(`compare ${i} and ${compareTagetRelease} is ${compareTagetReleaseResult}\n`);
}
```
semverの判定が失敗してないか適当なコードを用意して確認してみました。
* 結果
```
compare 0.14.0-preview.5 and >=0.14.0-preview is true
compare 0.14.0-preview.5 and >=0.14 is false

compare 0.14.0 and >=0.14.0-preview is true
compare 0.14.0 and >=0.14 is true
```
`0.14.0-preview.5`文字列に対して`>=0.14`で判定を行うとfalseになることがわかりました。

**Comment by Hiroshiba** [comment]
なるほどです･････。preleleaseがある場合の指定方法がかなり厄介ですね･･･。
`>=0.14`ではなく`>0.13`が直感的かもですね。

と思って[semver calculator](https://semver.npmjs.com/)なるものがあったので試してみたのですが、これたぶん `0.14.0-preview.5` `>0.13` がfalseになりますね。。。
`includePrerelease`フラグを付けると良い･･･････？ https://github.com/npm/node-semver#prerelease-tags

**Comment by madosuki** [comment]
```JavaScript
semver.satisfies("0.14.0-preview.5", ">0.13", { includePrerelease: true })
```
でtrueになったので確かに`includePrerelease`をつけることで解決できますね。

**Comment by Hiroshiba** [comment]
おーーーなるほどです！！とりあえずこれで解決できそうですね！！

たしか関数名に「014」って入ってるので、ここの処理は
`semver.satisfies("0.14.0-preview.5", ">=0.14", { includePrerelease: true })`
とかのが良いかもですね。

せっかくなのでプルリクエストの作成をお願いしても良いですか･･･？

---
ついでのメモです。
プロジェクトファイルのマイグレーションとこも直さないとなと思ったけど、こちらは既に`includePrerelease`でした。
https://github.com/VOICEVOX/voicevox/blob/4a84ac75f9e19468a33d221bfdcde484d66501d1/src/store/project.ts#L105-L107

あと`electron-store`のマイグレーションもこのフラグ付けられるとよかったのですが、ライブラリ内なのでアクセスできなそうでした。
`electron-store`のマイグレーションは[他にも課題](https://github.com/VOICEVOX/voicevox/pull/1119#discussion_r1072277588)があるので、自前でやったほうが良いかもです。

**Comment by madosuki** [comment]
https://github.com/VOICEVOX/voicevox/pull/1123

PR出しました。
