### ISSUE TITLE
[Mac] ダークテーマの改良

### ISSUE THREAD

**Issue by kat0h** [VOICEVOX/voicevox#1132]
## 内容

Electronにはレンダラー側のカラーテーマとOS(Chromium)側のカラーテーマがあると思うのですが、Mac環境ではOS側のテーマが常にlightに設定されています。
https://github.com/VOICEVOX/voicevox/blob/d25d6ea1381b454f10dc8604fb7eff4b1062fd81/src/background.ts#L357-L358

これはmacOSの制約によるもので、(ref. https://github.com/VOICEVOX/voicevox/pull/621 )レンダラがライトテーマかつOSがダークテーマの時に信号機ボタンが見えなくなってしまうために実装されたワークアラウンドです。

PRが作成された当時はレンダラ側にライトテーマしか実装されていなかったため、このようなワークアラウンドが必要になっていましたが、現在はダークテーマが実装されたためレンダラとOSのテーマを合わせることで、OSのダークテーマも使うことが可能になっていると思います。

<img width="477" alt="スクリーンショット 0005-01-21 午後0 05 12" src="https://user-images.githubusercontent.com/45391880/213840968-0adde51d-b7dd-4168-988b-84712aed61be.png">
↑OSがダークテーマに設定されていてもChromiumのテーマはライトのまま

### Pros 良くなる点
見た目が改良される

<img width="480" alt="スクリーンショット 0005-01-21 午後0 18 56" src="https://user-images.githubusercontent.com/45391880/213841375-50b2e5e9-29af-4d29-a325-cc35b9483b20.png">
↑レンダラがダークテーマかつChromiunがダークテーマの場合、ウィンドウがバックグラウンドに回ってもボタンが正常に描画されている

### 実現方法

Electronの`nativeTheme.themeSource`をVOICEVOX側のテーマに追従させる。

## VOICEVOXのバージョン

d25d6ea1381b454f10dc8604fb7eff4b1062fd81 で確認

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [x] macOS
- [ ] Linux

## その他

自分で実装してみようと考えています。

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます
簡潔な詳細助かります、すごくわかりやすいです･･･！
