### ISSUE TITLE
キャラクターアイコンに付いているエンジンのアイコンの表示方法を変える

### ISSUE THREAD

**Issue by rokujyushi** [VOICEVOX/voicevox#1138]
## 内容

キャラクターのアイコンには、
エンジンの種類がわかるようにエンジンのアイコンの表示されています。

しかし複数のスタイルを持った同名のキャラクターがエンジン別に追加されると
現在はリストを開いた時しかどのエンジンのキャラクターなのか確認できないです。

確認し易いように現在選択中のスタイルが表示される部分にもエンジンのアイコンを表示して欲しいです。

![image](https://user-images.githubusercontent.com/93469977/213910909-e51dfdb8-7027-4631-b6cb-f09f37f2b335.png)

### Pros 良くなる点

別エンジンで同名の複数スタイルを持つキャラクターが追加された時
エンジンの種類を確認しやすくなる

### Cons 悪くなる点

特にないはず

## VOICEVOXのバージョン

0.14.0-preview.5

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

* Windows 11 Pro 64bit(21H2)

**Comment by Hiroshiba** [comment]
issueありがとうございます！
これは別エンジンで同キャラの別スタイルが実装されていることを想定しています！

**Comment by rokujyushi** [comment]
詳しい仕様についてよくわかってなかったのですが。
つくよみちゃんは別エンジンでもまとめられているんですね。
ただ、白痴ーさんやお星さんはSpeakerUuidが異なる？ので
別々に表示されてエンジンアイコンがないと見分けがつきにくいです。

![image](https://user-images.githubusercontent.com/93469977/214241579-d2aeb41e-9822-49a9-a4c1-d8f10fbf866d.png)

なので複数のスタイルを持つ場合でも以下のように表示して欲しいです。
![image](https://user-images.githubusercontent.com/93469977/214242216-cd994da6-134d-4c48-80d6-f7aab6b749b9.png)

**Comment by Hiroshiba** [comment]
@rokujyushi なるほどです！
そのとき、同一speakerUuidのスタイルがエンジンA・Bで実装されいている場合、エンジンA・Bどちらが描かれているべきでしょうか

**Comment by rokujyushi** [comment]
同一speakerUuidのスタイルがエンジンA・Bで実装されている場合はアイコンは表示しないのが良いと思います。

### 理由

- 片方のみのアイコンを表示するのはエンジンを正しく登録できていないと誤認させてしまいそうだから
- デフォルトでエンジンのアイコンを表示するようになればアイコンの無いものは複数のエンジン対応と認識しやすいと思うから

**Comment by sevenc-nanashi** [comment]
自分は重ねて複数ある感じにした方が良いと思います。（これはq-avatarのサンプルにあったコード）
![image](https://user-images.githubusercontent.com/59691627/214539148-4843fadc-a554-4407-bb95-8f90775243b3.png)

マルチエンジンを使わない人は今までとほとんど変わらない見た目になるべきだと自分は思っているので、デフォルトでエンジンのアイコンを表示するのは反対です（個人の感想）

**Comment by Hiroshiba** [comment]
お二人ともありがとうございます！！
２つだと表示しないのも、並べて表示するのもどちらもありだなと感じました！

そもそもアイコンを描いてるのは、どのエンジンを利用しているかユーザーがわかるにするためでした。
その意味でスタイル選択では必須だと思います（今のUI）が、キャラ選択時にアイコンが表示されるのはどっちでもいいんですよね。

もし実装プルリクエスト頂けるならマージします。
難しい場合は、なぜ「どのエンジンのキャラクターなのか確認」したいのか理由をお聞きできれば！
（最初にお聞きすべきでした🙇‍♂️）

**Comment by rokujyushi** [comment]
どのエンジンのキャラクターなのか確認したいのか理由については
エンジンアイコンがついていないと使いたいスタイルの選択が個人的に手間になるからです。

例えばSHAREVOXの白痴ーさんに今後複数スタイル追加が来れば以下のようになって一度リストの方を見る必要があります。
![image](https://user-images.githubusercontent.com/93469977/215457124-6d71340c-b5c3-4a30-bd6e-8d6bb4213bdb.png)

またこれは別問題だとは思いますが誤ってスタイルを選択した場合スタイル選択のスクロールの位置が上に戻るので、
選択のしやすさが必要だと思います。

**Comment by Hiroshiba** [comment]
@rokujyushi ありがとうございます、すごくよくわかりました！！

おっしゃる通り不便だと思います。
これはそもそも各音声ライブラリの話者IDが同一でないことに起因しています。
そのキャラクターライブラリを運営されている方にご連絡して話者IDを揃えて頂くのが良いのかなと思いました。

選択のしやすさについては課題点と（あれば）解決策をissue化して頂ければと思います！
