### ISSUE TITLE
EngineId、SpeakerId、StyleIdそれぞれにユニークな型を作る

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1148]
## 内容

EngineId、SpeakerId、StyleIdはそれぞれstring, string, numberですが、別の文字列を代入してしまったりしてもコンパイルエラーが起こらないので気づきにくいです。
EngineIdにはEngineIdしか入れられないような型を作りたいです。

### Pros 良くなる点

コンパイル時にミスに気付ける

### Cons 悪くなる点

どう宣言すれば良いのかわからない

### 実現方法

可能ならRecordやArrayに含めたとき、その型ではない値を入れようとすると型エラーになって欲しいです。
[こちらの例](https://qiita.com/sdkei/items/494bd839d6986b40937d#%E5%AE%9F%E8%A3%85%E4%BE%8B)が良さそうに感じました。

```ts
declare const EngineIdSymbol: unique symbol; // ダミーのシンボル
type EngineId = string & { [EngineIdSymbol]: never };
function EngineId(id: string): EngineId {
  return id as EngineId;
}

// ちゃんとエラーになる
const table: Record<EngineId, string> = {
  [EngineId("engine-id-0")]: "hoge",
  ["engine-id-1"]: "hoge",
};
console.log(table);
```

<img src="https://user-images.githubusercontent.com/4987327/214636621-a89fb94b-5111-40f5-8b62-fbfe670348d3.png" width=400 />

## その他

あとzodで扱えると嬉しそう。

型に詳しい @yamachu さんや @Segu-g さんの意見ももしよかったら聞けると嬉しいかもです！

**Comment by Hiroshiba** [comment]
zod対応したものを作ってみました！！
```ts
import { z } from "zod";

const EngineIdSchema = z.string().uuid().brand<"EngineId">();
type EngineId = z.infer<typeof EngineIdSchema>;
const EngineId = (id: string): EngineId => EngineIdSchema.parse(id);

const table: Record<EngineId, string> = {
  [EngineId("engine-id-0")]: "hoge",
  ["engine-id-1"]: "hoge",
};
console.log(table);
```
<img src="https://user-images.githubusercontent.com/4987327/214644447-6d712468-2b6c-4ab5-97b5-a2c9dfa0ef42.png" width=400 />

**Comment by yamachu** [comment]
Symbolを使って型を作る例はそこそこ見るのと、こういうアプローチでいいんじゃないかなと思います :+1:

この文字列（EngineId）の生成箇所（例えばJSON.parseする箇所みたいな）以外では `as EngineId` する関数を使わないだったり、
`someObj?.someProperty ?? engineId` みたいに単なるstringを使おうとしてなかったら…みたいな異なる型を使わないみたいのを縛れたらより良さそうですね。

そこまでやらなくても、今のコードベースの

```ts
const hoge  = (engineId: string): any => {}
```

よりも意図は伝わりやすくはなりますし、

```ts
type EngineId = string;
const hoge  = (engineId: EngineId): any => {}
```

よりも安全側に倒れるので、とりあえず進めて良さそうに思えました。

**Comment by Hiroshiba** [comment]
- https://github.com/VOICEVOX/voicevox/pull/1211

でStyleIdもブランド型にするPRを出しました！
これが完了すればこのissueはcloseだと思います。

一方でまだ型にしたいstringがあることに気づいたのでissue化しておきました。

- https://github.com/VOICEVOX/voicevox/issues/1210
