### ISSUE TITLE
行番号を表示するオプション機能をつける

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1149]
## 内容

行番号の要望を数回頂いたのでメモです。
https://twitter.com/DokuroRoudoku/status/1618267090867351552

大多数の人にとってはいらなそうですが、長い台本を１つのプロジェクトファイルでやるタイプの方には有用だと思います。
デフォルトはオフにし、設定で表示の有無を変えられると良さそうです。

### Pros 良くなる点

人によっては効率が上がる

### 実現方法

設定ファイルに保存したりする処理の流れは`currentTheme`辺りが近いかもです。
https://github.com/VOICEVOX/voicevox/blob/d053d9837a1ace7dbbb26cd0d9af2066a6f6844b/src/type/preload.ts#L499
## その他

行番号をどういう感じに表示するかはいろいろやり方があると思います。
取り組む前にどういうの目指す予定かコメント頂けると助かります。

**Comment by wappon-28-dev** [comment]
## 目指す予定
イメージをささっと作ってみました.  こんな感じでどうでしょう？

<image src="https://user-images.githubusercontent.com/86721991/228331962-c75242ed-b59a-457b-a67c-9b95f866bc6a.png" width="600px"/>

### レイアウト
1. 緑の矢印 ([`arrow_right`](https://github.com/VOICEVOX/voicevox/blob/main/src/components/AudioCell.vue#L3-L9)) は, 動かない左側へ
     - デフォでオフなので, できるだけ変えない
2. セレクトされている行の行番号:
     - 色: 緑の矢印と同じ色 (たぶん [`colors.$primary`](https://github.com/VOICEVOX/voicevox/blob/main/src/styles/colors.scss#L1))
     - 太さ: bold
     - 不透明度: 100%
3. セレクトされていない行の行番号:
     - 色: テキストと同じ色 (たぶん [`colors.$display`](https://github.com/VOICEVOX/voicevox/blob/main/src/styles/colors.scss#L7) or inherit)
     - 太さ: normal
     - 不透明度: 60% くらい？ (text と比べてさほど重要ではないため)

### フォント
行番号で使うなら, 等幅フォント (Rounded M+ 1c とか) を別に用意したほうが良いのでは？と思ったけど,  
Rounded M+ 1p と Roboto (VOICEVOX で フォントを ”OS標準” にしたときのフォント) の数字の幅が  
おそらく均一なので, `<pre>` で囲わずに `<p>` (Rounded M+ 1p/Roboto のまま) でいけそうです.

<image src="https://user-images.githubusercontent.com/86721991/228335429-67ddb09b-0afc-4e3f-916a-03e67550822e.png" width="600px" />

## 疑問点
1. [緑の矢印, 行番号, キャラクター選択, テキスト] の順番で良いか
   
2. 色をできるだけ動的にしたが...  行番号が少し見づらいかもしれない (ダークテーマも含め要検証)
  
3. 行番号の幅 (１枚目の画像で赤く括った部分) は, どのように取るか
   1. 数字３桁入るくらいの幅で固定
   2. 一番大きな桁数に合わせて幅を変える
   3. 基本 i) で, ４桁以降は ii) のようにする (VSCodeが確かこの挙動だったかも)
   
4. 上記のように, 行番号はテキストと同じフォントで良いか


が疑問に思った点です  どうでしょう？  ご意見よろしくお願いします！

**Comment by Hiroshiba** [comment]
疑問点、提案全て同意見なので問題ないと思います！！！
疑問点３は、iiiのVSCodeと同じ挙動が確かに良さそうに思いました！
サイズや不透明度等、不自然だったら適宜揃えていたければ！！

丁寧に進めていただけて嬉しいです、ありがとうございます！
