### ISSUE TITLE
electron-storeから離脱する

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1156]
## 内容

VOICEVOXは設定の読み込みにelectron-storeを用いています。
electron-storeはいくつか問題があります。

1. 設定の読み込みロジックに一貫性がない
    * root直下かそうじゃないかで読み込みロジックやデフォルト値の扱いが異なるため不思議な挙動になります
3. マイグレーション前にバリデーションをかけてしまう
    * このため古いconfig.jsonを最新のスキーマでvalidateしてしまいエラーになります
4. 型サポートが微妙
    * set/getがdotnationに依存していてちょっと型サポートがおかしくなることがあります

しかしマイグレーションができることや、ネストされたオブジェクトをにもいい感じに代入できるのは強いです。
良い移行先があると嬉しいです。

### Pros 良くなる点

不思議な挙動に付き合わなくて良くなる

### Cons 悪くなる点

移行先が見当たらない

### 実現方法

自分たちで実装するのもありかもです。
マイグレーションはそんなに難しくないとして、ネストされたオブジェクトにどうやってアクセスするのかが課題になるかもです。

コマンド周りの実装で使った`JSON Patch`という概念が役立つかも･･･？

## その他

移行先がなかなか見つからない･･･。

**Comment by yamachu** [comment]
データストアに
https://github.com/typicode/lowdb
みたいなJsonベースのオブジェクトをストアするライブラリを採用するといい感じだったりしますかね。
Node上だとfilePathを指定してjsonファイルを書き出して、ブラウザだとlocalStorageなどに吐き出すようです

schemaの検証などは自前で実装する必要はあるのでそこは頑張りが必要そう…

値の書き換えなどは確かにJSON Patchを使ったり
https://github.com/debitoor/dot-prop-immutable

. でパスを繋げてpatchを当てるみたいのを使うか、
もしくは当該パスに存在するのがArrayかObjectかScalarかみたいのを判定して潜っていく感じのを自前実装……でしょうか

**Comment by Hiroshiba** [comment]
`lowdb`、良いですね！！

> dot-prop-immutable

なるほどです、便利そう。
欲を言えばTypeScriptの型周りのサポートを借りられると嬉しいかもとちょっと思いました。
