### ISSUE TITLE
サンプリングレートが異なるとモーフィングがプツプツする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1169]
## 不具合の内容

モーフィングがプツプツするという報告をいくつかいただいています。
原因はサンプリングレートっぽいということを突き止められた方がいたのでメモです。
https://twitter.com/Uotsumi/status/1620474971637301249

### 現象・ログ

モーフィングがプツプツする

### 再現手順

サンプリングレートを48000Hzとかにする？

### 期待動作

プツプツしない

## その他

出先なので再現試していないけどとりあえずメモです

**Comment by y-chan** [comment]
VOICEVOX/voicevox_engine#622 にて解決されているため、closeします
