### ISSUE TITLE
MinimumEngineManifest格納時の検証を Zodで行う

### ISSUE THREAD

**Issue by nmori** [VOICEVOX/voicevox#1181]
## 内容
JSONデータをそのままパース・代入している点について
検証をおこなうべきという潜在的課題について解決を行う　ref #1179

### Pros 良くなる点
・変数内の状態が保証される

### Cons 悪くなる点
・特になし？

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by nmori** [comment]
現段階でなんとなく動くところまで　書くことができたのですが
1点、どう実装していいか分からない部分があります

```
export const minimumEngineManifest = z.object({
  name: z.string().default(""),
  uuid: z.string().default(""),
  command: z.string().default(""),
  port: z.string().default(""),
  supported_features: z.record(z.string(), z.boolean()),
});
```
supported_featuresは、文字列とbooleanの組み合わせという評価でよいか、
定義済みの構造に沿っているかをみるべきか？という点です。

後者の場合はクラスを指定するのかな？とおもいますが
ちょっとどのように表記表現してよいのかわかりません
(現段階での私の技量を超えていて、コードの表現方法が思いつかないです）

**Comment by Hiroshiba** [comment]
issue作成アリア等ございます！！

zodで使うには実態（文字列とか）が無いといけないのですが、定義済みなのは型（Type）なのでおそらく使えないと思います！
ちょっとむずいのですが、TypeScriptはts→jsにトランスパイルしていて、前者はjsの概念ですが、後者はtsだけにある概念です。
今回の場合`SupportedFeatures`として存在するのは型だけなので、ここでは`z.record(z.string(), z.boolean())`とするしか無いのかなと！

欲を言うと`supported_features`はcamelCaseにして`supportedFeatures`としたいですね！

**Comment by nmori** [comment]
すこしZodを勉強してみました。
手元のテスト段階では、おおよそ期待通りに動くように出来たと思うので
PR出したいと思います。

なお、変数名がJSONラベル名と一致していないと解析時にエラーとなったので
最小限の範囲でcamelCaseを適用せずに記述しました。

ちなみに、経験不足ゆえ、こういう場合のPRの出し方について作法を1つご教示頂きたく。

今回のは ref #1179 に関連するかたちですが課題が異なると思ってIssueをわけましたが、
1つを進行中で　関連するもう１つをPRする場合は、ローカルでブランチきって
該当する部分のみPRする感じがよいのでしょうか？（作業を並走したことがないものでして…）  

(部分的に作業がかさなっているので、コンフリクトします。分けない方がよかったですかね）

**Comment by Hiroshiba** [comment]
PRお待ちしています！！

作法についてですが、正直特に無いと思います！
ちなみに今回は新しいPRが前のPRを必要としないパターンですよね。２つともPR出しちゃっていただくのが良いのかなと！

**Comment by nmori** [comment]
ありがとうございます。
では、個別のPRという形でだしてみます。
