### ISSUE TITLE
キャラクター変更ショートカットキー

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1187]
## 内容

選択中のキャラクターを変更するショートカットキーがあると便利そうです。

ユーザーの声
https://twitter.com/Super_Polymeriz/status/1622937962744012800

### Pros 良くなる点

使いやすくなる

### Cons 悪くなる点

何のキーにするか難しい？

### 実現方法

「上からN番目のキャラクターにする」キーを用意するパターンと、
「次／前のキャラクターにする」キーを用意するパターンがありそう。

ショートカットキー一覧はこの辺りにあります。
https://github.com/VOICEVOX/voicevox/blob/a22046c731dbd88794a0e2e0d0a632b977bf5e29/src/type/preload.ts#L7

## その他

どのショートカットキーを割り当てればいいか難しそう。
AIVOICEとかボイロとかCeVIOが何のキーを割り当ててるかが参考になりそう。

**Comment by Hiroshiba** [comment]
ゆっくりムービーメーカーではctrl+上下キーとのことでした！
https://twitter.com/minminzemi_main/status/1653062839224139782

**Comment by Hiroshiba** [comment]
AIVOICEの「上から N 番目のキャラクターの選択」ショートカットキーはctrl/command + 番号でした！
https://aivoice.jp/manual/editor2/text_block.html#id3

**Comment by tsym77yoshi** [comment]
ちょっとずれるかもしれませんがプリセット切り替えの方をctrl/command + 番号にすればキャラクター切り替えも兼ねられるかもしれません
（M-gen様制作の voiceroid+の音声効果の切替をショートカットキーでできるようにするというAssistVRoidを参考にしました！
https://www.nicovideo.jp/watch/sm30754768 ）

10で足りない場合、
- ctrl/command + 番号：1~10個目まで
- ctrl/command + 上キー：11~20個目まで
- ctrl/command + 左キー：21~30個目まで
...

のように別のキーと組み合わせれば対応できそうです

**Comment by Hiroshiba** [comment]
@tsym77yoshi コメントありがとうございます！

プリセット切り替えにするアイデア、なるほどです！
現状プリセットは一部並び替えられない（デフォルトプリセットが並び替えられないはず）ので、もし実現する場合は仕様変更が必要かもです。
あとは別でプリセット切り替えショートカットを用意する手もあるかも？

１１番目以降のショートカットキーもなるほどです！
組み合わせるキーを何にするか迷いますね 😇 　ctrl＋上キーなどは他のショートカットをと衝突しそうかも。
とーりあえず１０種類（か９種類）だけ対応にし、要望が来たら増やすとかもありかも･･･？

もし実装にご興味あれば、ぜひ！！

**Comment by tsym77yoshi** [comment]
あ.プリセットの機能を勘違いしてました（キャラクターも切り替わるものだと勘違い）<(_ _)>

ctrl+数字でキャラクター切り替えする機能に自分の力でトライできるかやってみたのですがこの実装は良くなさそうです

hotkeyの方でトライしてみます！
