### ISSUE TITLE
貢献者ガイドラインに記載する事項

### ISSUE THREAD

**Issue by nmori** [VOICEVOX/voicevox#1190]
## 質問の内容
ref #1168 内で会話になった「貢献者ガイドライン」について。
今回体感したことをベースに、いったん書いてPR出そうと考えています。

記載するにあたり、
* 現時点でドキュメントに明記されていないルールがあれば教えてください
* 把握することがベストであろうコミュニティ上の文化、風習を教えてください
* これから参加する貢献者・開発者が押さえておくべき事項があれば教えてください
* PRするにあたり、「これが守られていれば査読者の負担が減る」事項があれば教えてください
* 遵守事項（Must）、推奨事項(Better) があれば教えてください

こちらで教えて頂いた内容もふまえて、ドキュメントにおこしてみます。

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by Hiroshiba** [comment]
> 現時点でドキュメントに明記されていないルールがあれば教えてください

いまのところ無いかもです！
あ、ルールじゃないですが、マージされるとVOICEVOXソフトウェアの更新履歴にコミッターのGithub IDが刻まれます。

> 把握することがベストであろうコミュニティ上の文化、風習を教えてください

定まってないですが、「相手にリスペクトを持ってコメントする」とかでしょうか･･･。
あとはよくある「差別しない」とか･･･？

> これから参加する貢献者・開発者が押さえておくべき事項があれば教えてください

こちらも特に思いつきませんでした。
`/docs`にある他のドキュメントは参考になると思います、くらいかなと！

> PRするにあたり、「これが守られていれば査読者の負担が減る」事項があれば教えてください

PR作った後に自分のPRの差分を見直してもらえると、負担が減るしPR作った本人も自分で成長できて良いかなと！
あとは、UIや仕様変更の際は先にissueを作って聞いてもらえると、手戻りが少なくなったりするかもです！

> 遵守事項（Must）、推奨事項(Better) があれば教えてください

こちらも今のところは用意してません。
（本当は[行動規範](https://docs.github.com/ja/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project)なども定めたほうが良いのですが、手が回ってない感じです 😇 ）

**Comment by nmori** [comment]
ありがとうございます。

上記の質問については、ほかにコード提供されている方や
反映作業に従事されている方からも情報を伺いたいので、
お気づきの点ありましたらよろしくお願い致します。

**Comment by nmori** [comment]
・思いつくまま、いったん文章にしました。
・そもそもこの形での記述がよいか、他に必要な部分、不要な部分、誤解などあれば教えてください
・もうちょっと議論で形ができれば、PRを出します。
・PRする段階では、トップページと情報が被っている部分も整理したほうが良いかと考えています。

**Comment by sevenc-nanashi** [comment]
個人の意見：PRで議論する方がレビューも書きやすいのでPRで議論してもいいと思います。

**Comment by Hiroshiba** [comment]
@nmori すごく丁寧でとても良いと思いました！！！！！
ぜひPR化していただければ！！

あ、書くにあたって参考にした資料などあれば知りたいかもです🙏

続きはPR側で議論しても良いかもですね！

**Comment by nmori** [comment]
お二方、ありがとうございます。
ファイルベースの議論に立ってよい、という感触なのでPRだしますね。

このあたりを参考にしましたが、
今回ワンサイクル回すにあたって足りなかったので、いろいろ追記しました。

* https://github.com/rails/rails/blob/main/CONTRIBUTING.md
* https://github.com/github/docs/blob/main/CONTRIBUTING.md
