### ISSUE TITLE
CI) markdownlint の検索範囲を広げる

### ISSUE THREAD

**Issue by nmori** [VOICEVOX/voicevox#1212]
## 内容

markdownlint で品質管理をしているが、現在はルートにある md しかチェックできていない
現に、public、docs 配下のファイルなどはいくつかルールに沿っていない記述があり、チェックをすり抜けている

### Pros 良くなる点

* markdown 表記が均一化されメンテナンスされやすくなる
* 記述エラーを見つけやすくなる

### Cons 悪くなる点

* 現時点でエラーが出ているファイルがいくつかあるので、これを直さないとテストが通過できなくなる
 
- [ ] ./docs/UX・UIデザインの方針.md
- [ ] ./docs/フォントについて.md
- [ ] ./docs/ミッション・バリュー・ビジョン.md
- [ ] ./docs/細かい設計方針.md
- [ ] ./docs/全体構成.md
- [ ] ./public/contact.md
- [ ] ./public/howtouse.md
- [ ] ./public/ossCommunityInfos.md
- [ ] ./public/policy.md
- [ ] ./public/privacyPolicy.md
- [ ] ./public/qAndA.md

### 実現方法

* GitHub Actrion スクリプトの修正　( `npm run markdownlint *.md `-> `npm run markdownlint ./*/*.md`)
* mdファイルの記述修正

## その他

* リクエストあればPRつくって提出する時間とれそうです

**Comment by Hiroshiba** [comment]
あ、docs内部はテストされてなかったんですね･････。

> リクエストあればPRつくって提出する時間とれそうです

ぜひお願いしたいです！！
もしあまりにも大変そうであれば僕もお手伝いできると思います！

**Comment by nmori** [comment]
織り込みありがとうございました。
