### ISSUE TITLE
`zod.string().uuid()`が厳密なUUID検査をするために、正確にはUUIDでないSpeakerIDを持つ話者を読み込めない

### ISSUE THREAD

**Issue by y-chan** [VOICEVOX/voicevox#1218]
## このIssueの目的

`src/electron/preload.ts`の14行目
```diff
-export const speakerIdSchema = z.string().uuid().brand<"SpeakerId">();
+export const speakerIdSchema = z.string().brand<"SpeakerId">();
```
この変更を適用するか議論したいです。

## 不具合の内容

Zodの導入により、`SpeakerId`型や`AudioKey`型など、今までstring型だったものが置き換えられ、より安全なコードが書けるようになっています。
さらにZodはUUIDに関してもバリデーションを行っており、正規表現を用いたバリデーションがなされています。

https://github.com/colinhacks/zod/blob/981af6503ee1be530fe525ac77ba95e1904ce24a/src/types.ts#L519

しかしその影響により、見かけ上UUIDだが、厳密にはUUIDでない文字列(ここでは簡略化のため、`UUIDもどき`と言います)がバリデーションに引っかかり、「データ準備中・・・」画面から動かなくなることがあります。
現状、VOICEVOXの話者は全て正しいUUID形式になっているため、特にエラーは起きていませんが、COEIROINKの話者である`MANA`を導入すると、UUIDが`292ea286-3d5f-f1cc-157c-66462a6a9d08`となっており、UUIDバージョン(3セグメント目の頭の値)が1〜5に収まっていない(`f`になっている)ために、バリデーションエラーが発生します。
UUIDの形式については[wikipedia](https://ja.wikipedia.org/wiki/UUID)におおよそ正しい情報が載っているので、ご参照ください。

これはVOICEVOX自体の問題ではなく、マルチエンジンに関する問題ではありますが、0.14.0では動くが新しくしたら動かなくなった、という報告はほぼ確実にユーザーから上がることになると思います。　

解決策として、`src/electron/preload.ts`の14行目を以下のように書き換えれば、UUIDとしての検証は行われなくなるため、問題は発生しなくなりますが、UUIDではない文字列を受け取る可能性を受け入れることになります。

```diff
-export const speakerIdSchema = z.string().uuid().brand<"SpeakerId">();
+export const speakerIdSchema = z.string().brand<"SpeakerId">();
```

ただ、そもそもとして`z.string().brand()`を使うモチベーションは、`SpeakerId`が入るべき場所には`SpeakerId`だけを入れたいと言った理由ではあるので、UUIDもどきやUUIDでない文字列を受けれるように書き換えることは大きく問題にならないかも？と思っています。

この変更を受け入れる場合、おそらく`uuid()`を入れている場所を全て統一して消すべきかなと思います。
合わせて、`uuid()`を使わない理由に関してコメントを書くべきでしょう。

### 現象・ログ

![image](https://user-images.githubusercontent.com/34832037/220098935-c8d8151c-f378-4421-b5e9-fb83733e6773.png)

https://github.com/VOICEVOX/voicevox/pull/1207#issuecomment-1435954164

### 再現手順

COEIROINKプレビュー版にMANAを導入し、その状態のCOEIROINKをマルチエンジン機能で`main`ブランチのVOICEVOXに導入する

### 期待動作

マルチエンジンを利用した際も、問題なく利用することができる

## VOICEVOXのバージョン

`main`ブランチ

**Comment by Hiroshiba** [comment]
詳細ありがとうございます！
以前はz.uuid()じゃなかったんですね！　であればuuid()を取ってしまうのが良いかなと思いました。

**Comment by Hiroshiba** [comment]
ちょっと確認してみたのですが、speakerUuidはもとからUUIDだった箇所がちょくちょくありました。[`defaultStyleIds`もuuid](https://github.com/VOICEVOX/voicevox/blob/release-0.14/src/type/preload.ts#L484)になっていました。


まあでも厳密にUUID4でなくても良いのは事実なので、緩めるのが良いと思います。
現在のコードでuuidとしてそうなのは以下４つです。（全体を`uuid(`で検索）

* engineIdSchema
* speakerIdSchema
* audioKeySchema
* presetKeySchema

このうち下２つはエディタが生成するものなので厳密にuuidでも良さそう･･･ですが、まあ[以前は`uuid()`にしてなかった](https://github.com/VOICEVOX/voicevox/blob/65a4465333e4c4963aa726d6cb8de7841ffedc13/src/store/project.ts#L424-L431)っぽいので、uuidにしないでおきますか！

PRを作成します。

**Comment by qryxip** [comment]
上記のZodのやつは見たところ[RFC4122](https://www.rfc-editor.org/rfc/rfc4122.html)に厳密に従っているっぽく、[V5](https://www.rfc-editor.org/rfc/rfc9562.html#name-uuid-version-5)以降とか[Max UUID](https://www.rfc-editor.org/rfc/rfc9562.html#name-max-uuid)とかも弾かれますね。まあ先月まで[正式](https://www.rfc-editor.org/rfc/rfc9562.html)ではなかったのですが。しかしそのRFC4122では以下のようなことが書かれています。

> ```
>    Validation mechanism:
>       Apart from determining whether the timestamp portion of the UUID
>       is in the future and therefore not yet assignable, there is no
>       mechanism for determining whether a UUID is 'valid'.
> ```

あとよく考えたら各言語のUUIDを扱うライブラリ/標準ライブラリでも、「不正」な128-bit値をUUID型として拒否する実装には私は心当たりが無いです。

ということでZodの方が変なのではと思ってZodの方を見たのですが、どうやらV1-V4 OR Nil UUIDしか受けつけない仕様は2023年8月にリリースされた[Zod v3.22.0](https://github.com/colinhacks/zod/releases/tag/v3.22.0)で撤回されているようです。
<https://github.com/colinhacks/zod/commit/37e9c550460e4edd144da90d903e878c119c5cc1>
