### ISSUE TITLE
electronのバージョンをどこまで更新するか

### ISSUE THREAD

**Issue by sousuke0422** [VOICEVOX/voicevox#1227]
## 内容

ref #1226

electron@20はEOLを迎えました。
このissueを建てた現在、21～23までが保守されています。
ただし23はchrome 110ベースのためWindows 7/8.1が[切り捨て](https://www.electronjs.org/ja/blog/electron-23-0#dropping-windows-7881-support)となっています。

### Pros 良くなる点

- セキュリティー的に良いはず
- 最新の機能が使える場合がある

### Cons 悪くなる点

- 23にするとWindows 7/8.1を切り捨て

### 実現方法

そこまで影響のありそうな破壊的変更はないのでバージョン上げるだけでいいはず

## VOICEVOXのバージョン

0.?.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！！

いったん22まで上げるのが良いのかなと思いました！
23化はもうちょっとギリギリでも良いかなと思いました。
フリーソフトであるという特性上結構昔の環境で使われている方も多そうなのと、他に移行したい理由もないためです。
（まあ一気にやったほうが楽ではあるのですが。）

21と22のリリースノートを見ていましたが、どちらも問題なさそうな気がしますね！
一気に22まで行くのも良い気がしました。
22に行くにはNodeのパッチバージョンを上げないといけないかも･･･？

**Comment by sabonerune** [comment]
エンジンで使用しているONNX Runtime v1.13.1がWindows7ではソースコードからビルドしないと動かないらしいので切り捨てられるのはWindows8.1だけかもしれない？

https://github.com/microsoft/onnxruntime/releases/tag/v1.13.1
>Windows 8.x support in Nuget/C API prebuilt binaries. Support for Windows 7+ Desktop versions (including Windows servers) will be retained by building ONNX Runtime from source.

**Comment by Hiroshiba** [comment]
- https://github.com/VOICEVOX/voicevox/issues/1360

こちらのissueでelectron 23以上にアプデするのが必要だとわかりました！
win8は申し訳ないけど正式非対応OSということで、23にアプデできると嬉しいです！

**Comment by Hiroshiba** [comment]
とりあえず判断は完了していいそう＆すでにサポートは切られてそうなので、closeします！
issue作成ありがとうございました！！
