### ISSUE TITLE
新しくキャラクターが追加されたとき、並び替えを無視して追加されたキャラクターが最初のAudioCellで選ばれている

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1229]
## 不具合の内容

新しくキャラクターが追加されたとき、並び替えを無視して追加されたキャラクターが最初のAudioCellで選ばれるようになっています。

### 再現手順

config.jsonの`userCharacterOrder`を適当に１つ消す（これを元に新キャラ判定しているため）。
その後起動し直す。

### 期待動作

並び替えの１番目のキャラクターが選ばれている状態にする

## その他

優先度は低くていいかなと思いました。

**Comment by Hiroshiba** [comment]
ちょっと調べたのですが、原因がわかりませんでした･･･。
あとに続く人へのメモ。

最初のAudioCellが作られてるのはここなはず
https://github.com/VOICEVOX/voicevox/blob/13a268c9c3f44571e9bf920b9f93eae8781a6df0/src/views/EditorHome.vue#L522-L527

で、最初のキャラクターはここで選ばれてるはず
https://github.com/VOICEVOX/voicevox/blob/13a268c9c3f44571e9bf920b9f93eae8781a6df0/src/store/audio.ts#L496-L497

なんですが、`USER_ORDERED_CHARACTER_INFOS`がなぜ新キャラがいるときに勝手に変わってる？のかがわからない･･･。

**Comment by madosuki** [comment]
`CharacterOrderDialog`が開かれた後、処理が止まらず`GENERATE_AUDIO_ITEM`まで進んでるみたいです。
`state.userCharacterOrder`に追加キャラクターが反映されるのは`CharacterOrderDialog`の完了ボタンが押された時なので、追加キャラクターが反映されていない状態で`USER_ORDERED_CHARACTER_INFOS getter`が実行されてしまい追加キャラクターのspeakerUuidはuserCharacterOrderに存在しないのでindexOfは常に-1になるため先頭に配置され、これを使ってAUDIO_ITEMが作られるので順序が想定しないものになっているようです。

このバグは初回起動時でも発生し、並び替えをしても四国めたんが選ばれた状態になります。

**Comment by Hiroshiba** [comment]
調査ありがとうございます！！！

な、なるほど？？？？？？？
いろいろと面白いことが発生していそうで、解決策もいろいろありそうですが、とりあえず存在しないものは選ばれないようにするのが良さそう･････？

**Comment by madosuki** [comment]
存在しないもの選ばれないようにしても初回起動時は四国めたん、追加キャラクター検出時は保存されている並び替えの先頭キャラクターが選ばれている状態になるので、起動時のAudioCell生成タイミングを変化させるのが良いんじゃないかと思います。
[https://github.com/VOICEVOX/voicevox/blob/main/src/views/EditorHome.vue#L516-L530](https://github.com/VOICEVOX/voicevox/blob/main/src/views/EditorHome.vue#L516-L530)
で生成が行われているので、並び替えダイアログが開かれている場合は実行しないようにして、並び替えダイアログ側で起動シーケンス中であれば完了ボタンが押された時にAudioCellを生成するようにすれば並び替えが反映された最初のAudioCellが生成されると思います。

**Comment by madosuki** [comment]
ただフォーカスさせる処理が難しそう

**Comment by Hiroshiba** [comment]
たしかにclose時に`AudioCell`を生成することで解決しそうに思いました。
ただそうすると`AudioCell`生成が２箇所に分散してしまうので可能なら１箇所だけにするのが良いかなと思いました！

代案ですが、順序が変更されたときに`AudioCell`が１つならmodifyする、みたいな方法もありかも･･･？
であればEditorHomeで`userOrdered`をwatchすれば実現できるかもです。
こうすれば例えば起動シーケンスが変わったときとか、キャラ順序を変える方法が増えたりした場合も思ったように動作するかもです。

**Comment by madosuki** [comment]
なるほど、そちらの方がシンプルで良いですね。
