### ISSUE TITLE
AudioInfoコンポーネントに表示されるパラメータの初期値や範囲を構造化する

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1244]
## 内容

話速などのパラメータは初期値や可動範囲が決まっていますが、そのマジックナンバーはいろんなファイルに点在しています。
それらをまとめて構造化することでわかりやすくできると思います。

↓デフォルト値

- https://github.com/VOICEVOX/voicevox/pull/1228

↓値域

https://github.com/VOICEVOX/voicevox/blob/bf48e8cd310824982886692bc014cc2c974498b3/src/components/AudioInfo.vue#L582

## VOICEVOXのバージョン

0.?.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by weweweok** [comment]
試してみます。このような想像をしています。
```
/**
 * 話速パラメータの定義
 */
export const speakerSpeed: {
  MAX: () => number;
  MIN: () => number;
  STEP: () => number;
  SCROLLSTEP: () => number;
  SCROLLMINSTEP: () => number;
} = {
  MAX: () => 2,
  MIN: () => 0.5,
  STEP: () => 0.01,
  SCROLLSTEP: () => 0.1,
  SCROLLMINSTEP: () => 0.01,
};
```

![image](https://github.com/VOICEVOX/voicevox/assets/100256521/0b8f329d-8726-4b72-a7db-b3607b0aa28e)

**Comment by Hiroshiba** [comment]
良さそうです！！
定数になってる変数だけラージスケールにして、プロパティーチの方は普通にキャメルケースでも良いかもと思いました！（色々派閥がありそうですが）

その例だとこんな感じ･･･？

```ts
export const SPEAKER_SPEED: {
  max: () => number;
  min: () => number;
  step: () => number;
  scrollStep: () => number;
  scrollMinStep: () => number;
} = ...;
```

**Comment by weweweok** [comment]
各パラメータをどこで定義するか考えました。

## 既存のファイルに仕込む方法
- 定数が使用されるファイルに直接定義 
- store/ui.ts に定数を定義
(数値とはいえ、このissueによって定義された定数は、UIの構成に関わっている?)

## ファイルを追加する方法
例えば、ファイル名: sliderPrameter.ts というファイルを作成して下記の方法を検討しています。
-  helpersディレクトリで作成->定数の定義
-  storeディレクトリで作成->定数の定義

**Comment by Hiroshiba** [comment]
一旦既存のファイルに書いといて、数が増えてきたらファイルを移動を考える感じで良いのかなと思いました！

どのファイルに書くかですが、挙げられている２ファイルどちらもありだなと思いました。
似たような`DEFAULT_AUDIO_FILE_BASE_NAME_TEMPLATE`というパラメータが`src/store/utility.ts`にあったので、これの近くに書くとかもありかもです！
https://github.com/VOICEVOX/voicevox/blob/a9144ea38fabbe5a3727b8bc90034b26d0e83c08/src/store/utility.ts#L46

**Comment by Hiroshiba** [comment]
多分解決しているのでクローズします！（ thx @weweweok !!! ）
