### ISSUE TITLE
デフォルトプリセット周りのリファクタ

### ISSUE THREAD

**Issue by k-chop** [VOICEVOX/voicevox#1247]
## 内容
https://github.com/VOICEVOX/voicevox/pull/1228 のPRがだいぶ長くなってしまったため、
クリティカルではないソースコード上の問題をいくつか残したまま [#1288](https://github.com/VOICEVOX/voicevox/pull/1228) をマージしていただく予定です。
そこで残した問題を解決するissueです。引き続き @k-chop が取り組みます。

### 問題一覧
- **mutation内で渡した引数を直接書き換えているコードをどうにかする**
   - https://github.com/VOICEVOX/voicevox/pull/1228#discussion_r1129821236
   - 同コメントのツリー内に修正方針をコメント済み
- **`determineNextPresetKey` の引数を整理する**
   - https://github.com/VOICEVOX/voicevox/pull/1228#discussion_r1125717135
- **defaultPresetか判定する関数がcomposablesに存在するが、vuexでも同様の判定をしていて重複している**
   - https://github.com/VOICEVOX/voicevox/pull/1228#discussion_r1131799080
   - getterにO(1)で判定できるようにしたデータの中間表現を置いて、それを使って判定できるようにすると良さそう
   - composablesはコンポーネント上の処理を適切な粒度で切り出せる先としてぜひ使ってほしいので、上記措置で内容が薄くなってもそのまま残す...残したい...

## VOICEVOXのバージョン
latest

**Comment by Hiroshiba** [comment]
issue作成もありがとうございます！！

**Comment by k-chop** [comment]
元PRのやりとりが超長かったので、対応してないまま忘れてる問題がないか再度チェックしたものメモ：

----
https://github.com/VOICEVOX/voicevox/pull/1228#issuecomment-1444083828
> ↑の仕様にすると、プリセット値に戻らないことが不便かもなので、「プリセット値に戻す」機能があると良さそうかなと思いました。
これは別issueが良いかも･･･？（アイコン選びなどが必要そうなので）

UIが難しそう
別issueにしておいた方がよさそう

----
https://github.com/VOICEVOX/voicevox/pull/1228#issuecomment-1445045328
> パラメータ引き継ぎ の対象にプリセットも含む

これ周知が必要かも？
次リリースverまでに「今までの挙動」に合わせられるようなオプション追加しておくべきか？
それとも↓で解決できるか？

----
https://github.com/VOICEVOX/voicevox/pull/1228#issuecomment-1445441061
> このPRではオーバーな気がしますが、理想としてはコピー時・キャラ変時の挙動を別々に選んでカスタマイズできるようにするのが良いのかなと思いました。
> たぶん、望まれる処理はパラメータ↓の４パターンを選べることかなと。

> - 引き継ぐ
> - デフォルト値に戻す
> - デフォルトプリセットを適用する
> - コピーしてプリセットを適用する
> これをコピー・キャラ変でそれぞれ選べる、みたいな･･･。

これ次リリースまでにあった方が良い？
今まで台本読み込んだときにプリセット1つずつ当てるのつらい→最初のアイテムにプリセット当ててから読み込めば全部それが当たるよ！！という案内を何度か観測している
次リリースで「パラメータ引継ぎがOFF」の場合はデフォルトプリセットが当たるようになる
パラメータ引継ぎOFFで今までと同じ操作をしようとしたときできなくなるユーザが現れそう

「コピー」はユーザに伝わらないので適切なワードを選ぶ必要がある
（＋ボタンを押したときは「コピー」されるが、AudioCellをコピーしているというのは開発者しか知りようがない）

----
https://github.com/VOICEVOX/voicevox/pull/1228#discussion_r1125729287
> 今確認したらリリースされてました！！ 🙌
> https://github.com/colinhacks/zod/releases/tag/v3.21.0
> （直すのは別PRが良さそう感）

これ別PRで試してみたのですが直ってなさそう・・・？（Partialついたまんまでした）
忘れそうなので別issueにしとくのがいいかも

----

**Comment by Hiroshiba** [comment]
> これ周知が必要かも？

パラメータ引き継ぎの仕様変更の周知に関して、とりあえずリリース段取りでメモってるとこに追加しておきました！
https://github.com/VOICEVOX/voicevox_project/discussions/22

> これ次リリースまでにあった方が良い？

あーーー。
パラメータ引き継ぎの仕様変更にこまる方がいるかもなので、あった方が良さそうに思いました。
マストではない･･･かなぁ･･･。うーん。
あったほうが絶対便利に思いました。

> テキスト読み込みや長文コピペしたときに、どのキャラとプリセットを選択するか選べるUIが出てきたら便利かも？

便利だと思います！
一方で、プリセットを使う人＆コピペやテキスト読み込みを用いる人が対象なので、どれくらいのニーズがあるのか（優先度）が読めなそうだけど、変更量が結構大掛かりになっちゃうなーーーと思いました。
そう考えると、ほしいのはもしかしたらプリセットを一括で変更する機能かも･･･？

> これ別PRで試してみたのですが直ってなさそう・・・？（Partialついたまんま）

謎ですね。。。
もしそうだったらしれっと戻すPR出しますか！

**Comment by k-chop** [comment]
雑メモのまま直さず忘れてしまってました...失礼しました 🙇 

----

> パラメータ引き継ぎの仕様変更にこまる方がいるかもなので、あった方が良さそうに思いました。

了解です！issue立ててさっと取り組んでみます。
設定UI作ったらdetermineNextPresetKeyの中で設定値見て分岐するだけなのでそれほど重くはなさそうです。
- AudioItemのコピー時は「コピーしてプリセットを適用する」
- ボイス変更時は「引き継ぐ」

でたぶん現行と同じ操作になるはずという認識...

> どれくらいのニーズがあるのか（優先度）が読めなそう

あーーたしかに！
twitter見ててその話してる人がそこそこ見つかるので、これ結構使う人が多いのか～需要あるのかな？と思ってたんですが、
単にそれを使ってる人が困りごとに当たって発信しやすかっただけで、ニーズがでかい訳ではなさそうな気もしますね。
ひとまずおいとこうと思います。

> zodのやつ

ちょっと実験してみたのですが、
現verのzodでもrecord自体のinferは特に問題なかったようです。
objectやarrayの子になると謎のPartialに包まれる感じでした。
このinfer結果はVOICEVOXが使ってる現verも、Hiroshibaさんの対応が入った最新版も変わらなかった...
ZodObjectはだいぶ複雑で修正沼りそう 😇

![aaa](https://user-images.githubusercontent.com/241973/230123099-0830e13a-c206-4ff8-8896-52837af05b46.png)
このinfer結果は現ver(3.20.2)のものです

**Comment by k-chop** [comment]
issue立てました

- https://github.com/VOICEVOX/voicevox/issues/1280

**Comment by Hiroshiba** [comment]
> ちょっと実験してみたのですが、
現verのzodでもrecord自体のinferは特に問題なかったようです。
objectやarrayの子になると謎のPartialに包まれる感じでした。

おお･････。なるほど･･････････････。
