### ISSUE TITLE
音声ライブラリを同梱しない提案  

### ISSUE THREAD

**Issue by Coro365** [VOICEVOX/voicevox#1251]
類似の issue が開いており、その作業が進行中の時期に恐縮ではありますが、類似の issue で触れられていない点も解決するために、 既存の提案と異なる方法を提案します。  
この方法がより多くのメリットをもたらすと思います。  

## 方法  
1. Webサイトなどで音声ライブラリのZIPファイルを配布する  
1. ソフトウェアに音声ライブラリをインポートするボタンを追加する  

ブラウザ拡張機能の追加と同じ様な自由でシンプルな方法が良いと思います 。  
この提案を広く議論していただければ幸いです。  

Thank you!  

---
 
この issue は以下の issues と関連しています  
- [ソフトウェアの初期容量を減らすために音声ライブラリをUIでダウンロードできるようにする · Issue #830 · VOICEVOX/voicevox](https://github.com/VOICEVOX/voicevox/issues/830)  
- [議論：ライブラリダウンロードAPIについて · Issue #536 · VOICEVOX/voicevox\_engine](https://github.com/VOICEVOX/voicevox_engine/issues/536)  
- [音声ライブラリを管理する機能をサポートする · Issue #21 · VOICEVOX/voicevox\_project](https://github.com/VOICEVOX/voicevox_project/issues/21)  

## メリット  
- 製品版、OSS版という区分を無くすことができる  
  - 現在、どちらも VOICEVOX という名前なので混乱をきたすように思います  
  - VOICEVOX という単語の前に製品版またはOSS版という単語が無い場合、どちらについて話しているのか明確に見分ける方法がありません  
  - 一般的にOSSをOSS製品と表記することもあるため、製品版、OSS版という区分名はわかり易いとは言えないように思います
  - 他の解決方法として、Google Chrome に対しての Chromium の様な別の名前を OSS版VOICEVOX に与えるという方法もあると思います  

- 自作の音声ライブラリを作成、使用するための布石になる  
  - 自分の声を自分だけが使いたい場合などに有益です  
    - 地声での解説系動画作成者が自分の音声ライブラリと VOICEVOX を使って音声収録作業を廃止したい場合など  

- 音声ライブラリに起因するロックイン効果を抑制する
  - 音声ライブラリと読み上げソフトウェアを分離することで、「音声ライブラリA を使うには 読み上げソフトウェアα を使わなければならない」といった事象を解消し、人々が読み上げソフトウェアの選択肢を狭めてしまうのを防ぐ

- 音声ライブラリの著者が報酬を得やすくなる  
  - 音声ライブラリの流通が自由になれば BOOTH や物理メディアなどの形で販売できるようになる  
  - BOOTHなら 0円、100円、100円+チップ といった選択肢を提示することで対価を得られ、音声ライブラリの増加やアップデート頻度の向上に繋がる可能性がある  

- ソフトウェアのファイル容量を小さく保てる  
  - 将来更に多くの音声ライブラリがソフトウェア内に追加され、許容できないほどファイル容量が大きくなってしまうのを防ぐ  
  - 大抵の利用者は全ての音声ライブラリを使うわけではないと思われるので、利用者のストレージを無駄に専有するのを防ぐ  
  - ソフトウェア配布者のネットワーク転送量を削減する  

- 利用者がこのソフトウェアをより理解できるようになる  
  - 利用者自身が音声ライブラリのダウンロードとインポートを行うことで、利用者の行為が音声ライブラリというデータを AI の力を借りて編集し、目的の音声データを得ている。ということを理解しやすくなると思います  
  - 任意の画像をフォトショップにインポートして目的の画像を得ているのと同じように  

## デメリット  
- 同梱された音声ライブラリが全くない場合、初めての利用者が混乱する可能性がある  
  - LGPL-3.0-only と互換性のある音声ライブラリを少量だけ同梱することで、前述したメリットを大きく損ねずにこの混乱を回避できると思います  

- 現在同梱されている既存の音声ライブラリの利用者が、その利用を継続する場合個別にダウンロードとインポートが必要になる  
  - 既存の利用者に手間が発生しますが、事前の告知とダウンロードとインポート方法の表示、当該音声ライブラリのダウンロード場所へのリンクを表示することで混乱は避けられると思います  

- 新しい音声ライブラリの利用を開始する度にダウンロードとインポートの手間が発生する  

## 音声ライブラリに適した LGPL-3.0-only と互換性のあるライセンスの例  
- Public Domain (PD)  
- Creative Commons Zero (CC0)  
- Creative Commons Attribution 4.0 (CC BY 4.0)  
- Creative Commons Attribution-Sharealike 4.0 (CC BY-SA 4.0)

**Comment by Hiroshiba** [comment]
issueタイトルにある「同梱しない」という方針は検討中です。
目的は容量下げで、最初にエンジンがなければダウンロードされる仕組みを考えています。

- https://github.com/VOICEVOX/voicevox/issues/1194

提案されているメリットデメリットに関して、最も大事なこのソフトウェアの主目的が抜けていそうでした。
[VOICEVOXのミッション・バリュー・ビジョン](https://github.com/VOICEVOX/voicevox/blob/a23a7ac59fd7648d556bbd63fb436a3faa5534f2/docs/%E3%83%9F%E3%83%83%E3%82%B7%E3%83%A7%E3%83%B3%E3%83%BB%E3%83%90%E3%83%AA%E3%83%A5%E3%83%BC%E3%83%BB%E3%83%93%E3%82%B8%E3%83%A7%E3%83%B3.md)

VOICEVOXをより良くしたい気持ちは一緒だと思います。
提案頂いたメリットが↑の視点を考慮して再提案いただければ･･･！！

一旦議論用のラベルを付けさせていただきます

**Comment by Hiroshiba** [comment]
ありがとうございます！！

ちょっと整理してみました。
（プロプライエタリが一切入ってないソフトのことを、VSCodeとCode-OSSになぞらえて仮に**VOICEVOX-OSS**と呼んでいます。）

* ChromiumとChromeの関係とはかなり異なる
	* ChromiumとChromeは片方だけインストールする
	* VOICEVOXはVOICEVOX-OSSをインストールしたあとVOICEVOXをインストールする
	* ので、VOICEVOX-OSSを配布すると、VOICEVOXが選ばれる割合は単純に下がるので価値観に反する
* VOICEVOX-OSSをリリースすることにより全体のユーザー数や技術力が増加するかどうか
	* リリースするだけでは何も変わらない
		* オープンにしていくという方針を打ち立てて宣伝していかないといけない
		* 以下は宣伝する前提
	* ユーザー数はたぶんほとんど変わらない
		* もうVOICEVOXとCOEIROINKがかなり界隈として大きいため
		* 今取れてない需要を取れれば話は別だけど、ここに注力するよりも言語を変えるなどのが効果のが大きそう
	* [マルチエンジン](https://github.com/VOICEVOX/voicevox_project/issues/2)よりも参入しやすさは増えると思うので、開発力（人数）は増加方向だとは思う
		* ここが前述の「VOICEVOXが選ばれる割合が下がる」ことに比べてプラスマイナスどっちなのかが分かれ目だと思います
		* 個人的には、微増か微減だと思っていて、だったら他のタスクを進めたいなと

以下はちょっと条件が追加された折衷案です。

* 今の製品版VOICEVOXを名称そのままに機能をVOICEVOX-OSSに寄せるのはあり
	* 意図はマルチエンジン機能の促進
	* VOICEVOXのキャラクターをインストールしなくても起動できるイメージ
		* 一番最初にVOICEVOXのキャラクターのレコメンドが入る
* VOICEVOX-OSSのメンテを８割くらい手伝ってくれる方がいたらあり
	* エディター、音声合成エンジン、音声ライブラリ、UI、UX、リリース、コミュニティ運営、ドキュメント作成、広報などなど
	* もちろん１人じゃなくても

まとめると、リスクがあるのにリターンが不明なので進められない（見極めに時間がかかる）、メンテを任せられるならリターンがわかりやすいので嬉しい、という感じです。

**Comment by Coro365** [comment]
唐突な提案ににもかかわらず、丁寧に返信頂きありがとうございます。  
 
VSCode について少し調べてみました。  

- VSCode (Code - OSS)  
  - 配布方法: **ソースコードのみ**  
  - ライセンス: MIT  
  - 配布場所: https://github.com/microsoft/vscode  
  - 配布者: Microsoft  

- Visual Studio Code  
  - 配布方法: **バイナリのみ**  
  - ライセンス: 非フリーソフトウェア  
  - 配布場所: https://code.visualstudio.com/  
  - 配布者: Microsoft  
  - VSCode を Microsoft がビルドし配布しているバイナリ  

- VSCodium  
  - 配布方法: **バイナリ** と **バイナリに対応するソースコードを VSCode から生成するためのシェルスクリプト**  
  - ライセンス: MIT  
  - 配布場所: https://github.com/VSCodium/vscodium  
  - 配布者: VSCodium  
    - 配布者VSCodium は Microsoft とは無関係です  
  - VSCode を 配布者VSCodium が編集の後にビルドし配布しているバイナリ  
  - これは VSCode から利用者情報をMicrosoftに送信する機能などを取り除いたソースコードをコンパイルしたバイナリだと思われます  
  - ただし、VSCode から ソフトウェアVSCodiumのバイナリに対応するソースコードを生成するためのシェルスクリプトも配布しています 

- 私の理解では、Visual Studio Code と VSCode は機能に違いは無いと思われます
- こういった複雑な命名と許諾環境は不必要に混乱を招きやすく、良き手本とは言えないように思われます  

---

- ここでは以下の単語を使っています
  - VOICEVOX-OSS
  - VOICEVOX-非OSS 
  - 1つに統合されたVOICEVOX

---

- 最初のコメントで Chromium を例に`別の名前を OSS版VOICEVOX に与える`としたのは次善策であり、この issue での主要な提案の方がより良いと思います

- この issue での主要な提案は、VOICEVOX-非OSS から 音声ライブラリなどの LGPL-3.0-only に適合しない要素を取り除き、利用者が後から個別に音声ライブラリを追加できるようにすることで、現在 VOICEVOX-OSS, VOICEVOX-非OSS の2つが存在するという状態を解消する。といった一連のメリットを得るというものです
  - この方法によってソフトウェアの許諾環境は明確になります
    - 明瞭なソフトウェアの許諾環境は利用者と貢献者(コントリビューター)の増加に繋がると思います
  - また、音声ライブラリの自由な流通によって音声ライブラリの数が増加し、その結果としてクリエイティブ・コモンズのような認知度のある明瞭な許諾を持つ音声ライブラリも自然と増加することを期待しています
    - 明瞭な許諾を持つ音声ライブラリの存在は、利用者の増加、特にビジネスでの利用増加に大きく貢献すると思います
    - また、日本語以外の音声ライブラリへの布石にもなりえると思います
    - これらはいま満たせていない需要を満たしえます

- `> オープンにしていくという(...)宣伝`についてですが、オープンソースが何なのか知っている人であれば、現在でも公式サイトで配布される VOICEVOX-非OSS がオープンソースだと誤認している人が多いのではないかと思います 
  - オープンソースを知っている人々は将来貢献者になる可能性が利用者一般よりも高いと思われる人々です
  - リリース当時、VOICEVOX のリリースを知らせるヒホさんのトゥートがブーストで流れてきて、私はこのソフトウェアを知ったのですが、その時に確認した公式サイトに GitHub のボタンがあり、そのリンク先の voicevox と書かれたリポジトリに LGPL のライセンスファイルを見つけて「ボイスボックスはオープンソースなのか！」と当時は思いました
  - これが誤認だったこと、VOICEVOX-OSS と VOICEVOX-非OSS の2つが存在することに気づいたのは、最近、長すぎる文章を自分の代わりに読んでもらうために VOICEVOX を使い始め、許諾環境を詳細に確認した時でした

---

確かに、音声ライブラリの流通を自由にすると他の無料の音声合成ソフトウェアも活発になり、1つに統合されたVOICEVOX は利用者の絶対数は増加しても、利用者数ベースのシェア率は現在のかなり高い水準よりも低下するかもしれません。
しかし、音声合成ソフトウェア群の利用者と愛好家、そしてオタク文化にとって有益なのは確かだと思います。

例えば、
「アーティストAのCDを再生するにはα社のCDプレイヤーが必要」、
「アーティストBのCDを再生するにはβ社のCDプレイヤーが必要」、
といった障壁があると音楽愛好家にとっては不便ですし、歌手にとっても、音楽という文化にとっても、恐らくは音楽産業にとっても良い影響はないでしょう。

また、シェア率が低下してもシェア率で1位になることは現実的に可能だと思います。
例えば、
現在の音声合成界隈全体の利用者数が` 10万人`で、この内` 7万人`が VOICEVOX の利用者でシェア率`70%`の状態から
将来の音声合成界隈全体の利用者数が`100万人`で、この内`60万人`が VOICEVOX の利用者でシェア率`60%`の状態に
なった場合、VOICEVOX の利用者数は増加し、シェア率は低下しますが依然としてシェア率1位ということになります。
つまり、ミッションとバリューを満たし、ビジョンにも衝突しないということだと思われます。

私が提案したような機能を備えた音声合成ソフトウェアを他の人が作るかもしれません、その場合提案したようなメリットはそのソフトウェアが享受します。
しかし、私は VOICEVOX に上記のメリットの最初の受益者になっていただけたら良いなと思っています。
私は VOICEVOX の幾つかのキャラクターの声が好きですし、VOICEVOX の利用者が作る作品が好きです。
もちろん、商業音声合成ソフトウェアのキャラクターも幾つか好きですが、開発企業にこの様な提案をしても取り合ってはもらえないでしょう。
車輪の再発明を避けられるのはオープンソースの長所ですし、そういった良い側面を活かしていただけたらと思います。
また、私自身が自由なライセンスの音声合成ソフトウェアと音声ライブラリを使いたいという動機もあります。

この提案は大きな方針変更を要すると思いますし、最終的に提案が退けられてもやむをえないと考えています。
ただその前に、広く議論していただければ幸いです。

**Comment by Hiroshiba** [comment]
提示いただいたメリットについてリスクと現実を書いてみます。

> 「アーティストAのCDを再生するにはα社のCDプレイヤーが必要」、
> 「アーティストBのCDを再生するにはβ社のCDプレイヤーが必要」、
> といった障壁があると

その障壁は既に取っ払いました。さっき言及したマルチエンジン化プロジェクトがそうです。
https://twitter.com/voicevox_pj/status/1620376485025685505

> 現在の音声合成界隈全体の利用者数が 10万人で、この内 7万人が VOICEVOX の利用者でシェア率70%の状態から
> 将来の音声合成界隈全体の利用者数が100万人で、この内60万人が VOICEVOX の利用者でシェア率60%の状態に
> なった場合

話が噛み合ってないです。
理想として割合が減っても母数が増えればプラスだというのは理解できますが、そもそもユーザーの母数はほとんど増えないと思うし、であれば割合は減る可能性はそのままリスクになります。

---

続いてご指摘いただいた内容にお答えします。

> Visual Studio Code

こっちが製品名なの初耳でした。
たぶんVSCodeにも「ややこしいと思います」というIssueがあると思うので、そちらが解決の糸口に繋がるかもと思いました。

> オープンソースが何なのか知っている人であれば、現在でも公式サイトで配布される VOICEVOX-非OSS がオープンソースだと誤認している人が多いのではないかと思います

過去に２回ほど似たご指摘を頂いたので、伝わるよう改善の努力をしています。

- https://github.com/VOICEVOX/voicevox_core/issues/23
- https://github.com/VOICEVOX/voicevox_resource/issues/16

[VOICEVOX Org](https://github.com/VOICEVOX)でわかりやすく案内をしているのはそういった経緯です。
@Coro365 さんが最初にVOICEVOXを知ったときと比べて、今はかなり違っていると思います。

---

音声合成ソフトのはコードとキャラクターの二人三脚なのですが、キャラクター側の需要がオープンソース思想と極端に相性が悪いという現実があります。
イメージを全くコントロールできないため、知名度がどうしても頭打ちになりやすいです。
VOICEVOXは「VOICEVOXを通じて 音声合成ソフトウェアや音声合成キャラクターをより身近なものにする」というミッションの都合上、多くのキャラクターたちと力を合わせることが必要で、絶対に無視できません。
そのため今すぐにキャラクター含めてオープンソースなソフトを目指すことはできません。

ただ、よりオープンにしたいという思想は僕の中にもあります。
例えば先ほどのマルチエンジン化はまさにそうですし、プロプライエタリ部分をなるべくコードから離しています。
VOICEVOXのうちコードの中で残っているプロプライエタリ部分は、[VOICEVOX CORE](https://github.com/VOICEVOX/voicevox_core)で製品版のみ行っている[暗号化処理](https://github.com/VOICEVOX/voicevox_core/issues/388#issuecomment-1398128605)だけなはずです。
ここさえ分離できれば製品版VOICEVOXのソースコードは完全にオープンソースになるため、その努力を多くの肩の力を借りて[現在行っています](https://github.com/VOICEVOX/voicevox_core/issues/280)。

現状、仮にVOICEVOX-OSSができたとしても、VOICEVOXがそれに対応できません。
なので、必要なのは議論ではなく、まず実装です。
この点に関して @Coro365 さんは強い関心があると思います。ぜひ一緒に開発しませんか。

---

最後になりますが、すごく正直なことをお伝えすると、OSSの理想を一方的に押し付ける言い方をされていてこちらの精神面で相当な負荷がかかっています。
オープンなものを作れると面白いはずだという考えと、VOICEVOXを良くしたいと思う気持ちは同じなはずです。
ややこしい、あるいは理想と違うというのはよくわかるのですが、もう少しこちらの考えに寄り添って考えていただけると幸いです。

**Comment by Coro365** [comment]
返信ありがとうございます。  
私が情報の整理するのに長くて数日の期間を頂戴して、その後返信させていただきたいと思います。  
この issue は提案であり、何かを強要する性質のものではありませんので、目安箱の投書くらの気持ちで気楽に受け取っていただけたら幸いです。

**Comment by Hiroshiba** [comment]
@Coro365 こちらどうでしょうか。
特になければcloseしたいと思います。

**Comment by Coro365** [comment]
最近急に忙しくなってしまい、返信が遅くなってしまい申し訳ありません。
また、ライセンス関係の話題はかなり複雑で難しく、しかも機微に触れる話題なので、心労をおかけしてしまったかと思いますが、それは私の本意ではありませんでした。

---

さて、まず最初にいくつは私が勘違いしていた点について述べさせていただきます。

- > VOICEVOX は OSS（オープンソース・ソフトウェア）版 VOICEVOX をもとに構築されています。  
  - 公式サイトにこの様な文があったので、OSS版 VOICEVOX というものがすでにあるのだと思っていたのですが、1つ前の返信で VOICEVOX-OSS の開発を勧められたとき、これが誤解であったと気づきました。
- この issue を開いた時点ではマルチエンジンとは [voicevox_engine](https://github.com/VOICEVOX/voicevox_engine) を同じ機能を持つ他のソフトウェアと入れ替えられるという話だと思っていたのですが、これは誤解だったようです。
  - 音声ライブラリと絡んでいるとは思っていませんでした。

また、VOICEVOX-OSS の開発のお誘いについてですが、有益に機能するいわゆる 製品版VOICEVOX は複数のライセンスの異なるソフトウェアと音声ライブラリから構成されるため Chromium や VSCode のケースよりかなり複雑で、どのように変更を加えると変更コストを抑えつつ、より良くなるのか私にはまだ分かりませんでした。
私は、このソフトウェアの実装や音声合成技術に特別詳しいわけではないため、このソフトウェアの実装を解きほぐし、理解し、適切な再構成を行うのは時間がかかりすぎますし、また、私の負うべき役割では無いと思います。

---

続いて、1つ前のコメントでご指摘いただいた懸念についてですが、
誰かが制御権を持っていないとキャラクターのイメージが全くコントロールできなくなるとは思いません。
例えば、浦島太郎や桃太郎などのキャラクターは すでにパブリックドメインかと思いますが、娯楽作品として広く親しまれており、キャラクター性も一定の形を保っているように思われます。

また、この issue の提案はは将来と既存の音声ライブラリの著作権の放棄(PD)や権利保留(CC BY)を**必須にする提案ではありません**。
その放棄や権利保留を著者の選択によって**可能にする提案です**
しかしながら、音声合成キャラクター界隈でクリエイティブ・コモンズが現在恐らく前例がないという点には同意します。
また、見落としていたデメリットとして、音声ライブラリが増加すると注目が分散するという欠点があるなと思いました。

とはいえ、この件でこれ以上 ヒホさんにご負担をおかけするのもはばかりがあるので、最後に現在の実情に即した情報提供についての提案をして筆を置こうと思います。

## 情報提供の改善提案

次善の策として触れた名称変更についての具体案について幾つか提案させていただきます。

- このエディターのリポジトリの名前(voicevox) を 公式サイトで配布しているバイナリの名前と区別できる名前を付けるのが良いと思います。
  - 以下に例を2つを示します。
  - voicevox => voicevox-editor
  - voicevox => voicevox-ui
- また、できれば、将来の商標などの問題を回避するために VOICEVOX という単語を完全には含めない方がより望ましい形だと感じました。
  - 以下にリポジトリ名の変更の1例を Chromium の例にならって示しておきます。
  - voicevox => voicevium-editor
  - voicevox-engine => voicevium-engine
  - voicevox-core => voicevium-core
- [公式サイトのオープンソースの項目](https://voicevox.hiroshiba.jp/#oss)を適切に編集したほうが良いと思いました。
  - 現在(2023-03)
  > オープンソース
  > VOICEVOX は OSS（オープンソース・ソフトウェア）版 VOICEVOX をもとに構築されています。
  > 製品版と OSS 版の違いやモジュール構成は VOICEVOX の全体構成 をご参照ください。
  > ソフトウェア部分は Electron + Vue 、音声合成エンジン部分は Python + FastAPI です。
  > 追加したい・改善したい機能があれば、ぜひ開発にご参加ください。
  > [:gh: VOICEVOX エディター] [:gh: VOICEVOX エンジン]
  
  - 改善案
  > VOICEVOX には以下のオープンソースソフトウェアが組み込まれています。
  > - voicevium-editor (LGPL)
  >   - アプリケーションのUI です (Vue.js)
  > - voicevium-engine (LGPL)
  >   - ここに説明を記入 (Python)
  > - voicevium-core (MIT)
  >   - ここに説明を記入 (Rust)
  > 追加したい・改善したい機能があれば、ぜひ開発にご参加ください。
- また公式サイトのフッターにある GitHub ボタンは[公式サイト自体のリポジトリ](https://github.com/VOICEVOX/voicevox_blog)にリンクするか、[プロジェクトのリポジトリ](https://github.com/VOICEVOX/voicevox_project)にリンクするか、あるいはボタンを取り除くと誤解の可能性を低減できると思います。

しかし、どれを選択するにしても、しないにしても、このプロジェクトの貢献者の方々と最終的にはヒホさんの [BDFL](https://ja.wikipedia.org/wiki/%E5%84%AA%E3%81%97%E3%81%84%E7%B5%82%E8%BA%AB%E3%81%AE%E7%8B%AC%E8%A3%81%E8%80%85) としての判断に委ねられることになるでしょう。

数度に渡り議論していただき、ありがとうございました。

**Comment by Hiroshiba** [comment]
フリーな音声ライブラリに関しては、私自身が手が回らないため誰か興味のある方に任せたいと考えています。
VOICEVOXとしては進められませんが、僕自身興味がなくはないので、個人として何かしら協力はできるかもしれません。

「voicevox => voicevox-editor」という提案はなるほどと思いました。
VOICEVOX全体を指してVOICEVOXであり、エディタだけを指してvoicevoxと呼んでいるのはたしかにややこしいです。
変更するかは未定ですが、参考にしたいと思います。

名称の変更については、貢献者の意欲に関わってくるため簡単には決められないと感じています。
正直僕自身かなり気が進まないので、このままにしたいと思っています。

最後に、あなたは「適切に編集」など、相手が間違っていると決めつけているような言い方をされていて、無自覚かもしれませんが相手を傷つけています。
そのことを自覚してほしいです。
