### ISSUE TITLE
プリセットを実験的機能から通常機能に上げる？

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1258]
## 内容

デフォルトプリセットが入った関係で、プリセットについてのオプションが増えました。

- https://github.com/VOICEVOX/voicevox/pull/1228

プリセットは実験的機能なので、更に入れ子で設定があるとちょっと表示がややこしかったりします。
もうプリセットは実験的機能から通常機能に上げるのはどうかなという提案です。

### Pros 良くなる点

表示がわかりやすい。

### Cons 悪くなる点

実験的機能でなくなるため、しっかりサポートが必要になる。

### 実現方法

「操作」辺りに移動するのが良いかなと思ってます。

## その他

@y-chan さん的にどうでしょう･･･？

**Comment by y-chan** [comment]
実装してから今まで大きくバグ報告は特になかったと思いますし、サポートの面は使い方説明を整えれば、そこの案内をするだけで済みそうな感じが(私は)しているので、そもそもプリセットをオプショナルな機能ではなくデフォルト機能にしてしまうのも良いかなと思いました。
設計的な部分はかなり簡素化できますし、UI的に非常に邪魔かと言われればそうでもないと思うので。
どうでしょうか？
(ついでに初心者歓迎タスクとして使い方の整備とかを勧めてもいいかもしれませんね)

**Comment by Hiroshiba** [comment]
たしかに使い方への詳細な追記は必要そうですね！！

デフォルトでONにすると、プリセット欄が一番上に表示される関係で、[デザインの方針](https://github.com/VOICEVOX/voicevox/blob/c3e90faaa756d6c79a59b90b1c170f252b270b23/docs/UX%E3%83%BBUI%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3%E3%81%AE%E6%96%B9%E9%87%9D.md)の

> あってもなくても良いような機能はなるべく目立たない UI にしています

に衝突しそうだなと思っています。
実際のところVOICEVOXを触って間もない方向けではなく、必要とする人の割合はそこそこ低そうなので、プリセットはデフォルトでOFFのままが良いのではと思いました。
（賛否両論ありそうだなとは思います。）

それとは別に、「スタイルごとのデフォルトプリセット」（というより「スタイルごとのパラメータ初期値」）だけは、デフォルトでONでも良いかもちょっと思いました。
まあ･･････それをUIでどう案内すれば良いのか相当難しいし、今はプリセット機能なのでここだけを切り出すのは相当大変なのですが･･･ 😇 😇 😇

**Comment by Hiroshiba** [comment]
> (ついでに初心者歓迎タスクとして使い方の整備とかを進めてもいいかもしれませんね)

なるほどです、こちらもありな気がしました！
