### ISSUE TITLE
、とか　・　などのデフォルトの長さはユーザが設定できればいいと思う。

### ISSUE THREAD

**Issue by ckjpn** [VOICEVOX/voicevox#1277]
、とか　・　などのデフォルトの長さ調節できたらありがたい。

example: トムは、ノートパソコンは持ってるよ。

・　はvoicevoxは無視したら、いいかもしれません。

example: この車はメイド・イン・ジャパンだ。

ジョージ・ワシントン
マイケル・ジャクソン

でも、...?

学校では、読み・書き・そろばんを習います。

**Comment by sevenc-nanashi** [comment]
https://github.com/VOICEVOX/voicevox/issues/740

これと関係してそう？

**Comment by Hiroshiba** [comment]
ですね！　重複しているのでcloseします。
（実際かなりニーズはあるだろうなーと感じます。）
