### ISSUE TITLE
アクセント辞書登録時に区切りを入れたい

### ISSUE THREAD

**Issue by maekawa-mugi** [VOICEVOX/voicevox#1279]
## 内容
現状のアクセント辞書機能では、「NTT東日本」などの複数の語で構成され、アクセントが決まっている単語を正常に登録できない。

「NTT東」と組み合わせた場合のみ日本の読みはニホンになり、最終的なアクセントはエヌティイティイ・ヒガシニホンとなるべきです。
「日本郵便」での日本はニッポンとなるため、「日本」を個別に単語登録することでは解決することができません。

それ以外の例では、「ソニーコンピュータエンタテインメント」なども登録できません。

この問題は、アクセントと読み仮名が語の組み合わせによって変化する場合があることに起因しますが、区切りを登録できるようにすることで、その両方が解決します。

### Pros 良くなる点
1. アクセント辞書において、語の組み合わせによってアクセントが異なる語が別々に登録できるようになる。
2. アクセント辞書において、語の組み合わせによって読み仮名が異なる語が別々に登録できるようになる。

### Cons 悪くなる点
ほとんどのユーザーはこのような語を単語登録しないため、多くの人々にとってUIが煩雑となる。

### 実現方法
未検討

## VOICEVOXのバージョン
0.14.6

## OSの種類/ディストリ/バージョン

- [x] Windows
- [x] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
起こってほしい条件の認識合わせをさせてください。
「NTT東日本」を「エヌティイティイヒガシニホン」として登録できそうですが、これだと問題解決が不完全ということでしょうか？
![image](https://user-images.githubusercontent.com/4987327/230021800-a13aa9fe-164c-4091-a654-19b7b3da7890.png)
![image](https://user-images.githubusercontent.com/4987327/230021751-32900cbf-bb99-4414-99ae-3b120a871f58.png)

**Comment by maekawa-mugi** [comment]
添付いただいた画像では、問題解決として不完全です。好ましいアクセントは添付画像のとおりです。
![ntt](https://user-images.githubusercontent.com/102278483/230024731-cd3dc0da-2a57-451e-ab65-7bc804655f24.png)

公式によるアクセントの例は以下のとおりです。
https://youtu.be/0DssWXh6N1g?t=28

**Comment by maekawa-mugi** [comment]
添付いただいた画像では、問題解決として不完全です。好ましいアクセントは添付画像のとおりです。
![ntt](https://user-images.githubusercontent.com/102278483/230026203-5bb3558c-7922-44af-a80e-311b681ccead.png)

公式によるアクセントの例は以下のとおりです。
https://youtu.be/0DssWXh6N1g?t=28

「NTT」「ひがしにほん」と単独で入力した場合は概ね正しくアクセントが生成されますので、
単なる単語登録ではなく、単語同士の独立性は残ったまま読み仮名を固定できるような、いわば「セット語」とでも言うべき概念が導入されるべきではないかと考えました。

**Comment by takana-v** [comment]
デフォルトの辞書では、このような「セット語」が存在しています。
（つまり、VOICEVOXが内部で使用しているpyopenjtalkのレベルでは対応しているということになります）
`笑止千万,1347,1347,4640,名詞,形容動詞語幹,*,*,*,*,笑止:千万,ショウシ:センバン,ショーシ:センバン,1/3:0/4,C1`
https://github.com/r9y9/open_jtalk/blob/1.11/src/mecab-naist-jdic/naist-jdic.csv

ただし、VOICEVOX Engineのユーザー辞書機能は、このような単語を想定していない作りになっています。
よって、この機能を実装する場合はエンジン・エディタの両方に改修が必要になるかと思います。

**Comment by Hiroshiba** [comment]
あ、なるほどです！！　とてもよくわかりました！
こちらの用語に合わせると、「一つの単語に２つ以上のアクセント句を登録したい」ということになりそうです。

@takana-v 
OpenJTalkは対応してたんですね、初めて知りました。

優先度は高くないかもですが、とりあえずエンジン側にissue建てると良さそうに思いました。
懸念点としては、望みの挙動がデフォルト辞書でなくコンパイルで作った辞書でもできるかとかでしょうか（できそうですが）。

**Comment by maekawa-mugi** [comment]
エンジン側にissueを作成しましたのでクローズさせていただきます。
