### ISSUE TITLE
EngineInfoの`host`を`url`に変える

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1297]
## 内容

EngineInfoという型にhostというのがありますが、実態はエンジンのURLです。
今後ややこしくてなにか不具合になるかもなので変えたいというissueです。

### Cons 悪くなる点

どこかに落とし穴があるかもしれない？

### 実現方法

.envの中も変える必要があるはず

## その他

- https://github.com/VOICEVOX/voicevox/pull/1267/files#r1153677210

**Comment by Hiroshiba** [comment]
あ、まだですね！
ここのメンバー変数をhostからurlに変更することを意図しています！

https://github.com/VOICEVOX/voicevox/blob/66cb02f8521e74eb647d37824968772a382bebb6/src/type/preload.ts#L335

**Comment by jdkfx** [comment]
```
protocol: string; // `http:`など
hostname: string; // `example.com`など
defaultPort: string; // `50021`など。空文字列もありえる。
pathname: string; // `/engine`など。空文字列もありえる。
```
現状の`EngineInfo`（抜粋）はこうなっています。
Issueは完了しているように見えるのですが、どうでしょうか？

**Comment by Hiroshiba** [comment]
あっ達成していそうですね！！
ご報告ありがとうございます、助かってます！！！
