### ISSUE TITLE
実際にポートが使用されていなくてもTIME_WAIT状態のポートを使用中と判定してしまう

### ISSUE THREAD

**Issue by sabonerune** [VOICEVOX/voicevox#1307]
## 不具合の内容

実際にポートが使用されていなくてもTIME_WAIT状態のポートを使用中と判定してしまいます。
そのためポートが使用中でなくても代替ポートに切り替わってしまいます。

### 再現手順

エディタを終了直後すぐにエディタを再起動する。

### 期待動作

他のアプリが使用中でない限り通常のポートで起動する。

## VOICEVOXのバージョン

5ce05b6cf7528ba18c21d57193092809cdc3a625 以降

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

## その他

Windows以外の挙動については把握していません。

**Comment by madosuki** [comment]
Linuxではこの現象は起きませんでした。
Windows11では同様のバグが発生します。

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！
関係ありそうなPRにリンクしておきます。

- https://github.com/VOICEVOX/voicevox/pull/1267

なるほどです、ポートの状態確認にはライブラリを使っても良いのかなとちょっと思いました。
メンテナンスが止まっていますが、[`portscanner`](https://www.npmjs.com/package/portscanner)あたりが良さそうかも？

あるいはnetstatのstateに応じて処理を変更するか･･･？

**Comment by Hiroshiba** [comment]
開発時に結構見かけることになりそうなので少し高い優先度を設定してみました！
