### ISSUE TITLE
追加エンジンのポートが切り替わっても接続するポートが切り替わらない

### ISSUE THREAD

**Issue by sabonerune** [VOICEVOX/voicevox#1310]
## 不具合の内容

追加エンジンのデフォルトポートが何かしらの理由で切り替わっても接続を試みるポートがデフォルトのままになっています。
これによりエンジン起動中のまま無限ロードになってしまいます。
#1308 とは異なりこの現象は初回起動時でも発生します。

### 現象・ログ

https://github.com/VOICEVOX/voicevox/blob/b49c3b5db8409c029e837fee288fe59e4600c7ee/src/background/engineManager.ts#L161-L164
上記のコードが原因で
https://github.com/VOICEVOX/voicevox/blob/b49c3b5db8409c029e837fee288fe59e4600c7ee/src/background/engineManager.ts#L270-L271
`engineInfo.host`の代入が反映されていない?
(詳細は未検証)

### 再現手順

追加エンジンのポートを何かしらの手段で塞いで起動する。

### 期待動作

実際に起動したポートに接続をして起動する。

## VOICEVOXのバージョン

b49c3b5db8409c029e837fee288fe59e4600c7ee 以降

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

## その他

Windows以外確認していませんがコード的にすべての環境で起こると思います。

起動時に追加エンジンのみポートの切り替えが起こるとタイトルバーに追加エンジンのポートが表示されまるでVOICEVOXのポートが追加エンジンの代替ポートであるように表示されてしまいます。

**Comment by Hiroshiba** [comment]
コード眺めて色々把握しました！　たぶんポートが切り替わらない点については可能性が２つほどありそうです。
１つは @madosuki さんの言う通りadditionalEngineInfosが再作成されている点、もう１つがVuex側にengineInfosが渡された後にポート変更が行われうる点です。

そもそも今ポートの流れはこうなっています。

- 起動
	- defaultEngineInfosメンバー変数がEngineManagerコンストラクタで作成される
	- start関数
		- fetchEngineInfos
		- createWindow
			- Vuex側からメインプロセスのengineInfos(.port)を`ENGINE_INFOS`でget
				- fetchEngineInfos（ここで別のadditionalEngineInfosが作成されてしまう）
		- runEngineAll
			- メインプロセス側のengineInfos内のport変更
- エンジン再起動
	- restartEngine
		- killEngine
		- runEngine
			- メインプロセス側のengineInfos内のport変更
		- Vuex側からメインプロセスのengineInfos(.port)をget（ #1311 マージ後）
- （ちなみに）アプリ再起動
	- killEngineAll
	- window閉じる
	- start関数

また、エンジン再起動時は変更後のportが入ったengineInfoが参照されるので、元のポートに戻ろうとしない気がします。

この解決策は色々ありますが、個人的には↓の３つの変更を行うのが良いのかなと思いました！

* engineInfoには「デフォルトのポート」を持つようにする（名前もportからdefaultPortとかに変えておく）
* Vuexからエンジンにリクエストするとき、engineInfo.portではなく、デフォルトポートとaltPortInfosを使ってリクエスト先のportを求めるようにする
* メインプロセス側のengineInfoを変更不可にしておく（事故防止のため）

他の方法としてはadditionalEngineInfoをメンバ変数にしてportを破壊的に変更するなどがあるのですが、それはそれでエンジン追加時にアプリを再起動させないといけなかったりの仕様変更が生じそうな気がしました。
であれば、engineInfoは不変な値ということにし、変更される可能性があるportだけ別管理するのが良いのかなと思った次第です。

**Comment by Hiroshiba** [comment]
あるいは、すべてのエンジンを起動し始める前に、すべてのエンジンでポートスキャンしてportを固定してからエンジンを起動し始める、というのもありかもです。
（こっちのほうがすっきりしそう）

1. 全EngineInfoを作成（defaultPortは埋まっていて、portにはとりあえずdefaultPortが入る）
2. 全エンジンで起動できそうなポートをスキャン、EngineInfo.port要素をを破壊的変更
3. UI起動
4. 全エンジン起動

みたいな感じです！
