### ISSUE TITLE
未起動状態でインストール済みエンジンのvvppインストールした際に更新されない

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1316]
## 不具合の内容

未起動状態で、インストール済みのエンジンのvvppをインストール（エンジンアップデートなどの用途）した際、アップデートされないっぽいです。
普通にインストールはできたのでリプレイスがされてない･･･？

### 現象・ログ

ログを確認したのですが、特に何も表示されていませんでした。

### 再現手順

1. バージョンAのvvppをインストール
2. VOICEVOX終了
3. バージョンBのvvppをダブルクリックしてインストール
4. （VOICEVOXが起動する）
5. エンジン管理からバージョンを確認するとバージョンAのままになっている

### 期待動作

バージョンBに更新される

## VOICEVOXのバージョン

0.14.6

## その他

VOICEVOX起動中にvvpp経由でインストールしようとするとちゃんとバージョンが更新されるので、未起動状態のときだけインストール経路が違うのかなとちょっと思いました。

**Comment by sabonerune** [comment]
根本的な原因は再起動フラグが立っていない場合`event.preventDefault()`を呼び出さないで`await vvppManager.handleMarkedEngineDirs()`を呼びだしているためそのままアプリが終了することだと思います。
https://github.com/VOICEVOX/voicevox/blob/f42d64a903fd1036075a4bea37d240b50d869c20/src/background.ts#L921-L927

これはエンジンを上書きや削除をして再起動ダイアログで再起動を行わない時に発生します。

エンジンを上書きする場合、そのままそのまま上書きせずに削除と移動の予約をするようになっています。
https://github.com/VOICEVOX/voicevox/blob/f42d64a903fd1036075a4bea37d240b50d869c20/src/background/vvppManager.ts#L269-L273

また、vvppから起動した場合`restartNeeded: false`で呼び出すためそもそも再起動ダイアログが表示されません。
https://github.com/VOICEVOX/voicevox/blob/f42d64a903fd1036075a4bea37d240b50d869c20/src/background.ts#L1030-L1033

**Comment by Hiroshiba** [comment]
@sabonerune おー！！ありがとうございます！！

とりあえずissueの方（未起動状態でvvppダブルクリックインストール）に関しては、再起動を促すようにするか、エンジン起動前に削除＆新規インストールすればとりあえず解決しそうですね！
後者のほうがエレガントですが、どう考えてもスパゲティ起動シーケンスになる（この経路だけ特殊なコードになる）のでまずそうです。
となると解決にはとりあえず再起動を促すのが良さそうかなと。

それとは別に、 @sabonerune さんのいう「再起動ダイアログで再起動を断るとエンジンがアップデートされない」のもまた問題だと思います！
こちらもissue作ってあげると良さそうですかね

**Comment by Hiroshiba** [comment]
こちらの課題に関してはあと再起動ダイアログを表示するようにすればOKなはず。（thx @sabonerune ！）

取り組んでみます！
