### ISSUE TITLE
AudioInfoのパラメータを直接入力しようとすると勝手に値がしてしまう

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1324]
## 不具合の内容

メイン画面の右側のAudioInfoのパラメーターは数値を直接入力することができます。
そこで例えば値を消そうとすると勝手に値がして0が入力されます。

いつからこうなったかは未調査です。
リリース済みの0.14では正しく動作することを確認済みです。

### 再現手順

パラメーターの数値欄を選択、文字を全部消去しようとする。

### 期待動作

エンターが押されるまでしない

**Comment by sabonerune** [comment]
すみません、 14a30bc60472b925ca8c22ee376b346a4eeaa548 のせいですね。
https://quasar.dev/vue-components/input
QInputに`@change`が定義されていなかったのでそのまま`@update:model-value`に置き換えたところ文字入力するたびに`handleChangeSpeedScaleInput`等の入力が終わった後に実行される関数が実行されてしまうようです。
https://github.com/VOICEVOX/voicevox/commit/14a30bc60472b925ca8c22ee376b346a4eeaa548#diff-21392cf965830cf5140c9f694b14d53ba51086d861e77b7a7b7a2f1384ed4e16L182-R182

**Comment by sabonerune** [comment]
調べ直したところQInputに`@change`がないと思い込んでいましたがネイティブの属性が使えるみたいなので`@change`のまま引数の型を確認するようにすればよかった感じでしょうか?
https://quasar.dev/vue-components/input#native-attributes

**Comment by Hiroshiba** [comment]
おお、なるほどです！！　原因わかって助かりました！！
ちょっと最適なのかquaser力足りなくてわからないのですが、とりあえずchangeにするのが良いのかなと思いました！！
