### ISSUE TITLE
書き出し先固定時、音声書き出し成功した時にトーストを表示する

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1329]
## 内容

書き出し先を固定する機能があります。
これをオンにして音声を書き出しすると、一瞬で音声の保存が完了し、かつ成功したことをフィードバックしていないため、成功したことに気づけない状態になっています。
例：https://twitter.com/shutorabit/status/1663874694934847490

音声書き出しは反復作業となるため、必ず応答が必要になるような成功フィードバック（ダイアログなど）はあまり良くないと思いますが、トーストを表示するのはありかなと思いました。
あとはトーストの右側のボタンとかに二度と表示しないボタンがあれば十分そうだと思います。

### Pros 良くなる点

エラーだと勘違いしづらくなる

### 実現方法

ポート自動変更通知トーストが似ていると思います。
https://github.com/VOICEVOX/voicevox/blob/d98abaea54e3540d59083ce067a093339b19c468/src/views/EditorHome.vue#L590-L609

**Comment by shm11C3** [comment]
初めまして。こちらの課題取り組もうと思います！

`components/Dialog.ts` にトースト呼び出し処理を追記することで実装できると考えていますが、そのような実装で問題ないでしょうか？

**Comment by Hiroshiba** [comment]
@shm11C3 はじめまして！

なるほどです、とても良いと思います！！
わからないことがあればなんでも聞いてください！
