### ISSUE TITLE
「アクセス許可で禁じられた方法でソケットにアクセスしようとしました」エラー

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1330]
## 不具合の内容

50021番ポートででエンジンを起動しようとした時、`[Errno 13] error while attempting to bind on address ('127.0.0.1', 50021): アクセス許可で禁じられた方法でソケットにアクセスしようとしました。`というエラーが出ることがあります。

こちらの[プルリク](https://github.com/VOICEVOX/voicevox/pull/1317)でポートが利用中だった場合は別ポートで起動するように変更されましたが、それ以外の理由でポートが使用できない場合には無力です。
ポートがあらかじめ利用できない場合でもポートが自動的に置き換わる、あるいはそうだとわかるエラーが出るようになればこのissueはcloseだと思います。

### 現象・ログ

エンジン起動時にエラーが出る。

```bash
[Errno 13] error while attempting to bind on address ('127.0.0.1', 50021): アクセス許可で禁じられた方法でソケットにアクセスしようとしました。
```

### 再現手順

```bash
netsh int ipv4 show excludedportrange protocol=tcp
```
でアスタリスクがついてないポート範囲を使う。

### 期待動作

ポートがあらかじめ利用できない場合でもポートが自動的に置き換わる。
あるいはそうだとわかるエラーが出る。

## VOICEVOXのバージョン

0.?.0

## OSの種類/ディストリ/バージョン

（不明）

- [x] Windows
- [ ] macOS
- [ ] Linux

## その他

- https://github.com/VOICEVOX/voicevox/pull/1317

**Comment by Hiroshiba** [comment]
エンジン側がエラーだったらポートを変更するなどの方法もありますが、現状だとエンジンのエラーの原因が分からないので、無限にリトライを繰り返してしまう行動になるかもしれません。
エンジン側でポートが塞がれていったということをエラーメッセージで伝えられるようにしてからが一番正確かも？
（でもポートが使えなかったということをわかる方法ってあるのかな･･･）

**Comment by sabonerune** [comment]
エディタ側単独でできる方法としてnodeAPIでサーバーを作成して起動に成功したポートを使用してエンジンを起動するという方法があります。
https://nodejs.org/dist/latest-v18.x/docs/api/net.html#class-netserver
https://nodejs.org/dist/latest-v18.x/docs/api/net.html#netcreateserveroptions-connectionlistener


これが機能するか試しているとき気づいたことですが

- 自分の環境では600ポート連続で予約されていた。
エンジン指定のポート + 100番まででは足りない可能性がある。
- このissueには直接関係ないが自分の環境では100ポート探索した場合`win.loadURL()`で`ERR_FAILED (-2)`が発生する。
50ポート程度なら問題ないので何かしらのタイムアウトが発生している?(原因不明)

**Comment by Hiroshiba** [comment]
なるほどです！　数百連続しているとなると、空いているポートを探す手もあるかなと思いました。
ちょっと調べてみた感じ https://www.npmjs.com/package/get-port とかが便利そうかも？
