### ISSUE TITLE
[リファクタリング] src/components/Dialog.tsの処理がかぶっている部分を統一する

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1337]
## 内容

https://github.com/VOICEVOX/voicevox/blob/main/src/components/Dialog.ts
は生成後の処理が大部分がかぶっているけれども統一化されておらず、ダイアログを出すところやトーストを出すと部分がコピペコードになってしまっています。
ここを統一してリファクタリングが完了したらこのタスクは完了です。

### 実現方法

関数切り出ししたり。

## 関連

- https://github.com/VOICEVOX/voicevox/pull/1335

**Comment by shm11C3** [comment]
こちら取り組みます！
一旦https://github.com/VOICEVOX/voicevox/pull/1335#discussion_r1228905078 で挙がった `SET_CONFIRMED_TIP` の改修PRを発行してから着手したいと思います。

**Comment by Hiroshiba** [comment]
@shm11C3 おお、ぜひ！！　不明な点があればなんでも聞いて頂ければ！ 🙏
