### ISSUE TITLE
最近使ったプロジェクトが削除・移動されたときのエラーハンドリングがされていない。

### ISSUE THREAD

**Issue by sabonerune** [VOICEVOX/voicevox#1348]
## 不具合の内容

最近使ったプロジェクトから選択したプロジェクトファイルが存在しない場合のエラーハンドリングがされていません。
そのためユーザー向けではないエラーダイアログが表示されます。
また、最近使ったプロジェクト一覧からその項目が消えることもありません。

#### ログ
```
Error occurred in handler for 'READ_FILE': Error: ENOENT: no such file or directory, open 'D:\Dev\Untitled.vvproj' {errno: -4058, code: 'ENOENT', syscall: 'open', path: 'D:\Dev\Untitled.vvproj', stack: 'Error: ENOENT: no such file or directory, open 'D:\Dev\Untitled.vvproj'', …}
[22:16:07.436] [error] Error: Error invoking remote method 'READ_FILE': Error: ENOENT: no such file or directory, open 'D:\Dev\Untitled.vvproj'
```

#### エラーダイアログ
```
[Window Title]
エラー

[Content]
Error invoking remote method 'READ_FILE': Error: ENOENT: no such file or directory, open 'D:\Dev\Untitled.vvproj'

[OK]
```

### 再現手順

プロジェクトを保存してそのプロジェクトファイルを削除する。
その後ファイル>最近使ったプロジェクト>[先ほど削除したファイル]を選択する

### 期待動作

ユーザー向けのエラーメッセージが表示される。
その後一覧から削除される。

## VOICEVOXのバージョン

恐らく 64e044787b4aed2bf6573cbafe729c12bf2ec468 以降

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

## その他

恐らく全てのプラットフォームで発生する。

**Comment by Hiroshiba** [comment]
ご報告ありがとうございます！
そこそこ頻繁に発生しそうだと感じたので優先度を少し高めに設定してみました。

とりあえず[0.15アプデ](https://github.com/VOICEVOX/voicevox_project/discussions/22)までに解決すべきメモとして追記しておきました。

（ https://github.com/VOICEVOX/voicevox/pull/1264 を実装してくださった @sevenc-nanashi さんにも共有をば･･･！）
