### ISSUE TITLE
「見た目上のテキストだけを編集」する機能の追加

### ISSUE THREAD

**Issue by thiramisu** [VOICEVOX/voicevox#1353]
## 内容

(以下、「見た目上のテキスト」を「テキスト」とします。)

テキストを編集すると確定で読み方全体が再パースされ、それに伴いパラメータも初期化されてしまい、少し不便です。
例えば以下のような場面で直面します。
- 言い回しを一部分だけ変えたい
- 読みを変えないでテキストだけを変えたい
  - 括弧を付け足したい
  - 漢字をひらがなに直したい

テキストは、このアプリケーション単体で見ると見た目だけにしか関係しませんが、外部アプリケーションと連携させて使う場合には字幕としての使用が想定されます。
もし現状のようにVOICEVOX内で容易に変更できない場合は、外部アプリケーション側で字幕を再編集することになります。この場合、例えば後から今度は音声側を少し変更したいとなった時に、字幕も再設定することになり、不便です。

### Pros 良くなる点

- 見た目を諦めるか再設定の手間かのどちらかを取る必要があった状態が改善される。
- 外部アプリケーションとの連携がスムーズになる。

### Cons 悪くなる点

- このアプリケーション単体で見た場合に、出力に影響を及ぼさない。
- パラメータを調整しないで使う使用法のユーザーにとっては、必要ない機能である。

### 実現方法

- 各行の右クリックメニューに「テキストのみ編集」を追加します。
(ゴミ箱アイコンの横に追加する手もありますが、そこまで使用頻度が高いとは思えないため、右クリックメニューで十分だと思います)
- そのオプションのクリック時、「テキスト編集モード」にして、テキスト欄にフォーカスし、テキスト欄の背景色を通常のモードと違う色にします。
(通常の編集とは違う機能であることをユーザーに明示するためにテキストを全選択しても良いかもしれません。)
  - [テーマで指定できる色](https://github.com/VOICEVOX/voicevox/blob/c3e90faaa756d6c79a59b90b1c170f252b270b23/docs/%E8%89%B2%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6.md#%E3%83%86%E3%83%BC%E3%83%9E%E3%81%A7%E6%8C%87%E5%AE%9A%E3%81%A7%E3%81%8D%E3%82%8B%E8%89%B2)を増やす必要があります。
- テキスト編集モード中は、入力文字列をパースする処理をスキップします。
- テキスト欄からフォーカスが外れた時、テキスト編集モード中なら、モードを解除します。
- [F2]をショートカットキー「テキスト欄のテキストのみを編集」として割り当てます。(Excelでのセルの編集やGIMPでのレイヤー名変更が[F2]です)
(ただし使用頻度は低そうなので、ショートカットキーは追加せずとも問題ないと思われます。)

もし複数の欄の内容を連続で編集したいことがあれば、モードon/offするトグルボタン方式などもありかと思いますが、そういった需要はない気がします。

## VOICEVOXのバージョン

0.14.7

## 進捗
- [x] 内部実装
- [ ] UI
  - [x] UIの名前を考える
    ひとまずコンテキストメニューは「内容をテキストのみに適用」になりました。
  - [ ] ショートカットキーを考える;  他の類似のアプリから拾いたい
  - [ ] UIの配置先を考える; ショートカットキー & (コンテキストメニュー |& ツールバー)が有力、ボタンは目立ちすぎ
    - [x] 右クリックメニューの内部実装の改修
      ref #1364
      ref #1365
      ref #1374
  - [ ] 編集中であるとユーザーに伝える方法を考える; 例えば[Quasar.input](https://quasar.dev/vue-components/input/)のlabelとかhintとかでも良いかも？

## その他

「字幕としてのテキストの活用」という観点で見た場合、
- テキストを改行できるようになった方が良さそう
- 節・句・語などを区切る機能を流用すれば、折り返し文字数・行数の指定だけで良い感じの位置で自動改行もできたりして

なども考えましたが、音声には全く関係のない機能なため、保留します…
万が一必要そうであれば新たにissue書きます。

**Comment by thiramisu** [comment]
>機能的にはこちらが近いと思います。

少し自分のイメージと食い違ってしまっている気がします。
うまく伝えられなかったようなので、似た内容になってしまいますが今一度強調します。

欲しいのは、テキストの変更時に再解析をしない設定です。

「テキスト欄入力だけで自動的に設定される値からユーザーが手動で変更したアクセントやイントネーションや長さ」のことを「設定したパラメータ」と呼ぶことにします。
テキスト欄はそのままで読みを一部変更した場合には、その変更したアクセント句内こそ再解析され設定したパラメータはリセットされますが、その局所的な範囲以外の設定したパラメータは保持されます。
しかし、読みはそのままにテキスト欄を一部変更した場合は、そのテキスト全体が再解析される都合上、設定したパラメータが読みテキスト全体にわたり全て失われてしまいます。この **全て失われてしまう** のが致命的ではないかと感じました。

現状この失われるのを回避しつつ見た目テキストを編集するには例えば、
- 新しいテキスト欄を作り、一からパラメータを手動で同じものに設定していく
- テキストエディタで`.vvproj`ファイルを開いて直接編集

などの力技しかないと思うので(間違っていたら申し訳ないです)、そこが直観的になればなと思って提案しました。

----

> もし見た目テキスト編集モードを実装する場合、見た目編集完了後はそのテキスト欄で見た目テキストや元のテキストはどう表示すると良さそうでしょうか。

バージョン0.14.7現在でも、[読みの修正機能](https://voicevox.hiroshiba.jp/how_to_use/#:~:text=%E8%A1%8C%E3%81%A0%E3%81%91%E3%81%A7%E3%81%99%E3%80%82-,%E8%AA%AD%E3%81%BF%E3%81%AE%E4%BF%AE%E6%AD%A3,-%E8%AA%AD%E3%81%BF%E3%81%8C%E6%80%9D)を(本来想定されているであろう読み修正ではなく)、単語を丸ごと新たに加えるような「悪用」をした場合に、見た目上のテキストと読みが食い違う可能性があります。
そのため、自分はそもそもテキスト欄を「実際の読みとはそこまで密接に関わっていない、識別をするためのラベル」のようなものと捉えていました。

それを考慮すると、現状でも「片方表示」に近い状態だと思います。
自分の使用範囲では現状で困ったことはないため、片方表示で問題ないと考えていました。

----

> 似た方法やアイデア

自分の実現したいことと照らし合わせると、見た目テキストを無視して読みテキストだけでテキストが変更されたかを判断して再パースすべきか判定する、という方法で実現できそうではありますね。

ただその実装と仮定した場合、例えば語尾の`なのだ`を`なのです`にしたいケースで、読みの修正機能を使って読みを変更したあとで、読みテキストを維持したまま見た目テキストを変更することを考えると、`なの[だ](です)`という表記となり、分かりやすいとは言えない解決策になってしまうので、もう一捻りする必要がありそうです。

あと、その記述方式だと「片方表示」ではきつそうだなとも思います。

惜しいところな気はしますが、改善できるアイデアはパッとは浮かびませんね…

**Comment by thiramisu** [comment]
ありがとうございます。かくいう自分も再言語化でより目標が明確になりました。
いやしかし、真に欲しいことを実装するとすると、難易度爆上がりですね！

> ショートカットキーや機能の名称に関しては要議論
> 類似の機能があったらそれを真似すると良さそう

確かにもう少し似た機能を持つソフトから探したほうが良さそうですね。
ただお恥ずかしながら、こういう類のソフトを触る頻度が少ないため、勉強してきます…

----

あと、とりあえず試作してみました。

https://github.com/VOICEVOX/voicevox/assets/7900586/fa4181b1-e3c1-4b54-90a8-6efa4b9f4996

https://github.com/thiramisu/voicevox

ただ、UIが最初に示した実装と異なります。

- マウス用UIはテキスト欄削除ボタンの左に追加する形にしました。
右クリックメニューに追加しようとすると、 https://github.com/VOICEVOX/voicevox/commit/876d5193d97228062ae3ddc0439ff9518b529789 によって、`src/electron/contextMenu.ts`を`.vue`ファイル内で`import`しようとするとエラー吐いたりと、そもそもデフォルト機能以外を簡単に拡張できる構成になってなさそうで、大規模改修が必要そうだったので…自分の考えた実装がよろしくないんだと思いますが。

- 強調表示は枠線を追加する形にしました。
テーマ色追加は流石にやりすぎなのと、色の濃度の変化は意外と視認性が悪かったためです。

自分はこのUIでも問題ないかなと思うのですが、どうでしょう？最初のほうがより良いでしょうか？

**Comment by Hiroshiba** [comment]
> とりあえず試作してみました。

すごくイメージわきやすくて良いですね！！！
右クリックの実装見てみました、たしかにだいぶ難しそうな印象です･･･。諦めに賛成です。

---

UIに関して自分の思うことを箇条書してみました！

* 初期画面に表示されるものは「ほぼすべての人が使うもの」級のUIだけにしたいので、ボタンを初期画面から隠したい
	* 「簡単そうだ」という第一印象を思ってもらうため
	* [UI/UX デザイン方針](https://github.com/VOICEVOX/voicevox/blob/main/docs/UX%E3%83%BBUI%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3%E3%81%AE%E6%96%B9%E9%87%9D.md)
* 右クリックメニューが一番良さそう
	* でも実装難度が確かにだいぶ高い。。
* ショートカットキーと、ツールバーのカスタマイズの機能にする？
	* ショートカットキーは[テキスト欄を追加](https://github.com/VOICEVOX/voicevox/blob/9990a19a403282083f82ad18911cd486e4abeeb7/src/views/EditorHome.vue#L264)が参考になりそう
	* ツールバーのカスタマイズは[１つ書き出し](https://github.com/VOICEVOX/voicevox/blob/9990a19a403282083f82ad18911cd486e4abeeb7/src/store/utility.ts#L131)が参考になりそう
	* あとは「使い方」でご案内
* 見た目テキスト編集中を示すUIがどういうのが良いかはわからない
	* ショートカットキーにする場合、誤爆する人にも優しいようにしたい
		* [Quasar.input](https://quasar.dev/vue-components/input/)の`label`とか`hint`とかでも良いかも？
	* 表示方法は置いといて、一旦機能追加してあとで考えるのもあり

---

実装に関してのコメントです！
ショートカットキーもツールバーボタンもどちらもコンポーネントがAudioCellと異なるので、「見た目テキスト編集中」であることをどうやって伝えるかにいろんな方法がありそうだな～と思いました。

**Comment by thiramisu** [comment]
右クリックに関して
確かに、やはり右クリックが良さそうです。

右クリックの内部実装変更は、この機能以外でも需要ある汎用的な部分だと思うので、なんとかできないか一応やってみます！もし出来たらその部分だけでまずPR送ろうと思います。
原因は理解してませんが
> src/electron/contextMenu.tsを.vueファイル内でimportしようとするとエラー吐いたり

試しにこれを`// eslint-disable-next-line`したらアプリの起動すらできなくなった…ので、回避方法を模索中ですが、時間はかかりそうです。
実装が汚くなりそうなので、もし酷かったらPRの却下をお願いします！その場合はひとまず諦めて別のissueをやろうかと思います。

----

UIに関して
自分で作ってみて思ったんですが、入力欄の左側の枠線の強調表示は「複数選択」#457 とかを示していた方がしっくり来るかもしれません。
色々試しに実装して実際に触ってみるのが早いと思ったので、quaser.inputも試作してみますね。

----

実装に関して
実は(右クリックがよく分からなかったため)ショートカットキーをまず先に実装に実装してから、ボタンの方を実装したので、ショートカットキーは既に効いたりします。
具体的には、前からあった`"COMMAND_CHANGE_AUDIO_TEXT"`と同じ感じで`store.dispatch("COMMAND_CHANGE_DISPLAY_TEXT")`を実行する感じになってます！
なのでツールバーも比較的実装しやすいと思います。ひとまずツールバーとショートカットキーにしてみるという手もありそうですね。

**Comment by sevenc-nanashi** [comment]
> src/electron/contextMenu.tsを.vueファイル内でimportしようとするとエラー吐いたり

https://quasar.dev/vue-components/menu/ QuasarのContext Menu使うのはどうでしょう？

**Comment by thiramisu** [comment]
electronにはmenu.deleteItem(itemId)的なインスタンスメソッドが存在しないっぽいので、機能性も高くないかもです
確かにそもそもelectronでの実装を辞めるのもありですね

**Comment by Hiroshiba** [comment]
menuItemなどでやる（electronではなくブラウザとしてやる）場合、切り取りとかに該当する操作を簡単に実装できるかが課題になりそうかな〜と感じています。
ペーストの挙動も結構複雑で、カーソルが当たっている位置に挿入し、範囲選択されている場合は消去して挿入みたいな感じなので･･･。

**Comment by thiramisu** [comment]
![image](https://github.com/VOICEVOX/voicevox/assets/7900586/f4de68da-4001-4368-9636-4c6d4ce0ce49)

ユーザーへの提示方法ですが、こんな感じはどうでしょうか？
この場合のショートカットキーは、項目が１, ２, ３なので０あたりが自然なのかなと思います。

----

数種類のエディタのマニュアルを見た限りでは、入力されたテキストを読みに反映しない機能のあるエディタは[A.I.VOICE](https://aivoice.jp/manual/editor/text_list.html#id3)だけでした。もし未適用を表すならテキスト欄の右側にアクティブ行の矢印みたいなのを表示とかですかね…
上の欄が完全に行選択のためだけに活用されてて、画面の下半分で詳細を設定するようなレイアウトのものでは、そもそも字幕と読みで`<input>`が2つに分かれてました。
VOICEPEAKには #1354 相当の機能があり、明示的なテキストのみ編集はなさそうでした。
CeVIOでは [F2] はセルへの入力の開始(多分VOICEVOXの[Enter]相当？)っぽかったです。

**Comment by Hiroshiba** [comment]
提案ありがとうございます！！
詳細調整欄自身の見た目を変えるのはとても面白いアプローチだと思いました！

提案の内容だと「非表示になる・操作不可能になる」という挙動ですよね。
目指すべきは「連動しないことが伝わる」でそれ以外はそのままの状態なのかなと思いました！
例えば非表示にすると、イントネーションのパラメーター数値をメモりたい時に不便かもです。操作不能になっているのは･･･問題ないかも･･････？（ちょっと需要が不明でした）
あとショートカットキー「０」はテキスト欄を選んで入力できないので不便かも？

かといってさらなるアイデアは思いついていないのですが･･･。
例えば詳細調整欄に非連動を示すアイコンを表示したり、全体を半透明にしたりとかでしょうか。。
（連動を切るアイコンといえば、縦横比の連動を鎖アイコンで表示しているイラストソフトとかはたまにありますね･･･。）

**Comment by thiramisu** [comment]
あ、上記は同期/非同期状態を示すUIではなくて、「テキストエディタモード」中であることを示す目的のUIでした。機能を表せる的確な名前が思いついてませんでした…。
これは「解除する」を押すまでずっと続きます(単一行編集と連続編集で分けてもいいかもですが)。
また、「解除する」を押してもすぐにテキストと読みが同期されるわけではなくて、そこからテキスト欄を再編集してはじめて再同期される感じをイメージしてました！

同期状態かどうかを表すほうは、確かに鎖のアイコンが分かりやすいかなと思いました。
同期されてない間だけ切れた鎖のボタンを表示して、それをクリックすると再同期される、みたいな感じでしょうか？どこに表示するかが問題ですが…。

**Comment by Hiroshiba** [comment]
あ〜なるほどです、連続して複数のテキスト欄で字幕編集できるように、ということだったんですね！
面白そうですが、ちょっと需要の割に機能が大掛かりかも･･･？
どちらかというと１行だけサクッと変えたいという需要が多そうな気がしています。
（詳細調整欄に終了ボタンが有る場合、テキスト欄と終了ボタンを往復しないといけない）

> という流れで確認できるのですが、それも不便だったりしますかね？

ここも含めてちょっとユースケース考える感じかな〜と思いました！

> 鎖のアイコン

表示のみでボタン機能は持たないのをイメージしていました！　UI的に納得感あればボタンにしても良いと思います。
字幕編集モードに入ったあと、次にtextPush（テキスト欄の確定）したら勝手に字幕編集モードが解かれるのをイメージしてました！

---

複数行変更できた方が良いのか、１回だけパッと変更できる方が良いのか、ちょっとユースケース考えるのが良いのかなと思いました。
issueに書かれている↓に同意です。

> もし複数の欄の内容を連続で編集したいことがあれば、モードon/offするトグルボタン方式などもありかと思いますが、そういった需要はない気がします。

**Comment by thiramisu** [comment]
複数行編集を実装するかで結構UIも変わってきそうですね、一行だけなら鎖ボタンも、解除するボタンも不要ですし。提案しておいてなんですが、やはりまずは単一行のみに絞った方が良さそうですね。

通知の方法については、編集開始時にトーストで表示 + 編集中は詳細設定欄の背景を灰色寄りにする、というのはどうでしょうか？
トーストは「今後表示しない」こともでき、なるべくテキストで案内したいのと、なるべく操作の邪魔にならないようにしたいのが両立できると思います。
何かが起こっていることを分かりやすくするために、変化させる面積はなるべく広い方がいい気がしました。

同期/非同期状態を表すUIについてですが、内部的にテキスト欄ごとに「同期中？」フラグを持っておいて、
字幕編集が行われた場合にfalseにして、その間は削除ボタンの左に「再同期」ボタンを表示するのもありかなと思いました。
これなら字幕編集しない限りボタンが表示されることはなく、ファーストビューをシンプルに抑えられます。
再同期ボタンとするなら、ブラウザのリロードボタンみたいなアイコンも候補かなと思いました。
(でも「同期中？」フラグは逆に読みだけ編集した場合もfalseにすべきだったり…？)
まあこのUIも上の方で話した通り、無くても良いかもです。

----

あと追加で機能面に関してお聞きしたいのですが、字幕編集中に複数行貼り付けが行われた場合、どの挙動にすべきでしょうか？

- x：そもそも実行しないようにする
- o：実行はする

選択中のテキスト欄の読みは
- １：更新されない
- ２：更新される

増えるテキスト欄の読みは
- a：空欄
- b：解析される

個人的にはo2b(つまり別に字幕編集中ではなかったかのような挙動)が良いかなと思います。

**Comment by Hiroshiba** [comment]
> やはりまずは単一行のみに絞った方が良さそうですね

賛成です！
ユースケースが思いついたりニーズが届いたりしたら新たに考えたいですね。

> トースト

これは間違えて操作しちゃう人の数がどれくらいいるかどうかかなと思いました。
個人的には一旦なしでいいかなと思います。実際に操作してみて誤爆が多そうだなと思ったら再度考えるとか。

> 編集中は詳細設定欄の背景を灰色寄りにする

賛成です！！
（デザインの経験が少なくて、正直見てみないとわかんないんですよね。。。）

> 内部的にテキスト欄ごとに「同期中？」フラグを持っておいて、

僕もこの方針がいいのかなと思いました！

> その間は削除ボタンの左に「再同期」ボタンを表示するのもありかなと思いました。

個人的には、テキストの確定を同期解除とするので十分かなと思いました。
が、非同期編集状態であることを示すアイコンは多分必要で、そのアイコンについでにボタン的機能を持たせるという目的であればありかも･･･？
（正直、このアイコンがないとその編集モード中なのかどうか伝わらないのか、あってもなお伝わらないのか、これも実際に作ってみないとわかんないなと思いました。。。）

> 再同期ボタンとするなら、ブラウザのリロードボタンみたいなアイコンも候補かなと思いました。

アイコンやボタンの見た目として求められる要件としては、今回の場合は「何をしている最中かわかる」ことと「そのボタンをクリックすれば何が起こるかがわかる」のが重要かなと思いました。
そういう意味ではリロードボタンはどういう状態を示しているのかはわからないかもです。

> 字幕編集中に複数行貼り付けが行われた場合

なるほど確かにそういうことも起こり得ますね･･･。
ちょっと考えたのですが、僕も`字幕編集中ではなかったかのような挙動`に賛成です！

**Comment by thiramisu** [comment]
「見た目上のテキスト」という用語、この間定まったUIの名称に沿わせるなら、「台本」が伝わりやすそうですね。一応「ユーザーに提示しない」マークは付いていますが…

あと、試作しなおして気が付いたのですが、「編集したテキストを台本のみに適用」というアクションにしてしまえば、そもそも「編集中状態」を伝える必要がないので、UIとかを考える必要がなくなることに気が付きました。

**Comment by Hiroshiba** [comment]
> 「見た目上のテキスト」という用語、この間定まったUIの名称に沿わせるなら、「台本」が伝わりやすそうですね。

あ、台本を「複数のテキスト」を指す感じで書いてました！
ここで出てくる台本はテキストと意味が近いので置き換えられるかも･･･？
「テキストのみに適用」や「内容をテキストのみに適用」とか。。

> 「(編集した)テキストを台本のみに適用」というアクションにしてしまえば

なるほどです！！！！！
ユーザーが「読みを変更せずにテキストの内容を変えたい」と思うのはおそらく入力前なので、UXのことを考えればおそらく先に状態を変更してあげた方がいいのかなと思います。
ただまあこれはデザイン含む実装コストがなかなか大きいので、ニーズの大きさを考えるとそちらの方針の方が良いのかなと思いました！！

**Comment by thiramisu** [comment]
> あ、台本を「複数のテキスト」を指す感じで書いてました！

なるほど！「テキスト」、用語としては個人的にはピッタリとは言えない気がするんですよね…「読み」はしっくり来るんですが。台本中の一行なら「台詞」が近いですが、発話されたものも台詞と言えてしまうのでややこしいかも…
明言を避けるという消極的な方向でなら「読みを変えずに内容を適用」あたりでしょうか。
あとはこのissueとは離れてしまうんですが、UI中にあえて名称を登場させて覚えてもらう方法もあるかもですね、+ボタンに`hover`すると「テキストを追加」と出る、みたいな。

> ユーザーが「読みを変更せずにテキストの内容を変えたい」と思うのはおそらく入力前

逆に言えば、状態を管理しないことで、入力中に字幕編集モードじゃないと気付いた時にもリカバリが効く、というメリットも一応あります。(状態管理する場合にその時どういう動作にするかにもよりますが)

UIに関しては、その「状態を案内」をする場所や認識コスト？を他の機能に割いた方が分かりやすい気がしたんですよね。まあ個人的にはこれに並ぶ欲しい機能は複数選択しか思いつかないんですが、他に新たに追加されることもありそうかなと。

**Comment by Hiroshiba** [comment]
> テキスト

調査などありがとうございます！！！

個人的にテキストは馴染みがありすぎたのかもです。技術的に「テキスト音声合成」と呼ぶので･･･。一般的には馴染みがないのかもな～とちょっと思いました。

個人的には「セリフ」も十分にありだなと感じました。
音声も含んでしまいそうなのは確かに気になりますが、テキスト（文章）と違って１行だけっぽいのが良いなぁと。
文字と読みが一致しなくなりうるAIVOICEは「セリフ」じゃないのもなるほどという感じですねぇ。。
うーーーーーーーーん。セリフもありですが、まあ少なくともメジャーアプデまではテキストのままかな～と思いました。
１行の台本に該当する言葉があると良いのですが 😇 

> UI中にあえて名称を登場させて覚えてもらう方法もあるかもですね

すごくありだと思います。
ホバーしたら説明が出てくる体験を全体的に作っていくの良さそうです。アイコン表示にできるので。
汎用的な仕組み作れたらアクセシビリティも兼ねていろんなボタンに名称を割り当てていきたみがあります。
（スマホ展開のことも視野に入れて、長押しでも同じ事ができるようにしておきたいかも。）

> 逆に言えば、状態を管理しないことで、入力中に字幕編集モードじゃないと気付いた時にもリカバリが効く、というメリットも一応あります

まあたしかにです。

> 複数選択のUIは多分ツールバーを乗っ取る形になると思うので

これはどうなんでしょう。「N個選択されています」みたいなのが表示されるということですよね。
僕が知るツールでそういう表示があるのは意外と珍しいかもです。google driveくらいかも。
ツールバーを乗っ取るのは結構たいへん＆他のツールバーボタンが押せなくなるのでそこそこ反対気味ですが、例えばその下あたりに新たにステータスバーを作るとかはありかも･･･？

**Comment by thiramisu** [comment]
「tts」「テキスト読み上げソフトウェア」も「テキスト」ですし、馴染みはそこそこある気がします。しかし自分の中の基準だと、読みの方に表示されているのも「テキスト」なので、そこがちょっと分かりづらいかなと思っていました。ただ「テキストのみに」という表現なら少し考えれば察しは付くとは思うので、大丈夫かなと思ってきました。

> ツールバーを乗っ取る

スマホの複数選択みたいなイメージでしたが、確かにPCだと珍しいかもしれませんね…ウーム難しい
スマホの感じを想像していたので、他のツールバーが押せなくなるというよりは「その実行中の動作に合ったツールバーに置き換わる」みたいなイメージでした。テキストのみ編集中なら、「[X] テキストのみ編集中… [適用]」、複数選択中なら「[X] 〇行選択中… [再生] [停止]  [書き出し] [行を削除」みたいな。その動作中はツールバーボタンを使えなくても良いと思うですが、どういう場合に問題になりそうでしょうか？
実装が重そうなのは確かにです😇
実装を他機能と共有できなそうなら別の方法が良さそうだとは思います。

> 新たにステータスバーを作る

ステータスバーに関しては、一時的な表示にすると1行目を選択した場合の挙動が怪しそうですし、常に表示するのは狭くなるので避けたい気がします。

----

ボタン命名issue #1442 を立てておきました。

**Comment by Hiroshiba** [comment]
> > ツールバーを乗っ取る
> 
> どういう場合に問題になりそうでしょうか？

例えば複数選択中にツールバーにある「１つだけ書き出し」を押すと選択しているものを書き出せそうですが、複数選択中表示によりボタンが隠れてしまう可能性がありそうです。
まあツールバーは任意の機能が実装される可能性があるので、何かを表示する場所として使う場合は機能的に問題がないもの同士かを意識する必要がありそうだなぁと。

> ステータスバーに関しては、一時的な表示にすると1行目を選択した場合の挙動が怪しそうですし、常に表示するのは狭くなるので避けたい気がします。

そうなんですよねー･････。

> その機能のオマケとしてフキダシ(実は入力欄)の編集をした場合に見た目だけに反映される、みたいなのは思いつきました。

面白そうですが、音声も変わってほしいと願われてしまうかもしれませんね 😇 

---

まあ･･･無難なのはとりあえず適当にテキスト欄に色つける感じですかねぇ･･･。
https://quasar.dev/vue-components/input/#coloring
複数選択は青系、テキストのみ変更モードは黄色系、みたいな感じで･･･。

**Comment by Hiroshiba** [comment]
まだ結論が出ていない議論があるかもしれませんが、少なくともissueの内容は解決しているのでcloseします！
@thiramisu さん、ありがとうございました！！
