### ISSUE TITLE
テキスト書き出しで無視する単語（テキスト）を設定できるようにする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1355]
## 内容

`[]`で囲われたものを読み飛ばす機能が提案されています。

- https://github.com/VOICEVOX/voicevox/issues/1099

逆に、テキスト書き出し時に無視する気泡もあると色々便利そうです。
例えば`()`を字幕無視するとすれば、「`[DB](ドラゴンボール)`」と書けば読みはドラゴンボール、字幕はDBにできます。

### Pros 良くなる点

読みと字幕を分けられる

### Cons 悪くなる点

記法は何が正解かわからない

### 実現方法

テキスト書き出しする時にそのテキストを無視するようにすれば実現できそうです。
問題は基本何にするかで、類似ソフトなどで似たような記法がある場合はそれを参考にしたいです。

## その他

まず記法を何にするかの議論が必要そう。
調査結果だけでもコメントしていただけると助かります。

**Comment by weweweok** [comment]
やってみたいです！

**Comment by weweweok** [comment]
この問題に取り掛かります。

**Comment by weweweok** [comment]
方針としては入力された文字列を、読む用と文字として表す用に分ける。
“焼きそばTDN(只野)" が与えられた時、

キャラクターが読む場合の文字列は
“焼きそば只野”　に変換し、

文字として表す用は
焼きそばTDNと文字列を分けてみたいと思います。

読み飛ばしのルールですが、まずは各audiocellにつき一回までとすれば、取り敢えず[]と()の判定は比較的容易に済むと思います。

すると以前は入力前の文字列をバッファが許す条件の中の文字列であればそのままvoicevox enginに渡していたと思われますが、今回のこの方法では、入力テキストとvoicevoxから返された音声データが別になることになります。

不明なこと:

・どこで文字列を操作すれば良いか(具体的には、入力される文字列がどのファイルのどのスコープで捜査されるべきか)
・Audiocellのテキストがどこに渡されるのか
・最終的に出力する文字テキストは以前はどこから渡されていたのか

**Comment by Hiroshiba** [comment]
@weweweok おお、ありがとうございます！！　不明な点があれば何でも聞いてください！
（難しそうだった場合も、こちらにコメントを書いていただければ、次挑戦される方の助けになると思います！）

**Comment by weweweok** [comment]
方針としては、入力された文字列を、読む用と文字として表す用に分けます。
“焼きそばTDN(只野)" が与えられた時、

キャラクターが読む場合の文字列は
“焼きそば只野”　に変換し、

文字として表す用は
”焼きそばTDN“に変換し、文字列を分けてみたいと思います。

読み飛ばしのルールですが、まずは各audiocellにつき一回までとします。そうすれば、取り敢えず、[]と()の判定は比較的容易に済むと思います。

これまでの場合、入力した文字列は、バッファが許す条件に合っていれば、その入力文字列を、そのままvoicevox enginに渡していたと思われます。しかし、今回のこの方法では、入力テキストとvoicevoxから返された音声データが別になります。
つまり、入力テキスト　-> 「voicevox enginによる音声」　が、

　　　　入力テキスト　-> 「出力テキスト(仮名)」
　　　　　　　　　　　-> 「voicevox enginによる音声」

と分かれると思われます。

現在不明なこと:

・どこで文字列を操作すれば良いか(具体的には、入力される文字列がどのファイルのどのスコープで操作されるべきか)
・Audiocellのテキストがどの箇所に渡されるのか
・最終的に出力する文字テキストは以前はどこから渡されていたのか

**Comment by Hiroshiba** [comment]
方針いい感じに思いました！！

> 現在不明なこと

読みで無視する方は、テキストを読みに変換する直前で文字列を操作するとかどうでしょう？
具体的には↓の`COMMAND_CHANGE_AUDIO_TEXT action`かなと。
https://github.com/VOICEVOX/voicevox/blob/9990a19a403282083f82ad18911cd486e4abeeb7/src/store/audio.ts#L1993-L1997

文字として表す方（便宜上「字幕」とします）は、字幕を保存する直前で文字列操作とか･･･？
だとしたら字幕の保存は２箇所、[`CONNECT_AND_EXPORT_TEXT`](https://github.com/VOICEVOX/voicevox/blob/9990a19a403282083f82ad18911cd486e4abeeb7/src/store/audio.ts#L1635-L1639)と[`GENERATE_AND_SAVE_AUDIO`のexportText](https://github.com/VOICEVOX/voicevox/blob/9990a19a403282083f82ad18911cd486e4abeeb7/src/store/audio.ts#L1372-L1373)にあります。


ちなみに僕もどこにあるかはちゃんと把握してなくて、コードを毎回見直して追っかけています。
この機能はコードのどこにあるんだろう？って機能をメニューバーから探して、コード全体をその文字で検索して、関数をまた文字検索したりコードジャンプしたりして追いかけました。
今回の場合だと「テキストを繋げて書き出し」とかで検索しました！
コード追っかけは[コードの歩き方.md](https://github.com/VOICEVOX/voicevox/blob/main/docs/%E3%82%B3%E3%83%BC%E3%83%89%E3%81%AE%E6%AD%A9%E3%81%8D%E6%96%B9.md)が参考になるかもです！

**Comment by weweweok** [comment]
以下のコードにより、特定の条件で作動するようになりました。
条件

- []()が戦闘の場合正常に機能する
- []()の前に空白があると正常に機能する

意図しないバグが起きる条件

- []と()の間に文字列がある
- []()の文字列の前に文字がある

```
function resolve_brackets(text: string): boolean {
  // []()がこの組で存在するかまったくないか
  const front_square_brackets_cnt: number = (text.match(/[[]/g) || []).length;
  const back_square_brackets_cnt: number = (text.match(/[\]]/g) || []).length;
  const front_parenth: number = (text.match(/[(]/g) || []).length;
  const back_parenth: number = (text.match(/[)]/g) || []).length;

  if (
    front_square_brackets_cnt <= 1 && //[の数
    back_square_brackets_cnt <= 1 && //]の数
    front_square_brackets_cnt === back_square_brackets_cnt && // "["と"]"が一致するとき
    front_parenth <= 1 && //"("の数
    back_parenth <= 1 && //")"の数
    front_parenth === back_parenth //"("と")"が一致するとき
  ) {
    return true;
  } else {
    return false;
  }
}

function div_str(input: string): string | Array<string> | undefined {
  //字幕用とエンジン用に文字列を分ける
  const replacestring: RegExpMatchArray | null = input.match(
    /[[0-9a-zA-Zぁ-ん一-龠]{0,}]/g
  ); // []に含まれる文字列
  const parentheses_in: RegExpMatchArray | null = input.match(
    /\([0-9a-zA-Zぁ-ん一-龠]{0,}\)/g
  ); // ()に含まれる文字列

  if (resolve_brackets(input)) {
    if (replacestring === null || parentheses_in === null) return input;
    let parenthese_str: string =
      replacestring !== null ? replacestring[0].slice(1, -1) : "";
    let square_brackets_str: string =
      parentheses_in !== null ? parentheses_in[0].slice(1, -1) : "";

    const output_as_text_index_start: number = input.indexOf(parenthese_str);
    const output_as_text_index_end: number = //いらないかもしれない
      output_as_text_index_start + square_brackets_str.length;

    const output_as_voicevox_engine_start_index: number =
      input.indexOf(square_brackets_str);
    const output_as_voicevox_engine_end_index: number = //いらないかもしれない
      output_as_text_index_start + parenthese_str.length;

    const replaceset = input.substring(
      output_as_text_index_start - 1,
      output_as_voicevox_engine_start_index + parenthese_str.length + 1
    );
    const for_subtitle: string = input.replace(replaceset, parenthese_str);
    const for_read_engin: string = input.replace(
      replaceset,
      square_brackets_str
    );
    return [for_subtitle, for_read_engin];
  } else {
    console.error("次の記号は一回しか使用できません -> [ ] ( )");
  }
}
console.log(div_str("[TDN](ただの)焼きそば ずんだ風味"));
console.log(div_str("[TDN](ただの)焼きそばずんだ風味"));
console.log(div_str("焼きそば ずんだ風味 [TDN](ただの)"));
console.log(div_str("焼きそば ずんだ風味[TDN](ただの)")); //意図しない挙動
console.log(div_str("焼きそば [TDN]ずんだ風味(ただの)"));

//div_str("[ooooohoooooo");動かない
div_str("[ooooohoooooo]");
div_str("ooooohoooooo()");
div_str("ooooohoooooo())"); //
```

**Comment by Hiroshiba** [comment]
例示なるほどです！
JavaScriptはreplaceメソッドを使って正規表現にマッチするものを置き換える操作ができたりします。これを使えばうまくいくかもです。

@weweweok さんのコードをヒントにChatGPT君に聞いてみました。参考になれば！（動くか確かめてませんが･･･！）
https://chat.openai.com/share/9be9135b-bd05-4d52-824f-8bda04a200a9

**Comment by weweweok** [comment]
ありがとうございます。
ものすごく参考になりました。
こちらでコードを少し修正したところ角括弧や括弧の数に制限なく分けてくれました。

```
export const remove_brackets = (text: string): string => {
  let resolvedText = text.replace(/\[.*?\]/g, "");
  resolvedText = resolvedText.replace(/\((.*?)\)/g, "$1");
  return resolvedText;
};

export const remove_parentheses = (text: string): string => {
  let resolvedText = text.replace(/\(.*?\)/g, "");
  resolvedText = resolvedText.replace(/\[(.*?)\]/g, "$1");
  return resolvedText;
};

export default remove_brackets;
```

test
```
import remove_brackests from "./reaplacestr";
import { remove_parentheses } from "./reaplacestr";

describe("resolve_brackets", () => {
  it("removes contents inside square brackets and ignores parentheses only", () => {
    expect(remove_brackests("テストA[テストB](テストC)[テストD]")).toBe(
      "テストAテストC"
    );
    expect(remove_brackests("[テスト]")).toBe("");
    expect(remove_brackests("(テスト)")).toBe("テスト");
    expect(remove_brackests("テスト")).toBe("テスト");

    expect(remove_brackests("テストA[testB](テストB)[testC](テストC)")).toBe(
      "テストAテストBテストC"
    );

    expect(remove_brackests("テストA[テストB]テストC[テストD]")).toBe(
      "テストAテストC"
    );

    expect(remove_brackests("テストA(テストB)テストC(テストD)")).toBe(
      "テストAテストBテストCテストD"
    );
  });
});

describe("resolve_parentheses", () => {
  it("remove contents inside parentheses and ignores square brackets only", () => {
    expect(remove_parentheses("テストA[テストB](テストC)[テストD]")).toBe(
      "テストAテストBテストD"
    );
    expect(remove_parentheses("[テスト]")).toBe("テスト");
    expect(remove_parentheses("(テスト)")).toBe("");
    expect(remove_parentheses("テスト")).toBe("テスト");

    expect(remove_parentheses("testA[testB](テストB)[testC](テストC)")).toBe(
      "testAtestBtestC"
    );

    expect(remove_parentheses("テストA[テストB]テストC[テストD]")).toBe(
      "テストAテストBテストCテストD"
    );

    expect(remove_parentheses("テストA(テストB)テストC(テストD)")).toBe(
      "テストAテストC"
    );
  });
});
```

![image](https://github.com/VOICEVOX/voicevox/assets/100256521/3875a8f3-fd45-478b-8cfb-ce3f3feb67f4)

**Comment by Hiroshiba** [comment]
おー！！　良いですね！！

**Comment by weweweok** [comment]
字幕は問題なさそうです。
![image](https://github.com/VOICEVOX/voicevox/assets/100256521/278ed162-2d36-4eff-af36-6d6c45e49253)
![image](https://github.com/VOICEVOX/voicevox/assets/100256521/59f04d34-3e21-4639-887b-b51e28fbfc7d)

しかし、
[COMMAND_CHANGE_AUDIO_TEXT action]
において(textを別変数で置くとエラーが出るため)まず
(https://github.com/VOICEVOX/voicevox/blob/9990a19a403282083f82ad18911cd486e4abeeb7/src/store/audio.ts#L1993-L1997)
に
![image](https://github.com/VOICEVOX/voicevox/assets/100256521/392aeb1a-6073-4b9f-80b5-353e68004c37)
とコード(緑色の個所)を加えると

https://github.com/VOICEVOX/voicevox/assets/100256521/299b5dd2-d865-46b8-9f95-ad84d05a002a
のようにエディタのテキストも削除されますごと消えてしまいます。

```
const accentPhrases: AccentPhrase[] = await dispatch(
              "FETCH_ACCENT_PHRASES",
              {
                text,
                engineId,
                styleId,
              }
            );
```
のtextのみ別変数でテキストを代入することができればよさそうですが、
変数textを別変数へ置き換えるには調べた限りinterfaceをいじるようです。しかし、まだよく分かっていません。

**Comment by Hiroshiba** [comment]
エンジンに投げるテキストとVOICEVOXのAudioCellを置き換えるテキストを分けると良いと思います！
具体的には`FETCH_ACCENT_PHRASES`には`resolvedText`を、`COMMAND_CHANGE_AUDIO_TEXT`には元の`text`を渡す感じでしょうか。

**Comment by Hiroshiba** [comment]
- https://github.com/VOICEVOX/voicevox/pull/1378

にて実装されました！
`[]`で囲った部分がテキスト書き出しと音声再生のどちらもで省略されます。
