### ISSUE TITLE
＋ボタンを消すオプションを作る

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1359]
## 内容

テキスト欄を追加するとき、右下の+ボタンを押します。
この+ボタンは初心者にとって気づきやすく分かりやすいUIになっていますが、慣れてくるとボタンの大きさやテキスト欄にかぶってしまうこと（特に削除ボタンとかぶること）が気になってきます。

テキスト欄の追加はShift+Enterで可能です。
となると＋ボタンを消しても大丈夫なはずです。

このissueは＋ボタンを非表示にするオプション設定を設けると完了です。
そのオプション付近で、テキスト欄追加のためのショートカットキー案内ができるとさらに良さそうです。

### Pros 良くなる点

＋ボタンを消すための方法を提供できる

### Cons 悪くなる点

最初に設定をいじってしまって間違えて消してしまった場合に詰んでしまうかもしれない。

## VOICEVOXのバージョン

0.?.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by shm11C3** [comment]
こちらの課題取り組みます！

ショートカットの案内は、設定ボタンホバー時に案内用のツールチップを表示することで実現できると考えています。

加えて、アクティブなテキスト欄に表示されるプレースホルダーがあると分かりやすいのではと思いました。
しかし、テキストを入力してしまうとプレースホルダーは見えなくなってしまうため、完全な案内方法ではないです。

より確実な案内方法としてテキスト欄上部のラベルもありますが、見た目が悪くなるかもしれないです（実装しないと分からないですが）。

**Comment by Hiroshiba** [comment]
@shm11C3 おお、ぜひよろしくお願いします！！

設定のホバーで案内、とても良いと思いました！

プレースホルダーや上部での案内もなるほどです。
あとアイデアとしては設定オフ時にダイアログで案内もありかもですかね…。（ホバーでの案内を読んだ人にとってはくどくなっちゃいますが…）

あるいは、右下追加オフ時はもうテキスト欄ホバー時の右に追加ボタン表示しちゃっても良いかも…？

なんか定まってませんが、良さそうな方法で取り組んでみていただければ！！

**Comment by shm11C3** [comment]
@Hiroshiba 
ダイアログでの案内、なるほどです！
ホバーではショートカットについて説明せずに設定内容を説明し、設定時にダイアログで案内すればくどくないと思いました。

一旦ダイアログ+ラベルを使って案内する方向で実装してみます！！

**Comment by Hiroshiba** [comment]
@shm11C3 なるほどです！！
実際実装してみたらちょっと思わぬ落とし穴みたいなのあったりするかもですが、一度プルリクエストいただけると･･･！！
