### ISSUE TITLE
エンジンPIDの探索に失敗して起動できない

### ISSUE THREAD

**Issue by y-chan** [VOICEVOX/voicevox#1360]
## 不具合の内容

題のとおりです。
PIDの探索コマンドの実行に失敗しているみたいです。

https://github.com/VOICEVOX/voicevox/blob/9990a19a403282083f82ad18911cd486e4abeeb7/src/background/portManager.ts#L124-L126

<img width="622" alt="image" src="https://github.com/VOICEVOX/voicevox/assets/34832037/768b8957-7b7c-49e3-ba01-37bb90e1aaa8">

何回か試していると、`Error: spawnSync /bin/sh ENOBUFS`というエラーが発生しているみたいです。

<img width="645" alt="image" src="https://github.com/VOICEVOX/voicevox/assets/34832037/898ad15f-835a-423b-9ad0-a8e2b3505812">

`execFileSync`が適切にエラーハンドリングされていないために発生しているという点と、`execFileSync`はバッファサイズに制限があるためにこのようなエラーが発生するようで、`spwanSync`を利用することで回避できるようです。(そもそもプロセスIDしか返してこないはずがバッファオーバーフローしているのと、空文字列を返してきているはずなのにこのエラーが出ているという点において色々おかしいのですが...)

https://stackoverflow.com/questions/63796633/spawnsync-bin-sh-enobufs
https://neos21.net/blog/2019/10/18-01.html#child_processspawnsync

ちなみに、どうやら単体でこのコマンドを実行し、プロセスが存在しなかった場合はエラーを返すようです。(左端にバツ印がついている)
<img width="683" alt="image" src="https://github.com/VOICEVOX/voicevox/assets/34832037/90bc3467-c6c0-4717-8cd1-bbd63d997bc3">

### 再現手順

Windows以外(私はMacで発生しました、lsofの仕様が一緒であればlinuxでも発生するはず)で最新`main`ブランチにおいて`npm run electron:serve`する

### 期待動作

問題なく起動する

## VOICEVOXのバージョン

main

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [x] macOS
- [ ] Linux

**Comment by Hiroshiba** [comment]
ポートが塞がれていたときに別のポートを探索する部分ですね！

- https://github.com/VOICEVOX/voicevox/issues/1252

> spwanSyncを利用することで回避できる

なるほどです、回避できるなら回避したいところですね･･･！

**Comment by madosuki** [comment]
このバグの根本的な原因は https://github.com/VOICEVOX/voicevox/pull/1267#issuecomment-1528652718 のやつだと思います。  

どうやらElectronは自身にバンドルしているNode.JSを使用するようで、Electron 20.3.12内のv16.15が使われてしまいこのバグが発生してしまうようです。  

それはそれとしてlsofの結果が空だと例外が発生するのでエラーハンドリングは必要のようです。

**Comment by Hiroshiba** [comment]
@madosuki さんありがとうございます！！

なかなか奥が深いですね……。
新しいelectronだとnodeのバージョン上がってたりしないですかね…。

空の時のエラーは、とりあえずwarnにログ出しつつfixmeコメント書くとかで良さそうですかねぇ。

**Comment by madosuki** [comment]
[https://releases.electronjs.org/](https://releases.electronjs.org/)  
23以降なら修正が反映されているバージョンを使っているようなのでどれかにするのが良さそう。

**Comment by Hiroshiba** [comment]
なるほどです！
21と22のバージョンアップは問題ないという感じでした

- https://github.com/VOICEVOX/voicevox/issues/1227

23はwindows 8の切り捨てになるとのこと。まあ･･･良いかな！
目指せ23アプデかなと思いました！

**Comment by sabonerune** [comment]
普通は起こらないと思いますがWindowsでも極端に大量(15000ポート程度で発生)のポートを使用している場合に`execFileSync`の出力がオーバーフローする場合があると念のため報告します。
