### ISSUE TITLE
Is it possible to produce custom sound

### ISSUE THREAD

**Issue by sekkit** [VOICEVOX/voicevox#1367]
I am producing custom sounds in a game, and I found it hard to produce custom sound like screaming, crying, laughing.
How to do it in voicevox?

**Comment by Patchethium** [comment]
Shortly speaking you can't, try sth else like bark.

**Comment by Hiroshiba** [comment]
@sekkit 
To my knowledge, there isn't a well-established methodology for creating emotionally-charged sounds such as screams, cries, or laughter. I believe it's you, the creators, who can make this possible, articulate it, and figure out the methods. Please do share your findings once you gather them!

**Comment by sekkit** [comment]
Actually I mean, if I say "What the hell are you doing!!!" in Japanese with very strong emotion. Can it be done in voicevox?

**Comment by Hiroshiba** [comment]
I'm not sure. Please try it out!
