### ISSUE TITLE
npm run electron:serveでvoicevoxが動作しない

### ISSUE THREAD

**Issue by weweweok** [VOICEVOX/voicevox#1368]
## 不具合の内容
```
npm run electron:serve
```
でvoicevox ver.999.999.999が起動できません。

### 現象・ログ
![image](https://github.com/VOICEVOX/voicevox/assets/100256521/0285020a-8a71-4ad4-84e9-5f8d53085768)
![image](https://github.com/VOICEVOX/voicevox/assets/100256521/4ca96789-faea-4a32-b33b-03fd92759edc)

### 再現手順

- voicevoxリポジトリをfork　-> clone
- voicevoxディレクトリで`npm ci`
- `touch .env`
- 同じディレクトリにて.env.productionの内容を.envにコピー
- voicevoxをインストール(製品版よりインストーラでインストール)
- .envのDEFAULT_ENGINE_INFOS.executionFilePathに`~/.voicevox/VOICEVOX.AppImage --appimage-mount`(このディレクトリにファイルがあることは確認済み)を追加
- npm run electron:serve

### 期待動作

voicevoxを起動してissue[#1355](https://github.com/VOICEVOX/voicevox/issues/1355)で書いたコードを実験できるようにしたい

## VOICEVOXのバージョン

999.999.999

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [x] Linux ( Ubuntu 22.04.2 LTS )

## その他

reactのアプリにおけるnpm startでアプリが起動するような認識で期待してしまっている可能性もあるため認識が誤りであればご指摘ください。

製品版のアプリ自体は動きます。
![image](https://github.com/VOICEVOX/voicevox/assets/100256521/968357f6-3254-4862-a723-fcb1c3727697)

**Comment by Hiroshiba** [comment]
ちょうどこちらのエラーと同じ症状が出ていると思われます。

- https://github.com/VOICEVOX/voicevox/issues/1360

おそらくですが、こちらの箇所を

https://github.com/VOICEVOX/voicevox/blob/1b9e6c28a4b8e6ec7c49e2b0a23dc24f53aa9a34/src/background/portManager.ts#L124-L126

```ts
//  const stdout = execFileSync(exec.cmd, exec.args, {
//    shell: true,
//  }).toString();
  const stdout = undefined; // FIXME: ワークアラウンド https://github.com/VOICEVOX/voicevox/issues/1360
```

などとすると一旦回避できると思います。
