### ISSUE TITLE
テキスト欄内でルビを設定できるようにする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1383]
## 内容

音声合成の誤読がある場合、なんらかの修正する必要があります。
直接テキスト欄を書き換えるとか、辞書登録をするとか、読み変更するとか。
頻繁に出てくる単語であれば辞書登録が最適解ですが、1回しか出てこない場合はだいたいテキストを書き換えると思います。
ただテキストを書き換えてしまうと、字幕を表示する場合に動画作成ソフト側でもう一度書き換える必要があるので不便です。

字幕（テキスト書き出し内容）をそのままにして読みだけを変えられると便利そうです。
テキスト欄に`{漢字|かんじ}`とあった場合、音声合成では「漢字」が無視され、字幕では「かんじ」が無視されるようになればこのissueの完了です。

（記法は確定ではなく、より良い記法があれば提案をお待ちしています！）

### Pros 良くなる点

便利になる

## VOICEVOXのバージョン

0.?.0

## その他

ref

- https://github.com/VOICEVOX/voicevox/pull/1378
- https://github.com/VOICEVOX/voicevox/issues/1355
- https://github.com/VOICEVOX/voicevox/issues/1099

**Comment by weweweok** [comment]
現在取り組み中です。

**Comment by Hiroshiba** [comment]
@weweweok ありがとうございます！　よろしくお願いします･･･！！

**Comment by stmtk1** [comment]
このイシュー実装終わってますか？？

**Comment by weweweok** [comment]
@stmtk1 

ごめんなさい！クローズしていなかったです。
実装は、完了しました。

**Comment by sevenc-nanashi** [comment]
#1384 で実装されました。
