### ISSUE TITLE
エディタにおいて、テキスト入力後即座に音声が書き出されない

### ISSUE THREAD

**Issue by weweweok** [VOICEVOX/voicevox#1386]
## 不具合の内容
 
以下のように、テキスト入力後にEnterを押しても読み上げない
https://github.com/VOICEVOX/voicevox/assets/100256521/342d4961-0b0e-41c8-920e-f67ae002b09f

### 現象・ログ

gitの状態この時に、pullをして、アプリをテストして発生。
![image](https://github.com/VOICEVOX/voicevox/assets/100256521/eb1310dd-df6e-47cb-9326-266b05074aac)

### 再現手順
以下を参照して、履歴を変更する。
![image](https://github.com/VOICEVOX/voicevox/assets/100256521/eb1310dd-df6e-47cb-9326-266b05074aac)

### 期待動作

テキスト入力後、即座にEnterを押して、読み上げ。

## VOICEVOXのバージョン

999.999.999

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

Windows 10 Home
## その他

半角スペースを入れると読み上げられます。

gitGraphの近況
![image](https://github.com/VOICEVOX/voicevox/assets/100256521/a0a3bdae-034c-4664-a54b-ea5323e65c43)

名前変更時までcommitを戻すと動く

**Comment by Hiroshiba** [comment]
ご報告ありがとうございます！

･･･でもすみません！！！
何が問題で、どうやったら再現するのかがちょっとわからないです･･･！！

**Comment by weweweok** [comment]
私の勘違いだったようです。

**Comment by Hiroshiba** [comment]
あ、なるほどです！　良かったです！！
