### ISSUE TITLE
各UIの名称が定まっていない

### ISSUE THREAD

**Issue by thiramisu** [VOICEVOX/voicevox#1397]
## 内容

ヘルプ/使い方(howtouse.md)に各ペインや主要コンポーネントの名称と場所と簡単な役割の説明を書いてあると親切かな思いました。が、そもそも正式名称のないUIが数多くあることに気が付きました。
命名自体はもう少し良いのがあると思いますが、以下の名称は欲しいと思います。

- メニューバー(最上部)
- 最前面固定ボタン(右上)
- ツールバー(上部)
- キャラ(クター)表示欄(左)
- テキスト編集欄(中)
  - 行
    - 行番号
    - キャラ/スタイル選択欄
    - テキスト入力欄
  - 行追加ボタン
- パラメータ調整欄(右)
- 詳細調整欄(下)
  - タブ
  - 音声再生ボタン
  - アクセント句
  - 読み仮名(読み)

- 直接入力欄
(話速の直接入力欄、みたいな感じ)
- 調整スライダー
(アクセント調整スライダー、みたいな感じ)
- アクティブな行
(キャラ選択欄の左に三角が表示されてる行)

### Pros 良くなる点

- 意思疎通がしやすくなる。
  - ドキュメントやwiki・説明動画、あとはUI提案やバグ報告とかでも参照しやすくなりそうです。

### Cons 悪くなる点

- 機能の追加・変更やUIの再配置に伴って名前変更の必要が出てくる可能性がある。

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！！！
とりあえずお手入れいただいたところを1個1個名称考えました･･･！
（まとまり次第またドキュメントに追加しようと思います）

基本的に[使い方](https://voicevox.hiroshiba.jp/how_to_use/)に既存で書いてあるものはそちらに合わせています。

- メニューバー(最上部)
	- →[メニュー](https://voicevox.hiroshiba.jp/how_to_use/#:~:text=%E3%81%92%E3%81%A6%E6%9B%B8%E3%81%8D%E5%87%BA%E3%81%97-,%E3%83%A1%E3%83%8B%E3%83%A5%E3%83%BC,-%E3%80%8C%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%80%8D%E3%81%AE%E3%80%8C%E3%83%86%E3%82%AD%E3%82%B9%E3%83%88)
- 最前面固定ボタン(右上)
	- →[ピンボタン](https://voicevox.hiroshiba.jp/how_to_use/#:~:text=%E5%8F%B3%E4%B8%8A%E3%81%AE-,%E3%83%94%E3%83%B3%E3%83%9C%E3%82%BF%E3%83%B3,-%E3%81%A7%E3%82%A6%E3%82%A3%E3%83%B3%E3%83%89%E3%82%A6%E3%82%92)（そもそもあまり呼ばないかも）
- ツールバー(上部)
	- →[ツールバー](https://voicevox.hiroshiba.jp/how_to_use/#:~:text=%E3%82%A4%E3%83%B3%E3%83%88%E3%83%8D%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%92%E3%83%AA%E3%82%BB%E3%83%83%E3%83%88-,%E3%83%84%E3%83%BC%E3%83%AB%E3%83%90%E3%83%BC%E3%81%AE%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%9E%E3%82%A4%E3%82%BA,-%E7%94%BB%E9%9D%A2%E4%B8%8A%E9%83%A8%E3%81%AB)
- キャラ(クター)表示欄(左)
	- →「キャラクター表示欄」で！（そもそもあまり呼ばないかも）
- テキスト編集欄(中)
    - →「台本欄」で！！
  - 行
    - →「レーン」で！（「テキスト欄」でも通じる場合はそちらを優先）
    - 行番号
      - →「行番号」で。
    - キャラ/スタイル選択欄
      - [キャラクターアイコン](https://voicevox.hiroshiba.jp/how_to_use/#:~:text=%E9%9F%B3%E5%A3%B0%E3%81%AE%E7%94%9F%E6%88%90-,%E3%82%AD%E3%83%A3%E3%83%A9%E3%82%AF%E3%82%BF%E3%83%BC%E3%82%A2%E3%82%A4%E3%82%B3%E3%83%B3,-%E3%81%AE%E5%8F%B3%E3%81%AB)
    - テキスト入力欄
      - →[テキスト欄](https://voicevox.hiroshiba.jp/how_to_use/#:~:text=%E5%A4%89%E6%9B%B4%E3%81%A7%E3%81%8D%E3%81%BE%E3%81%99%E3%80%82-,%E3%83%86%E3%82%AD%E3%82%B9%E3%83%88%E6%AC%84%E3%81%AE%E4%B8%A6%E3%81%B3%E6%9B%BF%E3%81%88,-%E3%83%86%E3%82%AD%E3%82%B9%E3%83%88%E6%AC%84%E5%91%A8%E8%BE%BA)
  - 行追加ボタン
    - 「テキスト欄追加ボタン」で！（そもそもボタン名を呼ぶことがあまりないかも。どちらかというと機能名を言及することは結構多いかも）
- パラメータ調整欄(右)
  - →「パラメータ調整欄」で！
- 詳細調整欄(下)
  - →「詳細調整欄」で！
  - タブ
    - →[項目](https://voicevox.hiroshiba.jp/how_to_use/#:~:text=%E5%A0%B4%E5%90%88%E3%81%AF%E3%80%81%E3%82%A2%E3%82%AF%E3%82%BB%E3%83%B3%E3%83%88-,%E9%A0%85%E7%9B%AE,-%E3%81%A7%E6%96%87%E5%AD%97%E3%81%AE)・「詳細調整欄の項目」で！
  - 音声再生ボタン
    - →「再生ボタン」で！
  - アクセント句
    - →[アクセント区間](https://voicevox.hiroshiba.jp/how_to_use/#:~:text=%E3%81%95%E3%82%92%E8%AA%BF%E6%95%B4%E3%81%99%E3%82%8B%E3%81%93%E3%81%A8%E3%81%A7%E3%80%81%E5%90%8C%E3%81%98-,%E3%82%A2%E3%82%AF%E3%82%BB%E3%83%B3%E3%83%88%E5%8C%BA%E9%96%93,-%E5%86%85%E3%82%92%E5%90%8C%E6%99%82%E3%81%AB%E8%AA%BF%E6%95%B4%E3%81%A7%E3%81%8D%E3%81%BE%E3%81%99%E3%80%82)（より良い名称を求む）
  - 読み仮名(読み)
    - [読み](https://voicevox.hiroshiba.jp/how_to_use/#:~:text=%E3%82%A2%E3%82%AF%E3%82%BB%E3%83%B3%E3%83%88%E6%AC%84%E3%81%A7-,%E8%AA%AD%E3%81%BF,-%E3%82%92%E3%82%AF%E3%83%AA%E3%83%83%E3%82%AF%E3%81%99%E3%82%8B)
- 直接入力欄(話速の直接入力欄、みたいな感じ)
  - 「パラメータの直接入力（欄）」で！
- 調整スライダー(アクセント調整スライダー、みたいな感じ)
  - [スライダー](https://voicevox.hiroshiba.jp/how_to_use/#:~:text=%E6%AC%84%E3%82%92%E8%A1%A8%E7%A4%BA-,%E3%82%B9%E3%83%A9%E3%82%A4%E3%83%80%E3%83%BC,-%E3%81%AE%E4%B8%8A%E3%81%A7)
- アクティブな行(キャラ選択欄の左に三角が表示されてる行)
  - 「選択中のレーン」・「選択中のテキスト欄」

追加で

- アクセント区間内の１文字
	- [文字ごと](https://voicevox.hiroshiba.jp/how_to_use/#:~:text=%E3%81%95%E3%81%AE%E5%A4%89%E6%9B%B4-,%E6%96%87%E5%AD%97%E3%81%94%E3%81%A8,-%E3%81%AB%E3%80%81%E9%9F%B3%E3%81%AE)・「文字ごとの区間」･･･？

気になったのですが、機能と一対一対応しているボタンはそのままの機能の名称+UIの名称を使うだろうな～と思いました。
そうなると機能１つ１つに名前をつけて行った方がいいかもですね･･･････！ 😇

**Comment by thiramisu** [comment]
使い方内でも微妙に表記ゆれしてたりしたので、さくっと決めていただけて助かります！
機能名は「使い方」の見出しか「メニュー」の項目名そのままで良いと思うんですが、他に必要そうなものとかはありますかね…？

**Comment by thiramisu** [comment]
アクセント区間、現状だと「[単語](https://voicevox.hiroshiba.jp/how_to_use/#:~:text=%E3%82%89%E3%82%8C%E3%81%BE%E3%81%99%E3%80%82-,%E5%8D%98%E8%AA%9E,-%E3%81%AE%E6%8E%A5%E7%B6%9A%E5%A4%89%E6%9B%B4)」も近いですね。
発音上「アクセント句」が含まれてるのが結構好きですが、不正確さが許容できるなら「単語」もアリだと思います。

使い方から漏れている説明を洗い出すために、試しにUI逆引きを作ってみました。
管理コストを考えると実際に追加すべきではないかもしれませんが、参考になれば。

使い方になかったもの(説明は結構適当です)
音声の生成・再生 ← 音声の生成 から名前変更

文章の追加 ← 文章の追加・削除 から名前変更

アクセント区間の結合・分割？ ← 単語の接続変更 から名前変更？

無声化・有声化 ← イントネーションの変更 から分離？

文章の削除
テキスト欄にマウスカーソルを合わせると出てくるゴミ箱のボタンから、そのテキスト欄を削除できます。

読む区間の指定
アクセント区間をクリックすることで、その区間だけを読ませることができます。

行番号の表示
設定 / オプション から行番号を表示できます。

パラメータ
(説明難しいので省略でもいいかも…)

プリセット
(UI複雑なので説明も多分複雑)

----

# UI逆引き

## メニュー
できること
[音声ファイルの書き出し]
[テキストを繋げて書き出し]
[プロジェクトファイルの保存・読み込み]
[テキストファイルの読み込み]
[オプション]
関連
[ショートカットキー]
関連オプション
[保存項目]

## ピンボタン
ウィンドウを最前面に固定できます。

## ツールバー
いくつかの機能がボタン1つで実行できます。
関連機能
[ツールバーのカスタマイズ]

## キャラクター表示欄
選択中のテキスト欄のキャラクターの立ち絵・名前とスタイル名が表示されます。

## 台本欄
読ませたい文章と、誰に読んでもらうかを設定できます。
### 行番号
関連オプション
[行番号の表示]

### キャラクターアイコン
選択中のテキスト欄を読むキャラクター・スタイルのアイコンが表示されます。
また、左側に選択中のテキスト欄を示す小さい三角形が表示されます。
できること
[キャラクターの変更]
[スタイルの変更]
関連機能
[キャラクターの並び替え・視聴]
[デフォルトスタイル]

### テキスト欄
ここに読んでほしいテキストを入力します。
できること
[音声の生成・再生]
[文章の削除]
[テキスト欄の並び替え]
関連オプション
[テキストの分割箇所]

### テキスト欄追加ボタン
できること
[文章の追加]
関連オプション
[テキスト追加ボタンの表示]

## パラメータ調整欄
テキスト欄全体の読み方を調整できます。
関連機能
[プリセット]
関連
[パラメータ]

## 詳細調整欄
区間や文字単位での細かい読み方を調整できます。
関連オプション
[再生位置を追従]

### アクセント項目
アクセント区間ごとにアクセントがどこにあるかが表示されます。
できること
[読みの修正]
[アクセントの変更]
[読ませるアクセント区間の指定]
[アクセント区間の結合・分割]
関連機能
[読み方&アクセント辞書]

### イントネーション項目
文字ごとにイントネーションが表示されます。
できること
[イントネーションの変更]
[無声化・有声化]
[アクセント区間の結合・分割]
関連オプション
[疑問文を自動調整]

### 長さ項目
母音・子音ごとに長さが表示されます。
できること
[音の長さの変更]
[アクセント区間の結合・分割]

### 再生ボタン
できること
[音声の生成・再生]
関連機能
[読ませるアクセント区間の指定]

## ヒント
使い方のヒントが表示されます。
関連オプション
[非表示にしたヒントを全て再表示]
