### ISSUE TITLE
ブラウザ版はFirefoxでは音声が再生できない

### ISSUE THREAD

**Issue by sh1ma** [VOICEVOX/voicevox#1405]
## 不具合の内容

ブラウザ版のEditorは現状Firefoxで音声が再生できません。現リリース版Firefox115.0.2では`HTMLMediaElement.setSinkId()`というAPIに対応していないためです。
https://developer.mozilla.org/ja/docs/Web/API/HTMLMediaElement/setSinkId#%E3%83%96%E3%83%A9%E3%82%A6%E3%82%B6%E3%83%BC%E3%81%AE%E4%BA%92%E6%8F%9B%E6%80%A7

### 現象・ログ

Firefoxで音声合成を実行したあと、再生することができません。

```
TypeError: audioElem.setSinkId is not a function
    action audio.ts:1800
    createUILockAction ui.ts:22
    wrappedActionHandler vuex.esm-bundler.js:305
    dispatch vuex.esm-bundler.js:1032
    boundDispatch vuex.esm-bundler.js:914
    action audio.ts:1762
    createUILockAction ui.ts:22
    wrappedActionHandler vuex.esm-bundler.js:305
    dispatch vuex.esm-bundler.js:1032
    boundDispatch vuex.esm-bundler.js:914
    play AudioDetail.vue:496
    callWithErrorHandling runtime-core.esm-bundler.js:157
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:166
    emit$1 runtime-core.esm-bundler.js:714
    navigateOnClick quasar.esm.js:2968
    onClick quasar.esm.js:3700
    callWithErrorHandling runtime-core.esm-bundler.js:157
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:166
    invoker runtime-dom.esm-bundler.js:345
[sandbox.ts:205:12](http://localhost:5173/Users/sh1ma/Projects/github.com/VOICEVOX/voicevox/src/browser/sandbox.ts)
    logError sandbox.ts:205
    play AudioDetail.vue:505
    callWithErrorHandling runtime-core.esm-bundler.js:157
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:166
    emit$1 runtime-core.esm-bundler.js:714
    navigateOnClick quasar.esm.js:2968
    onClick quasar.esm.js:3700
    callWithErrorHandling runtime-core.esm-bundler.js:157
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:166
    invoker runtime-dom.esm-bundler.js:345
```

### 再現手順

ブラウザ版を実行後、Firefoxでアクセスし音声再生をしようとすると発生します。

### 期待動作

合成した音声が再生される

## VOICEVOXのバージョン

ブラウザ上で確認したところ、0.14.7となっていました。

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [x] macOS
- [ ] Linux

Firefox115.0.2

## その他

音声再生時に現状最速でエラーになる箇所がここというだけで、他にも特定のブラウザではエラーになる箇所が潜在している可能性があるかもしれません。

このAPIに関してはPolyfillのしようがないので、現状この挙動に対応することはできないと思われます。

## 追記

[8月1日のFirefox 116リリース](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/116)によってこのAPIは対応されることがわかりました！

**Comment by sh1ma** [comment]
[エラーの発生した箇所 https://github.com/VOICEVOX/voicevox/blob/7a597e76885b6c4993de5ae44c6669b14d096242/src/store/audio.ts#L1799-L1813]についてコメントアウトし実行したところ、音声の再生が可能になりました。
ただし当該箇所をコメントアウトすると音声を出力するデバイスを選択することはできなくなると思われます。

**Comment by Hiroshiba** [comment]
ご報告ありがとうございます！
一旦`setSinkId`が未実装であればそのコードを実行しない形が良さそうに感じました。
（ちなみにFirefoxではVOICEVOX内のデバイス選択設定もできなさそうですが、どうでしょうか 👀 ）

**Comment by sevenc-nanashi** [comment]
![image](https://github.com/VOICEVOX/voicevox/assets/59691627/24560b19-6654-40b2-8e44-83f0a97c4dcc)
未実装だったら隠すPRを作っています。

**Comment by thiramisu** [comment]
どのブラウザをサポートするのか決めたほうが良い気がします。Chrome/Edgeで85%あるので、宗教上の理由で使いたくない場合はexe版をDLしてもらうのが良い気がするのですがどうでしょうか？
[日本におけるデスクトップPCのブラウザシェア率](https://gs.statcounter.com/browser-market-share/desktop/japan)

**Comment by Hiroshiba** [comment]
@thiramisu 
正式サポートするのは確かにChrome系だけで良さそうですね！
でもまだ実現難易度が分かっていないので決めることはできないです。調査段階かなと。
Chromeですら正確に実装することが難しいのであれば、ブラウザ版は全部正式サポートしないという方針もありえるかもです。

でもまあ正式サポートしてなくても、誰か解決と思われる方がいて、その実装がメンテコストが高くないのであればマージする方針でいいかな～と思ってます！
