### ISSUE TITLE
エンジン起動中にキー入力などをするとその後キーが効かない場面がある

### ISSUE THREAD

**Issue by thiramisu** [VOICEVOX/voicevox#1416]
## 不具合の内容
エンジン起動中にキー入力やマウス入力をすると、その後、メニューで [Enter] キーが効かなくなったり、[アプリケーション] キーでコンテキストメニューが開けなくなったりします。
`mousetrap`由来の`keydown`イベントを削除すると効くようです。

### 現象・ログ
開発者ツール上ではエラーやログは出ません。

### 再現手順
1. エンジン起動中にキーやマウスボタンを押しまくります(実際は多分1回クリックかキー入力すれば十分です)。
2. 起動完了したら、[Shift] + [Tab] キー連打でメニューの[設定]に合わせます。
3. [Enter] キーで小メニューに入ります(これは反応します)。
4. [Tab] キーで [ツールバーのカスタマイズ] などに合わせます。
5. [Enter] キーを押しても何も起きません。

### 期待動作
[Enter] キー押下とマウスクリックが同じ動作をする。

## VOICEVOXのバージョン

0.14.7
mainブランチ最新版でも確認しました。

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

Windows 11 Home 22H2

## その他

メニューだけなら`@keydown.enter.exact`で`document.activeElement.dispatch(new Event("click"))`すれば多分直りますが、もう少し根本的に直したいところです。

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！！

こちらでも試してみたのですが確かにそのような挙動になっていました。
エンジン開始画面で連打するというよりは、テキスト欄を1回クリックすると発動してるかも･･･？

ちょっと行けるかどうか分かってないのですが、ダイアログやなどを開いた時にmousetrapの`Pause/unpause`を制御して透過させることができるかも･････？

**Comment by thiramisu** [comment]
#1374 で一旦直ったと思うので、closeします。
もし他の部位で再発した場合、`stopCallback`の中身を再検討すると直ると思います。
