### ISSUE TITLE
辞書機能の読みのIME確定時に`@keydown.enter`が発火する

### ISSUE THREAD

**Issue by thiramisu** [VOICEVOX/voicevox#1426]
## 不具合の内容
#1394 が原因で(多分)発生しているバグです。
IME確定時の [Enter] で`@keydown.enter`も一緒に呼ばれます。
#976 によれば、MAC向けには`isComposing`が必要なようです。
Windowsでは問題なく動作したため気付けませんでした、申し訳ないです。

### 期待動作
発火しない。

## VOICEVOXのバージョン

999.999.999

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [x] macOS
- [ ] Linux

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！！！
気づいていませんでした、すみません･･･。
