### ISSUE TITLE
「反映には再起動が必要です」をPC本体の再起動が必要と誤解する可能性

### ISSUE THREAD

**Issue by nohimazin** [VOICEVOX/voicevox#1430]
## 内容

タイトルの通り
![image](https://github.com/VOICEVOX/voicevox/assets/139631966/697fba38-b383-4c46-8c9a-73e91b207611)

### 実現方法

「VOICEVOXの」を追加

## VOICEVOXのバージョン

0.14.7

## OSの種類/ディストリ/バージョン

- [x] Windows
- [x] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
issueありがとうございます！　マージさせて頂きました 🙏
