### ISSUE TITLE
トースト(toast）の背景色が半透明になっていて文字とかぶると見づらいのを何とかする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1432]
## 内容

タイトルの通りです。

このような形で半透明になっています。
![image](https://github.com/VOICEVOX/voicevox/assets/4987327/6f72468d-f1e4-42a5-91b5-7c5bf0e3733c)
（https://github.com/VOICEVOX/voicevox/pull/1404　の画像を引用しています thx @thiramisu !）

背景色の問題が解決するとこの課題は解決だと思います。

### Pros 良くなる点

文字にかぶっても見づらくなくなる。

### 実現方法

今primary色の背景にしていますが、そういう色を作る手がありそうです。
新たにprimary-surfaceを作るか、あるいはsurfaceとprimaryの色を自動で混ぜるとか･･･？

もしくは、将来的に成功・失敗・ワーニングの通知をしたくなったときに色を分ける必要が出てくるので、primaryを使用するのはやめて、successカラーを使うという手もあると思います。
https://quasar.dev/quasar-plugins/notify#predefined-types

**Comment by Hiroshiba** [comment]
- https://github.com/VOICEVOX/voicevox/pull/1404

で一緒に解決してくださるかもで、衝突しないようにメモコメントをば！

**Comment by thiramisu** [comment]
すみません、closeをつけ忘れていました…。
上記PRで解決したので、closeしていただけると助かります。
