### ISSUE TITLE
マウスホイールでパラメータ調整欄のスライダーを調整できない

### ISSUE THREAD

**Issue by sevenc-nanashi** [VOICEVOX/voicevox#1437]
## 不具合の内容

タイトル通りです。

### 現象・ログ

https://github.com/VOICEVOX/voicevox/assets/59691627/55f4b9ac-fbb5-4005-99a9-be6024c35722

### 再現手順

動画参照。

### 期待動作

つまみが戻らない。

## VOICEVOXのバージョン

0.15.0-checkshellbash.0

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

## その他

（なし）

**Comment by Hiroshiba** [comment]
報告ありがとうございます！！

これかなり問題ですね･･･。
修正されないとリリースできないレベルなので、優先度を最大まで上げたいと思います。
