### ISSUE TITLE
テーマの`primary-light`が実質使われていないのを整理する

### ISSUE THREAD

**Issue by thiramisu** [VOICEVOX/voicevox#1447]
## 内容
`primary-light`はダークテーマ登場前に以下の意図で定義されたということです。
>> 用途を覚えてないんですが、lightテーマのprimaryという意図だったかも･･･。
> 
> それ、最初はダークテーマにも緑色になる部分の色としたかったんですね。今のダークテーマだとあんまり重要性がないので、消してもいいと思います。
> (https://github.com/VOICEVOX/voicevox/pull/1404#issuecomment-1656093509 より)

が、その後結局`color.scss`で分岐させる形に整理(#894)されたため、`default.json`と`dark.json`の両方で`primary`と`primary-light`の値が同じで、意味を成していません。
これを整理したいです。

### Pros 良くなる点
- 謎の定義が消える

### Cons 悪くなる点
- なし？

### 実現方法
そのまま`primary`に統合するのが早そうです。
(ユーザーがtheme.jsonを作れる「カスタムテーマ機能」(#865)的なのが実装された時に差が出てくるかもしれないので、json側に残した方が良い理由がありそうであればお聞きしたいです)

また、`色について.md`も正確な記述に書き換えが必要です。

**Comment by Hiroshiba** [comment]
issue作成と整理ありがとうございます！！
需要が生まれるまでは削除が良いのかなと思いました！！
