### ISSUE TITLE
一括出力失敗時のダイアログを外側クリックで閉じられるようにする

### ISSUE THREAD

**Issue by sevenc-nanashi** [VOICEVOX/voicevox#1449]
## 内容

タイトル通りです。

### Pros 良くなる点

![image](https://github.com/VOICEVOX/voicevox/assets/59691627/b20404cc-0fe9-451e-9052-b7fb3301f9e6)

このような状態の時にスクロールする手間がなくなる。Enterキーでも閉じられはしますが気がつく人は多分少ないです

### Cons 悪くなる点

ないはず？

### 実現方法

ダイアログを出すときに「外側クリックでも閉じられるようにする」オプションがあったはず？

## VOICEVOXのバージョン

（開発版）

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

## その他

（なし）

**Comment by Hiroshiba** [comment]
issueありがとうございます！！

> Cons 悪くなる点

間違えて閉じちゃえるのは悪くなる点かもです。

どれだけ長くてもスクロール領域は狭めて、一番下にある「確認」ボタンが最初から表示されてるようにするのが丸いかも･･･？

**Comment by sevenc-nanashi** [comment]
> 間違えて閉じちゃえるようになるのは悪くなる点かもです。

正直、AviUtlとか開いてるとEBUSYが出るのを理解している（確定している？）ので余り気にしないような気もします。EBUSYだけなら閉じられる様にするとかいうのも思いつきましたが、

> どれだけ長くてもスクロール領域は狭めて、一番下にある「確認」ボタンが最初から表示されてるようにするのが丸いかも･･･？

これが丸そう。

**Comment by thiramisu** [comment]
#1404 でまとめたところですね。ただレシートみたいな長いログが出るのは想像できていなかったので、そこだけ共通化部分から外してしまってもいい気がします。

**Comment by sevenc-nanashi** [comment]
おっと、 0.15.0-checkshellbash.0で試してました。最新のmainでちょっと試してみます

**Comment by Hiroshiba** [comment]
タイトル横のボタンでも良いと思うのですが、UXを揃えるならまあ「ダイアログ＝右下にボタン」がベターだろうなという気持ちです！
