### ISSUE TITLE
Mac版をHomebrewでインストールできるようにしたい

### ISSUE THREAD

**Issue by umi1299** [VOICEVOX/voicevox#1451]
## 内容

VOICEVOXのMac版をHomebrewでインストールできるようにしたいです。

### Pros 良くなる点

Homebrewを利用している人にとってインストールやアップデートが簡単になります。

### 実現方法

Homebrewによるインストールとアンインストールができることを以下のリポジトリで確認しました。

[umi1299/homebrew-voicevox](https://github.com/umi1299/homebrew-voicevox)

このリポジトリをフォークしていただくか、同じ内容のリポジトリを作っていただくことで、以下のコマンドでVOICEVOXをインストールできるようになります。

```bash
$ brew tap VOICEVOX/voicevox
$ brew install --cask voicevox
```

## VOICEVOXのバージョン

0.14.7

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [x] macOS Ventura
- [ ] Linux

## その他

[Homebrew/homebrew-cask](https://github.com/Homebrew/homebrew-cask)にPRを出すことも考えたのですが、以下のエラーが発生したため現状はできなさそうです。

```sh
$ brew audit --new-cask voicevox
==> Downloading https://github.com/VOICEVOX/voicevox/releases/download/0.14.7/VOICEVOX.0.14.7.dmg
Already downloaded: /Users/UserName/Library/Caches/Homebrew/downloads/045ea8c6a95afbd0b72140f428272c52db8af5ba9928bd7b5af44be710eb5076--VOICEVOX.0.14.7.dmg
audit for voicevox: failed
 - Signature verification failed:
/private/tmp/d20230802-97753-15smhh8/VOICEVOX.app: rejected

macOS on ARM requires software to be signed.
Please contact the upstream developer to let them know they should sign and notarize their software.
umi1299/cask/voicevox
  * line 5, col 2: Signature verification failed:
    /private/tmp/d20230802-97753-15smhh8/VOICEVOX.app: rejected

    macOS on ARM requires software to be signed.
    Please contact the upstream developer to let them know they should sign and notarize their software.
Error: 1 problem in 1 cask detected.
```

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！！

個人的には差分が少ないので、あとはメンテナンスコストがほぼなければアリだなと思いました！
`.rb`ファイル内でバージョン指定が必要なのが結構厄介ですね･･･！いつか変え忘れると思います 😇 

何も指定しなかった場合はlatestを取ってくるようにする、というのはどうでしょうか？
GithubのAPIを叩いて最新のバージョンを取得し、その値をversion変数に入れれば実現できるのかなとか思いました。
一般的なhomebrewの挙動と異なるかもしれませんが･･･。

あるいはreleasesに`.rb`ファイルを配置できると一番良さそうに思いました。
そういった仕様はhomebrew側にあったりしそうでしょうか？

@y-chan 
Casksディレクトリですが、このリポジトリ内でメンテすべきかどうかどう思われますか？ 👀 
releasesに乗っける方法があれば最高なのですが。。

**Comment by y-chan** [comment]
軽く調べてみたのですが、homebrew用に「フォーミュラ」というもの(`.rb`)を管理するために`homebrew-...`と言った感じのリポジトリを一個作らないといけないようでした。
なので、このリポジトリに統合することは無理そうな感じでした。
リポジトリが一つ増えるのは、あまり好ましくないかもですが、そこまで大きなものを管理するわけではないのでいいかなと。
あと、自動化だったりの手段はありそうだと感じたので、GitHub Actions等でリリース時にフォーミュラを自動更新する用に組んでしまえば、VOCIEVOX側でフォーミュラを管理するのは特に負荷がかからず良いのかなと感じました。
(過去バージョン等を一括管理できる仕組みだと思うので、リリースされたときにどんどん`.rb`にバージョン情報を追加する仕様にすればバージョン切り替えとかもしやすくていいのかなと(VOICEVOXの場合、バージョンを下げる利点はあまりないですが))

@.umi1299 さんに、GitHub Actionsを用いた自動化を含めて興味があり、取り組んでいただけるのであれば、VOICEVOX公式としてhomebrewリポジトリを用意するのはアリかなと思いました。

どうでしょうか？

**Comment by umi1299** [comment]
検討ありがとうございます！
GitHub Actionsを用いた自動化も気になるのでひとまず自前のリポジトリで試してみようと思います！

> 過去バージョン等を一括管理できる仕組みだと思うので、リリースされたときにどんどん.rbにバージョン情報を追加する仕様にすればバージョン切り替えとかもしやすくていいのかなと

`VOICEVOX/homebrew-...` というリポジトリを用意する方針であれば `voicevox@0.14.7.rb` や `voicevox@0.14.6.rb` といったファイルを複数用意することで過去のバージョンを管理することが可能だと思います。
ちなみに[Homebrew/homebrew-cask](https://github.com/Homebrew/homebrew-cask)は最新のバージョンしか管理しない方針らしいです。

**Comment by umi1299** [comment]
一応、形になったので報告します。
手段は以下の2通りがあり、自動でPRが作成されるところまで確認できました。

1. このリポジトリにリリース時にトリガーされるGitHub Actionsを追加する
2. `homebrew-...` リポジトリにcronで定期実行するGitHub Actionsを追加する

1のパターンは #1464 で、2のパターンは [umi1299/homebrew-voicevox/.github/workflows/autobump.yml](https://github.com/umi1299/homebrew-voicevox/blob/4a47e59706d73c198ee695dbe8b140c8209e2415/.github/workflows/autobump.yml) でファイルを確認できるのでご覧ください。

なお、これらのActionsを使用するためにはリポジトリのsecretsに[public_repoを有効にしたパーソナルアクセストークン](https://github.com/settings/tokens/new?scopes=public_repo,workflow)をセットする必要があるのですが、そのトークンのユーザーとしてコミットなどが行われるため[マシンユーザーアカウント](https://docs.github.com/ja/get-started/learning-about-github/types-of-github-accounts#personal-accounts)があればそれを利用するのがよいと思います。

Actionsの仕組みですがまず、Homebrewに [`brew bump-cask-pr` というコマンド](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request#submit-a-new-version-of-an-existing-cask)があります。
このコマンドはCaskの更新のためにリポジトリのフォーク・コミットのプッシュ・PRの作成までを自動で行ってくれます。
今回はこのコマンドを利用している[Homebrew bump cask](https://github.com/marketplace/actions/homebrew-bump-cask)というActionsがあったのでそれを使用しています。

ここで相談なのですが `brew bump-cask-pr` を使用しているため、現状は新しいリリースがあったときに `homebrew-...` リポジトリにPRが作られるまでになっています。
これはPRの自動マージまでやった方が良いでしょうか？
自動でマージして良い条件を考えるのがちょっと難しそうかなと思っています。

また、過去のバージョン管理をすることについて、これは作るのが大変そうなのと @y-chan さんの仰るとおりVOICEVOXはバージョンを下げる利点が特にないと思うので、まずはなくても良いかと思うのですがどう思われますか？

**Comment by Hiroshiba** [comment]
ありがとうございます、めちゃくちゃ分かりやすいです！！

`homebrew-voicevox`リポジトリ側でcron実行＋過去バージョンはサポートしない、がいいのかなと思いました！

まずリポジトリに関して、権限が必要になる物をリポジトリ単位で分けたいなという思いがちょっとだけあるので、まあクーロン実行でのがいいのかなと！

> 自動でマージ

こちらは一旦なくていいのかなと思いました！
あった方が良さそうなのですが、そもそも発生頻度が低そうなのと、やっぱり条件を定めるのが大変そうなので。
もしちょっと大変だなと思い始めたらちょっと相談するかもしれません！

> 過去バージョン

おっしゃる通りで、とりあえず最新版だけでいいのかなと！

**Comment by umi1299** [comment]
確認ありがとうございます！

> `homebrew-voicevox`リポジトリ側でcron実行＋過去バージョンはサポートしない

こちら了解致しました！
#1464 はクローズしちゃいますね。
`homebrew-voicevox`リポジトリの作成お願いします！

自動マージと過去バージョンについても了解致しました！

**Comment by Hiroshiba** [comment]
@umi1299 リポジトリ作成しました！！
https://github.com/VOICEVOX/homebrew-voicevox

**Comment by umi1299** [comment]
ありがとうございます！

**Comment by umi1299** [comment]
@Hiroshiba 作成していただいたリポジトリなのですが https://github.com/VOICEVOX/voicevox/pull/1464#issuecomment-1664818502 に書いたように、中身を[umi1299/homebrew-voicevox](https://github.com/umi1299/homebrew-voicevox)内の `umi1299/voicevox` を `VOICEVOX/voicevox` に置換したものにしていただきたいです！
ライセンスは[Homebrew/homebrew-cask](https://github.com/Homebrew/homebrew-cask)に倣ってBSD 2-Clauseにしていたのですが、MITに変えていただいて問題ないです！

**Comment by umi1299** [comment]
@Hiroshiba もしくは、こちらからPR出した方がよいでしょうか？

**Comment by umi1299** [comment]
@Hiroshiba お聞きしたいことを1つ忘れていました。
ファイル内にアプリの説明を記述する `desc` 欄があって、今は `無料で使える中品質なテキスト読み上げソフトウェア` を英訳して `Free, medium-quality text-to-speech software` としているのですが、公式な英語のキャッチフレーズなどありますでしょうか？

**Comment by Hiroshiba** [comment]
@umi1299 色々ありがとうございます！
`BSD 2-Clause`でも問題ないので変えた方が良さそうな場合は言っていただければ！！

プルリクエストをお願いします！
せっかく @umi1299 さんが開発したものなので、その名前を記録に残していければ･･･！

descに関して検討しましたが、`Free, medium-quality text-to-speech software`を公式の英語キャッチコピーにしたいと思います。
なのでそのまま適用いただければ！

**Comment by umi1299** [comment]
PRを3つ出しました！
ご確認お願いします！

**Comment by Hiroshiba** [comment]
あ、ご連絡ありがとうございます！

**Comment by umi1299** [comment]
マージ&紹介ありがとうございました！
