### ISSUE TITLE
mac版にlogsディレクトリが無い

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1452]
## 不具合の内容

mac版にlogsディレクトリが無い気がします。
本来であればconfig.jsonと同じディレクトリにあるはず･･･？

想定場所は`/Users/(ユーザー名)/Library/Application Support/voicevox/logs`です

## VOICEVOXのバージョン

0.14.7

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [x] macOS
- [ ] Linux

## その他

ここがlogディレクトリの取得箇所です。

https://github.com/VOICEVOX/voicevox/blob/01729f45a70f86aff2a43842d56eb68a1e5c4159/src/background.ts#L92

**Comment by y-chan** [comment]
どうやらMacのログディレクトリは`/Users/<user>/Library/Logs/voicevox`のようです。
これを案内として書き足すべきかもしれませんね...

**Comment by umi1299** [comment]
別件で調べていたのですが、ログディレクトリは `/Users/<user>/Library/Logs/voicevox-cpu` に作られることを確認しました。
ディレクトリ名は `voicevox` ではなく `voicevox-cpu` みたいです。

**Comment by Hiroshiba** [comment]
あ〜なるほどです。dev版はvoicevoxディレクトリだけど、リリースされている方はvoicevox-cpuですね。。
ちなみになかなか[深い理由](https://github.com/VOICEVOX/voicevox/issues/337)があったりします。（リリースするときにGPU版と名前が被ってしまうから分けただけですが）

とりあえず案内先を`/Users/<user>/Library/Logs/voicevox-cpu`にするのが応急処置としていいのかなと思いました！
プルリク作ろうと思います。
