### ISSUE TITLE
background.tsでアプリの名称をvoicevoxとしてsetする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1456]
## 内容

VOICEVOXはCPU版とGPU版がある関係で、ビルド時にアプリの名称（productName）をやむなく分けています。

- https://github.com/VOICEVOX/voicevox/pull/306

これがアプリ固有のディレクトリの名称にも影響を与えていて、いくつかの問題を引き起こしています。

- https://github.com/VOICEVOX/voicevox/issues/337
- https://github.com/VOICEVOX/voicevox/issues/1452

いっそのこともう[`app.setName`](https://www.electronjs.org/ja/docs/latest/api/app#appsetnamename)でアプリの名称を動的に変えちゃうのもありかなと思いました。
background.ts内でアプリの名称を変更し、問題がないことを確認できたらこの課題は解決かなと。

### Pros 良くなる点

CPU版とGPU版の名前の影響に怯えなくて済む

### Cons 悪くなる点

ないはずだけど、問題が起こらないか検証がいろいろ必要

### 実現方法

background.tsの上の方で`app.setName("voicevox")`的なことを書けばよさそう。
開発版とかは名称を分けた方が分かりやすいと思うので、[suffix](https://github.com/VOICEVOX/voicevox/blob/01729f45a70f86aff2a43842d56eb68a1e5c4159/src/background.ts#L67-L73)はつけた方が良さそう。

ただ設定ファイルの場所のマイグレーションコードもあるので要注意。
多分この`beforeUserDataDir`のコードよりも下でsetNameすれば問題ない･･･？
https://github.com/VOICEVOX/voicevox/blob/01729f45a70f86aff2a43842d56eb68a1e5c4159/src/background.ts#L76

## その他

リポジトリをフォークした後Github Actionsでbuild.ymlをworkflow_dispatchすれば自動ビルドしてReleasesにアップロードされるので、色々問題なさそうかをそこでチェックできると思います。

**Comment by g-Ratie** [comment]
こちら取り組んでみます。

**Comment by Hiroshiba** [comment]
@g-Ratie コメントありがとうございます！！是非よろしくお願いします！！

**Comment by Hiroshiba** [comment]
取り組みありがとうございます！closeしました！
