### ISSUE TITLE
VOICEVOXのリリース戦略を考えたい

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#147]
VOICEVOXバージョン0.4.0の際、次の問題が起こりました。

* エンジン・ソフトウェアの両方を一緒にアップデート
* ソフトウェア側でバグが見つかる
* ソフトウェア側でhotfixを入れ、0.4.1にバージョンアップ
* エンジン側もバージョンを0.4.1にしたいが、すでに別プルリクエストをマージ済みで0.4.0から仕様変更が入ってしまう

とりあえずエンジン側のバージョン0.4.0からreleaseブランチを切ってバージョン0.4.1にすることで問題を回避しましたが、もう少し戦略を建ててリリースしていきたいです。
どうすればいいか、議論したいです。

**Comment by Hiroshiba** [comment]
少なくとも、コミッターの方がブランチ戦略を意識しなくても、問題なく回るような構成にしたいです。

**Comment by Hiroshiba** [comment]
方針を考えてみました。

![image](https://user-images.githubusercontent.com/4987327/130469571-f20f6978-7aee-4a01-a917-b7d550a5e11f.png)

* プルリクエストは基本的にmainブランチから発生し、mainブランチにマージされます
* 大きなリリース時（major.minor.fixのminorバージョンアップ）に、releaseブランチを作ります
* hotfixがあった場合、releaseにhotfixプルリクエストをマージし、fixのバージョンをあげます
* リリース時はプルリクエストをmainブランチにマージするのを一旦止めます
* リリースバージョンはTAGで管理します

**Comment by isnot** [comment]
@Hiroshiba さんの方針を踏まえつつ、私のアイデアを図にしてみました。
「コミッターの方がブランチ戦略を意識しなくても〜」という点を重視しつつ、リリース作業はほぼGit Flowと差異ない作業フローになります。
図中の※ですが、現状で言うとメンテナは、実際 @Hiroshiba さんおひとりです。
ご検討の参考にしていただければ幸いです。

![voicevox_branch_strategy_idea_by_isnot](https://user-images.githubusercontent.com/21094354/130595706-e5fcc57b-4795-4486-b8fb-dfa04dbbddb8.png)
元の図『@IT 【図解】git-flow、GitHub Flowを開発現場で使い始めるためにこれだけは覚えておこう』より
一部改変・編集して作成

**Comment by Hiroshiba** [comment]
git flowのデメリットはもう１つあるかなと感じていて、hotfixやreleaseをdevelopとmasterにそれぞれ別々にマージする必要があり、このマージ処理が必ず同じになるようメンテナーが気をつける必要があります。
つまり人為的ミスによりリリースバージョンと開発バージョンのコードが分離する可能性があるということです。
この点はいかがでしょう 👀

**Comment by isnot** [comment]
> つまり人為的ミスによりリリースバージョンと開発バージョンのコードが分離する可能性があるということです。
> この点はいかがでしょう

ご指摘のような懸念は、実際に起こり得ると思います。
例としてhotfixの公開を急ぐ時に、masterやdevelopへのマージに手間取るよりは、手元のworkspaceでビルドしたものを使ってビルド、公開することさえ、想定されると思います。
そしてそれは、後から（もしくは気付いた段階で）修正できるだろうと思います。手間はかかりますが。

あとは如何に気付くか、そして、どのようにして負担を軽減できるかという部分でしょうか。
ひとつの解決策は、先にあげたようにメンテナ人員を増やして手数をかけることと、もうひとつはCI/CDを充実することだと思います。

**Comment by isnot** [comment]
「ミスが起こり得ること」について気にしていらっしゃるようにお見受けしましたが、
releaseからmasterへマージ完了したタイミングにhookして、developへのPRを出すような自動化はあるかと思います。
後は、ある程度は手動で介入できる余地があるというのも、イレギュラーへの対応ができる余地と捉えることはできないでしょうか。

**Comment by Hiroshiba** [comment]
あ！　気になっているのはマージし忘れではなく、hotfixにコンフリクトが発生する場合です。
releaseとdevelopで別のコンフリクト解消をしてしまう可能性があります。

**Comment by Hiroshiba** [comment]
CI/CDの充実とメンテナの増員は仰るとおりで、すごく魅力的だと思う一方、やはり開発リソースが足りないのが課題かなと感じています。開発コミュニティを大きくしようとするのが手なのかなぁと思いつつ、どういう手段が有効なのかわからないのが現状です。

**Comment by isnot** [comment]
> あ！　気になっているのはマージし忘れではなく、hotfixにコンフリクトが発生する場合です。
> releaseとdevelopで別のコンフリクト解消をしてしまう可能性があります。

仮定の話に終始してしまうのは申し訳ないのですが、
Git Flowでhotfix作業し、いざマージしようという時、おそらくmasterとの間のマージはスムーズで、developへのマージでコンフリクトが起こりやすくなるはずです。
関わる人数、ブランチ、コード変更行数の数字から、確率的に類推できます。
であるならば、先にdevelopとの間のコンフリクト解消（手動にならざるを得ない）をして、その次（手動か、自動）にmasterへマージするのがいいかもしれないですね。

**Comment by Hiroshiba** [comment]
マージの順番を変えてもコンフリクト解消によって実装が乖離する可能性は変わらないかも？
いろいろ考えていたのですが、そもそもリリースとhotfixという概念がある以上この実装の乖離は避けて通れなそうなので、一旦スルーしても良いなと思いました🙇

git-flow、良いと思います。ただmasterとdevelopのブランチが常に存在しているのがメンテナの負担になっちゃうので、もうすこし楽な https://github.com/Hiroshiba/voicevox/issues/147#issuecomment-903853290 の方針が良いかなと思いました。
（git flowからmasterの概念をなくして、マイナーバージョンのたびに新しいbranchを作る戦略です。
hotfixが発生しなかった場合はTAGを付けるだけで終わるので楽なはず。）

**Comment by isnot** [comment]
@Hiroshiba さん。丁寧に回答くださり、ありがとうございます。
またしても長文になってしまいますが、失礼します。

ます、前半について了解です。
私の趣旨もより楽できるのはどちらか？であって、トラブルは起こり得るだろうというのは先の発言の通りです。
今は気にしすぎないで良いと思います。
先の困難を想像して、改善を立ち止まってしまうことはないと思います。

次に後半。
私の中でも、masterをメンテする手間に関しては、ちょっと引っ掛かりがありました。
私の図の中では、developとmasterの関係は本来のGit Flowと違っていて、矢印の向きが逆になっていることにお気づきでしょうか。
Git Flowを教条的に遵守するという考えはなくて、単に説明が楽なので改変は少ないほうがいいのかなと思っていただけなのです。
しかしこうして会話してみて、現状のリソースにあったカスタマイズは、考えなくてはと思い直しました。

[ヒホさんの図](https://github.com/Hiroshiba/voicevox/issues/147#issuecomment-903853290) について気になる点を率直に申します。
これだけを見る限りはGitHub Flowと変わりがなく、また本件Issueの冒頭にある0.4.0リリース以前に行われていた作業フローとも、差がないという印象を受けました。
このIssueを通して、作業フローを明確化し、他のコミッターへ知っていただくという効果はあるでしょうが、フローそのものを改善しているのかについては、私には見えてこなかったのです。

その点を踏まえて、私の図に修正を加えました。

- masterは常に、developからのみpullします
- hotfixとreleaseからmasterへのマージはなくします
- releaseのブランチ開始の直前にdevelop→masterへpullし、そこをブランチの起点にします
- これによって、masterでコンフリクトする可能性は排除できます
- 流れを追えば、実質的にGitHub Flowと同じです。ただし、作業する場所を明確に切り分けることができます
- masterはdevelopの劣化コピー的な存在になってしまいましたが、素早くhotfixを開始するために、役に立ちます

![voicevox_branch_strategy_idea_by_isnot_2](https://user-images.githubusercontent.com/21094354/130661761-35c8989d-f0bb-472e-9571-5769b38b25d7.png)

こうしてみて、ヒホさんにご納得いただける自身はないのですが、私自身の考えをまとめる意味もあり、図にしてみた次第です。もはや私からは言いたいだけ発言させていただきましたので、ここからは、ヒホさんの結論を支持します。

**Comment by Hiroshiba** [comment]
そちらの方法だと、hotfixを入れようとした時にdevelopが進んでいた場合に問題になりそうです。
（ちょうどそちらの図の紫３つ目の■の前に２つめの■がcommitされています）

hotfixのとこをdevelopとmasterの両方にマージする形に変えたら僕の考えてたのと同じになる（streamを２本用意するか、片方にタグ付けだけにするかの運用の違いだけになる）ので、やっぱこの方法が良いなと改めて思えました。

**Comment by Hiroshiba** [comment]
だいたいこうかなというものが見つかってきたので、↓に移行していきます

- https://github.com/VOICEVOX/voicevox/issues/206
