### ISSUE TITLE
Fedoraで日本語入力ができない（mozc-fcitc）

### ISSUE THREAD

**Issue by kkai1010** [VOICEVOX/voicevox#1494]
## 不具合の内容

Fedora38で日本語入力ができません 

### 再現手順

fedoraをインストール、mozc-fcitcをインストール、.sh版のVOICEVOXをインストール

### 期待動作

日本語が打てる

## VOICEVOXのバージョン

0.14.7

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [x] Linux

*   Linux Fedora 38 64bit

## その他

テキストエディターなどで文字を打ってコピペをすると問題なく喋らせることができました。

**Comment by kkai1010** [comment]
ごめんなさい「な

**Comment by Hiroshiba** [comment]
こちらと同じ現象でしょうか？

- https://github.com/VOICEVOX/voicevox/issues/1237

そうだと思うのでcloseします！

**Comment by kkai1010** [comment]
起動してエラーなどは表示されないのですが...

**Comment by kkai1010** [comment]
[Screencast from 2023-08-10 12-11-05.webm](https://github.com/VOICEVOX/voicevox/assets/141879052/377f14ca-8323-419e-8200-631e3facd32e)

**Comment by kkai1010** [comment]
忘れていましたibus-anthyでは動作しました

**Comment by Hiroshiba** [comment]
ご報告ありがとうございます！
ボイボはOSSですのでみんなで解決することができます！
上記のissueに原因や方針がまとめられているので、よかったらディスカッションにご参加ください！

**Comment by kkai1010** [comment]
どうすれば参加することができますか？

**Comment by Hiroshiba** [comment]
@kkai1010 [こちらの議論](https://github.com/VOICEVOX/voicevox/issues/1237)を追って、何ができるか判断いただければと思います！
少し追ってみましたが、どうやら`libstdc++.so.6`が原因で、Pyinstallerによる影響の物っぽいので、そのあたりの依存を外せないかを色々考える･･･とか？

**Comment by kkai1010** [comment]
2日も遅れてしまいました、ごめんなさい。教えてれてありがとうございます！
