### ISSUE TITLE
【アナウンス】.env内の`DEFAULT_ENGINE_INFOS`パラメータが`VITE_DEFAULT_ENGINE_INFOS`に変わりました

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1507]
## 内容

タイトルの通り、パラメーター名が変更になりました。

- https://github.com/VOICEVOX/voicevox/pull/1501

この影響で、パラメーター名を変更する前の.envではエンジンが起動しないことがあると思います。
以前のパラメーターに`VITE_`をつければ起動するはずです。

### レビュワー向け案内

プルリクエストのタイミングによって必要なパラメータ名がしばらく変わりそうです。
コピーして両方とも.envに書いておくとどちらでも起動するので便利だと思います。

2023/08/24  0:35追記
`VITE_APP_NAME=voicevox`も必要になりました。

**Comment by Hiroshiba** [comment]
@y-chan メンテナとして共有です 🙏

**Comment by thiramisu** [comment]
.env内に`VITE_APP_NAME=voicevox`も必要になったみたいなので一応補足しておきます…！
以下のコミットからです。
- #1496

**Comment by Hiroshiba** [comment]
ありがとうございます！！
issue内容にも追記させていただきます！

**Comment by Hiroshiba** [comment]
十分に案内できた気がするのでクローズで良さそうに感じました！
多分問題ないのでクローズしますが問題ありそうだったらすみません 🙇 @y-chan
