### ISSUE TITLE
immerのバージョンを上げる。

### ISSUE THREAD

**Issue by stmtk1** [VOICEVOX/voicevox#1517]
## 内容
現在immerのバージョンが`9.0.2`になっているが、このバージョンはnpm auditの出力結果より、creticalになっている。なので、最新のバージョンに上げてcreticalではないようにしたい。

### Pros 良くなる点
- 脆弱性が減る

### Cons 悪くなる点
- もしかしたらバージョンを上げたことにより新たなバグが生まれるかもしれない。

## VOICEVOXのバージョン

0.?.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by sevenc-nanashi** [comment]
#1635 で解決。
