### ISSUE TITLE
エンジンが起動していなくても「データ準備中・・・」が表示される

### ISSUE THREAD

**Issue by umi1299** [VOICEVOX/voicevox#1538]
## 不具合の内容

エンジンが起動していなくても `エンジン起動中・・・` の後に `データ準備中・・・` が表示される

### 現象・ログ

エンジンが起動していないとき `エンジン起動中・・・` と `エンジン起動に時間がかかっています。` が表示されるが、しばらく放置しているとエンジン起動後に表示されると思われる `データ準備中・・・` が表示されてしまう

### 再現手順

1. `voicevox` リポジトリに移動する
2. `git reset --hard 087917c87295ba74deb6472f3d4f0ef42b17a10b`
3. `npm run browser:serve`
4. http://localhost:5173/#/home にアクセスする
5. 2分くらい待つ

### 期待動作

1. http://localhost:5173/#/home にアクセスする
2. `エンジン起動中・・・` が表示される
6. 加えて `エンジン起動に時間がかかっています。` と `Q&Aを見る` ボタンが表示される
7. 表示が変化しない、または `エンジン起動に失敗しました` や `エンジンとの接続に失敗しました` のようなメッセージが表示される

## VOICEVOXのバージョン

https://github.com/VOICEVOX/voicevox/tree/087917c87295ba74deb6472f3d4f0ef42b17a10b

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [x] macOS Venture 13.4
- [ ] Linux

## その他

関連がありそう？

- #964 
- #906

**Comment by sevenc-nanashi** [comment]
https://github.com/VOICEVOX/voicevox/blob/main/src/store/engine.ts#L165

理由としては単純で、エンジンの起動問い合わせのループが100回しか行われてないからですね。
while (true)にすれば直りはすると思いますが、あえて100回にしてる理由もあるかも？

**Comment by umi1299** [comment]
ありがとうございます
なるほど、100回のループを抜けるとステートが `FAILED_STARTING` になるんですね

メッセージの表示を分けているのは↓だと思うのですが、ステートが `STARTING` のとき以外は `データ準備中・・・` を表示するようになっていました

https://github.com/VOICEVOX/voicevox/blob/087917c87295ba74deb6472f3d4f0ef42b17a10b/src/views/EditorHome.vue#L20-L22

正常に起動するときは `エンジン起動中・・・` → `データ準備中・・・` → エディター画面 と推移するので、途中でこけているのに `データ準備中・・・` が表示されてしまうとエラーなのかどうか紛らわしいなと思いました
失敗を表すステートの `FAILED_STARTING` があるのであれば、そのときは専用のメッセージを用意しても良さそうかと思ったのですがどう思われますか？

**Comment by Hiroshiba** [comment]
今まで全く気づきませんでした･･･。
原因を掘り返していたのですがおそらく2年間ずっと存在していたエラーぽいです。
こちらで実装され

- https://github.com/VOICEVOX/voicevox/pull/156

その直後におそらく間違えてこちらで消去されてました。

- https://github.com/VOICEVOX/voicevox/pull/161

> 失敗を表すステートの FAILED_STARTING があるのであれば、そのときは専用のメッセージを用意しても良さそうかと思ったのですがどう思われますか？

過去にもそのような実装がされていたので、その形が良いかと思います！！
ぐるぐるマーク（スピナー）は表示せず、エラーで終わってしまったということが伝わるようにするとなお良さそうかもです！
