### ISSUE TITLE
マルチエンジン：シャットダウン前に送信されるエンドポイントを作る

### ISSUE THREAD

**Issue by sevenc-nanashi** [VOICEVOX/voicevox#1540]
## 内容

タイトル通り。`POST /shutdown`あたりに送ってから終了する感じです。

### Pros 良くなる点

Graceful shutdownができる

### Cons 悪くなる点

ないはず？

### 実現方法

エンジン終了前に送信する。
レスポンスは待つが404を許容しておく（500番台返されたらエラートーストを出してもいいかも）

## VOICEVOXのバージョン

0.?.0

## OSの種類/ディストリ/バージョン

- [x] Windows
- [x] macOS
- [x] Linux

## その他

エンジン側に立てるべきだったかも？

**Comment by Hiroshiba** [comment]
APIを実装するのもいいかもですが、終了シグナルを送る形でもいいのかなと思いました。
追加実装不要ですし、外部からAPIを叩かれる心配もないですし。

･･･もしかして今の実装がすでにそうなってるかも･･･？

**Comment by sevenc-nanashi** [comment]
シグナル送られましたね。アプリも待ってそうです。閉じます。

**Comment by Hiroshiba** [comment]
なるほどです！！
ログ見るにstdoutも切ってる気がするので（本当？）、正確にはkillを実行して死を待機してからシャットダウンするみたいな感じにしても良いかもですかね。
