### ISSUE TITLE
行末のアクセント句を選択した状態での結合や削除が考慮されていない

### ISSUE THREAD

**Issue by thiramisu** [VOICEVOX/voicevox#1552]
## 不具合の内容
行末のアクセント句を選択した状態で結合すると、再度アクセント句を選択しないと正常に再生ができなくなります。
原因は、アクセント句数が減少しても、`audioPlayStartPoint`（選択中のアクセント句の添え字）が変わらないためです。
このバグは結合に限らず、アクセント句数の減少を発生させる全ての操作で起きると思われます。
また行末に限らず、選択中のアクセント句の添え字を超える全ての操作で起きると思われます。

### 現象・ログ
結合時にコンソール上でエラーが出る。
その状態で再生ボタンを押しても内部的にエラーが出るだけでユーザーから見ると何も起こらない。

### 再現手順
1. テキスト欄に1234と入力
2. アクセント句「ヨン」をクリックして選択状態にする
3. 「ニヒャク」と「サンジュウ」の間をクリックして結合する
4. コンソール上にエラーが出る
5. 再生ボタンを押す
6. コンソール上にエラーが出るのみで何も再生されない
  （精確には誤差で最後のコンマ数秒分は再生されるかも）

### 期待動作 ＆ 解消方法案
- アクセント句の数が変わっても選択中のアクセント句の相対位置が保持される
  - 結合・削除時になるべく追従するようにすればバグを修正しつつ機能向上にもなるかと思ったんですが、分割→最後を選択→元に戻すとした場合は更にコマンドごとに選択句を保存する必要があって少し複雑かなと。

または
- 最後のアクセント句よりも後が内部的に選択されないようにする
  - とりあえずシンプルな解決策として、`ACTIVE_AUDIO_KEY`のようにgetterにして、0 から length - 1 までに収めるのが良さそうかなと思いました。

## VOICEVOXのバージョン

0.14.7
999.999.999

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！
（バグにを知らなかったし、指摘してくださってるundo/redoの考慮まで考えが及びませんでした･･･！）

提案の2番目のゲッターが良さそうに感じました！
読み変更などでアクセント句の数が大幅に増減したりした時に何かよからぬ挙動をするかもと思いましたが、特に問題になるような挙動は思いつかなかったです。

（以下、考えたけどいまいちな案のメモです。）

他にAudioDetail.vueでアクセント句の選択位置をwatchし、変な値になったら正しい値に変更するとかも考えました。
ただこの場合、最後のアクセント句が選択されなくなるなぁと思いました。なのでゲッターの方が良さそう。

よりリッチな解決策としては、undo/redoするタイミングでアクティブな場所を記憶しておいて、戻ったタイミングでアクティブな場所を変える手もあるかもと思いました。
ただこれは良い挙動がどういうものなのかしっかり吟味してからになってしまうので相当大変そう。
