### ISSUE TITLE
browser-e2eテストが[Errno 10013] error while attempting to bind on address ('127.0.0.1', 50021)で落ちることがある

### ISSUE THREAD

**Issue by sevenc-nanashi** [VOICEVOX/voicevox#1558]
## 不具合の内容

CIが落ちてます。
多分「アクセス許可で禁じられた方法でソケットにアクセスしようとしました。」のやつだと思います。

### 現象・ログ

https://github.com/VOICEVOX/voicevox/actions/runs/6205442990/job/16848654142

```
> voicevox@999.999.999 test:browser-e2e
> cross-env VITE_TARGET=browser playwright test --reporter=html


[WebServer] 2023-09-16T05:10:23.749708Z  INFO voicevox_core::publish: 検出されたGPU (DirectMLには1番目のGPUが使われます):
[WebServer] 2023-09-16T05:10:23.752275Z  INFO voicevox_core::publish:   - "Microsoft Basic Render Driver" (0 B)
2023-09-16T05:10:23.752311Z  INFO voicevox_core::publish:   - "Microsoft Basic Render Driver" (0 B)
[WebServer] Warning: cpu_num_threads is set to 0. ( The library leaves the decision to the synthesis runtime )
[WebServer] INFO:     Started server process [1208]
[WebServer] INFO:     Waiting for application startup.
[WebServer] INFO:     Application startup complete.
[WebServer] ERROR:    [Errno 10013] error while attempting to bind on address ('127.0.0.1', 50021): an attempt was made to access a socket in a way forbidden by its access permissions
[WebServer] INFO:     Waiting for application shutdown.
[WebServer] INFO:     Application shutdown complete.

Error: Process from config.webServer was not able to start. Exit code: 1

```

### 再現手順

CIを走らせる

### 期待動作

コケない

## VOICEVOXのバージョン

8f779ab

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by Hiroshiba** [comment]
browser-e2eで落ちてそうですね！
ブラウザ版テストの方はエンジンをPlaywright内で起動しているので、background.ts内にある自動ポート変更機能がなく、50021番がダメならそのまま起動に失敗するのかなとか思いました。

`portManager`にある`findOrCheckPort`を引数0で叩くと使えるランダムポートが帰ってくるので、それを指定するようにすればいいかも？
https://github.com/VOICEVOX/voicevox/blob/543f5083f449831ad1ae83f38a07342137c3481f/src/background/portManager.ts#L192

**Comment by Hiroshiba** [comment]
ちょっとよくわかってないのですが、CIが落ちない感じになってるのでissueのタイトルと優先度を変えさせていただこうと思います。
（たぶんガチャなんですが、逆に言うとガチャすれば解決するので、優先度は最高でなくても良いかなと思った次第です）

**Comment by Hiroshiba** [comment]
解決策のメモです。

そのポートが使えない時に、別のポートを使うようにコードを書くのが良さそうに感じました。
playwright.config.ts内にportが塞がっていたらスキャンするコードを書くと良さそう･･･？
（無指定だったらスキャンする、とかでもかっこいいかも）
