### ISSUE TITLE
詳細調整欄で、編集不可のモーラでもカーソルが`pointer`なのをなんとかする

### ISSUE THREAD

**Issue by thiramisu** [VOICEVOX/voicevox#1572]
## 内容
ｲﾝﾄﾈｰｼｮﾝ項目の無声化不可なモーラや、長さ項目の読みテキストをホバーした際、編集不可にもかかわらずカーソルが`pointer`になり、編集できるものとの区別がつかず、ややこしいです。
これを改善したいです。

### Pros 良くなる点
- カーソルの見た目とクリック時の挙動が一致する。

### Cons 悪くなる点
- ないはず。

### 実現方法
編集不可なテキストの場合は別のカーソル形状にする。

具体的には、`text-cell`に`cursor: not-allowed`を指定する。
- 無声化中のｲﾝﾄﾈｰｼｮﾝ項目のスライダーに合わせて。
- `default`か`not-allowed`かで実際に試してみたんですが、そもそもカーソルを合わせる場面は「編集したい」という気持ちが強いので、少し強めに否定してくれた方が分かりやすいかなと思ったりしました。
編集不可だと分かっている場合はそもそもカーソルを合わせないのであまり邪魔にならなそう。
できれば（無声化スライダーの操作不可も一緒に）理由をtool-tipなどで表示しても良いかも。

ちなみに原因としては、#578 で再生可能アクセント句が指定可能になった際に、アクセント句全体の`cursor`が`pointer`になったため、これを継承するようになって`cursor: default`がデフォルトではなくなったのが原因と思われます。

## VOICEVOXのバージョン

999.999.999

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！
ツールチップでの案内もとても良いと思います！

アクセント区間をクリックしたい人が偶然読みの部分をクリックした時（特に読みを全部クリックできない長さ欄）のこともちょっと考慮してみましたが、まあUIが完全に被さっていると見做して`not-allowed`で良いのかなと思いました！

**Comment by thiramisu** [comment]
PRを送りました

ちなみに無声化スライダーがdiableな理由が分からないのはissueから外れるのでとりあえず直してません。
issueとしては以下が立ってますね。
- #243
