### ISSUE TITLE
エディタのディレクトリとエンジンのディレクトリを分離するべきか。

### ISSUE THREAD

**Issue by sabonerune** [VOICEVOX/voicevox#1603]
## 内容

#1237 の問題は恐らくエンジンの配布物に含まれる共有ライブラリがエディタと干渉している可能性が高いようです。
エディタとエンジンのディレクトリを別々にすればこの問題を回避できるかもしれません。

### Pros 良くなる点

- #1237
が解決できるかもしれない。
- Linux以外でも今後発生するかもしれない共有ライブラリ関係の問題を回避できるかもしれない。

### Cons 悪くなる点

- 既存サードパーティアプリがエンジンの場所を見失う可能性がある。

### 実現方法

https://github.com/VOICEVOX/voicevox/blob/d98ab6cc41ece85b90459c8f266d9adfa49ddf94/electron-builder.config.js#L92-L93
https://github.com/VOICEVOX/voicevox/blob/main/.github/workflows/build.yml
の変更
(workflow周りは良く分かっていません)

## OSの種類/ディストリ/バージョン

- [x] Windows
- [x] macOS
- [x] Linux

## その他

自分はLinux環境がないのでそれで本当に回避可能か要確認する必要がある

**Comment by Hiroshiba** [comment]
個人的には分離（というより子ディレクトリ化）できるならしたほうが良いだろうなと感じています。
主な理由はLINUX版あれこれというより、zip版を展開した場合にVOICEVOX.exeが見つけやすくなりそうだからです。

ただconsに書かれている`既存サードパーティアプリがエンジンの場所を見失う可能性がある`は可能なら回避したい気はしています。
まあでも、ちょっとしょうがない気がしました。エンジンのrun.exeを起動するダミーのrun.exeを作る手もありそうですが、ゾンビプロセスにならないよう気を配ったり、stdin/outを良い感じに流してあげたり、環境変数やcwdをどうこうする手間が結構大変そうだなと･･･。

なので、個人的にはこうかなと！

* エンジンのディレクトリを分離するべきか
	* したい
* 既存サードパーティアプリがエンジンの場所を見失う可能性
	* 諦めた方が良い
	* 過去のバージョンと見分けがつくようにはしたい（といっても子ディレクトリ作るからほぼ自動達成）
	* 変わったよ〜という連絡はする。

**Comment by Hiroshiba** [comment]
なるほどです！！調査ありがとうございます！！！
となると、issueのタイトルの問いの答えは「した方が良い」という感じになりそうですかね･･･！！

どうしましょう？せっかくなのでこのまま解決に進行するのも面白いのかなと思っています。
ちょっとそこまではという感じでしたら、調査結果をまとめて別のissueにするか、タイトルを変更するかが良いのかなと思いました！

**Comment by Hiroshiba** [comment]
@sabonerune あ、ですです！　ぜひぜひ！！！

**Comment by y-chan** [comment]
遅くなりました...!
私としては、サードパーティアプリのために周知こそ必要だと思いますが、分離することによる恩恵がそこそこ大きいと思うので、いま出ているPRをマージする方針で問題ないと思います...!

**Comment by Hiroshiba** [comment]
@y-chan ありがとうございます！！　では全会一致ということで進められればと思います！！

**Comment by Hiroshiba** [comment]
すみません！
こちらの機能のことを忘れていて、大きな変更になるためアナウンスした後時間が経ってからアップデートするべきなことに気づきました。
なので0.15のアップデートに含めず、0.16からの追加にさせていただこうと思います。
0.16は1月末を予定しているので、今日明日に連絡すれば10日間あるためギリギリ大丈夫かなという判断です。（本当は良くないかもですが･･･。）

この機能のブランチ戦略はこんな感じかなと。

* release-0.15内でrevertをコミット
* そのまま0.15系統をリリース
* mainブランチに取り込む際、buffer-0.15ブランチ内でもう一度revert
* 0.16で正式リリース
