### ISSUE TITLE
[複数選択] 選択中デザインの調整

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1674]
## 内容

実験的機能の複数選択において、選択中をインジケートするUIの可視性を向上させたいです。
現状は薄い青色背景です。

### Pros 良くなる点

より見やすくなる

### Cons 悪くなる点

単純に濃くするだけだと逆に見にくくなる

### 実現方法

現状は薄い青色の背景になっているので、もう少し濃くするか、プライマリーカラーを使っても良いかも？
テキスト入力欄の背景は元に戻すと可視性はかなり向上しそう。

## その他

こちらに議論と具体的な提案があるのでとても参考になると思います！

- https://github.com/VOICEVOX/voicevox/issues/457#issuecomment-1848962682

**Comment by sevenc-nanashi** [comment]
![image](https://github.com/VOICEVOX/voicevox/assets/59691627/290864c6-9358-4c7e-a37f-22f4f9a5223a)

いま試したところあんまり気になりませんでした。薄めるのを無くすだけでも良さそう？

**Comment by Hiroshiba** [comment]
@sevenc-nanashi 確かにテキストが書かれているものを選択した時は違和感少ないかもです！
選択されている時にテキストを入力しようとすると見づらいかもしれません。

実際Windowsのファイラーはファイル名変更時に白背景になりました！
![image](https://github.com/VOICEVOX/voicevox/assets/4987327/9dd757a5-f401-404d-af48-ebef3ca445f7)

**Comment by sevenc-nanashi** [comment]
なるほど、選択中&入力中の背景を白くする、でやってみます

**Comment by Hiroshiba** [comment]
選択表示方法がここまで思いつかない原因を１つ思いつきました！

普通よくある操作だと、選択してから操作すると思うのですが、ボイボは先にカーソルを当てる（編集する）ためにクリックするんですよね。
つまり選択は意図しない操作なので、選択されたような表示になると違和感があるのかなと。

たぶん、テキストエディタに操作感を近づけると良さそうかもと思いました。
カーソルが当たってるだけの時は軽めのデザイン、範囲選択のときはガッツリ表示、みたいなのがイメージしやすいかも………？
