### ISSUE TITLE
メモ機能・ルビ機能の記法を全角記号にも対応させる

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1699]
## 内容

テキスト内`[メモ]`と書いたりすることで、メモ機能やルビ機能を使うことができます。

- https://github.com/VOICEVOX/voicevox/pull/1378
- https://github.com/VOICEVOX/voicevox/pull/1384

現状この機能は半角記号のみに適用可能ですが、おそらく日本語入力を考えると全角記号にも対応した方が嬉しそうです。
このissueは全角記号にも対応できたら完了だと思います。

### Pros 良くなる点

より直感的になる

### 実現方法

正規表現で判定しているので、そこに全角記号を足せば良い気がします。

**Comment by Hiroshiba** [comment]
この機能を実装してくださった @weweweok さん、機能向上にご興味ありませんか･･･！ 👀

**Comment by weweweok** [comment]
やってみます。

`{} ->｛｝`: ルビはこれで大丈夫だと思います。

無視する単語`[]`を何で囲むかが、ちょっとわかりません。
voicevoxエディタの利用者が「」を頻繁に使うなら、無視する単語を「」以外で囲むのが良いと思います。

**Comment by Hiroshiba** [comment]
@weweweok ありがとうございます！！ぜひぜひ！！！

全角は［角括弧］でどうでしょう？
wikipedia見た感じそれっぽいかなと！
https://ja.wikipedia.org/wiki/%E6%8B%AC%E5%BC%A7#%E8%A7%92%E6%8B%AC%E5%BC%A7%EF%BC%BB_%EF%BC%BD
