### ISSUE TITLE
スナップショットテストが更新されない（ことがある）

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1724]
## 不具合の内容

- https://github.com/VOICEVOX/voicevox/pull/1688

でVRTが導入されました！
コミットメッセージに`[update snapshots]`と書くとスナップショットを更新できるのですが、うまいこと更新されなかったのでissueを作りました。

こちらがログです。（関係ないのがエラーで落ちてるのはopenapiのAPIが減ったからです）

- https://github.com/Hiroshiba/voicevox/actions/runs/7563140833

## その他

成果物を見る感じ、多分Windows用のスナップショットを更新するのはWindowsだけで、ubuntuとかは更新されてないスナップショットをアップロードしていて、マージする時に衝突して更新されたりされなかったりするんだと思います。

パッと思いつく解決策は、まあOSに従った成果物だけアップロードするようにするのが良いのかなと思いました。
（Windowsは多分`*-win32.png`？）

もっと良い解決策があるかもと思ってとりあえずコメント待ちです！

**Comment by sevenc-nanashi** [comment]
そもそもWindows以外ではshouldUpdateSnapshotsをfalseにするのがいいような気がしました。

**Comment by Hiroshiba** [comment]
> そもそもWindows以外ではshouldUpdateSnapshotsをfalseにするのがいいような気がしました。

なるほどです。
どこをゴールにするかなのかなと思いました！
winでのみスナップショットテストする方針か、やっぱり他のOSでも本当はやりたい（けどできてない）方針か。

個人的には、OS依存の描画の差もあるので、やっぱマルチOSでVRTしたい気持ちがちょっとあります。

---

今気づいたのですが、「実行のたびに謎の描画差がある」現状の原因、これかも……？
スナップショットはいつも一定だけど、別のOSのが混じっちゃってる的な。

**Comment by Hiroshiba** [comment]
こちらが実行できないとテストを更新できないため、優先度最大にさせていただきます。

**Comment by Hiroshiba** [comment]
- https://github.com/VOICEVOX/voicevox/pull/1761

でいろいろやっていたのですが、macでflakyになるのはそういうものという感じでした。
なのでmacは省いちゃって良さそう。

mac省くなら別にlinuxとwinは表示が一緒なので、両方テストするのは意味ない気がします。
docker環境を整えてlinuxでやるのが一番良い気がしますが、なぜかwinでもうまくいっているので、winだけでチェックするのが良いかなと思いました！
