### ISSUE TITLE
Bug: VOICEVOX Nemo 「女声3（ノーマル）,約束」」 は声が出ない

### ISSUE THREAD

**Issue by ckjpn** [VOICEVOX/voicevox#1739]
女声1（ノーマル）,約束
女声2（ノーマル）,約束
女声3（ノーマル）,約束　＝ no sound
女声4（ノーマル）,約束
女声5（ノーマル）,約束
女声6（ノーマル）,約束
男声1（ノーマル）,約束
男声2（ノーマル）,約束
男声3（ノーマル）,約束

次のようなinputなら声が出る。
女声3（ノーマル）,約束を守る

Temporary "unlisted" video.

https://youtu.be/JRt38M_9eyw

**Comment by Hiroshiba** [comment]
ご報告ありがとうございます！
今回の例のような音声の出づらさは現状の仕様となりそうです 🙇
