### ISSUE TITLE
右辺がundefinedやnullである厳密等価演算子を等価演算子に自動で修正できる設定を追加

### ISSUE THREAD

**Issue by cm-ayf** [VOICEVOX/voicevox#1749]
## 内容

右辺がundefinedやnullである厳密等価演算子を等価演算子に自動で修正できる設定を追加します．

右辺がundefinedやnullである厳密等価演算子を禁止する設定が #1513 で提案され #1585 で実装されています．しかし，この規則は`eslint --fix`で自動で修正できるはずである程度に単純なものであり，なれば自動修正も実装すべきです．

### Pros 良くなる点

開発者が，右辺がundefinedやnullである厳密等価演算子があるかどうかを気にしなくて良くなる．

### Cons 悪くなる点

`"no-restricted-syntax"`では実装できないため，ESLintルールを自前で実装し維持する必要が発生する．

### 実現方法

ESLintルールを新たに実装し，プラグインとして導入する．
参考：<https://typescript-eslint.io/developers/custom-rules>

## VOICEVOXのバージョン

-

## OSの種類/ディストリ/バージョン

-

## その他

-

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！

とても良いと思います！
プルリクエストも楽しみにしています。
もしトライして難しい点があれば、知見としてぜひ知りたいです…！
