### ISSUE TITLE
アクセント辞書機能を付ける

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#175]
専門用語などはアクセントが思ったものと違う傾向があります。

こちらは「プレート内地震」が思っているものと違ったという報告です。
https://twitter.com/teruteru129/status/1431463737240657922

他にも「ディープラーニング」などのアクセントが違うなどが例としてあげられます。

これは、予め文字列とアクセントを登録しておき、何らかの手段でreplaceすることで実現できるかもしれません。
タスクとしては↓とよく似ていそうです。
https://github.com/Hiroshiba/voicevox/issues/158

そもそも実現できるのか微妙なところなので、まずは実現方法の議論が必要かもしれません。

**Comment by Hiroshiba** [comment]
参考：CoeFontのアクセント辞書機能
https://twitter.com/coefont/status/1433316257898631168

**Comment by yamachu** [comment]
テキストを解析して文節、アクセントを生成するのをEngine側のOpenJTalkに任せているので、カスタムのアクセントに関する処理はそこでまとめるのがいいのかなと思いました。

今回のIssueの対象であるアクセント辞書機能を実現するにはMecabのユーザ辞書機能を使うといいのかなと思いました。
OpenJTalkがテキスト解析に使っているMecab本体はユーザ辞書を読み込み機能を有しています。
https://taku910.github.io/mecab/dic.html

OpenJTalkはそのMecabを一部（辞書の読み込みなどの処理）改変し使っているだけなので、OpenJTalk自体に変更を加えることでそのユーザ辞書読み込み機能を使うことが可能です。
例: https://github.com/yamachu/LibOpenJTalk/pull/8

この様に改変を行ったOpenJTalkを使うことで予め読みを登録したユーザ辞書を読み込ませ、適切なアクセントを吐き出すことが可能となりそうだと考えています。

このユーザ辞書ですが、単純に手書きできるファイルではなく、特定フォーマットに則ったCSVをコンパイルしたもので、そのコンパイルをユーザに行ってもらうことは負担になりそうです。
そのためこのアクセント辞書機能を提供するのであれば、辞書コンパイル機能もENGINE側に持たせるのが良いかと思いますが、詳細はまた別途。

ということでアクセント辞書機能を付けるには以下のタスクが完了すれば実現出来るのではないかと考えています（あくまでの実装の1例です）。

### Ph.1

API
- [ ] ユーザ辞書（サンプルレベルのもの）をENGINE側で読み込める（例: VOICEVOXを「ぶいおーあいしー…」ではなく「ぼいすぼっくす」と読ませるだけの辞書）

Ph.1 でユーザ辞書機能を使う方向性で良さそうと感じたら

### Ph.2

API
- [ ] ユーザ辞書に単語を追加できる（アクセント位置は固定）
  - [ ] コンパイル機能が付く
  - [ ] UIとの通信のアレコレが決まる。Endpoint、モデルなどなど

UI
- [ ] ユーザ辞書に追加したい単語と読みを追加出来る

Ph.2 までやると多くのケースをカバーできるのではないかと思われます

更にブラッシュアップするのであれば

### Ph.3

API
- [ ] ユーザ辞書のエントリが取得できる
- [ ] ユーザ辞書の中身が編集できる（読みの修正やアクセント位置の修正など）

UI
- [ ] ユーザ辞書の中身が見れる
- [ ] ユーザ辞書の中身を編集できる
  - [ ] アクセント位置が編集できる

などが出来るとそれっぽくなるのかなと。
こんな感じの方針が立てば進められるのかなと思うのですが、この実装方針はいかがでしょうか？
（例えばユーザ辞書を作るとアップデートする時にインストーラーはそのまま置いてくれるんですか？とかアンインストールする時はちゃんと消してくれるんですか？みたいな懸念はあります。）

また例えばUI側のみで実装するとどんな感じになるのかみたいなアイデアがある人がいたら教えてほしいです。

読みの修正UIが追加されたこともあり、UIだけでも実現が出来るのではないかという勝手なイメージもあります。

**Comment by Hiroshiba** [comment]
個人的には、OpenJTalkのユーザー辞書を使うのがとてもかっこいいと思うので、yamachuさんの案を推したいです。
エンジン内に実装しつつもかなり独立させた状態で作っていって、需要を整理しつつのちのちにはPythonライブラリとして切り出しても面白そうです。
辞書.txtとしてタブと改行区切りなんかでユーザー辞書を持っておくようにすれば、最初はUIなくても良いかもしれないなと思いました。

一方で、確かにUI側だけでもある程度なんとかなるだろうなとも思います。
アイデアとしては単純にテキストに`.replace(bef, aft)`をかける、とかです。
ただどんな場合も、形態素解析に失敗する「てへぺろ」とかはどうしようもないと思います。

**Comment by Yosshi999** [comment]
辞書コンパイルも含めてpyopenjtalkの改造だけで行けそうです
https://github.com/Yosshi999/pyopenjtalk/commit/57c15e7ba67656f1e7965a52a14873a12b38cc84

**Comment by Hiroshiba** [comment]
おー！　pyopenjtalkだけでできると、依存関係が増えないので良さそうです。
本家pyopenjtalkにマージされたものを利用するのが最も良さそうですが、難しそうであればforkしたものをメンテしても良さそうですね。

**Comment by takana-v** [comment]
取りあえず自分の頭の中で考えている案です。
- （エンジン）https://github.com/Yosshi999/pyopenjtalk/commit/57c15e7ba67656f1e7965a52a14873a12b38cc84 をマージして`requirements.txt`に追加
- （エンジン）叩くとcssの辞書を編集、コンパイル、ユーザー辞書適用を行うエンドポイントを追加
- （エディタ）今のアクセントの編集欄を流用して辞書設定画面を追加

ただpyopenjtalkを利用すると様々なパラメータを指定する必要があるのでちょっと大変かもしれません。
（csvの辞書で品詞って省略できましたっけ…？）

**Comment by Hiroshiba** [comment]
方針、良さそうです・・・！

> Yosshi999/pyopenjtalk@57c15e7 をマージしてrequirements.txtに追加

pyopenjtalkは現状日本語パスからの辞書ロードができないはずなので注意が必要かもです。
[pyopenjtalkに出している下のプルリクエスト](https://github.com/r9y9/open_jtalk/pull/6)をマージするか、[（pyopenjtalk作者さんの方の）openjtalkリポジトリに出しているこちらのプルリクエスト](https://github.com/r9y9/open_jtalk/pull/6)のマージが必要かもです。
（僕のpyopenjtalkリポジトリにYosshi999さんのプルリクエストをマージして管理するのが一番丸そう・・・？）

> エンドポイントを追加

良いと思います！

> 今のアクセントの編集欄を流用して辞書設定画面を追加

面白い方法だと思いました！
ただ、アクセント句ごとにしか辞書設定できないかも・・・？（僕の認識がずれていたらすみません）

**Comment by Yosshi999** [comment]
マージするならhttps://github.com/Yosshi999/pyopenjtalk/tree/PR-user-dic を使ってほしいです。
openjtalkが使用しているmecabではいくつかのAssertionが無効化されており、例えば https://github.com/Yosshi999/pyopenjtalk/commit/57c15e7 では指定したファイルが存在しないときpythonインタプリタごと落ちます。

**Comment by Hiroshiba** [comment]
完了なのでcloseします！ @y-chan さん、 @takana-v さん、ありがとうございました！！！
