### ISSUE TITLE
[project-s] ノート歌詞のUI調整

### ISSUE THREAD

**Issue by romot-co** [VOICEVOX/voicevox#1751]
## 内容

- ノート上歌詞の位置をノート内に移動する
- ノート歌詞編集時に入力欄を選択する
- ノート歌詞タブ移動時に入力欄を選択する
- 歌詞表示調整: ノート上に文字を置いて見づらかった場合の調整

### Pros 良くなる点

歌詞の入力を直感的にする(現状だと歌詞部分をダブルクリックしてしまうが、なにも起こらない)
編集において入力を容易にする

### Cons 悪くなる点

なし

### 実現方法

- CSSによる歌詞位置の調整
- ダブルクリック時・タブ移動時にinput要素をselect

## VOICEVOXのバージョン

0.16.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by Hiroshiba** [comment]
> ノート上歌詞の位置をノート内に移動する
ノート歌詞編集時に入力欄を選択する
ノート歌詞タブ移動時に入力欄を選択する

どれも良さそうに思いました！！

> 歌詞表示調整

こちらは、ノート内の位置に移動したとき、そのままだとちょっと見づらかった場合の微調整、という認識であってそうでしょうか 👀
