### ISSUE TITLE
[project-s] 鍵盤・シーケンサーのテーマ・ダークモード対応

### ISSUE THREAD

**Issue by y-chan** [VOICEVOX/voicevox#1755]
## 内容

題の通りです。現状は色の値が直に書き込まれているなど、様々な原因でダークモード時の表示がおかしくなります。
間に合いそうならプロトタイプリリースに間に合わせられると良さそうです。

現状は以下のような感じになっています。

![image](https://github.com/VOICEVOX/voicevox/assets/34832037/de1d22e3-6ed7-49fa-b5bb-7656f18bd82b)

鍵盤・シーケンサーについては、他ソフト(Synthesizer V Studio)だとこんな感じなので、参考にできるとよさそう。
![image](https://github.com/VOICEVOX/voicevox/assets/34832037/ca4ad282-c5d0-4659-b5a8-8d3dfe89176f)
鍵盤は明度を下げる感じ、シーケンサーは明度の差があるグレーを使えばある程度良いんじゃないかなと。
`$background`をうまく使ってあげると良いかもしれないです。

とりあえず現状のコードを調べてみた感じ、以下の色がありそうでした(見落としあるかもです)

- 鍵盤
  - https://github.com/VOICEVOX/voicevox/blob/cd41c30d54a387fc72a805f9fda3310f086f787e/src/components/Sing/SequencerKeys.vue#L200-L203
  - https://github.com/VOICEVOX/voicevox/blob/cd41c30d54a387fc72a805f9fda3310f086f787e/src/components/Sing/SequencerKeys.vue#L210-L212
- 鍵盤上の文字
  - https://github.com/VOICEVOX/voicevox/blob/cd41c30d54a387fc72a805f9fda3310f086f787e/src/components/Sing/SequencerKeys.vue#L218-L220
  - ![image](https://github.com/VOICEVOX/voicevox/assets/34832037/8b50e6a3-7884-4232-9f5c-c24c8d8d6cd4)
- レンダー失敗時の、シーケンスルーラー直下のバーの色
  - 警告色`$warning`に統一しても良いかも。
  - https://github.com/VOICEVOX/voicevox/blob/cd41c30d54a387fc72a805f9fda3310f086f787e/src/components/Sing/SequencerPhraseIndicator.vue#L78-L80
  - ![image](https://github.com/VOICEVOX/voicevox/assets/34832037/7277ed94-891a-450c-906c-bc78eae76dd1)
- シーケンスルーラー(上の小節番号が振られているところ)
  - 文字色
  - https://github.com/VOICEVOX/voicevox/blob/cd41c30d54a387fc72a805f9fda3310f086f787e/src/components/Sing/SequencerRuler.vue#L231-L233
  - ![image](https://github.com/VOICEVOX/voicevox/assets/34832037/339f0715-9e52-4140-97f8-1ee7ee73513e)
  - シーケンスルーラーの左端の隣の空間の枠線・背景色(背景色は`$background`で良さそう)
https://github.com/VOICEVOX/voicevox/blob/cd41c30d54a387fc72a805f9fda3310f086f787e/src/components/Sing/ScoreSequencer.vue#L1083-L1089
  - ![image](https://github.com/VOICEVOX/voicevox/assets/34832037/3591481a-a2fa-4f00-a294-7df93a0a9cc2)
  - シーケンサーとの境界色
  - https://github.com/VOICEVOX/voicevox/blob/cd41c30d54a387fc72a805f9fda3310f086f787e/src/components/Sing/SequencerRuler.vue#L216
  - 各セルの枠色
  - https://github.com/VOICEVOX/voicevox/blob/cd41c30d54a387fc72a805f9fda3310f086f787e/src/components/Sing/ScoreSequencer.vue#L1116
  - 1ビート(1小節はデフォルトで4ビート)の表示線
  - https://github.com/VOICEVOX/voicevox/blob/cd41c30d54a387fc72a805f9fda3310f086f787e/src/components/Sing/ScoreSequencer.vue#L1133-L1136
  - 1小節の表示線
  - https://github.com/VOICEVOX/voicevox/blob/cd41c30d54a387fc72a805f9fda3310f086f787e/src/components/Sing/ScoreSequencer.vue#L1128-L1131
  - 各、空のセルの色(白と灰色)
  - https://github.com/VOICEVOX/voicevox/blob/cd41c30d54a387fc72a805f9fda3310f086f787e/src/components/Sing/ScoreSequencer.vue#L1120-L1122
  - https://github.com/VOICEVOX/voicevox/blob/cd41c30d54a387fc72a805f9fda3310f086f787e/src/components/Sing/ScoreSequencer.vue#L1124-L1126
  - 現在のマウスの位置に合わせて変化する表示線(ガイドライン)
  - https://github.com/VOICEVOX/voicevox/blob/cd41c30d54a387fc72a805f9fda3310f086f787e/src/components/Sing/ScoreSequencer.vue#L1143
  - ![image](https://github.com/VOICEVOX/voicevox/assets/34832037/eeead5f8-18ca-4473-b2bc-5c6b7225d37d)
- ノート
  - 各ノートの枠線(ノート自体は`$primary`になっている)
  - https://github.com/VOICEVOX/voicevox/blob/cd41c30d54a387fc72a805f9fda3310f086f787e/src/components/Sing/SequencerNote.vue#L245
  - ノートの選択時の色
  - https://github.com/VOICEVOX/voicevox/blob/cd41c30d54a387fc72a805f9fda3310f086f787e/src/components/Sing/SequencerNote.vue#L205-L207
  - ノートの選択時の歌詞表示部分の枠線の色
  - https://github.com/VOICEVOX/voicevox/blob/cd41c30d54a387fc72a805f9fda3310f086f787e/src/components/Sing/SequencerNote.vue#L210-L212
  - 同じ時間でノートが複数配置された場合の色(無効であることを示す色)
  - https://github.com/VOICEVOX/voicevox/blob/cd41c30d54a387fc72a805f9fda3310f086f787e/src/components/Sing/SequencerNote.vue#L215-L220
  - ![image](https://github.com/VOICEVOX/voicevox/assets/34832037/b02c896a-164d-4fa3-a371-fb33b9db9d61)
  - 歌詞表示部分の枠線と文字色・背景色
  - https://github.com/VOICEVOX/voicevox/blob/cd41c30d54a387fc72a805f9fda3310f086f787e/src/components/Sing/SequencerNote.vue#L229-L231
  - ノートの歌詞入力時の枠線
  - https://github.com/VOICEVOX/voicevox/blob/cd41c30d54a387fc72a805f9fda3310f086f787e/src/components/Sing/SequencerNote.vue#L272

### Pros 良くなる点

表示が良くなる

### Cons 悪くなる点

特になし

### 実現方法

テーマの色を増やして、反映する

**Comment by romot-co** [comment]
以下に対応させるとよさそうでしょうか…？
https://github.com/VOICEVOX/voicevox/pull/1756

(色定義でシーケンサ特有の部分について追加いたします)

## 新規定義が必要そうな部分

- ピアノ鍵盤部分のカラー: 白鍵 / 黒鍵
- ピアノ鍵盤部分 / シーケンサグリッド: ボーダー1(罫線の濃い方...小節およびオクターブ)
- ピアノ鍵盤部分 / シーケンサグリッド: ボーダー2(罫線の薄い方)
- シーケンサグリッド: 黒鍵にあたるエリアのカラー
- シーケンサグリッド: 白鍵にあたるエリアのカラー(いらないかも)
- ノート: ボーダー
- ノート: 選択中
- ノート: 無効(重なったノート)
- ノート: 入力時テキスト入力エリア

## 必要でなさそうなもの

- テキストカラー: 標準
- 警告: 標準

## 確認中

- テキストカラー: Medium-emphasis
- テキストカラー: Low-emphasis

**Comment by y-chan** [comment]
新デザインについては、後で適用していくことになると思うので、一旦気にしないで良いと思います...!

現在CSS上で直に設定している値はデフォルトテーマにそのまま使っていいと思うので、ひとまず`新規定義が必要そうな部分`で挙げられている色をこちらに追加してもらうことになりそうです。

https://github.com/VOICEVOX/voicevox/blob/main/public/themes/default.json

その後、ダークテーマの色をいい感じに決めて以下に追加してもらえれば...!

https://github.com/VOICEVOX/voicevox/blob/main/public/themes/dark.json

以下の部分がいい感じに可変色を反映してくれているので
https://github.com/VOICEVOX/voicevox/blob/2b2013bcd20c312e37054723d1304a4d00382166/src/store/setting.ts#L246-L304

それを元に更にSCSSに書き込んで、使ってあげればとりあえずこのIssueは完了になるのかなと...!

https://github.com/VOICEVOX/voicevox/blob/main/src/styles/colors.scss

**Comment by romot-co** [comment]
@y-chan 
ありがとうございます！こちら調整・修正いたします！
