### ISSUE TITLE
「フュ」は「フユ」と発音する

### ISSUE THREAD

**Issue by ckjpn** [VOICEVOX/voicevox#1766]
フューチャー
フユウチャア

フュージョン
フユウジョン

<img width="680" alt="Screenshot 2024-01-27 at 14 30 57" src="https://github.com/VOICEVOX/voicevox/assets/7934273/45ec8a51-6e60-4309-a2f1-a8faef8b3a0b">

**Comment by ckjpn** [comment]
### Screenshot
<img width="801" alt="Screenshot 2024-01-28 at 8 48 49" src="https://github.com/VOICEVOX/voicevox/assets/7934273/12506882-09ca-4010-835d-4cee9e44f42c">

### Video
You will need to unmute the audio.

https://github.com/VOICEVOX/voicevox/assets/7934273/d153622f-7546-4ea4-9f25-61c14cfd27b7

**Comment by Hiroshiba** [comment]
ご報告ありがとうございます。

VOICEVOXが内部で使っているopenjtalkが`フュ`を`f u y u`と使うことが原因そうです。
ちょっとVOICEVOXとして修正が難しそうなのでclose させていただこうと思います。

（ちなみにopenjtalk 側で問題が解決しても、音の中に「フュ」がないため音声合成は失敗しそうです。）
