### ISSUE TITLE
シングエディタの編集状態を保存できるようにする

### ISSUE THREAD

**Issue by y-chan** [VOICEVOX/voicevox#1781]
## 内容

現在、シング画面の状態はまだ保存できません。
これを、保存できるようにしたいです。

どう保存するかを考えています。
保存するデータは、基本的にsinging storeが抱えているデータを保存すればよいのですが、プロジェクトファイルをどうするかが課題になりそうです。
2択です。

1. トークのプロジェクトファイルに統合する(VOICEVOXとしてプロジェクトファイルは`vvproj`のみにする)
2. ソング用にプロジェクトファイルを新しく用意する

今のところ、1で進めようかなと思っているのですが、もしかしたら2の方が良いかも...?
1の場合、最後に開いていた画面をプロジェクトファイル内に保存すると、一発でシング画面に飛べて便利かなと思っています。
2の「方がいい」という理由は特に思いついていなくて、エディタが1つになっているのだからプロジェクトファイルも1つの方がユーザーにとってもわかりやすいだろうと思っています。

設計的な課題としては、1の方だと、既存のプロジェクトファイルを拡張する形になりますが、talk前提のプロジェクトファイルだったので、songをつけ足すのは設計的に結構無理くり感があるかもです。
2の方だと、拡張子を考えたり、変更範囲が大きくなりそうだったり(プロジェクトファイルの拡張子を増やせるようにbackgroundまでいじることになりそう)と、設計はあっさりしつつも実装が少し大変な気もしています。

### Pros 良くなる点

ソングエディタの状態が保存できる

### Cons 悪くなる点

なし

## VOICEVOXのバージョン

0.16

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by Hiroshiba** [comment]
自分も1の、拡張子vvprojを共有する方法が良いかなと思いました！！

保存するのはtalkかsongどっちか１つだけで良いきがしてます。
２つとも保存したいケースが思いつかないので･･･。
いやでも「アプリを閉じるときにプロジェクトを保存するか聞く」辺りの挙動の大改革が必要になるかも･･･。

データ構造ですが、片方１つだけならzodの`discriminatedUnion`使って`{type: "talk", TalkProject}`か`{type: "song", SongProject}`のどっちかだけが入るようにするのが良さそう。
https://zenn.dev/terrierscript/books/2023-01-typed-zod/viewer/2-4-or-union#discriminatedunion

２つとも保存なら、まあ普通に`talk`キーと`song`キーを追加して、それぞれ`TalkProject`と`SongProject`を持たせるとかでしょうか。

**Comment by sevenc-nanashi** [comment]
これって誰か取り組んでいたりしますか？

**Comment by y-chan** [comment]
すみません、Assignつけ忘れてました！
#1800 が大方終わったので私の方で取り組み始めています...!
