### ISSUE TITLE
ソング画面でスペースキーを再生・停止に割り当てる

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1783]
## 内容

ソング画面でスペースを押すと再生が始まってほしいのですが、未実装です。
結構根幹の機能なので優先度高めにしつつissueを作りました。コミット募集中です！！

### Pros 良くなる点

使い勝手が大幅に向上する

### Cons 悪くなる点

実はショートカットキー周りがちょっと複雑。

### 実現方法

トーク側の再生が始まらないようにしつつ、ソング側で再生出来るようにする必要があります。
どちらもショートカットキーの`"再生/停止"`でコード全体検索すると追っかけやすいと思います。

#### トーク側の再生を抑える

雑な方法とちゃんとした方法があります。

雑な方法は、SongEditorかScoreSequencer辺りでspaceキーをフックし、かつそのeventをpreventする感じです。
こうすればトーク側までキーボードイベントが伝わらない･････と思います。
（キーボードショートカットに使っているMousetrapの実装によります）

ちゃんとした方法は、今開いているエディタがトークなのかソングなのかわかるようにして、トークが開かれているときのみトーク側のショートカットキーが動作するようにする感じです。
今どちらが開かれているのかは、vuex（store）のui.ts辺りで保持するのが良い気がしています。

#### ソング側の再生を可能にする。

こっちも雑な方法とちゃんとした方法があります。

雑な方法はspaceキーをlistenする方法です。簡単ですがショートカットキーを変更できません。

ちゃんとした方法は、既存のキーボードショートカットキー登録方法に対応させる感じです。
まあでも、トーク側の処理を追いかけて雰囲気でコピーすれば意外と簡単だと思います。

## その他

ぜひ！！

**Comment by sevenc-nanashi** [comment]
やってみようと思います。

**Comment by Hiroshiba** [comment]
おー！！！ぜひ！！

**Comment by Hiroshiba** [comment]
こちらは達成なのでcloseします！
