### ISSUE TITLE
歌詞付きmidiの歌詞を読み込めない

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1787]
## 不具合の内容

ソングエディタで、<s>shift-jisな</s>midiファイルの歌詞が読み込まれないかもしれません。
UTAUでexportしたmidiファイルが対象です。

こちらがサンプルファイルです。
https://drive.google.com/file/d/1ArGawXgHWR2WUUQ9fWq2z5NXddUcjZza/view?usp=sharing

### 現象・ログ

歌詞が「ドレミ」になる。ログは特に無さそう。

### 再現手順

このサンプルを読み込む
https://drive.google.com/file/d/1ArGawXgHWR2WUUQ9fWq2z5NXddUcjZza/view?usp=sharing

### 期待動作

特にエラーが出ず読み込める。

**Comment by y-chan** [comment]
現状は文字コードに関係なく、ノートの音程がそのまま歌詞になるコードになっています。(`lyric: getDoremiFromNoteNumber(value.midi)`)
https://github.com/VOICEVOX/voicevox/blob/5ad43b2653d493cdd9bc3e5afd882243aadc52ab/src/store/singing.ts#L1334-L1345

midiに歌詞を挿入する仕組みはどうやらmidiの拡張形式のxfフォーマット(普通のmidiはsmfフォーマットと呼ぶらしいです)で導入されたもののようで、それに対応したmidi読み込みライブラリを使うか、独自に既存のmidiライブラリを拡張する必要がありそうです。

サラッと探した感じ、xfフォーマットに対応したライブラリはなさそうな雰囲気だったので、自分たちで拡張する必要がありそうです....

**Comment by Hiroshiba** [comment]
あ～なるほどです！！　歌詞読み込めたよな～と思ってたんですが、それはMusicXMLでした。
ではとりあえずissueのタイトルを変更して、優先度はちょい低めで設定します！

**Comment by shigobu** [comment]
smfに歌詞イベントはあります。
公開されている「MIDI1.0規格書PDF版」の4-9ページに記載があります。
https://amei.or.jp/midistandardcommittee/MIDI1.0.pdf
