### ISSUE TITLE
ソングで四国めたん　トーク・ノーマルが選択されている状態になっている

### ISSUE THREAD

**Issue by madosuki** [VOICEVOX/voicevox#1797]
## 不具合の内容

起動後，ソングで四国めたん　トーク・ノーマルが選択されている状態になっている．この状態でピアノロールをクリックするとエンジンがASGIエラーを吐く．

### 再現手順

16.0-devエンジンを使って開発版VOICEVOXを起動し，ソングに遷移する．

## VOICEVOXのバージョン

0.?.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by Hiroshiba** [comment]
@madosuki issue 作成ありがとうございます！

ちょっと自分も気になってました。トークだからダメなんだ、ということに気づくのはかなり難しい気がします。
なんとか修正できると嬉しそうなのですが･････。

**Comment by madosuki** [comment]
処理を追っていくと
https://github.com/VOICEVOX/voicevox/blob/main/src/views/SingerHome.vue#L104
で最初のSET_SINGERが実行され，
https://github.com/VOICEVOX/voicevox/blob/23fe2593458110deb4dba2420e6c290c0944a4e2/src/store/singing.ts#L188C1-L195C26 でsingerがundefined時にデフォルトスタイルIDを使用するという流れになっていますが，ここでトークのスタイルが入り込んでしまうぽく #1782 と同じ問題なので同じようにとりあえず同様に決め打ちにするで対処ができるんじゃないかなーとは思います．

**Comment by Hiroshiba** [comment]
なるほどです！！！
トーク側の処理と見比べてみましたが、処理の流れは問題なく、ソング用のデフォルトスタイルが無いことが課題そうでした。
なのでおっしゃるとおり #1782 と同じ感じのワークアラウンドで良さそうに思いました！
