### ISSUE TITLE
ソング：ノート・テンポ・拍子の持ち方を変更する

### ISSUE THREAD

**Issue by sigprogramming** [VOICEVOX/voicevox#1800]
## 内容
（ソングのissueです）
現在、ノート・テンポ・拍子（とTPQN）は`Score`型で持っていますが、
将来のマルチトラック対応のことを考えると、ノートは`Track`型（まだ存在しません）で持ち、テンポ・拍子は全トラックに適用されるデータとして持つ形に変更した方が良さそうです。
以下のような感じです。
```ts
type Track = {
  notes: Note[];
};

type SongEditorStoreState = {
  tpqn: number;
  timeSignatures: TimeSignature[];
  tempos: Tempo[];
  tracks: Track[]; // マルチトラックに対応するまではトラック1つ
  ...
};
```

`Score`型は楽譜情報のみを保持するものとして、楽譜のインポート・エクスポート時に使用するのが良いかなと思います。

### Pros 良くなる点

- マルチトラック対応しやすくなる

### Cons 悪くなる点

- 特にないと思います

## その他
早めにやっておくと良さそう（後々楽かも）と思ったのでissueを作成しました。

**Comment by Hiroshiba** [comment]
プルリクマージさせていただきました！
こちら解決でしょうか 👀

**Comment by sigprogramming** [comment]
`tracks[0]`からgetter（`CURRENT_TRACK`or`SELECTED_TRACK`）に変更しておいたほうが良い気がしてきたので、それも行っておこうと思います…！
