### ISSUE TITLE
ソング：矩形選択を作る

### ISSUE THREAD

**Issue by sevenc-nanashi** [VOICEVOX/voicevox#1804]
## 内容

GarageBandにあるような矩形選択があると便利だと思います。

![image](https://github.com/VOICEVOX/voicevox/assets/59691627/f916138f-26e5-4a70-9465-831e457dc228)

### Pros 良くなる点

- 選択がしやすくなる

### Cons 悪くなる点

ないはず？

### 実現方法

コメントを参照： https://github.com/VOICEVOX/voicevox/issues/1804#issuecomment-1945756818

## VOICEVOXのバージョン

（開発版）

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

## その他

（なし）

**Comment by romot-co** [comment]
@sevenc-nanashi 
こちらありがとうございます！矩形選択につきまして現状のUI上の考慮点です：

1. 可能であればクリック+ドラッグで矩形選択にしたい
2. しかしノート追加とコンフリクトするため、矩形選択モードへの切り替えが必要(ノート追加やドラッグでのドローの簡便性を優先したい)
3. まずはShift+ドラッグで矩形選択させる...現状、複数選択で使用しておりますが、矩形選択の代替
4. いずれ必要に応じて矩形選択モード切り替えボタンを用意する

2.ふくめ、もしなにか良い方法があれば議論できれば幸いです...！

**Comment by Hiroshiba** [comment]
Romotさんの流れに同意です。

一般的に範囲といえばなぜかshiftなので、ctrlかshiftでいえばshiftかなと感じました！
（SynthVやACE StudioやVoisonaやVocaloid6やStudioOneなどがそうじゃないなら再考すべきかも）

> もしなにか良い方法があれば

（本気度１割くらいですが）ダブルクリック＋ドラッグを範囲選択にするとかは面白いかもと思いました。
スマホのテキスト範囲選択がそうなってるなーと。イベントハンドリングだいぶ大変になりそうですが･･･。

---

@sevenc-nanashi 

> GarageBandにあるような矩形選択

ちなみにこれはどういう操作なんでしょう 👀 （ググっても出てこなかった）

**Comment by sevenc-nanashi** [comment]
https://github.com/VOICEVOX/voicevox/assets/59691627/9a695a05-65d7-4429-8fa8-da7f3247518d

多分一般的なDAWには全部あると思います。

**Comment by Hiroshiba** [comment]
@sevenc-nanashi あーなるほどです！！！！
長押し＋ドラッグなんですね。テキスト範囲選択と同じだ。

**Comment by Hiroshiba** [comment]
@sevenc-nanashi @romot-co こちらちょっと後から見返した時に結局どうなってるかわからなくなっちゃうともったいないので整理しておきたいんですが、どうしましょ。
とりあえず、こう？

* とりあえず　shift+ドラッグ　（過去の調べてctrl+ドラッグの方が多そうだったらそっちでも）
* 将来的には「選択モード」を用意する

**Comment by romot-co** [comment]
@Hiroshiba @sevenc-nanashi 
いったん以下の想定でしたが、

> とりあえず　shift+ドラッグ　（過去の調べてctrl+ドラッグの方が多そうだったらそっちでも）
> 将来的には「選択モード」を用意する

いただいたガレージバンド(モバイル版)だとロングタップで範囲選択モード切り替えのため、

- 右クリック+ドラッグ

もPCに置き換えた場合の慣行や意味合いとしてありそうです😇

- Shift+ドラッグ or Ctrl+ドラッグ or 右クリック+ドラッグ(一般的にどうなっているか調査してから決める)
- 将来的には「選択モード」を用意する

という形でいかがでしょうか…！

**Comment by romot-co** [comment]
操作の対応表つくりなおしたほうがよさそうやも

**Comment by Hiroshiba** [comment]
> - Shift+ドラッグ or Ctrl+ドラッグ or 右クリック+ドラッグ(一般的にどうなっているか調査してから決める)
> - 将来的には「選択モード」を用意する
> 
> という形でいかがでしょうか…！

先に調査すべき、というのはとても同感です！！

<details>
<summary>右クリック＋ドラッグ</summary>

さすがに右クリック＋ドラッグはないだろうとは思うのですが、じゃあなんでスマホ版ガレージバンドは長押し＋ドラッグが範囲選択になってるのか若干考えてました。
まあ普通に、スマホはドラッグがスクロールに割り当てているので、通常ドラッグ操作で良いものでもワンアクション挟まないといけなくて、となるとダブルタップかロングタップしかなくこうなってるみたいな感じな気がしました。

</details>

**Comment by sevenc-nanashi** [comment]
変更しました。

**Comment by romot-co** [comment]
以下の赤文字の部分を修正すれば実装できそう
https://docs.google.com/spreadsheets/d/1ltGxtvCoUhDiX06F8E1-Tf1TWlC9XM98ESBNOIHUYjw/edit#gid=0

### 最低限

- ツール切り替えを用意しない
- Shift+ドラッグで矩形選択を実装する

### よい良い

- 編集ツールの他に選択ツールボタンを用意する
- 矩形選択やノート追加の動作などを以下の赤文字部分にあわせ修正する

- UIの位置としては以下
- デフォルトは編集モード(要議論？) : 個人的には特に最初、なにもせず入力できた方がよいように思える

![select-mode-toolbar](https://github.com/VOICEVOX/voicevox/assets/9082140/f79b1afd-02e5-4ffb-8264-7bee3b0ca881)

---

実装どうすればいいか確認中・問題なければIssueを修正

**Comment by Hiroshiba** [comment]
@romot-co さんの提案に賛成です！！（というより補強という感じかも）
@sevenc-nanashi さん的にも良さそうでしたら↑のコメントのリンクをissueの実現方法のとこに書き加えようかなと思ってます！ 🙏

**Comment by sevenc-nanashi** [comment]
コメントのリンクに差し替えました。
