### ISSUE TITLE
ソング：歌詞の流し込み機能がほしいです

### ISSUE THREAD

**Issue by shigobu** [VOICEVOX/voicevox#1815]
## 内容

ボーカロイド等で使える、歌詞の流し込み機能がほしいです。
現状、ノート毎に文字を入力する必要があり、歌詞の入力に手間がかかります。歌詞の流し込み機能では、テキストボックスに、ひらがなで複数文字の歌詞を入力して決定すると、各ノートに自動で歌詞を割り振ります。
とても便利です。

### Pros 良くなる点

歌詞の入力が早くなる。

### Cons 悪くなる点

とくになし。

## VOICEVOXのバージョン

0.16.1

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by Hiroshiba** [comment]
UIをどうするかが課題に感じました！
既存ソフトのUIがどうなってるかご存知だったら知りたいです。

既存手法は置いといて、とりあえずボイボのUIでできそうな流れはこうでしょうか。

* ノート右クリック
* 「歌詞を流し込む」みたいなメニュークリック
* →テキスト欄が入力できるダイアログ表示
* 決定したら歌詞が流し込まれる

「１文字ずつ流し込む」みたいなチェックボックスがあっても便利そう？

**Comment by shigobu** [comment]
私が想像してた機能は、ノートをダブルクリックしたときに表示されるテキストボックスに複数の文字を入力したら、二文字目以降が自動で次のノートに割り振られる、というような機能でした。
VOCALOID4Editor For Cubaseではそうなっています。

これだと、UIの変更は無いに等しく、実装も比較的簡単かと思います。

**Comment by Hiroshiba** [comment]
なるほどです！
今は１ノート１モーラですが、将来的に２モーラ以上可能になった場合の挙動は考えとかないとかもです。
あとその機能を知らないと「なんか勝手に次のノートに移動するバグがある」と思われるかもですね。

他のエディタはどうなっていますか？

**Comment by shigobu** [comment]
VOCALOIDしか持っていないのですが、ピアプロスタジオもVOCALOID4Editor For Cubaseと同様です。ノートをダブルクリックすると表示される枠がすでに歌詞流し込み画面になっていて、テキストボックスに入力しOKボタンを押すと、1ノート1モーラで割り振られます。区切り方法の設定はありませんでした。

**Comment by shigobu** [comment]
VOCALOIDは、1ノートに1モーラが基本らしいです。VOCALOIDの発音記号を直接入力すると、2モーラ以上当てることができるらしいですけど。

CeVIOやSynthesizer Vの1ノートに2モーラ以上入れられる機能って何であるのだろうか？ノートを分割すれば良いような気がします。
1ノートに2モーラ以上入れられる機能に意味があって、それがVOICEVOXのソング機能に必要であるならば、歌詞流し込み機能はCeVIOのように、分割方法を選ぶラジオボタン等をつける必要があると思います。

1ノート1モーラ固定で良いならば、歌詞入力欄に複数文字入れたら、モーラごとに分割されて順番にノートに割り振られる方式で良いのかなと思いました。実装も比較的かんたんかと思われます。

**Comment by Hiroshiba** [comment]
ノート内に複数モーラ置けるのはわりとメジャーで、1音だと感じる区切りが日本語テキストの発声とズレてるためだと思います！
よくある例だと「ワン・トゥー・スリー・フォー・ファイ（ブ）」とか、全部1音として歌うと思います。もちろん分割して手動にもできるので、AIが良い感じに調整してくれるか、人間がマニュアル調整するかの差かなと。
あと、1ノート1モーラは合成エンジンの制約で、その制約をエディタ側にも適用してるのがボカロ4、してないor複数モーラもいけるのが他って感じかなと思います。

とりあえず状況が変化するまでは、勝手にモーラが次に送られるように実装し、将来的にはチェックボックスがある工程を挟実装に変える…かも、というのはどうでしょうか？

この辺りご意見あれば！！ @romot-co @sigprogramming @y-chan

**Comment by romot-co** [comment]
@Hiroshiba 
> とりあえず状況が変化するまでは、勝手にモーラが次に送られるように実装し

こちら、同意です！

---

UI的に考えてみると

- 変更後の状態が予測できない
→ どこで区切られるかわからないなど
- 入力もそうですが、間違えた場合・修正したい場合の修正の容易さを担保する方向がよさそう
→ たいてい1文字ずれたとかが問題になるので、その調整を容易にするなど？
- ミスっても元に戻せばいいや(可逆変更)ができる
→ Undo/Redoいるので当面むずかしそう

あたりが重要そうに思えます。

案ですが、以下の感じがありえそうかな、と思っております。
https://xd.adobe.com/view/c433028a-50b3-4411-871d-f4e13d5bd358-9160/

これであれば、とりあえず最初は

- 1モーラで分割して流し込める
- ノートに対し変更後の歌詞のプレビューが行える or 対象ノートの歌詞範囲明示のみ

あたりでしょうか…？

**Comment by sigprogramming** [comment]
「1ノートに2モーラ以上入れられる機能」は、英語や「～し（たい）」「～（ない）」等の二重母音があるときに（AIがいい感じに調整してくれると）便利＆時短になるかなと思います。

@Hiroshiba 
> とりあえず状況が変化するまでは、勝手にモーラが次に送られるように実装し

良いと思いますが、「右クリック→歌詞の流し込み」で普段入力を行っているユーザーも多いかもと思いました！
なので、歌詞入力のダイアログ（チェックボックスなし）も同じくらいの優先度で実装が良いかもです。

**Comment by Hiroshiba** [comment]
@romot-co 案見させて頂きました、なるほどです！！！
プレビューするの良さそうなのですが、「入力中のinputでカーソルより右の文字を薄くする」が相当しんどいかもです。
多分HTML inputじゃ無理で、自作する感じになりそうかもで、なかなか厳しいかもしれません･･･。

@sigprogramming さんの意見も確かにと思いました！
まあもしダイアログ版がなくても、いつか2文字入力して勝手に次のノートに１モーラ移動することに気づいてくれるかもとかちょっと思いました。

**Comment by Hiroshiba** [comment]
次のノートに勝手に歌詞が移動するのは、将来的に１ノートに２モーラ以上入力可能になった場合に衝突する気がしました。
その解決ができて実現可能そうなUXの目処が立っていない場合、２モーラ入力を簡単にするために将来破壊的に仕様変更するか、頻繁に行う２モーラ入力が面倒なUIのままにするか、という２択を選ぶことになるかもです。

となると現状は、自動的に入力歌詞が次のノートに行く仕様は一旦ペンディングにして、とりあえず右クリックで歌詞流し込みを可能にするのが無難かもと思いました！
（重要度のバランスがちょっと微妙かもなので違和感あったらご指摘いただければ！）

あと歌詞入力をダイアログじゃなくポップアップとかにすれば、プレビュー表示しながら流し込みもできるかもです。

@sigprogramming 

> 「1ノートに2モーラ以上入れられる機能」は、英語や「～し（たい）」「～（ない）」等の二重母音があるときに（AIがいい感じに調整してくれると）便利＆時短になるかなと思います。

マジレスしてしまうと、データがなくて色々用意するのに相当大変そうですね･･･ 😇

**Comment by sevenc-nanashi** [comment]
そこそこ欲しかったのでやってみようと思います。

**Comment by Hiroshiba** [comment]
@sevenc-nanashi ぜひぜひ！！

**Comment by Hiroshiba** [comment]
@sevenc-nanashi さんプルリクエストありがとうございます！

頂いたプルリクエストの実装は、実は[以前に課題有るよなーと議論した内容](https://github.com/VOICEVOX/voicevox/issues/1815#issuecomment-1920416117)のUI（１ノート１モーラを前提としたUI）だったりします。
問題だったのは UX の迂回策が見つかってなかったからでしたが、迂回策を思いついたのでメモです。

（将来的に）ノートに歌詞を入力した場合のデフォルトの挙動をグローバル設定で選べるようするとかどうでしょう。
で、デフォルトの動作以外で歌詞を流し込みたい場合は右クリックから歌詞入力とか。
デフォルトの動作はたぶん言語やエンジンによって最適なものが変わる気がします。将来的には言語によってデフォルト設定を変えてもいいかも。

UX をまとめるとこうですかね

* １ノート１モーラ前提の日本語エンジン
	* VOICEVOXは"今"これ
		* ボカロもたぶんこれだけど、英語エンジンもあるのでこれを大前提にしていない
	* 自動歌詞送りが実装簡単＆便利
* １ノート２モーラ以上入力できる日本語エンジン
	* NEUTRINOとか大体の日本語歌声エンジンがこれ（なのでマルチエンジンを考えるとこのUXを想定すべき）
		* 便利なのでVOICEVOXも可能ならこっちを目指したい気持ちがある
	* 大体はノート入力時の歌詞自動移動がなく、右クリックで歌詞流し込みができ、スペース区切りで次のノートに行くか、1文字ごとに次のノートに行くかを選べる UI になってる
		* [SynthVの例](https://japancreatorslabo.com/synthesizerv-enter-lyrics/)
		* なので右クリックで歌詞入力は将来的にほぼ必須
	* ノートに歌詞入力時の自動歌詞送りが不便なこともある
		* これはデフォルトの歌詞送り方法を設定可能にすれば解決
* 英語エンジン
	* 1ノート1モーラを前提にするかしないかに関わらず、そもそも文字と音が1対1対応しない
		* 日本語におけるひらがなカタカナがない
	* 歌詞流し込みする時は右クリックでやることが多い
	* ちなみにSynthVも英語エンジンがあるのでこっち寄りで、歌詞流し込みのショートカットキーはcommand+L。
