### ISSUE TITLE
Inquiry About Project Implementation Principles

### ISSUE THREAD

**Issue by Skaiyin** [VOICEVOX/voicevox#1816]
I've recently come across this fascinating project. I'm particularly interested in understanding the core implementation principles behind it. I've gone through the README and explored the documentation, but I found myself looking for more detailed insights into it.

Could you please provide some guidance on the project's architecture or point me towards any resources or documentation that delve deeper into its implementation? I'm eager to learn more about the design decisions and the technologies used in this project.

Thank you for your time and for the amazing work on this project!

**Comment by Hiroshiba** [comment]
@Skaiyin 
Thank you for your interest!

I realize that VOICEVOX might have insufficient documentation and not much information available. I would like to provide better guidance, so could you please tell me what you would like to know and why you are interested in learning about it?

---

(japanese) ご興味を持っていただいてありがとうございます！

VOICEVOXはドキュメントが不足していて、情報があまりないと思います。
より良い案内をしたいので、何を知りたいか、そしてなぜ知りたいかを教えてください！

**Comment by Skaiyin** [comment]
@Hiroshiba 
Hello Hiroshiba,
Thank you for your response! I became interested in VOICEVOX after seeing some related projects in videos. I noticed that while many systems can generate speech smoothly, they often lack detailed control in aspects like voice modulation and pitch. This led me to explore how to create and manipulate a voice model myself.

In particular, I am curious about:
- Voice Model Creation: How does VOICEVOX approach the creation and training of custom voice models? What kind of data and algorithms are typically involved in this process?
- Pitch Adjustment Techniques: How does VOICEVOX specifically manage the pitch adjustments in voice synthesis? Is there a particular method or algorithm employed for this purpose?

I am exploring this technology both out of personal interest and for a project I am considering. If you have any recommendations for books, academic papers, or online courses that could provide a deeper insight into these topics, I would be extremely grateful. This way, I can explore these concepts in detail without taking up too much of your time.

**Comment by Hiroshiba** [comment]
@Skaiyin 
Understood, here you go!
https://docs.google.com/presentation/d/1GcYm0vl0G8RWnmfKsFuiPWE_28MppbeE6qJveYgzU2U/edit?usp=sharing

And I apologize, but this is a place for developing the VOICEVOX software, not a forum for discussing speech synthesis technology, so I will have to close this. If you're interested in OSS development, please feel free to visit us again!

---

なるほどです。こちらをどうぞ！
https://docs.google.com/presentation/d/1GcYm0vl0G8RWnmfKsFuiPWE_28MppbeE6qJveYgzU2U/edit?usp=sharing

そして申し訳ないのですが、ここはVOICEVOXソフトウェアを開発する場所で、音声合成技術を話す場ではないためcloseさせていただきます。
OSS開発に興味あったらぜひまた来てください！
