### ISSUE TITLE
ソング：MIDIインポートでトラックを選択できるようにする

### ISSUE THREAD

**Issue by romot-co** [VOICEVOX/voicevox#1818]
## 内容

プロトタイプだと、MIDIインポート時にトラックを選択できない(最初のトラックを利用している)ため、
MIDIファイルによっては正常に読み込めないように見える

使い勝手の前に、まずは理由がわからないけどできない、というのを無くすのがよさそうに思えています

### Pros 良くなる点

MIDIつくったのに原因不明で読み込めないというのがなくなる

### Cons 悪くなる点

おそらくなし

#### 1. 簡単そうな方法: 警告のみ

単に読み込み時に「1つめのトラックが読み込まれます」と標準アラート表示する

#### 2: めんどくさい方法: インポートモーダルダイアログを用意する

トラックが複数ある場合、インポート時にトラックを選択するモーダルを用意する

初期案(トラック選択だけでよさそう)
https://xd.adobe.com/view/5f744622-2dfd-4e3f-b9f0-483e9ff5587a-0a27/

Vuex周辺だと以下の部分の調整などが必要そうです
https://github.com/VOICEVOX/voicevox/blob/main/src/store/singing.ts#L1321

## VOICEVOXのバージョン

0.1.6

**Comment by Hiroshiba** [comment]
こちら、Xで数例要望を見かけたので優先度を少し上げさせて頂きました･･･！
もしご興味あれば！
