### ISSUE TITLE
ソング：歌wave出力時のデフォルトファイル名を良い感じにする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1833]
## 内容

今は`test_export.wav`なのですが、ちょっと味気ないので良い感じにしたいです。

プロジェクトファイル名が指定されている場合は`プロジェクトファイル名.wav`が良い気がします。
↓がマージされ次第可能になります。

- https://github.com/VOICEVOX/voicevox/pull/1829

プロジェクトファイル名が指定されていない場合は、たとえば`[キャラ名]_[出だしの歌詞数文字]`とかが良いと思います。
このissuえはとりあえず後者の「プロジェクトファイル名が指定されていない場合」の方が完了したら完了だと思います。

### Pros 良くなる点

公式っぽい

### 実現方法

「test_export」でコード全体検索したら変更すべき場所がわかるかも

## その他

そこそこにやりやすいタスクだと思うので初心者歓迎タスクラベルを付けてみました。

**Comment by P0ngCh4ng** [comment]
こちらのタスク作業してみます！

OSS不慣れなので確認させていただきたいんですが、

voicevoxのリポジトリをfork
-> 自分のリポジトリ内でブランチを切ってコミット
     -> voicevoxのリポジトリにPRを切る

で大丈夫ですか？
お手数おかけします！

**Comment by Hiroshiba** [comment]
おお、ぜひぜひ！！
わからないところがあれば気軽に聞いてください！🙏

流れは合っているはずです！
細かい部分気になる感じでしたら、以前コントリビュートしてくださったこちらの方の記事が参考になるかもです！
https://zenn.dev/tantan_tanuki/articles/309d6976d749ea

**Comment by Hiroshiba** [comment]
やってしまって大丈夫です！
ちなみにPR側に「resolve #1833」とか書いておけば自動的にcloseされたりします。

今回は解決ということでこちらでcloseさせていただきます。ありがとうございました！ 🙏
