### ISSUE TITLE
ソング：Undo/Redoを作る

### ISSUE THREAD

**Issue by sevenc-nanashi** [VOICEVOX/voicevox#1834]
## 内容

タイトル通り。

### Pros 良くなる点

便利

### Cons 悪くなる点

ないはず？

### 実現方法

基本的にはトーク側のと同じ感じで作れるとは思いますが、Undoスタックを分けるかどうかで少し考える必要がありそうです。
- 分ける：
  - Pros：認識外での変更がなくなる
  - Cons：ステートが増える
- 共有する：
  - Pros：コードを使いまわせる部分が増える
  - Cons：認識外での変更が起きるかも

（まぁどっちでもほとんどのユーザーには関係ないと思いますが）

## VOICEVOXのバージョン

0.16.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

## その他

（なし）

**Comment by Hiroshiba** [comment]
Discordを見る感じ @y-chan さんが作っていらっしゃるかもしれないのでコメントメモです！
https://discord.com/channels/879570910208733277/893889888208977960/1205186250550804480

**Comment by y-chan** [comment]
すみません...!
Issueを立てずに進めてしまいました... 🙇 

まだ不完全なのですが、後でDraft PRを作ります...

とりあえず、プロジェクトファイルの議論をもとに、不幸が起きにくい方向で作るとなると、Undo/Redoスタックはトークとソングで分けて作るのがよいのかなと思いました！
ただ、これをやる場合、トークとソングでどっちのページを開いているかを判定して、ショートカットキーの判定を変えてあげる必要がありそうで、やらなきゃいけないことは増えそうかなと....(一旦Draft PRでは、どっちも実装できる形にしておいて、ショートカットキー側が落ち着いたらトークとソングで分けられるような設計にしようかなと思っています)

**Comment by Hiroshiba** [comment]
基本的にはやっぱりソング・トークでundo処理を分けるべきだと思います！
でもこっちもプロジェクト機能と同様、分けたほうが実装が大変なので、とりあえず共通のをで賛成です。

ちなみに分ける場合のショートカットキーの判定は @sevenc-nanashi さんの↓のプルリクがマージされれば解決だと思います！！

- https://github.com/VOICEVOX/voicevox/pull/1822

個人的には型パズル周りとcommands周りを少し心配しています。
きれいに実装が分けられるのかは既存実装に依存していそうだなぁと。（未調査です）

**Comment by sevenc-nanashi** [comment]
#1861 と合わせて実装が完了したと思うのでClose。
