### ISSUE TITLE
`/`を`/talk`にリダイレクトする

### ISSUE THREAD

**Issue by sevenc-nanashi** [VOICEVOX/voicevox#1835]
## 内容

タイトル通りです。

### Pros 良くなる点

- ブラウザ版で開発するときにViteの出力から直接開ける

### Cons 悪くなる点

ないはず？

### 実現方法

Vue-routerにリダイレクトのオプションがありそう（調べてない）

## VOICEVOXのバージョン

（開発時のみ）

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

## その他

（なし）

**Comment by Hiroshiba** [comment]
あっても良さそうに思いました！
「？」をとって初心者歓迎タスクをつけてみます！

**Comment by sevenc-nanashi** [comment]
https://github.com/VOICEVOX/voicevox/pull/1875 で実装された（？）のでClose。

**Comment by Hiroshiba** [comment]
close助かります！！
結構解決してるのに残ってるのある気がしますね…😇
