### ISSUE TITLE
ソング：ダイアログを開いたときに右下にスライダーが出続けてしまう

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1840]
## 不具合の内容

↓の右下のこれです
![image](https://github.com/VOICEVOX/voicevox/assets/4987327/1252e637-5589-4a84-96a3-75e50e4343ba)

### 再現手順

ソングからダイアログを開く

### 期待動作

バーがダイアログより手前に表示されない。
## その他

ここのzIndexが大きいのが原因だと思われるけど、どう解決すれば良いかはわからない。
https://github.com/VOICEVOX/voicevox/blob/fb78789ade8bbb308ba74b84ac17e77ab818aa41/src/components/Sing/ScoreSequencer.vue#L163

**Comment by sevenc-nanashi** [comment]
#1790 で、sing-mainにposition: relativeがつくので治りますね。
![image](https://github.com/VOICEVOX/voicevox/assets/59691627/2caa0c36-846f-4893-94f1-b64eb985a9b5)

**Comment by Hiroshiba** [comment]
なるほどです！！

そちらのPRにこのissueの自動close書けば良さそう。書きます！！
