### ISSUE TITLE
softprops/action-gh-releaseがmacOSで同じファイルのアップロードに失敗する

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1845]
## 不具合の内容

ちゃんとわかってないのですが、dev用のreleaseを作る際にmacOSのdmgだけエラーで落ちているっぽいです。

### 現象・ログ

```log
Run softprops/action-gh-release@v1
⬆️ Uploading VOICEVOX 0.16.0-dev.dmg...
Error: Failed to upload release asset VOICEVOX 0.16.0-dev.dmg. received status code 422
Validation Failed
[{"resource":"ReleaseAsset","code":"already_exists","field":"name"}]
```

![image](https://github.com/VOICEVOX/voicevox/assets/4987327/67318dec-4106-4db8-a8fb-166a8c93cd25)

### 再現手順

おそらく同じファイルにアップロードしようとすると落ちる。
`?.?.?-dev`系のActionsを参照

## その他

`softprops/action-gh-release`は更新が止まってしばらく経っているので、他の何かに移動してもいいかも？

**Comment by sabonerune** [comment]
Windowsでのリリースではまずリリース済みのファイルを削除してその後にアップロードしています。
![スクリーンショット 2024-02-14 181202](https://github.com/VOICEVOX/voicevox/assets/102559104/c8802f6b-86e7-4e6c-a323-f447dbd17367)
一方dmgのアップロードの場合は削除をせずにそのままアップロードをしています。

この挙動を参考にビルドスクリプトを観察したところdmgのファイル名にスペースが含まれていることに気づきました。

Windows版ではわざわざビルド後にリネームをしていることからファイル名にスペースが含まれていると何か問題が起きたのではないのでしょうか？
(PRにスペースを置換する理由が特に議論されていない https://github.com/VOICEVOX/voicevox/pull/465#discussion_r747316381)
https://github.com/VOICEVOX/voicevox/blob/33167d88db48b96c089ec4dff7a0acfc3e69a2e8/.github/workflows/build.yml#L481-L489


ふと思ったのですが置換せずに最初からスペースが含まれないファイル名を指定すればいい気がします。
https://github.com/VOICEVOX/voicevox/blob/33167d88db48b96c089ec4dff7a0acfc3e69a2e8/.github/workflows/build.yml#L112

**Comment by Hiroshiba** [comment]
うおーーーーーーーーーーーなるほどです！！！！

> ふと思ったのですが置換せずに最初からスペースが含まれないファイル名を指定すればいい気がします。

この方針で問題ない気がします！！
まあそもそもスペース区切りのファイル名がちょっと危ないので･･･。

････いつもすみません、もしよかったら修正お願いしてもよろしいでしょうか 🙇 @sabonerune
