### ISSUE TITLE
[ソング] ノートのレンダリングがうまく行かない理由を説明する

### ISSUE THREAD

**Issue by y-chan** [VOICEVOX/voicevox#1846]
## 内容

Xなどを見ていると、かなりの数の人がレンダリングに失敗している理由がわからずに詰まっていそうです。(ほぼ100%、1ノートに2モーラ以上挿入していることが原因です)
これらを、ホバー時のツールチップなどで説明してあげると、UXが向上しそうです。

### Pros 良くなる点

UXの向上・ユーザーが詰まりにくくなる

### 実現方法

エンジン側からは、エラーの理由として`"lyricが不正です: {note.lyric}"`という内容が返ってきているはずなので、その文言を元に、エラー内容をユーザーに提示できるとよいかなと思います。

## VOICEVOXのバージョン

0.16.1

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by Hiroshiba** [comment]
今はエラー原因表示が特に無いので、なんでもいいから１つエラー原因表示してあげたいですね…。
その意味では実装難度的にトースト表示が手っ取り早いかもとか思いました！
（参考コードの探し方：コード全体でtoastと文字列検索）

あとはもう左下にチップス表示してあげるとかも。
（confirmtipとかで全体検索すると見つかるかも）

エラーに出くわす経路はノートを足した場合とmusicxml等をimportした場合の２経路あると思うので、そこ考慮しても良いかもと思いました！

**Comment by romot-co** [comment]
Tooltipだとイメージとしてはこんな感じです(状態が切り替わるタイミングがおかしいですので、大体として…)
とりあえず即時バリデーションはなしにして、エンジン側からエラーの場合は表示するようにやってみられればと思います。
https://github.com/VOICEVOX/voicevox/assets/9082140/e6856709-208e-40f3-b5fa-f0bf74bbca56

**Comment by Hiroshiba** [comment]
実装ありがとうございました！

- https://github.com/VOICEVOX/voicevox/pull/1893
