### ISSUE TITLE
書き出し先を固定するをオンにした状態で書き出し先のフォルダが未指定のまま書き出しを行うとインストールディレクトリにファイルが保存されてしまう

### ISSUE THREAD

**Issue by sabonerune** [VOICEVOX/voicevox#1847]
## 不具合の内容

ref: https://github.com/VOICEVOX/voicevox/pull/1844#pullrequestreview-1878526071

書き出し先を固定するを初めてオンにすると書き出し先にのフォルダが未指定状態になります。
このままの状態で音声書き出しをするとインストールディレクトリにファイルが保存されてしまいます。

### 現象・ログ

fixedExportDirの初期値が空文字のため保存場所がカレントディレクトリからの相対パスとして扱われてしまうためカレントディレクトリであるインストールディレクトリに保存される。

### 再現手順

1. 設定ファイルの`fixedExportDir`を空文字にする
2. 書き出し先を固定するをオン
3. 音声書き出しを行う

### 期待動作

少なくとも明示的に指定しない限りインストールディレクトリが書き出し先にならないようにする。

## その他

Windows環境のVOICEVOXのインストールディレクトリはアンインストールが実行されると(更新・上書きも含む)中身が全て削除されます。

気付かないまま放置すると非常に悲しいことになるので修正するべきです。

どのような動作にすべきかは色々あるような気がします。

- 保存時に`fixedExportDir`がファイルパスか確認する。
- 初期値にapp.getPath("documents")が設定されるようにする。
- 書き出し先を固定するをオンにしたときダイアログが表示されるようにする。

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！！

取れる手のうち3つ目の

> 書き出し先を固定するをオンにしたときダイアログが表示されるようにする。

が一番良いと思います。空欄保存がないようにできるので。
ただまあ結構実装が大変な気がします。[書き出しファイル名パターン](https://github.com/VOICEVOX/voicevox/blob/33167d88db48b96c089ec4dff7a0acfc3e69a2e8/src/components/Dialog/FileNamePatternDialog.vue#L9)と同じように実装すればいいと思うのですが･･･。

なので一旦

> 初期値にapp.getPath("documents")が設定されるようにする。

でも良いのかなと思っています。何よりも穴を防ぐことが大事そうかなと。

実装してくださる方募集中です 🙇
