### ISSUE TITLE
[ソング] PhraseKeyに型をつける

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1856]
## 内容

ソングはPhraseという区切りがあり、対応するPhraseKeyをキャッシュなどに利用しています。

### Pros 良くなる点

型間違いを起こしづらくなり、コーディングが楽になる

### 実現方法

たぶんこんな感じで定義して、
https://github.com/VOICEVOX/voicevox/pull/1217/files#diff-a2e928a7b8428dba5f753cc8014e39204ccb3aaf1049ba8567f4b59af69defc7R26-R28
あとはいろんなところのstringをPhraseKeyに置き換える感じだと思います。
SingingStoreStateの`phrases: Map<string, Phrase>`のstringとか。

`phraseKey`でコード全体検索をすると見つけやすいはず。
トーク側の`AccentPhrase`と間違いやすいかもなので注意が必要かも

## その他

- https://github.com/VOICEVOX/voicevox/pull/1836

がマージされてからのがやりやすそう。

**Comment by jdkfx** [comment]
この内容ってこちらで解決されていませんか？
間違っていたらすみません！

https://github.com/VOICEVOX/voicevox/pull/2248/files#diff-d26d5d8607099d0eb54ebe12db20ed3f7d1c9d9593727df50d16feef55a6bb4a

**Comment by sevenc-nanashi** [comment]
確かにできてるかも、ありがとうございます

**Comment by Hiroshiba** [comment]
報告ありがとうございます！！

結構closeし忘れてるのあると思うので、また見つけたらぜひコメントいただけると･･･！！
