### ISSUE TITLE
[refactor] MenuBarを１つにする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1860]
## 内容

ウィンドウの一番上に表示されているメニューバーですが、表示は1つに見えて実はソング・トーク用のメニューバーが２つが用意されています。
これを1つにするタスクです。

### Pros 良くなる点

MenuBar内にある、アプリで1回だけ実行されて欲しい処理が実行できるようになる。
（ショートカットキーの登録など）

### 実現方法

2つのメニューバーは`BaseMenuBar.vue`を子コンポーネントにしているラッパーの形になっています。
そうではなく、`App.vue`の直下に`BaseMenuBar`が１つだけ存在する形を目指すことになると思います。

問題はBaseMenuBarのpropsのfileSubMenuDataですが、とりあえず親（App.vue）から必要なデータを受け取る形が良いかなと。
あとはApp.vueでこんな感じで`fileSubMenuData`を渡せばいいかなと！
```ts
const fileSubMenuData = computed(() => {
  // editor = "song" もしくは "talk"
  return {talk: talkFileSubMenuData, song: songFileSubMenuData}[editor]
})
```

### Pros 良くなる点

MenuBar内にある、アプリで1回だけ実行されて欲しい処理が実行できるようになる。
（ショートカットキーの登録など）

## その他

Vue的な知識が必要になり、ちょっと設計の知識も必要になりますが、結構勉強になると思うのでもしよければ！
（分からないこととか、こういう設計で合ってる？とかあれば聞いてください！）

**Comment by sevenc-nanashi** [comment]
やってみようとおもいます。
