### ISSUE TITLE
hostkeys-jsに変更した影響でmacOSでCmdを使ったショートカットが使えなくなっている

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1862]
## 不具合の内容

mainブランチにて、macOSでcmdを使ったショートカットが使えなくなっていそうでした。

### 現象・ログ

[mousetrap](https://craig.is/killing/mice)が[hostkeys-js](https://github.com/jaywcjlove/hotkeys-js)に変更された影響だと思われます。

- https://github.com/VOICEVOX/voicevox/pull/1822

mousetrapはmacOSのCmdを`Meta`としても扱えていたけど、hostkeys-jsでは扱えなくなったっぽい。
VOICEVOXでは保存を`Meta`としているので、さてどうしようかなという感じです。

あとwindowsではwinキーが`Meta`だけど、それもサポートされなくなってるかもしれない･･･？
まあVOICEVOXは実質的にwinキーをメインサポートしていない（表示が`Cmd`になる）ので、まあ･･･切っても良いかも。

### 再現手順

macでショートカットを使ってみる

## その他

ショートカットキーを使うe2eテストがあったほうが良いかもしれない。

**Comment by y-chan** [comment]
Macだとかなり困りますね....

軽く調べたところ、READMEのexampleではサポートキーとして`command`が登場していました。
https://github.com/jaywcjlove/hotkeys-js?tab=readme-ov-file#supported-keys
これか、あるいはコードをたどったところ、`metaKey`が使えそうな感じがしました。

Windowsのwinキーについては言及がなさそうでしたが、まあ`metaKey`でいけるんじゃないかなと思います。(まあサポート切ってもいいかも良いというのは同意です)

少なくとも、configのマイグレーションが必要そうですね....

**Comment by Hiroshiba** [comment]
ライブラリに合わせてconfigを変えるのはなんか変な気もするので、マイグレーションはちょっと慎重になりたい･･･かもです。（ちょっとわからない）
とりあえずconfigはmetaで保存しておいて、hotkeys-jsに登録するときにcommandなりに翻訳する･･･とかが無難かも･･･？

configに保存してなかったら最初から`command`か`cmd`使用で良かった気もします。

**Comment by sevenc-nanashi** [comment]
> hotkeys-jsに登録するときにmetaをcommandなりに翻訳する･･･とかが無難かも･･･？

これでいい気がします。combinationToBindingKeyあたりでやるのがいいかも

**Comment by Hiroshiba** [comment]
こちらmacを持ってる僕が取り組もうかなと思ってます！　･･･そのうち？

@sevenc-nanashi 
cmd等のショートカットキーが使えるか確認するe2eテストをお願いしても良いでしょうか 🙇 
なんとなくですがundo/redoがちょうどいい気がしてます。
（あとついでにショートカットキー変更のe2eテストもあるとかっこいいかも）

**Comment by Hiroshiba** [comment]
とりあえず解決するPR作りました！

- https://github.com/VOICEVOX/voicevox/pull/1865
