### ISSUE TITLE
window.electronをwindow.backendにする

### ISSUE THREAD

**Issue by sevenc-nanashi** [VOICEVOX/voicevox#1869]
## 内容

タイトル通り。

### Pros 良くなる点

ブラウザ版が`window.electron`に代入する、というぱっと見謎のコードが自然になる

### Cons 悪くなる点

ないはず？

### 実現方法

> SandboxKeyという名前でexportしている中身を書き換えて、各所window.electronでアクセスしてるところを書き換えるだけなので結構楽に行けるはず
> @yamachu | https://discord.com/channels/879570910208733277/893889888208977960/1210267202234621952

## VOICEVOXのバージョン

0.?.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

## その他

docs内のコードの歩き方とかが参考になるかも？

**Comment by Hiroshiba** [comment]
issue 作成ありがとうございます！

`初心者歓迎タスク`タグがついてますが、難しいかも？（ちゃんとコード追ってないですが）
確かに全体設計が分かってると変更するべき行数は少ないかもだけど、全体設計わからないとなのでその辺の案内を少し書いておくのはどうでしょう。
