### ISSUE TITLE
<template>内に書くコンポーネント名をkebab-caseからPascalCaseに変えたい

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1873]
## 内容

Vueのコンポーネントはケバブケースでもパスカルケースでもどちらでもいいとされています。
https://ja.vuejs.org/style-guide/rules-strongly-recommended#component-name-casing-in-templates

個人的にはケバブケースは基本的にデメリットしかないと思ってます。

* コピペできない
	* コンポーネント名はもともとPascalCaseなので、毎回ケバブケースに変えないといけない
	* 正直これが一番辛い･･･。
* コード検索がやりづらい
	* 上と一緒ですが、コードを検索する時にケバブケースに変えないといけないのが結構大変です

大体の利用箇所でケバブケースがなくなれば完了だと思います。
とりあえず方針を示すためと、あと議論ができればと思ってissue化しました。

### Pros 良くなる点

コピペできるようになる

### Cons 悪くなる点

コード全体検索をした時、import 箇所と利用箇所が同じ文字列になるので差が分からなくなる。
（これは定期箇所と利用箇所で文字列が違うのがそもそもいまいちな気がしてます）

### 実現方法

ひたすら置き換えていく。
1ファイル1ファイルだと置き換えに手間がかかるので、ある程度まとめて一気に置き換えていただけると助かります！

これから書き足すところだけはパスカルケースにして、置き換えは気が向いた時にでもいいかも。

**Comment by cm-ayf** [comment]
https://eslint.vuejs.org/rules/component-name-in-template-casing というまさにそのようなESLintルールがあるようですね．

**Comment by Hiroshiba** [comment]
@cm-ayf なるほどです！！！　とても良さそうです！！

**Comment by cm-ayf** [comment]
↑10分でできましたので
