### ISSUE TITLE
キャラ選択をショートカットキーで行うことが出来るようにする

### ISSUE THREAD

**Issue by tsym77yoshi** [VOICEVOX/voicevox#1878]
VOICEVOX/voicevox_engine#742 の内容の一部アレンジ。この機能は欲しいなと思ったので。

## 内容

設定/キー割り当てに「○○(キャラクター名)を選択」をキャラクターの数だけ追加する
これによってキャラごとにそのキャラへ切り替えるショートカットキーを登録できるようにする

### Pros 良くなる点

ショートカットキーを覚えればキャラクターの選択がしやすくなる

### Cons 悪くなる点

設定 / キー割り当てのページが煩雑になる

### 実現方法

コードとしてはどこかのタイミングでショートカットキーの配列にこれの配列を追加するのが良いかも...？

## VOICEVOXのバージョン

0.16.1

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

## その他

https://github.com/VOICEVOX/voicevox_engine/issues/742#issuecomment-1710359039 とあったが新しいissueが見つけられなかったので

アコーディオンメニューで畳むのもよさそうだが処理が複雑になりそう

キャラクターの増減にたえるようにするのが少し面倒...？

**Comment by Hiroshiba** [comment]
issueありがとうございます！！

面白い機能だと思うのでちょっと議論にお付き合いいただければ･･･！

キャラクターごとにショートカットキーを割り当てるのは、[キャラクター変更ショートカットキー](https://github.com/VOICEVOX/voicevox/issues/1187)のissueにある「上からN番目のキャラクターにする」ショートカットキーでかなり代替可能かも？と思いました！

というのも、よくゲームで番号キーを押すとその番号にある道具を持つUIがあって、慣れてくるとこれで十分だったりしました。（マイクラがこれです。）
VOICEVOXはキャラクター並び替えができるので、お気に入りのキャラクター上の方に設定し、どの番号がどのキャラクターなのか何度か試しているうちに素早い変更に慣れるかも、と！

あと、キャラクターごとにショートカットキーを割り当てる場合、キャラごとに設定が必要でユーザーがちょっと大変かもです。
あとはまあ実装する場合に専用の UI が必要かも･･･？（マルチエンジンの有無やエンジンの読み込み状況等でキャラクターの数などが変わってくるため）

どの機能も想像になってしまいますが、ぜひ使い勝手の想像をお聞きしたく！！

**Comment by tsym77yoshi** [comment]
確かに11人以上必要な場面も考えにくいので上からN番目のキャラクターにする設定で十分そうです！このissueはcloseして #1187 に移動しようと思います！
