### ISSUE TITLE
onActivatedを不要にする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1886]
## 内容

ソング・トークの切り替えは`KeepAlive`になっています。
これはonUnmountedが呼ばれず、ステートをメモリに乗せておき、切り替わるときにoMountedの代わりに`onActivated`が働く仕組みです。
初回はonMountedとonActivatedが、それ以降はonActivatedのみが呼ばれます。

と思いきや、子コンポーネントに関してはそうではなく、初回でonActivatedが呼ばれない場合があります。
この条件が重なったときに[コードが複雑化](https://github.com/VOICEVOX/voicevox/pull/1828)することがあります。
まあさほど難しくはならないのですが、結構予想外の動きをしてしまうので、可能なら`onActivated`を不要にしたいです。

以前はvue-routerを使っていた関係で`KeepAlive`が必須だったのですが、[撤廃した](https://github.com/VOICEVOX/voicevox/issues/1872)ので抜け出すことが可能になりました。
KeepAliveをやめ、onActivatedコードもなくせたらこのissueは完了だと思います。

### Pros 良くなる点

ランニングコストが下がる。

### Cons 悪くなる点

可能性として、毎回マウント処理が走るのでエディタの切り替えがだいぶ重くなるかも。
こればかりは１回実装してみないとわからないかも。

### 実現方法

KeepAliveをやめ、onActivatedコードをなくす。

**Comment by Hiroshiba** [comment]
こちら今晩取り組んでみようかなと思ってます。
@sigprogramming さん辺りもし取り組まれてたら譲ります！

**Comment by Hiroshiba** [comment]
問題になりそうなとこメモ

- トーク
	- 再度移ったらテキスト欄が増える
	- 再度移ったらDetail.vueなどが現れない
- ソング
	- onActivatedに書いている処理を移動

**Comment by sigprogramming** [comment]
こちら未着手でした、よろしくお願いします…！
（[L277-L305の処理](https://github.com/VOICEVOX/voicevox/blob/ff362c828816d3fd1f45f2c4af3d67fea32adfef/src/components/Sing/SequencerPitch.vue#L277-L305)は要らなくなるかなと思います）
