### ISSUE TITLE
型情報付きのESLintを有効化する

### ISSUE THREAD

**Issue by sevenc-nanashi** [VOICEVOX/voicevox#1895]
## 内容

[型情報が必要なルール](https://typescript-eslint.io/rules/?=typeInformation)を有効化したいです。

### Pros 良くなる点

- バグが減る。

### Cons 悪くなる点

- Lintが遅くなる。
- 現状警告が大量に出るのでそれを対処する必要がある。

### 実現方法

.tsファイルなら楽そうなんですけどVueだと厳しそうですね...：https://github.com/vuejs/eslint-config-typescript/issues/29

## VOICEVOXのバージョン

0.?.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

## その他

（なし）

**Comment by Hiroshiba** [comment]
導入したいですね！！

昔やろうとしたことがあるのですが、修正が大変すぎて諦めました。
今思えばとりあえずwarningで導入してみるとかが良かったかもと思ってます。
その時のPRこちらです。

- https://github.com/VOICEVOX/voicevox/pull/1380/

> .tsファイルなら楽そうなんですけどVueだと厳しそうですね

上のプルリクエストではワークアラウンドで迂回してるので参考になるかもです。
[`tsconfig.json`](https://github.com/VOICEVOX/voicevox/pull/1380/files#diff-b55cdbef4907b7045f32cc5360d48d262cca5f94062e353089f189f4460039e0)と[`.eslintrc.js`](https://github.com/VOICEVOX/voicevox/pull/1380/files#diff-e2954b558f2aa82baff0e30964490d12942e0e251c1aa56c3294de6ec67b7cf5)を変更しています。
僕が試した感じだと問題になってたのが`.js`にtypescript用のESLintが当たってしまうことだったので、`.ts`と`.vue`にだけ当たるようにしています。
ちゃんと知らずやってるので、もっとうまい設定があるのかもですが･･･。

**Comment by Hiroshiba** [comment]
もしかしたら @cm-ayf さんが詳しいかも･･･？

**Comment by cm-ayf** [comment]
あまり詳しくないです、私も.vueでESLintを使ったことはここ以外で無くて……
