### ISSUE TITLE
macOSにて、ヘルプの[使い方]ページの内容が一部古い情報になっている。

### ISSUE THREAD

**Issue by palm209** [VOICEVOX/voicevox#1898]
## 内容

macOSのVOICEVOXでヘルプの内容が少し古いものになっています。
macOS 13 Venturaからシステム設定に変更されているので説明も更新したほうがわかりやすいと思います。
![スクリーンショット 2024-03-04 3 52 46](https://github.com/VOICEVOX/voicevox/assets/162051377/b1bc1db1-bf71-481f-82be-ee5ac03e3fce)

### Pros 良くなる点

ヘルプの内容を新しくすることにより、操作方法がわかりやすくなる。

### Cons 悪くなる点

特になし

## VOICEVOXのバージョン

0.16.1

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [x] macOS
- [ ] Linux

macOS Sonoma 14.3.1

**Comment by Hiroshiba** [comment]
@palm209 issue作成ありがとうございます！！

気づきませんでした･･･。Venturaからということはかなり昔から違っていたんですね。
スクショと説明を置き換えるのが良さそうに思います。

@palm209 もしよかったら変更してみませんか？ 👀 
「使い方」はこちらです。 https://github.com/VOICEVOX/voicevox/blob/main/public/howtouse.md
スクショを置き換えつつ、説明も合わせる感じを想像しています。

難しければスクショとか説明文だけ頂ければこちらで良い感じに変更します！

**Comment by palm209** [comment]
返信有り難うございます。
一応howtouse.mdを編集し、フォークしましたが、githubに慣れていないので間違えた方法であったらすみません。
https://github.com/VOICEVOX/voicevox/commit/d96479b30dab9f85df2a232896f4f58d1674c25b

それとこのissueとは関係がない話になってしまいますが、howtouse.mdに書かれているMacのアンインストール方法だと完全に削除されないため、"~/Library/Application Support/voicevox"と"~/Library/Application Support/voicevox-engine"のディレクトリも削除するように書くべきか考えましたが、どうすればよいでしょうか。

**Comment by Hiroshiba** [comment]
@palm209 forkの仕方はバッチリだと思います！
あとはプルリクエストというものを作っていただければ･･･！（分からなかったら何でも聞いてください 🙏 ）

アンインストールに関してもなるほどです！
そのディレクトリはどっちかというと設定ファイルに近いですね！登録された辞書の情報が入ってるはずです。
設定ファイルはアンインストールで消えないものが大半なので、削除方法案内しなくても良さそうに思いました。

ただマルチエンジンを使っている場合は話が別で、マルチエンジンは結構重いので消した方が良いんですよね･･･。
もしその案内にもご興味あれば書いていただけると助かります 🙇 
ちなみに`config.json`があるディレクトリの`vvpp-engines`というディレクトリが対象のディレクトリです。
`/Users/（ユーザー名）/Library/Application Support/voicevox/`かな･･･？

**Comment by palm209** [comment]
プルリクエストというものを知らなかったためわかりませんでした。すみません🙇
フォークをプルリクエストしようと思い、よく分からずgit cloneコマンドを使ったのですが、githubページ上で「This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.」という警告が表示され、どこからプルリクエストを行えば良いのかわからない状態です。
お恥ずかしいですが、解決策を教えていただけると嬉しいです。
アンインストールに関しては、Windowsで確認したところアンインストール時に削除されるのはvvpp-enginesだけなのですね。
Macでも同ディレクトリの削除方法を説明した文章も時間があれば追加したいと思います。

**Comment by palm209** [comment]
自己解決できました。
プルリクエストを作成できました。
間違えて自分の所でプルリクエストを作ってしまいました。
https://github.com/VOICEVOX/voicevox/pull/1960

**Comment by Hiroshiba** [comment]
@palm209 プルリクエストありがとうございました！
