### ISSUE TITLE
音域補正・音量補正用のパラメータ名を整理したい

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1899]
## 内容

音高補正・音量補正用のドメイン用語をちょっと整理しておきたいです。
というのもそろそろアップデートリリースしようと思ってて、プロジェクトの内部情報としてこの辺の値が書き込まれるので、その前に決めておきたいなと。

日本語のドメイン用語がユーザーに露出するのはもうちょっと後なので、とりあえず英語（パラメーター名）の方を決められれば！

関連issue

- https://github.com/VOICEVOX/voicevox/issues/1838
- https://github.com/VOICEVOX/voicevox/issues/1870

**Comment by Hiroshiba** [comment]
@sigprogramming （cc @romot-co @y-chan ）
「voiceKeyShift」だと出力音声のキーシフトと誤解されるかもなので、歌い方のキーシフトだと分かりやすいように「guideKeyShift」に変更したいのですが、どうでしょうか 👀 
キーシフトだと大丈夫なのですが、音量スケールだと結構紛らわしいのでリリース前に変えておきたいなと。

---

今の実装でのパラメーター名と意味はこうなってます。

* notesKeyShift
	* ユーザー入力されたノートをどれぐらいキーシフトしてからクエリAPIに投げるか
* voiceKeyShift
	* エンジン出力された歌い方（ガイド）のピッチをどれぐらいキーシフトしてから歌声合成APIに投げるか

ここで[音量のこと](https://github.com/VOICEVOX/voicevox/issues/1870)も考えると「歌い方の音量をどれぐらいスケールするか」のパラメータが欲しくなります。
キーシフトの命名に合わせると「voiceVolumeScale」とかになるのですが、これが捉え方によっては歌い方の音量スケールではなく、出力された歌声の音量スケールだと勘違いしちゃいそうだなと。
ということでちょっと変えたいと思った次第です。

データの流れはこうなってます。

入力スコア　→　（パラメータ調整）　→　クエリAPI　→　歌い方　→　（パラメータ調整）　→　合成API　→　合成音声　→　（パラメータ調整）　→　出力音声

なんとなくですが、スコアのとこを「notes」（エディタにとってスコアはとても大きな概念）、歌い方を「guide」、出力音声を「output」辺りにすると分かりやすいかもと思いました。
この命名に乗っ取ると↓のようになります。

* notesKeyShift
	* ユーザー入力されたノートをどれぐらいキーシフトしてからクエリAPIに投げるか
* guideKeyShift
	* エンジン出力された歌い方（ガイド）のピッチをどれぐらいキーシフトしてから歌声合成APIに投げるか
* guideVolumeScale
	* エンジン出力された歌い方（ガイド）の音量をどれぐらいスケールしてから歌声合成APIに投げるか
* outputVolumeScale
	* （まだ存在しないので仮置き）合成した音声の音量をどれぐらい変えるか

**Comment by sigprogramming** [comment]
@Hiroshiba 
なるほどです！
`guideKeyShift`、良いと思います！（歌い方のピッチのシフトなので`guidePitchShift`も良いかもです）
スコアのところを「notes」、歌い方を「guide」、出力音声を「output」にするのも良さそうに思いました！

**Comment by Hiroshiba** [comment]
> guidePitchShift

なるほどたしかにです！
keyを含めていればkey単位でのシフトだということがわかるかもなので`guidePitchKeyShift`もありかもと思いましたが、まあ単位はコメントで書けば良いかなと思いました！

**Comment by Hiroshiba** [comment]
変更するプルリクエストを作りました！ https://github.com/VOICEVOX/voicevox/pull/1902

色々実装してて分かったのですが、音域補正用のパラメーターを1つ追加する必要があったのでそういう実装になってます。
ちょっとどうすべきか迷ってます。。 🙇

**Comment by Hiroshiba** [comment]
あと音域補正はノートと出力音声のピッチが合うように２回シフトさせるのですが、
じゃあ音量補正は歌い方と出力音声の音量が合うように２回音量増減するべきなのかがわからない･･･ 😇 
２回音量増減するなら、guideVolumeScaleで音量を上げた後、query.volumeScaleで音量を下げて合成する必要がありそう。
