### ISSUE TITLE
ソング: ズームの見た目をいい感じにする

### ISSUE THREAD

**Issue by romot-co** [VOICEVOX/voicevox#1907]
## 内容

- シーケンサのズームが現状input: rangeのため、いい感じの表示(おそらくQuasarのSlider)に置き換える
- 可能であればキーボードショートカットとメニューを用意する

### Pros 良くなる点

- 見た目が良くなる
- 操作系の向上

### Cons 悪くなる点

- プロトタイプ(実験中・工事中です！)というのを見た目あらわしてはいるため、正式版の直前がよさそう？

### 実現方法

- QuasarのSliderに置き換える

## VOICEVOXのバージョン

0.?.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by romot-co** [comment]
いったん対応済み

**Comment by sevenc-nanashi** [comment]
#2014 があるのでCloseしちゃってよさそう。
