### ISSUE TITLE
ustファイルを読み込めるようにする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1908]
## 内容

UTAU用のファイルフォーマットの.ustファイルの読み込み機能を切望されることがちらほらあります。
もしご興味ある方いらっしゃったら、ぜひ！

### Pros 良くなる点

とりあえず使ってみるというのがやりやすくなる

### 実現方法

ustファイルをよく知らないのですが、そこさえわかればあとはmusic xmlを読み込むコード部分を真似すれば実装できるのかなと思っています。
ファイル内全体検索で `IMPORT_MUSICXML_FILE` と検索すれば該当コードが見つかると思います。

あと歌プロジェクトファイルを相互変換できる utaformatix がOSSなので参考になるかも。
言語はKotlinで、Kotlin for Javascriptでjsから使えるようにされてるっぽい？
https://github.com/sdercolin/utaformatix3

## その他

もし挑戦してみたい方がいらっしゃったら気軽にコメントしてください！
わからないことがあればそちらも気軽に聞いて頂ければ。

**Comment by romot-co** [comment]
試行で実装してみたら一応動いたので
このあと残念な実装を修正してPR送れる形にします！
