### ISSUE TITLE
ソング：選択中のノート`selectedNoteIds`を存在するものだけでフィルタできるようにする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1917]
## 内容

簡単なリファクタリング用のissueです。Vuexのちょっとした知識が必要です。

選択中のノート`selectedNoteIds`は、undo/redoなどの操作で存在しないものが含まれることがあります。
これを、取得する時にフィルタリングするようにすれば意図しない変更に強くなれるはずです。

### Pros 良くなる点

いろんな処理を追加したときに選択中かどうかを意識しなくて良くなる

### Cons 悪くなる点

実装によっては見えない選択中のノートが大量に増えていく
（DESELECT_ALLそれなりに実行していれば良さそうではある）

### 実現方法

`selectedNoteIds`を`_`などをつけてプライベートっぽくし、Vuexのgetterでフィルターを実装してあげれば良さそう。
ちょうどトーク側の実装がそうなってるので真似しやすいかもです！
https://github.com/VOICEVOX/voicevox/blob/be6e005c6dab30a7f448ba175289c9178087197c/src/store/audio.ts#L249-L259

## その他

実際に起こったバグです。

- https://github.com/VOICEVOX/voicevox/pull/1916

**Comment by sevenc-nanashi** [comment]
これもマルチトラックで実装されたのでClose。
