### ISSUE TITLE
ソング：小節追加の挙動を良い感じにする

### ISSUE THREAD

**Issue by sevenc-nanashi** [VOICEVOX/voicevox#1919]
## 内容

今は最後の小節にノートを置いたら１小節追加される感じになっています。
が、それだと打ちこんでいる場所を画面中央に持ってくることができないので地味に不便です。
ので、最後から8小節くらいの所に置いたら8小節増やすとかそういう感じにした方が便利だと思います。

### Pros 良くなる点

- 打ちこんでいる場所を画面中央に持ってくることができる

### Cons 悪くなる点

（なし）

### 実現方法

ScoreSequencerあたりにそれっぽい処理があった記憶。

## VOICEVOXのバージョン

0.17.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

## その他

（なし）

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！

これ理想的な形は「小節は無限に広がっている」な気がしますね！
今は端が最初からあるので、そのワークアラウンドとして１小節追加されてると考えられるかもです。
となると８小節追加はワークアラウンドの改良になりそうかな。

このissueの今のステート的には、一旦ワークアラウンドでの小節追加を８小節にしても良いかどうか決を取る感じでしょうか。
問題点としては、音声書き出しすると足した部分だけ無音が必ず足されるデメリットもあると思います。
個人的には８小節は長いので、目的を達成するためであればまあ４小節くらいで良い気がしました。
４小節でもBPM120で８秒なのでかなり長いですが、まあ良いのかなという気持ちです。

@sigprogramming さんや @romot-co さんもご意見あれば 🙏

**Comment by sevenc-nanashi** [comment]
> 問題点としては、音声書き出しすると足した部分だけ無音が必ず足されるデメリットもあると思います。

それはならないと思います。
https://github.com/VOICEVOX/voicevox/blob/main/src/store/singing.ts#L1800
を読む限りは最後のノートの終了時間で止まってるっぽみがあるので。

> これ理想的な形は「小節は無限に広がっている」な気がしますね！

これは本当にそうですね、スクロール位置を監視して最後の方に行ったら自動的に出すようにするとか...？

**Comment by romot-co** [comment]
@Hiroshiba @sevenc-nanashi 
こちら考慮しました！無限スクロールよさそうです！
気になる点として、追加の場合はよいのですが減らすのがちょっとおかしなことになるかもです…！

ex: どんどんスクロールして1000小節ぐらいに増やした → スクロール範囲がクソ広くて迷子になる・縮められない

- どこかで全体長さを指定できる(候補としてはまずはプレイヤーで現在時間 | 総時間みたいなのを加え、総を編集可能など)
- シークバー or トラック長さバーをつけ、ドラッグなどで変更できるようにする
- 端っこにおいて8とか4小節単位で手動で増減できるようにする

形がいいかなと思っております！(案を持ち寄ってみて考えるのがよさそう)

**Comment by sevenc-nanashi** [comment]
Excelあたりの動作が参考になりそうだと思ってます。

**Comment by sigprogramming** [comment]
一旦8小節追加で良いと思います！

理想は無限スクロールだと思います、全体の長さの設定は、
- プロジェクト設定で設定できるようにする
- 長い場合に、ノート編集時に最適な長さに（自動で）設定

なども良いかもと思いました！

**Comment by Hiroshiba** [comment]
なるほどです、８小節追加で良さそうならその形で良いのかなと思います！

他のソフトがどうしてるのかとかも参考になるかもですね。
CeVIO CS7を見てみたら「最後までスクロールしたら２小節追加」でした！
