### ISSUE TITLE
ソング：MIDIファイルやMusicXMLやUSTファイルのインポートをundo可能にする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1946]
## 内容

midi等をimportするとコマンド履歴が壊れる事に気づきました。

`IMPORT_MIDI_FILE`や`IMPORT_MUSICXML_FILE`でファイル全体検索をしたら該当箇所がわかるはず。
このあたりの中身を書き換えればOKなはず。
https://github.com/VOICEVOX/voicevox/blob/86d2e8ebd7c8bfbac45981559a4d6f7f1cb27b4a/src/store/singing.ts#L1222-L1226

内部で`SET_SCORE`を呼んでいるので、それのCOMMANDバージョンを作って呼ぶようにすれば良さそう。

### Pros 良くなる点

importする前のファイルを保存していなかった場合などに戻れるようになる。

**Comment by sevenc-nanashi** [comment]
そういえばマルチトラックで実装されましたね。Close。
