### ISSUE TITLE
ウィンドウ位置・splitterの位置を記憶してほしい

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#195]
## 内容

毎回ウィンドウの位置やSplitterの位置（特にキャラクター枠）を調整するのが大変なので、記憶しておけるようにしたい。
ただ、モニターAでウィンドウを表示し、そのモニターを外してからソフトウェアを起動した場合、ウィンドウ位置が壊れている可能性があるので、なんらかの復帰処理が必要かも。

**Comment by Hiroshiba** [comment]
この辺り・・・？
https://github.com/electron/electron/issues/526
https://github.com/mawie81/electron-window-state

**Comment by Hiroshiba** [comment]
ご要望の声 https://twitter.com/U1kirby/status/1503304437858979849

ずっと使っているほど、つまりリリース後半年たった今需要が高まってきてるかもです。
ということで優先度をちょっと上げてみます！

**Comment by k-chop** [comment]
こちら確かにあると便利そうだなぁと思ったので、
こんな感じで実現出来るかなーと試していたらできてしまい・・・PR出してみました。
[ウィンドウ位置・splitterの位置を記憶できるようにする](https://github.com/VOICEVOX/voicevox/pull/782)

お手すきの際に見ていただければと思います 🙇
