### ISSUE TITLE
英単語を入力したときに英語っぽく読み上げられると嬉しい

### ISSUE THREAD

**Issue by ShimagayaSatoka** [VOICEVOX/voicevox#1955]
## 内容

英単語を入力したときに文字を読み上げるのではなく英語っぽいカタカナで読み上げるようにしたい
（例えば、"Speaker"を「スピーカー」、"talk"を「トーク」）

### Pros 良くなる点

チャットやコメントの読み上げBOTで英単語が入力されたときに聞き取りやすくなる
動画で英単語を読み上げて欲しい場合に入力と字幕の２つの理由で楽
入力・それらしく読んでくれるカタカナを探る手間が少し省ける
字幕・出力されるテキストファイルをそのまま使える

### Cons 悪くなる点

アルファベット列をそのまま読み上げて欲しい場合は困る（IAA、ISOなど）

### 実現方法

単語に分割する前後かモーラに分割するときにカタカナに変換する？

基本はフォニックス、例外は辞書登録

## その他

2単語以上の場合、間のスペースをポーズとして認識しないようにしたい
A.I.Voiceではすでに英単語を入力したときに英語っぽく読んでくれるので参考になにかできるかもしれない

**Comment by Hiroshiba** [comment]
すみません、こちらと被っているのでcloseさせていただきます！

- https://github.com/VOICEVOX/voicevox/issues/803

それっぽく読んでくれると嬉しそうな気持ちはあるのですが、openjtalkを辞書レベルからどうにかしないといけなく、その実装をやってくれる方を募集しています。
もしご興味あれば↑のissueや、あとVOICEVOX Discordの開発チャンネルにいらしてみてください！
定期的にこの話題が上がってきていて、どのあたりが難しいかなどが議論されていたりします。
