### ISSUE TITLE
ソング: USTファイルのセクション形式によってインポートできないことがある

### ISSUE THREAD

**Issue by romot-co** [VOICEVOX/voicevox#1956]
## 不具合の内容

一部のUSTファイルがインポートできない

### 現象・ログ

USTファイルのノートセクションは多くの場合[#0000]という形式だが、
出力ソフト(ex: SynthesizerVのUSTエクスポート)によっては[#0]のため
正常にインポートできない

### 再現手順

SynthesizerVでファイル作成でUSTエクスポート
またはUSTファイルのノートセクションを[#0000]から[#0]などへ変更

### 期待動作

[#0]など#以降に数値が続く場合はノートとして扱う

## VOICEVOXのバージョン

0.18.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！！
原因が分かって助かりました 🙇
