### ISSUE TITLE
ソング：ノートを画面外の音域（C10やB-2）に移動できてしまう

### ISSUE THREAD

**Issue by manju-summoner** [VOICEVOX/voicevox#1959]
## 不具合の内容
ノートを画面外の領域へドラッグし、スクロールバー上でマウス左ボタンを離すと画面外の音域（C10やB-2）にノートを配置できてしまう。
また、その後ノートを追加したり移動できなくなる。

### 現象・ログ
![voicevox song note issue](https://github.com/VOICEVOX/voicevox/assets/57256282/796f44da-a878-408d-bebd-29d903cfa298)

### 再現手順
1. ノートを追加する
2. 画面外の音域（B-2）までドラッグする
3. スクロールバーにカーソルが乗っている状態でマウス左ボタンを離す

### 期待動作
画面外にドラッグできない、または画面外にドラッグした場合は操作をキャンセルする

## VOICEVOXのバージョン
0.18.0

## OSの種類/ディストリ/バージョン
- [x] Windows 11 Pro 23H2 22631.3296
- [ ] macOS
- [ ] Linux

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！

これもしかして一回配置してしまうと復帰する方法がない･･･ですかね･･･？
かなり致命的な問題に感じました。報告感謝です 🙇
