### ISSUE TITLE
トーク：全選択ショートカットキーを作る

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1962]
## 内容

今実験的機能として複数選択機能があります。

- https://github.com/VOICEVOX/voicevox/issues/457

よくあるショートカットキーとしてctrl+Aで全選択ができるのですが、まだ実装されていません。
このショートカットキーを登録可能にしたいです。

### Pros 良くなる点

全選択ができるようになる

### 実現方法

ショートカットキーの設定と、操作の設定をすれば OK。

ショートカットキーの設定はこの辺り。
https://github.com/VOICEVOX/voicevox/blob/e45ad641ea80cd0614dc54dc127fcee4dd8f943a/src/type/preload.ts#L433
https://github.com/VOICEVOX/voicevox/blob/e45ad641ea80cd0614dc54dc127fcee4dd8f943a/src/type/preload.ts#L66

操作の登録はTalkEditor.vue内でregisterHotkeyWithCleanupを使えばできるはず。
参考になりそうなコードは例えばこことか
https://github.com/VOICEVOX/voicevox/blob/e45ad641ea80cd0614dc54dc127fcee4dd8f943a/src/components/Talk/TalkEditor.vue#L166-L174

## その他

わりと結構簡単だと思うので初心者の方とかぜひ！

**Comment by ShimagayaSatoka** [comment]
テキストボックスがフォーカスされているときにctrl+Aを押すと、テキストボックス内のテキストが全選択されるようになっていますが、そことの干渉はどうするべきでしょうか。
案としては
・ctrl+shift+Aでセル全選択とする
・テキストボックスがフォーカスされている場合はセル全選択はしない
があると思うですがどちらが良いでしょうか？

**Comment by Hiroshiba** [comment]
@ShimagayaSatoka コメントありがとうございます！
`・テキストボックスがフォーカスされている場合はセル全選択はしない`が良いかなと思いました！

というのも、よくあるUIの挙動に合わせるのが良いかなと思っていて、大体の場合は「フォーカスがあたっている部分の全選択」となるためです。
なのでテキスト欄にフォーカスがあたっている場合はテキスト欄内全選択、外にフォーカスがあたっている場合はセル全選択が良いかなと･･･！

**Comment by Hiroshiba** [comment]
@ShimagayaSatoka さん実装ありがとうございます！！

---

セルの全選択ですが、ソング側にあるノーと全選択と同じコマンド（ctrl+A）に変更できないかチャレンジしてみようと思います！
（今はctrl+shift+A）
考えたこととしてはこんな感じです

* 「すべて選択」は同じコマンドにしておきたい
	* なるべく特別な操作をなくしたいため
* ソング側は「すべて選択」という名前のアクションなので、統一してもそこまで違和感がない
* そのかわりセルのtext内でAudioCellをすべて選択ができなくなる
	* おそらく需要は少ないと思われる（ユースケースが思いつかなかった）
	* テキスト欄フォーカス解除（escキー）→ctrl+Aという代替手段
	* どちらかというと全選択キーの統一によるUX向上のが強いと判断

挑戦してみますが、実装が容易でなければ諦めるかもです。
