### ISSUE TITLE
english language support for the ui

### ISSUE THREAD

**Issue by Online122228** [VOICEVOX/voicevox#1974]
Please add english translation for the ui. It would make it easier to be ported to other languages as well.

**Comment by Hiroshiba** [comment]
メモです。
元のissue内容は `Please add english translation for the ui. It would make it easier to be ported to other languages as well.` という感じでした。

このあたりが近そうですね！

- https://github.com/VOICEVOX/voicevox/issues/1682

でもissueはぶっ壊れているので、何があったのかとよくわからなくならないためにdeleteさせていただこうと思います！
