### ISSUE TITLE
VOICEVOX 0.18.1 リリース ページ内のインストール媒体へのリンクが 0.18.0 のもになっている

### ISSUE THREAD

**Issue by kantas-spike** [VOICEVOX/voicevox#1983]
## 不具合の内容

[Release VOICEVOX 0.18.1 · VOICEVOX/voicevox](https://github.com/VOICEVOX/voicevox/releases/tag/0.18.1)のページの上部に記載されている、各OS別のインストール媒体へのリンクが 0.18.0のものになっている。

### 現象・ログ

例えば、macOSなら以下のURLになっている。

https://github.com/VOICEVOX/voicevox/releases/download/0.18.0/VOICEVOX.0.18.0.dmg

### 再現手順

[Release VOICEVOX 0.18.1 · VOICEVOX/voicevox](https://github.com/VOICEVOX/voicevox/releases/tag/0.18.1)を確認してください。

### 期待動作

macOSなら以下のURLになるべき。

https://github.com/VOICEVOX/voicevox/releases/download/0.18.0/VOICEVOX.0.18.1.dmg

## VOICEVOXのバージョン

0.18.1

## その他

まだリリースページが編集途中だったら、ごめんなさい。
(Assetsからは、0.18.1版を ダウンロードできるので、回避策はあります。)

**Comment by Hiroshiba** [comment]
@kantas-spike 本当ですね！！　ご指摘ありがとうございます！！

**Comment by Hiroshiba** [comment]
修正しました、助かりました 🙇
