### ISSUE TITLE
ソング：MusicXML・UST読み込み時の歌詞trimによるエラーメッセージ混乱の解消

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1987]
## 内容

VOICEVOXの使用中に「歌詞は日本語1文字までです。」というエラーメッセージが生成エラー全般で表示される[問題](https://github.com/VOICEVOX/voicevox/issues/1976)があります。
このメッセージは、実際には歌詞に関する問題ではない場合でも表示され、ユーザーの混乱を招いています。
原因の一つとして、歌詞にひらがな・カタカナの後ろに空白文字が含まれている場合があり、この空白文字がエンジンに渡され、クエリ生成に失敗している可能性が指摘されました。

### 実現方法

歌詞をMusicXML・USTから読み込む処理において、読み込み時に自動的にtrimを行う機能を追加します。
これにより、ひらがな・カタカナの前後に不要な空白文字が入ることがなくなります。

コードはこのあたりです。
https://github.com/VOICEVOX/voicevox/blob/3f196671b6d7225bf7e3f64c8527259b05cf339a/src/store/singing.ts#L1393

### Pros 良くなる点

- 歌詞をMusicXML・USTから読み込む際にtrimを行うことで、不要な空白文字が除去され、より正確なエラーメッセージが表示されるようになります。
- ユーザーの混乱が減少し、問題の診断と解決が容易になります。

### Cons 悪くなる点

- 特になし。ただし、実装には開発リソースが必要です。

## その他

この問題は、特定のエラーメッセージが適切でない状況で表示されることによるユーザーの混乱に関連しています。修正により、VOICEVOXのユーザーエクスペリエンスが向上することが期待されます。

（ちなみに、このような感じの内容を[ChatGPT君が生成してくれた](https://chat.openai.com/share/bc99d8b2-ad50-46d5-94bf-d8fb9139bd37)ので添削・整形してコピペしました。便利。）

**Comment by sigprogramming** [comment]
issue作成ありがとうございます！
こちら取り組みます！
