### ISSUE TITLE
起動直後の音声合成に失敗し「再生に失敗しました」と表示される

### ISSUE THREAD

**Issue by HyodaKazuaki** [VOICEVOX/voicevox#199]
## 不具合の内容

VOICEVOXを起動後、テキスト欄にテキストを入力して再生ボタンを押すとアクションとなどが表示されずに「再生に失敗しました。エンジンを再起動してください。」と表示される。
エンターキーを押していないのが原因？

### 現象・ログ

![Vv2URFn](https://user-images.githubusercontent.com/17569894/132481007-625ad220-2410-4e35-a7cb-411e59535bd4.gif)

### 再現手順

1. VOICEVOXを起動する
2. テキスト欄に任意のテキストを入力する
3. 再生ボタンを押す

### 期待動作

アクセントなどが下に表示されて音声が再生される。

## VOICEVOXのバージョン

0.5.0
0.4.1では遅れてアクセントが生成されるが音声の再生が行われない。

( `ヘルプ` → `アップデート情報` で確認できます)

## OSの種類/ディストリ/バージョン

*   Windows 10 Home 64bit (20H2 Build 19042.1165)

**Comment by Hiroshiba** [comment]
報告ありがとうございます。
仰るとおりエンターが押されていないのが原因ですが、バグのような挙動をするので修正したいところです。

昔からある現象なのですが、DOMと仕様が混ざっていてなかなか修正に手が加えられていません。
なぜこの挙動が起きているか解説してみます。

* 音声合成は「テキスト入力→AudioQueryをfetchで取得→音声取得」の流れ
* テキストが確定したら「AudioQueryをfetchで取得」が、再生ボタンを押したら「音声取得」が走る
* テキスト未確定の状態で再生ボタンを押すと、DOM的には「テキストの確定」と「再生ボタン押し」が順次実行される
* が、テキストが確定したときに走る「AudioQueryをfetchで取得」が非同期実行になっている
* 結果として「音声取得」と「AudioQueryをfetchで取得」の順序が入れ替わって音声合成に失敗する

「AudioQueryをfetchで取得」はほぼ一瞬なので待機しても問題ないのですが、それはそれで実装が大変（？）なので手がつけられていない感じだと思われます。

**Comment by Hiroshiba** [comment]
遭遇された方の例　https://twitter.com/n0o8BTzbdrUxMSi/status/1435788664039038978

**Comment by Hiroshiba** [comment]
エラーハンドリングを直した辺りで直ったかもなのでclose！
