### ISSUE TITLE
ソング：水平方向の拡大縮小と同時に垂直スクロールしてしまう

### ISSUE THREAD

**Issue by KoharuYuzuki** [VOICEVOX/voicevox#1995]
## 不具合の内容

ソングエディタで、Cmdキー + マウススクロールでのピアノロールの水平方向の拡大縮小を行うと、同時に垂直方向にスクロールしてしまいます。

### 現象・ログ

同上

### 再現手順

ピアノロール上でCmdキーを押しながら、マウスホイールを回転させる。

### 期待動作

マウススクロールによる拡大縮小中はスクロールしない。

## VOICEVOXのバージョン

0.18.1

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [x] macOS
- [ ] Linux

*   macOS Ventura 13.6.3

## その他

ScoreSequencer.vueのonWheelとonScrollの両方が呼び出されているからかもしれません。
もしこれが正しければ、wheelイベントをevent.preventDefaultすることで修正できそうです。
(ヒホ様からアドバイスを頂きました: https://twitter.com/hiho_karuta/status/1780348935170572537)

https://github.com/VOICEVOX/voicevox/blob/5cb3455554257040fb751d616e463deb187fd664/src/components/Sing/ScoreSequencer.vue#L1061-L1090

**Comment by Hiroshiba** [comment]
@KoharuYuzuki issue作成ありがとうございます！

手元のmac（物理マウスではなくトラックパッド）で試してみました、たしかにスクロールされちゃいますね！！
windowsだと発生しないので不思議ですね･･･。

wheelイベントとscrollイベントの仕様がよくわかりませんが、もしかしたらctrl+wheelはマウス操作だと拡大・縮小にためスクロールイベントが発生しないのかもです。
まあとりあえずpreventDefaultしてあげつつ、その理由をコメント書いておくのが良いのかなと感じました。

@KoharuYuzuki 検証ありがとうございます！！
もしよかったらプルリクエストの作成に挑戦してみませんか？

**Comment by KoharuYuzuki** [comment]
@Hiroshiba プルリクエストの作成、挑戦させてもらいます！

**Comment by Hiroshiba** [comment]
おお、ぜひぜひ！！
不明な点があればなんでもお聞きください！

**Comment by KoharuYuzuki** [comment]
これで良いのか不安ですが、プルリクエストを作成しました。

**Comment by Hiroshiba** [comment]
issue作成とPR取り組みありがとうございました、助かりました！！
