### ISSUE TITLE
デフォルトプリセットの再登録が機能してない

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1996]
## 不具合の内容

デフォルトプリセットにパラメータを再登録したあと、そのプリセットを適用しようとしても反映されてないっぽいことが分かりました。
https://x.com/lei10gohan/status/1780217148708970618

### 再現手順

1. プリセット機能をオンにする
2. デフォルトプリセットの状態でパラメータを変更する
3. デフォルトプリセットにパラメーターを再登録する
4. 一度プリセットを解除する
5. デフォルトプリセットを割り当てる
6. 登録したパラメーターじゃなく、初期パラメーターになってしまう

### 期待動作

登録したパラメーターが適用される

## VOICEVOXのバージョン

0.18.1

## その他

過去バージョンの0.15.2では問題なく動作していることがわかりました。
もしかしたらデグレってるかも･･･？

**Comment by Hiroshiba** [comment]
今のmainブランチで検証した感じ、普通のプリセットの再登録はできてそうでした。
デフォルトプリセットだけできてない･･･？

**Comment by Hiroshiba** [comment]
もしかしたらプリセットの再登録に問題があるのではなく、プリセットを適用する時にデフォルトの引っ張ってくるとこに問題があるとか…？

**Comment by k-chop** [comment]
[![Image from Gyazo](https://i.gyazo.com/c58ef6ff431c6233a90a695667c9e560.png)](https://gyazo.com/c58ef6ff431c6233a90a695667c9e560)
とりあえず同じ名前でidの違う別のpresetが作成され、
参照時は変更してない方が参照されているというところまで突き止めました。
プリセットの保存はされているが、変更したプリセットが参照されないので変更されていないように見えるっぽいです。
(↓ここでresult.itemsをnameでfilterして出力しました)
https://github.com/VOICEVOX/voicevox/blob/5cb3455554257040fb751d616e463deb187fd664/src/store/preset.ts#L162-L181

これがユーザの環境で既に起きているとなると、修正後にどっちを取ったら良いか決定するの無理ですね...
presetKeysは追加順な気がするので後にある方を優先、で大丈夫かな...

すみませんがこれ以後調査や修正の時間をコンスタントに確保できるかどうかはちょっと何とも言えないので、
分かったことは誰でも引き継げるよう都度メモっていきます🙏
今週の土日は時間取れそうなので引き続き見ていきますね

**Comment by madosuki** [comment]
https://github.com/VOICEVOX/voicevox/blob/5cb3455554257040fb751d616e463deb187fd664/src/store/preset.ts#L201C2-L234C5　でプリントデバッグしてみたところ生成対象にソング機能用スタイルが入っているようでした．

**Comment by Hiroshiba** [comment]
このバグのこと完全に忘れてました。。。
もしよかったらプルリクエストお待ちしています！！！
