### ISSUE TITLE
リファクタリング：キー割り当て画面で、ショートカット設定ダイアログを別コンポーネントにする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#2002]
## 内容

ショートカットキー設定画面が若干複雑化しつつあるので、解体してのリファクタリングを募集しています。

ショートカット設定ダイアログは、「キー割り当て」を押したあとショートカットキーを設定しようとすると出てくる↓のダイアログのことです。
![image](https://github.com/VOICEVOX/voicevox/assets/4987327/27915730-fc7f-4a8c-a2ec-c4ac0c68331d)

今はキー割当画面と同じコンポーネント内に記述されていて、かなりややこしくなっています。
これを解体して2つのコンポーネントにしてあげたいです。

### 実現方法

キー割り当て画面は `src/components/Dialog/HotkeySettingDialog.vue` にあります。

その中のショートカットキー設定ダイアログはこのあたりです。
https://github.com/VOICEVOX/voicevox/blob/c0fa953734a68328dc3924973a43224cfde0998c/src/components/Dialog/HotkeySettingDialog.vue#L129

分解はvueの知識こそ必要ですが、綺麗に分けられるとは思います。

**Comment by jdkfx** [comment]
試しにやってみたらうまくいきそうだったのでこちら取り組みます！

**Comment by Hiroshiba** [comment]
@jdkfx コメントありがとうございます、ぜひぜひ！！
