### ISSUE TITLE
新しいGithub Actions環境でmacOSのテストが一部落ちるのを解決したい

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#2007]
## 不具合の内容

2024/04/22辺りにmacOSのlatestが更新され、macos-14が利用されるようになりました。

以前
![image](https://github.com/VOICEVOX/voicevox/assets/4987327/da7f5d62-7a7b-4fd1-8fc9-37d770292f0d)

以降
![image](https://github.com/VOICEVOX/voicevox/assets/4987327/84a54aed-bf67-4bbe-980e-f3a95d7aab08)

その影響でテストが２つ落ちるようになったのでメモです。
応急処置としてskipすることにしていますが、可能なら解決したいです。

### 現象・ログ

このissueを作った時点でのmainブランチの結果
https://github.com/VOICEVOX/voicevox/actions/runs/8732000344/attempts/2

同じコミットIDでの以前の結果
https://github.com/VOICEVOX/voicevox/actions/runs/8732000344/attempts/1

## その他

原因調査に取り組まれた場合はぜひコメントをいただけると助かります。

skipは @weweweok さんが実装してくださいました、ありがとうございます！

- https://github.com/VOICEVOX/voicevox/pull/2006

**Comment by weweweok** [comment]
ローカル環境で何回かe2eテストを実行してみましたが、かなりの頻度で時間切れになりますね。。。(毎回同じ箇所で落ちる)
ファイル数が少ないと通ります。

![image](https://github.com/VOICEVOX/voicevox/assets/100256521/0a1a152e-8d30-4d0e-9487-87a6661eb643)

**Comment by Hiroshiba** [comment]
@weweweok なるほどです！！
`fullyParallel`をfalseにし、workersを1にするとどうでしょう？
このあたりです↓
https://github.com/VOICEVOX/voicevox/blob/177ecee5eaea5f78b46ce95370c99580f7cf97b3/playwright.config.ts#L67-L69

**Comment by weweweok** [comment]
全体として遅くなりますが、ほとんど動きました。
![image](https://github.com/VOICEVOX/voicevox/assets/100256521/82215da8-c198-454b-b58a-aa3dbe0437d4)

**Comment by sevenc-nanashi** [comment]
>  ファイル数が少ないと通ります。

もしかして：エンジンにキャラクターが多いせいで時間内にデータ準備が終わっていない？
VRTでやってるようなモックを全体に適用してもいいかも。全部差し替えなくてもGET /speakersを5人に絞るとかでも。

**Comment by Hiroshiba** [comment]
理由は全くわからないけれども最近落ちてない気がするので、クローズします･･･！

もしかしたらx64用ではなくarm64用のエンジンが使えるようになったからかも？
と思ったけどテストで使ってるはずのNemo用のエンジンにarm64版追加したのはだいぶ最近で、テストが落ちなくなったのはもっと前だと思うので･･･謎ですね･･･。
