### ISSUE TITLE
トーク・ソングどちらを前回開いていたか保存し、再開時にそちらが表示されている状態で起動する

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#2010]
## 内容

ソングが正式リリースされるのですが、表示状態が保存されないため、ソングにしか興味がない人は毎回トーク画面から開始してしまってちょっと煩わしいかもしれません。
開いていたエディターがどちらかを保存しておき、起動時にそれに従って初期表示されるものを選ぶと良いかなと思いました！

### 実現方法

開かれているエディターがどちらなのかを切り替えてるのはここ
https://github.com/VOICEVOX/voicevox/blob/8d2e0ebb4cd2799ace31637e097fc2b7e12f83f7/src/components/App.vue#L51-L52

開かれているエディターがどっちなのかを初期化しているのはここ
https://github.com/VOICEVOX/voicevox/blob/8d2e0ebb4cd2799ace31637e097fc2b7e12f83f7/src/components/App.vue#L96-L97

データを保存するのに便利な関数はこれ（関数名でファイル全体検索をすると使い方がちょっとわかるかも）
https://github.com/VOICEVOX/voicevox/blob/8d2e0ebb4cd2799ace31637e097fc2b7e12f83f7/src/store/setting.ts#L210

保存されたデータを読み出してUI側に反映するのはここ
https://github.com/VOICEVOX/voicevox/blob/8d2e0ebb4cd2799ace31637e097fc2b7e12f83f7/src/store/ui.ts#L258-L259

## その他

保存の処理が必要ですが、Vueなどに慣れていたらなんとなくコードが追えると思うので興味あれば是非！

**Comment by jdkfx** [comment]
@Hiroshiba こちらクローズされていないっぽいです

**Comment by Hiroshiba** [comment]
あっ忘れていました、ありがとうございます！

@X-20A さん、実装ありがとうございました！！
