### ISSUE TITLE
[song]ノーツが先頭に存在すると動作しない

### ISSUE THREAD

**Issue by tsym77yoshi** [VOICEVOX/voicevox#2031]
## 不具合の内容

ノーツが先頭に存在するとエラーになる

### 現象・ログ

ノーツが１小節目の最初に存在するとエラーになる（メッセージは歌詞が一文字までですとなっているが原因は違いそうです）
![image](https://github.com/VOICEVOX/voicevox/assets/67378554/1c638769-0e72-4b1f-9300-a92efbf73204)

### 再現手順

一番最初にノーツを置くとでます。後ろの場所に移動させたらエラーは消えました。

## VOICEVOXのバージョン

0.19.0

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

## その他

apiで最初に無音の秒数がないと実行できない仕様に関係するバグだと思います

**Comment by KoharuYuzuki** [comment]
Mac版でも同様のバグを確認しました。
一番最初にノーツを置くと、applyPitchEdit関数のstartFrameがマイナス値になり、f0[i - startFrame]にundefinedを格納してしまいます。
そうすると、フレームごとの音量を得る際にバリデーションエラーが発生します。
正しい修正方法か分かりませんが、マイナス値を0にしたところ動作するようになりました。
https://github.com/VOICEVOX/voicevox/blob/fb0adce77acdc01fb8b06954fb9f0f30688bd693/src/sing/domain.ts#L424-L457

**Comment by sigprogramming** [comment]
ご報告＆調査ありがとうございます！

こちら、以下を考慮せずpitchEditDataをf0に転写しようとして、f0にundefinedが入ってしまっているようです。
- 最初のノートの開始が1秒未満の場合、f0の開始がマイナスフレームになる
- pitchEditDataは0フレームから開始

修正方法ですが、startFrameの算出部分を
```ts
const f0StartFrame = Math.round(
  singingGuide.startTime * singingGuide.frameRate,
);
const startFrame = Math.max(0, f0StartFrame);
```
に変更するとf0にundefinedが入らなくなり、エラーも発生しなくなると思います。

修正PRを作成します…！
