### ISSUE TITLE
母音の連続発声時に起きる異音

### ISSUE THREAD

**Issue by GasOjisan** [VOICEVOX/voicevox#2038]
### 現象・ログ

特定の文字（おそらく母音のみだと思われる）を連続発声させようとすると
※例えば「うわああああああああああああああ」など
発声した音が前倒しに被って出力されているような**異音**を出力する。

異音が発声される文字数
- 「あ」は9文字以上
- 「い」は11文字以上
- 「う」は6文字以上
- 「え」は2文字以上※1文字でもちょっと怪しい
- 「お」は11文字以上

### 再現手順

1. 入力欄に「あああああああああ」などの母音を入力（上記文字数以上で）
2. 再生ボタンを押下
3. 発声した音が異音になる

### 期待動作

上記文字数でも以下文字数と同じように発声し、異音が出力されない。

## VOICEVOXのバージョン

0.19.1

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

**OS**：Windows 11 Home
**バージョン**：23H2
**使用状況**：棒読みちゃんと連携させて配信時に使用※VOICEVOX単体でも確認しましたが同じでした。

## その他
これは前バージョンでも起きていたことでした。報告遅れました。

**Comment by y-chan** [comment]
Issueを作っていただきありがとうございます！
この問題は、VOICEVOXの音声合成エンジン(音声合成の仕組み)の問題で、エディタの問題ではなく、その上解決が非常に難しい問題です。

いずれこの問題を解決できれば良いのですが、解決しそうな手法や時期が未定であるため、not plannedとしてIssueを閉じさせていただきます。
Issueを作っていただいたところ申し訳ありません :bow:

**Comment by Hiroshiba** [comment]
長音がうまく発声できないのは @y-chan さんの仰るとおりエンジンの課題で、解決の目処は立っておりません 🙇 
という制約がある中で、有志の方が長音を出すコツを解説してくださっている動画があります。参考になれば幸いです！
https://www.nicovideo.jp/watch/sm41172195
