### ISSUE TITLE
ソング: デフォルト編集モードでノート選択中にシーケンサをクリックした時の挙動

### ISSUE THREAD

**Issue by romot-co** [VOICEVOX/voicevox#2039]
## 内容

ノート選択をキャンセルしたい場合、他位置をクリックしたときにノートが作成されてしまう
ノート選択時には他位置クリックは選択キャンセルの方がよさそうな可能性を考慮する
(いらないものが追加されてしまい、うっとうしい可能性)

### Pros 良くなる点

- キャンセルをしたいのに誤って必要のないノートを作成してしまうことがなくなる

### Cons 悪くなる点

- 連続的な入力に一手間増える ノート作成(選択) → [選択キャンセル] → ノート作成

### 実現方法

考慮中

## VOICEVOXのバージョン

0.?.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by Hiroshiba** [comment]
今までで僕もエゴサしてて、ここにつまづいてるDAWユーザーの方を2回ほど見かけました。
考慮すべき事項だと僕も感じます。

シーケンサークリック時の挙動を制御する設定を用意して、玄人モードとしてシーケンサーfocusとするのが丸いのかなと思いました！

ドラッグしないと入力できないのはやっぱり初学者の人に難しい気がして、そこそこ優先度が高いかなぁと。
他にはダブルクリックでノート追加もありかもですが･･･個人的には設定を用意して振り分ける形のが良いのかなぁと思いました！

実装の複雑度が若干上がりますが、将来初心者・DAW玄人を最初に選べるようにするのがいいのかな～と考えてて、だったら設定を増やすのがいいのかなぁみたいな流れで考えました！

**Comment by romot-co** [comment]
@Hiroshiba 
こちらコメントできておらず失礼しました！

もしかすると議題が二種類あるかもですが

---

*1. いまの編集操作でノート選択→シーケンサクリックで選択キャンセルできるようにする*
→ シーケンサクリック時の挙動をオプションで切り替えるようにする？
→ このIssueで行う

※ 派生として選択中のノートの再クリックで選択キャンセルもありそう

---

*2. 編集優先・選択優先モードを切り替えられるようにする*
→ モード切り替え(ペン/選択)を追加する
→ 前の調査だと以下のC列の部分3つを入れ替えれば選択優先モードにできそう
https://docs.google.com/spreadsheets/d/1ltGxtvCoUhDiX06F8E1-Tf1TWlC9XM98ESBNOIHUYjw/edit?gid=0#gid=0

---

で、いったん1を解消できればと思います…！

**Comment by Hiroshiba** [comment]
編集優先モード・選択優先モードも面白いなと思いました！
変わる動作としてはクリックのデフォルト挙動とトラックのデフォルト挙動だけでしょうか 👀 
（それくらいだったら別にモードを用意するほどではないのかも･･･？）

**Comment by Hiroshiba** [comment]
issue側で`選択時は外側クリックで選択解除`に関してのコメントを書いたのでこちらからリンクさせていただきます･･･！

https://github.com/VOICEVOX/voicevox/pull/2279#issuecomment-2391882089

**Comment by romot-co** [comment]
案B:

案Aとの差異: 追加後に追加ノートを自動選択しない

Pros:
- クリックについて対称的な操作になるはず
- 連続的な追加が行いやすい

Cons:
- 追加したノートを即変更したい場合に手間が増える

---

- クリックで追加 / 追加可能時は追加可能カーソルで現在の状態を表現
- 選択時は外側クリックで選択解除
- Ctrl + ノートクリックで複数選択/選択解除

| 操作 | PC（マウス） | PC カーソル（モード） | タッチデバイス |
|------|--------------|------------------------|----------------|
| ノートの追加 | 1. クリックでデフォルト長のノートを追加 2. クリック＆ドラッグで長さを指定してノートを追加(ドロー) | 鉛筆アイコン？ | 1タップでデフォルト長のノートを追加 2. タップ＆ドラッグで長さを指定してノートを追加 |
| ノートの選択 | ノートクリックで選択 | 標準の矢印カーソル | ノートタップで選択 |
| ノートの選択解除 | 1. 空白部分をクリック 2. Escキーを押す | 標準の矢印カーソル | 空白部分をタップ |
| ノート範囲の選択 | 1. Shift + ドラッグで選択範囲を作成 2. Ctrl+クリック | 十字カーソル | 二本指でドラッグして選択範囲を作成 |
| ノートの移動 | 選択したノートをドラッグ | 十字矢印 | 選択したノートをドラッグ |
| ノートのサイズ変更 | ノートのエッジをドラッグ | 水平方向の両矢印アイコン | ノートのエッジをドラッグ(エッジをわかるように表示) |
| ノートの削除 | 選択後にDeleteキー 2. コンテキストメニューから削除 | 標準矢印 | 1. 選択後に削除アイコンをタップ 2. コンテキストメニュー(ロングタップ)から削除 |

実装は仮だが以下
https://github.com/romot-co/voicevox/tree/feature/2039_sequencer_click_mode_plan_b

**Comment by romot-co** [comment]
ノートを追加後に選択状態に**する**場合の試行実装:
https://github.com/romot-co/voicevox/tree/feature/2039_sequencer_click_mode_plan_a

ノートを追加後に選択状態に**しない**場合の試行実装:
https://github.com/romot-co/voicevox/tree/feature/2039_sequencer_click_mode_plan_b

**Comment by romot-co** [comment]
いったん各操作を使えるようにした(実装とカーソルは適当)
https://github.com/romot-co/voicevox/tree/feature/2039_sequencer_click_selectable_various_mode_mock

個人的にはBかCが好きなものの
やってみて思うのはこれは好み

<img width="1728" alt="スクリーンショット 2024-10-12 16 32 38" src="https://github.com/user-attachments/assets/cff00b3c-d421-4898-9223-948ae4bfb816">

<detail>
## 単一ツールのみで操作

### マルチツール（TOOLLESS_A, TOOLLESS_B, TOOLLESS_C, TOOLLESS_D）

A: https://github.com/VOICEVOX/voicevox/pull/2279#issuecomment-2404572615
B: https://github.com/VOICEVOX/voicevox/pull/2279#issuecomment-2399991802
C: plan_b
D: クリックドラッグで選択・ダブルクリックで追加

| 操作 | TOOLLESS_A | TOOLLESS_B | TOOLLESS_C | TOOLLESS_D |
|:-----------------|:-----------|:-----------|:-----------|:-----------|
| **グリッドをクリック** | ノート追加 | ノート追加 | ノート追加 | すべて選択解除 |
| **ノート追加後** | 該当ノートの選択 | 該当ノートを選択しない | 該当ノートを選択しない | 該当ノートを選択する |
| **ノート選択中にCtrl or Command + グリッドをクリック** | すべて選択解除 | すべて選択解除・ノートの追加はしない | すべて選択解除 | すべて選択解除 |
| **グリッドをダブルクリック** | なし | なし | なし | ノート追加 |
| **グリッドをドラッグ** | ノート追加 | ノート追加 | ノート追加 | 矩形選択 |
| **グリッドドラッグ後** | 該当ノートの選択 | 該当ノートを選択しない | 該当ノートを選択しない | 矩形選択中のノートの選択 |
| **Shift + グリッドをドラッグ** | 矩形選択 | 矩形選択 | 矩形選択 | なし |
| **ノートをクリック** | ノート単体選択 | ノート単体選択 | ノート単体選択 | ノート単体選択 |
| **ノート選択中にCtrl or Command + ノートをクリック** | ノート複数選択 | ノート複数選択 | ノート複数選択 | ノート複数選択 |
| **ノートをダブルクリック** | ノートの歌詞編集 | ノートの歌詞編集 | ノートの歌詞編集 | ノートの歌詞編集 |
| **ノートをドラッグ** | ノート移動 | ノート移動 | ノート移動 | ノート移動 |
| **ノートドラッグ後** | 該当ノートの選択 | 該当ノートを選択しない | 該当ノートを選択する | 該当ノートを選択する |
| **ノートの端をドラッグ** | ノートリサイズ | ノートリサイズ | ノートリサイズ | ノートリサイズ |
| **ノートリサイズ後** | 該当ノートの選択 | 該当ノートを選択しない | 該当ノートを選択する | 該当ノートを選択する |
| **Escキー** | すべて選択解除 | すべて選択解除 | すべて選択解除 | すべて選択解除 |
| **ノートを選択中にDeleteキー** | 該当ノートの削除 | 該当ノートの削除 | 該当ノートの削除 | 該当ノートの削除 |

## ツールパレットからツールを選択して操作

### マルチツール（TOOLSELECT_A）

#### マルチツール1（選択優先）

クリックドラッグで選択・ダブルクリックで追加

| 元の状態と操作 | マルチツール1（選択優先） |
|:-----------------|:--------------------------|
| **グリッドをクリック** | すべて選択解除 |
| **ノート選択中にグリッドをクリック** | すべて選択解除 |
| **グリッドをダブルクリック** | ノート追加 |
| **ノート追加後** | 該当ノートを選択する |
| **グリッドをドラッグ** | 矩形選択 |
| **グリッドドラッグ後** | 選択中のノートの選択 |
| **Shift + グリッドをドラッグ** | 矩形選択 |
| **ノートをクリック** | ノート単体選択 |
| **ノート選択中にCtrl or Command + ノートをクリック** | ノート複数選択 |
| **ノートをダブルクリック** | ノートの歌詞編集 |
| **ノートをドラッグ** | ノート移動 |
| **ノートドラッグ後** | 該当ノートを選択する |
| **ノートの端をドラッグ** | ノートリサイズ |
| **ノートリサイズ後** | 該当ノートを選択する |
| **Escキー** | すべて選択解除 |
| **ノートを選択中にDeleteキー** | 該当ノートの削除 |

#### マルチエディットツール2（編集優先）

クリックで追加

| 元の状態と操作 | マルチエディットツール2（編集優先） |
|:-----------------|:-------------------------------------|
| **グリッドをクリック** | ノート追加 |
| **ノート選択中にグリッドをクリック** | ノート追加 |
| **グリッドをダブルクリック** | なし |
| **ノート追加後** | 該当ノートを選択する |
| **グリッドをドラッグ** | ノート追加 |
| **グリッドドラッグ後** | 選択中のノートを選択する |
| **Shift + グリッドをドラッグ** | 矩形選択 |
| **ノートをクリック** | ノート単体選択 |
| **ノート選択中にCtrl or Command + ノートをクリック** | ノート複数選択 |
| **ノートをダブルクリック** | ノートの歌詞編集 |
| **ノートをドラッグ** | ノート移動 |
| **ノートドラッグ後** | 該当ノートを選択する |
| **ノートの端をドラッグ** | ノートリサイズ |
| **ノートリサイズ後** | 該当ノートを選択する |
| **Escキー** | すべて選択解除 |
| **ノートを選択中にDeleteキー** | 該当ノートの削除 |

### ツール別モード（TOOLSELECT_B）

#### 選択ツール

選択のみ

| 元の状態と操作 | 選択ツール |
|:-----------------|:-----------|
| **グリッドをクリック** | すべて選択解除 |
| **ノート選択中にグリッドをクリック** | すべて選択解除 |
| **グリッドをダブルクリック** | なし |
| **ノート追加後** | 該当ノートを選択する |
| **グリッドをドラッグ** | 矩形選択 |
| **グリッドドラッグ後** | 選択中のノートの選択 |
| **Shift + グリッドをドラッグ** | 矩形選択 |
| **ノートをクリック** | ノート単体選択 |
| **ノート選択中にCtrl or Command + ノートをクリック** | ノート複数選択 |
| **ノートをダブルクリック** | ノートの歌詞編集 |
| **ノートをドラッグ** | ノート移動 |
| **ノートドラッグ後** | 該当ノートを選択する |
| **ノートの端をドラッグ** | ノートリサイズ |
| **ノートリサイズ後** | 該当ノートを選択する |
| **Escキー** | すべて選択解除 |
| **ノートを選択中にDeleteキー** | 該当ノートの削除 |

#### ペンツール

追加と移動・リサイズ・削除

| 元の状態と操作 | ペンツール |
|:-----------------|:-----------|
| **グリッドをクリック** | ノート追加 |
| **ノート選択中にグリッドをクリック** | ノート追加 |
| **グリッドをダブルクリック** | なし |
| **ノート追加後** | 該当ノートを選択しない |
| **グリッドをドラッグ** | ノート追加 |
| **グリッドドラッグ後** | 選択中のノートを選択する |
| **Shift + グリッドをドラッグ** | なし |
| **ノートをクリック** | ノート単体選択 |
| **ノート選択中にCtrl or Command + ノートをクリック** | ノート複数選択 |
| **ノートをダブルクリック** | ノートの歌詞編集 |
| **ノートをドラッグ** | ノート移動 |
| **ノートドラッグ後** | 該当ノートを選択する |
| **ノートの端をドラッグ** | ノートリサイズ |
| **ノートリサイズ後** | 該当ノートを選択しない |
| **Escキー** | すべて選択解除 |
| **ノートを選択中にDeleteキー** | 該当ノートの削除 |

#### 消しゴムツール

削除のみ

| 元の状態と操作 | 消しゴムツール |
|:-----------------|:---------------|
| **グリッドをクリック** | なし |
| **ノート選択中にグリッドをクリック** | すべて選択解除 |
| **グリッドをダブルクリック** | なし |
| **ノート追加後** | なし |
| **グリッドをドラッグ** | なし |
| **グリッドドラッグ後** | なし |
| **Shift + グリッドをドラッグ** | なし |
| **ノートをクリック** | 該当ノートを削除 |
| **ノート選択中にCtrl or Command + ノートをクリック** | なし |
| **ノートをダブルクリック** | なし |
| **ノートをドラッグ** | なし |
| **ノートドラッグ後** | なし |
| **ノートの端をドラッグ** | なし |
| **ノートリサイズ後** | なし |
| **Escキー** | すべて選択解除 |
| **ノートを選択中にDeleteキー** | 該当ノートの削除 |
</detail>

**Comment by sigprogramming** [comment]
@romot-co 

実装ありがとうございます！！
とても比較しやすかったです…！

試してみた感想：

- ツールなし
  - A
    - ツール選択なしの中ではこの形が一番使いやすく感じました
    - 右クリックメニューの選択解除がグレーアウトしてしまうので、グリッドを右クリック時は選択解除しない方が良いかも
      - StudioOneはグリッドを右クリック時に選択解除しないようになっていました
  - B, C
    - 「選択中にグリッドをクリックで選択解除」がなくなっていますね！
      選択の有無で挙動が切り替わらなくなったので、使いやすくなったように感じましたが、「追加等を行った後に選択しない」のメリットがない…かも…？
      （選択されていた方が、インスペクターで値を設定するなどが行いやすくなると思います）
  - D
    - ノート追加がしにくいので、一から打ち込むときに使いにくいかも
    - ダブルクリックでノート追加に気づかない人もいるかも（特に初心者）
- ツールあり
  - A
    - 6つの中ではこれが一番使いやすく感じました（使い慣れた形なので）
    - GUIのみで（キーボードを使わずに）操作できて、行えることがアイコンで表示されているので（ツールパレット）、「初めてピアノロールを触る」という人でも分かりやすく使いやすいっかなと思います
  - B
    - 選択のみ、編集のみ、削除のみと分ける形は分かりやすいですが、編集効率は下がるので、DAWに慣れている人は少し面倒に感じるかも
    - 削除はノート右クリックで可能なので、消しゴムツールはなくても良いかも…？
      - 「分かりやすさを上げるために消しゴムツールを追加するかどうか」かなと

**Comment by romot-co** [comment]
@sigprogramming 
試行ありがとうございます！
急いでみたら間違いもあったので修正いたします…！(あと比較表がくっそわかりづらいので書き直します…

周り回って以下のB列とC列に戻ってきそう…？
https://docs.google.com/spreadsheets/d/1ltGxtvCoUhDiX06F8E1-Tf1TWlC9XM98ESBNOIHUYjw/edit?gid=0#gid=0

---

> A. ツール選択なしの中ではこの形が一番使いやすく感じました
> 右クリックメニューの選択解除がグレーアウトしてしまうので、グリッドを右クリック時は選択解除しない方が良いかも

→ こちらを採用するのであれば
おっしゃる形にできればと思っています！(右クリックは全般に試行実装の範囲外にしています

> B, C
>「選択中にグリッドをクリックで選択解除」がなくなっていますね！

こちらごめんなさい、おそらく実装ミスでした…！
「選択中にクリックで選択解除」がいちおうの想定動作なので修正します

> 選択の有無で挙動が切り替わらなくなったので、使いやすくなったように感じましたが、「追加等を行った後に選択しない」のメリットがない…かも…？
>（選択されていた方が、インスペクターで値を設定するなどが行いやすくなると思います）

「追加などの後に選択しない」の

メリット:

- 即次の動作に移れる
- マウスでの選択解除と両立できる

デメリット:

- 追加などの後に即変更しづらい(削除やインスペクタでの詳細設定など、Bにおいては複数コピペ要素の移動)

かなあと
メリットデメリットがありなにを取るかかなのですが
インスペクタについては入力後即詳細設定はあまりしなさそう(歌詞も入力されていない)…という想定ではいます

> D
> ノート追加がしにくいので、一から打ち込むときに使いにくいかも

SynthV/StudioOne/AbletonLiveなどでデフォルトツールの動作なのですが
こちらはペンツール…編集優先ツールとの併用が必要なのかもです…！

> ツールあり
> A
> 6つの中ではこれが一番使いやすく感じました（使い慣れた形というのもある）
> GUIのみで（キーボードを使わずに）操作できて、行えることがアイコンで表示されているので（ツールパレット）、「初めてピアノロールを触る」という人でも分かりやすく使いやすいかなと思います

なんだかんだこれが一番いいのかもですね
両方とも複数機能を持つマルチモードなツール(選択優先か・編集優先か)ですが
違和感ないならこれが第一選択かも

いずれツールパレットは必要になるようではあるため / タッチデバイスなら今のところツール選択なしの編集優先でカバーできそうなため

> B
> 選択のみ、編集のみ、削除のみと分ける形は分かりやすいですが、編集効率は下がるので、DAWに慣れている人は少し面倒に感じるかも

VoiSonaなどはこちらのような単一モード切り替え式な方向なものの
個人的には切り替え面倒なので無しかなと思っております

**Comment by Hiroshiba** [comment]
@romot-co だいたい同感です！！
ピッチ編集の消しゴムツール、マウスだけだと消せないから確かにあった方がよさそう！

ちょっとショートカットキーはもしかしたら相談させていただくかもです！！
というのもソングソフトは、ツールの切り替えよりも編集ターゲット？の切り替え（ノートとかピッチとか）のほうが重要かもと思ったので･･･！
どっちを単体数字キー操作にしてどっちを修飾キーありにすべきか、もしかしたら考えた方がいいのかも。

まあでもとりあえず実装しちゃうのありだと思います！！
リリースするまでは変えられるので･･･！

**Comment by romot-co** [comment]
進捗:

https://github.com/user-attachments/assets/12c4d571-b9fc-4b10-92e2-556747b20483

---

### 追加

- ノート編集で編集優先と選択優先でツール選べるようにする
- ピッチ側も消しゴム追加

### 残作業
- ツールパレットの位置などは仮
→ 少なくともノート/ピッチモード切り替えとあわせて考えたほうが良さそう / もしかしたらツールバー自体もそろそろ機能増えてきたので構成変更
- ノート側のショートカットキー
- リファクタリング
- カーソルとか
- テスト

**Comment by romot-co** [comment]
進捗:

いったん修正

---

## 設計について考える

- editTargetと各ツール選択`selectedTool(仮)`はおそらく疎にはできない
→  editTargetと統合前提
→ `useEditState`などとする

---

- 各ツール選択時の挙動を振る舞いとして定義している

動作表をそのまま定義している

```
EDIT_FIRST: {
   ...
   // ダブルクリックで追加する
   shouldAddOnDoubleClick: true,
}
```

→ イベントごとの動作を記述した方がまだわかりやすそう

---

- ノート編集の振る舞いであり、ピッチ編集の振る舞いは定義していない
→ まずはノートのみで定義(コメントに残す)

---

- カーソル状態やプレビュー状態との兼ね合い
→ 影響しあうが今回スコープ外とする

**Comment by romot-co** [comment]
進捗:

WIPに対して

### useEditStateについて

WIPだとcomposableの意味があまりない
(とりあえずコピペなため...)

おそらくは行われるアクションの判定をカプセル化したほうが少なくともScoreSequencerの複雑さは減らせる？
イメージとしては以下のような形

```
// 関連storeや関連するコンテキスト(キーの状態やプレビュー状態など)を渡す
const { ... } from useEditMode(store, {
   ctrlKey, ShiftKey, nowPreviewing...
})

// マウス押す
const onMouseDown = (event: MouseEvent) => {
  // アクションを判定し取得する
  const action = getActionFromEditMode(event, isSelfEventTarget(event));
  
  switch (action) {
    // 矩形選択開始
    case "START_RECT_SELECT":
      isRectSelecting.value = true;
      rectSelectStartX.value = result.cursorX;
      rectSelectStartY.value = result.cursorY;
      break;
     
    // ノート追加
    case "ADD_NOTE":
      ...
      break;
      
    // ノート全選択解除
    case "DESELECT_ALL":
      break;     
    default:
      break;
  }
};
```

useEditState内に振る舞いを直接記述のほうがまだマシ…？

### 依存注入について

- まずはstoreと関連コンテキストをすべて渡す

### カーソル状態について

- 編集モード切り替えに依存しているので統合してしまった方がいいかもしれない

### プレビュー状態について

- コンテキストとして渡す

### ツールパレットについて

- コンポーネントとして分離
