### ISSUE TITLE
ソングのデフォルトスタイルについて考える

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#2063]
## 内容

トークには、キャラクター選択をしたときにどのスタイルがデフォルトになるかを設定できる機能（デフォルトスタイル機能）があります。
これをソング側にも導入すべきかどうか議論したいというissueです。

導入すべき・見送るべき・あるいはその間のどの優先度かが決まればこのissueはcloseだと思います。

## その他

コメントあれば誰でもなんでも歓迎です！

**Comment by sevenc-nanashi** [comment]
トークと違って探す機会は本当に少ないので別に無くても良いと思います。自分の中ではWant以下。

**Comment by Hiroshiba** [comment]
個人的には、「どちらかというと無い方が良いかも。その代わりサンプルを聞ける機能がほしい。」くらいの気持ちです。

デフォルトスタイル機能には２つ目的があります。

目的１つ目がデフォルトスタイルの提供で、これはソングでキャラクター切り替えをほとんど行わないことを考えると不要だと思います。
それどころか機能をメンテナンスしないといけないことと、機能を追加しないといけない（ユーザーの関心が分散する）ことを考えると、どちらかといえばマイナスかなとすら思います。

目的２つ目は「サンプルを聞ける画面を作る」「いろんなサンプルを聞いてもらう」ことです。
他のキャラクター・スタイルの音声を聞いて、別の声にも追加で興味を持ってもらいたいという思いから来ています。
このあたりの議論です。 #1085 #1539 #1535
ただこれはそもそもデフォルトスタイルを選ぼうとする機会が０なので、サンプルを聞く画面にたどり着かない気がしてます。

まとめると「需要の割にメンテコストかかるから無い方が良い」「サンプル聞ける場所はほしい」です。

**Comment by Hiroshiba** [comment]
@y-chan おつです！　すみません、ちょっとエディタの仕様について相談できると！

ソングのデフォルトスタイルですが、「なくてよいのでは」という方針で整いつつあります。
もしよかったらなにかコメントいただけると！！ 🙏

**Comment by y-chan** [comment]
個人的にも色々考えてみましたが、メンテコストなどいろいろ加味した上で、見送っていいのではないかなと思います。

> サンプルを聞ける機能がほしい

これは私も思ったのですが、現状はサイトである程度聞けるので、緊急性は無いのかなと思いました。
実装するなら、キャラクター並び替え・試聴ダイアログ内でしょうかね...?

**Comment by Hiroshiba** [comment]
@sevenc-nanashi @y-chan ありがとうございます！！

とりあえずソングデフォルトスタイルは見送りの方針にしたいと思います！
確かメモコメントが残っていたと思うのでそちらを削除して完了としたいと思います。

@y-chan 
確かに視聴機能はホームページ側にあるので緊急性は低いかもですね･･･！
たしかに並び替えダイアログはソング側でも使える機能だとは思うので、そこにソング欄をつけるとかが妥当そう。

うーん！　試聴ダイアログでソングに切り替えられるタブとかがあれば良いのかも。
あるいはソング側でこのダイアログを開いたらソングになればいいのかも
ちょっとその方針でissue作ってみます！

**Comment by Hiroshiba** [comment]
プルリクを出してissueも切り出してみました！

- https://github.com/VOICEVOX/voicevox/pull/2077
- https://github.com/VOICEVOX/voicevox/issues/2078

ということでクローズしたいと思います！

ご意見ありがとうございました！
