### ISSUE TITLE
トーク：ファイルの書き出し時の名前設定にプロジェクトファイル名を含められるようにする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#2075]
## 内容

トークの音声書き出しファイル名は設定から変えることができます。
そこにプロジェクトファイル名を指定可能にできると便利そうです。

要望の声
https://twitter.com/swind_prv/status/1789933214099816714
https://github.com/VOICEVOX/voicevox/issues/969

### Pros 良くなる点

ファイル管理がやりやすくなる

### 実現方法

ファイル名の決定は`buildAudioFileNameFromRawData`で行われています。
https://github.com/VOICEVOX/voicevox/blob/1087cad9fd2db4f9246e783bfff5dc3811e36e9f/src/store/utility.ts#L326-L327

ここの引数でプロジェクトファイル名を指定可能にし、あとはこの関数が使われているところのエラーを解消していけばよいはず。
プロジェクトファイル名は`getters.PROJECT_NAME`で得られるはず！

## その他

結構簡単だと思うので初心者歓迎ラベルを付けます。
不明な点などあればコメントいただければ！

**Comment by jdkfx** [comment]
こちらのタスクについて、ちょっと触ってみたらできてしまったのでPR出します！

**Comment by Hiroshiba** [comment]
おお、ぜひぜひ！！
