### ISSUE TITLE
設定ファイルの保存をアトミック操作にする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#2082]
## 内容

設定ファイルの保存はConfigManagerで行われていて、それはファイルに直接書き込む形で実装されています。
https://github.com/VOICEVOX/voicevox/blob/4c9550b089aeda07153a2ba203c54d27b988e9ff/src/backend/electron/electronConfig.ts#L23-L28

この操作は割と危なくて、何かしらの原因で途中で書き込みが中断してしまうことがあると、中途半端な値が保存されて設定ファイルが壊れます。
実際にそれが原因かもしれない不具合報告も見つかりました。

- https://github.com/VOICEVOX/voicevox/issues/2081

設定ファイルに関してはプリセットが保存されていたりとクリエイターにとって割と重要なポジションを占めるので、優先度ラベルを高めに設定しています。

### Pros 良くなる点

バグが起こりにくくなる

### 実現方法

一度保存する先のパス+`.tmp`みたいなファイルに書き出した後、`moveFile`でファイルを上書きすれば OK。
moveFileの使い方はこんな感じ
https://github.com/VOICEVOX/voicevox/blob/4c9550b089aeda07153a2ba203c54d27b988e9ff/src/backend/electron/manager/vvppManager.ts#L283

## その他

直接ファイルを書き込んでいるところはいくつかあるので、一度同じディレクトリの`.tmp`に書き込んだ後moveFileする便利関数を作って使いますと便利そう。

処理としてはそんなに難しくないと思うのでぜひ気軽にコミットにチャレンジしてみてください！

**Comment by RikitoNoto** [comment]
初めまして、こちらのissueぜひ対応させていただきたいです！
> 一度同じディレクトリの.tmpに書き込んだ後moveFileする便利関数を作って使いますと便利そう。

これは作るとしたら、```src/helpers/```にファイル操作用の新規ソース作成するような形でよろしいでしょうか？

**Comment by Hiroshiba** [comment]
PRありがとうございます！

> これは作るとしたら、src/helpers/にファイル操作用の新規ソース作成するような形でよろしいでしょうか？

そちらでも問題ないですが、今回の場合は使われる場所が（今のところ）`src/backend/electron/`だけなので、ここに作っちゃうのも良いかもです･･･！

**Comment by Hiroshiba** [comment]
@RikitoNoto PRありがとうございます！！

> これは作るとしたら、src/helpers/にファイル操作用の新規ソース作成するような形でよろしいでしょうか？

そちらでも問題ないですが、今回の場合は使われる場所が（今のところ）`src/backend/electron/`だけなので、ここに作っちゃうのも良いかもです･･･！
