### ISSUE TITLE
依存しているパッケージを整理する

### ISSUE THREAD

**Issue by yamachu** [VOICEVOX/voicevox#2085]
## 内容

初回リリースから何年か経過し、様々な機能の追加やリファクタリング、ビルドツールキットの変更など多くの変化がおきました。
その過程で開発を容易にしたり、特定の機能を果たすために多くのパッケージを慎重ながらも追加してきました。

しかしリファクタリングやツールキットの変更に伴って不要になったパッケージの掃除などは積極的には行われてこなかったように感じられます。

プロダクトのリファクタリングの一環として、依存パッケージの整理も行ってはどうだろうかというのを提案します。

継続的に、また自動的に行えることが望ましいですが、それは一度スコープから外しています。

### Pros 良くなる点

- 依存パッケージの総量が減ることで、初回のセットアップが若干ではあるが早くなる
- `npm audit` などで脆弱性が見つかった時に、そのパッケージはどこに影響を及ぼしていたっけ？みたいな調査の対象を減らすことが出来る
- 定期的なパッケージのアップデートなどを実施した場合に、アップデートする必要のない（使っていないため）ものを見て判断するコストを抑えられる

### 実現方法

一例を示します。

例えば [depcheck](https://www.npmjs.com/package/depcheck) などを使うことで調査可能です。
Issue作成時の最新のコミットの 
 https://github.com/VOICEVOX/voicevox/commit/4c9550b089aeda07153a2ba203c54d27b988e9ff で行うと以下のような結果を得ることが出来ます。

```
# ~/Projects/github.com/yamachu/voicevox $ [main]
 npx depcheck
Unused dependencies
* buffer
* source-map-support
Unused devDependencies
* @openapitools/openapi-generator-cli
* @types/clone-deep
* @types/diff
* @types/unzipper
* @types/yargs
* @typescript-eslint/eslint-plugin
* @typescript-eslint/parser
* @typescript-eslint/types
* @typescript-eslint/utils
* eslint-config-prettier
* eslint-plugin-prettier
* markdownlint
* optionator
* sass-loader
* tmp
* ts-node
* tsconfig-paths
Missing dependencies
* vue-eslint-parser: ./.eslintrc.js
* /Users/yamachu/Projects/github.com/yamachu/voicevox/node_modules/vue-eslint-parser/index.js: ./.eslintrc.js
```

実際は `@typescript-eslint/*` 周りのパッケージは `eslint` から使用しているため不要なパッケージではありません。
また `buffer` も `index.html` から呼ばれているなどがあります。
あくまでも `.js` や `.ts` などから `import * from '?'` や `require('?')` などで依存されていない、みたいなものをチェックしているに過ぎません。

そのため、ここに出てきたパッケージを全て削除して良い、という風にはなりませんが、削除のヒントにはなります。

これらの情報や、当該パッケージが導入された PullRequests などのコードやその背景などを読み取ることで、判断することが出来るでしょう。
当該パッケージが不要であるのであればどのようにして確かめることが出来るかなどを一緒に示すことで安心して削除できるでしょう。

#### 簡単な例、@types/*

例えば `@types/diff` は `diff` パッケージの型定義を提供するために導入されたものですが、`diff` の代わりに `fast-array-diff` が導入されたことにより、`@types/diff` が不要になりました。

これは型定義の対象となるパッケージが存在するかだったり、削除した場合に `npm run typecheck` を実行することで型チェックで調べることが出来るでしょう。
https://github.com/VOICEVOX/voicevox/blob/4c9550b089aeda07153a2ba203c54d27b988e9ff/package.json#L25

#### 他の依存パッケージの場合

例えば `tmp` パッケージは Temporary なファイルやディレクトリを作成できるパッケージです。
VOICEVOXエディタではなく、ビルドやパッケージングなどのスクリプトで一時的に利用されていたパッケージですが、現在はそのパッケージに依存しない形で目的を果たしています。

これはエディタ外の振る舞いのため、何の目的だったか、またそれを検証するのが難しくなってしまう例ではあります。

また `sass-loader` のような `*-loader` というパッケージは、以前VOICEVOXがWebpack(Vue-CLI)を使用してビルドされていたという経緯を知らないと、すぐにこれを削除して良い、という判断に至るのは難しいです。
というように、`package.json` の blame を見て探したり、ツールキット特有の知識も求められるケースもあります。

と、作業にはいくつかの知識や、過去の経緯を調べるなどが必要ではありますが、このような方法で実現できるかと思います。

## VOICEVOXのバージョン

0.?.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

## その他

プログラミング初心者、という状態では難しいとは思います。
voicevoxリポジトリに対して初心者だが、過去から現在までのコードの流れを横断的に見ることが出来るので、そういう人に適したIssueだと思います。

### こぼれ話

`sass-loader` を消したのであれば `sass` もいらないのでは？と感じてしまいますが、利用しているUI Library の `Quasar` の `.sass` ファイルを import しています。
では `sass` は必要なのかと言うと、`Vite` が `sass` に依存しているため、直接依存に書く必要はないので消す判断を取ってもよいかと思います（package-lock.jsonがあり、固定は出来ているため）。
この `Vite` が依存しているというのは、例えば `npm why sass`  で調べることが出来る。

この peer dependencies のバージョンを固定したいというのであれば `npm overrides` を利用するでも良いのでは…？とも思うが、これは別トピックだろう

https://docs.npmjs.com/cli/v10/configuring-npm/package-json#overrides

**Comment by Hiroshiba** [comment]
非常に詳しいissue作成ありがとうございます！！
TypeScript等にあまり詳しくなくても実践できるタスクだと思うので、初心者歓迎タスクをつけさせていただきました！！
