### ISSUE TITLE
「初期ファイルの作成エラー　インストールを中止するには中止を、～」などと表示されてアップデートできない

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#2086]
## 不具合の内容

アップデートすることができないという連絡がたまに来るのでissueにしました。

### 現象・ログ

アンインストールに失敗する。
PCを再起動してもダメ。

### 再現手順

？

### 期待動作

アンインストールできる。
再インストール・アップデートができる。

## VOICEVOXのバージョン

0.19.1

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

## その他

理由がわかってなかったのですが、もしかしたら管理者権限と関係してるかもしれません。
報告にあった一例のエラーメッセージは以下の通りです。

---

VOICEVOXが終了できません。
手動で閉じて、「再試行」をクリックしてください。

（こっちはVOICEVOX起動中にアンインストールやアップデートしようとした時にも出る）

---

初期ファイル作成エラー："E:\Program Files\VOICEVOX\Uninstlal VOICEVOX.exe"
インストールを中止するには中止を、
再びこのファイルの作成を試みるには再試行を、また
ファイルをスキップして続けるには無視を押してください

（今見たけどEドライブなのがもしかしたら原因と関係しているかも･･･？）

**Comment by Hiroshiba** [comment]
詳しくお聞きして、可能性としては以下がありえそうなことが分かりました！
https://x.com/hiho_karuta/status/1791452463264158014

1. C ドライブ以外にインストールする
2. 管理者権限でインストール（すべてのユーザーにインストール）
3. 管理者権限でインストールした後、現在のユーザーとしてアップデートしようとする
4. 1+3の合わせ技

同じインストーラーを使って何度もインストールしようとしたらおそらく同じエラーを再現できる気がします。
再現できた方がいらっしゃったらぜひご報告いただけると･･･！

**Comment by terapotan** [comment]
こちらの件、私の環境でも再現できないかなーと思い軽く試してみたのですが、再現しませんでした……
雑多ではありますが、詳細な内容を以下に記しておきます。

- OS：Windows11
- VOICEVOXインストール先ドライブ：Eドライブ（追加SSDドライブ）
- VOICEVOX0.19.0をすべてのユーザーにインストールした後、VOICEVOX0.19.1を現在のユーザーのみに対してインストール（つまりアップデート）する。この際、VOICEVOX0.19.1のインストール先は、VOICEVOX0.19.0のインストール先と同じにした。
- 上記手順を5回ほど実施したが、いずれも正常にアップデートが完了し、VOICEVOX0.19.1のVOICEVOXが起動した。詳細は不明だが、インストーラーの挙動的に選択したフォルダを一度クリアしてからインストールする仕組みになっているらしく、選択したフォルダにVOICEVOX関連ファイルがあったとしても問題なくインストールは進むようだった。
- VOICEVOX0.19.0とVOICEVOX0.19.1のインストール先を別々にした場合も試したが、同様に正常にアップデートが完了した。この場合、同じPCにVOICEVOX0.19.0とVOICEVOX0.19.1の両方がインストールされ、どちらも起動可能であった。
  - ちなみに違うバージョンのVOICEVOXが一つのPCに入っている場合、Windows設定上ではすべてのユーザーにインストールしたバージョンが優先して表示される……っぽい？（現Winodwsユーザーアカウント=管理者のとき）
- VOICEVOX0.19.0とVOICEVOX0.19.1のインストール先を同じにした場合、アンインストール時に若干の不都合が生ずる。VOICEVOX0.19.0をWindowsの設定からアンインストールした場合、Windows観点では0.19.0のみアンインストールされ、0.19.1はインストールされたままとなっているが、実際には0.19.1もアンインストールされている（=フォルダが削除されてしまっている）ため、0.19.1がWindows設定上にゾンビのように残ってしまっていた。Windows設定からアンインストールしようとしても、Uninstall.exeが存在しないため、0.19.1をアンインストールできない。
- ただし、もう一度現在のユーザーに0.19.1をインストールし直せば、再度アンインストールできるようになるため、さほど問題にならないと考えられる。また、この場合でも、必ず一回はアンインストールできるため、既に不具合で挙がっているような「そもそもアンインストールが実行不可能」という事象とは矛盾する。これが、アンインストール失敗の原因ではないと思われる。

VOICEVOXインストーラーの詳細なエラーログが存在しないため、これ以上原因を探るのは難しいような気がします。
初期ファイルの作成エラーというエラー自体は、VOICEVOX以外でも度々見られるエラーっぽいです。完全な推測になってしまいますが、恐らくVOICEVOXのフォルダに何かが干渉していて（再起動してもダメなら常駐しているソフトウェアか何か）、その影響でファイルにアクセスできなくなって、アップデートもアンインストールも出来なくなっている……ような気がします。もしそうだとすると、インストール先を変えるだけでアップデートやアンインストールできない問題は解消されるのかも……？

根拠がふわふわっとしてますが……ひとまず私が試した手順を載せておきます。何かのお役に立てば幸いです。

**Comment by Hiroshiba** [comment]
きめ細やかな検証ありがとうございます！！

再現しない、なるほどです･･････！　かなりの強敵な予感がしますね･･･！

今回の報告の方の場合はフォルダごと消せばOKだったみたいなので、何かしらの常駐ソフトが干渉している可能性もありそうですね･･･。
DropboxやOneDriveとかならディレクトリがヒントになりそうなので、次からはディレクトリのインストール場所も聞いてみようと思います。

そこまで多くの報告は来ていないこと、再現ができなかったことからこのissueは根本的な解決ができないとしてcloseしたいと思います！
@terapotan さんありがとうございました！！
