### ISSUE TITLE
ファイル保存全般をアトミック操作にする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#2103]
## 内容

VOICEVOXでファイル保存する時、大体はファイルに直接書き込む形で実装されています。
https://github.com/VOICEVOX/voicevox/blob/bba10607fa6c57eda45f4695ff643cd9cbd236bf/src/backend/electron/main.ts#L998-L1007

この操作は割と危なくて、何かしらの原因で途中で書き込みが中断してしまうことがあると、中途半端な値が保存されて設定ファイルが壊れます。
特にプロジェクトファイルは膨大な作業量の賜物なので、慎重に上書きしてあげたいです。

このissueは↑の`WRITE_FILE`と、あと`RuntimeInfoManager.ts`にある`writeFile`がアトミック操作になれば完了だと思います。
https://github.com/VOICEVOX/voicevox/blob/bba10607fa6c57eda45f4695ff643cd9cbd236bf/src/backend/electron/manager/RuntimeInfoManager.ts#L89-L92

### Pros 良くなる点

意図しないデータの削除が発生しにくくなる

### Cons 悪くなる点

ないはず

### 実現方法

同じディレクトリに一時ファイルを書き出し、mvするのが安全だと思います。
アトミック操作にする処理は @RikitoNoto さんが↓で実装してくださいました！

- https://github.com/VOICEVOX/voicevox/pull/2098

この操作を関数切り出ししていろんなところで使えるようにし、いろんなところで使えば解決かもしれません。

## その他

不明な点があれば何でもお聞きください！

**Comment by tsunekazuomija** [comment]
こんにちは！
こちらのタスクに取り組んで見たいのですが、よろしいでしょうか？

また、タスクについて一点質問なのですが、
切り出した関数は`src/helpers`フォルダ下にファイルを作成して保存する
という形で良いでしょうか？

**Comment by Hiroshiba** [comment]
@tsunekazuomija もちろんです、ぜひぜひ！！

> 切り出した関数はsrc/helpersフォルダ下にファイルを作成して保存する
という形で良いでしょうか？

とても良いと思います！
今見てみたらすでに`fileHelper.ts`ファイルがあったので、切り出す関数によってはとりあえずここに書いても良いかもですね･･･！
https://github.com/VOICEVOX/voicevox/blob/b0d8c2e8aa843f380c36352fdcc6e6c1b8bfb66f/src/helpers/fileHelper.ts

なにかあればかなり気軽にお聞きいただければ 🙏

**Comment by tsunekazuomija** [comment]
ありがとうございます！
確かにfileHelper.tsにまとまっていたほうが良さそうです！
その方針で進めてみます！

**Comment by Hiroshiba** [comment]
ぜひぜひ！！
