### ISSUE TITLE
Chromebookでvoicevoxが起動しない

### ISSUE THREAD

**Issue by ykyk15** [VOICEVOX/voicevox#2105]
## 不具合の内容

ChromebookのOSをアップデートしたら、voicevoxが起動しなくなった(ウィンドウが白や黒に点滅)
そこで再度インストールし直してみたら、インストールはされているが、ランチャーにアプリが表示されず起動できない。

### 現象・ログ
Chromebookでvoicevoxが起動しない

### 再現手順
？

### 期待動作
インストールでき、アプリがランチャーに表示され起動できる

## VOICEVOXのバージョン

0.19.1

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [x] Linux

*   Others (Chromebook OS ver：124.0.6367.219)

## その他

ターミナルから、
~$ .voicevox/VOICEVOX.AppImage
と打つと
-bash: .voicevox/VOICEVOX.AppImage: No such file or directory
となり起動しない。

再インストールしようとすると、
VOICEVOX already installed in '/root/.voicevox/VOICEVOX.AppImage'.
Replace?(y/n):
となるのでインストールはされているよう。yを選択して再インストールしても、状況は同じ

ChromebookのOSアップデート以前は、ランチャーに表示され、起動もできた
(アップデート前のOSバージョンは不明。voicevoxも最新版ではなく0.18.？か0.17.？あたりだった)

OSアップデート前は、
マイファイル＞Linuxファイル＞.voicevox
と、.voicevoxフォルダがあったが、現在はこの場所に.voicevoxフォルダがない

root下にインストールされているから起動できない？？？

GIMPというアプリは、ChromebookのOSのアップデート前後で特に変わりはなく、ランチャーに表示され起動もできる

Linux初心者で、これはバグなのかこちらで対処できることなのか、わからず。。
どうすれば良いか教えていただけると助かります。

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！
chromebookはサポート対象外かもしれませんが、知見をこのissueに集められると嬉しいです。

たしかにrootにインストールされているのは不思議ですね。
インストール時に`sudo`を付けてしまったとかでしょうか。

ちなみにLinuxのバージョンはいくつでしょうか？
例えば今回の問題とは異なりそうですが、ubuntuの24.04でしたら動かないとかがあったりします。参考になれば･･･！！

- https://github.com/VOICEVOX/voicevox/issues/2071

**Comment by ykyk15** [comment]
コメントありがとうございます。
結論から申しますと、無事インストールできて起動しました。

Linuxのバージョンは12.5でした。
インストール時におっしゃるとおり、sudo付けておりました。

OSアップデート前は、sh、bashでインストールできなかったので、sudo bashでインストールしており、ランチャーにも表示され、起動しておりました。

OSアップデート後は、sh、bashではインストールできないと思いこんでおり、最初からsudo bashでインストールし、報告したような状況になっていました。

コメントいただいて、sh、bashでインストールし直してみたところ、
shでは下記のようなエラーが出てインストールできなかったですが、
VOICEVOX.Installer.0.19.1.Linux.sh: 19: set: Illegal option -o pipefail

bashで試したところ、home/ユーザー名/.voicevoxにインストールされ、ランチャーにも表示され、起動することができました。

お騒がせして申し訳ありませんでした。
コメントいただきありがとうございました。

**Comment by Hiroshiba** [comment]
ご報告ありがとうございます！解決してよかったです！！

issueがあると同じようなエラーが出た方が自力で解決できると思うので、こちらとしても助かりました･･･！
