### ISSUE TITLE
ソング・ハミングで口パクデータ（.labファイル）を出力したい

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#2107]
## 内容

トークソフトにはよくある .lab ファイルの出力機能がソング側にもあると面白そうです。
実際の需要の声↓

https://x.com/Sazanami_ch35/status/1795808363064013058

VOICEVOXは原理的に、音声合成の途中で音素列を求めます。
その情報はエディタ内にもあるので、どうにかしてファイル出力まで持っていけば可能だとは思います。
https://github.com/VOICEVOX/voicevox/blob/a07c776956987f8a44538089278449cd0469f022/src/openapi/models/FrameAudioQuery.ts#L46

### Pros 良くなる点

口パクで歌えるようになるので動画映えする

### 実現方法

音素列を取得し、labに加工してファイル保存すればOKなはずです。

labに加工する方法はトーク側にあります。
https://github.com/VOICEVOX/voicevox/blob/a07c776956987f8a44538089278449cd0469f022/src/store/audioGenerate.ts#L70

ファイル保存は、wav保存時に同じファイル名.labを保存すればOK。

問題はどうやって音素列を保存関数まで持っていくかだと思います。
現状音声合成はリアルタイム性を加味するために[RENDER関数](https://github.com/VOICEVOX/voicevox/blob/a07c776956987f8a44538089278449cd0469f022/src/store/singing.ts#L922)で閉じていて、音素列を持ってこれないはずです。
また給付ごとに区切ったフレーズごとに音声合成しているので、フレーズごとに散らばっている音素列をどうにかして集約する必要もありそうです。

このあたりの設計を整理するところからなのかなと思います。

## その他

設計だけでもコメントウェルカムです！
不明な点などあれば気軽にお聞きください 🙏

**Comment by sigprogramming** [comment]
[EXPORT_WAVE_FILE](https://github.com/VOICEVOX/voicevox/blob/a07c776956987f8a44538089278449cd0469f022/src/store/singing.ts#L2309)は[レンダリング完了を待って](https://github.com/VOICEVOX/voicevox/blob/a07c776956987f8a44538089278449cd0469f022/src/store/singing.ts#L2460-L2469)から書き出すようになっていて、これと同じようにレンダリング完了を待つようにすれば音素列を持ってこれると思います。
音素列は`state.singingGuides.get(phrase.singingGuideKey)`して`singingGuide.frameAudioQuery.phonemes`で取得できます。

フレーズごとに散らばっている音素列は、以下の流れで集約できると思います。
1. 各音素の位置（曲の先頭から何秒のところにあるか）を求める
2. フレーズごとに散らばっている音素列を一つにまとめる
3. pauが連続しているところを一つのpauにまとめる
4. 各音素の位置を $t_0, t_1, t_2, \ldots, t_{n-1}$ として、 $t_i > t_{i+1}$ の場合に $t_{i+1}$ を $t_i$ に設定する

**Comment by Hiroshiba** [comment]
この機能の要望を結構見かけるので、優先度中にしたいと思います！挑戦者求む！
https://x.com/roxtarland/status/1819718592163918197

**Comment by sigprogramming** [comment]
#2356 で実装した処理を使用すれば、こちらすぐ実装できそうです、取り組みます。

**Comment by sigprogramming** [comment]
まだ書き出すトラックを指定できるようにはなっていませんが、
書き出し自体はひとまず実装できたので、こちらcloseします！
