### ISSUE TITLE
話者の一括変更

### ISSUE THREAD

**Issue by stIprurIJu** [VOICEVOX/voicevox#2119]
## 内容

全体の話者を一括で変える機能が欲しい。

話者を変えて聞き比べてみたい時に不便。

### Pros 良くなる点

一つ一つ変更する必要がなくなる。
### Cons 悪くなる点

個別に変更したい時は、手間が増える。
## VOICEVOXのバージョン

0.19.2

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

Windows 11 Home 64 ビット
## その他

https://github.com/VOICEVOX/voicevox/assets/164626763/6299d961-e25b-4253-a640-0edb1386f3ac

**Comment by sevenc-nanashi** [comment]
実験的機能に複数選択があります、それで一括選択->変更ができます。

**Comment by stIprurIJu** [comment]
やり方が解りません。どうすれば良いですか？

**Comment by sevenc-nanashi** [comment]
「設定」 > 「オプション」、の下の方の「実験的機能」に「複数選択」があります。それを有効にした後に、テキスト欄をShift+クリック、またはCtrl+クリック（Excelやエクスプローラー等の挙動と揃えています）すると複数のテキスト欄が選択されるので、その状態で話者を変更すると一括で変わります。

**Comment by stIprurIJu** [comment]
これだと全部選択するのに300回以上クリックしないといけないのですが、他に方法は無いのでしょうか？
https://github.com/VOICEVOX/voicevox/assets/164626763/947332f4-5f41-48b2-8f5f-e2bf7228e51f

**Comment by sevenc-nanashi** [comment]
一番上のテキスト欄を選択した後に一番下のテキスト欄をShift（Ctrlではない）押しながらクリックすると範囲選択できます。（ちなみに、今後のアップデートで全選択が実装されます）

**Comment by stIprurIJu** [comment]
出来ました。ありがとう御座います。
これは説明がないと判りませんね。

**Comment by Hiroshiba** [comment]
@stIprurIJu さん

操作方法については使い方ガイドに記載がありました。
https://voicevox.hiroshiba.jp/how_to_use/#:~:text=%E3%81%97%E3%81%A6%E3%81%84%E3%81%BE%E3%81%99%E3%80%82-,%E8%A4%87%E6%95%B0%E9%81%B8%E6%8A%9E,-%E8%A4%87%E6%95%B0%E3%81%AE%E3%83%86%E3%82%AD%E3%82%B9%E3%83%88

よりわかりやすく改善が必要かもしれません。もしドキュメントの修正にご興味がありましたら、VOICEVOXプロジェクトにプルリクエストを送っていただけると助かります。
https://github.com/VOICEVOX/voicevox/blob/0bd0a3fa42abc16e840bd36764e02382435ec7bc/public/howtouse.md#L460-L464

**Comment by stIprurIJu** [comment]
『今後のアップデートで全選択が実装されます』との事ですので、ひとまず大丈夫そうです。

**Comment by Hiroshiba** [comment]
@stIprurIJu さん

あっすみません、一括変更に関して解決しそうなことは良かったのですが、ドキュメントに課題がありそうだとわかったので、よかったら改善に挑戦してみないかというお誘いでした！
（オープンソースソフトウェアはみんなで協力してより良くしていくものなので）
