### ISSUE TITLE
『連続再生』中に『停止』を押すと、『停止』を押した位置で止まって欲しい

### ISSUE THREAD

**Issue by stIprurIJu** [VOICEVOX/voicevox#2127]
## 内容
読み上げの間違いを探そうと『連続再生』を押して、間違いを見付けて『停止』を押すと、『連続再生』を押した位置まで戻ってしまい、修正に手間が掛かる。

https://github.com/VOICEVOX/voicevox/assets/164626763/b0e6fe8a-b609-48fe-bf8c-f505bebd1780

『停止』を押した位置で止まる様にして欲しい。
長文を読み上げさせていると、間違い箇所まで戻るのに何十行と探さなくてはならない時もあり、一苦労する。

### Pros 良くなる点

ちょっとした事だが、作業効率が格段に上がる。

## VOICEVOXのバージョン

0.19.2

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

Windows 11 Home 64 ビット 23H2

**Comment by sevenc-nanashi** [comment]
個人の思想ですが：こういう連続再生系、停止押したときに元の場所に戻るソフトと押したところで止まるソフトで分かれてる気がするので設定可能にしてもいいかも？

**Comment by Hiroshiba** [comment]
たしかに、設定を用意するの良さそうですね！

### 実装方法

`PLAY_CONTINUOUSLY_AUDIO`関数の最後の`SET_ACTIVE_AUDIO_KEY`をなくせばたぶん最初に戻らなくなるはず？
https://github.com/VOICEVOX/voicevox/blob/2a95df7a2bc3d9eda08fb012958e1759a61d2cfd/src/store/audio.ts#L1801

あとは設定パラメータを増やして、その設定に従って挙動を変えれば良さそう。
たぶんこの「再生位置を追従」と同じように設定パラメータを作れば良さそう。
![image](https://github.com/VOICEVOX/voicevox/assets/4987327/fb820f5b-57e8-48f6-b0b8-d6ccb0457d8d)
「再生位置を追従」でコード全体検索すれば場所わかるはず。

---

おそらく結構簡単なので、初心者歓迎タスクラベルをつけてみました。
実装募集中です！

**Comment by Hiroshiba** [comment]
@stIprurIJu あれ、closeされた意図はなんでしょうか？ 👀
