### ISSUE TITLE
ドキュメント修正：READMEにおけるmacOS向けのvoicevox_engineのパス修正

### ISSUE THREAD

**Issue by jdkfx** [VOICEVOX/voicevox#2136]
## 内容

READMEに記載されてあるmacOS向けの`voicevox_engine`のパスが最新版の`VOICEVOX.app`とは違っている。
https://github.com/VOICEVOX/voicevox/blob/2b059d462c1481003907acacd006cf53320ee230/README.md?plain=1#L58

現在のバージョンにおける正確なパスは`/path/to/VOICEVOX.app/Contents/MacOS/vv-engine/run`となっている。

### Pros 良くなる点

- macOSでの環境構築において、環境構築できないといった問題がなくなる

### Cons 悪くなる点

- なし

### 実現方法

- READMEを修正

## VOICEVOXのバージョン

0.19.2

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [x] macOS
- [ ] Linux

## その他

- 他にもmacOS向けの`voicevox_engine`パスの記載について、違っている箇所があれば修正する。

**Comment by Hiroshiba** [comment]
あっ本当ですね！！

リポジトリ全体を`Contents`とかで検索してみた感じ、READMEのそちら以外は特になさそう･･･？

もしよかったら修正プルリクエストいただけると助かります！
なにかのついででもOKです。ご面倒でしたらこちらで変更しておきます！

**Comment by jdkfx** [comment]
#2075 

こちらのPRに合わせて修正コミットしておきます！
