### ISSUE TITLE
エンジンプロセスの停止をtreeKillではなく通常のkillにしたい

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#2167]
## 内容

エンジンの停止はtreeKillを使っていて、windowsは[どうしても強制終了するコード](https://github.com/pkrumins/node-tree-kill/blob/cb478381547107f5c53362668533f634beff7e6e/index.js#L29)になっています。
これではエンジン側のgracefulシャットダウンができないので、通常のkill（SIGTERM送信的なの）にしたいです。

ただNodeのprocess.killは子プロセスをキルしないので、エンジン側が子孫をちゃんとkillするように作ってないと、ゾンビプロセス的な感じで残ってしまうかもしれません。

今のVOICEVOXエンジンにNodeでprocess.killしてみて（treeKillの部分を普通にprocess.killに変えれば良さそう）、ちゃんと消えてくれてそうならkillに置き換えたいです。

### Pros 良くなる点

エンジン側が強制終了されなくなる

### Cons 悪くなる点

確かめが必要

### 実現方法

1. treeKillの部分をprocess.killに置き換え
2. VOICEVOXエンジンのサブプロセスが残っているかをこのissueにコメント
3. なさそうなことを確認できたらプルリク

## VOICEVOXのバージョン

0..19.2

## その他

可能ならいろんなOSで大丈夫か確認したいところですが、windowsで確認できればいったんOKな気がします。
（ビルド後にいろんなOSでチェックは必要）

[VOICEVOXエンジン側でgracefulな処理をしたい部分がある](https://github.com/VOICEVOX/voicevox_engine/issues/1347)ので、実験結果をお待ちしています！

**Comment by sabonerune** [comment]
次のようにコードを修正してWindowsで試してみました。
https://github.com/VOICEVOX/voicevox/blob/1f39897f28ffaf93cd5df3e391a4c5a22e1d37cf/src/backend/electron/manager/engineManager.ts#L444-L449
```diff
-      treeKill(enginePid, (error) => {
-        if (error != undefined) {
-          log.error(`ENGINE ${engineId}: Error during killing process`);
-          reject(error);
-        }
-      });
+      const result = engineProcess.kill("SIGINT");
+      if (!result) reject("err");
```
Windows環境、VOICEVOX Engineの場合は子プロセスまで終了できていると思います。
(念のため`--enable_cancellable_synthesis`を追加しても全て終了した。)

エンジンの方に`lifespan`でファイルに書き込む処理を足して動作確認をしましたがgraceful shutdownは行われていないようです。

---

Nodeのドキュメントの記述で子プロセスがキルできるかよく分からないのですよね…
[subprocess.kill([signal])](https://nodejs.org/docs/latest-v20.x/api/child_process.html#subprocesskillsignal)
>On Windows, where POSIX signals do not exist, the signal argument will be ignored, and the process will be killed forcefully and abruptly (similar to 'SIGKILL'). See [Signal Events](https://nodejs.org/docs/latest-v20.x/api/process.html#signal-events) for more details.

[Signal events](https://nodejs.org/docs/latest-v20.x/api/process.html#signal-events)
> - Sending `SIGINT`, `SIGTERM`, and `SIGKILL` will cause the unconditional termination of the target process, and afterwards, subprocess will report that the process was terminated by signal.

エンジンは恐らく強制終了。
エンジンの子プロセスはエンジンの親がキルされたというシグナルを受け取る？(見当違いかも)

**Comment by Hiroshiba** [comment]
@sabonerune おお！！　検証ありがとうございます！！！！

> Windows環境、VOICEVOX Engineの場合は子プロセスまで終了できていると思います。

なるほどです！！

> エンジンの方にlifespanでファイルに書き込む処理を足して動作確認をしましたがgraceful shutdownは行われていないようです。
> On Windows, where POSIX signals do not exist, the signal argument will be ignored, and the process will be killed forcefully and abruptly (similar to 'SIGKILL'). See [Signal Events](https://nodejs.org/docs/latest-v20.x/api/process.html#signal-events) for more details.

ああああすみません。。。。。killシグナルを選べない可能性を考えていませんでした。。。。
強制終了になってしまうんですね･･･････。

> Nodeのドキュメントの記述で子プロセスがキルできるかよく分からないのですよね…

わからないですね･･･。Windowsだから･･･？あるいはpyinstallerくんがよしなにやってくれてるのかも。

---

なんにせよエンジン側をgracefulに終了できないならこのissueの提案は叶えられなそうです。。。

検証ほんとにありがとうございます！！！
（gracefulの戦いはまだ続きそうですね。。。 😇 ）
