### ISSUE TITLE
`voicevox.app`に直接`vvproj`をD&Dすると開かない場合がある。

### ISSUE THREAD

**Issue by sabonerune** [VOICEVOX/voicevox#2168]
## 不具合の内容

未起動状態で`vvproj`をD&Dするとそのプロジェクトが開きます。
しかし普通にVOICEVOX.appをダブルクリックして起動した後に、`voicevox.app`に`vvproj`をD&Dしてもプロジェクトが一度も開かないようです。

### 期待動作

VOICEVOX起動状態で`vvproj`ファイルを`VOICEVOX.app`にD&Dしてプロジェクトが読み込まれる。

## VOICEVOXのバージョン

0.19.2 ?

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [x] macOS
- [ ] Linux

## その他

発見の経緯
https://discord.com/channels/879570910208733277/893889888208977960/1260262392932208681

このコードがElectronが想定しているコードと異なる気がします。
https://github.com/VOICEVOX/voicevox/blob/1f39897f28ffaf93cd5df3e391a4c5a22e1d37cf/src/backend/electron/main.ts#L1106-L1112
https://www.electronjs.org/ja/docs/latest/api/app#%E3%82%A4%E3%83%99%E3%83%B3%E3%83%88-open-file-macos

本来は`open-file`を`app.on`で監視して既にアプリが起動しているなら`second-instance`と同様の処理をするようにするべきなのだと思います。
https://github.com/VOICEVOX/voicevox/blob/1f39897f28ffaf93cd5df3e391a4c5a22e1d37cf/src/backend/electron/main.ts#L1245-L1269

自分はmacを持っていないので検証や修正が難しいです。

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！！

おっしゃる通り、おそらくsecond-instanceの処理と共通化するのが良いと思います！
ただopen-fileは初回起動の時も呼ばれるっぽいので、２回目以降ならsecond-instanceと同じような処理をし、１回目なら通常起動させるみたいなコードが必要になりそうです。

もしまともに実装しようとすると起動シーケンスがさらにややこしくなってしまうのと、.appにドラッグ&ドロップしなくてもファイルダブルクリックなら別経路になって正しく開かれること、それと実際に出くわすことが珍しそうなので、意図しない挙動だとは認識しつつ、あえて実装はしない方針で進めるのが良いのかなと思いました。
メンテナンス性考えるとこっちのがボイボの発展に良いだろうという考えです。もう少し起動シーケンスが整理されたら取り組んでも良いのかなと思います…！

ということでcloseさせていただきます。
issue作成ありがとうございます！！！
