### ISSUE TITLE
マルチトラック：トラックの追加・削除・ソロの解除ボタンはどこに置くのが良いか

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#2182]
## 質問の内容

すみません、ちょっとデザイン周りで相談が 🙇 cc @sevenc-nanashi @romot-co @sigprogramming 

マルチトラックのUIで、トラックの追加・削除ボタンの場所と、あとソロ解除のボタンはどこにどう配置するのが良いでしょうか。。
後々の使い方に関わってくるので、場所だけちょっと相談したいなと。

今のマルチトラックの UI はこんな感じです。

<img src="https://github.com/user-attachments/assets/57fce183-24ba-470c-aa40-687b492ac8fa" width="300" />

トラックの追加・削除ボタンが右上にあって、ソロの解除ボタンが右下にあります。
それぞれなぜこうなっているか、なぜ迷っているかの説明はこんな感じです。

* 追加ボタンが右上
	* 辞書に単語追加するときのボタンが右上だから揃えた
	* ここにはソロ解除ボタンが来るべきな気がしなくもないので迷ってます。。
* 削除ボタンが右上
	* トラックは右クリックできるけど、ソフトウェア全体として右クリックを使う機会が少ないので気づけないんじゃないかと思って追加
	* かと言ってトラックごとに削除ボタンを置くスペースはない
	* なので追加の横に配置したけど、本当にそれでいいのか迷ってます。。。
* ソロ解除ボタンが右下
	* ソロボタンと縦のラインを揃えた方がいいかなと思った
	* 上が使われているので、消去法で下にあります
	* 上にあるべきな気がしなくもない。。。。

どうすべきですかね。。。 😇 

## その他

色々アイデア考えてみました。

1. 削除ボタンを消し、右上に「＋」ボタンとソロ解除ボタンを置く
	* 収まりは良い。
	* トラックの削除に気づけないかもしれない（意外と大丈夫･･･？）
	* ＋ボタンとソロ解除ボタンは意味的に異なるものなのに隣同士に置かれるのがちょっと違和感ある
2. 右下に追加ボタン、右上にソロ解除ボタン
	* なんだかんだこれが丸い気がする
	* 削除ボタンは追加ボタンの横に置くか置かないかどっちでも良さそう、とりあえず置く･･･？
	* ＋ボタンと🗑️ボタンでも良いかも
3. そのままにする

書いてるうちに 2 で良いのではという気持ちになってきました！
ご意見募集中です 🙇

**Comment by romot-co** [comment]
@Hiroshiba 
(詳細考慮してみますが、まず取り急ぎ)

- 削除ボタンは各トラック側(削除対象)に置く: 「トラック」の「削除」というように見せた方がよさそう
- 追加ボタンはトラック全体を操作する場所に置く: 「トラック全体(一覧)」に「追加」/ 全ソロON/OFFを置くのであればそれと同じ場所がよさそう？
- 全ソロON/OFF: 上記同様・表示の仕方は考慮した方がよさそう

あとで絵にしてみます！

**Comment by sigprogramming** [comment]
@Hiroshiba 
追加ボタンを押したら一番下に新しいトラックが追加されますが、追加ボタンとトラックが追加される位置が離れている感じがするので、トラックが追加される位置に追加ボタンを置くと良いかもと思いました。（追加ボタンの高さ分、追加でスクロール可能にする）

削除ボタンも同様で、削除ボタンの位置からどのトラックが削除されるか（実際は選択されているトラックが削除される）が分からないかもです。なので、@romot-co さんがおっしゃるように「各トラックに置く」か、「右クリックからのみにする」のが良いかもと思いました。

ソロ解除ボタンも同様で、トラックが少ないときに各トラックのソロボタンとソロ解除ボタンが離れてしまうので、右上が良いかもです。

**Comment by Hiroshiba** [comment]
ご意見ありがとうございます！！

とりあえず意見の一致ということで全ソロ解除ボタンは右上にしようと思います！

追加ボタンの場所をどこにするかボタンをどうするかは引き続き迷っています。
うーん。。。。。ちょっと実際に配置してみて許されそうだったら右上に追加ボタン、削除ボタンはなし･･･かなぁと思ってます！
一旦これでリリースさせていただくかもです 🙇 

> 削除ボタンは各トラック側(削除対象)に置く

そうしたいんですが、置く場所がなく･･･ 😇 
置く場所が見つかったらこれが一番良さそう。

> 追加ボタンを押したら一番下に新しいトラックが追加されますが、追加ボタンとトラックが追加される位置が離れている感じがするので

右クリックのコンテキストメニューに「トラックの追加」を追加してもいいかもですね！
ちなみに選択されているトラックの下に新しいトラックが追加されるのが良いのかなと思っています。
（トーク側がそうなので）

> トラックが追加される位置に追加ボタンを置くと良いかもと思いました

実はこの方法には欠点があって、画面外にはみ出るほどトラックがたくさんあった時、追加ボタンが一番下の画面外に行っちゃうんですよね。
あと途中にトラックを追加することができなくなるかもです。
例えば後からインスト用のトラックを一番上に追加したくなった時に、一番下に追加した後ドラッグ&ドロップで移動させないといけないみたいな。

（ということに気づいてトーク側は右下に+ボタンを固定配置し、選択されている欄の下に追加されるようにしています）

**Comment by romot-co** [comment]
少しだけ考えてみました…！
(上の場合と下の場合)
https://xd.adobe.com/view/8f64f65d-a369-4a07-a9c6-31c2f0f4f89c-da37/

**Comment by Hiroshiba** [comment]
おお、なるほどです！！
削除ボタンはデザイン次第でトラック内に含められそうだなと感じました！
追加ボタン左上、もしかしてもしかしたらアリかもですね。ちょっと見ないので難しいかもだけど。

**Comment by Hiroshiba** [comment]
一旦こんな感じになりました！

> サイドバーの部分は、フッターにあったソロ全解除を上に上げて、横に追加ボタンを＋にして配置し、削除可能になったら削除ボタンが出るようにしてみました。

![image](https://github.com/user-attachments/assets/4f0e23f3-9115-477e-bf29-0bff4d0200ad)
