### ISSUE TITLE
ソング：ソロ全解除をして再生すると、全解除前のように聞こえる

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#2194]
## 不具合の内容

ソロ全解除して再生すると、全解除してないような聞こえ方をしました。

### 再現手順

* ２つトラック用意
* 片方ソロに
* ソロ全解除する
* 再生する、ソロが解かれてないように聞こえる
* ミュート状態変えたり、ノートを移動させたりすると聞こえるようになる

https://github.com/user-attachments/assets/a9c84d4e-399c-46de-9dc1-e486181c7599

## VOICEVOXのバージョン

0.20.0

## その他

まあ････超致命的というほどではないので、0.20.0のリリースはそのままで良いかな･･････。

**Comment by sevenc-nanashi** [comment]
ちなみに原因としてはUNSOLO_ALL_TRACKSでRENDERが呼ばれてないからですね。

**Comment by Hiroshiba** [comment]
おーーーなるほどです！！！

なんかこれ前もあった気がしますね。マルチトラックで追加された全actionを一通り点検しても良いかもしれない。

**Comment by Hiroshiba** [comment]
こちら取り組もうと思います！
