### ISSUE TITLE
読み方&アクセント辞典: ホバーで現れた編集（鉛筆アイコン）ボタンを押下して開いたときのみ、編集ペインが空っぽになる

### ISSUE THREAD

**Issue by honey32** [VOICEVOX/voicevox#2196]
## 不具合の内容

タイトルの通りです

### 現象・ログ

- ✅  リストアイテム全体のクリック可能領域を押下した場合（以下、「全体クリック」）
    - 期待どおりに編集ペインの中に、該当するアイテムの単語・読みが入っている
- 💣   全体クリックせず、ホバーして現れた編集（鉛筆アイコン）ボタンを押下した場合
    -  編集ペインが開くが、該当するアイテムの単語・読みが入っておらず空っぽになっている（下図の通り）
- ✅  ただし、全体クリックをしたあと、編集ボタンを押下した場合には、期待通りに動作する

![image](https://github.com/user-attachments/assets/154b536a-307f-4268-a9a7-332b3c95423d)

### 期待動作

編集ボタンを押下したときは、リストアイテム全体のクリック可能領域を押下したときと同じように編集ペインの初期値が設定されるはず

## VOICEVOXのバージョン

0.20.0

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

エディション	Windows 11 Home
バージョン	23H2
インストール日	‎2022/‎09/‎30
OS ビルド	22631.3880
エクスペリエンス	Windows Feature Experience Pack 1000.22700.1020.0

## その他

この変更によるデグレの可能性が高い…

https://github.com/VOICEVOX/voicevox/pull/2072

**Comment by honey32** [comment]
クリックしたあとに編集ボタンを押下したら期待通り、
クリックせず、ホバーだけで現れた編集ボタンを押下したときには空になる

ってことに気づいた…

「対象を選択する処理を挟まずにペインだけを開く」流れになってしまってそう

**Comment by Hiroshiba** [comment]
@honey32 issue作成ありがとうございます！！

おっしゃる通り選択を挟まずに状態遷移してしまってるためな気がします！
試してみた感じもしかしたら編集だけでなく削除もそういった挙動かもです。

ちょっと試してないのですが、とりあえず編集・削除する時にselectWord(key)を挟むともしかしたら解決するかも･･･？

https://github.com/VOICEVOX/voicevox/blob/b1596965fb0161451e968c02a23feff209e3e5be/src/components/Dialog/DictionaryManageDialog.vue#L93-L94
この辺りの処理を`@click.stop="selectWord(key); editWord"`とする感じを想像してます･･･！！

**Comment by honey32** [comment]
@Hiroshiba 

やっぱりそこですか！ではやっておきます！

**Comment by Hiroshiba** [comment]
すみません助かります！！
よくわからないとこあればなんでも聞いていただければ！！
