### ISSUE TITLE
ソング：「tracksとtrackChannelStripsの同期」と「ChannelStripにフレーズの音声を接続」をRENDERで行わないようにする

### ISSUE THREAD

**Issue by sigprogramming** [VOICEVOX/voicevox#2197]
## 内容

現在、
- tracksとtrackChannelStripsの同期
- ChannelStripにフレーズの音声を接続する

を`RENDER`（非同期）で行っていますが、これには以下の問題があります。
- 本来同期的に行えるはずのWebAudioAPI関連の処理を非同期で行っている
  - メインスレッドで同期的にAudioNodeの操作を行えるというWebAudioAPIのメリットが活かされない
  - チャンネルの音量の変更などがリアルタイムに反映されない
    - 微調整がしにくく、結構つらい
- trackChannelStripsに依存する処理を`RENDER`で行わないといけなくなる
  - `RENDER`がどんどん複雑になっていくかも
  - チャンネルのルーティングを行う機能などが実装しにくくなる
- 「ChannelStripの生成・削除」と「ChannelStripにフレーズの音声を接続する処理」が分かれている
  - 「ChannelStripの生成・削除」は「trackChannelStripsを同期する」で行っている
  - 「ChannelStripにフレーズの音声を接続する処理」は「歌声のレンダリング」で行っている
  - トラックの削除をUndoしたときChannelStripは再生成されるが、トラック削除時にフレーズの削除が行われていなかった場合、歌声レンダラー視点ではフレーズは変わっていないので再レンダリングが行われず、ChannelStripにフレーズの音声を再接続する処理も行われない

なので、`RENDER`では「歌声のレンダリング」と「フレーズの音声を登録・削除する関数を呼ぶ」のみ行って、
「フレーズの音声を登録・削除する関数」と「tracksとtrackChannelStripsを同期する関数」内で「ChannelStripにフレーズの音声を接続する」を行うようにした方が良さそうです。
フレーズの音声をトラックIDと紐づけて保持しておけば、ChannelStripの再生成時に再接続を行えると思います。
そして、「tracksとtrackChannelStripsを同期する関数」を同期的に呼ぶようにすれば、「ChannelStripにフレーズの音声を接続する処理」も同期的に行えると思います。

### Pros 良くなる点

- 機能追加しやすくなる
- チャンネルの音量の変更などをリアルタイムに反映させることが可能になる
- 「tracksとtrackChannelStripsを同期する」の後に「フレーズを更新する」を必ず実行しないといけないという制約がなくなる

### Cons 悪くなる点

- 若干コードが増えて複雑になるかも

### 実現方法

以下の関数を実装します。
- `registerSequence`
- `deleteSequence`
- `syncTracksAndTrackChannelStrips`（これはactionで良いかも）

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！

方針に賛成です！
「フレーズ←→ChannelStrip」はRENDERで行い、「ChannelStrip←→track設定」は別の関数で行う感じですよね。

> syncTracksAndTrackChannelStrips（これはactionで良いかも）

少なくとも、channelStripsがstate内にあって、mut内で呼んでしまうとundo/redoでバグるのでダメなはず。
それ以外なら一旦問題は思いつかないかもです。RENDERに合わせてactionが良いかも･･･？

あるいはwatchで同期でも良いと思います。
全ノートをwatchしないといけないRENDERだと計算資源的に厳しいかもだけど、トラックをwatchするだけでいいのでchannelStripの同期はwatchで十分かも。

ただどの方法にしろ、channelStripの作成・削除がRENDERとsyncTrackでずれうるのをどう解決するか厄介ですね･････。
パッと思いつくのはされてもchannelStripは消さずにグラフ接続だけ切る、とかでしょうか･･･。
（これで解決できるのか若干自信ないですが･･･。）
