### ISSUE TITLE
ソング：トラック名が保存されない

### ISSUE THREAD

**Issue by sigprogramming** [VOICEVOX/voicevox#2198]
## 不具合の内容

トラック名が保存されません。

### 現象・ログ

プロジェクトファイルにトラック名が保存されていない

### 再現手順

トラック名を変更して保存する

### 期待動作

トラック名が保存される

## VOICEVOXのバージョン

0.20.0

**Comment by Hiroshiba** [comment]
こちら取り組んでいます！
