### ISSUE TITLE
ソング: 表示メニューを用意する？

### ISSUE THREAD

**Issue by romot-co** [VOICEVOX/voicevox#2202]
## 内容

メニューに「表示」メニューが必要ではないかという提案です
表示切り替えできる機能を押し込んでおく場所目的です

今後、シンガー表示・拍子変更・BPM変更・ボリューム変更その他など
好みや目的に応じて表示を切り替えるものが多くなると予想されます

個別に切り替えボタンを用意する前提ですが
まずは悩まずにすむよう切り替えられるすべてを放り込んでおければ楽そうです

### Pros 良くなる点

- 表示関連の機能において切り替えに困らない

### Cons 悪くなる点

- ボタンとも併用なので二重にはなる

### 実現方法

ドロップダウンメニューに「表示」を追加
実装およびハイドレーションは他と同様

## VOICEVOXのバージョン

0.2.1?

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by Hiroshiba** [comment]
作るべきだと感じました！
アプリ全体の拡大率とかもいじれるようにしたい気もするのですが、現状それ用の案内場所がなかったので良い機会かなと！

利点がもう1個あって、ショートカットキーの案内ができると思います。
現在表示の切り替えはUI 上に表示するか、設定ダイアログに押し込めるかの二択なのですが、その両方でショートカットキーの案内ができないので。
（まあホバー時のツールチップに書けばいいんですけど。）

もしご入用でしたらぜひ作っちゃっていただければ！！
難しそうであればこちらで枠組みだけ作れると思います。
こちらで作るなら「ソング」と「トーク」を切り替えるだけの「表示」メニューを作る感じになるかなと。

ちなみに「ファイル」や「編集」メニューでは、一部ソングとトークで違うものが表示されるようになってます。
「表示」メニューも同じ仕組みで良さそう！
余計なお世話かもですが、`App.vue`内の`useMenuBarData`辺りを追いかけるとなんとなく仕組みがわかるかもです！

**Comment by romot-co** [comment]
@Hiroshiba 
ありがとうございます！

> 利点がもう1個あって、ショートカットキーの案内ができると思います

これは確かに！

> もしご入用でしたらぜひ作っちゃっていただければ！！
> 難しそうであればこちらで枠組みだけ作れると思います。

たしかソングリリース前のときにメニュー実装した記憶がちょっとだけある…のですが
もしわからなかったら聞くかもしれないです、適宜実装していきます…！
