### ISSUE TITLE
シング：キャラクター表示を切り替えられるようにする

### ISSUE THREAD

**Issue by romot-co** [VOICEVOX/voicevox#2203]
## 内容

キャラクター表示/非表示を簡単に切り替えられるようにしたい
かつ、切り替えは簡単に行いたい(動画などでは表示させてほしい)

### Pros 良くなる点

- 必要ない場合に邪魔にならない

### Cons 悪くなる点

- なし

### 実現方法

右下にキャラの表示・非表示トグルボタンをつける
想定としては以下の右下ピンク部分
<img width="1312" alt="スクリーンショット 2024-08-05 23 31 41" src="https://github.com/user-attachments/assets/fdc6fb4e-b594-48e2-970b-2413cad01bf4">

## VOICEVOXのバージョン

0.?.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by Hiroshiba** [comment]
場所、かわいくていい感じだと思います！！

**Comment by romot-co** [comment]
@Hiroshiba 
まずは表示メニューで切り替えられるようにしてあるので、クローズで大丈夫かと思います！
(問題なければ閉じます

**Comment by Hiroshiba** [comment]
あったしかに、「実現方法」に書いてあることとは異なりますね･･･！

Romotさん的にOKであればcloseしちゃっていただければと！
あるいは追加で変更がありそうであれば、新しくissue作るとか、タイトルを目的に沿う形に微調整するのでも良さそう。
どれでも！！ 🙏

**Comment by romot-co** [comment]
別途必要があればIssue作成する形でクローズいたします…！
