### ISSUE TITLE
ソング：Utaformatixの翻訳処理を移植する

### ISSUE THREAD

**Issue by sevenc-nanashi** [VOICEVOX/voicevox#2204]
## 内容

ここらへんの置換処理を移植したいです：https://github.com/sdercolin/utaformatix3/blob/master/core/src/main/kotlin/core/process/lyrics/LyricsReplacement.kt#L97-L129

### Pros 良くなる点

インポート時に記号とかを置き換える手間がなくなる

### Cons 悪くなる点

ないはず

### 実現方法

tracksのnotesをforで回して置き換えれば良さそう。フォーマットの区別はしなくてもいいと思います。

## VOICEVOXのバージョン

0.20.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

## その他

（なし）

**Comment by Hiroshiba** [comment]
おっとなるほどです！
ちなみに今は一部の拡張子で一部の記号？が正しく読み込めない感じでしょうか。

また知見がなく聞きたいだけなのですが、変換処理はutaformatix-tsだとちょっと都合よくない感じでしょうか？
実装的にこっちのがずっと楽とか…？

**Comment by Hiroshiba** [comment]
おーなるほどです！！変換はできるの良かった。

たしかに需要考えると確かに-tsの方への実装のが喜ばれそう感。
完全に変換できないとかなら優先度あげてエディタに実装する手もありそうだけど、そこまで…かな…？

あ！お伝えして忘れていました、issue作成ありがとうございます！

**Comment by sevenc-nanashi** [comment]
utaformatix-tsに移しました： https://github.com/sevenc-nanashi/utaformatix-ts/issues/1

こっちは閉じても良さそう

**Comment by Hiroshiba** [comment]
ではそのように･･･！
