### ISSUE TITLE
マルチトラック：stem（トラック毎）書き出し

### ISSUE THREAD

**Issue by sevenc-nanashi** [VOICEVOX/voicevox#2214]
## 内容

マルチトラックのトラック毎書き出しをしたいです。

### Pros 良くなる点

コーラス用トラックとかを用意してそっちに別のエフェクトを掛けたいのでwavファイルを分けたい、といったユースケースに対応できる

### Cons 悪くなる点

初見殺しになるかも？

### 実現方法

こんなこともあろうかとEXPORT_WAVE_FILEは`Map<TrackId, Track>`を受け取るofflineRenderTracksを呼ぶような設計にしてるので、トラック毎に`Map{ trackId => { mute: false, solo: false, ...track }}`を作ってofflineRenderTracksを呼べば良いはず。
周りのコード（レンダリング待機とか）は分けて共通化してもよさげ？

## VOICEVOXのバージョン

0.20.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

## その他

（なし）

**Comment by Hiroshiba** [comment]
isuse作成ありがとうございます！！

> Cons 悪くなる点
> 初見殺しになるかも？

お！　ちなみにこれはどういった点でしょう 👀 
機能を見つけづらそうとか･･･？

---

UIをどうしようか自明ではないので、そこだけでも練れると良いかもですね！
どういうメニュー配置にするか、そのメニューをクリックするとどういう画面が現れるか（あるいはいきなり書き出しが始まるとか）、とか思い浮かんでいたらぜひ･･･！

**Comment by sevenc-nanashi** [comment]
今思ったらそんなこともなかったです初見殺し

基本的にはトークの複数書きだしと同じ感じかな～って思ってます。ディレクトリのポップアップが出てきて、選ぶと始まる感じ。

**Comment by Hiroshiba** [comment]
> 基本的にはトークの複数書きだしと同じ感じかな～って思ってます。ディレクトリのポップアップが出てきて、選ぶと始まる感じ。

僕もこれに賛成です！！
エクスポートするトラックを選ぶダイアログを挟むことも考えられますか、とりあえずミュートになってないトラックを全部書き出しが良い気がします。
