### ISSUE TITLE
読み方&アクセント辞書の編集画面において、リセットボタンの挙動がおかしい

### ISSUE THREAD

**Issue by jdkfx** [VOICEVOX/voicevox#2229]
## 不具合の内容

<img width="1291" alt="スクリーンショット 2024-08-19 1 05 47" src="https://github.com/user-attachments/assets/5f5ce805-b451-4516-97e6-dafb7e39fe8c">

画像赤矢印のリセットボタンが、変更を加えた単語に対してリセットができない。

### 再現手順

- 単語・読みに変更を加える
- リセットボタンを押す
- モーダルのリセットを押す

### 期待動作

変更を加えた単語・読みに対してリセットすることができる

## VOICEVOXのバージョン

0.20.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [x] macOS
- [ ] Linux

**Comment by Hiroshiba** [comment]
おっと本当ですね！！！　ご報告ありがとうございます 🙇

**Comment by Hiroshiba** [comment]
`src\components\Dialog\DictionaryManageDialog.vue`コンポーネントの中で、`selectWord`と同じような処理をresetWordでもやれば解決するかも･･･？

結構簡単に解決できそうだと思うので、初心者歓迎ラベルをつけます！
もしよければどなたか是非！ 🙏

**Comment by jdkfx** [comment]
@Hiroshiba PR出します！
