### ISSUE TITLE
リファクタリング：読み方＆アクセント辞書ダイアログの右側パネルを別コンポーネントにする

### ISSUE THREAD

**Issue by jdkfx** [VOICEVOX/voicevox#2234]
## 内容

<img width="1136" alt="スクリーンショット 2024-08-20 16 04 01" src="https://github.com/user-attachments/assets/3e24d6ce-faab-46a3-8e6e-b18252519b80">

読み方＆アクセント辞書ダイアログ（以下、辞書）は、

- 辞書に登録した単語・読みの一覧など、主に表示・削除に関する処理（左側パネル）
- 辞書に登録した単語・読みの追加・編集など、主に入力に関する処理（右側パネル）

の二つの要素があります。
この二つの要素をコンポーネントに分割したいです。

### Pros 良くなる点

- 辞書ダイアログのコードが読みやすくなります
- 今後の修正や改善がやりやすくなります

### Cons 悪くなる点

- 特に思いつくものはありません

### 実現方法

- `<!-- 右側のpane -->`というコメント箇所以下からコンポーネントに分割する

https://github.com/VOICEVOX/voicevox/blob/e640cd26e89f3deb6d48cdb55ae51f326fdc7bad/src/components/Dialog/DictionaryManageDialog.vue#L119-L123

## VOICEVOXのバージョン

0.20.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

## その他

参照：
https://github.com/VOICEVOX/voicevox/pull/2156#pullrequestreview-2225512695

**Comment by Hiroshiba** [comment]
とても良いと思います！！ぜひ！！！

**Comment by jdkfx** [comment]
これやってます！
