### ISSUE TITLE
ファイルの保存ができない

### ISSUE THREAD

**Issue by moto0294** [VOICEVOX/voicevox#2238]
### 現象・ログ

windows11 22H2 でインストールしました。データを作成し音声データの保存をしようとしたら。一件の書き込みエラーによる失敗というメッセージが出ました。詳細にはファイルが見つかりませんというメッセージになっています。またプログラムを閉じようとして、保存を選択すると「ファイルが見つかりませんファイル名を確認して再実行してください」というメッセージでエラーになってします。

### 再現手順
初回インストール直後です、インストーラーモードからインストールしました
アンインストールして再度インストールしましたが同様でした。

## VOICEVOXのバージョン

0.20.0

## OSの種類/ディストリ/バージョン

- [X] Windows
- [ ] macOS
- [ ] Linux

Windows 11 Pro 64bit (windows11 22H2)

## その他
 管理者モードで実行しても同様でした

**Comment by Hiroshiba** [comment]
@moto0294 
ファイル周りはいろんな環境があるらしく、結構頻繁にエラーに関して連絡を受けます。
大体の場合は保存先を変更することで解決するので、一度デスクトップやダウンロードディレクトリ（`~/Downloads`）に書き出しを試してみてください。

**Comment by Hiroshiba** [comment]
解決したかわからないのですが、クローズ！
