### ISSUE TITLE
ソング：エンジンAPIに追加されたノートIDで仕様が大丈夫そうか確認したい

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#2246]
## 内容

エンジン側に、スコア内のノートにID を付与できるようにしてみました。
帰ってくる音素にノートIDが付与され、どのノートと結びついているかわかるようになっています。

- https://github.com/VOICEVOX/voicevox_engine/pull/1460

この API の仕様で良さそうかと、実装したことの共有も兼ねてissueにしてみました。

### 実現方法

確認できればクローズ

## VOICEVOXのバージョン

0.20.0

## その他

現在これに対応しているプレビュー版エンジンをビルドしました。

- https://github.com/VOICEVOX/voicevox_engine/releases/tag/0.21-preview.0

エンジン側でプルリクエストをマージする前に確認するべきだったのですが、忘れてマージしてしまったので･･･。

**Comment by Hiroshiba** [comment]
確か @sigprogramming さんと話していてこういう機能が欲しいという感じだった記憶です。
ちょっとお手数おかけしちゃうのですが、もし気が向いたらご確認いただけると･･･！

APIドキュメントのこのあたりの `notes` とか、返り値の `phoneme` を展開するとid項目が見れると思います 🙇 
https://voicevox.github.io/voicevox_engine/api/#tag/%E3%82%AF%E3%82%A8%E3%83%AA%E4%BD%9C%E6%88%90/operation/sing_frame_audio_query_sing_frame_audio_query_post

**Comment by sigprogramming** [comment]
APIの仕様、良さそうです！
実装ありがとうございます！

**Comment by Hiroshiba** [comment]
確認ありがとうございます！　大丈夫そうということでcloseします！
