### ISSUE TITLE
フルスクリーンを可能にする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#2251]
## 内容

VOICEVOXはフルスクリーン用の機能がほぼコーディングされているのですが、なぜか UI 上には現れません。
フルスクリーンを可能にしてあげると、ちょっと便利かもです。
おそらく結構簡単なタスクだと思うので、初心者歓迎タスクにしてみてます。

### 実現方法

フルスクリーンにする機能はelectron側にあります。
最大化ボタンもelectronの機能を使っているので、ほとんど同じような流れを取ります。
コード全体で「`maximizeWindow`」と検索すれば最大化ボタンの処理がわかると思います。

あと同じようにしてフルスクリーン用の処理を書いていって、あとは[electronの`win.setFullScreen`](https://www.electronjs.org/ja/docs/latest/api/browser-window#winsetfullscreenflag)を実行すれば良いはず。

## VOICEVOXのバージョン

0.20.0

## その他

やらなくちゃいけないことの総量は少ないのですが、画面の処理からelectronの関数を実行するまでの経路がややこしいので、意外と手間取るかもしれません。
不明なことがあれば何でもご質問ください！

**Comment by terapotan** [comment]
こちら着手してもよろしいでしょうか？
まだプロジェクトに不慣れなので、お時間頂戴するかもしれませんが、それでもよろしければ……！

また本issueに関して一点質問があります。フルスクリーンモードへ突入する契機はどのようなものを考えていらっしゃいますでしょうか。私の方で思いつく契機といたしましては、
1. F11キーなどファンクションキーを押すことでフルスクリーンに移行する
2. UIからフルスクリーンモードに切り替える
があります。

**Comment by Hiroshiba** [comment]
@tarepan issueコメントありがとうございます！　もちろん大歓迎です！！

初心者歓迎タスクラベルはついていますが、もしかしたら予想していなかった不明な点がいくつかあるかもしれません。
なのでかなり気軽にご質問いただければ･･･！

フルスクリーンモードへの移行は1と2両方が良さそうに感じました！
どちらの実装も一癖ありますが、概ねこんな感じだと思います。

* メニューバーから表示できると良さそう
*

**Comment by Hiroshiba** [comment]
すみません、コメントを間違えた上に間違えてcloseしてしまいました 🙇 

---

@terapotan issueコメントありがとうございます！　もちろん大歓迎です！！

初心者歓迎タスクラベルはついていますが、もしかしたら予想していなかった不明な点がいくつかあるかもしれません。
なのでかなり気軽にご質問いただければ･･･！

フルスクリーンモードへの移行は1と2両方が良さそうに感じました！
どちらの実装も一癖ありますが、概ねこんな感じだと思います。参考になれば。。 🙇 

* 今のVOICEVOXのコード的には、まず2を実装して1を実装するのが簡単かも
* 2のUIからフルスクリーンは、メニューバーの「表示」できると良さそう
	* [このあたり](https://github.com/VOICEVOX/voicevox/blob/f0df6a6d2c463c4e2721f132720e3bbca8846427/src/components/Menu/MenuBar/MenuBar.vue#L392-L400)！
	* ちょっとtypescriptに慣れてないと難しい書式だけど、[このあたり](https://github.com/VOICEVOX/voicevox/blob/f0df6a6d2c463c4e2721f132720e3bbca8846427/src/components/Menu/MenuBar/MenuBar.vue#L303-L310)のコードを真似るとメニューアイテムを足せるはず。。
	* あとはissue内容の`実現方法`にある感じで頑張ればなんとかなる･･･はず！！
* 1のショートカットキー
	* [同じファイルにあるregisterHotkeyForAllEditors](https://github.com/VOICEVOX/voicevox/blob/f0df6a6d2c463c4e2721f132720e3bbca8846427/src/components/Menu/MenuBar/MenuBar.vue#L530-L533)を書きつつ、あとはファイル全体検索で`新規プロジェクト`と検索して、出てきたコードのようにいろいろ書き足す
	* ちなみにmacOSのフルスクリーンショートカットは`ctrl+cmd+F`が主流とのこと

**Comment by terapotan** [comment]
@Hiroshiba 
コメントありがとうございます！　とても助かります！
ショートカットキーの実装について再度質問があるのですが……ファンクションキーの設定はどのように行えばよいかご存知でしょうか？
参考までに他のショートカットキーの設定を見たのですが、ショートカットキーにファンクションキーを使用している例はなく……具体的には下記のコードにおいて、ファンクションキーを表す文字列として何を指定すれば良いのか分からないという質問です。

`    action: "新規プロジェクト",
    combination: HotkeyCombination(!isMac ? "Ctrl N" : "Meta N"),
  },`

**Comment by sevenc-nanashi** [comment]
多分 `F11` で大丈夫だと思います。

**Comment by sevenc-nanashi** [comment]
デフォルトの設定なので新しく設定を作らないと反映されないと思います。

（あと：Draft PRでもいいのでPRを作ってくださると色々とアドバイスしやすいので可能ならお願いします）

**Comment by terapotan** [comment]
@sevenc-nanashi 
ありがとうございます！
承知いたしました、PR作成します。

**Comment by Hiroshiba** [comment]
> 依然として、Ctrl + Shift +Sが「プロジェクトを名前を付けて保存」のショートカットキーとして機能していました。

完全にカンですが、`Ctrl + Shift +S`が設定に保存されているかもしれません！
VOICEVOX内のアプリの「設定」→「ホットキー」で`プロジェクトを名前を付けて保存`の設定を確認するとチェックできる･･･かも･･･！
（更にそこでリセットすればちゃんと`F10`になるかも･･･？）

**Comment by terapotan** [comment]
@Hiroshiba 
新規でプロジェクト作成するか、ショートカットキーの設定をデフォルトに戻すと無事「プロジェクトを名前を付けて保存」がF10になりました！
ありがとうございます！

**Comment by Hiroshiba** [comment]
おっ良かったです！！
