### ISSUE TITLE
buildディレクトリを整理したい

### ISSUE THREAD

**Issue by sevenc-nanashi** [VOICEVOX/voicevox#2267]
## 内容

build/下が混沌としてきたので整理したいです。

### Pros 良くなる点

すっきりする

### Cons 悪くなる点

ないはず？

### 実現方法

<details>
<summary>軽く分類しました。</summary>

配布周り：
icons
README.txt

electron-builder周り：
afterAllArtifactBuild.js
afterNsisWebArtifactBuild.js
codesign_cleanup.bash
codesign_setup.bash
funcs.nsh
installer.nsh
installer_linux.sh

ダウンロード：
vendored
download7z.js

スクリプト：
generateLicenses.js
mergeLicenses.js
splitNsisArchive.js

その他：
patches

</details>

## VOICEVOXのバージョン

0.20.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

## その他

（なし）

**Comment by Hiroshiba** [comment]
整理したいところですね！！

個人的には、まあファイル2個ぐらいだったらディレクトリに分けなくても良いのでは、という気がしなくもないです！
というルールに従って僕も整理してみました。と言っても真似してelectron-builderディレクトリを作るだけですが！

<details>

* build/
	* README.txt
	* icons/
	* vendored/
	* patches/
	* electron-builder/　←　new !
		* afterAllArtifactBuild.js
		* afterNsisWebArtifactBuild.js
		* funcs.nsh
		* installer.nsh
		* splitNsisArchive.js
	* codesign_cleanup.bash
	* codesign_setup.bash
	* download7z.js
	* generateLicenses.js
	* mergeLicenses.js
	* installer_linux.sh

</details>

（コードサイン系と`installer_linux.sh`を`electron-builder`から外してみました）
うーーーーーーーん。
`scripts`は結局そこが太っていく気もするんですよねぇ。。
`codesigin/`と`licenses/`はアリ････かも･･･？これでファイル数は半分ぐらいになるはず。。

**Comment by sevenc-nanashi** [comment]
そもそもbuild/ディレクトリ自体がなんかビルド成果物感があるんですよね

**Comment by Hiroshiba** [comment]
あ、ですね！
というかビルドに関係ないものも含まれているので、`tools`とかにするのが良いのかな～と。

**Comment by Hiroshiba** [comment]
Discordで会話していたので転載。
https://discordapp.com/channels/879570910208733277/893889888208977960/1307543543992291408

今まとまっている内容：

* build/の他にtools/を作る
* build→toolsの依存を認める

今迷ってる内容：

* vendoredをどこに置くか

**Comment by sevenc-nanashi** [comment]
Discord転記：ルート直下にvendoredを置いてgitignoreする （ https://canary.discord.com/channels/879570910208733277/893889888208977960/1307975125252968508 ）
