### ISSUE TITLE
ソング: 再生ヘッドのクリックでの変更位置をスナップにあわせる

### ISSUE THREAD

**Issue by romot-co** [VOICEVOX/voicevox#2295]
## 内容

再生ヘッドの位置をクリックで変更できますが
スナップに沿わないため使いづらいことがあるのを解決します

多くの場合：
クリックで変更でコピペ基準や特定位置からの再生を意図しますが
微妙にずれた位置になり困ることがあります

どのような仕様がよいかはこちらで議論できればと思います

### Pros 良くなる点

- コピペや再生位置や今後のループ範囲などプレイヘッドを基準にしたい場合に使いやすくなる

### Cons 悪くなる点

- スナップが1/2など大きな場合に使いづらい可能性

### 実現方法

ガイドラインやループなどと同様を想定

## VOICEVOXのバージョン

0.2.1？

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

macOS 14

## その他

- 大きな値のスナップの場合は1/8程度を上限にしてもいいかもしれない？

**Comment by Hiroshiba** [comment]
便利そう！！

> 大きな値のスナップの場合は1/8程度を上限にしてもいいかもしれない？

たしか大きなスナップだったとしても小さめの拍子でグリッド線描かれてましたよね。1/4かな？
それに合わせておくと直感的寄りかもとか思いました！

**Comment by romot-co** [comment]
@Hiroshiba 
ありがとうございます、こちら手が空いたら実装してみます…！
