### ISSUE TITLE
ソング：再生デバイスを変更できるようにする

### ISSUE THREAD

**Issue by sigprogramming** [VOICEVOX/voicevox#2300]
## 内容

トークは設定で再生デバイスを変更できます。
ソングも変更できると便利だと思います。

### Pros 良くなる点

- 再生デバイスを変更できるようになる

### Cons 悪くなる点

- 特になし

### 実現方法

[`AudioContext.setSinkId()`](https://developer.mozilla.org/ja/docs/Web/API/AudioContext/setSinkId)を使うことで実現できると思います。

## その他

- トークとソングどちらの設定なのかが分かりにくくなっているので、そろそろ設定を分けていった方が良さそう

**Comment by X-20A** [comment]
まだコードは確認してないのですが、トークとソングそれぞれで再生デバイスを設定するより、一つの設定に一本化したほうが分かり易いように思います。それぞれ別のデバイスから再生したいという需要があれば別ですがちょっと想像しづらいかなと。
ともあれ、現状のソングに適用されない仕様は不自然だと思います。

**Comment by Hiroshiba** [comment]
僕もどちらも同じ設定が適用される形（トークソング共通設定的な）がわかりやすそうに思いました！

> ともあれ、現状のソングに適用されない仕様は不自然だと思います。

完全に同感です！！
今の設定がソングにも適用されるようになると良さそう･･･！！

**Comment by sigprogramming** [comment]
こちら解決だと思うのでcloseします！
