### ISSUE TITLE
ソング：鉛筆カーソルの向きを矢印カーソルと同じにする

### ISSUE THREAD

**Issue by sigprogramming** [VOICEVOX/voicevox#2304]
## 内容

現在、鉛筆カーソルと矢印カーソルの向きが一致しておらず、カーソルが切り替わるときに違和感を感じます。
一致させた方が良さそうです。

### Pros 良くなる点

- 違和感がなくなる

### Cons 悪くなる点

- 特になし

## その他

- VoiSonaのペンカーソルは矢印カーソルと同じ向きになっていました

**Comment by Hiroshiba** [comment]
言われてみれば、ノートを書き始めるとカーソルがペンに変わるので、たしかに違和感あるかもですね！

@romot-co さん的にどうでしょう 👀

**Comment by romot-co** [comment]
@sigprogramming @Hiroshiba 
ありがとうございます、こちらおっしゃる形に変えていいかと思います！

(直接関係ないですが: カーソルもライブラリ使うのとMaterial Iconのバージョン古くて無いものがあるのでアップデートしたいなどと

**Comment by Hiroshiba** [comment]
こちら、デフォルトが鉛筆カーソルになって優先度が上がっているので、次のアップデートリリースまでにこちら変更しておこうと思います！
ちょっとやっちゃおうと思います！

**Comment by Hiroshiba** [comment]
PR作りました！
エンジンを起動している状態（or製品版VOICEVOX.exeを起動している状態）で

https://voicevox.github.io/preview-pages/preview/pr-2400/editor/

にアクセスすれば確認できると思います。

以下個人的な感想：

* ペンを上に持つのは意外と違和感があった
* でも左下にペンがある状態よりは操作しやすい気がする
* しばらく使ってるとあまり違和感なくなった、慣れの問題だったかも
* ちなみにVoisonaもペンマークは左上が支点

**Comment by sigprogramming** [comment]
@Hiroshiba 
PRありがとうございます！
試してみましたが良さそうに感じました！
