### ISSUE TITLE
ソング：再生位置を小節・拍が分かる形式で表示するようにする

### ISSUE THREAD

**Issue by sigprogramming** [VOICEVOX/voicevox#2305]
## 内容

現在、再生位置を`分:秒.ミリ秒`の形で表示していますが、何小節の何拍を再生しているかが分からないので、小節や拍が分かる形で表示した方が良いかもです。

### Pros 良くなる点

- 何小節の何拍を再生しているかが分かるようになる

### Cons 悪くなる点

- 再生位置の表示形式が変わる
  - 以前の形式でも表示できると良さそう

### 実現方法

小節・拍が分かる形式で表示する処理を追加する。

## その他

**Comment by Hiroshiba** [comment]
（ただのコメントです）

････････もしかしたら初学者の方にとっては絶対時間のほうが良かったりするかもですね！！
「１分くらいのとこちょっと変かも」みたいな感じで手直しそうだなと。

いや、作曲中は小節・拍が良くて、完成したあとは時間のが良いとか･･･？
カバーは元曲が最初から完成してるから時間のが良いみたいな･･･。

全然結論出てないですが、思ったことメモまで･･･！

**Comment by sigprogramming** [comment]
> ････････もしかしたら初学者の方にとっては絶対時間のほうが良かったりするかもですね！！
「１分くらいのとこちょっと変かも」みたいな感じで手直しそうだなと。

確かに初学者は秒の方が位置を把握しやすいかもですが、これは慣れもあるかもです。
小節・拍は最初は難しく感じるかもですが、慣れてくると便利に感じる…かも…？

> いや、作曲中は小節・拍が良くて、完成したあとは時間のが良いとか･･･？
カバーは元曲が最初から完成してるから時間のが良いみたいな･･･。

作曲中は小節・拍が良いと思います。
DAWに慣れている人は、ずっと小節・拍で表示でも問題ないと思います（たぶん）。
時間（秒）は、映像と合わせたり、各セクションの時間や曲の長さを知りたいときにあると便利、作曲中は少し不便、という感じだと思います。

**Comment by romot-co** [comment]
@sigprogramming @Hiroshiba @sevenc-nanashi 
(Issueの方にまとめてで)

ありがとうございます、これも慣れや目的によって異なる案件な気もしています…！
実装いただいた形で選択できれば大丈夫そうです！

---

当初の秒表示の理由:

- 多くの人にとって音楽プレイヤーやスマホ動画編集などで親しんでいる形式(な気がした)
- 情報量で圧迫したくなかった(再生ボタンとともに現状ほどデカい必要はないですが、とっつきやすく見える…気がした)

個人的には:

- 小節・拍はルーラーで見がち
- MIDIベースで作曲中は小節・拍がよい / 波形ベースで考える時などは秒もほしい

今後変えるなら:

- 右クリックに頼らずどこかにドロップダウンや単位切り替えなりで選択できるようにすることを明示
- フォーマットは方言がいくつかあるので今後必要が出たら選択できるようにする

---

各ソフトのデフォルトをいちおう見てみた

### SynthesizerV

ない

### VoiSona

分:秒:ミリ秒
<img width="307" alt="スクリーンショット 2024-10-20 13 31 04" src="https://github.com/user-attachments/assets/57ddf9ec-948e-442f-862b-c47fddf80042">

### GarageBand

小節.拍 (選択可能)
<img width="413" alt="スクリーンショット 2024-10-20 13 32 14" src="https://github.com/user-attachments/assets/5df2ff00-f8ef-4922-b1e8-398d95c6fe48">

### GarageBand(iOS)

ない

### Cubase

小節.拍.ティック (選択式)
<img width="173" alt="スクリーンショット 2024-10-20 13 39 24" src="https://github.com/user-attachments/assets/0db00f6a-09ad-4fee-b463-b643fc3fb4e6">

### Studio One

小節.拍.100分 + 分:秒:ミリ秒
<img width="571" alt="スクリーンショット 2024-10-20 13 31 47" src="https://github.com/user-attachments/assets/4bc63956-71c4-4cea-b943-a07dbbe4ca4f">


### Ableton Live
小節.拍.16分
<img width="212" alt="スクリーンショット 2024-10-20 13 33 16" src="https://github.com/user-attachments/assets/a735d7e8-24ce-411b-af5b-52b0ca8d4c3c">

### Bitwig
小節.拍.100分 + 分:秒:ミリ秒
<img width="348" alt="スクリーンショット 2024-10-20 13 32 42" src="https://github.com/user-attachments/assets/17d91de7-fa27-4d83-8815-af39a23dce47">

### Reaper
小節.拍.100分

※ ななしさんありがとうございます

**Comment by Hiroshiba** [comment]
僕もデフォルトは分秒推しです。
ちなみに自分は1ヶ月作曲やってて小節と拍を意識したことがなかったです。。。太線（小節）の位置くらいは目安にしてたかも。。

どっちも表示もなるほどな～～～と思いました。多分どっちも表示したいって人もいそう。（そして面積的に難しそう。。。。。）
