### ISSUE TITLE
need ios version

### ISSUE THREAD

**Issue by mottzz87** [VOICEVOX/voicevox#2340]
## VOICEVOXのバージョン

0.?.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by sevenc-nanashi** [comment]
Actually the development of mobile version is on roadmap, and the repository and task list exists: https://github.com/VOICEVOX/voicevox_mobile/issues/28

It's not actively developed because developers are focusing on sing editor.

I'm closing this issue as duplicate.
