### ISSUE TITLE
ソング・TAB時に単体歌詞が選択できない

### ISSUE THREAD

**Issue by shuntia** [VOICEVOX/voicevox#2345]
## 不具合の内容

ソングで単体ノーツを選択し、TABで順番に歌詞を入力すると、四回に一回、定期的に、規則性を持って、ハイライトが行われません。

### 現象・ログ
https://github.com/user-attachments/assets/15515b23-c2f1-47e9-8ed3-fa3c0f679414

### 再現手順

ソングを開き、ノーツを置く。
クリックして歌詞を出す
ひらがな一文字入力、TABをくりかえす
4n回目にハイライトが実行されない

### 期待動作

毎回歌詞がハイライトされる

## VOICEVOXのバージョン

0.21.1

## OSの種類/ディストリ/バージョン

- [x] Win11 23H2 x64
- [ ] macOS
- [ ] Linux

**Comment by sigprogramming** [comment]
ご報告ありがとうございます！

こちら再現できました。「レレ」など、同じ歌詞が続く場合に起こるようです。
おそらく
https://github.com/VOICEVOX/voicevox/blob/b1596965fb0161451e968c02a23feff209e3e5be/src/components/Sing/SequencerLyricInput.vue#L92-L93 が
https://github.com/VOICEVOX/voicevox/blob/375aaea7e89ecf324d20b8dc0a6a2353b98f1272/src/components/Sing/SequencerLyricInput.vue#L96-L97 に変わったのが原因で、
watchは同じ値の場合はコールバックが呼ばれないので、それで`select`が呼ばれなくなっているのだと思います。

以前の「オブジェクトの参照をwatch」に戻すと直ると思いますが、
参照は分かりにくいので、「`noteId`をwatch」にしても良いかもです。

**Comment by terapotan** [comment]
> ご報告ありがとうございます！
> 
> こちら再現できました。「レレ」など、同じ歌詞が続く場合に起こるようです。 おそらく
> 
> https://github.com/VOICEVOX/voicevox/blob/b1596965fb0161451e968c02a23feff209e3e5be/src/components/Sing/SequencerLyricInput.vue#L92-L93
> 
> が
> https://github.com/VOICEVOX/voicevox/blob/375aaea7e89ecf324d20b8dc0a6a2353b98f1272/src/components/Sing/SequencerLyricInput.vue#L96-L97
> 
> に変わったのが原因で、
> watchは同じ値の場合はコールバックが呼ばれないので、それで`select`が呼ばれなくなっているのだと思います。
> 以前の「オブジェクトの参照をwatch」に戻すと直ると思いますが、 参照は分かりにくいので、「`noteId`をwatch」にしても良いかもです。

@sigprogramming @Hiroshiba 
原因解析ありがとうございます。
こちらの原因解析に沿って、不具合修正を行いましたので、ご確認いただけると幸いです。
作業重複になっていましたら、申し訳ないです。

**Comment by sigprogramming** [comment]
@terapotan 
修正プルリクありがとうございます！助かります！

**Comment by Hiroshiba** [comment]
- https://github.com/VOICEVOX/voicevox/pull/2386

で解決したと思うのでcloseします！
@shuntia さん、@terapotan さん、ありがとうございました！
