### ISSUE TITLE
ソング：Speakerの初期化を`SET_SINGER`で行わないようにする

### ISSUE THREAD

**Issue by sigprogramming** [VOICEVOX/voicevox#2359]
## 内容

現在、`SET_SINGER`でSpeakerの初期化（`INITIALIZE_ENGINE_SPEAKER`の実行）を行っていますが、Speakerの初期化中はUIがロックされます。
これが結構UXを下げているように感じました。（特にエディタ起動直後）
また、ソングエディタでSpeakerの初期化を前もって行う必要はない気がします。（レンダリングに時間がかかることを前提とした設計・UIになっている）
なので、Speakerの初期化を`SET_SINGER`で行わないようにするのが良いかなと思います。

### Pros 良くなる点

- 起動直後やシンガー切り替え直後にUIがロックされなくなる
  - Speakerの初期化の完了を待つ必要がなくなる

### Cons 悪くなる点

- Speakerの初期化をレンダリング時に行うことになり、（初回の）レンダリング時間が長くなる

### 実現方法

`SET_SINGER`の
```ts
void actions.SETUP_SINGER({ singer: { engineId, styleId } });
```
を削除する。

## その他

**Comment by Hiroshiba** [comment]
確かに不要そうだと感じました！！

`INITIALIZE_ENGINE_SPEAKER`側にUI_LOCKするかどうかのフラグを持たせて、トーク側からはロックし、ソング側からはロックしないようにするのが UX 的には最高かもです。

エンジン側には初期化をリクエストしておきつつUI は触れるようにしておく感じになるかなと。
ちなみにエンジン側はセマフォ？してるので、続けてリクエストを送っても送らなくても大丈夫なようになっています。

（ついでに`INITIALIZE_ENGINE_SPEAKER`の`speaker`部分を`character`に名前変更したいかも 😇 ）
