### ISSUE TITLE
ソングのスクロールバーのところでマウスカーソルが変わらない

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#2394]
## 不具合の内容

タイトルの通りです。
ちょっとこれがバグなのかわからないのですが、珍しいけどな気がするのでメモがてらissueを作ってみました。

### 再現手順

編集モード状態でスクロールバーにカーソル合わせても、よく見かけるマウスカーソルのマークにならない。

### 期待動作

スクロールバーの上ではよく見かけるマウスカーソルのマークになる･･･？

## VOICEVOXのバージョン

（mainブランチ）

**Comment by Hiroshiba** [comment]
@romot-co (cc @sigprogramming )
これ仕様どうあるべきかコメントいただけると心強いです！！

**Comment by romot-co** [comment]
@Hiroshiba 
こちらスクロールバー上は標準カーソルになっているのが妥当かと思います！
確認して修正いたします…！
