### ISSUE TITLE
トラックリストを開くとツール選択欄がかぶってしまう

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#2395]
## 不具合の内容

トラックリストを開くとツール選択ボタンがかぶってしまうことに気づきました。
（今のmainブランチで起こってる事象です）

![image](https://github.com/user-attachments/assets/57e446dc-8b96-4116-b04d-d690a0f0b1d6)

## その他

おそらくposition: absoluteになってるから･･･？

**Comment by Hiroshiba** [comment]
@romot-co 何度もメンションすみません、とりあえずご共有まで･･･！ 🙇

**Comment by romot-co** [comment]
@Hiroshiba 
失礼しました！修正します🙇
