### ISSUE TITLE
読みをクリックするときに間違えてsplitしてしまう

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#241]
## 内容

読みをクリックすると読みを変更できますが、間違えてsplit-cellをクリックしがちです。

![image](https://user-images.githubusercontent.com/4987327/134019750-7e6f7ea5-861d-4836-8e51-cd0f322ff469.png)
↑このテキスト部分をクリックすると読み変更、青い部分だとsplitになる

split-cellをアクセントの線が表示されている部分に移動すればミスもなくせる気がしています。

### 実現方法

split-cellをAudioAccentに移動する。

（イントネーション欄でsplitできなくなるけど、そもそもする人がかなり少なそうなので影響はほぼ無いかなと思っています）

**Comment by jdkfx** [comment]
こちら取り組もうと思っております！

**Comment by Hiroshiba** [comment]
@jdkfx おお！！　ぜひよろしくおねがいします！！

こちらのissueが少し近いので参考になるかもしれません。

- https://github.com/VOICEVOX/voicevox/issues/777
- https://github.com/VOICEVOX/voicevox/issues/453

**Comment by jdkfx** [comment]
@Hiroshiba 技術力不足で解決策を見つけられなかったため，こちらのアサインを外していただけると幸いです．

**Comment by Hiroshiba** [comment]
承知しました！ご検討いただきありがとうございます･･･！
