### ISSUE TITLE
最新版Windows(Windows11 24H2)で動かない

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#2449]
## 不具合の内容

最新版Windows(Windows11 24H2)で動かないという報告をいただきました。

ref: https://x.com/tanep3/status/1872807342737362957

これからどんどん報告があがってくるはずなのと、かつ動かないのであればかなり問題なので、優先度を高く設定しています。
検証報告・PR募集中です。

### 現象・ログ

WMICコマンドを使ってる部分があり、そこがエラーになってると思われます。
https://github.com/VOICEVOX/voicevox/blob/4cab1c584b229d5ed0572efc84989c115f3478b6/src/backend/electron/portHelper.ts#L155

### 再現手順

再現確認はまだです。ご報告お待ちしています。

### 期待動作

エラーが出ない。正常起動する。

## VOICEVOXのバージョン

0.22.3

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

## その他

Discordでの会話 @raa0121 @sevenc-nanashi 

```
らぁ/raa0121 — 今日 17:16
プロセス確認系ですかね？
らぁ/raa0121 — 今日 17:23
https://github.com/VOICEVOX/voicevox/blob/4cab1c584b229d5ed0572efc84989c115f3478b6/src/backend/electron/portHelper.ts#L155
あってた
ヒホ — 今日 17:53
ははーーーーーーーーんなるほど！！！！！！！
最新版windowsで動かないということはたぶんhotfixレベルの案件な気がする！
これなにに置き換えればいいんだろ
とりあえずissue作ろ～っと
らぁ/raa0121 — 今日 17:55
tasklist とかですかねー
名無し｡ — 今日 17:56
netstat？
```

**Comment by raa0121** [comment]
修正できそうなので、対応します。
