### ISSUE TITLE
CPU版でGPUモードに切り替えようとするときに、CPU版であることを気付けるようにする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#298]
## 内容

実はCPU版の作成が可能になっているのですが、その場合でもCPU/GPUモード切替のUIが普通に存在します。
ユーザーがCPU版を使っていることを忘れた状態で、なぜかGPUモードを使おうとすると、原因にたどり着けないかもしれません。
なので、何らかの方法でCPU版であることを気づけるようにしたいです。

ただ、どうやって自分のビルドモードを知れるようにするかが思い付けていません。

ref: https://github.com/Hiroshiba/voicevox/pull/264

**Comment by Hiroshiba** [comment]
将来的にコアに対応デバイスがわかるAPIが生えるので、それを使うのが一番良さそうです。
https://github.com/Hiroshiba/voicevox_core/issues/16

ただ、コアに対応を入れた後、コアをプレリリースし、エンジンにAPIを生やしてやっとソフトウェアに対応を入れられるので、次0.7.0のリリースに間に合わないかもしれません。
先に別の方法（一時的に.envにONLY_CPUフラグを作るとか？）を実装すると良いかもしれません・・・。

**Comment by Apple-Yuki** [comment]
こちらでも言及しましたが、Mac版に関しては、GPUボタンは非表示がいいかと。

https://github.com/VOICEVOX/voicevox/issues/576#issuecomment-994763478

**Comment by Hiroshiba** [comment]
エンジン側にAPIが実装されているので、お手軽なタスクになりました！

- https://github.com/VOICEVOX/voicevox_engine/pull/299

**Comment by tunamaguro** [comment]
できるかどうかわかりませんがちょっとやってみます

**Comment by Hiroshiba** [comment]
@tunamaguro ありがとうございます！！

こちらのタスク、昔はエンジンが１つだけで簡単だったのですが、今はマルチエンジンが実装されたため複雑になっている気がします。
もし不明な点や相談すべき点などあればお気軽にコメント頂ければ！！

**Comment by tunamaguro** [comment]
今日考えたことのメモです。
- GPUが使用可能かどうかかのAPIはエンジンに実装されている([レスポンス](https://github.com/VOICEVOX/voicevox/blob/main/src/openapi/models/SupportedDevicesInfo.ts#L21-L40))
- エンジンにリクエストを投げるためには`ENGINE_CONNECTOR`が必要([参考1](https://github.com/VOICEVOX/voicevox/blob/main/src/store/audio.ts#L1114-L1143) [参考2](https://github.com/VOICEVOX/voicevox/blob/main/src/store/proxy.ts#L12-L34))
- つまるところ、登録されているすべての`engineId`を取得して各エンジンに対してGPU対応可能か確認すればよい気がする 
  - 上のような方法で行くと、エンジンAはGPU可、エンジンBはGPU不可みたいなことがあると実現できなさそう
  - 各エンジンごとにCPUかGPUかを選択できるようにする?
- GPU不可のときのUIは単純に`disable`にするだけでよいか?何かしらのメッセージを表示するか?
　- `disable`だとGPUにトグルできないことが分かりにくいかも 
`disable = true`
![image](https://user-images.githubusercontent.com/79092292/213919567-1a21b2ce-b4e5-4337-a7bf-21688ea59468.png)
`disable = false`
![image](https://user-images.githubusercontent.com/79092292/213919644-5c45bea6-d96f-4827-8f3a-b987043371a6.png)

明日以降考えること
- [ ] すべての`engineId`をどこから取得するか
- [ ] GPU不可のときの表示をどうするか

**Comment by Hiroshiba** [comment]
検討と考えのご共有ありがとうございます！！方針いい感じに思います！！

disableにするの良さそうに思います。
ジャストアイデアですが、マウスホバーしているときになぜdisableになっているのか理由を描いてあげるとなかなか良いUXかもです！

ちなみにエンジンごとに変更するというのは @raa0121 さんが検討中だったりします！
https://github.com/VOICEVOX/voicevox/pull/1136
なのでこのissueではエンジン全体だけの変更を考えつつ、先に↑がマージされた場合は各エンジン切り替えのことも考えるとかが方針としてやりやすいのかな？と思いました。
参考になれば幸いです！

**Comment by tunamaguro** [comment]
ご意見ありがとうございます!

確かに何処かになぜGPUに変えられないかの理由があったほうが親切だと思うので、ツールチップなどで表示したいと思います。

**Comment by tunamaguro** [comment]
こちらのプルリクエスト出しました!! #1140 
ご確認お願いします!!

**Comment by Hiroshiba** [comment]
こちら完了済みのタスクなのでcloseします！
@tunamaguro さんありがとうございました！！
