### ISSUE TITLE
ダークモードデザインを作る

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#316]
## 内容

全体的に明るい色を起用していますが、昨今のダークモード欲を満たすためにも実装しても良さそうだなと思いました。

## VOICEVOXのバージョン

0.?.0

**Comment by sevenc-nanashi** [comment]
#849 で漏れてました、閉じてもよさそうな気がします

**Comment by Hiroshiba** [comment]
ほんとですね！closeします！！
