### ISSUE TITLE
長文の場合、読んでいる箇所と下部[アクセント/イントネーション]を同期して横スクロールして欲しい

### ISSUE THREAD

**Issue by arigayas** [VOICEVOX/voicevox#332]
## 内容
例えば、
`寿限無、寿限無、五劫の擦り切れ、海砂利水魚の、水行末・雲来末・風来末、喰う寝る処に住む処、藪ら柑子の藪柑子、パイポ・パイポ・パイポのシューリンガン、シューリンガンのグーリンダイ、グーリンダイのポンポコピーのポンポコナの長久命の長助`
みたいな長文を貼り付けた場合に　**読んでいる箇所**　と　**下部[アクセント/イントネーション]**　を同期して横スクロールして欲しいです。

_例文は長すぎる名前にしました。_

### Pros 良くなる点
手動でスクロールする必要がなくなります。

### Cons 悪くなる点
わかりません。

## VOICEVOXのバージョン
0.7.0

## OSの種類/ディストリ/バージョン
*   Windows 10 Pro 64bit (20H2)

## その他
読み上げ中に VOICEVOX のウィンドウのリサイズを行うと処理が重くなる可能性があるかもしれません。

**Comment by Hiroshiba** [comment]
スクロール機能は実装されたのでcloseします！
