### ISSUE TITLE
CPU版のelectron-storeの保存先がvoicevox-cpuなのをGPU版と合わせたい

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#337]
## 内容

CPU版の自動ビルドは問題なく稼働していそうでした！

（2021/10/11  0:28現在ミスがあって再ビルド中ですが、こちらです↓）
https://github.com/Hiroshiba/yukarin-tts-software/actions/runs/1326080659

CPU版を動かしてみると、electron-storeなどの保存先が`%appdata%/voicevox-cpu`でした。
こちらをGPU版に合わせてVOICEVOXにしておくと、将来的に対応などが簡単になるかなと思いました。

## VOICEVOXのバージョン

0.7.2

## その他

CPU版の自動ビルドをするプルリクエストが参考になるかもです https://github.com/Hiroshiba/voicevox/pull/306

@aoirint 実現可能そうでしょうか 👀

**Comment by aoirint** [comment]
`package.json` の `name` （`packageName`） を書き換えているのがそもそもの原因と思いました。
これは、GitHub Releaseにアップロードする7zファイルの名前を重複させないために書き換えています。

レジストリにインストール情報が書き込まれていそうですが、そちらでも同じこと（別々に記録）が起きているかもしれないと思いました（こちらは`appId`かもです）。

7zファイルの名前以外への影響を抑えるには、`packageName`を変更しない方法で、7zファイルの名前を変更するのが一番いいのかなと思いました。

Electron Builderの他のオプションで7zファイルの名前を書き換える方法があればいいのですが、
以下のようにロジックを追うと、結合済みの7zファイルの名前を`packageName`を介さずに変更するには、
Electron Builderを書き換える必要がありそうに思いました。

- 7zファイルの名前決定: https://github.com/electron-userland/electron-builder/blob/7327025ad0a63ec999ade43347e5c8ffea90e08b/packages/app-builder-lib/src/targets/nsis/NsisTarget.ts#L90
    - `${packager.appInfo.sanitizedName}-${packager.appInfo.version}-${Arch[arch]}.nsis.${format}`
- AppInfo.sanitizedName: https://github.com/electron-userland/electron-builder/blob/7327025ad0a63ec999ade43347e5c8ffea90e08b/packages/app-builder-lib/src/appInfo.ts#L132
    - `sanitizeFileName(this.name)`
- AppInfo.name: https://github.com/electron-userland/electron-builder/blob/7327025ad0a63ec999ade43347e5c8ffea90e08b/packages/app-builder-lib/src/appInfo.ts#L122
    - `this.info.metadata.name!`
        - `packageName`を参照している?
- AppInfo.metadataの読み込み: https://github.com/electron-userland/electron-builder/blob/7327025ad0a63ec999ade43347e5c8ffea90e08b/packages/app-builder-lib/src/packager.ts#L328

**Comment by Hiroshiba** [comment]
ユーザーデータのディレクトリを、起動後に修正する方法もありそうです。
こちらで手軽に解決してしまう手もありそうです

- https://github.com/Hiroshiba/voicevox/pull/525

**Comment by Hiroshiba** [comment]
結構声が聞こえてくるので、早めに修正しておくと将来の悲劇を救えるかも。優先度を１段階上げたいと思います。
https://twitter.com/unyassu_nnn/status/1585224875786276865

**Comment by sabonerune** [comment]
一通り調べてみました。
Electronのアプリケーションの名前をコード内で`voievox`に変更してしまうのが一番楽な気がします。
https://www.electronjs.org/ja/docs/latest/api/app#appsetnamename

また、調査中に`electron-log`がElectronの`userData`と`logs`の場所を無視しているため開発版のログが製品版のログと混ざっていることが分かりました。
別途`electron-log`側で設定をすれば解決します。
https://github.com/megahertz/electron-log/blob/master/docs/file.md#resolvepath-variables-pathvariables-message-logmessage--string

その他、デフォルトのログの保存場所が必ず作成されてしまう`electron-log`の既知の問題があります。
- https://github.com/megahertz/electron-log/issues/301

**Comment by Hiroshiba** [comment]
調査ありがとうございます！！！
アプリ内でアプリ名を設定すれば良いというのは盲点でした、良いと思います！！！

`electron-log`のパス指定方法もなるほどです。とても助かります。
デフォルトのログディレクトリが作られてしまう件はまあ一旦仕方ないかなという気持ちです！

**Comment by sabonerune** [comment]
すみません、このコード何に使っているか分かりますか？
https://github.com/VOICEVOX/voicevox/blob/1d1d7f60202330ef61dd89b2749d86c4baceac99/src/background.ts#L1025-L1032

**Comment by Hiroshiba** [comment]
@sabonerune `getAppInfos`でコード内検索すると結構色々出てきました。ヘルプダイアログとか。

**Comment by sabonerune** [comment]
ありがとうございます。
`GET_APP_INFOS`で検索していました。
