### ISSUE TITLE
Macユニバーサルアプリ版のリリース：Release a Mac Universal App version.

### ISSUE THREAD

**Issue by Apple-Yuki** [VOICEVOX/voicevox#348]
## ダウンロード（VOICEVOX for Mac）
Mac版リリースのVOICEVOXを今までで最高のものにするためにご協力ください。
GitHubのメンバーは、プレリリースバージョンをお試しいただき、お気付きの点をこちらのイシューでお知らせいただくことで、ソフトウェアの構築に参加していただくことができます。

⚠️ベータ版ソフトウェア（プレリリース、プレビューやシードを含む）とは、一般に向けたリリースがまだ行われていない、開発中のソフトウェアを指します。プレリリース版はバグが残っている可能性が正式版より高く、 場合によっては意図的に残している可能性があります。

**ご利用の方は[こちら](https://github.com/PickledChair/voicevox/releases/download/0.9.3-pickledchair-4/VOICEVOX.0.9.3.dmg)よりVOICEVOXをダウンロードしてください。**

**VOICEVOXを初回利用時は設定のセキュリティよりVOICEVOXの実行の許可が必要です。**

### 議論について

ベータ版ソフトウェアの議論は[Mac版の自動ビルド・リリース #399](https://github.com/VOICEVOX/voicevox/issues/399)にて実施中です。

## Improvement contents

Please release a Mac Universal App version.

### Implementation Methods

This is achieved by making VOICEVOX ENGINE and VOICEVOX Software a universal App. If possible, it would be even better if it could be made into one App like Open Broadcaster Software (OBS).

## Version of VOICEVOX

I don't know, I can't install it now.

## OS type/district/version

*   macOS Monterey

**Comment by Hiroshiba** [comment]
Issue作成ありがとうございます！

mac対応で最も課題になっているのは、[VOICEVOX CORE](https://github.com/Hiroshiba/voicevox_core)のビルドに必要なGithub Actions上でのcudaインストール部分です。
coreのビルドでのcudaインストールは[こちらのGitHub Action
](https://github.com/Jimver/cuda-toolkit/tree/6c431511cdbaef1174130412c0a245a6c205f883)に頼っていますが、ubuntuとwindowsはサポートしている一方でmacがサポートされていません。
ここさえ解決できれば、mac版の作成が可能になると思います。

**Comment by Apple-Yuki** [comment]
NVIDIA® CUDA Toolkit 11.4 Update 1 no longer supports development or running applications on macOS. While there are no tools which use macOS as a target environment, NVIDIA is making macOS host versions of these tools that you can launch profiling and debugging sessions on supported target platforms.


https://developer.nvidia.com/nvidia-cuda-toolkit-developer-tools-mac-hosts#history

**Comment by Hiroshiba** [comment]
そもそもCUDAはmacOSをサポートしなくなったんですね！全く知りませんでした。
では、CPUのみバージョンのmacOSビルドを考えてみます。

**Comment by Apple-Yuki** [comment]
Unfortunately CUDA 10.2 only supports up to macOS 10.13, see the documentation: https://docs.nvidia.com/cuda/archive/10.2/cuda-installation-guide-mac-os-x/index.html

This was the latest CUDA version to support macOS, and unfortunately macOS 10.13 is not available in GitHub actions, see: https://github.com/actions/virtual-environments/issues/461

So until Nvidia updates their CUDA toolkit to support a recent version of macOS this won't be possible to do in GitHub actions :(

**Comment by Apple-Yuki** [comment]
#399  comment forked.

[macOS用アプリケーション (.app) とdmgファイル (.dmg) の自動ビルド #570](https://github.com/VOICEVOX/voicevox/pull/570)の実行テストですが動作自体は以下の通りです

・Apple Silicon M1、M1 Pro、M1 Maxでの動作は問題ありませんでした。（Rosetta環境のみ）

[動作の状況や書き出しデータはこちらからご覧ください。](https://app.box.com/s/jmxa4js18m0jpn6mb0cthk7u5pjxq0ie)

なお、以下のイシューや改善点があります。

- 設定画面のエンジンタイプでCPUからGPUに変更し、再起動された後CPUタイプへ復帰の際、**アプリがクラッシュする**。（以前のバージョンからあるものですけど）
- 設定画面のコマンド登録画面で`⌘Command`キーを押すと名称が`Meta`となる。（`⌘Command`＋`E`などの複数登録が不可）
- 設定画面などを開いてる際、上のコマンドバーの操作を一切受付ない。（仕様としてもユーザーエクスペリエンス的に直感的にしておいた方がいいかと。）
- 初期起動のキャラの声のイントネーション未選択時に「次へ」をグレーアウトせず、警告文でユーザーに知らせるといいかと思います。
もしくは、デフォルトイントネーションを決めておく。

**Comment by Hiroshiba** [comment]
こちらはユニバーサル化に関して議論するissueにして、macでの動作に関しては #399 でやりとりできればと思います！
