### ISSUE TITLE
セルを入れ替え可能にする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#369]
## 内容

今のUIだとセリフが入れ替えられず、VOICEVOX上でプロットを書くタイプの作成方法だと結構不便です。
入れ替え可能にできると作業効率がぐっと上がると思います。

### Cons 悪くなる点

UIどうするかが難しそう

### 実現方法

CeVIOの方式だと、
「クリックしてセルを選択」したあと、「ctrl+Xなどで切り取り」するか、「ドラッグアンドドロップで移動」です。
まずセルを選択する機能が必要だと思います。
（セルをアクティブにする機能はありますが、いずれマルチ選択を実装することになると思うので、最初から分けたほうが良いと思います）

## その他

要望の声 https://twitter.com/anon10779562/status/1450414896705798144

**Comment by Segu-g** [comment]
やってみたいと思います

**Comment by Hiroshiba** [comment]
実装されたのでcloseします！！ thx @.Segu-g
