### ISSUE TITLE
Mac版の自動ビルド・リリース

### ISSUE THREAD

**Issue by Apple-Yuki** [VOICEVOX/voicevox#399]
## 内容
以下のイシューでvoicevoxがMacで動作するのが確認できたため、自動ビルドできるようにイシューとして作業を分けます。
https://github.com/Hiroshiba/voicevox/issues/348

リリースできる状態になったらプルリクなどでやります。

**Comment by PickledChair** [comment]
> 一応テストビルドでのインストーラーパッケージを貼っておきます。 https://github.com/Apple-Yuki/voicevox-for-Mac/releases/download/0.7.5.2/VOICEVOX_installer_x64.zip

インストーラーを試してみました。正常にインストールできました。VOICEVOX も使うことができました。環境は MacBook Air Early 2020, Intel Core i5, macOS Monterey (version 12.0.1) です。

| インストーラー | VOICEVOX |
| --- | --- |
|<img width="732" alt="voicevox_installer" src="https://user-images.githubusercontent.com/41382894/139643316-61ce85f2-b3ac-4ad3-a314-2ce3749954a8.png"> | <img width="912" alt="voicevox_on_mac" src="https://user-images.githubusercontent.com/41382894/139643345-295540c9-cf63-4e7c-8c3d-c92e6ea8ef7f.png"> |

**Comment by Apple-Yuki** [comment]
> > 一応テストビルドでのインストーラーパッケージを貼っておきます。 https://github.com/Apple-Yuki/voicevox-for-Mac/releases/download/0.7.5.2/VOICEVOX_installer_x64.zip
> 
> インストーラーを試してみました。正常にインストールできました（インストーラーをコンテキストメニューから開くと、ダイアログで信頼するかどうか聞かれますが、そのまま直接インストーラーを使用できました）。VOICEVOX も使うことができました。環境は MacBook Air Early 2020, Intel Core i5, macOS Monterey (version 12.0.1) です。
> 
> インストーラー	VOICEVOX
> <img alt="voicevox_installer" width="732" src="https://user-images.githubusercontent.com/41382894/139643316-61ce85f2-b3ac-4ad3-a314-2ce3749954a8.png">	<img alt="voicevox_on_mac" width="912" src="https://user-images.githubusercontent.com/41382894/139643345-295540c9-cf63-4e7c-8c3d-c92e6ea8ef7f.png">

おぉ、動作チェックありがとうございます。
一旦、開発環境入れたくないけどVOICEVOX使いたい人には使いやすくなったかと。

**Comment by kilinbox** [comment]
> 一応テストビルドでのインストーラーパッケージを貼っておきます。 https://github.com/Apple-Yuki/voicevox-for-Mac/releases/download/0.7.5.2/VOICEVOX_installer_x64.zip

新しいM1 Macbookが手に入ったので、このMacにインストールしてみました。
（OSが入ったばかり。何もソフトウェアが入っていない状態）
起動時に『音声合成エンジンエラー』が表示されました。
素人な質問で申し訳ありませんが、別に何かをインストールしなければならないのでしょうか。
```
user@usernomakku MacOS % ./VOICEVOX
[20:30:52.820] [info]  Starting ENGINE in CPU mode
[20:30:53.735] [error] ENGINE: ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/Applications/VOICEVOX.app/Contents/MacOS/hashlib.py", line 244, in <module>
  File "/Applications/VOICEVOX.app/Contents/MacOS/hashlib.py", line 113, in __get_builtin_constructor
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/Applications/VOICEVOX.app/Contents/MacOS/hashlib.py", line 244, in <module>
  File "/Applications/VOICEVOX.app/Contents/MacOS/hashlib.py", line 113, in __get_builtin_constructor
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/Applications/VOICEVOX.app/Contents/MacOS/hashlib.py", line 244, in <module>
  File "/Applications/VOICEVOX.app/Contents/MacOS/hashlib.py", line 113, in __get_builtin_constructor
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/Applications/VOICEVOX.app/Contents/MacOS/hashlib.py", line 244, in <module>
  File "/Applications/VOICEVOX.app/Contents/MacOS/hashlib.py", line 113, in __get_builtin_constructor
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/Applications/VOICEVOX.app/Contents/MacOS/hashlib.py", line 244, in <module>
  File "/Applications/VOICEVOX.app/Contents/MacOS/hashlib.py", line 113, in __get_builtin_constructor
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/Applications/VOICEVOX.app/Contents/MacOS/hashlib.py", line 244, in <module>
  File "/Applications/VOICEVOX.app/Contents/MacOS/hashlib.py", line 113, in __get_builtin_constructor
ValueError: unsupported hash type sha512

[20:30:53.761] [error] ENGINE: Traceback (most recent call last):
  File "/Applications/VOICEVOX.app/Contents/MacOS/run.py", line 7, in <module>
  File "/Applications/VOICEVOX.app/Contents/MacOS/tempfile.py", line 45, in <module>
  File "/Applications/VOICEVOX.app/Contents/MacOS/random.py", line 46, in <module>
ImportError: cannot import name 'sha512' from 'hashlib' (/Applications/VOICEVOX.app/Contents/MacOS/hashlib.py)

[20:30:53.768] [info]  ENGINE: terminated due to receipt of signal null
[20:30:53.768] [info]  ENGINE: exited with code 1
[20:30:57.580] [error] Error: Failed to fetch Failed to fetch AudioQuery for the text "".
[20:30:57.670] [error] TypeError: Failed to fetch
[20:30:58.569] [info]  waiting engine...
```

**Comment by Apple-Yuki** [comment]
@kilinbox さん、ご報告ありがとうございます。
macOS 12 Montereyからは、Python2.7、PHPが非推奨としてバンドルされなくなったりしてるため、Xcode Command Line Toolsを入れることでPython3.xが自動でインストールできます。

以下の方法でインストールを試してみてください。これを一行ずつmacOSのターミナルに貼り付けて下さい。

## Command Line Toolsのインストール
```
xcode-select --install
python3 --version
```
**Python 3.x.xと結果表示すればインストールされています。**


## Xcodeコマンドラインツールインストールを通してPython2系のPythonをインストール
```
sudo xcode-select --install
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew install python@2
export PATH="/usr/local/opt/python@2/bin:$PATH"
```

**Comment by kilinbox** [comment]
@Apple-Yuki ありがとうございます。
明日試してみます。

**Comment by PickledChair** [comment]
> macOS 12 Montereyからは、Python2.7、PHPが非推奨としてバンドルされなくなったりしてるため、Xcode Command Line Toolsを入れることでPython3.xが自動でインストールできます。

VOICEVOX.app 内には [Nuitka](https://nuitka.net/) でコンパイルされた [VOICEVOX のエンジン](https://github.com/Hiroshiba/voicevox_engine) が入っており、その中に Python 環境も含まれているはずなので、追加の Python のインストールが必要ないようになっているはずです。実際、 @kilinbox さんの報告されたエラーメッセージを見ると、Python のエラーメッセージ（ValueError や ImportError など）が表示されているので、Python インタープリタは実行されているように見えます。

しかし VOICEVOX を実行可能にするだけなのであれば、 @Apple-Yuki さんの示された Python3 のインストール手順で起動するようになる可能性はあります。

エラーメッセージを見ると Python の標準ライブラリに含まれている hashlib モジュールのインポート中にエラーが起こっています。似たようなエラーが起こっている例を探したところ、Nuitka のリポジトリで同じようなエラーを扱っている Issue が立っているのを見つけたので共有します（ただし環境は Intel Mac のようです）。

https://github.com/Nuitka/Nuitka/issues/516

この Issue では実行ファイルなどの rpath に追加されている Python 関連の共有ライブラリのパスが、 `@executable_path/...` のような実行ファイルからの相対パスではなく、ハードコードされた絶対パスとして追加されてしまうことを問題としています。特に macOS における問題のようです。 @kilinbox さんの環境でも似た問題が生じている可能性があり、システムの適切な場所に Python がインストールされると解決する可能性があります。

（ただし、この Issue の author の調査方法を参考に、自分の環境にインストールした VOICEVOX に含まれるバイナリ（`/path/to/VOICEVOX.app/Contents/MacOS` にある）を以下のコマンドで調査しましたが、hashlib で利用されている libssl はディレクトリに含まれており、rpath の指定も問題なさそうなので、hashlib モジュールのインポートが失敗する理由はわかりませんでした。実際自分の環境では VOICEVOX が正常に動作しますが、クリーンな macOS 環境を持っておらず、Nuitka についても詳しくないので、これ以上のことは今のところ調べるのが難しいです。）

<details>
<summary>otool -l *.so | grep ' name' | sort | uniq の実行結果</summary>
<pre>
<code>
$ otool -l *.so | grep ' name' | sort | uniq
         name /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (offset 24)
         name /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration (offset 24)
         name /System/Library/Frameworks/Tcl.framework/Versions/8.5/Tcl (offset 24)
         name /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk (offset 24)
         name /usr/lib/libSystem.B.dylib (offset 24)
         name /usr/lib/libbz2.1.0.dylib (offset 24)
         name /usr/lib/libc++.1.dylib (offset 24)
         name /usr/lib/libffi.dylib (offset 24)
         name /usr/lib/libncurses.5.4.dylib (offset 24)
         name /usr/lib/libpanel.5.4.dylib (offset 24)
         name /usr/lib/libz.1.dylib (offset 24)
         name @executable_path/libcrypto.1.1.dylib (offset 24)
         name @executable_path/libgdbm.6.dylib (offset 24)
         name @executable_path/libgdbm_compat.4.dylib (offset 24)
         name @executable_path/liblzma.5.dylib (offset 24)
         name @executable_path/libmpdec.3.dylib (offset 24)
         name @executable_path/libreadline.8.dylib (offset 24)
         name @executable_path/libsqlite3.0.dylib (offset 24)
         name @executable_path/libssl.1.1.dylib (offset 24)
         name @rpath/libcore.dylib (offset 24)
</code>
</pre>
</details>

<details>
<summary>ls -1 *.dylib の実行結果</summary>
<pre>
<code>
$ ls -1 *.dylib
libblas.dylib
libc10.dylib
libcaffe2_detectron_ops.dylib
libcore.dylib
libcrypto.1.1.dylib
libgcc_s.1.dylib
libgdbm.6.dylib
libgdbm_compat.4.dylib
libgfortran.5.dylib
liblapack.dylib
libllvmlite.dylib
liblzma.5.dylib
libmpdec.3.dylib
libopenblas.0.dylib
libopenblas.dylib
libopenblasp-r0.3.18.dylib
libquadmath.0.dylib
libreadline.8.dylib
libsqlite3.0.dylib
libssl.1.1.dylib
libtorch.dylib
libtorch_cpu.dylib
libtorch_global_deps.dylib
</code>
</pre>
</details>

最終的にはユーザーに Python をインストールさせるのは避けたいところです。以下のような原因の切り分けが必要だと思います。

- システムに Python がインストールされていない環境のみで起こるのかどうか
- Apple Silicon Mac 特有の問題か、Intel Mac でも起こりうる問題なのか

また、もし rpath の問題なのであれば、ビルド手順に install_name_tool コマンドで修正する手順などを加える必要があります。あるいは、先ほど挙げた Issue には Nuitka のオプションを利用するような解決策を提示している人（ https://github.com/Nuitka/Nuitka/issues/516#issuecomment-731579895 ）もいたので、そのような方法も有効なのかもしれません。

**Comment by Hiroshiba** [comment]
僕も、このエラーを場当たり的に解決するのではなく、原因を特定してそもそもエラーが起こらないようにするのが最も良いのかなと思いました。
ただでもこのリポジトリはエディターの方なので、エンジン側に報告issueを建てるのが良いのかもしれません。

クリーンな環境でちゃんと動くかのテストは、github actionsでやると便利かもしれません。
（というissueを建ててみました！）

- https://github.com/Hiroshiba/voicevox_engine/issues/176

**Comment by Apple-Yuki** [comment]
あくまでもIntelビルドなのでApple Siliconシリーズ（M1シリーズ）で利用する場合、Rosetta 2で実行にチェックついてるか確認してみてください。（多分Intelビルドなので強制Rosetta使ってそうですが念の為）

### Mac に Rosetta をインストールする必要がある場合
Rosetta 2 を使えば、Apple シリコンを搭載した Mac でも、Intel プロセッサ搭載 Mac 用に開発された App を使えるようになります。
https://support.apple.com/ja-jp/HT211861


あと動かないイシューはこのイシューの関連である　https://github.com/Hiroshiba/voicevox/issues/348　側で議論する方がいい気もしますね。

**Comment by kilinbox** [comment]
まっさらなMontereyで動かなかった件ですが、解決しましたのでご報告します
（次回から建てていただいたissueに書くことにします）

VOICEVOX起動時に以下のエラーが出る（前回報告した内容）

> ImportError: cannot import name 'sha512' from 'hashlib' (/Applications/VOICEVOX.app/Contents/MacOS/hashlib.py)

Rosetta2を使ったターミナルでHomebrewとPython3をインストール
```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew install python3
```
VOICEVOX起動時、今度は以下のエラーが出る

> ImportError: dlopen(/Applications/VOICEVOX.app/Contents/MacOS/numpy/core/_multiarray_umath.so, 0x0002): Library not loaded: /usr/local/opt/gcc/lib/gcc/11/libgfortran.5.dylib

gccをインストール
`brew install gcc`

VOICEVOX起動時、今度は以下のエラーが出る

>   Referenced from: /Applications/VOICEVOX.app/Contents/MacOS/libgfortran.5.dylib
>   Reason: tried: '/usr/local/Cellar/gcc/11.2.0/lib/gcc/11/libquadmath.0.dylib' (no such file), '/usr/local/lib/libquadmath.0.dylib' (no such file), '/usr/lib/libquadmath.0.dylib' (no such file)

パスを変更する
`sudo install_name_tool -change /usr/local/Cellar/gcc/11.2.0/lib/gcc/11/libquadmath.0.dylib /usr/local/opt/gcc/lib/gcc/11/libquadmath.0.dylib '/Applications/VOICEVOX.app/Contents/MacOS/libgfortran.5.dylib'`

VOICEVOX起動時、今度は以下のエラーが出る

> ImportError: dlopen(/Applications/VOICEVOX.app/Contents/MacOS/core.so, 0x0002): Library not loaded: /usr/local/opt/protobuf/lib/libprotobuf.28.dylib

Protocol buffersをインストール
`brew install protobuf`

これで無事起動するようになりました。

**Comment by PickledChair** [comment]
@kilinbox さん報告ありがとうございます。おかげで問題がかなり整理され、原因と思われる部分がわかってきました。エンジンのビルドの問題なので、エンジンのリポジトリの方で Issue を立てました。

**Comment by Apple-Yuki** [comment]
Appleが配布しているOS拡張である[CommandLineTools](https://github.com/Apple-Yuki/voicevox-for-Mac/releases/download/0.7.5.2.2/Command_Line_Tools_for_Xcode_13.1.dmg)を入れることでPython3が入るようで
以下のコマンドで一応動作しました。

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew install gcc
sudo install_name_tool -change /usr/local/Cellar/gcc/11.2.0/lib/gcc/11/libquadmath.0.dylib /usr/local/opt/gcc/lib/gcc/11/libquadmath.0.dylib '/Applications/VOICEVOX.app/Contents/MacOS/libgfortran.5.dylib'
brew install protobuf
```

**Comment by HyodaKazuaki** [comment]
> Appleが配布しているOS拡張であるCommandLineToolsを入れることでPython3が入るようで
> 以下のコマンドで一応動作しました。

ユーザーがインストールのために追加で作業が必要なのは、利便性が低いのではないかと思います。

@Hiroshiba にお伺いしたいのですが、VOICEVOXは動作に必要な前提となるソフトウェアを同梱する方針なのでしょうか？

私としては、VOICEVOXを配布するのであれば前提とするソフトウェアを同梱するか、インストーラで一緒に導入することができるようにしたほうが良いと思っています。
ユーザーにCommand Line Toolsを導入してもらうのは解決策の1つではあると思いますが、できれば全部入りのアプリにした方が導入難易度が低いと考えています。

**Comment by Hiroshiba** [comment]
ターミナルの利用はハードルが高いと思うので、ダブルクリックするだけで実行できるように、同梱する形で作りたいと思っています。
（インストーラで一緒に導入は、利用者のPC環境が変になったときのサポートが大変そうなので、避けたほうが無難かも？）

**Comment by Apple-Yuki** [comment]
ひとまずメモ：

一応調べると、gccもPython3と同じくCommand Line Toolsに同梱されているみたいです。
現在Macはレガシーなソフトウェアとの互換性を持たせるため一時的にPython 2.7.18が入ってますが将来的にCommand Line Toolsに移行しPythonのOS同梱がなくなるようなので、Pythonで動くようにしている場合、将来的にCommand Line Toolsが必要になるようです。


アプリケーションがPython 2.7を使用している場合、macOSは、開発者がアプリケーションをアップデートして、macOSの将来のバージョンで確実に動作するようにする必要があることを示すアラートを表示するようになりました。(80221011) -macOS Monterey 12.0.1 Release Notes
[If an app uses Python 2.7, macOS now triggers an alert indicating that the developer must update the app to ensure it will work in future versions of macOS. (80221011)](https://developer.apple.com/documentation/macos-release-notes/macos-12_0_1-release-notes)

**Comment by PickledChair** [comment]
> 一応調べると、gccもPython3と同じくCommand Line Toolsに同梱されているみたいです。
> 現在Macはレガシーなソフトウェアとの互換性を持たせるため一時的にPython 2.7.18が入ってますが将来的にCommand Line Toolsに移行しPythonのOS同梱がなくなるようなので、Pythonで動くようにしている場合、将来的にCommand Line Toolsが必要になるようです。

公式にリリースされている VOICEVOX エディターは内蔵エンジンに https://github.com/Hiroshiba/voicevox_engine リポジトリの自動ビルドを用いています。macOS 向けの自動ビルドのコードはこちらです→ https://github.com/Hiroshiba/voicevox_engine/blob/a665d995f2e030087174458e70457f83894bdbc6/.github/workflows/build.yml#L14-L236 。自動ビルドの生成物は https://github.com/Hiroshiba/voicevox_engine/releases からダウンロード可能です。

近いうちに、macOS において、Python や gcc 等の依存関係がなくても、この自動ビルドの生成物のみで（ユーザーの追加インストールなしに）エンジンの実行ができるようになります（Python については、Nuitka を用いてバージョン 3.7 がコンパイルされており、すでにほぼこれだけで動作できるようになっています）。Windows 版と Linux 版はすでに開発パッケージの追加インストールが不要なようになっています。現在の最新版では macOS 版だけに問題があります。しかしこれも https://github.com/Hiroshiba/voicevox_engine/issues/177 で議論を進めた結果、解決の目処が立ちそうなので今しばらくお待ちください。解決したら改めてこの Issue でお知らせします。この Issue では、Python や gcc の心配はしなくても大丈夫だと思います。

**Comment by Hiroshiba** [comment]
dylibの修正がマージされました（thx! @PickledChair ）！
↓で自動ビルドのお試しをしています。
https://github.com/Hiroshiba/voicevox_engine/releases/tag/autobuild-check-20211119

**Comment by PickledChair** [comment]
Nuitka に起因する問題は https://github.com/Hiroshiba/voicevox_engine/pull/191 で解決できたと思います。しかし、macOS版エンジンの別の問題が見つかりました。それについては https://github.com/Hiroshiba/voicevox_engine/issues/193 で作業したいと思います。

**Comment by PickledChair** [comment]
> Nuitka に起因する問題は [Hiroshiba/voicevox_engine#191](https://github.com/Hiroshiba/voicevox_engine/pull/191) で解決できたと思います。しかし、macOS版エンジンの別の問題が見つかりました。それについては [Hiroshiba/voicevox_engine#193](https://github.com/Hiroshiba/voicevox_engine/issues/193) で作業したいと思います。

https://github.com/Hiroshiba/voicevox_engine/pull/194 で上記の Issue の問題が解決したと思われます。[autobuild check 20211120](https://github.com/Hiroshiba/voicevox_engine/releases/tag/autobuild-check-20211120) の `macos-x64.7z.100` が自動ビルドの結果です。

ダウンロードしたものを macOS で解凍する時は `brew install p7zip` で 7z コマンドをインストールし、`7z x macos-x64.7z.100` で解凍するのが便利だと思います（参考： https://github.com/Hiroshiba/voicevox_engine/issues/163#issuecomment-966039932 。実行方法についても書いてあります）。

この macOS 版エンジンに問題がなければ、macOS 版 VOICEVOX エディターの自動ビルド整備に取り掛かれると思います。

**Comment by Hiroshiba** [comment]
@Apple-Yuki エンジンのMac版自動ビルドが作業完了なため、エディタも含めたソフトウェア全体の自動ビルドが可能になりました！
VOICEVOXのmac対応の要望は今もなお結構見かけます。どうでしょう、自動ビルドを作ってみませんか・・・？
https://twitter.com/search?q=VOICEVOX%20mac&src=typed_query&f=live

**Comment by Apple-Yuki** [comment]
@Hiroshiba わかりました。
できる範囲でお手伝いします。

**Comment by Apple-Yuki** [comment]
なんかM1用にHomebrewが出たご様子でこのコマンドで入れろと言われる。というメモ

`arch -arm64 brew install `

**Comment by Hiroshiba** [comment]
@Apple-Yuki 調子はいかがでしょうか👀
もしお忙しかったら、今までの進捗を書いていただければ別の方が引き継いで作業できるかもです。

**Comment by Hiroshiba** [comment]
@Apple-Yuki 調子はいかがでしょうか👀
もしお忙しかったら、今までの進捗を書いていただければ別の方が引き継いで作業できるかもです。

**Comment by Apple-Yuki** [comment]
@Hiroshiba 
最近M1Macで環境入れ替えした結果、ビルドエラーが出たりするので色々対策を考えてます。
あとActionを勉強してるんですが仕事も年末特有の多忙さで…

**Comment by Hiroshiba** [comment]
なるほどです！
ちなみにですが、別の方でチャレンジしてみたい方いらっしゃったりしますか・・・？ 👀

**Comment by PickledChair** [comment]
@Hiroshiba Linux・Windows版のビルドや、 @HyodaKazuaki さん、 @Apple-Yuki さんのこれまでの取り組みで得られた情報を参考にして、取り組むことができるかもしれないと感じています。なので取り組みたい気持ちはあります。今月は特に時間を割けそうなので、とりあえず自主的に作業を始めてみても良いでしょうか。やってみて出来なさそうだった場合はその旨ご報告します（どのあたりで詰まった等も含めて）。

**Comment by Hiroshiba** [comment]
おお、ぜひお願いします！！

**Comment by PickledChair** [comment]
了解しました。自分も取り組んでみます。

**Comment by Apple-Yuki** [comment]
@PickledChair さん、ありがとうございます。
なんか途中で丸投げになった感じになってすいません。
私にも何かお手伝いできることあれば言っていただければ暇見つけてお手伝いはできるかもしれないのでご気楽にお申しください。
（引き続き自分がお手伝いできることはお手伝いしますし、M1 MaxやProでの動作などのチェックなども承ります）

> @Hiroshiba Linux・Windows版のビルドや、 @HyodaKazuaki さん、 @Apple-Yuki さんのこれまでの取り組みで得られた情報を参考にして、取り組むことができるかもしれないと感じています。なので取り組みたい気持ちはあります。今月は特に時間を割けそうなので、とりあえず自主的に作業を始めてみても良いでしょうか。やってみて出来なさそうだった場合はその旨ご報告します（どのあたりで詰まった等も含めて）。

**Comment by Hiroshiba** [comment]
- https://github.com/VOICEVOX/voicevox/pull/570

で使ってみたアプリの操作感で、ちょっと気になったところをメモしておきます。

* タイトルバーをダブルクリックしても最大画面にならない
* `cmd`キー系統をショートカットキーとして登録できない
* トラックパッドだとスクロール感度が良すぎるかも

**Comment by PickledChair** [comment]
最初の

> タイトルバーをダブルクリックしても最大画面にならない

だけ、普段この操作をしないので気づきませんでした。残りは自分も気になっていました。これらは別途 Issue を立てると良さそうですね……！

**Comment by Apple-Yuki** [comment]
@Hiroshiba @PickledChair 
[macOS用アプリケーション (.app) とdmgファイル (.dmg) の自動ビルド #570](https://github.com/VOICEVOX/voicevox/pull/570)の実行テストですが動作自体は以下の通りです

・Apple Silicon M1、M1 Pro、M1 Maxでの動作は問題ありませんでした。（Rosetta環境のみ）

[動作の状況や書き出しデータはこちらからご覧ください。](https://app.box.com/s/jmxa4js18m0jpn6mb0cthk7u5pjxq0ie)

なお、以下のイシューや改善点があります。

- 設定画面のエンジンタイプでCPUからGPUに変更し、再起動された後CPUタイプへ復帰の際、**アプリがクラッシュする**。（以前のバージョンからあるものですけど）
- 設定画面のコマンド登録画面で`⌘Command`キーを押すと名称が`Meta`となる。（`⌘Command`＋`E`などの複数登録が不可）
- 設定画面などを開いてる際、上のコマンドバーの操作を一切受付ない。（仕様としてもユーザーエクスペリエンス的に直感的にしておいた方がいいかと。）
- 初期起動のキャラの声のイントネーション未選択時に「次へ」をグレーアウトせず、警告文でユーザーに知らせるといいかと思います。
もしくは、デフォルトイントネーションを決めておく。

他に気が付いたらまたこちらに書きます。

**Comment by Hiroshiba** [comment]
M1動作確認ありがとうございます、動いてよかったです！

コメントに関して追加のコメントをしてみます。

> 設定画面のエンジンタイプでCPUからGPUに変更し、再起動された後CPUタイプへ復帰の際、アプリがクラッシュする。

こちら再現できませんでした。正確な流れか、動画があると現象を共有できるかもです。

> 設定画面のコマンド登録画面〜

こちらは上で出てましたね

> 設定画面などを開いてる際、上のコマンドバーの操作を一切受付ない〜
> 初期起動のキャラの声のイントネーション未選択時に〜

これらはmacとは関係無さそうです。別途issueを作って頂けると！
