### ISSUE TITLE
quasarのスライダーが変な状態で固まる

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#404]
## 内容

調整していると、↓のような感じでスライダーが壊れることがあります。
![image](https://user-images.githubusercontent.com/4987327/139105990-0ff401c4-0624-4894-ab79-2febe0b9f442.png)

ホイール操作が（見た目上だったり本当にそうだったりで）効かなくなってしまうので、不便です。

どうやら「編集していない状態で、移動せずにクリックで値を変更する」と発生するっぽいです。
利用しているライブラリのquasarが原因なのか、VOICEVOXの特殊な処理（preview値を変更した後stateを更新する）のが原因なのかわかりませんが、結構頻繁に起こる気がするのでなんとかしたいところです。

### Pros 良くなる点

見た目が壊れなくなる

### 実現方法

quasar側の対応が必要そうなら、向こうにissueを建てて様子を見てもいいかもしれません。

## OSの種類/ディストリ/バージョン

Windows

## その他

調べたことがある人がいたら調査結果をコメント頂けると助かります。

**Comment by Uotsumi78a7** [comment]
Windows版 0.8.1 を使用していて、調整の「イントネーション」「長さ」タブのスライダーを右クリックするとこの状態になります。
見た目上は固まりますが、ホイール操作でマウスオーバーで表示される数値と実際の数値は変更されます。
調整のタブを切り替えると直ります。

再現性がとても高かったので、一応ご報告を……。

**Comment by Hiroshiba** [comment]
おっと、なるほどです･･･。ご報告ありがとうございます！

**Comment by Hiroshiba** [comment]
どうやら最新のquaserだとこの現象に関するアップデートがあるらしいです・・・！
quaser2.3.1にアップデートすると緩和されるかも。
https://github.com/quasarframework/quasar/issues/11250
