### ISSUE TITLE
複数のエンジンで音声合成できるようにする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#429]
## 内容

VOICEVOX製ではない、いわゆるサードパーティ製の音声合成エンジンを、VOICEVOX製のものとシームレスに利用できるようにしたいです。

VOICEVOXはエンジンや音声合成コアと疎結合になっているので、音声合成エンジンさえ変えればVOICEVOX製じゃないエンジンを挿せるはずです。
が、現状だとキャラクターイラストなども含めてビルドする必要などがあるため、エンジンごとにエディターを分ける必要があってしまいます。
これらの課題を解決すれば複数のエンジンに対応することができ、いろんなエンジンのいろんなキャラクターが利用可能になったり、自由にエンジンを作って付けたりできるようになるはずです。

### Pros 良くなる点

エンジンの自由度が増える

### Cons 悪くなる点

無いはず

### 実現方法

これらのissueを解決する必要がありそうです

- [x] CharactorInfoが必要な情報（立ち絵など）をエンジンに実装する
  - [x] https://github.com/Hiroshiba/voicevox_engine/issues/169
- [x] CharactorInfoをエンジンから取って来るようにする
  - [x] #433
- [x] 複数のエンジンのキャラクターを利用可能にする
  - [x] 別キャラクターのエンジンを用意する
  - [ ] エディタ側から複数のエンジンを見るようにする（.envのVUE_APP_ENGINE_URLを複数にする）
- [x] 設定で複数のエンジンを登録可能にする
  - [ ] ポートが登録できる
  - [x] VOICEVOX起動時に一緒に起動できる

## VOICEVOXのバージョン

0.7.5

## その他

0.9.0や0.10.0で追加したいマイルストーンです。

**Comment by shirowanisan** [comment]
問題なければ「CharacterInfoをエンジンから取って来るようにする」担当します。

**Comment by Hiroshiba** [comment]
@shirowanisan  よろしくおねがいします！！ #433 でassignします！

**Comment by Hiroshiba** [comment]
@shirowanisan さん、実装ありがとうございます！！

次は `複数のエンジンのキャラクターを利用可能にする` でしょうか。
これは、「別キャラクターのエンジンを用意する」というのと、「エディタ側から複数のエンジンを見るようにする（.envのVUE_APP_ENGINE_URLを複数にする）」の２つに分けられそうです。

@shirowanisan どうでしょう、前者の「別キャラクターのエンジンを用意する」をおまかせすることってできそうでしょうか・・・？

**Comment by shirowanisan** [comment]
@Hiroshiba 
マージありがとうございます。あまり慣れておらず時間がかかってしまいすみません。

> どうでしょう、前者の「別キャラクターのエンジンを用意する」をおまかせすることってできそうでしょうか・・・？

了解です。どう実現するのか考えるため、別のissueを作って設計の相談させていただくかもしれせん。

**Comment by aoirint** [comment]
`エディタ側から複数のエンジンを見るようにする`の方、取り組んでみて大丈夫そうでしょうか...?（簡単なデバッグはできると思います）

**Comment by Hiroshiba** [comment]
パラレルに進められそうなので、良いと思います！
いろんな設計が考えられそう＆変更箇所が大きそうなので、一旦issue化して頂いて、調査したり議論したりしつつ進められると良い実装にたどり着きやすいかもと感じました。

**Comment by aoirint** [comment]
こちらの方でも議論がありましたね。

- <https://github.com/VOICEVOX/voicevox/discussions/431>

いったんIssueを作ってみようと思います！

**Comment by Hiroshiba** [comment]
これがopenしたのが2021年の11月、懐かしいです。
こちらのissueに移動しています！

- https://github.com/VOICEVOX/voicevox_project/issues/2

もう完了しているので閉じたいと思います。
