### ISSUE TITLE
CharacterInfoをエンジンから取って来るようにする

### ISSUE THREAD

**Issue by shirowanisan** [VOICEVOX/voicevox#433]
## 内容

「CharacterInfoをエンジンから取って来るようにする」

関連：
Hiroshiba/voicevox#429 
Hiroshiba/voicevox_engine#169

### 実現方法
現在のキャラクター読み込み部分
https://github.com/Hiroshiba/voicevox/blob/2e44591474ec99e1c777495ab1a27b4094af41a6/src/background.ts#L293-L332

`_engineFactory`からとってくるようになるので`background.ts`ではなく、ここで整形する方が良い？
https://github.com/Hiroshiba/voicevox/blob/2e44591474ec99e1c777495ab1a27b4094af41a6/src/store/audio.ts#L419-L422

`LOAD_CHARACTER`の中でこのコードより、spekersを取得。
https://github.com/Hiroshiba/voicevox/blob/aebf5fc7f1eba3d360131f0b27108eb2ddc74230/src/openapi/apis/DefaultApi.ts#L560-L563

さらにspekers内のspeaker_uuidを使ってエンジンから以下を取得する

- policy.md
- portrait.png
- icons/*.png
- voice_samples/*.wav

### 担当者

問題なければ、エンジンが実装され次第自分が実装します。

**Comment by Hiroshiba** [comment]
issueありがとうございます！
一旦仰る通りの方針で実装をお願いしたいです！

**Comment by Hiroshiba** [comment]
エンジンの方にCharacterInfo（エンドポイント名はspeaker_info）が実装されました！
（ @takana-v さんありがとうございます！ ）
