### ISSUE TITLE
読み修正や区切り・長さ調整などの当たり判定が狭い領域の当たり判定を大きくする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#453]
## 内容

特定のUIで当たり判定がちょっと狭いという意見があります。
（アクセント句を区切る部分は特に狭いと思います。）

この当たり判定を広くする良い方法を探りたいです。

### Pros 良くなる点

操作しやすくなる

### 実現方法

当たり判定を広めするよう、CSSのpaddingとかを用意する・・・？

quasarのsplitter（AudioDetailの上などの区切り線）は見かけよりも広いクリック判定を持っているので、実装の参考になるかもです。

## VOICEVOXのバージョン

0.8.0

## その他

ご意見 https://twitter.com/Uotsumi/status/1457250558021013507

**Comment by nebocco** [comment]
こういうのはいかがでしょうか？

https://codepen.io/nebocco/pen/BaJQZoJ

```html
<div class="container">
  <span class="button">Click Me!</span>
</div>

<style>
  .container {
    margin: 20px;
  }

  .button {
    background-color: blue;
    position: relative;
  }

  .button:hover {
    cursor: pointer;
    background-color: red;
  }

  .button::after {
    content: "";
    position: absolute;
    top: 0;
    bottom: 0;
    left: -20px;
    right: -20px;
    z-index: 0;
    // background-color: green;
  }
</style>
```

**Comment by Hiroshiba** [comment]
良さそうです！！！

ちょっと当たり判定が小さそうなところをまとめてみました。

↓読み
https://github.com/VOICEVOX/voicevox/blob/62e7b3604c12f3dd97aaa7c1a2a8b8f48ca4e627/src/components/AudioDetail.vue#L144-L178

↓アクセント句の区切り
https://github.com/VOICEVOX/voicevox/blob/62e7b3604c12f3dd97aaa7c1a2a8b8f48ca4e627/src/components/AudioDetail.vue#L820-L838

（タイトルにある「長さ調整」はどれのことか忘れてしまいました･････。）

どちらもhtmlのgrid layoutの中にあるので、CSSが崩れてしまうかもです。

書いていて気づいたのですが、この２つとものUIが隣り合っているので、片方の当たり判定を増やしたらもう片方の当たり判定が狭まってしまいそうですね･･･
こんな感じに、アクセント句の区切りは当たり判定を縦方向にも伸ばす、とか･･･････？
<img width="472" alt="あ" src="https://user-images.githubusercontent.com/4987327/159730207-b73bf170-e63c-4b2e-aea2-c691fbf8e336.png">

**Comment by nebocco** [comment]
文字の直上にマウスカーソルを持ってくるのは文字間の中央に持ってくるよりもはるかに簡単なので、文字部分の当たり判定は今よりも小さくて大丈夫な気がします。いったん全体の文字間隔が変わらないようにアクセント句の当たり判定を広げてみます。

**Comment by Hiroshiba** [comment]
毎日エゴサしてますが、クリックがむずいことに関して全く言及がなくなったので、解決かなと思いました！
@nebocco さんありがとうございました！！
