### ISSUE TITLE
ツールバーのボタン配置をカスタマイズ可能にする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#462]
## 内容

元に戻す、やり直す等が表示されているツールバーですが、ここをカスタマイズ可能にすると多岐にわたるユーザーが、自分の使いたい機能へUI的にアクセスしやすくできそうです。
![image](https://user-images.githubusercontent.com/4987327/140955852-96c59229-bacb-4bcb-9b80-d94fd9eff511.png)

### 実現方法

ショートカットキーに設定されているものを流用すれば割と簡単に実装できるかも？

## VOICEVOXのバージョン

0.?.0

**Comment by y-chan** [comment]
これ、ちょっと手を付けてみようかと思います。
アサインしていただければ幸いです

**Comment by Hiroshiba** [comment]
ありがとうございます！！　よろしくおねがいします・・・！
