### ISSUE TITLE
0.8.0で廃止された音声保存ボタン(音声書き出しボタン)について

### ISSUE THREAD

**Issue by noronoro56** [VOICEVOX/voicevox#463]
## 内容
0.8.0で廃止された音声保存ボタンですが、必要なGUIだと感じますので議論させてください。
Hiroshibaさん曰く「あまり使われない」とのことですが議論があったわけではないようですし、音声保存ボタンの廃止について戸惑う声も多く、考慮していただきたく思います。

###横幅問題について
TwitterにてHirosibaさん曰く
>大多数の人は横幅が増えて嬉しいと感じられるはず

とのことですが、上下方向に並べれば横幅占有の問題は生じないのではないでしょうか？

###想定されるワークフロー
おそらくHiroshibaさんは「複数の音声を設定してからまとめて書き出す」というワークフローを想定されているのだと思われます。ですがtwitterでも指摘の声がある通り「1フレーズずつ保存して動画に貼り付ける」ワークフローも存在し、決して稀な方法ではないと思われます。

1フレーズずつ保存する場合には「音声調整」→「音声確認」→「保存ボタンで保存」の過程をたどるので、再生ボタンと保存ボタンが近いとワークフローを妨げずスムーズな操作になります。メニューボタンは距離的にも遠く、ワンクリック増えるので好ましくありません。

###初めて使う人向けにも音声ボタンがあると親切
TwitterでHiroshibaさんが
>UIとして見えていなくても、初学者の方は音声を作ったあと、音声が保存できるだろうと考えて保存方法を探し、メニューにあることに気づくと思うのであまり問題ではないと思います。

とおっしゃっていますが、初学者がパッと見て「音声の保存方法がわからないな」と戸惑うようなUIは好ましくないのではないでしょうか。
初学者が戸惑うのは「あるべきところにあるはずのボタンがない」と感じるからであり、必要なボタンであったと思います。
また「初学者も慣れたらみんなショートカットキーを使うのでボタンは不要になる」というわけではなく、大部分のユーザーはGUIを使い続けるものではないでしょうか。

**Comment by noronoro56** [comment]
それから、従来の音声保存ボタンとメニューの「音声書き出し」は別物なのですね。
現在、従来の音声保存ボタンと同じ機能を持つのはショートカットキー割り当ての「一つだけ書き出し」に相当するようですが、メニュー内を含めてGUIが存在しないようです。

先述のとおり従来の音声保存ボタンに相当する機能は必要なものと思いますので、復活をご検討ください。

**Comment by arigayas** [comment]
従来の音声保存ボタンに相当するGUIというかボタンを各文の上にマウスホバーすると表示される「削除ボタン」の左に置くのはどうでしょうか？
この位置に保存ボタンをおいたら「この文の保存」だと直感的にわかる気がします。

**Comment by Hiroshiba** [comment]
@noronoro56 
一番問題なのは、代替方法が全く案内できなかったことだと思っています。
ショートカットキーで（完璧ではないけど）代替可能なことを最初から案内できていれば、少なくとも混乱は避けられたはずなので申し訳なく思っています。
遅ればせながら案内を出したので、こちらの代替案でご要望がどの程度満たされるかを見て、今後どうするかを決めたいです。
https://twitter.com/hiho_karuta/status/1458034252268724228

また、マウス操作だけで音声を１つ書き出す代替策が無いのも問題だと感じました。
ので、hotfixを作成してバージョン0.8.2をリリースしました。メニューから書き出しが可能になっています。
（ついでにデフォルトショートカットキーを設定しました。）
この２点で、不完全ながらも代替できる方法を用意できたと思っています。

次の論点として、戻すかどうかに関してですが、縦幅・横幅が狭くなるので戻さないほうが、これからVOICEVOXを利用する人も福田全体的な満足度は上がると思っています。
ただ、書き出しのためのUIがファーストビューにて表示されていないのも問題だと感じています。
ので、これら２つの意見を両方解決するような手段を考えるのはどうでしょうか。

アイデアの１つ目はツールバーのカスタマイズ機能です。
ツールバーに最初から音声書き出し機能が備わっていれば、幅も問題ないし、かつそれが不要な方は別のボタンを置くことも可能なので、個人的には良い案だと思っています。

- https://github.com/Hiroshiba/voicevox/issues/462

もう１つはAudioDetailの右下か右上にfloatとして表示し、設定によって消せるというのでも良いと思います。

どちらもプルリクエストを頂ければhotfixとしてバージョン0.8.3としてリリースしたいと思います。

**Comment by Hiroshiba** [comment]
@arigayas テキスト欄に表示するのは確かに幅も取らずわかりやすそうなのですが、消去ボタンと合わさってちらつきがキツくなりそうかもとちょっと感じました！

**Comment by noronoro56** [comment]
@arigayas
ありがとうございます。
>各文の上にマウスホバーすると表示される「削除ボタン」の左に置く

ホバーなしでも見えていないと、UIの存在に気付かれない可能性があるように思います。
それと、保存ボタンと消去ボタンが並んでいると「保存しようと思ったのに隣の消去ボタンを押してしまった」トラブルが発生しそうです。

**Comment by noronoro56** [comment]
@Hiroshiba
hotfixありがとうございます。

>ツールバーのカスタマイズ機能です。
ツールバーに最初から音声書き出し機能が備わっていれば

個人的には再生ボタンと音声書き出し機能が近い方がうれしいですが、ツールバー上に分かりやすく表示できれば十分に機能を果たしてくれると思うので、良さそうに思います。

**Comment by Hiroshiba** [comment]
@noronoro56 なるほどです！！
どうでしょう、ツールバー上にカスタマイズ機能を実装してみませんか・・・？
カスタマイズ機能の実装が決まれば、一旦音声を１つだけ書き出す機能をツールバー上に表示するhotfixを作成したいと思います。
１回のhotfixは３時間くらいの工数がかかるそれなりに大きな作業なのですが、この修正は大事なので可能なら早急に導入したいと思っています。

その後カスタマイズ機能がリリースされれば、ツールバーがごちゃっとしてるのが嫌いなユーザーは片付けられたり、ボタンが不要な方は別のボタンに置き換えられるので全員納得できるのかなと思っています。

**Comment by noronoro56** [comment]
すみません、単にボタンを作成するだけならともかくツールバーカスタマイズのダイアログ等も含めて作成するとなると、私では初心者なもので手に余りそうです・・・。

**Comment by Hiroshiba** [comment]
なるほどです・・・！

引き続き、ツールバーのボタン配置をカスタマイズ可能にする機能 #462 か、AudioDetailの右下か右上にfloatとして表示して設定によって消せる機能を実装してもいいよという方を募集したいと思います。
