### ISSUE TITLE
開発に使用するNode.jsのバージョンを上げたい

### ISSUE THREAD

**Issue by yamachu** [VOICEVOX/voicevox#464]
## 内容

開発に使用しているNode.jsのバージョンがv14系で固定されている。
これをv16に引き上げることを提案する。

### Pros 良くなる点

2点良くなる点があると考えている。

1. 初学者に優しくなりそう

現在Node.jsのLTSはv16になっている。
そのこともあり [Node.jsのホームページ](https://nodejs.org/ja/) にアクセスするとv16とv17へのダウンロードリンクが表示されるようになっている。

そのため、初学者がNode.jsをインストールしようとした時、ホームページに表示されているリンクを押しインストールするだけで開発に必要なバージョンのNode.jsがインストールできる。

2. M1 Nativeサポートされている

M1 Macなどで開発する時にRosettaとか考えずにそのまま使える。

### Cons 悪くなる点

Electronで使われているNode.jsのバージョンと差異が出るため、Electronのバージョンも併せて上げる必要が出てきそう（electron-rebuildとかで回避は出来ないこともないが…）。
それに伴ってElectron関係のパッケージ類も上げる必要が出てくることが考えられる。

### 実現方法

1. 一旦 `.node-version` を消し飛ばす
2. `packge.json` の `engines` のフィールドの書き換え
3. v16での動作確認
4. （余力があれば）v16系を使っているElectronへバージョンアップ

## VOICEVOXのバージョン

0.?.0

**Comment by koizuka** [comment]
単純に package.json の `engines` を緩和してnode 16.13.0に上げて  `npm run electron:build` を試したところ、以下のエラーが沢山でるので、これを解決する必要がありますね。
>Error: editions-autoloader-none-broadened: Unable to determine a suitable edition, even after broadening.

**Comment by koizuka** [comment]
あと、開発環境のnodeとElectronのバージョンは違っていても `electron-builder` がよしなにしてくれますので大丈夫です。

node-gypを使っている依存がある場合には `postinstall` スクリプトで  `electron-builder install-app-deps` を仕掛けておけばfixできますが、それもすでに入っていますね。

**Comment by yamachu** [comment]
> あと、開発環境のnodeとElectronのバージョンは違っていても electron-builder がよしなにしてくれますので大丈夫です。

なるほど！自分がElectronでの開発に慣れていない時にNode.jsのバージョンを上げたらネイティブ依存のパッケージ関連がある場合はelectron-rebuildを何度かかまさないといけなかったなーという記憶があったのですが、`electron-builder`がいい感じにしてくれるのですね。
であれば
https://github.com/Hiroshiba/voicevox/issues/464#issuecomment-974618034

> Error: editions-autoloader-none-broadened: Unable to determine a suitable edition, even after broadening.

この解消ですね…

**Comment by koizuka** [comment]
このエラーに関連しそうなやりとり:
https://github.com/electron-userland/electron-builder/issues/5668#issuecomment-826941928
https://github.com/electron-userland/electron-builder/issues/5668#issuecomment-841062746

このあたりをみると、nodeとelectron-builder のバージョンの関係でおきるみたいですが、voicevoxは現状 electron-builder を直接dependしていないのでコントロールができませんね... (vue-cli-plugin-electron-builder経由で間接的に依存している)

**Comment by Hiroshiba** [comment]
状況をちゃんと掴めていないのですが、voicevoxからelectron-builderを参照して、ほしいバージョンを指定するみたいなちょっとゴリ押し方法もあるかも・・・？

**Comment by koizuka** [comment]
試しに https://github.com/nklayman/vue-cli-plugin-electron-builder を forkして、electron-builderを最新の 22.14.5に更新したリポジトリを作成してみたので、それを
```shell
npm add koizuka/vue-cli-plugin-electron-builder
```
で参照するようにしてから `npm run electron:build` をしたらビルドできましたね。やはり electron-builderを更新するだけで解決はするようです。

直接参照でelectron-builderだけを更新するというのは、 package-lock.json をダイレクトに書き換えるかさもなくば vue-cli-plugin-electron-builder がやってることを同等になるように自分で書くか、という感じになるので微妙な感じですね。

**Comment by yamachu** [comment]
yarnであればresolutions fieldで無理やりパッケージバージョンを指定出来るのですが、npmだったら
https://github.com/rogeriochaves/npm-force-resolutions
この辺りで指定してあげればどうにかなりそうですね

**Comment by koizuka** [comment]
じゃあそれで試してみるかなw

**Comment by koizuka** [comment]
うーん、試してみたけどうまくいかないな。forkして入れた場合は大丈夫で resolutionsだと駄目なのは、resolutionsだとその特定のひとつだけを置換して、そこからの依存先は変わってないのもしれない?

**Comment by koizuka** [comment]
package-lock.jsonを見たところ、確かに依存先は古いままみたい。forkほうののyarn.lockで更新されてるものと同じになっていないので、動くまでひとつひとつresolutionsを足していく必要がある...?

**Comment by koizuka** [comment]
なのでまあ、
1. ビルド出来るようになる vue-cli-plugin-electron-builder の更新を待つ(一番楽だがいつになるかわからない)
2. vue-cli-plugin-electron-builder に更新を働きかける
3. 上記更新まで
    1. forkで凌ぐ
    2. resolutionsで凌ぐ
というような選択肢が考えられるかな。

**Comment by Hiroshiba** [comment]
なるほどです、調査ありがとうございます！！
`vue-cli-plugin-electron-builder`が依存する`electron-builder`のバージョンが低くてなんかエラーが出るんですね･･･

`vue-cli-plugin-electron-builder`側にissue建てて更新を待つのが綺麗ですが、更新頻度を見るにかなり先の話になるかもと思いました。

となると方法3、fork辺りの選択肢が現実的だと思います。
個人的には、forkしてpackage.jsonに`"electron-builder": "22.14.5"`と書いてそれに依存するのも、VOICEVOXにpackage.jsonに`"electron-builder": "22.14.5"`と書くのも、同じくらいの複雑度に感じます。
package.jsonにメモを直接書ければ、FIXME辺りでコメントを残してVOICEVOXのpackage.jsonを書き換えちゃうのが楽そうなのですが、jsonなんで難しいかな･･･

とりあえず、`vue-cli-plugin-electron-builder`をforkしてみました。
https://github.com/Hiroshiba/vue-cli-plugin-electron-builder

**Comment by koizuka** [comment]
そのforkにこちらでやったやつをPull Requestしようとしたけど候補に出てこないな...ラグなのかな?
手でやる場合、作業ディレクトリで
```
yarn add electron-builder
```
と打つだけです(yarnなのでこれでlatestになる)

**Comment by koizuka** [comment]
そうそう、
>VOICEVOXにpackage.jsonに"electron-builder": "22.14.5"と書く

これは機能しないはず。これは単に両方のバージョンがインストールされ、依存してるツールから指定したバージョンのほうが実行されてしまう。
なので上記の議論にある resolutions による差し込み置換が候補になったわけです。

**Comment by koizuka** [comment]
ちょっと調べてみると、 npm shrinkwrap という機能がつかえる可能性があるのかな？こっちも試してみよう...

**Comment by koizuka** [comment]
色々試していたんですが、
```
npm install --save-dev electron-builder
```
で依存の electron-builderを 22.14.5にした場合でも、forkアプローチでも、

* node 14だと electron:build, electron:serve, test:unit すべて成功しますが、
* node 16(package.json のenginesを緩和)だと electron:build, electron:serve は動くが test:unit がひとつfailするので、まだ何か解決が必要そうです。

>  1) HowToUse.vue
>       can mount:
>     Uncaught TypeError: Cannot read properties of undefined (reading 'render')
>      at ...\voicevox\dist\js\webpack:\src\components\HowToUse.vue:11:27
