### ISSUE TITLE
Windowを閉じるときの保存確認ダイアログのボタンを、一般的なYes/No/Cancel形式にする

### ISSUE THREAD

**Issue by shigobu** [VOICEVOX/voicevox#467]
## 内容
VOICEVOXで行った変更を保存せずにWindowを閉じると、変更を破棄するかどうかの確認ダイアログが表示されます。
現在、このダイアログの問いは「破棄しますか？」で、選択肢は「OK」「キャンセル」です。

しかし、他の多くのアプリでは問いが「保存しますか？」で、選択肢は「保存する」「保存しない」「キャンセル」です。
他のアプリの使用者にとっては、問いが逆で選択肢の数も異なるので、意図せず変更を破棄してしまう恐れがあります。

慣例に則りVOICEVOXも、問いを「保存しますか？」に変え、選択肢を「保存する」「保存しない」「キャンセル」に変更したほうが良いと思います。

### Pros 良くなる点

他のアプリと統一され、他のアプリに慣れているユーザーにとって使いやすくなる。

### Cons 悪くなる点

今のVOICEVOXに慣れたユーザーが、仕様変更により混乱する。

## VOICEVOXのバージョン

0.8.0

## OSの種類/ディストリ/バージョン

Windows 10 Home 20H2

## その他

特に無し。

**Comment by Hiroshiba** [comment]
良いと思います！！
「保存しますか？」という内容にすると、保存するための処理が発生するのでちょっとむずかしいかもしれません。
一旦「破棄しますか？」→「破棄する」「キャンセル」にするプルリクエストを作ってみて、行けそうだったら「保存しますか？」も挑戦するという手もありそうだなと思いました！

**Comment by shigobu** [comment]
挑戦してみます。
ただ、時間がかかるかもです。

**Comment by Hiroshiba** [comment]
ぜひぜひ！！

**Comment by shigobu** [comment]
#471 と競合しそうなので、マージされてから作業します。

**Comment by y-chan** [comment]
#1238 にて解決されました
closeします
