### ISSUE TITLE
Nvidia製GPUを搭載していないパソコンで「対応するGPUデバイスが見つかりません」ダイアログボックスの内容を変更して欲しい。

### ISSUE THREAD

**Issue by arigayas** [VOICEVOX/voicevox#479]
## 内容
CPU版VOICEVOXの `設定`→`オプション`で表示される画面にGPUエンジンが選べるようになっている。

![image](https://user-images.githubusercontent.com/11251874/141646151-320b3585-2d1a-4850-ae3b-ce008a8f28fd.png)

### Pros 良くなる点

CPU版をダウンロードしたのにGPUエンジンが選べるようになっているのが、もやっとする人がいなくなる。

### Cons 悪くなる点

設定画面からGPUが消えると GPU版の存在を忘れてしまう可能性がある。

## VOICEVOXのバージョン

0.8.2

## OSの種類/ディストリ/バージョン
*   Windows 10 Pro 64bit 20H2

## その他

関係ありそうなissue
#298

**Comment by Hiroshiba** [comment]
Issueありがとうございます。

> 設定画面からGPUが消えると GPU版の存在を忘れてしまう可能性がある。

こちらに書かれているConsがまさしく気になっていて、より速いGPU版があることをほのめかしたいと思っています。
とはいえ切り替えられてしまうのは問題だと思います。

- https://github.com/Hiroshiba/voicevox/issues/298

とかなり内容が近そうですが、異なる点はどの辺りでしょう？

**Comment by arigayas** [comment]
> こちらに書かれているConsがまさしく気になっていて、より速いGPU版があることをほのめかしたいと思っています。

ほのめかしたいのであれば、現在のCPU版VOICEVOXの `設定`→`オプション`で表示される画面にGPUエンジンが選べるUIになっているのは良いと思います。

>   #298
とかなり内容が近そうですが、異なる点はどの辺りでしょう？

ほぼ同じだと思いましたが追加コメントを書こうと考えている内に
「対応するGPUデバイスが見つかりません」ダイアログボックスを変更する提案がしたいのだと気付きました。

具体的には「対応するGPUデバイスを搭載していないパソコン」で `GPU`をクリックして表示される「対応するGPUデバイスが見つかりません」ダイアログボックスの`変更しない` と `変更する` のボタンを`OK`ボタンのみにして
文章を「GPUモードの利用には、メモリが3GB以上あるNVIDIA製GPUが必要です。
対応するグラフィックスカードを搭載するパソコンにてお試しください。」というような文に変更するのが良いかもしれないと思いました。
![image](https://user-images.githubusercontent.com/11251874/141667499-83e47912-7fcf-4ca5-bbd0-c7e78d4684f4.png)

「対応するGPUデバイスが見つかりません」ダイアログボックスの「`変更する`」ボタンをクリックしても、
ほとんどの場合「音声合成エンジンエラー」になってしまってCPUモードに戻すまで音声合成が使用できないと想像できるからです。
![image](https://user-images.githubusercontent.com/11251874/141667789-9cd15897-230b-44af-a7ab-c918b06b7c77.png)

余談ですが現在、グラフィックスカードはRadeon RX550 ビデオメモリ2GBを使用中です。

**Comment by Hiroshiba** [comment]
なるほど！
とりあえず、タイトル的には改善したい（enhancement）というよりバグ報告に近いかなと思ったので、bugラベルにします。

挙動を変更した方が良さそうというのは納得です。
解決には、 https://github.com/Hiroshiba/voicevox/issues/298 にあるとおりコアに機能追加が必要かなと思います。

**Comment by arigayas** [comment]
現状の仕組みで「対応するGPUデバイスを搭載していないパソコン」かどうかを
恐らく判定出来ているので早急にVOICEVOXコアに機能追加する必要は無いと思います。
（CPU/GPUのモード判定のAPUがあれば拡張性は上がそうだと思いますが）

### 手順
1. 「対応するGPUデバイスを搭載していないパソコン」でCPU版VOICEVOXを起動します。
2. 「設定」→「オプション」で「設定/オプション」を表示します。
3. 「エンジン」の「エンジンモード」の「GPU」をクリックします。
4. 「対応するGPUデバイスが見つかりません」ダイアログボックスを表示します。

### 現状
5-a. 説明文：「GPUモードの利用には、メモリが3GB以上あるNVIDIA製GPUが必要です。
このままGPUモードに変更するとエンジンエラーが発生する可能性があります。本当に変更しますか？」 「変更しない」ボタンと「変更する」ボタンがある。
6-a. 「変更する」ボタンを押すと「音声合成エンジンエラー」ダイアログボックスが表示されてCPUモードに戻すまで音声合成が使用できない。


### 期待する動作というか提案
5-b. 説明文：「GPUモードの利用には、メモリが3GB以上あるNVIDIA製GPUが必要です。
適合するグラフィックスカードを搭載するパソコンにてお試しください。」というような文に変更して「OK」ボタンのみにする。
6-b. 「OK」ボタンを押すと「対応するGPUデバイスが見つかりません」ダイアログボックスを閉じる。
7-b. 「設定/オプション」画面の「エンジン」の「エンジンモード」が「CPU」が選択されている状態になる。

**Comment by Hiroshiba** [comment]
なるほどです、よくわかりました！

個人的には、ダイアログが出たけど覚悟の上で変更可能になっていた方がいいかなと思います。
理由は、例えば3GBメモリもなくても実は動くので、試してみたいという人が通れるようにしたいためです。
他の理由としては、将来GPUの型番などが変わって判定ロジックにバグが発生した時に無視できるようにしたい、とかです。

一方、 @arigayas さんが作ってくださったこのissueのタイトルの通り、「CPU版なのにGPUモードが選べるのはおかしい」というのは僕もそう思います。
なのでコアに判別APIを実装しましょう！という提案をしていました。

**Comment by arigayas** [comment]
> 個人的には、警告のダイアログを出すだけにして、覚悟の上で変更可能になっていた方がいいかなと思います。 理由は、例えば3GBメモリもなくても実は動くので、試してみたいという人が通れるようにしたいためです。 他の理由としては、将来GPUの型番などが変わって判定ロジックにバグが発生した時に無視できるようにしたい、とかです。
> 
> 一方、 @arigayas さんが作ってくださったこのissueのタイトルの通り、「CPU版なのにGPUモードが選べるのはおかしい」というのは僕もそう思います。 なのでコアに判別APIを実装しましょう！という提案をしていました。

3GBメモリもなくても実は動くのであれば条件のメモリ量を下げても良いのでは？と思いました。

メモリ量以外は、了解しました。

確認なのですが今後、NVIDIA製GPU以外の AMD製GPUである Radeon 系のグラフィックスカードや Intel CPUに含まれるグラフィックス機能でGPUモードが動くようにする予定はあるのでしょうか？
もし予定がないor技術的に対応が難しいのであれば、これらの搭載パソコンには「期待する動作というか提案」になって欲しいなぁと思ってます。

**Comment by Hiroshiba** [comment]
> 確認なのですが今後、NVIDIA製GPU以外の AMD製GPUである Radeon 系のグラフィックスカードや Intel CPUに含まれるグラフィックス機能でGPUモードが動くようにする予定はあるのでしょうか？

可能性としてはありますが、かなり先の話だと思います。

> これらの搭載パソコンには「期待する動作というか提案」になって欲しいなぁと思ってます。

なるほどです！理由をお伺いしても良いでしょうか👀

**Comment by arigayas** [comment]
> > これらの搭載パソコンには「期待する動作というか提案」になって欲しいなぁと思ってます。
> 
> なるほどです！理由をお伺いしても良いでしょうか👀

確実にGPUモードが動かないパソコンの場合にGPUモードに変更する選択肢が示されるのは、あまり意味が無いと思ったからです。

**Comment by Hiroshiba** [comment]
> 確実にGPUモードが動かないパソコンの場合にGPUモードに変更する選択肢が示されるのは、あまり意味が無いと思ったからです。

なるほどです、よくわかりました！！
たしかに良い挙動ではないと思います。

前述の通り、メモリ量は起動の可否にあまり寄与しません。
なので、Nvidia製GPUを持っていない場合にはエラーが表示されるのが良いのかなと感じました。

**Comment by arigayas** [comment]
issueタイトルを変更した方が良さそうですね。
例えば、
Nvidia製GPUを搭載していないパソコンで「対応するGPUデバイスが見つかりません」ダイアログボックスの内容を変更して欲しい。
みたいに。

ここまで来るのに時間を取ってしまい申し訳ないです。😅

**Comment by Hiroshiba** [comment]
そうですね、タイトルを変えていただけると！

次はよりラリー回数を少なくできると良いですね！

**Comment by arigayas** [comment]
issueタイトルを変更しました。

**Comment by arigayas** [comment]
voicevox-windows-cpu-0.14.4.zipをダウンロードして、
エンジンモードの切り替え部分にマウスカーソルを持っていくとどうなるか確認しましたが、
CPU版ではGPUにエンジンモードの切り替えができないようになったので、
![image](https://user-images.githubusercontent.com/11251874/221235996-f49f10d7-96a8-4a20-8639-d32882bd2284.png)
このIssueは閉じても良いかもしれません。

私が思い付かない懸念事項が他にあるかもしれないのでCloseするかどうかは、Hiroshiba さんにお任せします。

**Comment by y-chan** [comment]
#1140 で解決されたものですね...!
#298 はリンクしていましたが、こちらはリンクしていなかったようです。
特に問題もなさそうなので、解決としてcloseしたいと思います！
ありがとうございました！
