### ISSUE TITLE
インストーラ使用時に不要なファイルが残る

### ISSUE THREAD

**Issue by takana-v** [VOICEVOX/voicevox#482]
## 不具合の内容
windowsでインストーラを使用した際に`%LOCALAPPDATA%\voicevox-updater\package.7z`が生成され、削除されずに残ります。
この現象は、「使い終わったダウンロード済みファイルを削除する」のチェックの有無にかかわらず発生します。
`package.7z`は`voicevox-0.8.2-x64.nsis.7z`と同じファイルです。
（SHA-256のハッシュ値が一致しました）
このファイルの有無はインストール/アンインストールに影響しないと思われます。

### 現象・ログ
内容と同じなので省略

### 再現手順
VOICEVOX.Web.Setup.0.8.2.exeを実行、インストールを完了する。

### 期待動作
不要なファイルを残さずにインストーラが終了する。

## VOICEVOXのバージョン
0.8.2

## OSの種類/ディストリ/バージョン
Windows10 21H1

## その他
CPU版のインストーラーでは、`%LOCALAPPDATA%\voicevox-cpu-updater\package.7z`が残ります。

## 追記
VOICEVOXをアンインストールしても消えませんでした。
（Geek Uninstallerを用いても残っていました）

**Comment by Hiroshiba** [comment]
おっと、本当ですね･･･
元の7zの容量、GPU版なら2.7GBほどあるので、問題ないなら消してしまったほうが良い気がします。

electron-bulider辺りが差分アップデートとかに用いるのでしょうか。
ちょっと調べましたが情報が見つかりませんでした。謎です。

**Comment by Hiroshiba** [comment]
ご要望の声 https://twitter.com/tvanime_yukkuri/status/1514464720882860037

nsis周りの設定フラグを１つ変えるだけで勝手に消してくれそうな気もするのですが･･･どうなんだろう。

**Comment by madosuki** [comment]
[https://www.electron.build/configuration/nsis.html](https://www.electron.build/configuration/nsis.html)
deleteAppDataOnUninstallオプションがあるようですがこれはワンクリックインストーラーの時のみ有効のようです。
ワンクリックインストーラーだとインストール先指定などができなくなりますので、NSISスクリプトで頑張ることになると思います。

**Comment by takana-v** [comment]
differentialPackageをfalseにして試してみましたがうまくいきませんでした...
https://github.com/takana-v/voicevox/commit/ef8b3a5970d02b1dedffe978fc344132e92ca769

- https://github.com/electron-userland/electron-builder/issues/4682
