### ISSUE TITLE
途中から再生する機能

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#491]
## 内容

調整していると、調整している箇所から音声を聞きたいことが結構あるので、実装したいです。
（ツイッターでもちらほら要望を見かけます）

VOICEVOXは全音素の長さの情報を持っているので、どこからなんの音が始まるかわかるはず。

### 実現方法

どういうUIにするかがとても難しいです。

VOICEROIDは上のバーをクリックしてから再生すれば途中から再生になる。かなり気づきにくい。
![image](https://user-images.githubusercontent.com/4987327/142268964-92255cec-3bd2-40ac-b448-2878d38f55a2.png)

CeVIOは空いてるところをクリックするとそこから再生されるけど、今再生中のステートなのかがわからない。
![image](https://user-images.githubusercontent.com/4987327/142269141-9004ecb5-6768-410c-972b-bb4dc29fc0b7.png)

## VOICEVOXのバージョン

0.?.0

## その他

要望ツイート
https://twitter.com/ichico_3939/status/1460982938615435267

**Comment by Hiroshiba** [comment]
２つアイデアがあります。

* 再生中の文字と同列にスピーカーマークを表示する。普段は透明だけどマウスカーソルを合わせるとスピーカーマークが出て途中再生できる。
* AudioDetailの上か下にシークバーみたいなのを表示し、再生時間に応じて範囲が広がる・狭まるようにする。マウスカーソルを近づけると縦方向に大きくなり、クリックすればそこから再生できる。

**Comment by y-chan** [comment]
モーラ単位で制御できないかなと思いましたが、現在再生している部分を表すのが難しそうだと思いました(主にAudioAccentのCSSなど)
アクセント句単位なら何とかできそう？と少し思いました(以下は表示をいじってみただけです)
![image](https://user-images.githubusercontent.com/34832037/144932530-698770f0-2f0c-4fc2-b3ec-8b242e0efc68.png)

現状再生しているアクセント句を赤い色のバックグラウンドでフォーカスしていく感じを想定しています。
