### ISSUE TITLE
翻訳サポート / Translation Support

### ISSUE THREAD

**Issue by nagotown** [VOICEVOX/voicevox#498]
## 内容

翻訳サポート / Translation Support

海外のユーザーにも読みやすくするために / Making it easier for foreign users to read.

### Pros 良くなる点

VOICEVOXをより多くの人に読んでもらうために / Making VOICEVOX more accessible.

### Cons 悪くなる点

なし / None.

### 実現方法

「string」を使って（？）/ Using strings?

> メモ：自分の日本語の話し方で誰かを不快にさせたくなかったので、機械翻訳を使用しました。不正確な表現があったらごめんなさい。
> Note: Sorry for the machine translation, I didn't want to offend with my own Japanese speaking... Sorry if the translation is wrong.

**Comment by Hiroshiba** [comment]
@nagotown さん

issueありがとうございます！
ソフトウェア内のどの辺りが翻訳されていているのが望ましいと思いますか？
理由も合わせて知りたいです。

僕も機械翻訳を使用しています。不正確だったらすみません。

---

Thanks for the issue!
What parts of the software do you think should be translated?
I would like to know why as well.

I'm using machine translation too. I'm sorry if it's inaccurate.

**Comment by nagotown** [comment]
I can't read kanji well, and I'm sure other English users would like to use the software easily too! I wouldn't mind making a translation for English.

---

私は漢字がうまく読めないので、他の英語ユーザーも簡単に使いたいと思っているはずです 英語版の翻訳を作ってもいいと思います。

**Comment by Hiroshiba** [comment]
なるほどです！

海外の方にもぜひ使ってもらいたいとは思いますが、それは海外の言語で音声合成ができるようになったタイミングで考えるのが良いのかなと思っています。
なので、日本語音声合成しかない今は、まだサポートしなくても良いのかなと感じました。

一旦closeしますが、機会があればまたopenしたいと思います！

---

I see what you mean!

I would love to have people from overseas use it, but I think it would be better to consider that at the time when text-to-speech becomes available in foreign languages.
So, I felt that we don't have to support it yet when we only have Japanese text-to-speech.

I'm going to close this once, but I'll open it up again when I get the chance!

**Comment by nagotown** [comment]
Ah, sorry, I meant UI translation, not for the text to speech!
---
あ、すみません、音声合成ではなく、UI翻訳のことでした。

**Comment by Hiroshiba** [comment]
混乱させてしまいすみません。
音声合成の翻訳ではなく、UIの翻訳について議論していることは承知していました！

UIの翻訳を行うのは、音声合成の英語版がもしできたらにしたいと思います。

---

Sorry for the confusion.
I was aware that we were discussing the UI translation, not the text-to-speech translation!

Sorry for the confusion.
I was aware that we were discussing about translating the UI, not the speech synthesis!

I would like to translate the UI in the future if we ever create an English version of Text-to-Speech.

**Comment by Hiroshiba** [comment]
翻訳表をスプレッドシートにして管理するアイデアを頂いたのでメモ追記です。
スプレッドシート→jsonはこちらでできそう？
https://github.com/VictorCazanave/google-sheets-i18n-generator

**Comment by grape4842** [comment]
README.mdを翻訳してみたのでメールでお送りしますのでご確認ください。

**Comment by Hiroshiba** [comment]
@grape4842 翻訳ありがとうございます！
しかし我々ではメンテナンスができないのと、このissueにあるように海外に向けた展開を視野に入れるのはもう少し先だと考えているため、OSS内に含めることはできません。

OSSに含めるのは今は難しいですが、 @grape4842 さんがブログ記事などで翻訳内容を公開するとかはもうでしょう？
その言語が母語の方にはとても有用だと思います！

**Comment by Hiroshiba** [comment]
（間違えてreopenしてしまいました）

**Comment by Patchethium** [comment]
Made a brief [gist](https://gist.github.com/Patchethium/8f116e1a13dfbe712b65b80ba63cc6ae) with 15 minutes, this should be enough for English speakers looking for Japanese TTS readme while being not able to read Japanese.
