### ISSUE TITLE
アクセントからイントネーションを全て再設定する機能がほしい

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#524]
## 内容

VOICEVOXの調整は難しいという意見をよく聞いていて、僕もそうだなと思っていたのですが、
でもよくよく考えると調整いらずで一発で良いイントネーションを引くことも結構ある気がしました。
そしてアクセントを変更したりしているとだんだん迷子になっていく気がします。

これはもしかしたら、アクセントを変更しても、そのアクセント句のイントネーションだけが変わる仕様なため、
前後のイントネーションと合わなくなりがちなのが原因なのかなと少し思いました。

どれくらい変わるのかわかりませんが、アクセントからイントネーションをリセットする機能がほしいなと思いました。

### Pros 良くなる点

イントネーションの迷子を防げるかも

### 実現方法

とりあえずデバッグも兼ねて、イントネーションを再設定するショートカットキーを実装してから、
便利だったらボタンの場所を考える、とかが良い気がしています。

## VOICEVOXのバージョン

0.9.0

**Comment by k-chop** [comment]
唐突ですがこちら実装してみました（事前に着手宣言するの忘れてました、すみません🙇）
![Animation](https://user-images.githubusercontent.com/241973/161277171-ea93a4ee-cecc-446d-b85d-54fd30000237.gif)

`/mora_pitch` を叩いて返ってきた `AccentPhrase[]` を上書きして実現しています。
これからPR出してみます。

**Comment by Hiroshiba** [comment]
こちら、 @k-chop さんのおかげでとても良い機能が実装できました！
ということでissueをcloseしたいと思います。ありがとうございました！
