### ISSUE TITLE
キャラクターリソースをエンジンに含め、preview版ビルドを作る

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#533]
## 内容

CharacterInfoをエンジンから取って来るようにする予定です。

- https://github.com/Hiroshiba/voicevox/pull/450

今の製品版エンジン（0.9.3）はちょっとバグっていて、speakers_infoのデータが正しく取れていません。
なので↑のプルリクエストをマージすると、製品版エンジンを使ったエディタの開発できなくなってしまいます。

ということで、0.10のエンジンのプレビュー版ビルドを作成します。
ちょっと複雑な手順が必要になってしまうので、下記にまとめました。

### 実現方法

- [x] エディタのresource参照を最新版以外も指定できるようにする
  - [x] release-0.9にマージ
- [x] エンジンのresource参照を最新版以外も指定できるようにする
  - [x] release-0.9にマージ
- [x] resourceにreleaseブランチを作る
- [x] https://github.com/Hiroshiba/voicevox_resource/pull/3
- [x] （オプショナル）エンジンのリソースモックにキャラクターを２人追加
- [x] エンジンで0.10.preview.1ビルドする
- [x] https://github.com/Hiroshiba/voicevox/pull/450 をマージ
- [x] 周知用issueを作ってpinnedする

## VOICEVOXのバージョン

0.9.3

## その他

speakers_infoのデータが正しく取れていないのに気づけませんでした、すみません。。

**Comment by takana-v** [comment]
現在の状態ではresourceの画像ファイルの名前がmockと異なっており、正常に画像を取得できません。
resourceの方を変えてしまうとエディタのビルドの方に影響が出てしまうので、エンジン側で対応したいと思います。
`（オプショナル）エンジンのリソースモックにキャラクターを２人追加`と合わせて行いたいと思います。
ref https://github.com/VOICEVOX/voicevox_engine/issues/206

**Comment by Hiroshiba** [comment]
なるほど！！
エンジン側の方を合わせるという手がありますね！！
ぜひお願いしたいです！

**Comment by Hiroshiba** [comment]
エンジンのビルドを開始しました！
https://github.com/VOICEVOX/voicevox_engine/releases/tag/0.10.preview.1

**Comment by takana-v** [comment]
0.10.preview.1をチェックしたところ、speaker_info内のフォルダ名がuuidではありませんでした。
actionsを見るとCheckoutがスキップされていたのでキャッシュを使ってしまっているのかもしれません。

**Comment by shirowanisan** [comment]
横から失礼します。
0.10.preview.1でengine側のdummy1とdummy2のスタイルの順番違いが直っていないように思います。

dummy1
0.pngのスタイルが1_2　→ 正しくは1_1
https://github.com/VOICEVOX/voicevox_engine/blob/master/speaker_info/7ffcb7ce-00ec-4bdc-82cd-45a8889e43ff/icons/0.png
2.pngのスタイルが1_1　→ 正しくは1_2
https://github.com/VOICEVOX/voicevox_engine/blob/master/speaker_info/7ffcb7ce-00ec-4bdc-82cd-45a8889e43ff/icons/2.png

0_001~003のサンプル音声が「あまあま」　→ 正しくは「ノーマル」
2_001~003のサンプル音声が「ノーマル」　→ 正しくは「あまあま」


dummy2
1.pngのスタイルが2_2　→ 正しくは2_1
https://github.com/VOICEVOX/voicevox_engine/blob/master/speaker_info/388f246b-8c41-4ac1-8e2d-5d79f3ff56d9/icons/1.png
3.pngのスタイルが2_1　→ 正しくは2_2
https://github.com/VOICEVOX/voicevox_engine/blob/master/speaker_info/7ffcb7ce-00ec-4bdc-82cd-45a8889e43ff/icons/2.png

1_001~003のサンプル音声が「あまあま」　→ 正しくは「ノーマル」
3_001~003のサンプル音声が「ノーマル」　→ 正しくは「あまあま」

**Comment by y-chan** [comment]
@shirowanisan さん
現状で問題ないと思います。

というのも、VOICEVOXは公開当初、 @Hiroshiba さんの手違いによって「あまあま」スタイルの音声が提供されていた経緯があります。
https://twitter.com/hiho_karuta/status/1447133506161688578?t=t1BMLwwxI7UzY8MRNqLUaA&s=19

現状のVOICEVOXでは、過去バージョンとのプロジェクトファイルの互換性を保つために、speaker idの0と1の音声を「あまあま」スタイルのまま、変えずに保持しています。

なので、間違っている訳ではなく、意図して順番を変更しているものと思います。

**Comment by shirowanisan** [comment]
@y-chan おお、そうだったんですね。
了解です。仕様であるならば問題ありません。

**Comment by Hiroshiba** [comment]
> 0.10.preview.1をチェックしたところ、speaker_info内のフォルダ名がuuidではありませんでした。 actionsを見るとCheckoutがスキップされていたのでキャッシュを使ってしまっているのかもしれません。
> 
> 追記： おそらくエンジンのbuild.ymlの`matrix.voicevox_resource_version`が古いままなのが原因な気がします。 ブランチが無いのでPRをどこに出せばいいか分かりませんが...

おっと、ほんとですね･･･　ご指摘感謝です！
relase-0.10のbranchを作って修正してrelease作り直してみます。

**Comment by Hiroshiba** [comment]
周知用issueも作ったので、このissueはcloseします！
