### ISSUE TITLE
Debian上でinstaller_linux.shが正常動作しない

### ISSUE THREAD

**Issue by YTJVDCM** [VOICEVOX/voicevox#540]
## 不具合の内容

`installer_linux.sh`が、Debian環境でのlibsndfileのインストールチェックに失敗し、インストールができない。

### 現象・ログ

インストール時に、`libsndfile1`がインストールされている場合でもlibsndfileがインストールされていない趣旨のメッセージが表示され、インストールが停止する。

おそらく、libsndfileのライブラリをチェックするために使用しているldconfigが、Debianにおいては一般権限で使用できない(おそらく、デフォルトでPATHが通っていない)ため、インストールスクリプト内のチェックで失敗判定となり、結果として、表記上はlibsndfileがインストールされていないというメッセージと共に、インストールが停止します。

### 再現手順

Debian 10環境上で、必要なパッケージをインストールした上で、`installer_linux.sh`(あるいはインストーラー)を一般権限で実行。

## VOICEVOXのバージョン

0.9.3

## OSの種類/ディストリ/バージョン

Debian 10 (buster) x86_64

## その他

ldconfig自体は一般権限でも実行は可能でなので、`installer_linux.sh`120行目のldconfigを絶対パス(`/sbin/ldconfig`)で指定することでインストールはできるようになりますが、この変更がDebian以外のディストリビューションにどのような影響を及ぼすか不明です。
(少なくとも、Arch Linuxでは実行できました)

**Comment by aoirint** [comment]
一般ユーザでのldconfigの実行を再現してみました（本来は`ldconfig -p`ですが）。
たしかに、DebianではデフォルトでPATHが通っていないようなので、インストーラが停止しますね...

```
$ docker run --rm -it debian:bullseye-20211115 bash
root@0f4e2076bc36:/# adduser user --disabled-login --gecos ""
Adding user `user' ...
Adding new group `user' (1000) ...
Adding new user `user' (1000) with group `user' ...
Creating home directory `/home/user' ...
Copying files from `/etc/skel' ...
root@0f4e2076bc36:/# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
root@0f4e2076bc36:/# ldconfig
root@0f4e2076bc36:/# su - user
user@0f4e2076bc36:~$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
user@0f4e2076bc36:~$ ldconfig
-bash: ldconfig: command not found
```

インストーラ内で一時的に/sbinなどをPATHに追加する修正をするのがよさそうだと思いました。

**Comment by Hiroshiba** [comment]
linuxのサポートはubuntuだけとかにしてしまっても良いのかなとちょっと思いました。
優先度は低めにしつつ、誰か解決策がわかる方がいればプルリクエストを待つ感じにしようかなと思います。
