### ISSUE TITLE
「長さ欄を表示」ショートカットキーが初期化できない

### ISSUE THREAD

**Issue by y-chan** [VOICEVOX/voicevox#541]
## 不具合の内容

題の通り、migrationで処理されており、以下の`defaultHotkeySettings`に含まれていないためです。
https://github.com/VOICEVOX/voicevox/blob/febf1a4df9b8cab885b4d272e78d3cd97c330744/src/background.ts#L70-L139
https://github.com/VOICEVOX/voicevox/blob/febf1a4df9b8cab885b4d272e78d3cd97c330744/src/background.ts#L220-L233

### 再現手順

「キー割り当て」の設定を開き、「長さ欄を表示」の設定を変更後、初期化を試みる

### 期待動作

初期化ボタン押下で初期化できる

## VOICEVOXのバージョン

0.9.3

## OSの種類/ディストリ/バージョン

すべての環境で起きうる

## その他

修正はそこまで難しくありません(`defaultHotkeySetting`に長さ欄のものを追加するだけです)が、今後ショートカットキーが増え、同じようにマイグレーションで処理しなければならない時に以下のようなことをいい感じにできる関数を用意しておくとよいかもしれません。
- 設定済みショートカットキーと被る場合はキーを割り当てない処理 
 https://github.com/VOICEVOX/voicevox/blob/febf1a4df9b8cab885b4d272e78d3cd97c330744/src/background.ts#L226-L230
- マイグレーション設定を所定の場所に差し込む処理
  https://github.com/VOICEVOX/voicevox/blob/febf1a4df9b8cab885b4d272e78d3cd97c330744/src/background.ts#L231
  - 現状はspliceで直接数字(index)を指定して置き換えていますが、findなどを利用し、いい感じに所定の場所に差し込めるとよさそうです。

good first issueにしてみます。どなたか取り組んでみませんか？

**Comment by yuqquu** [comment]
取り組んでみます。

**Comment by y-chan** [comment]
@yuqquu お願いします...!
Assignしますね!
