### ISSUE TITLE
macOSにおいて Command + Q でアプリケーションを終了できるようにしたい

### ISSUE THREAD

**Issue by PickledChair** [VOICEVOX/voicevox#546]
## 内容

macOS の GUI アプリケーションは通常 Command + Q のキーボードショートカットで閉じることができます。しかし現在、VOICEVOX エディターで Command + Q を押すとウィンドウが閉じるだけであり、アプリケーションの終了は行われません。追加の操作（OSネイティブのメニューから終了操作をする等）でこの状態からアプリケーションを終了することは可能ですが、Command + Q で「ウィンドウを閉じる」「アプリケーションを終了する」の２つの作業が両方とも行われることが望ましいです。

現在後者が行われないようになっているのは、electron の "window-all-closed" イベントが発生した時、以下のように macOS だけ `app.quit();` を実行していないことが原因です。

https://github.com/VOICEVOX/voicevox/blob/9fc7098e50e5f0cac704fb40f71eef03f54c6311/src/background.ts#L742-L746

electron に詳しくないので推測になってしまいますが、この実装の意図は、macOS における一般的なアプリケーションの挙動に合わせて、**アプリケーションウィンドウを全て閉じることがアプリケーションの終了を引き起こさない**ようにすることにあるのだと思います。これは「ウィンドウを閉じる」ボタンを押す時には期待通りに機能しますが、Command + Q 操作では続いて「アプリケーションを終了する」ことが期待されるので、この場合は期待通りになっていません。

（備考： [electron のドキュメント](https://www.electronjs.org/ja/docs/latest/api/app#%E3%82%A4%E3%83%99%E3%83%B3%E3%83%88-window-all-closed)によると、macOS において Command + Q 操作をしても "window-all-closed" イベントは発火しないみたいです。しかし VOICEVOX エディターでは以下のように "CLOSE_WINDOW" イベントで "window-all-closed" が発生し、ここからアプリケーション終了処理の続きが行われます。）

https://github.com/VOICEVOX/voicevox/blob/9fc7098e50e5f0cac704fb40f71eef03f54c6311/src/background.ts#L572-L576

### Pros 良くなる点

macOS の一般的なアプリケーションの挙動と同じく、Command + Q で一発でアプリケーションを終了することができるようになる。

### Cons 悪くなる点

実装方法によっては、macOS の一般的なアプリケーションと異なり、ウィンドウを閉じる操作をするとアプリケーションの終了も同時に行われるようになる（「実現方法」で後述します。そちらでも触れる通り、この点は気にしなくても良いと思われます）。

### 実現方法

２つ考えられます。

- 問題の if 分岐をなくす
- 何らかの手段で Command + Q 操作が行われたことを検出し、その時だけアプリケーションの挙動を変える

前者が現実的です。この場合、「Cons 悪くなる点」で触れたように一般的な macOS アプリケーションとは異なり、「ウィンドウを閉じる」ボタンを押す操作でもアプリケーションを終了できてしまいます。しかし、このように振る舞う macOS アプリケーションがないわけではありません（自分の観測範囲では、Qt製のアプリケーションも同様の挙動を示すことが多いです）。なので、この問題点は無視できるものだと思います。

後者は大変そうです。

## VOICEVOXのバージョン

0.9.3

## OSの種類/ディストリ/バージョン

macOS Monterey version 12.0.1, Intel Mac

## その他

- 上述の if 分岐の正確な意図についてご存じの方は教えてくださると幸いです。
- if 分岐を外した時の macOS 上での挙動が他の OS の場合と同じになるかどうかはまだ確認していません。後ほど Linux 上での動作と比較してみたいと思います。
- より良い案がありましたらご提案くださると幸いです。

**Comment by Hiroshiba** [comment]
issueありがとうございます！
僕もmacを使うので分かるのですが、たしかにcmd+Qはアプリケーションの完全停止になっていることが望ましいと思います。

なぜcmd+Qで完全停止しないようになっているのかは、こちらのプルリクエストの経緯があったためです。
参考になりますと幸いです。

- https://github.com/VOICEVOX/voicevox/pull/471

**Comment by PickledChair** [comment]
情報ありがとうございます。過去の変更を追ってみました。自分が理解した範囲では次のことが言えると思います：

1. 終了時に確認ダイアログが表示されるバージョンより前の仕様では、終了処理は単純に `app.on("quit", () => { ... });` 内で完結していたので、electron のデフォルトの動作に従って Cmd+Q で "window-all-closed" が発火することなく、素直に終了したと考えられる（一方、Cmd+W や閉じるボタンではmacOS流にアプリが起動したままになる）。
2. 終了時に確認ダイアログが表示される仕様に変更され、かつ Linux での不具合が修正されたバージョンでは、終了処理は**全てのOSで必ず "window-all-closed" を経由する**ようになったので、今まで Cmd+Q 操作に影響を与えなかった "window-all-closed" の処理が Cmd+Q でも走るようになった。これにより macOS では一度の Cmd+Q では終了できなくなった（一度目の Cmd+Q で `willQuit` フラグが立っているので、二度目の Cmd+Q では終了処理の続きから始まり、正常終了する）。

また、教えてくださった Issue のコメント https://github.com/VOICEVOX/voicevox/pull/471#issuecomment-968123903 で

> 整理されたコードを眺めていて思ったのですが、Cmd+Qのapp.quit()もCmd+Wのwin.close()も行き着く先はアプリ終了なので、どちらが起因かは区別する必要は無いのかなと思いました。

と言及されていました。これはmacOSにおいても、Cmd+QとCmd+Wの両方でアプリ終了に達するという仕様になるはずだった（実際にはそうならなかった）、という解釈でよろしいでしょうか。

以上のことを考え合わせると、"window-all-closed" の際のmacOS判定をなくすことが正解のような気がしています。Windows版やLinux版の動作に影響を与えない解決策でもあります。

**Comment by madosuki** [comment]
#471 を出した者です。
https://github.com/VOICEVOX/voicevox/pull/471#issuecomment-968123903 このhiho氏のコメントは当該PRに私が貼った[https://qiita.com/hoto17296/items/72d3526bef332f9ce027](https://qiita.com/hoto17296/items/72d3526bef332f9ce027)の記事に基づいてるものだと思いますが、この記事だとどっちもアプリ終了になるように見えるからだと思います。

Cmd+WとCmd+Qで挙動をわけるとコードが複雑になるのでどっちもアプリケーションの終了の挙動の方が良いんじゃないかなと個人的には思っています。

```window-all-closed```のifを残した理由としては私がMacを所持していないので諸々の挙動を実際に確認できないから、なので動作が確認出来ておらっしゃるようなので判定を消すことに賛成します。

**Comment by Hiroshiba** [comment]
僕もmacユーザーですが、cmd+wはアプリケーションは消えない感があるのですが、処理が複雑になりそうなので @madosuki さんと同意見で、どちらにせよアプリ完全終了で良いかなと感じました！

**Comment by PickledChair** [comment]
@madosuki @Hiroshiba ご意見感謝します。macOS判定を取り除く方向でPR出そうと思います。
