### ISSUE TITLE
同じアクセント句にあるピッチや音の長さを一緒に増減できるようにする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#551]
## 内容

調整していると、このアクセント句にある音高を全部上げたい、みたいなことが多々あります。
一緒に全部上げ下げできると結構便利だと思います。

### Pros 良くなる点

調整体験が改善する

### Cons 悪くなる点

UIが思いつかない

### 実現方法

良いUIが思いつきません･･･

ちなみにCeVIOには長さ設定で似たような機能があります。（ピッチはたぶん一気に変更できない？）
https://user-images.githubusercontent.com/4987327/144710036-8023ae85-da51-4f9d-bd1d-00948453aee5.mp4

shiftやctrlを押しながら上下することで一気に変更するUIがあるらしいです。
同じように、何かを押しながらドラッグ、もしくはスクロールが良い感じかも・・・？
https://twitter.com/boroboroborobor/status/1467117930332573698

## その他

実際にご要望もいただきました
https://twitter.com/boroboroborobor/status/1467091366228348930

**Comment by qwerty2501** [comment]
> shiftやctrlを押しながら上下することで一気に変更するUIがあるらしいです。
同じように、何かを押しながらドラッグ、もしくはスクロールが良い感じかも・・・？

学習コストはかかりますが修飾キー押しながらドラッグがユーザーにとっては楽そうですね。
音楽界隈ではあるとのことですが、恐らくDAW系でしょうかね。上手く似せることができれば違和感を与えずに済みそうです。

私はCeVIO持ってないのではっきりとは言えませんが、見た感じCeVIO UIに似せるのだとかなり実装コストが重そうですし、ピッチなどはどうするのかという問題がのこりそうです。

**Comment by Hiroshiba** [comment]
ですね、修飾キー押しながらドラッグとかスクロールで操作できるのが良いと改めて感じました！

こちら、ユーザーからは多く望まれている（と思われる）機能なので、ぜひ実装したいところです･･･！

**Comment by qwerty2501** [comment]
使用感似せてるか確認しつつ実装したいところですが、DAWで有名どころって多分Windowsでしか動かないですよね。私はUbuntuしかもってないのでちょっと厳しいかも・・・
Windows持ってる人に任せたほうが良さそうですが誰もいなければやってみます

**Comment by Hiroshiba** [comment]
おお、ぜひお願いしたいです！！　アサインさせていただきます！

VOICEVOXを使われる方の大半は、たぶんDAWを触れたことがない方ばかりだと思うので、使用感を似せなくても良いのかなとちょっと思いました。
使いやすければ何でも良いかと・・・！

**Comment by qwerty2501** [comment]
ctrlで同じAccentPhrase内のmora全て、ctrl+shiftでそのセリフ内の全てのAccentPhrase内のmora全てを一緒に動かせるようにしようとしたのですが、mora調整ですでに修飾キーが使用されておりどうするべきかちょっと困ってます。

既存実装で使用されてる修飾キー
- ctrl+scroll:各値を微量調整できるようにしてるので競合する
- shit+scroll:スクロールによる値変更を無効化するようになってるので競合する(ヘルプ記載なし)

あと残ってるのはaltぐらいですがaltで全体化させるのは個人的に違和感がありちょっと迷ってます。
既存機能と競合しないようにするには使用する修飾キーをalt keyにし、提供する機能を同じAccentPhrase内のmora全ての値を一緒に変更できるようにするのみにしますか？

**Comment by Hiroshiba** [comment]
altキーで良い気がしました！！
もしくは↓にある強調表示をしつつ、スライダー以外の場所であれば全体調整ができるというのもありかなと思いました。

- https://github.com/VOICEVOX/voicevox/pull/578

**Comment by qwerty2501** [comment]
とりあえずaltで同じAccentPhrase内のmora上げれるように実装しちゃいます！

**Comment by yuqquu** [comment]
遅レスかもですが、ドラッグ等で複数選択をして、その部分を増減できるようにするとわかりやすくて便利かもしれません。
同じアクセント句内でも途中までの一部分しか変更したくない場面もありそうです。
実装は大変になりそうですが…(ここまでやるとなると別のissueになりそうですかね)。

テキスト欄に関しては似たようなissueがあります: ref: #457

操作について：
[DAWのREAPER](https://www.reaper.fm/)は右クリック＆ドラッグで音符を複数選択するインターフェースでした。
[MIDIシーケンサーのDomino](https://takabosoft.com/domino)は範囲選択モードに切り替えて複数選択できるようになっていました。
操作についてはこのあたりが参考になるかもしれません。

[REAPER](https://user-images.githubusercontent.com/50493934/147564334-3390ab14-423e-4034-88fc-f9ded8733e81.mp4)

[Domino](https://user-images.githubusercontent.com/50493934/147564655-8f6155a9-1dba-4b9f-ace0-87868b106cf1.mp4)

上がREAPER、下がDominoでの複数選択の様子です。


vueをやったことがないので提案だけになってしまいますが…！

**Comment by Hiroshiba** [comment]
なるほど、確かに複数選択＋調整も便利そうだと思いました！！
ただやっぱり実装コストがかなり上がってしまう（モーラごとの選択状態というのを作らないといけない）ので、まずはアクセント句ごとが良いのかなと感じました！

**Comment by yuqquu** [comment]
たしかに、少し急ぎすぎました。
まずはアクセント句で様子見ですね。

**Comment by Hiroshiba** [comment]
alt + スクロールやドラッグで調整可能になったのでOK･･･！

派生タスクとしてこちらがあります

- https://github.com/VOICEVOX/voicevox/issues/646
