### ISSUE TITLE
macOSにおいてタイトルバーの三色ボタンを左側に移動したい

### ISSUE THREAD

**Issue by PickledChair** [VOICEVOX/voicevox#554]
## 内容

以前の PR https://github.com/VOICEVOX/voicevox/pull/430 で、タイトルバーにおける三色ボタン（「閉じる・最小化・最大化」ボタン）の位置を Windows, Linux と同様に右側のままにしたのですが、やはり左側にあった方がMacユーザー的には自然だと感じました。以下のようなデザインを考えてみました。

|        | タイトルバーのデザイン |
| :--- | :---: |
| 現在 |  <img width="801" alt="voicevox_mac_title_bar_previous" src="https://user-images.githubusercontent.com/41382894/144712124-2bbf7f42-fe2b-437a-bd53-6e700b94c361.png"> |
| 試案 |  <img width="801" alt="voicevox_mac_title_bar" src="https://user-images.githubusercontent.com/41382894/144712149-6d52e3d9-11c7-4009-b830-ff518a5d11f4.png"> |

### Pros 良くなる点

Macユーザーの UX が向上する

### Cons 悪くなる点

一部コンポーネントの再設計が必要

### 実現方法

「閉じる・最小化・最大化」ボタンのみ別のコンポーネントに切り出して、macOSの時のみ、[voicevox/src/components/MenuBar.vue](https://github.com/VOICEVOX/voicevox/blob/918458cfcf1a679d643fd8cee34f39b02b22c014/src/components/MenuBar.vue) で左に表示させている VOICEVOX のロゴの代わりに表示します。それ以外のOSでは今まで通り [voicevox/src/components/TitleBarButtons.vue](https://github.com/VOICEVOX/voicevox/blob/918458cfcf1a679d643fd8cee34f39b02b22c014/src/components/TitleBarButtons.vue) で右側に表示します。

## VOICEVOXのバージョン

0.9.3

## OSの種類/ディストリ/バージョン

macOS Monterey version 12.0.1, Intel Mac

## その他

良いコンポーネント名が思いつきませんでした。良い案がありましたらご提案くださると幸いです。デザインももっと良いものがあればご提案ください。
また、この変更で生じうる問題があればご指摘ください。

**Comment by Hiroshiba** [comment]
良いと思います！！

**Comment by PickledChair** [comment]
他の案も一応出しておきます。結構悩ましいです。

### VOICEVOX アイコンを表示する（ボタン領域の背景は無地）

<img width="801" alt="voicevox_mac_titlebar" src="https://user-images.githubusercontent.com/41382894/144730579-418d015a-067b-4a47-97e0-f3cf66823b71.png">

### VOICEVOX アイコンを表示する（ボタン領域の背景は `bg-primary-light` ）

<img width="801" alt="voicevox_mac_titlebar_green" src="https://user-images.githubusercontent.com/41382894/144730641-cf727cd0-dbd9-48c6-94fd-bae6057b19b1.png">

（ちょっとこれは自分でもない気がします😅）

### VOICEVOX アイコンなし（ボタン領域の背景は無地）

<img width="801" alt="voicevox_mac_titlebar_without_icon" src="https://user-images.githubusercontent.com/41382894/144730621-ed0aeb90-6f85-4b50-8945-e4064b905443.png">

**Comment by MT224244** [comment]
DiscordやvscodeのMac版を見てみても左上のアイコンは無くなって背景色も特に変えていないようなので、個人的には一番下の案を推したいです。
とはいえ私はMacユーザーではないので、あまり強い意見ではないです…。

**Comment by PickledChair** [comment]
ご意見ありがとうございます。
自分も特に強いこだわりがあって最初の案を考えたわけではない（元のデザインに近寄せただけ）ので、最後の案で良い気がしてきました。
もう一人くらい最後の案を推す人がおられれば、そちらに変えようかと思います。

**Comment by Hiroshiba** [comment]
どれも良いなと思いました。
となると慣習に合わせるのが無難だと思うので、最後の案が良いのかなと思いました！

ps.
VOICEVOXタイトルが真ん中からさらに右にいってる感があるなーと感じました。いつか直したいかもです。
