### ISSUE TITLE
スクロールでピッチ（音高）を微調整できることが気づけるUIにする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#563]
## 内容

音高はスライダーで設定可能になっていますが、マウス操作で微調整するのはだいぶ大変です。
なのでマウススクロールで微調整可能になってはいるのですが、使い方を読まないとなかなか気づけません。

使い方を読まなくても気付けるUIにできると最高なのですが、良い方法は無いでしょうか。

### Pros 良くなる点

気づいてもらうことによって間接的に調整難度を下げられる

**Comment by aoirint** [comment]
![Screenshot from 2021-12-19 06-57-24](https://user-images.githubusercontent.com/27213639/146656490-ecb27db1-36ff-428a-9385-da48c1186f51.png)

ホバー時のツールチップで、設定値に併記して`ホイール: ±0.1`、`Ctrl + ホイール: ±0.01`のようなヒントを表示できないかなと感じました（`ホイール`は長い気もするけれど...）。

```
5.95
ホイール: ±0.1
Ctrl + ホイール: ±0.01
```

ここですかね?

<https://github.com/VOICEVOX/voicevox/blob/a41c0b3c5f0b50cf360610eea7b7f72842900b68/src/components/AudioParameter.vue#L6-L15>

**Comment by Hiroshiba** [comment]
面白い案に感じました！

ヒントは、ヒントが不要な人には邪魔にならない感じで表示するのが最も良いのかなと思いました。
仰るとおりテキストが少し長く、常に３行表示になるので、縦幅が増えてしまって表示区間がもったいないかもです。

ジャストアイデアですが、「イントネーション」タブボタンのtooltipにその案内を書くとか・・・？

**Comment by k-chop** [comment]
必要な人への届いてほしさ vs 不要な人への邪魔したくなさ、バランスが難しいですね・・・

ホイールに気付いていない人の調整作業を実際に観測した訳ではないので憶測ですが、
微調整をしたい人は「この値に調整したい」というのが決まっている（例えば元の値から+0.01したい、隣の音素と同じ値にしたい、等）と思われるため、
目的の値に持っていくためにスライダーを掴んだままにする時間が長そうです。
なので一定秒数以上スライダーを掴んだままだとツールチップが出てくるというのはどうでしょうか。

（ただ上記の仮定を外していたり、秒数の設定によってはユーザの中に鬱陶しい思いをする人が出てしまうかもしれません。個人的な感覚だと1.5秒くらい...？）

![Animation3](https://user-images.githubusercontent.com/241973/168440861-efd86843-cec6-4609-bf57-409093cbb497.gif)
1.5秒での動作イメージです↑

**Comment by k-chop** [comment]
> 「イントネーション」タブボタンのtooltipにその案内を書く

こちらも試してみたので動作イメージを
![Animation4](https://user-images.githubusercontent.com/241973/168441218-5bba4eea-6b96-47af-91f0-cb128315fa8c.gif)

「スクロールで微調整できます」みたいな文言があった方が分かりやすいですかね？（ちょっとくどいかも・・・？）
![スクリーンショット 2022-05-15 015819](https://user-images.githubusercontent.com/241973/168441446-cf92c417-3ef3-4071-b36c-30d7a157c7eb.png)

**Comment by Hiroshiba** [comment]
> 必要な人への届いてほしさ vs 不要な人への邪魔したくなさ

おっしゃるとおりだと思います。（あと実装の大変さも）

たしかに、1.5秒くらいでツールチップを出すのはそこまで鬱陶しくなさそうに感じました！
ただ、本当にそうなのか、苦しむ人がいないかが判断しにくいというのが本音です･･･。

「イントネーション」欄にカーソルを当てたときに出すのも、思ったよりちょっと目立つなぁという感覚です。

考えたのですが、1.5秒で出すのではなく、例えば3秒とか、もっと長くしてしまえば苦しむ人がほとんどいないかもと感じました。

もしくは代案ですが、「設定」に「ホイールの値の変更量：イントネーション」みたいな項目を作って気づけるようにするとか･･･。でも設定全部見ないですし、見る人は使い方も見られそう･･･。

もしくはイントネーション欄の右上あたりに、×で消せるツールチップを表示するとかもありかもと思いました。
あとは起動時にTips表示とか･･･。

（考えがまとまってなくてすみません）

**Comment by k-chop** [comment]
返信大変遅くなってすみません！！！！！

上記提案したときはマウスホイールがある前提で考えていたのですが、
mac（タッチパッド）でスクロールを試してみたところ、マウスホイールのように1ずつ微調整ができないことに気付きました。
なのでmac勢にとっては、表示までの時間を大きめに取ったとしても
表示されても対応できない悲しい表示になってしまいそうですので、取り下げさせてください 🙇 
検討していただいたのにすみません。

代わりに書いていただいた中で一番実装コスト軽そうかつ効果がありそう！と思った
> イントネーション欄の右上あたりに、×で消せるツールチップ

を表示だけ試してみたのがこんな感じです。
![スクリーンショット 2022-06-26 183701](https://user-images.githubusercontent.com/241973/175808454-3c8efabd-4d14-40a3-8a82-1ab4a388a095.png)

存在感があるので一度は必ず見た上で消す・一度消したら再表示されない（設定ファイルに見たよフラグ書き込み）、ならば
困る人も少ないし救える人は救えるのではないかと思いました。
問題なさそうでしたらこれで実装進めてみようかなと思っています。

**Comment by Hiroshiba** [comment]
場所依存のtips表示機能、とてもいいと思います！！
実装、ぜひお願いしたいです！！

１つだけ実装上の提案なのですが、おそらくこのtips機能はいろんなところで欲しくなると思われます。
なので設定に保存する時に、key&value（つまり普通のobject）として保存できると追加しやすくて良いのかなと思いました！
