### ISSUE TITLE
テキストファイル読み込みのキャラクター指定機能のバグ

### ISSUE THREAD

**Issue by Segu-g** [VOICEVOX/voicevox#565]
## 不具合の内容

テキストファイル読み込みで，キャラクター名を挟むことでキャラクター名を指定する機能があります．
しかし，スタイルが追加された影響でテキストファイルを読み込んだ際，この機能が上手く働かずスタイルが一番最後のもの（製品版viocevoxだとセクシー）になってしまいます．

## VOICEVOXのバージョン

0.9.0

**Comment by yuqquu** [comment]
使おうとしていた機能だったので、修正してみます。

ただ、期待動作は人によって分かれるかもしれません。
単に「四国めたん」と書かれている場合、選択されるスタイルはノーマルなのかデフォルトスタイルなのかで選択の余地があります。
私としては後者のほうが使い勝手が良さそうだと思うので、とりあえずそちらのほうで実装します。

**Comment by y-chan** [comment]
@yuqquu assignさせていただきます...!

**Comment by Hiroshiba** [comment]
@yuqquu プルリクありがとうございます！！
こちらのissueはcloseしちゃっても大丈夫そうでしょうか？

**Comment by yuqquu** [comment]
大丈夫です、closeお願いします！
