### ISSUE TITLE
ショートカットキーを初期値に戻すと重複して設定出来てしまう

### ISSUE THREAD

**Issue by MT224244** [VOICEVOX/voicevox#566]
## 不具合の内容

キー割り当てにて、操作Aの初期値を操作Bに設定した状態で操作Aを初期値に戻すと、ショートカットキーが重複して設定出来てしまう。
重複したショートカットキーを入力すると、初期値の方が優先されて、重複している方は実行されないようです。

### 現象・ログ

![image](https://user-images.githubusercontent.com/25514849/145577773-a3df8f7b-0569-4938-ae0e-75659d1caab7.png)

### 再現手順

1. 「音声書き出し」のショートカットキーを別のキーに変更
2. 「一つだけ書き出し」のショートカットキーを `Ctrl + E` に設定
3. 「音声書き出し」のショートカットキーを初期値に戻す

例として「音声書き出し」「一つだけ書き出し」を出していますが、どの操作でも起こりえます。

### 期待動作

下記のどちらかが望ましいかもしれません。

- 初期値に戻す操作を失敗にする
- 初期値と被っている方のキーを未設定にする

## VOICEVOXのバージョン

\>=0.9.1

**Comment by Hiroshiba** [comment]
なるほど、気づきませんでした･･･。

挙動としては、「初期値に戻そうとする」ときと「新しくそのショートカットキーを割り当てる」ときの挙動を合わせるのがとりあえず良いのかなと感じました。

**Comment by yuriko0505** [comment]
この課題に取り組みます！

**Comment by Hiroshiba** [comment]
@yuriko0505 ぜひぜひ！！
もし分からないことがあったら何でも聞いてください！
難しかった場合はその旨をコメントいただけると次の方の励みになると思います！
