### ISSUE TITLE
Mac版でわかっている不具合を直す

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#572]
## 不具合の内容

できれば修正したいもの

- [x] Mac: cmdキーをショートカットキーとして使用できない
- [x] Mac: 左上の赤黄緑のボタンが、どれがどの挙動かわからない（マウスホバーしても×などが出ない）

余裕があれば修正したいもの

- [ ] Mac: タイトルバーをダブルクリックしても最大画面にならない
- [ ] スクロール感度の調整（トラックパッドなど、感度が高すぎることがある）
- [x] Mac: system preferenceからアプリケーション実行を許可した初回起動時にエラーが出る？

## OSの種類/ディストリ/バージョン

Mac OS

## その他

できれば修正したいものが完了し次第closeして、残りはissue化すれば良いかなと思います。

ref

- https://github.com/VOICEVOX/voicevox/pull/570
- https://github.com/VOICEVOX/voicevox/issues/399

**Comment by PickledChair** [comment]
> Mac: 左上の赤黄緑のボタンが、どれがどの挙動かわからない（マウスホバーしても×などが出ない）
> Mac: タイトルバーをダブルクリックしても最大画面にならない

上記２つについては、以下のelectronのウィンドウ初期化時に、452行目の指定を `frame: true` にすると、macOSネイティブのタイトルバーが使われるようになり解決します。

https://github.com/VOICEVOX/voicevox/blob/c27970a0a26f69e912cb574f8fa284295ddb6876/src/background.ts#L449-L461

以下の動画のように機能します。

https://user-images.githubusercontent.com/41382894/145706103-732db6a6-4d22-48ff-8c00-e4e8907188f5.mov

ただし難しい部分として、タイトルバー部分に関して他のOSとは大きく異なるUI設計をしなければならなくなるという点があります。UIが他のOS版と大きく異なってくると、大きなUI変更時にmacOS対応がリリースの速度にブレーキをかける可能性があるので、この解決策は欠点の方が大きい気がしています。

次善の策としては、例えば

> Mac: 左上の赤黄緑のボタンが、どれがどの挙動かわからない（マウスホバーしても×などが出ない）

に関しては頑張ってCSSで再現する、ということなどが考えられます。

対応の優先順位に関しては、個人的には２番目もそんなに急ぐ必要はなさそう？ と思っています（ユーザーの反応次第）が、全体的にはおおむね同意見です。

**Comment by aoirint** [comment]
> Mac: system preferenceからアプリケーション実行を許可した初回起動時にエラーが出る？

たしかに、プロジェクトファイルを開こうとしてエラーになっているようでした。

```
[***] [error] Error: ENOENT: no such file or directory, open '-psn_0_**'
```

<https://github.com/VOICEVOX/voicevox/blob/c27970a0a26f69e912cb574f8fa284295ddb6876/src/background.ts#L497-L500>

ここで`-psn_`から始まる引数を無視するようにすることになるかなと思いました。

- 対応例
    - <https://github.com/IJHack/QtPass/issues/213>
    - <https://github.com/bitcoin/bitcoin/issues/17179>
    - <https://github.com/qt/qtbase/blob/ed546ff216010c979b94263aab4773a1a6afd5bb/src/gui/kernel/qguiapplication.cpp#L1558-L1569>
    - <https://blog.michinari-nukazawa.com/2020/05/eletctron-macosx.html>

詳しい仕様はよくわからないですが、macOS 10.9以前のGUIアプリケーション（Carbonフレームワークで作られたもの）は、PSN（Process Serial Number）という固有IDを起動引数に渡していたようです。Finderから起動すると渡されるという記述も見かけましたが、手元（macOS Catalina）では再現できなかったです。

- <https://apple.stackexchange.com/questions/207895/app-gets-in-commandline-parameter-psn-0-nnnnnn-why>
- <https://stackoverflow.com/questions/10242115/os-x-strange-psn-command-line-parameter-when-launched-from-finder>

署名されていないアプリとして署名が整備される前の古いものを想定しているようなので、互換性のために引数に付けるようにしているのかもしれないです。

- <https://support.apple.com/ja-jp/guide/mac-help/mh40616/12.0/mac/12.0>

**Comment by aoirint** [comment]
macOS版VOICEVOXのdmgを開くか、zipを展開すると、自動的にvvprojファイルが関連付けられました。

そこでFinderからvvprojファイルを開いても、VOICEVOXは起動しますが、プロジェクトが開かれませんでした（起動自体は、Ctrl+クリックで開いて許可できます）。

macOSは、Windows/Linuxと違って、ファイルパスが起動引数に渡されないかもです。

`open-file`イベントを拾ってあげる必要がありそうです。

- <https://stackoverflow.com/questions/46262130/electronjs-osx-open-file-with-my-application-how-to-use-the-apple-event>
- <https://github.com/electron/electron/blob/c4e471fbe2f89f4c665ef706f12e04f6d2bfb9d9/docs/api/app.md#event-open-file-macos>
- <https://blog.michinari-nukazawa.com/2020/05/eletctron-macosx.html#:~:text=%23%23%20electron%E3%81%AF%20OSX%E3%81%A7%E3%81%AF%27open-file%27%20%E3%82%A4%E3%83%99%E3%83%B3%E3%83%88%E3%82%92%E5%8F%97%E3%81%91%E3%82%8B>

**Comment by Hiroshiba** [comment]
> 対応の優先順位に関しては、個人的には２番目（Mac: 左上の赤黄緑のボタンが、どれがどの挙動かわからない（マウスホバーしても×などが出ない））もそんなに急ぐ必要はなさそう？ と思っています

慣れていないと終わらせ方がわからないのはなかなか不安だったので、優先度を高めにしてみてみました。

> ここで-psn_から始まる引数を無視するようにすることになるかなと思いました。

なるほどです！！
個人的には、ブラックリスト方式ではなくホワイトリスト方式にしても良いのかなと感じました。
vvprojだけ通す感じです。

**Comment by PickledChair** [comment]
@aoirint 

> macOS版VOICEVOXのdmgを開くか、zipを展開すると、自動的にvvprojファイルが関連付けられました。
> そこでFinderからvvprojファイルを開いても、VOICEVOXは起動しますが、プロジェクトが開かれませんでした（起動自体は、Ctrl+クリックで開いて許可できます）。

指摘されて気づきました。vvprojファイルは以下のような見た目になりますね。これを開いてみてもプロジェクトがアプリケーションに反映されないので、確かにユーザーが混乱するかもしれないと思いました。こちらでも、教えていただいたリンク等をもとに調査してみたいと思います。

<img width="682" alt="vvproj_on_finder" src="https://user-images.githubusercontent.com/41382894/145710428-336c5058-0f69-4e91-b2f3-e72181bdf528.png">

@Hiroshiba 

> 慣れていないと終わらせ方がわからないのはなかなか不安だったので、優先度を高めにしてみてみました。

Macユーザーであればボタンの意味は知っているだろうということを念頭においていましたが、確かに、例えばMac初心者や、普段からMacを使っている訳ではないユーザーがVOICEVOXに触れる機会があるかもしれないですね。それを考えると、ユーザーがボタンの意味を理解しづらいというケースはありそうですね。納得しました。

**Comment by PickledChair** [comment]
各不具合の中で、自分が取り組んだ範囲の情報をメモします。

## Mac: cmdキーをショートカットキーとして使用できない

Windows・Linux における問題が残っていますが（ #600 ）、 #594 で対応しました（最初のコメントに勝手にチェックを入れましたが大丈夫だったでしょうか？）。

## Mac: system preferenceからアプリケーション実行を許可した初回起動時にエラーが出る？

#588 の変更で同時に直ったのでないかと推測しています。しかし、もともと自分の環境では出なかったエラーなので、修正されたかどうかを確認できていません。このエラーが出ていた方は、余裕のある時に確認していただければ幸いです（ @Hiroshiba さんだけだったでしょうか？ @aoirint さんもでしょうか？）

## その他

優先順位の高い「Mac: 左上の赤黄緑のボタンが、どれがどの挙動かわからない（マウスホバーしても×などが出ない）」ですが、現状、自分には対応が出来なさそうです（色々試してみましたが……）。できる方がいらっしゃればお願いしたいと思います。

**Comment by Hiroshiba** [comment]
> Mac: system preferenceからアプリケーション実行を許可した初回起動時にエラーが出る？
> 余裕のある時に確認していただければ幸いです

確認のためにreleaseビルドを作ってみました！
https://github.com/VOICEVOX/voicevox/releases/tag/0.10.preview.1

**Comment by PickledChair** [comment]
そういえばなのですが、 

- #593 

の影響で、現在releaseビルドを作ると画面が白くなりますね（現在の自動ビルドはエンジンのバージョンとして 0.9.3 を指定しています。Mac では https://github.com/VOICEVOX/voicevox/issues/598#issuecomment-996694222 の手順で動作するようになることを確認しています）。

以下のエンジンのバージョン指定を 0.10.preview.2 などにすると解決すると思いますが、今後、テストリリース向けに変える予定はありますか？

https://github.com/VOICEVOX/voicevox/blob/52a01ccba5e2c627298b8661e2df004f410b5594/.github/workflows/build.yml#L14

**Comment by Hiroshiba** [comment]
たしかに良さそうです、ビルドしてみます！！

**Comment by Hiroshiba** [comment]
> Mac: system preferenceからアプリケーション実行を許可した初回起動時にエラーが出る？

こちら、問題なく直っていそうなことを確認しました！

**Comment by madosuki** [comment]
[https://www.electronjs.org/docs/latest/api/frameless-window#alternatives](https://www.electronjs.org/docs/latest/api/frameless-window#alternatives)
ドキュメントを読む限りでは、```frame: false```ではなく```titleBarStyle: "hidden"```ならネイティブの三色ボタンが使えるようなるぽいです。
ただしLinuxではこのオプションは無視されるのでLinuxでフレームレスウィンドウをやる場合は```frame: false```が必要です。

**Comment by PickledChair** [comment]
@madosuki 

> ドキュメントを読む限りでは、frame: falseではなくtitleBarStyle: "hidden"ならネイティブの三色ボタンが使えるようなるぽいです。

情報ありがとうございます。試してみました。上記の指定をウィンドウに設定した上で、`<min-max-close-buttons />` のクラスに `invisible` を設定した時の見た目は以下の通りです。機能面でも問題なさそうです（それどころか、最大化ボタンの挙動がネイティブのものになったので、ちゃんと画面全体を占有するようになります。現在の挙動は、ウィンドウサイズを最大化するだけで、画面全体を占有するようにはなりません）。

<img width="413" alt="native_3colors_buttons" src="https://user-images.githubusercontent.com/41382894/147312089-f436014d-452a-4d34-b332-10bf15260480.png">

タイトルバーのレイアウトと若干あっていませんが、レイアウトをうまく調整できれば使えるかもしれません。その辺りの quasar や css の知識がないので、自分が取り組むとしても時間がかかりますが……。良さそうな方法だと思います！

**Comment by Hiroshiba** [comment]
いいですね！！　確かになんかずれていますが…！
vscodeなどに比べると、ちょっと縦幅が狭い感じでしょうか。

**Comment by PickledChair** [comment]
`BrowserWindow` のオプションに `trafficLightPosition` という項目を見つけました（「信号機ボタン」という名前にしているようです）。設定したら三色ボタンの方を好きな位置にできました！ `trafficLightPosition: { x: 6, y: 4 }` とすると以下のようになります。三色ボタンのためにメニューバーに空白を設ける方法は試行錯誤中です😅

<img width="379" alt="traffic_light_positioning" src="https://user-images.githubusercontent.com/41382894/147374445-037f30b2-416f-48b3-9c00-4b110ad521bc.png">

**Comment by PickledChair** [comment]
> Mac: 左上の赤黄緑のボタンが、どれがどの挙動かわからない（マウスホバーしても×などが出ない）

上記の問題が #621 で解消されましたが、Mac のネイティブ UI 部分が英語になってしまっている問題が判明したので、 #624 の Issue にしました。これは「できれば修正したいもの」に入るでしょうか……？

**Comment by Hiroshiba** [comment]
そうですね！できれば修正したいです・・・！
このissueに追記でも良かったのですが、必須issueが解決できているので（ありがとうございます！）、閉じちゃって個別issueにしちゃうのが良いのかなと感じました。
ということで、issue化します！
