### ISSUE TITLE
Linux版: プロジェクト保存時に自動でvvproj拡張子がつかない

### ISSUE THREAD

**Issue by aoirint** [VOICEVOX/voicevox#574]
## 不具合の内容

Linux版（Ubuntu）でプロジェクトファイル（vvproj）を保存するとき、ファイル名に拡張子を自分で記述しなかった場合、拡張子がつきません。

Windowsでは、拡張子なしで保存すると、末尾にファイルの種類で選択したvvprojが自動で追加されます。

macOS #570 では、デフォルトファイル名の拡張子部分が選択されていないほか、拡張子なしで保存すると、vvprojが自動で追加されます。

Linux（Ubuntu）では、vvprojのファイル一覧フィルタは動作していますが、拡張子を自分で記述しなかった場合、拡張子なしで保存されます。

Linuxでも拡張子が自動で付くようにした方がよさそうに思いました。

保存先のパスに拡張子がなかった場合、強制的に追加する処理を入れてもいいかもしれませんが、上書き防止をOSのダイアログに任せる実装になっている場合、自前で実装する必要があるかもです。

### 現象・ログ

UIの比較

<details>

#### Windows 10

![windows-vvproj](https://user-images.githubusercontent.com/27213639/145711381-aadbd117-057e-4faf-b2e8-c1aaf0cfc595.png)

#### macOS Catalina

<img width="345" alt="macos-vvproj" src="https://user-images.githubusercontent.com/27213639/145711387-1071976a-8f5d-4bfa-b66c-e840265c954d.png">

<img width="844" alt="macos-vvproj2" src="https://user-images.githubusercontent.com/27213639/145712048-193c4803-29f7-4dc7-a150-aad4379ec56e.png">

#### Ubuntu 20.04

![linux-vvproj](https://user-images.githubusercontent.com/27213639/145711390-07502362-eff8-4b25-a5ee-a731fc5a53fe.png)

</details>

### 再現手順

Linux版をUbuntuで起動し、プロジェクトを保存する。

### 期待動作

拡張子がファイル名にない場合、自動的に追加される（Windows、macOSのように）

または、拡張子付きのデフォルトファイル名が表示されている（macOSのように）

## VOICEVOXのバージョン

0.9.3

## OSの種類/ディストリ/バージョン

* Ubuntu 20.04

**Comment by qwerty2501** [comment]
私はUbuntu20.04を使用してますが、例えばVSCodeだと右下のファイル拡張子を特定の物に変更してもファイル名に拡張子を入れないとやはり拡張子は付きません。
なのでバグではなく仕様であるととらえることもできます。VOICEVOXだと読み込み時にvvprojで絞り込みされてるのでUbuntu上でのUXは悪いですが。

恐らくこれはデスクトップ環境依存の挙動なのではないでしょうか。
Gnomeではこの挙動ですがKDEやXfaceだとまた違う挙動になるかもしれません。この挙動を変更するとこちらを立てればあちらが立たずといった問題は発生しそうです。
仮にこの問題に対応するとしたらLinuxで推奨するOSはUbuntuのみと明言してしまうのが良さそうです。キリがないので

> 拡張子付きのデフォルトファイル名が表示されている（macOSのように）

ちなみに私が使用しているGIF録画アプリケーションや動画編集ソフトウェアだとファイル保存時の挙動はこれでした

**Comment by Hiroshiba** [comment]
なるほどです。
なにか拡張子を表示するためのフラグがなさそうであれば、デフォルトファイル名を拡張子付きにしてしまうのが手っ取り早いのかなと感じました。

**Comment by aoirint** [comment]
プロジェクト保存ダイアログでも、「音声を繋げて書き出し」機能のようにデフォルトファイル名`defaultPath`がダイアログに入力されているようにする実装になるかなと思いました。

<https://github.com/VOICEVOX/voicevox/blob/16b2c1e483a99855d3c21d37b433e4bc845803a7/src/background.ts#L554-L558>

<https://github.com/VOICEVOX/voicevox/blob/16b2c1e483a99855d3c21d37b433e4bc845803a7/src/store/audio.ts#L979-L985>

**Comment by aoirint** [comment]
#606 が #574 の解決策としてマージされたので、Closeします。
