### ISSUE TITLE
Linux版: vvprojファイルの関連付けをする

### ISSUE THREAD

**Issue by aoirint** [VOICEVOX/voicevox#575]
## 内容

Linux版（インストーラ）では、vvprojファイルの関連付けがされていなかったので、Issue化します。

### Pros 良くなる点

プロジェクトファイルを開きやすくなる

### 実現方法

インストーラで、`voicevox.desktop`ファイル内の起動引数に`%U`を追加すれば、関連付けの候補に追加されます。
この時点で、GUIで関連付けを設定してプロジェクトファイルを開くことはできるようになります。

#### ~/local/share/applications/voicevox.desktop

```desktop
...
Exec=/home/user/.voicevox/VOICEVOX.AppImage %U
...
```

その上で、インストーラで自動的な関連付けをしたいですが、よく方法がわかっていません。

まず、electron-builder側の設定で、fileAssociationsに適当なMIMEType（`application/x-voicevox`とか）を追加して、`voicevox.desktop`ファイルに吐き出されるかどうか確認したいです。

#### ~/local/share/applications/voicevox.desktop

```desktop
...
MimeType=application/x-voicevox
```

MIMETypeをdesktopファイルに追加した上で、インストーラで以下に関連付けを追記すれば、自動で関連付けができそうなのですが、手元ではうまくいっていないです。

#### ~/local/share/applications/defaults.list

```
...
application/x-voicevox=voicevox.desktop
```

- <https://askubuntu.com/questions/16580/where-are-file-associations-stored>

もっとうまくElectron Builder側で対応する方法があるかもしれません。

関連しそうなUbuntuのコマンドにdesktop-file-installコマンド、update-desktop-databaseコマンド、update-mime-databaseコマンドなどがあるようですが、OS間の互換性や仕様がよくわかっていません。

## VOICEVOXのバージョン

0.9.3

## OSの種類/ディストリ/バージョン

* Ubuntu 20.04

## その他

- #88

**Comment by eggplants** [comment]
memo: https://wiki.archlinux.org/title/Desktop_entries

**Comment by eggplants** [comment]
https://qiita.com/laineus/items/92d354ff6c230613fbdc

**Comment by eggplants** [comment]
```bash
sudo cat<<'A'>>/usr/share/mime/packages/freedesktop.org.xml
  <mime-type type="application/voicevox">
    <comment>Voicevox Project file</comment>
    <comment xml:lang="ja">Voicevixプロジェクトファイル</comment>
    <acronym>Voicevox pj</acronym>
    <expanded-acronym>Voicevox project</expanded-acronym>
    <glob pattern="*.vvproj"/>
  </mime-type>
A
```

**Comment by eggplants** [comment]
Linuxは大体freedesktopを採用しているので↑でなんとかなるかもです。

**Comment by Hiroshiba** [comment]
おお！！ありがとうございます！！

sudo使う必要があるとなると、あまりsudo使いたくないユーザーも一定数いそうなので、インストーラーに含めるのに一工夫必要かもですね。
インストールスクリプト実行後に、「関連付けしたかったらこれ実行してね」とコマンド列を表示するという折衷案を思いつきました。

**Comment by aoirint** [comment]
ありがとうございます！

XMLを追加する先は`~/.local/share/mime/packages/`でいいかもと思いました。
これならsudoがいらなさそうです。

**Comment by aoirint** [comment]
自分の環境を見てみましたが、acronym, expanded-acronymを定義しているアプリケーションが見当たらなかったのでちょっと省略して、以下のようなXMLがよさそうでした。

~/.local/share/mime/packages/voicevox.xml

```xml
<?xml version="1.0" encoding="utf-8"?>
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
    <mime-type type="application/x-voicevox">
        <comment>VOICEVOX Project file</comment>
        <comment xml:lang="ja">VOICEVOX プロジェクトファイル</comment>
        <sub-class-of type="application/json" />
        <glob pattern="*.vvproj" />
        <icon name="voicevox" />
    </mime-type>
</mime-info>
```

XML追加後に`update-mime-database ~/.local/share/mime`の実行が必要です。

desktopファイルにMimeType追記済みの環境で、アイコンも表示され、ダブルクリックでプロジェクトを開くことができました。

<details>

![Screenshot from 2021-12-13 17-24-17](https://user-images.githubusercontent.com/27213639/145777990-e8c8063e-1560-41c9-9ad3-7fca5a4efb2d.png)

</details>

関連付けの選択UIで、初期値に戻す操作をするとVOICEVOXに設定されるようになりました（もともとはgeditに戻っていた）。
インストール時は自動でVOICEVOXが使われるはずです。

<details>

![Screenshot from 2021-12-13 17-17-28](https://user-images.githubusercontent.com/27213639/145778222-112ca272-67d5-4f1b-a725-015eac4c46c5.png)

</details>

**Comment by eggplants** [comment]
@aoirint PR作られます？

**Comment by aoirint** [comment]
@eggplants PR作ります！
