### ISSUE TITLE
ドラッグ移動後のテキスト欄初回フォーカス時にフォーカスが外れる

### ISSUE THREAD

**Issue by Segu-g** [VOICEVOX/voicevox#587]
## 不具合の内容

#369 のissueを実装した#553 のプルリクエストでドラッグすると，その後一度だけテキスト欄のフォーカスがキャンセルされる．

### 現象・ログ

https://user-images.githubusercontent.com/25514849/144720244-a856f218-d195-424e-b449-3fbd9b3e4f2b.mp4

(https://github.com/VOICEVOX/voicevox/pull/553#pullrequestreview-823290269 より引用)

### 再現手順

並び替えをしてからテキスト欄をクリックする

### 期待動作

blurされない

## VOICEVOXのバージョン

0.?.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

## その他

~~`input`ではなく`AudioCell`に`click`イベントが発火されるのが問題になっているかも...?~~
並び替えした後の初めての`click`イベントでblurされる模様
使用したライブラリ [SortableJS/vue.draggable.next](https://github.com/SortableJS/vue.draggable.next) を読む必要があるかも．

**Comment by Hiroshiba** [comment]
ドラッグ移動、すごく便利ですね！！

カーソルが外れてしまうのはユーザーから必ず指摘されることだと感じたので、優先度を高めてみました。
D&Dしたあと、一度なにもないところをクリックするだけでも、この挙動がなくなっていそうでした。何かのヒントになれば・・・！

**Comment by Hiroshiba** [comment]
もしくは、簡単にif分岐できそうであれば一旦experiment機能にしてしまう手もあるかなと思いました。
（設定の「実験的項目」にon/offフラグを付け、デフォルトをoffにするやつです）

**Comment by Hiroshiba** [comment]
experimental化が完了したので、優先度を少し下げて、バグから機能向上に変更します

**Comment by Segu-g** [comment]
どうやらハンドルに用いているアイコン部分がq-btnであるためドラッグ開始時にmousedownイベントを受け登録されたmouseupイベントリスナーがドラッグ終了時に呼ばれずに次のクリック時のmouseup時に呼ばれることでフォーカスが外れているようでした. 

従ってハンドルをq-btnではない別の要素に移したいと思うのですが,  active_arrowの位置にハンドルを置くのはデザインが微妙になってしまって悩んでいます　アイデアがあればお願いします.

**Comment by Hiroshiba** [comment]
おーーなるほどです！！
そもそもアイコンをドラッグするのではなく、AudioCell全体のviewをドラッグするようにするとかどうでしょう。

**Comment by Segu-g** [comment]
AudioCell全体のDivはq-btnを含むので同じバグが起こります

**Comment by Segu-g** [comment]
なるほど、では一旦その方針でPRを立てたいと思います

**Comment by Hiroshiba** [comment]
たぶん解決で良いと思うのでcloseします。
ユーザーさんから指摘来たらopenして検討する感じで・・・！
