### ISSUE TITLE
Ver0.4.1で保存したプロジェクト（.vvproj）がVer0.9.3で読めない

### ISSUE THREAD

**Issue by K-Magara** [VOICEVOX/voicevox#592]
## 不具合の内容

Ver0.4.1で保存したプロジェクト（.vvproj）をVer0.9.3で開こうとすると
audioItem.styleID == undefined
と表示され開くことができません．

## VOICEVOXのバージョン

0.9.0

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

Windows 10 Enterprise 64bit (21H2 19044.1387)

**Comment by yuqquu** [comment]
マイグレーションがうまくいっていないのが原因のようでした。
おそらく 0.5 を境に `characterIndex` が `styleId` に変わったのだと思います。
0.4.1 と 0.9.3 のプロジェクトファイルを覗いたところ `characterIndex` が `styleId` に変わっていることを確認しています(画像参照)。
![image](https://user-images.githubusercontent.com/50493934/146018082-b43d2192-b197-4abe-b240-99b38bbb0633.png)

0.5.3 をダウンロード中なので、そのバージョンで確認ができたら取り組みたいと思います。
