### ISSUE TITLE
初期起動のキャラの声のイントネーション未選択時に「次へ」をグレーアウトというのがわかりずらい。

### ISSUE THREAD

**Issue by Apple-Yuki** [VOICEVOX/voicevox#597]
## 内容

初期起動のキャラの声のイントネーション未選択時に「次へ」をグレーアウトというのがわかりずらい。

### Pros 良くなる点

初期起動のキャラの声のイントネーション未選択時に「次へ」をグレーアウトせず、警告文でユーザーに知らせるといいかと思います。
もしくは、デフォルトイントネーションを決めておくことで簡単に使えるようになると思います。

## その他

関連issue：#576

**Comment by Hiroshiba** [comment]
こちらは意図的で、絶対に聞いてほしいからわざとこうしています。
VOICEVOXに興味を持ち、音声合成を初めてチャレンジする人は、興味深く聞いてくれるはずです。

@Apple-Yuki 例えばどのように表示すれば良さそうでしょうか？
ちなみに今のUIはこんな感じです。
![image](https://user-images.githubusercontent.com/4987327/146216248-642084df-cd60-4a55-ab71-18ac24eb07c7.png)

**Comment by Apple-Yuki** [comment]
@Hiroshiba 
そうですね。声のスタイルは「後からでも設定できます」なので、この前に一括設定するか個別設定するかを聞けば、ユーザーによってこの画面見るのがめんどくさいと思う人を回避できるかもしれませんね。

例として、MacやiPhoneの初期設定にあるエクスプレス設定をご参考に。
おそらくMacの初期設定の順番が結局ソフトウェアの設定なり利用規約提示なりが順序よくされているかと。

**Comment by Hiroshiba** [comment]
なるほどです。voicevoxのデザインの思想とからめて、なぜここをスキップできなくしているかちょっと語ってみます。

ここでスタイルを選択してもらう目的は、コンテンツを作る人に、調整された音声への興味を持ってもらうためです。
（スタイルを選択すると、あらかじめ用意してあった音声が再生されます。）

それなりの割合の人は、完璧に調整された音声を聞くことに興味がないかもしれませんが、良いコンテンツを作るためにお手本は必須です。
ここでいろんなスタイルに触れてもらいつつ、最高の品質の音声を聞くという体験を提供しています。

voicevoxに手をつける人の大半は、おそらく調整の大変さを知りません。
いろいろ音声を聴き比べてもらって、作りたいコンテンツのイメージを膨らませたりしつつ、コンテンツ作りの大変さを乗り切るモチベの足しになればと思っています。

より良い音声試聴の体験を提供する方法があれば、変更したいです。

**Comment by Hiroshiba** [comment]
それはさておいて、スキップできないのにスキップできそうな見た目になっている（グレーアウトはしてるものの「次へ」ボタンが表示されている）のは、確かに混乱を与えそうだなと思いました。
「次へ」が上に表示されるプライマリーカラーのツールバーにあって、スタイル選択ボタンより目立っているのをなんとかすると良いのかなと感じました。

**Comment by Apple-Yuki** [comment]
@Hiroshiba そうですね。
結構選択系の初期設定などのUI見てみましたが、混乱防止のため、選択されるまではそもそも次に進むボタンは非表示（画面に出てない）されていることが多いですね。

あと、
 ![image](https://user-images.githubusercontent.com/4987327/146216248-642084df-cd60-4a55-ab71-18ac24eb07c7.png)
の画面で自分で軽く文字列を設定して喋らせれるとなおいいかもですね。

**Comment by Hiroshiba** [comment]
なるほどです。非表示する方針で行きたいところです。

disabledになっている箇所をhiddenとかに変えると動作しそうです。
どうでしょう、プルリクエスト作成してみませんか…？

ちなみに対象のUIはこの辺りにあります。
src/components/DefaultStyleSelectDialog.vue

---

軽く音声合成する機能は、まあ実装が大変なのと、無調整だとまだだいぶ微妙なのでここでは完璧なのだけ聞いてほしいですね…。

**Comment by Apple-Yuki** [comment]
@Hiroshiba 
src/components/DefaultStyleSelectDialog.vue でdisabledになってる箇所とか探してるんですけど見つからないです...。
どの辺にありそうですか？

**Comment by Hiroshiba** [comment]
この辺りでしょうか。僕はよくボタンに表示されてる文字とかで検索して該当箇所を見つける手がかりにしています。
https://github.com/VOICEVOX/voicevox/blob/52a01ccba5e2c627298b8661e2df004f410b5594/src/components/DefaultStyleSelectDialog.vue#L55-L74

**Comment by nebocco** [comment]
こちらもしどなたも取り組んでいないのであれば取り掛かってもよろしいでしょうか？

**Comment by y-chan** [comment]
@nebocco 問題ないと思います!
Assignさせていただきますね...!

**Comment by nebocco** [comment]
やると言っておきながら一月以上放置しており申し訳ありません……
修正すべき点は分かってはいるのですが手元で動かず確認ができていない状態です（コンパイルは通るが即座に終了してしまうのでブラウザで見れない）。
electron に馴染みが薄いので現在いろいろ調べて回っています。

**Comment by y-chan** [comment]
ブラウザではなく、専用のウィンドウが立ち上がるモード(`npm run electron:serve`)があるので、そちらではどうでしょうか👀

**Comment by nebocco** [comment]
ありがとうございます！普段の開発は WSL 内で行っていたのですが、WSL に gui の機能がない影響でウィンドウの立ち上げに失敗し、`serve` が即終了してしまっていたようです。native windows 内に node の環境を構築して実行したところ無事にウィンドウが立ち上がりました。

**Comment by nebocco** [comment]
`v-if` や `v-show` で制御すると要素は右詰めになり、ラジオボタン選択時に他要素が左に動きます。対して CSS の visibility を変化させるようにすると他要素の位置は固定され、「次へ」の表示 / 非表示のみが切り替わります。どちらが好ましいでしょうか？

### display: none を指定した場合
![220321display](https://user-images.githubusercontent.com/73807432/159221007-fe985ca1-42e3-430f-9f35-3f5de7fd2be9.png)

### visibility: hidden を与えた場合
![220321visibility](https://user-images.githubusercontent.com/73807432/159221013-8aa469a9-11df-45dd-935f-e5edd0ed1f61.png)

**Comment by Hiroshiba** [comment]
@nebocco どちらでも問題なさそうですが、空いてることの意図がユーザーの方に伝わらなそうなので前者が良いのかなと思いました！！
