### ISSUE TITLE
Mac版のデフォルトショートカットキーはctrlではなくcmdにすべき？

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#604]
## 内容

Macでは通常、ショートカットキーのコンボ？にとして、ctrlではなくcmdを使います。
voicevoxもその慣例に習ってそのようなデフォルトショートカットキーにすべきか、意見が欲しいです。

### Pros 良くなる点

直感的Macユーザーにとって直感的

### Cons 悪くなる点

処理が煩雑になる

## その他

個人的には、そこまで煩雑な処理にならないのであれば実装した方が良いのかな、と感じています。

**Comment by PickledChair** [comment]
確かに Mac 版のデフォルトショートカットキーが Cmd になっている方がユーザーには優しいと思います。少し検討してみましたが、実装も簡単そうです。

例えば background.ts にあるデフォルトショートカットキーの最初の項目は以下のようになっていますが、

https://github.com/VOICEVOX/voicevox/blob/16b2c1e483a99855d3c21d37b433e4bc845803a7/src/background.ts#L70-L74

これについて手っ取り早く Mac 用の設定を加えるには以下のようにすると良さそうです：

```ts
const defaultHotkeySettings: HotkeySetting[] = [
  {
    action: "音声書き出し",
    combination: process.platform !== "darwin" ? "Ctrl E": "Meta E",
  },
```

この方針で良ければすぐ実装できます……！

**Comment by Hiroshiba** [comment]
そうですね、やっぱりcmdにすべきだと思いました。
そちらの方針でぜひ実装お願いしたいです！
