### ISSUE TITLE
エディタ側から複数のエンジンを見るようにする

### ISSUE THREAD

**Issue by aoirint** [VOICEVOX/voicevox#609]
## 内容

- <https://github.com/VOICEVOX/voicevox/issues/429>

こちらから派生したIssueです。

VOICEVOXエディタから、VOICEVOX ENGINEのHTTP APIに対応した複数の音声合成エンジンを利用できるようにします。

### Pros 良くなる点

- VOICEVOX ENGINEのHTTP APIに対応したサードパーティの音声合成エンジンを、製品版VOICEVOXソフトウェア上で利用できるようになる

### 実現方法

このIssueで検討します。

## VOICEVOXのバージョン

- エディタ #450 以降
- ENGINE [0.10.preview.2](https://github.com/VOICEVOX/voicevox_engine/releases/tag/0.10.preview.2) 以降

**Comment by aoirint** [comment]
AudioItemでの`styleId`の扱いが問題になりそうかなと思いました。

<https://github.com/VOICEVOX/voicevox/blob/ffc55550a76d15ad1466dbc2d120c112530218de/src/store/type.ts#L28-L33>

<https://github.com/VOICEVOX/voicevox/blob/ffc55550a76d15ad1466dbc2d120c112530218de/src/components/AudioCell.vue#L190-L204>

AudioItemやプロジェクトファイルでは`styleId`でキャラクター・スタイルを識別する形になっていますが、複数のエンジンを見るようにした場合、`styleId`の重複を気にする必要が出てきそうです。

- <https://github.com/VOICEVOX/voicevox/discussions/431#discussioncomment-1578982>

上では、`characterUuid`、`engineId`などキーを増やす提案がありました。

<https://github.com/VOICEVOX/voicevox/blob/ffc55550a76d15ad1466dbc2d120c112530218de/src/store/project.ts#L291-L299>

AudioItemは、プロジェクトファイルに直接ダンプされる実装になっているので、ロード側にマイグレーションを追加して、キーを増やしていいかなと思いました。

<https://github.com/VOICEVOX/voicevox/blob/ffc55550a76d15ad1466dbc2d120c112530218de/src/store/project.ts#L202-L210>

---

- <https://github.com/VOICEVOX/voicevox/discussions/431#discussion-3663220>
- <https://github.com/VOICEVOX/voicevox/discussions/431#discussioncomment-1578982>
- <https://github.com/VOICEVOX/voicevox/issues/312>

このあたりの議論では、`styleId`をUUID化する言及がありそうでした。
`styleId`
UUIDは

この場合、ENGINEでは互換性のために数値IDを扱う機能を残したまま、UUIDで扱えるようにできるかなと思いました。

コアライブラリのAPIを数値ID

コアライブラリでは数値IDの方がかもしれないと思いましたが、UUIDに統一してもいいかもです。
1.xとかで互換を

を両方扱えるようにする形で

---

プロジェクトファイルなどでエンジンのブランドをどう識別するか、も問題になりそうです。
ENGINEが固有の`engineId`（UUID?）を持っているとすると、


このIssueでは、

複数エンジンを見るようにできるようにする、には、同じブランドのエンジンを複数扱えるようにする（例えば複数バージョンのVOICEVOX ENGINEを同時に使えるようにする）

`styleId`をUUID化した場合、複数エンジンでも一意性を想定できるので、上のAudioCellのような実装をそのまま使って、`styleId`のみから`speakerUuid`とエンジンを特定できそうに思いました。

- <https://github.com/VOICEVOX/voicevox/discussions/431#discussioncomment-1578982>

ここで言及がありますが、

**Comment by aoirint** [comment]
- <https://github.com/VOICEVOX/voicevox/discussions/431#discussion-3663220>
- <https://github.com/VOICEVOX/voicevox/discussions/431#discussioncomment-1578982>
- <https://github.com/VOICEVOX/voicevox/issues/312>

このあたりの議論では、`styleId`をUUID化する言及がありそうでした。

これが行われた場合、`styleId`の型をstringに変えれば、`styleId`からCharacterInfoを持ってくるような実装をそのままにできるのかなと思いました。

<https://github.com/VOICEVOX/voicevox/blob/ffc55550a76d15ad1466dbc2d120c112530218de/src/components/AudioCell.vue#L190-L204>

ENGINEでは、互換性のために数値IDを扱う機能を残したまま、UUIDで扱えるようにできるかなと思いました。
この場合、サードパーティ向けのエンジンAPI仕様としては、UUIDだけを要求すればいいと思うので、1.xになったときにENGINEから数値IDのAPIを削除するとかを検討してもいいかもです。

コアライブラリでは、metasにスタイルの識別子として、数値IDとUUIDを両方持たせる形かなと思いました。
コアライブラリのAPIを数値IDのままにするか、UUIDにするか、というのはちょっと迷いそうです。

**Comment by Hiroshiba** [comment]
styleId周りは確かに強敵だなと感じました。
そもそも何をもってユニークとするかを決めることになりそうでしょうか。

styleIdがUUIDになれば確かにユニークにできそうです。
エンジンやコアに調整が必要なのが少し厄介かもしれません。
（ここをどうしていくかは、リポジトリをまたぐのでdiscussionの方で進めたほうが良いかもです）

エディタ側だけですすめるなら、speakerIdとstyleIdのペアをユニークキーとする手もあるかなと思いました。
ただこれはデータ構造が変わるので、それで良いのか考えたほうが良さそうにも感じました。

どうやって決めようか迷いますね･･･。

**Comment by aoirint** [comment]
複数のエンジンに接続できるようにするには、環境変数で複数のエンジンURLを渡すことになると思います。

エンジンのAPI URLは、SettingStoreが`engineHost`として持っています。

<https://github.com/VOICEVOX/voicevox/blob/ffc55550a76d15ad1466dbc2d120c112530218de/src/store/type.ts#L677-L684>

ここで環境変数`VUE_APP_ENGINE_URL`からの読み出しがされています。

<https://github.com/VOICEVOX/voicevox/blob/ffc55550a76d15ad1466dbc2d120c112530218de/src/store/setting.ts#L23-L43>

環境変数ではJSON文字列を持つようにして、`JSON.parse`してデフォルトのエンジン設定を読み出すようにするのがいいのかなと思いました。

<https://github.com/VOICEVOX/voicevox/blob/ffc55550a76d15ad1466dbc2d120c112530218de/.env.production#L1-L3>

```
VUE_APP_DEFAULT_ENGINE_HOSTS=[{"key":"074fc39e-678b-4c13-8916-ffca8d505d1d","executablePath":"run.exe","host":"http://127.0.0.1:50021"}]
```

`engineHost: string`は、`engineHosts: EngineHostSetting[]`にして、下のような型に当てはめます。

```typescript
export type EngineHostSetting = {
  key: string;
  executablePath?: string;
  host: string;
};
```

`executablePath`は、環境変数`ENGINE_PATH`を統合することを考えています。

`key`は、設定画面でエンジンを新しく登録したときに、エディタ側で生成して割り当てる識別子を想定しています（ここでは適当なUUID）。
エディタ内でのエンジンの識別のほかに、デフォルト設定を書き換える必要が出たとき、設定のマイグレーションに使えるかなと思っています。

エンジンのブランド（VOICEVOX、COEIROINKのような）を識別するための`engineId`のようなものをキーとして使った場合、 #220 のように、音声合成を外部のサーバで実行するような用途で、同じブランドを持つエンジン複数をエディタに登録することができなくなるかなと思いました。例えば、VOICEVOX ENGINEをGPUサーバでホストしていて、別のCPUマシンでVOICEVOX ENGINEがすでに組み込まれた製品版エディタにサーバを登録する場合です。

このあたりは、深く考えるとエンジンの使用優先度やサーバニックネーム、バージョンの異なるエンジン（コア）が同時に見えている場合の対応などが必要そうで、複雑になりそうなので、いったん1ブランド1エンジンで進めるのがよさそうですが、ある程度想定しておきたいなと思いました。

一応、エンジンの登録部分（管理画面?）、起動部分、設定の構成は別Issueで考えたほうがいいかなと思うので、このIssueの段階では単にカンマ区切りとかJSONリストにしておく形でもいいかもです。

**Comment by aoirint** [comment]
エンジンとの通信は、`INVOKE_ENGINE_CONNECTOR`を書き換えればよさそうです。

<https://github.com/VOICEVOX/voicevox/blob/ffc55550a76d15ad1466dbc2d120c112530218de/src/store/proxy.ts#L26-L33>

接続先`engineHost`を変えるために、ここに引数を追加することを考えます。

<https://github.com/VOICEVOX/voicevox/blob/ffc55550a76d15ad1466dbc2d120c112530218de/src/store/type.ts#L925-L931>

`payload`に`host: string`（か`engineKey: string`）を追加すればいいかなと思いました。

`host: string`の場合、`INVOKE_ENGINE_CONNECTOR`の呼び出し元で、キャラクターにひもづいたエンジンURLを設定から取り出して渡す形です。

**Comment by aoirint** [comment]
<https://github.com/VOICEVOX/voicevox/blob/ffc55550a76d15ad1466dbc2d120c112530218de/src/store/type.ts#L70-L78>

AudioStoreでは、`engineState`を`engineStates`にして複数のエンジンの起動状態を持てるようにするとよさそうです。

<https://github.com/VOICEVOX/voicevox/blob/ffc55550a76d15ad1466dbc2d120c112530218de/src/store/type.ts#L35-L38>

`audioStates`、`audioItems`と同じように`engineKeys: string[]`を追加して、`engineStates: Record<string, EngineState>`にできそうです。

<https://github.com/VOICEVOX/voicevox/blob/ffc55550a76d15ad1466dbc2d120c112530218de/src/store/type.ts#L46>

エンジンの起動状態の設定は、`SET_ENGINE_STATE`の引数に`engineKey: string`を追加して、`engineStates[engineKey]`を書き換えるようにすればいいのかなと思いました。

<https://github.com/VOICEVOX/voicevox/blob/ffc55550a76d15ad1466dbc2d120c112530218de/src/store/audio.ts#L163-L165>

エラー発生時に保持している起動状態を更新する`DETECTED_ENGINE_ERROR`でも同じように`engineKey`を追加すればよさそうです。

<https://github.com/VOICEVOX/voicevox/blob/ffc55550a76d15ad1466dbc2d120c112530218de/src/store/audio.ts#L1237-L1248>

**Comment by aoirint** [comment]
エンジンの起動完了を待機する`START_WAITING_ENGINE`、キャラクター情報をエンジンから取得する`LOAD_CHARACTER`、サーバプロセスを再起動する`RESTART_ENGINE`は、引数に`engineKey`を追加した上で、それぞれ検討が必要そうです。

<https://github.com/VOICEVOX/voicevox/blob/ffc55550a76d15ad1466dbc2d120c112530218de/src/store/audio.ts#L442-L448>

ひとまず、すべてのエンジンに対して操作を同時にする`START_WAITING_ENGINE_ALL`のようなActionを追加して既存の呼び出し部分を置き換えるのがいいかなと思っています。すべての登録されたエンジンに対して順番に`START_WAITING_ENGINE`を`dispatch`する形です。

**Comment by aoirint** [comment]
`START_WAITING_ENGINE`は、エンジンの起動完了を待機しますが、複数のエンジン、特に外部サーバを考えると、エディタの起動時にすべての登録されたエンジンに到達できることを想定しない作りにするのがよさそうです。

<https://github.com/VOICEVOX/voicevox/blob/ffc55550a76d15ad1466dbc2d120c112530218de/src/store/audio.ts#L442-L448>

しかし、エディタが操作できるようになったあとでキャラクターがだんだん増えると、意図しない操作を起こしそうです。初期化に時間がかかると思われる、エディタがプロセス管理しているエンジンだけ待機するようにするのがいいのかなと思っています。

起動時に複数のエンジンを待つことになる場合、並列起動をしたり、エンジンの初期化状態をエンジンロゴなどといっしょに表示する画面が表示されていたりするとよさそうだなと感じました。

また、起動時のAudioCellの追加などで`characterInfos.length === 0`の場合を想定していないところがある感じがしますが、このあたりを整えるときに手を入れてもいいかもと思いました。

一応、設定画面を作るときに考えればいいはずなので、ひとまずこのIssueでは、すべての登録されたエンジンに到達することを想定しておいていいかなと思っています。

**Comment by aoirint** [comment]
`LOAD_CHARACTER`は、キャラクター情報をエンジンから取得して、`SET_CHARACTER_INFOS`で`characterInfos`に格納します。

<https://github.com/VOICEVOX/voicevox/blob/ffc55550a76d15ad1466dbc2d120c112530218de/src/store/audio.ts#L471-L482>

`characterInfos`は、エンジンのブランドを表示するために、エンジン別にキャラクターを表示する需要がありそうなので、キャラクターをエンジン別に持つようにして、`characterInfos: Record<string, CharacterInfo[]>`にしてもいいのかなと思いました。

<https://github.com/VOICEVOX/voicevox/blob/ffc55550a76d15ad1466dbc2d120c112530218de/src/store/type.ts#L70-L78>

影響がよくわかっていないですが、`characterInfos`を使っているところでは、いったん`flatMap`で`Record<string, CharacterInfo[]>`を`CharacterInfo[]`にしてから使うようにしておいて、あとでブランドを考慮した表示を実装してもよさそうです。

<https://github.com/VOICEVOX/voicevox/blob/ffc55550a76d15ad1466dbc2d120c112530218de/src/type/preload.d.ts#L92-L100>

<https://github.com/VOICEVOX/voicevox/blob/ffc55550a76d15ad1466dbc2d120c112530218de/src/store/audio.ts#L519-L529>

キャラクター一覧の表示は、エンジンにロゴ画像やブランド名を返すAPIを追加して、仮で以下のようにできるかなと思っています（表示の変更・デザインは別Issueで考えたい）。

![sectioned_characters](https://user-images.githubusercontent.com/27213639/147099751-376adea5-1a31-4c43-b013-1fc572e81640.png)

**Comment by aoirint** [comment]
`RESTART_ENGINE`は、エンジンを再起動しますが、エディタがプロセス管理しているエンジン以外（外部サーバ）に対しては、仕組み上再起動させることができません。

- <https://github.com/VOICEVOX/voicevox_engine/issues/64>

エンジン側で、上で実装されたような、音声合成プロセス管理の仕組みをAPIとして持つようになれば（サーバ機能と音声合成機能の分離）、外部サーバについても（再起動権限の認証を付けた上で）再起動コマンドが実装できるように思いますが、別Issueかなと思います。

このIssueでは、これまで通りの挙動を登録された全エンジンに適用するように拡張すればいいかなと思っています（`RESTART_ENGINE_ALL`）。

<https://github.com/VOICEVOX/voicevox/blob/ffc55550a76d15ad1466dbc2d120c112530218de/src/store/audio.ts#L1249-L1255>

プロセスを再起動する実装は、無名関数として入れ込まれているので、関数として切り出すようにリファクタリングが必要かなと思いました。

<https://github.com/VOICEVOX/voicevox/blob/ffc55550a76d15ad1466dbc2d120c112530218de/src/background.ts#L666-L676>

**Comment by Hiroshiba** [comment]
> AudioItemでのstyleIdの扱い

すごく迷ったのですが、engineIdとstyleIdを持つようにするのが良いかなと思いました！

* styleUuidにするのは互換性考慮するのが大変そうだから、別タイミングか余力があればにしたい
* styleIdだと被る可能性があるから何かをペアに持たせないといけない
* styleUuidにしたとしても結局engineIdは取得しないといけない
* プロジェクト読み込み後、styleUuidだけ持っていてもどのエンジンを待機中なのかわからないのでちょっと不便かも

という感じです。
どれも迂回策はあるけど、engineId持っていたほうが全体的に楽かなという判断です･･･！

> Record

ユニークなキーがあるときは積極的にRecordを採用して頂けると！
そういえばengineIdやaudioKeyなどは全部stringですが、たぶん型が付いていたほうがコーディングが楽だと思います。
もし方法をご存知であれば専用の型をつけて頂けると安心かもです。

> エディタの起動時にすべての登録されたエンジンに到達できることを想定しない作りにするのがよさそうです。

たしかに、どれかのエンジンが起動しなかったらエディタが正常動作しないというのは避けたい気がします。
ただおっしゃるとおり（？）、このissueでは一旦全部に到達できる前提で進めて良さそうに感じました！

> キャラクター一覧の表示

良いデザインに感じました！！
が、いずれキャラクターが増えるとキャラ表示のon/offに加え、おそらく並び替えがしたくなる気がします。
そのときにエンジンの境界があったほうが良いのか無いほうが良いのかわからないというのもあって、最初は全部のキャラがずらっと並んでいても良いのかなと感じました。
（実装が複雑にならなければ提案されているデザインでも良いと思います！）

> RESTART_ENGINE_ALL

良さそうに感じました！！

---

遅れてすみませんでした。全体的に良さそうだったので、可能であれば進めちゃって頂けると！！

**Comment by Hiroshiba** [comment]
現状全部engineKeyになっていますが、[こちらのPR](https://github.com/VOICEVOX/voicevox/pull/743)でengineIdが導入される予定でしたが、まだengineKeyとengineIdの使い分けを議論しきれていない状況です。

そこで一度、VOICEVOXエディタはエンジンの種類ごとに１つだけしかエンジンを把握できない、という設計にしたいと思います。
つまり、engineKeyをなくして、engineIdのみにする戦略です。

engineKeyはあとで導入することもできるはずです。
engineKeyを活かすには更にUIの実装も必要なため、実装をいったん後回しにしたいと思います。

･･･という内容のPRを出しました！

- https://github.com/VOICEVOX/voicevox/pull/871

**Comment by Hiroshiba** [comment]
タイトルのことはかなりの部分実装できたかなと思うので、こちらのissueはcloseにしたいと思います！
続きは↓で行えれば！

- https://github.com/VOICEVOX/voicevox_project/issues/2

@aoirint さん、ありがとうございました！！！
