### ISSUE TITLE
UXがキャラクター数スケールに対応できていないのではないか

### ISSUE THREAD

**Issue by qwerty2501** [VOICEVOX/voicevox#614]
## 内容
議論用issueです。
先日配信を見たときに結構な頻度でキャラクターを追加する予定であると知ったのですが、これに対して現状のVOICEVOXのUXではその増加スピードに耐えられないのではないかと感じました。
問題になってから対応するのではなく、今のうちに懸念点を洗い出しておけば仮に対応できてなかったとしても問題発生時点ですぐに対応できるかと思ったので建てました

私が懸念してる点は以下です。

### 初回起動時に一人一人のスタイルを選択しなければならない
初回起動時に各キャラクターのスタイルを選択しますが、一人分のスタイルを選択して次のキャラスタイル選択画面に遷移という風になってます。
遅くとも一年後には10人以上のキャラが存在している状態になってるかと思いますので、これを全キャラ分しなければならないと考えるとかなり苦痛です。私が初めて使うユーザーなら使うのを投げ出して辞めると思います。
これに対して初回起動時のスタイル選択をやめてデフォルトのスタイルをアプリケーション側で設定しておくか、あるいはキャラのスタイルをまとめて選択できるようなUIを作ったほうが良いかなと思いました。

### キャラ選択が複雑化しそう
これは仕方ないところはありますが、現状のままでキャラクターが大量に増えると選択するのがかなり困難になりそうです。

**Comment by Hiroshiba** [comment]
製品版VOICEVOXは今のところ月１人のペースで増えています。３ヶ月後くらいに問題が顕著になりそうです。

デフォルトスタイル選択は改良すべきだと僕も感じます！
キャラをまとめて一覧化するのが良いのかなと思いました。

キャラ選択の複雑さも懸念点だと思います。
「設定でキャラ選択に表示するキャラを選んでおける」という作戦は１つの手かなと感じます。
あとはもう複雑なのは仕方ないとしてよく使うキャラが上に来るように「表示順序入れ替え」機能をつける、とかでしょうか。

**Comment by qwerty2501** [comment]
> 「設定でキャラ選択に表示するキャラを選んでおける」という作戦は１つの手かなと感じます。

ずんだもんしか使う気がないというユーザーは結構いそうですね。
一案ですが、キャラクターインストールという概念を作り、一覧化されたスタイル選択時にチェックボックスで選べる(後で設定から変えられる)ようにしてはどうでしょうか？

**Comment by Hiroshiba** [comment]
あー、いいですね！
デフォルトスタイル選択ダイアログより前くらいに使用するキャラクター一覧を出す感じでしょうか。
出来る限り使って欲しいというのが願いにあるので、そこでなるべくチェックを外されないようにしたいところです。
チェックボックスの横にサンプル再生ボタンを付けて、思いもよらぬ出会いの機会をなるべく排除しない、とかでしょうか。
（個人的にはチェックボックスを外す前に、一回でも良いからサンプル音声を再生したいです。）

最初のチェックボックスリストとそのあとのデフォルトスタイル選択の役割がややこしくなりそうですね･･･
一旦モチベーションを整理してみます。

* デフォルトスタイル選択のモチベーション
  * デフォルトスタイルを最初に選んでほしい
  * 別スタイルやキャラクターに興味がないと思っているが、実は潜在的には興味がある人に、興味を持ってもらいたい
    * デフォルトでスタイルが選択されていない
    * 選択時に音声を再生する
  * エンジンが起動するまでに時間稼ぎ

真のインストール（キャラごとにコアライブラリがあってユーザーが何らかの方法でインストールする）と語弊がありそうなので、開発サイドでインストールと呼称すると語弊があるかもです。

**Comment by qwerty2501** [comment]
> デフォルトスタイル選択ダイアログより前くらいに使用するキャラクター一覧を出す感じでしょうか。

これも2画面遷移する必要があるのでできれば1画面にまとめたいですね。ちょっと伝わりづらいかもですが、以下のような感じの行を表示する感じはどうでしょう？

```
[インストールチェックボックス] [キャラアイコン] [スタイル選択プルダウン] [選択してるスタイルのサンプル再生ボタン]
[インストールチェックボックス] [キャラアイコン] [スタイル選択プルダウン] [選択してるスタイルのサンプル再生ボタン]
...
```

> 出来る限りいろんなキャラを使ってほしいというのが願いにあるので、そこでなるべくチェックを外されないようにしたいところです。
チェックボックスの横にサンプル再生ボタンを付けて、思いもよらぬ出会いの機会をなるべく排除しない、とかでしょうか。
（個人的にはチェックボックスを外す前に、一回でも良いからサンプル音声を再生したいです。）

まあ作り手としてはそうですよね。とりあえずデフォルトでインストールチェック項目をチェック済みにしとけば大体の人はそのままにするのではないでしょうか。
↑のリスト表示案ならスタイル選択とインストールチェックさせつつサンプルも聞かせられるかなと思ったんですがどうですかね？

> 別スタイルやキャラクターに興味がないと思っているが、実は潜在的には興味がある人に、興味を持ってもらいたい
> デフォルトでスタイルが選択されていない

これは初期設定時のわずらわしさからくる離脱とのトレードオフになりそうなので意見は分かれそうですね。
IMO: 全キャラ分選択するのはめんどそう

> エンジンが起動するまでに時間稼ぎ

今は初回起動時にはエンジン起動してない状態でやってるんですか。今後同梱エンジンが増えた場合はまずエンジンを起動しないとキャラ情報は取れないのでこのアプローチは使えなくなるのではないでしょうか。

インストールという名称については思い付きの仮名称なので適切な名称を設定したほうが良いですね

**Comment by y-chan** [comment]
> 以下のような感じの行を表示する感じはどうでしょう？
> ```
> [インストールチェックボックス] [キャラアイコン] [スタイル選択プルダウン] [選択してるスタイルのサンプル再生ボタン]
> [インストールチェックボックス] [キャラアイコン] [スタイル選択プルダウン] [選択してるスタイルのサンプル再生ボタン]
> ...
> ```

インストールチェックボックスという概念がたしかにわかりにくいですね...
私もパッといい方法は思いつきません...

> エンジンを起動しないとキャラ情報は取れないのでこのアプローチは使えなくなるのではないでしょうか。

これは個人的にも気になっていました。
今後はエンジンを起動しないとデフォルトキャラ選択画面が出せないはずなので、ちゃんと挙動を確認したいところですね。

**Comment by Hiroshiba** [comment]
> インストールという名称

初期キャラ選択とかでしょうか。

> これも2画面遷移する必要があるのでできれば1画面にまとめたいですね

キャラクターであるという意識をあまり捨てたくなく、１画面にまとめてキャラっぽさが減って業務っぽさが増えるのは、少し慎重になりたいです。

> ↑のリスト表示案ならスタイル選択とインストールチェックさせつつサンプルも聞かせられるかなと思ったんですがどうですかね？

`別スタイルやキャラクターに興味がないと思っているが、実は潜在的には興味がある人に、興味を持ってもらいたい`というのがあります。
今だと受動的にサンプルが流れる設計です。
能動的にサンプルボタンを再生することはあまりないと思っています。
（そして起動後に適当にテキストを入力して、無調整な音声が再生され、興味を持てずに終わる、という流れになってしまうと思います）

> 煩わしさからくる離脱

インストールに５分かかるのにここで離脱する人は相当少ないかなと考えています。
SNSで煩わしいという意見は今ところ見かけてないです。
GTMが導入されているので、どこまで進んだかの測定しても良いかなと思います。

> エンジンを起動しないとキャラ情報は取れないので

ほんとですね。。モチベーションから外しておきます！

**Comment by qwerty2501** [comment]
> 初期キャラ選択とかでしょうか。

後で変えれるという点を加味すると単純にキャラ選択でしょうか？わかりません。

またバージョンアップによって新規キャラクターが増えた場合、そのキャラクターについての設定を新たにする必要がありそうですね。その辺はすでに考慮された実装になってるかもしれませんが。
離脱に関しては完全に私の想像なので杞憂かもしれません。
測定できるのならその結果をみてからでも遅くはなさそうですね。

**Comment by qwerty2501** [comment]
>別スタイルやキャラクターに興味がないと思っているが、実は潜在的には興味がある人に、興味を持ってもらいたい

あとここについては超相当強い意思を感じたのでいったんは初回起動時にキャラ選択画面は出さずに全キャラ分選択されてる状態にし、設定の奥深くでキャラ選択の切り替えができるようにして様子を見てみるのも良さそうですね。
または最初の方のコメントであった表示順序入れ替えにとどめるか。

**Comment by Hiroshiba** [comment]
その流れだと個人的には嬉しいです。リストにするとこうでしょうか。

1. 初期設定画面を先に作る
2. 様子見しつつ、ウェルカム画面でのデフォルトスタイル選択やキャラ選択をどうするか考える
3. 2を実装する

ウェルカム画面で表示順序を決めてもらうの、すごく良いかもと思いました！！
「好きなキャラ３人以上選んで」とだけ伝えて、キャラ選択したら声が再生されるというのを想像しました。
ただこれだと選ばれなかったキャラは非表示になりますが、それで本当に良いかとかはもうちょっと吟味したいかもです。

**Comment by qwerty2501** [comment]
コントリビューターにすぎない私がここまで意見してしまうのはちょっと行き過ぎな気がしてきましたが気にせず書いてしまいます。
気に食わなかったら採用しないぐらいのノリでお願いします。

時間的にまだ余裕はありますし、とりあえずは様子見の方向で良いと思います。

> ウェルカム画面で表示順序を決めてもらうの、すごく良いかもと思いました！！

良さそうに見えますが、よく考えたらユーザーが表示順序入れ替えることを本当に求めてるかわからないですよね。案外あまり気にしないかもしれない。
表示順序入れ替え機能を初期設定でできるようにしても入れなかった場合と比べてユーザーの手間がほぼ0であるならやってしまっても良いかもですが、
表示順序入れ替え機能をいれるならまず実験機能として設定のオプションにのみ表示順序入れ替え機能を実装してみて、ある程度使用されてる実績があるなら初期設定でも表示順序を変えれるようにしても遅くはないのではないかなと思いました。表示順序入れ替え機能を提供するならどのみちオプションで表示順序を変えれる機能はつくらないといけないですし。
本当はユーザーに表示順序変えたいか聞くのがいいんでしょうけどまあキャラが増えきってからじゃないと本当の気持ちは教えてくれなさそうな気がします。

> 「好きなキャラ３人以上選んで」とだけ伝えて、キャラ選択したら声が再生されるというのを想像しました。
ただこれだと選ばれなかったキャラは非表示になりますが、それで本当に良いかとかはもうちょっと吟味したいかもです。

できるだけ多くのキャラを使ってほしい気持ちがあるならこれについては保留にしたほうが良いのではないでしょうか。
ただどこかのタイミングでこういった決断はしなければならないと思います。誰かが神UXを作ってくれれば別ですが。
仮にやるとしたら割と現実的な実装案かなと思いました。

**Comment by Hiroshiba** [comment]
たしかに、とりあえずウェルカム画面は保留で良い気がしました。

となると最初は、設定画面でキャラの表示非表示・並び替えを設定できるようにする感じでどうでしょう。
そのissueを建てて、このissueはウェルカム画面でキャラが多すぎるのをどうするか話す場として再利用・・・？

**Comment by qwerty2501** [comment]
> となると最初は、設定画面でキャラの表示非表示・並び替えを設定できるようにする感じでどうでしょう。

第一歩としては良さそうです。ただもう少し他の方の意見を聞いてからでも遅くはないと思います。

おっしゃられてる通りやるとしたらissueを別に立ててここは議論用として残したほうが良いと思います。
他にもまだ対応が必要なところあるかもしれないので。

**Comment by Hiroshiba** [comment]
ちょっとUIを考えてみました。

設定画面は前述通り、表示非表示＋並び替えのUIで良い気がします。

ウェルカム画面ですが、表示順序選択UIが良いのかなと思いました。
キャラクター一覧が右にアイコンで並んでいて、選択時に音声再生＋キャラクターが左に表示される感じです。これでいろんなキャラに簡単に興味を持てるのかなと思っています。

![image](https://user-images.githubusercontent.com/4987327/149794542-5d8f28ea-c31f-46a4-a604-6be59dab1505.png)

ただこのとき、別スタイルがあることをどう表示すべきか迷っています。
右のアイコンリストにスタイル名を表示し、左右ボタンを並べ、左右ボタンが押されたら別スタイルになる（音声も再生される）UIだと、そのボタンを押すまでそのボタンが別スタイルへの遷移であることに気づけなそうです。
右のキャラアイコンをクリックしたときに左にスタイル一覧が表示されるUIだと、キャラを選ぶまで別スタイルがあることに気づけません。
この２択であれば後者のが良いかなと思っています。更に良いUIが思いついたらまたメモします。

**Comment by qwerty2501** [comment]
アイコンリストで表示されてる時に複数スタイルがあることを示せるとよさそうですが・・・ :thinking:

**Comment by Hiroshiba** [comment]
たしかに！
単純に「スタイル数：４」みたいな感じでスタイルの数を書くとかを思いつきました。
