### ISSUE TITLE
ディスカッション：使い方の一番下にあるお問い合わせに関して

### ISSUE THREAD

**Issue by Apple-Yuki** [VOICEVOX/voicevox#615]
## 内容
今,#602 で使い方の内容を順次更新している状況ですが、もしお問合せしたい時にお問合せ先が一番下にありすぎて観に行くのが億劫になる可能性があると思います。
それらの改善案というか半分質問提起です。

使い方のところにあってもいいですが、別途画面があった方がいいんじゃないかなぁと思ったのでイシュー立てました。

### Pros 良くなる点
現状、ヘルプにある「アップデート」の下に別途お問合せの画面を作ることで、使い方の一番下まで行かなくてもお問合せ方法が確認できる

<img width="912" alt="スクリーンショット" src="https://user-images.githubusercontent.com/91584669/147038601-02d977e9-cc68-4141-8c22-ed2717592c8f.png">

### Cons 悪くなる点

多分悪くなる点はないと思われる

## その他

改善案というかディスカッションでも可です。

**Comment by Hiroshiba** [comment]
なるほど！確かに使い方の一番下にあるのは微妙な気がしました。

あと項目を用意して問い合わせ先がわかるようにできると嬉しそうです。
たたき台はこんな感じでしょうか

使い方に関する質問、改善の要望、バグ報告
→ ハッシュタグをつけてTwitterでツイート

上記の開発者向け
→ github リポジトリ

その他
→ hiho_karutaツイッターまで

**Comment by Hiroshiba** [comment]
その変更を加えるとホームページから問い合わせ先を知る方法がいったんなくなるので、ホームページの方も簡単でも良いから問い合わせ情報を記載したいかもです。

**Comment by Apple-Yuki** [comment]
@Hiroshiba さんのたたき台ベースで内容をまとめて尚且つ導線考えるとこんな感じですかね？


## クレジット

ホームページ：[https://voicevox.hiroshiba.jp](https://voicevox.hiroshiba.jp)
Copyright ©︎ Hiroshiba Kazuyuki
VOICEVOX公式：[@voicevox_pj](https://twitter.com/voicevox_pj)
開発者Twitter：[@hiho_karuta](https://twitter.com/hiho_karuta)

## 使い方に関する質問、改善の要望、バグ報告
ご感想・ご要望は、ぜひ Twitter にてハッシュタグ `#VOICEVOX` を付けてツイートしてください。

うまく動かない場合や不具合を見つけられた方は以下の内容を添えてハッシュタグ `#VOICEVOX` を付けてツイートしていただくか、VOICEVOX公式（[@voicevox_pj](https://twitter.com/voicevox_pj)）までご報告いただけると助かります。  

- 不具合の内容
- 再現手順（動画や写真があれば添付してください）
- 現在ご利用のVOICEVOXのバージョン
- 現在ご利用のOSの種類・バージョン（例：Windows 11 21H2）

バージョンの確認方法は以下のページでご紹介しています。
- Windows
 [Microsoft Windows Support](https://support.microsoft.com/ja-jp/windows/使用中の-windows-オペレーティング-システムのバージョンを確認する-628bec99-476a-2c13-5296-9dd081cdd808)
- macOS 
[https://support.apple.com/ja-jp/HT201260](https://support.apple.com/ja-jp/HT201260)
- Linux系統  
各プラットフォームにより確認方法が異なる場合があります。詳しくは各OSのサポートページをご覧ください。


### 開発者向け 
GitHub開発者の方は以下でもお問い合わせ頂けます。
また、不具合の修正など、誰でもVOICEVOXの開発や修正にもご参加頂けます。
- [VOICEVOX エディター](https://github.com/Hiroshiba/voicevox)
- [VOICEVOX エンジン](https://github.com/Hiroshiba/voicevox_engine)
- [VOICEVOX コア](https://github.com/Hiroshiba/voicevox_core)

### その他
商用利用等のお問い合わせや使用許諾などのお問い合わせは、[@hiho_karuta](https://twitter.com/hiho_karuta)までお問い合わせください。

**Comment by Hiroshiba** [comment]
すごくいいですね！！！

2点だけ…！

不具合のツイッター報告のOSのバージョン情報は、文字数が増えてツイート内の情報量が減っちゃいそうなのと、調べるの面倒で報告やめちゃうのがあるかもなので、まあ案内省いちゃって良いかもと思いました！

> 商用利用等のお問い合わせや使用許諾などのお問い合わせ

この2点、気になる人多いと思うのですが、できる限り自己判断してほしいんだよなぁという願いがあったりします。。（対応してもこちらにほとんど利益がないのに時間はかかるので…）
書いちゃうと、ああ質問して良いんだと思われそうなので、（あまり効果があるかは微妙ですが）「何かあればhiho_karutaまで〜」とぼかして書いておきたいなという気持ちがあります。

> FAQ

たしかに、FAQも分けた方が良いと思います！！
タスク内容はとても似ていますが、今のissueタイトルからはずれるので別issueを作成いただけるととても助かります…！

**Comment by Apple-Yuki** [comment]
@Hiroshiba 
では、それらを踏まえて書き直しました。

OSのバージョン情報とかは、後ほどいただく場合があることに変更して、
お問い合わせ系は別issueを発行しているFAQを確認して、解決しない場合のみ連絡いただく動線に変更してみました。

よくあるご質問 （FAQ）のリンク先は一旦、issueへのリンクにしてるので使う場合は、FAQできてからになりますね。

## クレジット

ホームページ：[https://voicevox.hiroshiba.jp](https://voicevox.hiroshiba.jp)
Copyright ©︎ Hiroshiba Kazuyuki
VOICEVOX公式：[@voicevox_pj](https://twitter.com/voicevox_pj)
開発者Twitter：[@hiho_karuta](https://twitter.com/hiho_karuta)

## 使い方に関する質問、改善の要望、バグ報告
ご感想・ご要望は、ぜひ Twitter にてハッシュタグ `#VOICEVOX` を付けてツイートしてください。

うまく動かない場合や不具合を見つけられた方は以下の内容を添えてハッシュタグ `#VOICEVOX` を付けてツイートしていただくか、VOICEVOX公式（[@voicevox_pj](https://twitter.com/voicevox_pj)）までご報告いただけると助かります。  

- 不具合の内容
- 再現手順（動画や写真があれば添付してください）
- 現在ご利用のVOICEVOXのバージョン

報告の際の文章の例：VOICEVOX 0.9.3でCPUモード、GPUモード共に起動しません。　　など

なお、以下の情報が後ほど確認させていただく場合がありますので、事前にお控えいただくとスムーズにご対応ができる場合があります。
- 現在ご利用のOSの種類・バージョン（例：Windows 11 21H2）
- ウイルス対策ソフトなどの有無
- 事前にやっていただいたトラブルシューティング

バージョンの確認方法は以下のページでご紹介しています。
- Windows
 [Microsoft Windows Support](https://support.microsoft.com/ja-jp/windows/使用中の-windows-オペレーティング-システムのバージョンを確認する-628bec99-476a-2c13-5296-9dd081cdd808)
- macOS 
[https://support.apple.com/ja-jp/HT201260](https://support.apple.com/ja-jp/HT201260)
- Linux系統  
各プラットフォームにより確認方法が異なる場合があります。詳しくは各OSのサポートページをご覧ください。


### 開発者向け 
GitHub開発者の方は以下でもお問い合わせ頂けます。
また、不具合の修正など、誰でもVOICEVOXの開発や修正にもご参加頂けます。
- [VOICEVOX エディター](https://github.com/Hiroshiba/voicevox)
- [VOICEVOX エンジン](https://github.com/Hiroshiba/voicevox_engine)
- [VOICEVOX コア](https://github.com/Hiroshiba/voicevox_core)

### その他
何かご質問があれば「[よくあるご質問 （FAQ）](https://github.com/VOICEVOX/voicevox_blog/issues/15)」をご覧いただき、解決ない場合、[@hiho_karuta](https://twitter.com/hiho_karuta)までお問い合わせください。

**Comment by Apple-Yuki** [comment]
あと、
ヘルプの画面

- 利用規約
- 利用規約
- 使い方
- コミュニティ
- ライセンス
- アップデート情報


ですけど、ライセンスも結局使ってるライブラリの規約類なので

- 使い方
- FAQ
- 利用規約
- 利用規約
- ライセンス
- アップデート情報
- コミュニティ
- お問い合わせ

項目は固めた方が綺麗に見えるかなとふと思いました。

**Comment by Hiroshiba** [comment]
これで行きましょう！！

```markdown
## ご感想・ご要望
ぜひ Twitter にてハッシュタグ `#VOICEVOX` を付けてツイートしてください。（開発の励みになります。）

## 不具合・バグ報告
以下の内容を添えてハッシュタグ `#VOICEVOX` を付けてツイートしていただくか、VOICEVOX公式（[@voicevox_pj](https://twitter.com/voicevox_pj)）までご報告いただけると助かります。  

- 不具合の内容
- 再現手順（動画や写真があれば添付してください）
- 現在ご利用のVOICEVOXのバージョン

報告の際の文章の例：VOICEVOX 0.9.3でCPUモード、GPUモード共に起動しません。　　など

なお、以下の情報を後ほど確認させていただく場合がありますので、事前にお控えいただくとスムーズにご対応ができる場合があります。
- 現在ご利用のOSの種類・バージョン（例：Windows 11 21H2）
- ウイルス対策ソフトなどの有無
- 事前にやっていただいたトラブルシューティング


## 開発者の方
GitHub Issueにてご報告・ご連絡ください。

- [VOICEVOX エディター](https://github.com/Hiroshiba/voicevox)
- [VOICEVOX エンジン](https://github.com/Hiroshiba/voicevox_engine)
- [VOICEVOX コア](https://github.com/Hiroshiba/voicevox_core)

## その他

<!--
FIXME: FAQができたらコメントを外す
何かご質問があれば「[よくあるご質問 （FAQ）](https://github.com/VOICEVOX/voicevox_blog/issues/15)」をご覧いただき、解決できない場合は
-->

[@hiho_karuta](https://twitter.com/hiho_karuta)までお問い合わせください。
```

最初のクレジットは以降に出てくるので省いたのですが、書かれた意図はなんでしたか？👀

バージョンの確認方法はメンテナンスが大変なので省いちゃおうと思います。せっかく調べていただいたのにすみません。
ただ重要な情報だとは思うので、ソフトウェア側でOS情報を取得してコピーできるようにできると良いかもと思いました。

**Comment by Apple-Yuki** [comment]
@Hiroshiba 
アプリケーションへのクレジットがどこにもないなーと思いまして。

**Comment by Hiroshiba** [comment]
あーたしかに・・・
最初にクレジットあるのも良さそうに感じました。
もしよかったらプルリクエスト頂けると、とても嬉しいです･･･！ @Apple-Yuki 
（難しそうであれば言って頂ければ！）

**Comment by Apple-Yuki** [comment]
@Hiroshiba 
`src/components`　`public`のmdを読み込んでる感じでしょうか？

`<div class="q-pa-md markdown markdown-body" v-html="."></div>`の`v-html="  "`の内容を書き換えで大丈夫なのでしょうか？

一旦ここまでは作業終わってます。
https://github.com/Apple-Yuki/voicevox/blob/patch-4/src/components/HelpDialog.vue
https://github.com/Apple-Yuki/voicevox/blob/patch-4/public/Contact.md　
（Contact.mdはpatch3で作って画面作成をpatch4で作っちゃったので自分のgitの方で一旦mergeして統合しましたが。）

```
<template>
  <q-page class="relative-absolute-wrapper scroller bg-background">
    <div class="q-pa-md markdown markdown-body" v-html="Contact"></div>
  </q-page>
</template>

<script lang="ts">
import { defineComponent, onMounted, ref } from "vue";
import { useStore } from "@/store";
import { useMarkdownIt } from "@/plugins/markdownItPlugin";
export default defineComponent({
  setup() {
    const store = useStore();
    const policy = ref("");
    const md = useMarkdownIt();
    onMounted(async () => {
      policy.value = md.render(await store.dispatch("GET_POLICY_TEXT"));
    });
    return {
      policy,
    };
  },
});
</script>

<style scoped lang="scss">
.root {
  .scroller {
    width: 100%;
    overflow: auto;
  }
}
</style>
```

**Comment by Hiroshiba** [comment]
はい！　ちょっと正確にはわかりませんが、たぶん合っていると思います！

markdownを分離して、問い合わせ用の.vueを追加したプルリクエストを送って頂ければ・・・！
gitでわからないことがあったら聞いて頂ければ！（返信にタイムラグがありますが。。）
