### ISSUE TITLE
ディスカッション：使い方の一番下にあるFAQに関して

### ISSUE THREAD

**Issue by Apple-Yuki** [VOICEVOX/voicevox#617]
## 内容

おそらくFAQも今後増えると思うと思うので、メンテナンスのしやすさ向上のため、別項目の作成をした方がいいのではないかと思ったので改善案というか半分ディスカッションissue作成です。

### Pros 良くなる点

関連issue：#615　を参照

== to connected  issue ==
VOICEVOX issue:
#615 

VOICEVOX BLOG issue:
[#12](https://github.com/VOICEVOX/voicevox_blog/issues/12)
[#15](https://github.com/VOICEVOX/voicevox_blog/issues/15)

**Comment by Hiroshiba** [comment]
Q&Aが分離されたのでcloseします！
