### ISSUE TITLE
VSTプラグインを取り扱えるようにする

### ISSUE THREAD

**Issue by qwerty2501** [VOICEVOX/voicevox#619]
## 内容

[VST](https://ja.wikipedia.org/wiki/Virtual_Studio_Technology#:~:text=Steinberg's%20Virtual%20Studio%20Technology%EF%BC%88%E4%B8%80%E8%88%AC,%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%A0%E3%82%92%E3%80%81%E3%83%97%E3%83%A9%E3%82%B0%E3%82%A4%E3%83%B3%E3%81%A8%E3%81%97%E3%81%A6) とはよくDAWなどで使用されている音声データにたいしてエフェクトをかけたりするプラグインの共通規格です。
これに対応することにより既存のプラグインにより音声エフェクト機能をユーザーに提供することができます。
調べた感じだと歌声系のものだとこの機能は提供されてるようですが、会話系だと提供されてなさそうでした。恐らく需要が少ないと見られてるのでしょう。
しかしニコ動ではVSTを使用してボイロ音声に対してエフェクトをかける方法が紹介されているのである程度需要はあるのではないかと思われます。
https://www.nicovideo.jp/watch/sm31787344
https://www.nicovideo.jp/watch/sm33064762
動画内ではAviUtlのプラグインからVSTプラグインを取り扱えるようにして、編集する方法が紹介されてますが、これは本来音声ソフトウェア側で完結するべき機能ではないかと思います。
プラグイン0の状態で配布すれば既存機能にそこまで影響を与えることはないでしょう。
優先度は低そうですが

### Pros 良くなる点
- AviUtlをメインに使用していないユーザーの表現の幅を増やすことができる。あるいは手間を削減させることができる。

### Cons 悪くなる点
- 実装コスト、難易度が高い
- electronアプリケーションに組み込めるか不透明

### 実現方法

VST hosting機能を実装する(恐らくC++)

**Comment by shigobu** [comment]
どうだろう。

## 動画編集の効率化について

プレイバックの音声だけにエフェクトを適応させるならば面白い機能ではありますが、エフェクトの適応した状態で保存できる機能は、動画編集の効率化やユーザーの増加につながらないと思います。

なぜかというと、エフェクトの適応した音声を書き出し、動画編集ソフトに取込み編集中に、エフェクトの効き具合を変更したい場合、もう一度VOICEVOXを開きパラメータの調整をして再書き出しを行う必要があります。
それを行うくらいなら、ドライ(エフェクト無し)で書き出し、動画編集ソフトでエフェクトを調整したほうが効率が良いです。

逆に、VOICEVOXをVSTプラグイン化するならばわかります。そうすれば、書き出しすらいりません。

ボーカロイドエディターがこれに似ていて、後にVSTプラグイン化(ピアプロスタジオ)やCubaseへ統合(VOCALOID™ Editor for Cubase)された経緯があります。
VSTプラグイン化やCubaseへ統合される前は、ボーカロイドエディターで歌声を作成・書き出しを行い、DAWへ取込み、歌声の修正を行いたい場合はまたボーカロイドエディターで編集し再書き出しを行い、の繰り返しだったと聞いています。

実装コストが高い割に、動画編集の効率化につながらないと思います。

## 動画編集ソフトを使用していないユーザーについて

ここまで書いてみて、Prosを再確認しました。
> AviUtlをメインに使用していないユーザーの表現の幅を増やすことができる。あるいは手間を削減させることができる。

AviUtl含め多くの動画編集ソフトには少なからずエフェクト追加機能があると思うので、「AviUtl = 動画編集ソフト」と読み替えて、「動画編集ソフトをメインに使用していないユーザー」あるいは「エフェクト機能の無い動画編集ソフトのユーザー」について考えます。

これらのユーザーに対しては、簡易的でよく使うエフェクトのみを適応できる機能があればよいかと思います。これらは、VSTプラグインである必要はありません。
例えば、一つのスライダーで調整できるエコーやロボット声化など、固定の種類のエフェクトをはじめから搭載しておくみたいな。

より詳しく編集したい場合は、動画編集ソフトやDAWの使用を案内すればいいでしょう。

---
**VOICEVOXのVSTプラグイン化を推します。**

**Comment by Hiroshiba** [comment]
コメントありがとうございます！！

動画制作の流れを知りませんでした。
たしかに制作ソフト側で、ボイボ音声にVSTプラグインを適用してしまった方が楽そうです。
労力やメンテコストの割に、あまりユーザー獲得には繋がらなそうだと感じました。

簡易的なエフェクター機能は面白そうです。何がいるのかを知りつつ、エンジン側に実装しても面白いかもと感じました。

VOIcEVOXのVST化は興味があります。
ただ全く知識を持っていないので想像がつかないのが本音です。
もし知識をお持ちでしたら、issue作っていただけるととても嬉しいです！

**Comment by qwerty2501** [comment]
なるほど。確かにVOICEVOX自体をVSTプラグイン化したほうが良さそうですね。

しかしVSTプラグイン化するのは(VOICEVOXでVSTをhostするより)かなりコストはかなりそうです。
基本的にC++で書かなければならず、そもそも求められるUIが違ってくるのもあるためリポジトリを分けて一からエディタを作り直すぐらいには。

やる気があるならC++にJUCEというApplication frameworkがあるのですが、そこにVST plugin作成がサポートされてるのでそれを使ってやるのが良さそうです。
https://trap.jp/post/1136/

**Comment by Hiroshiba** [comment]
ですね、リポジトリは分けるべきだと思います…！

**Comment by Hiroshiba** [comment]
たぶんvstを挿せるようにするタスクはやらないことになると思うので、このissueはcloseしちゃいます。
その後も議論や質問の場として利用していただければ！

**Comment by shigobu** [comment]
じつは、ちょっと前からJUCEでプラグイン化できないか妄想したりしてました。
JUCE使ったこと無いのとC++っていうので、妄想のまま終わりそうでしたけど。

気が向いたら、別でリポジトリ作ります。
気が向いたら・・・

**Comment by qwerty2501** [comment]
やれたら面白そうですが、プラグインは単一バイナリで配られている節があるのでエンジンをどうするかは課題になりそうですね。

> 簡易的なエフェクター機能は面白そうです。何がいるのかを知りつつ、エンジン側に実装しても面白いかもと感じました。

@Hiroshiba 今ちょっと気になったのですが、エンジンに機能盛り込む=エンジンのAPIが変わるだと思うので広くエンジン製作を募ることを考えるとあまりエンジンではやらないほうが良いのではないかと感じました。API定義に影響がでるのと、その分エンジン製作者側の手間が増えるわけですから。
また簡易エフェクター機能をエディタ側に実装すれば複数エンジンがその恩恵をうけることができるのでやるとしたらエディタ側ではないでしょうか？

**Comment by Hiroshiba** [comment]
VSTプラグインがどういう形式になるのか全くわかっていないので想像止まりなのですが、エンジンを叩く何かなのかなと考えています。
エンジン側にあればVOICEVOXエディタがなくても動くし、エディタのアプデの周期にとらわれずにアップデートできて良いのかなとか考えていました。

エンジンでもエディタでもない別リポジトリに作って、ポート指定してエンジンを叩くとかのが良いかもです。

**Comment by qwerty2501** [comment]
> VSTプラグインがどういう形式になるのか全くわかっていないので想像止まりなのですが、エンジンを叩く何かなのかなと考えています。

基本そうだと思ってますが、エンジン起動してなかったときどうするかは少し考えないといけなさそうです。
https://www.nicovideo.jp/watch/sm31787344
動画を見る限りdllにして配布してるようですね。特段インストーラーとかはなさそうな印象です。
エンジン同梱配布だとdllをコピーされて別のところで管理されるような挙動だとちょっと困りそうです。
キャッシュディレクトリをどこかに指定し、プラグイン起動時にキャッシュディレクトリ内にエンジンがなかったらGitHubのassetsからエンジンとってくるとかですかね？
あとユーザー環境にpythonがインストール済みであることを要求するのも導入障壁になりそうです。

> エンジンでもエディタでもない別リポジトリに作って、ポート指定してエンジンを叩くとかのが良いかもです。

こっちは簡易エフェクター文脈の話ですよね？　若干プロキシ的に働くサーバーですかね。良さそうに感じました。
もしくはこれはサーバーではなくnpmパッケージとして実装してライブラリとしてもCLIツールとしても働くものを作ってしまっても良さそうですね。余分なポート専有せずに済みますし。

**Comment by shigobu** [comment]
VSTプラグイン化のリポジトリ作りました。
https://github.com/shigobu/VOICEVOX_vstplugin

中身はほぼ空で、READMEがあるだけですが。
妄想を妄想のまま終わらせないために作りました。

**Comment by qwerty2501** [comment]
@shigobu 素晴らしいですね！VSTについては私も少し興味があったので手伝えそうなら手伝います
