### ISSUE TITLE
Linux GPU版のダウンロード不具合

### ISSUE THREAD

**Issue by elftune** [VOICEVOX/voicevox#635]
## 不具合の内容

LinuxのGPU版が(そのままでは)ダウンロードできない状態になっています。CPU版はOKです。

### 現象

`VOICEVOX.Installer.0.9.4.Linux.sh` の最後から2行目に `NAME=linux-nvidia-appimage` が無いので `tmp_voicevox_installer.sh` が失敗します(指定すればDLできます)。

また、LinuxのZIPダウンロードはどちらを選んでもCPU版になっていると思います,

以上から、Linux/GPU版のDLがそのままではできない状態です。

## VOICEVOXのバージョン

0.9.4

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [x] Linux (WSL2/Ubuntu 20.04)

**Comment by PickledChair** [comment]
ご報告ありがとうございます。

> `VOICEVOX.Installer.0.9.4.Linux.sh` の最後から2行目に `NAME=linux-nvidia-appimage` が無いので `tmp_voicevox_installer.sh` が失敗します(指定すればDLできます)。

手元の Linux 環境で GPU 版のインストーラーを実行してみましたが、GPU 版も正常にダウンロードできているようです。以下のように、`NAME` の値を指定をしない場合はインストーラースクリプト内でデフォルト値 `linux-nvidia-appimage` が適用されるので、本来なら GPU 版がダウンロードされるはずです。

https://github.com/VOICEVOX/voicevox/blob/97f5922d072f28639d4b76eabb37aa48b498505d/build/installer_linux.sh#L28

しかしダウンロードされなかった、かつ `NAME=linux-nvidia-appimage` を指定すればダウンロードされた、ということですので、想定していない不具合があるのかもしれません。ダウンロードに失敗した時のエラー表示をいただければ手がかりになるかもしれないので、教えていただけると大変助かります。

> また、LinuxのZIPダウンロードはどちらを選んでもCPU版になっていると思います,

こちらについては、GPU 版のダウンロードリンクが誤っていることを確認しましたので、 https://github.com/VOICEVOX/voicevox_blog/issues/41 に報告いたしました。

**Comment by elftune** [comment]
ご回答ありがとうございます。他のLinux機でGPU版インストーラーでDLが実行されるのを確認しました。

状況を再度確認してみました。今回の件はWSL2/Ubuntu 20.04で `./VOICEVOX.Installer.0.9.4.Linux.sh` を実行したのですが、環境変数 `NAME`  が元々存在しており、`./VOICEVOX.Installer.0.9.4.Linux.sh` で `NAME` 指定なしで `tmp_voicevox_installer.sh` を呼び出すとその `NAME` で実行されてしまうためDLに失敗する、という状況でした。
(`NAME` は自分のPC名がセットされていた。WSL2の仕様なのか、自分で以前設定したのか不明です。すみません)

```
...
[+] Downloading https://github.com/Hiroshiba/voicevox/releases/download/0.9.4/PC名.7z.txt...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   141  100   141    0     0    431      0 --:--:-- --:--:-- --:--:--   431
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
```

**Comment by Hiroshiba** [comment]
なるほど！！
とりあえずGPU版のインストーラでNAMEを指定するようにしてみます。

ただ今回のような課題が今後もあるかもなので、NAME環境変数が定義済みであっても正しく動くようにするか、NAMEという名前をやめてかぶりにくい名前にするかしたいですね

**Comment by elftune** [comment]
インストーラーが更新されているのを確認しました！
