### ISSUE TITLE
起動時に一瞬真っ白になるのを防ぐ

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#637]
## 内容

今のlatestのVOICEVOXを起動すると、エンジンが起動したあとUIがレンダリングされるまで真っ白な画面が表示されています

https://user-images.githubusercontent.com/4987327/148593681-99ade422-2b6d-436f-adc0-dad946c555da.mp4

ユーザー的にはバグったのかな？と一瞬不安になると思うので、なるべく避けた方が良いかもとおもいました。

### Pros 良くなる点

ユーザーに困惑を与えない

### Cons 悪くなる点

どう実装すればいいかが要議論

### 実現方法

たしかエンジンが起動したあと、画像などのリソース取得などをしてからレンダリングが走るようになっているはずです。

レンダリングが完了するまでloadingぐるぐるインジケータを表示し続けるか、
リソースの読み込みがまだであっても空のUIが表示されるか、どちらかが良いかなと思っています。

実装難度的には圧倒的に前者のほうが簡単だと思うので、とりあえず前者がいいのかなとかんじました。

## その他

@MT224244 さん、お時間あったりしますか・・・？ 👀

**Comment by MT224244** [comment]
すみません、しばらく時間取れそうにないので他の方へお願いします…。(レビューも滞っていて申し訳ありません…)

**Comment by Hiroshiba** [comment]
了解です、コメントありがとうございます！
誰かやっても良いという方がいらっしゃったらおまかせしたいです。
（難しそうであれば自分でやりたいと思います）
