### ISSUE TITLE
Linux用zip配布物をAppImageからprepackage-targzに変更したい

### ISSUE THREAD

**Issue by aoirint** [VOICEVOX/voicevox#638]
## 内容

Linux版の非インストーラ配布物として、tar.gz形式（`linux-prepackage-targz`の中身のtar.gzファイル）を配布するように変更したいです。

Linux版のzip配布物は、0.9.4現在AppImageファイルをzip圧縮したもの（`linux-*-appimage`）が配布されています。

一方自動ビルドでは、AppImageとは別に、Windows zip版と同様のディレクトリ構造でシンボリックリンクやファイル権限が保たれるtar.gz形式を作成しています。

AppImageファイルの中身を取り扱うには、Linux用インストーラで使用しているような特殊なコマンドを使う必要があり、Windowsと同様に同梱ファイルを取り扱うのが難しいです（エンジンの単体起動、コアの置き換えなど）。

Discordは、deb/rpm版（インストーラ版）とtar.gz版を配布していますが、tar.gz版は`linux-prepackage-targz`のようなディレクトリ構造になっています（個人的には、zip版/tar.gz版として期待されるのはこちらだと思っています）。

- <https://discord.com/download>

### Pros 良くなる点

- Linux用の非インストーラ配布物をWindows用zipと同様のディレクトリ構造であることを想定して扱えるようになる

### Cons 悪くなる点

- 既存バージョンと非インストーラ配布物の形式が変わる
    - 既存ユーザが混乱するかもしれない
    - Linux用の配布物は、インストーラ、AppImage（zip圧縮されていない）、tar.gzの3種類にしてもいいかもしれない

### 実現方法

リリース手順の変更、もしくは #636 でリリースする成果物を変更

## VOICEVOXのバージョン

0.9.4

## OSの種類/ディストリ/バージョン

- Linux

**Comment by Hiroshiba** [comment]
良いと思います！！

もうtargz版に置き換えてしまっても良いのですが、アップデートと同時に行うことでユーザーの混乱を最小化すると良いのかなと思いました。
（というのはちょっと建前で、ダウンロード数そこまでないだろうから次のタイミングでいいかなーと考えています）

ちなみにmacもtargzのほうが良いんでしたっけ、だとしたらそちらもそうしちゃえると最高かもですね。
（このPRで全部解決するかは置いといて）releasesでの配布物はこんな感じになりそうでしょうか。

* Windows インストーラー版
* Windows Zip版
* Mac インストーラー版
* Mac tagz版
* Linux インストーラー版
* Linux targz版

**Comment by PickledChair** [comment]
> ちなみにmacもtargzのほうが良いんでしたっけ、だとしたらそちらもそうしちゃえると最高かもですね。

Mac 版ビルドを追加した時にそのような会話をした記憶があります。最初は targz でないと File permission が保存されないと思い込んでいたので、zip ではなく targz に固めることを選択肢にしていました（参考： https://github.com/VOICEVOX/voicevox/pull/570#issuecomment-991705346 ）。

しかし、試しに zip を作ってみたところ、実際には zip でも File permission が保存されていたので zip で行きました（参考： https://github.com/VOICEVOX/voicevox/pull/570#issuecomment-991824635 ）。

なので、zip のままで良いと思います……！

**Comment by Hiroshiba** [comment]
なるほどです、ということでこんな感じにしてみようと思います！

```
Windows インストーラー版
Windows Zip版
Mac インストーラー版
Mac zip版
Linux インストーラー版
Linux targz版
```

**Comment by aoirint** [comment]
macosのzip版を踏まえるとtargzでなくzipでもファイルパーミッションが維持されそうです。

そこで #656 のようにzipファイルに統一するのがいいかどうか、ちょっと悩みます。

zipに統一すると、OS間でビルド処理の共通化・簡略化を進めることができます。

ちなみに、現在のmain e276e57532e1a3025e07230ecdc20d7dccbb5f47 ではビルド処理のミスでprepackage-targzは無圧縮のtarになってしまっていることに気づきました。これは、圧縮時のコマンドを`tar cf`から`tar cfz`にして直すことができます。

Windows向けに圧縮率の高い7z形式で配布しないのは、標準で展開できないというのが理由になると思うので、Linux向けの場合にも標準で展開できるのが望ましいのかなと思います。

GitHubのReleaseを見ると、ソースコードの形式としてzipとtar.gzが用意されています。
Discordは、debとtar.gz形式で配布されています。

Linux用の配布物はtar.gz/tgzやtar.xzがよく使われているイメージで、配布形式にtar系を選んでいるのは、Linux環境にはtarコマンドが標準で入っていることが多いというのが理由なのかなと思いました。

Ubuntu Server 18.04、20.04には標準でtarコマンドは入っていましたがzip/unzipコマンドは入っていませんでした（Dockerイメージ）。

しかしVOICEVOXエディタはGUIアプリケーションなので、サーバー向けOSではなく、Ubuntu Desktop 18.04、20.04のようにデスクトップ向けOSで標準でzip展開ができればzipでもいいのかも・・・？　という考えで進めることもできそうです。

個人的には、先例にならってtargzで進めたい気持ちがあります・・・！

**Comment by Hiroshiba** [comment]
なるほどです、デフォルトでunzipが入っていないのは確かに不便そうなので、targzが良いかなと感じました！
いまzip配布にするブランチでtargzを消していますが、消すのをやめてこちらを配布するようにしたいと思います！
