### ISSUE TITLE
設定画面の項目ごとの詳細情報をわかりやすく表示する

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#647]
## 内容

設定画面の項目にて、トグルボタンにカーソルを当てるとその項目の詳細が表示されるようになっています。
![image](https://user-images.githubusercontent.com/4987327/150149800-564572c2-474b-410d-837e-36b7f2b0e634.png)

情報が欲しい人が必ずしもここにカーソルを当てるわけではないので、詳細情報を表示するのがわかりやすいUIに変更したいです。

何となく思っているのは、よくある？ボタンを右端か左端に表示し、クリックかマウスホバーで詳細情報を出してあげると良いのかなと思いました。

### Pros 良くなる点

情報が伝わりやすくなる

**Comment by jdkfx** [comment]
こちらのissueやります！

**Comment by Hiroshiba** [comment]
おお！！　是非お願いしたいです！！

ちなみにどんなUIを想定されていますか？
実装前に相談できると、より良いデザインに着地できるかもなので･･･！

**Comment by jdkfx** [comment]
こんな感じでカーソルが（？）にホバーした際に詳細情報を表示するようなものを想定しています．
どうでしょうか？

![image](https://user-images.githubusercontent.com/40142697/161522512-5fcb586f-f922-437c-83c3-dc219be98016.png)

**Comment by jdkfx** [comment]
では，こちらのデザインで実装をしていきます．
ただし，トグルボタンにホバーした際の詳細情報を表示する既存の機能と二重になってしまう可能性があるので，こちらについてはどちらか一方にしたほうがよろしいでしょうか？

また，（？）のアイコンなどについて，フリーで使用できるものでしたらどんなものを使用してもよろしいでしょうか？
既に同じような内容でアイコンを利用している場合どちらから利用されておられますか？

**Comment by Hiroshiba** [comment]
ホバーで出てくる内容が同じ場合は、？アイコンの方だけにする感じがわかりやすそうに感じました！

？アイコンに関しては、既にfontとして使えるものがあります。fontawesomeかな…？
コード内を「icon」で検索するとヒットすると思います。そのコンフィグ画面の「❌」とかもそうだったと思います。

**Comment by jdkfx** [comment]
わかりました！ありがとうございます！
実装の方進めていきたいと思います！
