### ISSUE TITLE
保存確認ダイアログの×ボタンの挙動を変更する

### ISSUE THREAD

**Issue by takana-v** [VOICEVOX/voicevox#662]
## 内容

現在（0.9.4）では、保存確認ダイアログで「×」を押すと「破棄」と同様の挙動をします。
これを「キャンセル」と同様の挙動をするように変更します。

### Pros 良くなる点

キャンセルする意図で×ボタンを押した場合のデータ消失を防ぐことができます。

### Cons 悪くなる点

恐らく無し

## VOICEVOXのバージョン

0.9.4

## その他

現時点でのmasterでの挙動を確認できていません。
もし既に変更されているようであればcloseをお願いします。

**Comment by Hiroshiba** [comment]
おお、本当ですね･･･
ちょっと危なそうなので、ちょっと高めの優先度を付けてみました。

**Comment by Hiroshiba** [comment]
ダイアログを開くときに`cancelId`を指定すると良さそうでした。
ちょっと修正してみます。
