### ISSUE TITLE
音高や話速のプリセット

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#67]
例えば「声が高めのずんだもん」で動画を作りたい時、今だとずんだもんがしゃべるテキスト全部で音高を上げる必要がある。
ユーザーがプリセットを作れるようにしたい。

プリセットには「キャラクターが誰か」「話速」「音高」「抑揚」あと「プリセット名」があると良さそう。

プリセットを用意するためのUIをどうするかが・どうやって保存するかが課題かも。
UIはAudioInfoPane（ソフトウェア右側の欄）に「プリセットとして登録」とかあれば良さそう。

意見・実装お待ちしています。

要望
https://twitter.com/InfoStLabo/status/1430472611364966409

**Comment by Hiroshiba** [comment]
ご要望 https://twitter.com/KigaNatsuno_2nd/status/1439613491430653954
![image](https://user-images.githubusercontent.com/4987327/133937249-5c76faf9-6807-40c8-8346-476c47f0e2f9.png)

**Comment by Oyaki122** [comment]
実装を進めてみています
![image](https://user-images.githubusercontent.com/42294158/135508610-9de1b9d6-6f27-4b85-b9ed-87320176e9f5.png)

ここで質問なのですが、プリセット削除画面(将来的には並び替えも)のUIについて、設定画面とダイアログのどちらのほうがいいでしょうか？
なおプリセット追加時のタイトル入力に関してはダイアログを使用する方針です
![VOICEVOX preset settings](https://user-images.githubusercontent.com/42294158/135508709-e79b900a-1e3f-4b17-87b9-fcd661ba284d.png)
![VOICEVOX preset dialog](https://user-images.githubusercontent.com/42294158/135508722-02b38eb5-1bc8-4c2a-9f13-fa11195e2014.png)

**Comment by Hiroshiba** [comment]
おー！良いですね！！

> プリセット削除画面(将来的には並び替えも)のUIについて、設定画面とダイアログのどちらのほうがいいでしょうか？

消去したいと感じる場所からすぐ呼び出せると嬉しそうなので、ダイアログが良いと思います！

**Comment by Hiroshiba** [comment]
実装されたのでcloseします！
