### ISSUE TITLE
Mac: テキスト欄でコピペなどのショートカットキーが使えない

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#675]
## 不具合の内容

Macにて、テキスト欄でcmd+cやvが使えませんでした。
とりあえず他の方でもそうか確認する用途も兼ねてissue化してみました。

### 現象・ログ

全体選択のcmd+aなどもできなそう。
先頭移動のctrl+aはできました。

### 再現手順

普通に起動して編集する

### 期待動作

コピペができる

## VOICEVOXのバージョン

0.10.2

## OSの種類/ディストリ/バージョン

- [x] macOS

**Comment by shigobu** [comment]
私の環境でも同じでした。

**Comment by PickledChair** [comment]
自分の環境でも同様でした。

調べたところ、`npm run electron:serve` で立ち上げているときは Electron のデフォルトのメニュー項目やキーボードショートカットのアクセラレータが備え付けられており `Cmd+C` や `Cmd+V` などが機能するが、パッケージ化されるとそれらが設定されないので使えない、という仕様になっているようです（自分で試してみた範囲では確かにそうなっていました）。パッケージ化された後も使えるようにするには、メインプロセスで明示的に設定しなければならないということです。

参考： https://github.com/electron/electron/issues/2591

上記の Issue をさらっと見た感じでは、解決策としては Electron の標準のメニューを設定する、ということが説明されていました（コード例も例示されていました： https://github.com/electron/electron/blob/cb9be091aa203f27496b2b8993e10b5c554525c4/default_app/menu.js ）。ただ、他の OS では不要な設定だと思うので、Mac のみで設定する必要がありそうです。
