### ISSUE TITLE
生成＆再生専用モードが欲しい

### ISSUE THREAD

**Issue by sevenc-nanashi** [VOICEVOX/voicevox#684]
## 内容

生成＆再生だけのモードが欲しいです。
入力してEnterだけで生成して自動再生する、みたいな。
![image](https://user-images.githubusercontent.com/59691627/152102270-5c738bf1-a13e-4bd3-b932-6d72fc555af0.png)

### Pros 良くなる点

VB-Cable等を使ってDiscord等のVCにVoicevoxで参加するときに便利になる

### Cons 悪くなる点

利用機会が限られている

### 実現方法

- タイトルのピンの左に再生アイコンのボタンをつけ、クリックで切り換え

## VOICEVOXのバージョン

0.10.3

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

Windows 10 Pro 21H2 19044.1415

## その他

ここまでUI変更がなくてもEnterで計算と同時に生成＆再生のオプションがあるとうれしいです。

**Comment by raa0121** [comment]
一応、 [民安★TALK](https://publish-tool.blogspot.com/2012/09/voiceroid-live-gear2ch-niconama-comment.html) を使用すると、生成＆再生が用意になると思います。
利用検討をしてみてください。

**Comment by Hiroshiba** [comment]
@sevenc-nanashi issueありがとうございます！

VOICEVOXのエディタはどちらかというと凝った音声を作るためのソフトウェアなので、実装は避けたいなと思います。
ここは一応VOICEVOXエディタのリポジトリで、かつエディタ側の実装は見送るという判断ということで、issueをcloseしたいと思います。


ところで、VOICEVOXは音声合成エンジンが別れているのですが、こちらにもデバッグのために使える簡単なUIがほしいなと思っています。
それこそ、テキスト欄があって、エンターを押したら再生されるようなものがほしいです。
もしよかったら実際に作成し、VOICEVOXエンジンの機能としてリリースを目指す、というのはどうでしょう？

エンジンはpythonで書かれています。pythonでGUIを作るのは`PySimpleGUI`などのライブラリがありそうです。
Nanashi.さんのリポジトリにpythonがあり、かつコードもしっかりされていると感じたのでご提案させていただいた次第です。
エンジンのリポジトリはこちらです！ https://github.com/VOICEVOX/voicevox_engine

**Comment by sevenc-nanashi** [comment]
わかりましたー、時間がある時にやってみますね。

**Comment by Hiroshiba** [comment]
わからないところとか方針困ったところとかあればissue作成いただければ！
