### ISSUE TITLE
【質問】NVIDIA製以外のGPUの対応予定について

### ISSUE THREAD

**Issue by cyatarow** [VOICEVOX/voicevox#686]
## 質問の内容
昨年11月のIssue（https://github.com/VOICEVOX/voicevox/issues/479#issuecomment-968294000 ）にて、@Hiroshiba さんはAMD/Intel製GPUの対応予定について「_可能性としてはありますが、かなり先の話だと思います。_」と回答していますが、その後@chihayuki さんにより「_ONNXへの移行により、NVIDIA/AMD/Intel問わず使用可能になる_」（https://github.com/VOICEVOX/voicevox_engine/issues/69#issuecomment-932955492 ）という旨の提案が挙がりました。
そして、バージョン0.10.xでVOICEVOXのコアがONNXに移行したわけですが、AMD/Intel製GPU対応の実現可能性について、現在はどうなっているのでしょうか?

もしAMD/Intel製GPUに対応すれば、快適なGPUモードを使える人が増えることが期待できます。
CPU内蔵GPUだけでGPUモードを動作させられるようになり、NVIDIA製グラボを購入しなくてもよくなる他、物理的にグラボを搭載できないミニPCなどでもGPUモードを利用できるようになるはずです。
また私としては、IntelがdGPU「Arc」を今年投入することも見越しています。

なお、私はVOICEVOX内部のコードについて詳しくありません。

- キーワード: 内蔵GPU、AMD Radeon、Intel UHD Graphics、Intel Arc

## VOICEVOXのバージョン

0.10.4

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by Patchethium** [comment]
It is possible on Windows, with onnx runtime based on [directML](https://github.com/microsoft/DirectML).

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！

@Patchethium さんのおっしゃるとおり、ONNXに移行したことによってDirectMLを使えば確かにAMD GPUでも高速音声合成ができそうに思います。
https://onnxruntime.ai/docs/execution-providers/DirectML-ExecutionProvider

実装予定は今のところありません。
ので、とりあえずissueを作ってみました！
関わってくるのはVOICEVOXの音声合成コア部分なので、そちらに作成してみました。

- https://github.com/VOICEVOX/voicevox_core/issues/74

開発したい気もするのですが、AMD製GPUなどを持っていないと実装チェックができなそうです。
もしお持ちの方がいらっしゃったら、ぜひ取り組んでみて頂けると･･･！

とりあえず質問のお答えはできたかなと思うのでcloseします。
もし追加で質問等あればコメントを追記して頂ければ！
