### ISSUE TITLE
CPU/GPUモードがわかるようにタイトルに表示する

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#694]
## 内容

タイトルにバージョン情報を表示している感じで、CPUモード・GPUモードがわかるようになってほしいという要望を見かけました。
https://twitter.com/M_C3O2/status/1490358332292759552

スクショ撮られたときにどっちなのかわかって便利だし、デフォルトがCPUモードなことに気づけるので良いのかなと思いました。

### Pros 良くなる点

どっちなのかわかって便利

### Cons 悪くなる点

タイトルバーがごちゃつく

## VOICEVOXのバージョン

0.10.4

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by Hiroshiba** [comment]
解決したのでcloseします！！

**Comment by o108minmin** [comment]
@Hiroshiba  
mergeありがとうございます。一応、Ubuntu 20.04とmacでの動作確認のスクリーンショットも撮ったので追記しておきます

## Ubuntu 20.04

![Screenshot from 2022-03-18 14-35-17](https://user-images.githubusercontent.com/6399740/159408269-1ff9a088-fdf4-400b-a38e-e2264ef637f1.png)

## mac

![スクリーンショット 2022-03-18 13 47 47](https://user-images.githubusercontent.com/6399740/159408210-a54023f1-5156-4b11-a9d8-1687a93d51f1.png)

**Comment by Hiroshiba** [comment]
@o108minmin
確認ありがとうございます！
もしよければまた別のプルリクエスト、お待ちしています！！
