### ISSUE TITLE
音声生成前に音声停止ボタンを押すと、音声再生が止まらない

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#696]
## 不具合の内容

VOICEVOXは音声再生ボタンが押されたあと、音声が生成され、その後に音声が再生されます。
この音声が生成される前にも音声停止ボタンが押せるのですが、内部処理の都合上音声再生が止まりません。
この挙動はバグっぽい印象を与えてしまうので、できれば直すと良いかなと思いました。

報告 https://twitter.com/M_C3O2/status/1490383451740340225

### 現象・ログ

長いテキストで再生し、すぐに停止ボタンを押すと、音声が再生されてしまう。

### 期待動作

音声が再生されない

**Comment by ToshihiroWatanabe** [comment]
修正方針について質問です。

こちらのissueの説明を見ると、修正方針としては「音声生成前に停止ボタンを押しても音声が再生されないようにする」というふうに読み取れました。

ただ、音声再生/停止ボタンはメイン画面だけでなく「読み方＆アクセント辞書」画面にもあり、「読み方＆アクセント辞書」画面では、音声生成中は音声停止ボタンが押せないようになっています。
メイン画面の音声再生/停止ボタンの挙動を「読み方＆アクセント辞書」画面のものに合わせたほうが、コードの修正も楽で良さそうですが、いかがでしょうか。

**Comment by Hiroshiba** [comment]
おお、なるほどです！！
ユーザーの期待的にはどちらかというと生成が止まってくれたほうが嬉しそうですが、実装難度や需要の大きさ的に見てもそちらの仕様に合わせるのが良いのかなと思いました！！

**Comment by ToshihiroWatanabe** [comment]
ありがとうございます。
では、「読み方＆アクセント辞書」画面の音声停止ボタンの仕様に合わせる方向で修正を始めます。
