### ISSUE TITLE
Macでキャラクター音声が再生されていないことがある

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#701]
## 不具合の内容

Macでキャラ音声が再生されず、openjtalkの音声が再生されるという報告をいくつか見かけました。

https://twitter.com/mimimi_viaggio/status/1493241530227720195
https://twitter.com/misoco/status/1491329105354444801

### 現象・ログ

* キャラの声が変わらない
* アクセントが変わらない

### 再現手順

不明。Macのバージョンかも（Mojavaよりあとのバージョンからの報告はなさそう）

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [x] macOS
- [ ] Linux

## その他

エラーが起こっていることがわからないのは問題なのでなんとかしたいかも

**Comment by Hiroshiba** [comment]
@PickledChair さん、 @Apple-Yuki さん
mojava以前のmacを持っていらっしゃったりしますか･･･？👀

**Comment by PickledChair** [comment]
> mojava以前のmacを持っていらっしゃったりしますか･･･？👀

持っていないです、すみません😣

**Comment by shigobu** [comment]
MacBook Proをリセットしたくなったので、High Sierraにリセットしました。
High Sierraではエンジンエラーでエンジンが起動できませんでした。

runを起動したところ、以下の内容が表示されました。
```
Traceback (most recent call last):
  File "/Applications/VOICEVOX.app/Contents/MacOS/run.py", line 14, in <module>
  File "/Applications/VOICEVOX.app/Contents/MacOS/uvicorn/init.py", line 1, in <module uvicorn>
  File "/Applications/VOICEVOX.app/Contents/MacOS/uvicorn/config.py", line 8, in <module uvicorn.config>
  File "/Applications/VOICEVOX.app/Contents/MacOS/ssl.py", line 98, in <module>
ImportError: dlopen(/Applications/VOICEVOX.app/Contents/MacOS/_ssl.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/VOICEVOX.app/Contents/MacOS/libcrypto.1.1.dylib (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/VOICEVOX.app/Contents/MacOS/libcrypto.1.1.dylib
```

**Comment by Hiroshiba** [comment]
discordで頂いた情報を転載します。

Mojavaでのエラー
```bash
[22:09:51.539] [error] ENGINE: Traceback (most recent call last):
  File "/Users/---/Desktop/VOICEVOX.app/Contents/MacOS/voicevox_engine/synthesis_engine/make_synthesis_engine.py", line 39, in make_synthesis_engine
  File "/Users/---/Desktop/VOICEVOX.app/Contents/MacOS/core/__init__.py", line 130, in <module core>
ImportError: dlopen(/Users/---/Desktop/VOICEVOX.app/Contents/MacOS/core/_core.so, 2): Symbol not found: __ZNKSt3__14__fs10filesystem4path10__filenameEv
  Referenced from: /Users/---/Desktop/VOICEVOX.app/Contents/MacOS/libcore.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libc++.1.dylib
 in /Users/---/Desktop/VOICEVOX.app/Contents/MacOS/libcore.dylib
Notice: mock-library will be used. Try re-run with valid --voicevox_dir
```

> なるほど、エラーメッセージを見る限り、High Sierra でも Mojave でも、OS 標準搭載のライブラリのバージョンが合わなくて起動できないようですね。解決のしようがなさそうです……

> High Sierra では Python の ssl 関連のモジュールが読み込めないのでエンジンそのものが立ち上がらず、Mojave では Python は起動できるものの libcore.dylib が期待している libc++.1.dylib 中のシンボルが見つからないので、コアの読み込みに失敗する、ということのようです

> Mojave の場合はコアを Mojave に対応させると、Mojave でもコアが読み込めるようになるかもです。具体的には、コアの CMakeLists.txt に set(CMAKE_OSX_DEPLOYMENT_TARGET "10.14" CACHE STRING "" FORCE) の設定を加えると、動作する最小バージョンとして 10.14 が指定されます。参考１： https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html 参考２： https://qiita.com/KaiShoya/items/b3a353246478942b7a28

> コアを Mojave に対応させられるかもしれないという件ですが、思ったほど簡単ではなさそうなことがわかりました。Mojave 以前の macOS の libc++ は C++17 の std::filesystem に対応していないため、cmake がそれに気づいてビルドが落ちます。Xcode付属のclangではビルドできなさそうでした。gccを使うか、filesystem の別実装として boost を使うなどの手段がありそうでしたが、C++ や cmake に詳しくないためこれ以上深入りできておりません…… 参考： https://mem-archive.com/2019/08/17/post-2016/

https://discord.com/channels/879570910208733277/883257983029624853/943132919944318996

**Comment by Apple-Yuki** [comment]
@Hiroshiba mac miniにマウンテンライオンからストックはあるのでやることはできますよ。

**Comment by Hiroshiba** [comment]
@Apple-Yuki  おお、なるほどです！！　たしかにlatestでビルドした影響かもしれません。
もしお時間あれば、古い方の`macos-10.15`でビルドした場合に昔のmacで起動するかの調査をお願いできると嬉しいです･･･！
（ツイート見ている感じ、意外と数世代前のmacで実行されている方が多かったので）

**Comment by Apple-Yuki** [comment]
@Hiroshiba 大丈夫ですよ。

**Comment by Hiroshiba** [comment]
@Apple-Yuki  おお！！ありがとうございます、ぜひよろしくおねがいします！！！
わからないことがあれば聞いて頂ければ･･･！

**Comment by Apple-Yuki** [comment]
@Hiroshiba 一応見ておく形にはなりますが、MacOSの全て網羅は辛いので、[Microsoft Officeのライフサイクル](https://support.microsoft.com/ja-jp/office/macos-をアップグレードして-microsoft-365-および-office-for-mac-の更新プログラムを引き続き受信する-16b8414f-08ec-4b24-8c91-10a918f649f8#ID0EBBF=Office_for_Mac_2021)を参考にしたサポート範囲がいいかと思います。

> **注**: MacOS の新しい主要バージョンが一般に入手できるようになると、Microsoft は最も古いバージョンのサポートをやめて、MacOS の最新バージョンとその前の 2 つのバージョンをサポートするようになります。 古いシステムでは、製品の機能と機能の可用性が異なる場合があります。 最適なパフォーマンスでご利用いただくために、上記に指定されているいずれかのオペレーティング システムの最新バージョンを使用してください。


今だと  
- [macOS Catalina](https://ja.wikipedia.org/wiki/MacOS_Catalina)
- [macOS Big Sur](https://ja.wikipedia.org/wiki/MacOS_Big_Sur)
- [macOS Monterey](https://ja.wikipedia.org/wiki/MacOS_Monterey)

になります。

それ以前の

- [Mac OS X Lion](https://ja.wikipedia.org/wiki/Mac_OS_X_Lion)
- [OS X Mountain Lion](https://ja.wikipedia.org/wiki/OS_X_Mountain_Lion)
- [OS X Mavericks](https://ja.wikipedia.org/wiki/OS_X_Mavericks)
- [OS X Yosemite](https://ja.wikipedia.org/wiki/OS_X_Yosemite)
- [OS X El Capitan](https://ja.wikipedia.org/wiki/OS_X_El_Capitan)
- [macOS Sierra](https://ja.wikipedia.org/wiki/MacOS_Sierra)
- [macOS High Sierra](https://ja.wikipedia.org/wiki/MacOS_High_Sierra)
- [macOS Mojave](https://ja.wikipedia.org/wiki/MacOS_Mojave)

はサポート範囲外にしちゃうのがいいかも？

**Comment by Apple-Yuki** [comment]
@Hiroshiba  OSの下限は別イシュー（https://github.com/VOICEVOX/voicevox/issues/715）を作成しました。

**Comment by Apple-Yuki** [comment]
一応、Mac OS X 10.15.7（519H1715）でビルド中です。

workflow
https://github.com/Apple-Yuki/voicevox/runs/5350234976?check_suite_focus=true

build
https://github.com/Apple-Yuki/voicevox/releases/tag/0.10.4-b1

**Comment by Hiroshiba** [comment]
ビルドできてそうですね･･･！

**Comment by Apple-Yuki** [comment]
@Hiroshiba 

#715 でクリーンな環境で検証しましたが、本件の問題が出なかったですね。
そのユーザーの環境要因なんでしょうか。

現状、Sierraで試しましたが、フリーズしてたので　https://github.com/VOICEVOX/voicevox/issues/701#issuecomment-1042490255　の問題で起動しないだけかと。

**Comment by Hiroshiba** [comment]
検証ありがとうございます！！
とりあえず別キャラクターの声が再生されてしまう、というのは防げている感じになっているということなので、こちらのissueは閉じたいと思います。
@Apple-Yuki さんありがとうございました！！
