### ISSUE TITLE
ユーザー辞書UIを作る

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#709]
## 内容

エンジン側に辞書登録機能が整備されました！ （ thx!!! @takana-v  ）

- https://github.com/VOICEVOX/voicevox_engine/pull/338

合わせてエディタ側にUIを実装できればと考えています。

### Pros 良くなる点

ユーザーが読み変更辞書を作れる

### Cons 悪くなる点

UI実装が少し大変かも

### 実現方法

discordの方で @y-chan さんがデザインを考えられていたこともあっておまかせできればと思うのですが、どうでしょう 👀

## その他

間に合えばキャラクター追加を予定している0.11で実装できると嬉しいですが、0.12の目玉機能でも全く問題ないと考えています。

関連issue

- https://github.com/VOICEVOX/voicevox_project/issues/6
- https://github.com/VOICEVOX/voicevox/issues/158
- https://github.com/VOICEVOX/voicevox/issues/175

**Comment by y-chan** [comment]
はい、大丈夫です！
self-assignしますね！
