### ISSUE TITLE
【Mac OS】サポート範囲のOSの制定＆案内

### ISSUE THREAD

**Issue by Apple-Yuki** [VOICEVOX/voicevox#715]
## 内容

MacOSの全て網羅は辛いので、[Microsoft Officeのライフサイクル](https://support.microsoft.com/ja-jp/office/macos-をアップグレードして-microsoft-365-および-office-for-mac-の更新プログラムを引き続き受信する-16b8414f-08ec-4b24-8c91-10a918f649f8#ID0EBBF=Office_for_Mac_2021)を参考にしたサポート範囲がいいかと思います。

> **注**: MacOS の新しい主要バージョンが一般に入手できるようになると、Microsoft は最も古いバージョンのサポートをやめて、MacOS の最新バージョンとその前の 2 つのバージョンをサポートするようになります。 古いシステムでは、製品の機能と機能の可用性が異なる場合があります。 最適なパフォーマンスでご利用いただくために、上記に指定されているいずれかのオペレーティング システムの最新バージョンを使用してください。

関連：[Macでキャラクター音声が再生されていないことがある #701](https://github.com/VOICEVOX/voicevox/issues/701)

### Pros 良くなる点

サポート範囲を絞れて対処に速くなりやすいです。

今だと  
- [macOS Catalina](https://ja.wikipedia.org/wiki/MacOS_Catalina)
- [macOS Big Sur](https://ja.wikipedia.org/wiki/MacOS_Big_Sur)
- [macOS Monterey](https://ja.wikipedia.org/wiki/MacOS_Monterey)

になります。

### Cons 悪くなる点

以前の

- [Mac OS X Lion](https://ja.wikipedia.org/wiki/Mac_OS_X_Lion)
- [OS X Mountain Lion](https://ja.wikipedia.org/wiki/OS_X_Mountain_Lion)
- [OS X Mavericks](https://ja.wikipedia.org/wiki/OS_X_Mavericks)
- [OS X Yosemite](https://ja.wikipedia.org/wiki/OS_X_Yosemite)
- [OS X El Capitan](https://ja.wikipedia.org/wiki/OS_X_El_Capitan)
- [macOS Sierra](https://ja.wikipedia.org/wiki/MacOS_Sierra)
- [macOS High Sierra](https://ja.wikipedia.org/wiki/MacOS_High_Sierra)
- [macOS Mojave](https://ja.wikipedia.org/wiki/MacOS_Mojave)

はサポート範囲外

### 実現方法

[Microsoft Forms](https://www.microsoft.com/ja-jp/microsoft-365/online-surveys-polls-quizzes)とか使って一番ユーザーが多いOSを割り出し

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [x] macOS
- [ ] Linux

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！！

> macOS Catalina
> macOS Big Sur
> macOS Monterey

なんとなくこちらの３つで良いかなと感じました！
こちら３つで実際に動作させてみて、動くかどうかを確認していきたいですね･･･！

せっかくなのでこの３つがサポート対象であるということがわかるようにどこかで案内できると嬉しそうです。
案内をする変更が加えられたら、このissueをcloseしましょう･･･！

**Comment by Apple-Yuki** [comment]
検証リスト
M1
- [ ] macOS Catalina
- [ ] macOS Big Sur
- [x] macOS Monterey

Intel
- [ ] macOS Catalina
- [ ] macOS Big Sur
- [x] macOS Monterey

**Comment by Apple-Yuki** [comment]
@Hiroshiba 
チェック完了しました。検証結果は以下のとおりです。

-  macOS Catalina
　動作に問題なく動きました。
-   macOS Big Sur
　動作に問題なく動きました。M1（Rosetta）でも動作に問題なく動きました。
-   macOS Monterey
動作に問題なく動きました。
M1 Pro M1 Max、M1 Ultraでの動作も確認済です。

ただ、関連issue：https://github.com/VOICEVOX/voicevox/issues/701 の事象に関してissue #701 で継続的にみてみます。

**Comment by Hiroshiba** [comment]
おお、検証ありがとうございます！！！！
`Monterey`は起動したことすらなかったのでとても心強いです！！
また新バージョンが出たりしたらお願いできるととても助かります！

とりあえずmacOSのサポート範囲を制定し、動くことも確認し、案内もマージされた（まだweb記事に反映できていませんが）ので、このissueはcloseにしたいと思います。
ありがとうございました！！
