### ISSUE TITLE
辞書UI周りのリファクタリング

### ISSUE THREAD

**Issue by y-chan** [VOICEVOX/voicevox#724]
## 内容

辞書のUI実装がマージされましたが、時間との戦いだったこともあり、雑な実装や、改善必須な実装が残っています。
そこで、本Issueではこれらの問題を解消するために、修正が必要な内容を列挙します。
必要な修正が全て解決し次第、Issueをクローズします。
主に、私(@y-chan )が行いますが、一部を他の方にお願いすることがあるかもしれません。

- [x] デザインの調整 #718
  - thx @.Hiroshiba
- [x] User Dictionary APIの呼び出し分離
  - APIの呼び出し実装をUIサイドから、Vuexに移動させる
- [x] Template/CSS周りのリファクタ
  - 無理くりJSで制御している箇所や、数値を埋め込んでいる箇所があるので、それらをいい感じにしたい
- [x] 初回起動時に辞書の追加ができない #727 
  - なぜかui lockがかかっている
- [ ] エラーをもう少しわかりやすくする
  - なぜ辞書の登録に失敗したかなどをわかりやすくし、ユーザーに改善策を示す
- その他の実装等
  - 雑な実装で、用途がわかりにくい関数があったり、簡略化できるような場所があるので、保守性のためにそれらの改善をする

### Pros 良くなる点

保守性を高められる

### Cons 悪くなる点

- 時間がかかりそう
  - そもそも辞書UIを短時間で構築したための負債なので、仕方なさそう

**Comment by Hiroshiba** [comment]
上２つは早めにやっちゃっといたほうが良さそうなので、取り組んでみようと思います！

**Comment by y-chan** [comment]
滞っていてすみません、お願いします...!

**Comment by Hiroshiba** [comment]
こちら概ね完了したと思うので、閉じちゃっても大丈夫でしょうか 👀
どうしても気になる箇所があれば別issueに切り出して頂ければ！

**Comment by Hiroshiba** [comment]
こちら閉じちゃいますね！

> エラーをもう少しわかりやすくする

に関してもし気になるようでしたらissue作って頂ければ！！
（これはまあVOICEVOX EDITOR全体的な課題かもですね･･･）
