### ISSUE TITLE
辞書UIの初回起動で単語追加ができない

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#727]
## 不具合の内容

単語辞書機能で、なぜか初回起動時に追加ボタンもdisableになっていました。
ツイッターでも報告がありますが、二回目以降の再現方法がわからず、ちょっと苦戦しそうです。

### 現象・ログ

初回起動時にボタンを押せない

### 再現手順

不明

## その他

@y-chan さんもおっしゃっていましたが、UILockを使わず、辞書UI内でステートを管理すれば良いのかなと思いました。

関連

- https://github.com/VOICEVOX/voicevox/issues/724

**Comment by Hiroshiba** [comment]
0.11.3のバージョンアップで直るかなとも思ったのですが、まだ発生してるとのことでした。なんでだろう･･･？
https://twitter.com/PetitGuzzi/status/1498869034716381191

**Comment by madosuki** [comment]
https://gist.github.com/madosuki/a0f993f8ed7a2e8cd6af59da34cc7216

UI Lock周りの挙動を追うためにプリントデバッグ的なやつをしてみました。
first.txtが初回起動時のでsecond.txtが二回目以降起動時のログです。
二回目以降起動時ではstate.uiLockCountが負数になっているのでUI Lockが機能してないから単語追加できるという感じみたいです。

**Comment by Hiroshiba** [comment]
おおなるほど、バグっているから追加できないのではなく、バグっているから追加できるんですね･･･！
