### ISSUE TITLE
辞書UI中にスペースを押すと、メイン画面の方の音声が再生される

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#728]
## 不具合の内容

辞書UI中にスペースを押すと、メイン画面の方の音声が再生される不具合があります。

### 期待動作

何も起こらない、もしくは辞書UI側の音声が再生される

**Comment by jdkfx** [comment]
現在のバージョンでは、辞書UI中にスペースを押すと、機体動作のうちの何も起こらない状態になっています。

**Comment by Hiroshiba** [comment]
確かにです！！
クローズしたいと思います、ご報告感謝です！！
