### ISSUE TITLE
「ジャックポット」という読みの単語を登録できない

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#729]
## 不具合の内容

辞書登録する際、読みによってエラーが発生するという不具合報告を頂きました。

### 現象・ログ

「ジャックポット」が読みの単語を登録しようとするとエラー

## その他

「ジャッ」もだめで、「ジャァ」もだめなので、拗音とか「ッ」が連続するとエラー･･･？

**Comment by takana-v** [comment]
エンジン側の問題みたいです。

捨て仮名のリストに「ッ」が誤って入っているためかと思います。
https://github.com/VOICEVOX/voicevox_engine/blob/78c846eb73fb684ee77d613b4741fca21bee8e84/voicevox_engine/model.py#L183

「ジャァ」は日本語的に誤った読みなのではじいています。
