### ISSUE TITLE
単語一覧から単語の削除後、「単語の追加・変更を破棄しますか？」ダイアログが表示される

### ISSUE THREAD

**Issue by aoirint** [VOICEVOX/voicevox#731]
## 不具合の内容

読み方＆アクセント辞書の単語一覧から、「削除」をクリックして登録された単語を削除したあと、
「単語の追加・変更を破棄しますか？」の確認ダイアログが表示されます。

本来このダイアログは、単語の編集画面で、変更を加えた後に編集画面を閉じようとしたときに表示されるものです。

「続行」を選んでも、実際には削除は巻きもどらないので、ダイアログを表示しない方がよさそうです。

![image](https://user-images.githubusercontent.com/27213639/156010615-501a922b-75b6-4d67-9e0b-8cc9c69356bd.png)

### 再現手順

1. 読み方＆アクセント辞書を開く
2. 適当な単語を1つ登録する
3. 登録した単語を1つ削除する
4. 読み方＆アクセント辞書を閉じようとする（×ボタンをクリック）
5. 確認ダイアログが表示されてしまう

### 期待動作

確認ダイアログを表示しないで「読み方＆アクセント辞書」を閉じる

## VOICEVOXのバージョン

0.11.2

## OSの種類/ディストリ/バージョン

- Windows

**Comment by Hiroshiba** [comment]
issueありがとうございます！
辞書UIのステート管理がどこかおかしくなっていそうです。
閉じるときにも同じようなダイアログが出るという報告もいただきました
https://twitter.com/GSka01/status/1498541958821969924

**Comment by Hiroshiba** [comment]
こちらのissueはhotfixとしてリリースできればと考えています。
プルリクエストを作る際に`release-0.11`に向けて頂ければ･･･！

**Comment by Hiroshiba** [comment]
0.11.3で修正されます！ということでcloseします。
