### ISSUE TITLE
音声書き出し時に進捗がわかるような表示をする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#739]
## 内容

大量のテキストを入力して一気に書き出すと画面が固まってしまいます。
何番目を書き出し中なのか進捗がわかるような表示があると良さそうに感じました。

### Pros 良くなる点

安心できる

### 実現方法

３秒くらい待ったら　何分の何　と画面中央に出始める、とか。
（すぐ出てすぐ消えるのは画面がちらつくので、３秒くらい待ってから表示する）

## その他

ご要望の声 https://twitter.com/yataka_orbital/status/1499322333936627713

**Comment by Apple-Yuki** [comment]
## 内容

長めの音声データ（エディタで言うと複数行の会話）を一括出力するときに、画面がさわれなくなるだけではなく進捗バーが欲しい
こんなの。
![20170612143019](https://user-images.githubusercontent.com/91584669/158332404-c28029b6-e4bb-4760-83e7-a3e118af2712.gif)

 #### https://github.com/VOICEVOX/voicevox/issues/759 と同様な問題のため統合します。

> ## 内容
> 大量のテキストを入力して一気に書き出すと画面が固まってしまいます。 何番目を書き出し中なのか進捗がわかるような表示があると良さそうに感じました。
> 
> ### Pros 良くなる点
> 安心できる
> 
> ### Cons 悪くなる点
> ### 実現方法
> ３秒くらい待ったら　何分の何　と画面中央に出始める、とか。 （すぐ出てすぐ消えるのは画面がちらつくので、３秒くらい待ってから表示する）
> 
> ## その他
> ご要望の声 https://twitter.com/yataka_orbital/status/1499322333936627713

### Pros 良くなる点

出力進捗がわかるので固まったように見えなくはなる

### Cons 悪くなる点
ないと思うけど、システム見直しというかフラグ管理的なものが必要になりそう。


### 実現方法
VOICEVOXで使ってる言語がわからないので詳しくは分かりませんが出るように処理すればいいと思う（願望）
また @Hiroshiba さんが言っている処理が必要かも？
![images](https://user-images.githubusercontent.com/91584669/158332511-84cd9398-39ad-4745-bb70-106f6db9bfa3.png)

**Comment by Hiroshiba** [comment]
たしかに変更が必要な行数自体は少ないですね！！
ぜひよろしくお願いします…！

UI部分は既存コード読む必要があっていろいろ大変かもです。
難しそうであればProgres表示だけでも…！🙏（どちらでも大丈夫です！）

**Comment by k-chop** [comment]
UI側で実装できたので #1038 にPR出しました！

indeterminateな進捗表示は実はwindowsのみの対応だったようで、
macではただの100%表示になってしまいかなり違和感がありました。

なので結局OSプログレスバー表示は諦めてUI部分のみの実装になりました...
