### ISSUE TITLE
質問：３音のアクセント低・高・低　方法ありますか？

### ISSUE THREAD

**Issue by Apple-Yuki** [VOICEVOX/voicevox#753]
Twitterで見かけた質問の共有です。

## 質問の内容
３音のアクセント低・高・低　方法ありますか？

via https://twitter.com/nigaoejima/status/1502948358314668035
## その他
単語にアクセント低・高・低を登録する方法が見当たらないので改善でイシューでするべきなのか、あるのかわからなかったので共有の形で立てます。

## 関連
質問・改善：辞書に半角の単語が登録できない #752

**Comment by takana-v** [comment]
ちょっと「3音のアクセント」が分からないですが、語尾のアクセントを考慮するために挿入される「が」が誤解を招いているかもしれません。
この「が」は平板型と尾高型を区別するために必要なので削除は難しそうです。
（3音の単語、という意味だと、低・高・低のアクセントは表現できるはずですが...）

**Comment by Apple-Yuki** [comment]
@takana-v 要望をいただいた方に詳しく聞いたところ図解するとこういうことを言いたいそうです。

![FNvBxRRaQAMD-b0](https://user-images.githubusercontent.com/91584669/158063482-f6c66f2d-585c-40ee-a066-7006ce85a19a.jpeg)

**Comment by takana-v** [comment]
1音1音音の高さを変えれるようにするにはコア部分から変える必要があるかと思います。
（コア部分には詳しくないので、もしかしたら間違っているかもしれません...）
少なくともエンジン部分、エディタ部分両方に大きな変更が必要です。

VOICEVOXでは東京式アクセントの日本語文章から音声合成するように作られています。
東京式アクセントでは、1音目が「高」の場合は、アクセント句の終端まではずっと「低」でなければならない制約があります。
（東京式アクセントについてはこちらの記事が分かりやすいと思います）
https://www.nihongo-appliedlinguistics.net/wp/archives/4519

私の回答としては、
- 現状、アクセントを「低・高・低」のように調整することはできない
- 自由に高低を調節できるようにするには大きな変更が必要であり難しい
- 必要に応じ、イントネーション欄で音の高さを調整して欲しい

といった感じになるでしょうか。
（あくまでも1レビュワーの回答となりますが）

一旦closeしますので必要に応じて再度openしていただければと思います。

**Comment by Hiroshiba** [comment]
こちらに関して、質問されていた方にリプライして説明したところ、ご納得いただけた形です。
https://twitter.com/hiho_karuta/status/1503028139685183493
