### ISSUE TITLE
Windows 11 で Ver.0.11.4 が使用できないケースがある

### ISSUE THREAD

**Issue by PickledChair** [VOICEVOX/voicevox#761]
## 不具合の内容

[Twitter 上で見られた事例](https://twitter.com/arYccGGTiREfZiQ/status/1504267818098847750?s=20&t=xwvuChlFj9jnWxX3JlIQkA)のように、Windows 11 上で Ver.0.11.4 がエンジンの起動エラーにより使用できません。

### 現象・ログ

Ver.0.11.4 のインストール後、初回起動の時点で「音声合成エンジンエラー　音声合成エンジンが異常終了しました。エンジンを再起動してください。」のエラーダイアログが現れます。エンジンが起動しないので VOICEVOX を使用することができません。

#### 備考

同じ Windows 11 上でも Ver.0.11.3 であれば正常に VOICEVOX を使用することができました。

### 再現手順

Windows 11 上で VOICEVOX Ver.0.11.4 をインストールし、起動する

### 期待動作

Windows 11 上で VOICEVOX Ver.0.11.4 を使用することができる

## VOICEVOXのバージョン

0.11.4

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

Twitter の事例での詳細な情報は分かりませんが、ユーザーインターフェースのデザインを見るに Windows 11 と考えられます。
自分で再現した環境は macOS で Parallels Desktop 上で動作させている Windows 11 enterprise 評価版です。

## その他

エンジンの問題の気がするのでエディタのリポジトリに立てるべき Issue ではないかもしれないと思いましたが、Windows での開発に不慣れであまり原因を調査できていないので、とりあえずこのリポジトリに Issue を立てました。

**Comment by Hiroshiba** [comment]
issueありがとうございます！

0.11.4と0.11.3の違いはコアだけなはずで、0.11.3と同じようにビルドしたつもりなので思い当たる点がないですね･･･。
win11で必ずエラーになるならもうちょっとエラー報告が来てそうな気がするので、もしかしたら起動できることもあるのかも･･･？

**Comment by PickledChair** [comment]
> win11で必ずエラーになるならもうちょっとエラー報告が来てそうな気がするので、もしかしたら起動できることもあるのかも･･･？

もう一度 Ver.0.11.4 をインストールしてみたところ、正常起動し、使用できるようになりました！ 流れとしては、

- 最初に Ver.0.11.4 をインストールしたがエンジンの起動エラーで使用できなかった
- Ver.0.11.4 のアンインストール
- Ver.0.11.3 をインストールし、正常に使用できた
- Ver.0.11.3 をアンインストール
- Ver.0.11.4 をインストールすると、今度は正常に使用することができた

です。理由はわかりませんが、アンインストール＆再インストールでうまく行ったという形です。
一方で、詳細なエラーメッセージを確認できなくなってしまいました……。

**Comment by Hiroshiba** [comment]
追加の報告ありがとうございます！！

とても謎ですね････････。
１回目の方はなぜかdllがなかった、みたいな可能性がある･･･のかなぁ･･･

とりあえずissueは開いたままにしておき、追加の報告があれば待ちたいと思います！

**Comment by Apple-Yuki** [comment]
以下の機種のクリーンな環境でテストしてみました。

CPU問題あってはこまるのでCPUが違うSurface Book 4を2台用意しました。

- 第 11 世代 Intel® Core™ プロセッサ intel Core i7 /メモリ：16GB
- カスタム AMD Ryzen™ Microsoft Surface® エディション プロセッサ AMD Ryzen 7 /メモリ：16GB

1.新規でインストールしてみる
⇒問題なくインストールされ動きました。

2.Ver.0.11.3 をインストールし、Ver.0.11.4をインストール（Windowsの機能でリカバリー済）
⇒まったく問題なく動く。

3.[PickledChairさん](https://github.com/VOICEVOX/voicevox/issues/761#issuecomment-1070920329)のやり方で再インストール
⇒問題なし


予測：もしかしたら[Windows 11のセキュリティー](https://docs.microsoft.com/ja-jp/windows/whats-new/windows-11-overview#%E3%82%BB%E3%82%AD%E3%83%A5%E3%83%AA%E3%83%86%E3%82%A3%E3%81%A8%E3%82%B9%E3%82%AD%E3%83%A3%E3%83%B3)かNortonなどでおかしくなってそうな気もします。
ただ、アップグレードに失敗する人は、再インストールをしたほうがよさそうです。

**Comment by Hiroshiba** [comment]
ご報告ありがとうございます！！
とても参考になります。

２台を３通りずつの方法で試して問題なく動いた、ということですよね。
うーん･･･一時的な問題だったのかもですね･･･
謎ですが、いったんこの問題が再発された方を見かけるまで、issueをcloseしてみたいと思います。

ご協力いただき感謝です！！
