### ISSUE TITLE
横幅を広げないようにしつつ、splitの当たり判定を大きくする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#777]
## 内容

- https://github.com/VOICEVOX/voicevox/pull/772

こちらのプルリクエストで、splitの当たり判定が大きくなりました。（thx @nebocco ！）

ちょっと気づかなかったのですが、イントネーション欄のときに横幅が大きくなっていて、かつ二文字（ファとかニュとか）で表示が崩れることに気づきました。

↓アクセント欄
![image](https://user-images.githubusercontent.com/4987327/161436037-f66ece9a-6870-4cb6-84fd-e77a637faf75.png)

↓イントネーション欄
![image](https://user-images.githubusercontent.com/4987327/161436043-1156320f-3cc2-46a5-86bd-ac51d31055cc.png)

こちらの表示を崩れないようになんとかするissueです。

### Pros 良くなる点

アクセント欄とイントネーション欄で幅がおなじになるので調整がしやすくなる。

### Cons 悪くなる点

読み修正の見た目と当たり判定が不一致になるかも

### 実現方法

改行をなくすのはたしかcssがあった記憶があります。
横幅の方は、表示はしつつ横幅は小さいdivを作ればいいと思うのですが、できるのかは不明です･･･。

## その他

ちょっと不味めなので、次のアップデートまでに修正が難しそうであれば、[こちらのプルリク](https://github.com/VOICEVOX/voicevox/pull/772)をrevertしたいと思います。
レビューの際に気づかなくて申し訳ないです･･･。

**Comment by nebocco** [comment]
こちら手元でも表示を確認してみます。今の段階ではどの程度簡単に直せそうかイメージが湧いていないのですが、次回アップデートはいつ頃を予定されているのでしょうか？

**Comment by Hiroshiba** [comment]
おお、ありがとうございます！！
アプデタイミングは厳密に決めてないのですが、なんとなく今月末くらいかな〜と思っています。

**Comment by Hiroshiba** [comment]
そもそもイントネーション設定のときにアクセント句のsplitは要らないかも･･･？と少し思いました。
（こちらで頂いた意見を参考に考えました https://twitter.com/tiha48/status/1514814780099678209 ）
