### ISSUE TITLE
全テキスト欄の文章をキャラ名とともに一括してテキスト書き出す機能が欲しい

### ISSUE THREAD

**Issue by kantas-spike** [VOICEVOX/voicevox#786]
## 内容

全テキスト欄の文章をキャラ名とともに一括してテキスト書き出す機能を追加していただきたいです。

誤記や単語の発音調整のために、テキスト欄の単語を一括置換したいケースがあります。

VOICEVOXのエディタには一括置換機能がないですが、
全テキスト欄をエクスポートして、テキストエディタなどで一括置換後、
"テキスト読み込み"機能でインポートできれば解決できます。

現状では、一括してテキスト書き出す機能は、
"設定/オプション"で、"txtファイルを書き出し"を有効にして、"音声を繋げて書き出し"をする方法しかないと思います。
しかし、この方法は、必ず音声ファイルも出力されるため時間がかかりますし、
出力テキストファイルにはキャラ名が出力されない問題があります。

そのため、ファイルメニューに、"テキストを繋げて書き出し"項目を追加し、
クリックすると、全テキスト欄の文章をキャラ名とともに一括してテキスト書き出す機能が欲しいです。

### Pros 良くなる点
全テキスト欄の一括置換をエクスポート、インポートを利用して実現できます。

この機能があれば、1〜3の工程くり変えして、ナレーション原稿を作成できます。

1.  テキストエディタで原稿を編集
2. インポートしてVOICEVOXで確認
3. 修正用にエクスポート

### Cons 悪くなる点
ないと思います。

### 実現方法
vueで開発したことがないため見様見真似で機能を以下に追加してみました。
一応、動いていますが、作法やコードの共通化などは考慮できていません。

https://github.com/kantas-spike/voicevox/tree/feature-export-textfile-with-character-name

## VOICEVOXのバージョン

0.11.4

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [x] macOS
- [ ] Linux

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！

コード読ませていただきました！ぜひプルリクエストを頂けますと幸いです！！

**Comment by nebocco** [comment]
横からすみません、読み込ませた原稿を修正して再度読み込ませるのではなく、一度エクスポートさせることにはどのようなメリットがあるのでしょうか？
長文原稿を読ませたことがないので今後のために感覚を教えてもらえると嬉しいです。

**Comment by Hiroshiba** [comment]
issue内容に書かれているように、テキストの一斉置換やキャラクターの一斉変換など、痒い所に手が届く様になりやすいのかなと感じました！

**Comment by kantas-spike** [comment]
@nebocco さん、質問ありがとうございます。

私はまだ機能を全部使いこなせていません。
それもあり、少数派だとは思いますが、イントネーションは味・個性と考えて、
VOICEVOXでアクセント等の調整をほとんどせずに音声出力させてもらっています。

あとは、辞書では対応の難しい文脈によって読み方の変わる単語(「値(あたい)」とか)などを、VOICEVOXで再生して確認し、ひらがなに修正しています。(エクスポートできるとテキストエディタで一括置換できます。)
そのため、VOICEVOXとテキストエディタを行き来するので、どちらで文章を書いても、インポート/エクスポートできると助かります。

これはVOICEVOXで100行以上文章を書いてしまって、あとで再生したときに「値(あたい)」を「ね」と読まれて泣きながら手修正する人が助かる機能です。お時間があるとき対応していただけるとありがたいです。

**Comment by nebocco** [comment]
なるほど！最初にテキスト原稿を書くのではなく、VOICEVOXに直接書き込んだ場合に有用なんですね
参考になります、ありがとうございます

**Comment by kantas-spike** [comment]
#787 を取り込んでいただきました。
皆様ご対応ありがとうございました。
