### ISSUE TITLE
単語登録時に優先度を設定可能にする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#790]
## 内容

辞書登録する際に優先度を指定できるようになりました（ thx @takana-v ! ）

- https://github.com/VOICEVOX/voicevox_engine/pull/359

このissueの目的は、辞書登録時に優先度を指定できるようなUIを作ることです。
ユーザー側で頻度調整ができてとても便利だと思います。

### Pros 良くなる点

現れる頻度調整ができる

### Cons 悪くなる点

UIの実装が必要

### 実現方法

４段階くらいの優先度（最高・高・並・低）を用意して、辞書登録APIのpriorityに10, 7, 5, 3辺りを指定すれば良さそう？

## その他

現状だと必ず現れるわけではないので、「辞書登録ができない」という捉えられ方をしがちです。
例： https://twitter.com/hairanndo/status/1516239134792503296

とりあえず優先度最大で登録しちゃうのも良いかも。

**Comment by Hiroshiba** [comment]
UI部分はこちら
https://github.com/VOICEVOX/voicevox/blob/main/src/components/DictionaryManageDialog.vue

辞書APIを叩く部分はこちら
https://github.com/VOICEVOX/voicevox/blob/e0f8d208053ba3b86fcc05278fbf0e99f7134d12/src/store/dictionary.ts

辞書APIのドキュメントはこちら
https://voicevox.github.io/voicevox_engine/api/#operation/add_user_dict_word_user_dict_word_post

**Comment by y-chan** [comment]
こちら、実装してみたいと思います。

**Comment by Hiroshiba** [comment]
おお！！ぜひよろしくお願いします…！！
