### ISSUE TITLE
コマンドラインからでもVOICEVOXを操作したい

### ISSUE THREAD

**Issue by AlphaIru** [VOICEVOX/voicevox#804]
## 内容

Open-JTalkみたいに、コマンドラインからでも読み上げ、WAV生成の機能を足して頂きたいです（特にLinux系で）。
できるならそのコマンドラインからTXTの入力もできたらありがたいです。
例えば：
VoiceVox -m Zundamon-normal -i input.txt -o tests.wav

### Pros 良くなる点

サーバーからでも色々と変換の動作ができるようになる。

### Cons 悪くなる点

無いと思います。あるとしたら悪用系なので…

### 実現方法

起動時にエンジンの起動->そこから入力とやれば大丈夫かと。

## VOICEVOXのバージョン

0.11.4

## OSの種類/ディストリ/バージョン

- [x] Windows
- [x] macOS
- [x] Linux

**Comment by AlphaIru** [comment]
なるほどです！頑張ってみます！

**Comment by AlphaIru** [comment]
ん、それってUbuntu Server みたいなコマンドオンリーのCUIの環境でも行けますでしょうか?

**Comment by Hiroshiba** [comment]
はい。
ちょっと質問内容がOSSとしてのVOICEVOXから離れていそうです。
VOICEVOXのユーザー向けdiscordサーバーなどでお聴きください。
