### ISSUE TITLE
キャラクター初期化中に真ん中にインジケータを表示する

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#821]
## 内容

キャラクター変更時に音声合成の初期化が走るようになりましたが、初期化中であるということがわかりにくくなっています。
初期化中はloadingインジケーターを真ん中に表示すると、ユーザーにとってわかりやすそうです。

### Pros 良くなる点

ユーザーにとってわかりやすそう

### 実現方法

エンジン起動中に真ん中にインジケータを表示する機能があるので、そのあたりのコードが参考になるかも。

## その他

関連issue

- https://github.com/VOICEVOX/voicevox/issues/813

**Comment by sigprogramming** [comment]
こちら取り組みます！

**Comment by Hiroshiba** [comment]
ありがとうございます！わからないことなどがあればお聞きください！

**Comment by Hiroshiba** [comment]
- https://github.com/VOICEVOX/voicevox/pull/888

により解決したのでcloseします。 @sigprogramming さんありがとうございました！！
