### ISSUE TITLE
OSError: [WinError 1]　書き込み権限が無いと起動しない

### ISSUE THREAD

**Issue by arigayas** [VOICEVOX/voicevox#824]
## 不具合の内容

自分の環境で起動しないとツイートしました。
https://twitter.com/arigayas/status/1531456337825402880

zip版を展開してvoicevox.exe をダブルクリックで起動しても「音声合成エンジンエラー」というダイアログが表示された後は「データ準備中」のままになってしまい使用できません。
![image](https://user-images.githubusercontent.com/11251874/171084185-90df62fb-7547-4584-8252-6b5c5eeef954.png)
![image](https://user-images.githubusercontent.com/11251874/171084200-8987e3a8-55dd-42ba-a83f-4f51fa1e7f40.png)

### 現象・ログ
エラーログです。
[20220531_104942_error.log](https://github.com/VOICEVOX/voicevox/files/8801653/20220531_104942_error.log)

エラーログのエラーメッセージが文字化けしているとヒホ（ヒロシバ）さんにTwitterにて伝えたらリプライで コマンドプロンプトにてrun.exe を実行したスクリーンショットです。
OSError: [WinError 1] ファンクションが間違っています。: '.'　と表示されていました。
![image](https://user-images.githubusercontent.com/11251874/171084170-dfc1f5c2-2976-4d1a-8d52-809da9597cb4.png)

### 再現手順

1. RAMディスク作成ツールは ImDisk Virtual Disk Driver　を使用しました。
![image](https://user-images.githubusercontent.com/11251874/171088411-dfdae75c-d832-4e19-b441-7cd20bc687a4.png)

2. Rドライブ(RAMディスクで4GB確保している) にvoicevox-windows-cpu-0.12.0 をダウンロードします。
3. voicevox-windows-cpu-0.12.0 を展開します。
4. R:\voicevox-windows-cpu-0.12.0\VOICEVOX 内の voicevox.exe をダブルクリックで起動します。

### 期待動作

問題無く起動して初回起動時の画面（キャラクター選択画面）が表示される。

## VOICEVOXのバージョン

0.12.0 Pre-release

## OSの種類/使用ソフトなど
*   Windows 10 Pro 64bit 21H2 (10.0.10586)
*   Ryzen 5 3600 + Radeon RX 6600 + 64GB
*   7-zip 21.07(x64)
*   ImDisk Virtual Disk Driver　

## その他

RドライブにダウンロードしたzipをCドライブに展開したら問題無く起動しました。

Rドライブに展開したVOICEVOX 内のフォルダやファイルたちのプロパティのセキュリティタブのアクセス許可を見ると
「フルコントロール」、「変更」、「読み取りと実行」、「読み取り」、「書き込み」、「特殊なアクセス許可」と並んでいて
Usersには読み取りと実行、読み取りの2つだけにチェックマークが入っていました。
これが原因かと思いRドライブ自体に フルコントロールにチェックマークを入れる作業をして
そこにダウンロードしたzipを別フォルダ名で展開しVOICEVOX の起動を試みても起動しませんでした。

issueタイトルに行き着いたのは最後の部分のファイルのプロパティを見比べてアレ？と思ったからです。
それでもRドライブでの起動ができなかったのは腑に落ちないですが。

**Comment by Hiroshiba** [comment]
engine側に移動したということで、こちらのissueは一旦closeとさせていただきます！
