### ISSUE TITLE
DirectML版GPUモードにおいて前回の文章が再生される

### ISSUE THREAD

**Issue by musicsoul0142** [VOICEVOX/voicevox#828]
## 不具合の内容

GPUモードで前回の入力テキストを読み上げる

### 現象・ログ

入力されている文章ではなく前回の文章が再生される
ログはエンジン起動関連ログのみ

### 再現手順

1.任意のキャラで文章Aを記述し再生する
2.（音声は再生されない）
3.文章を削除し文章Bを記述し再生する
4.文章Aが再生される
以降文章を書き換えても一つ前のものが再生される

時折再現せずに正しく再生される

キャラを切り替えたうえでテキストを書き換えても同様の症状が発生することがある（100％再現ならず）
文章を変更せずに再度再生すると文章が正しく再生されるが、これは「ひとつ前」と「現在」の文章が同一であるためそう見えるだけだと思われます

連続再生は正しく動作する
CPUモードでは再現しない

検証結果の動画はこちらになります（限定公開です）
https://youtu.be/-QjsTYRAeUM

### 期待動作

現在テキストボックスに入力されてる文章を正しく読み上げる

## VOICEVOXのバージョン

0.12.1-DirectML

## OSの種類/ディストリ/バージョン

Windows 10 Home 21H1 (OS ビルド 19043.1706)
## ハードウェア情報
CPU:AMD Ryzen 5 2400G with Radeon Vega Graphics
RAM:16GB
GPU:Radeon RX 570 4GB ドライババージョン 30.0.15021.7000
使用されているGPUはRX 570であることをタスクマネージャーで確認済み

## その他

https://github.com/VOICEVOX/voicevox/issues/762 と類似してるかもしれないです

**Comment by musicsoul0142** [comment]
追記:汎用合成音声エディタ[ユニコエ](https://sites.google.com/view/unicoe/%E3%83%9B%E3%83%BC%E3%83%A0?authuser=0)に[VOICEVOXプラグイン](https://drive.google.com/drive/folders/1jxSemFB0vLYh8SSAxHpNzB87ROOECkPH?usp=sharing)を導入してAPI経由で音声合成を実行した際には再現しないです 
GPUも正しく使用されているのを確認しました

**Comment by musicsoul0142** [comment]
> おそらくになってしまうのですが、文章入力後、クリック（blur）して即再生した場合に起こる問題かもしれません。
文章確定後数秒待ってから再生した場合、問題なく再生されることを確認しました。
タイムラグが原因で間違いなさそうですね。
しばらくは運用で回避する形になりそうですね。
Openのまま、了解しました、ありがとうございます。

**Comment by musicsoul0142** [comment]
DirectML版0.12.2において再度検証したところ、今回の問題が発生しなくなってることを確認しました。

**Comment by Hiroshiba** [comment]
検証ありがとうございます！
ではいったんこちらのissueは閉じさせていただきたいと思います！
