### ISSUE TITLE
辞書の変更のリセットボタンが機能していない

### ISSUE THREAD

**Issue by y-chan** [VOICEVOX/voicevox#832]
## 不具合の内容

題の通り
単純に実装ミスなようです。

### 再現手順

読み方＆アクセント辞書機能で、単語のアクセントを編集し、リセットボタンを押し、確認ダイアログにおいてOKを押す

### 期待動作

リセットボタンを押し、確認も終われば単語情報がリセットされる

## VOICEVOXのバージョン

0.11 以上

## OSの種類/ディストリ/バージョン

- [x] Windows
- [x] macOS
- [x] Linux

## その他

ステート管理にしたことで、逆にややこしさを生んで、このようなミスを引き起こしてしまったような気がします....
私は元に戻したいと考えているのですが、どうでしょうか...

**Comment by Hiroshiba** [comment]
issueありがとうございます！

リセットがバグってることに関して、エゴサしてて報告がひとつもなかったので、もしかしたら実際のユースケース考えるとなくていいのかも？と思いました。
リセットが欲しくなるケースは、すでに登録済みで、かつ試行錯誤が必要で、かつ最初に戻った方が良いときですが、もしかしたらかなりレアかもです。

実装に関して調べてみました。今のにした経緯はこちらのPRっぽいです

- https://github.com/VOICEVOX/voicevox/pull/736

以前は「全ての状態から全ての状態に移動でき、かつ全ての変数を書き換えられる」という感じでした。
今は「全ての状態から全ての状態に移動でき、状態のみが変数を書き換えられる」感じになってそうです。

たぶん後者のが制約が強いので、今のがまだマシだと思います。
ただ、今のでも微妙に感じるのは同感です。

たぶん、全状態から全状態に移動できるのがよくないはずです。
reset関数がグローバルになってて全状態から呼べるから、何が起こってほしいのか・いつ呼ばれるのかパッとわからず、実装時にバグに気づけないのかなと思いました。
（ボイボのメインUIはほとんど状態がなく、かつ要素が独立してるのでまだ簡単だった）

ステートパターンだと、状態ごとにクラスを作って、遷移をメソッドにするみたいな方法がありそうです。
が、そこまでやるかと言うと、うーんという感じです！

**Comment by jdkfx** [comment]
こちらのissue、現在のバージョンだと機体動作の通りに動いているように見えます。

**Comment by Hiroshiba** [comment]
コメントありがとうございます！
確かに直っていそうです！（どこで直ったんだろう）

クローズします！
