### ISSUE TITLE
[GPU/DirectML版] Radeonを搭載したパソコンでCPUモードに切り替えた後にGPUモードへ切り替えると「対応GPUが見つかりません」と表示される

### ISSUE THREAD

**Issue by arigayas** [VOICEVOX/voicevox#833]
## 不具合の内容

Radeon を搭載したパソコンに GPU/DirectML 版をインストールしてCPUモードに切り替えた後にGPUモードへ切り替えると「対応GPUデバイスが見つかりません」とダイアログが表示されます。

ダイアログが表示されますがGPUに切り替えても普通に動作するので致命的なバグではありません。

### 再現手順

1. Radeon を搭載したパソコンに ZIP版の GPU/DirectML 版をダウンロードして展開します。
2. VOICEVOX.exe を起動して初期設定を一通りやります。
3. 「設定→オプション」をクリックします。
4. 「エンジンモード」が「GPU」になっている事を確認して「CPU」をクリックします。
5. 「起動モード」が変更されます。
6. 「エンジンモード」が「CPU」になっている事を確認して「GPU」をクリックします。
7. 「対応GPUデバイスが見つかりません」と確認ダイアログが表示されます。
![image](https://user-images.githubusercontent.com/11251874/172784063-c70efff2-ec5a-4d84-a8fd-10e1e6c39370.png)

### 期待動作

CPUモードに切り替えた後にGPUモードへ切り替えると「対応GPUデバイスが見つかりません」のダイアログが表示さない。

## VOICEVOXのバージョン

0.12.2

## 使用パソコンのスペック

- Windows Pro 64bit [21H2 / OSビルド：19044.1706]
- Ryzen 5 3600
- Radeon RX 6600 Challenger D 8GB
- 64GB Memory

## その他
関係ありそうなissue
#479

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！

将来的には、CUDA版（今のGPU版）を失くしてDirectML版に統一したいと考えています。
実は一度こちらでDirectML用の文言にしたのですが、

- https://github.com/VOICEVOX/voicevox/pull/819

不具合が発生したこともあってrevertしました。

- https://github.com/VOICEVOX/voicevox/pull/825

DirectML版の不具合はおそらく解消しているので、

- https://github.com/VOICEVOX/voicevox/issues/827

次回アップデートの際にまた #819 の変更を加えてリリースしたいと思っています。

**Comment by arigayas** [comment]
ニコ生で報告してから頭に残っていたのでissue報告しました。
次回リリース時に解決するなら、うれしいです。

**Comment by Hiroshiba** [comment]
DirectML版がデフォルトになったのでもうこのエラーは表示されなさそうです！
ということでcloseします！

**Comment by arigayas** [comment]
当方の環境でも確認ダイアログが表示されなくなったことを確認しました！
