### ISSUE TITLE
最大化状態で起動すると、ウィンドウの最大化ボタンのアイコンがかわらない

### ISSUE THREAD

**Issue by sevenc-nanashi** [VOICEVOX/voicevox#851]
## 不具合の内容

最大化した状態で起動すると、右上の最大化アイコンが変わらない。

### 現象・ログ

![image](https://user-images.githubusercontent.com/59691627/177150886-95ac5e88-f1e7-48b7-89dc-075f66473e61.png)

### 再現手順

1. Windowsで最大化する
2. Voicevoxを閉じる
3. Voicevoxを起動する

### 期待動作

アイコンが最小化のアイコンになる

## VOICEVOXのバージョン

0.12.3

## OSの種類/ディストリ/バージョン

- [x] Windows 10 Pro 64bit 21H2 (19044.1766)
- [ ] macOS
- [ ] Linux

## その他

https://twitter.com/sabonerune/status/1543916086323662850

**Comment by Hiroshiba** [comment]
再現手順も含めた丁寧なIssue作成、ありがとうございます！！！

**Comment by k-chop** [comment]
報告ありがとうございます 🙏 自分の実装したところですね...

https://github.com/VOICEVOX/voicevox/pull/782/commits/62181d9661fbac5e4442fdee317764d37b515fb9 でその問題自体には対応したつもりで、
自分の環境だと `npm run electron:serve` で起動したときは
最大化起動時に最小化アイコンに変わっていることを、現状のmainブランチ＋当時のコミットで確認しました。
が、0.12.3本番ビルドだと確かにそうならない様子・・・

本番ビルドではvuex初期化前に `DETECT_MAXIMIZED` が投げられ虚空に消えていそうな雰囲気を感じます。
最大化状態がvuex storeに同期されていないことが問題なので、

* `mainWindowState.manage(win)` をvuexの初期化が終わってそうなタイミングで呼ばれる適当なコールバックに乗せる
* windowの最大化状態を問い合わせるIPCメッセージを作ってINIT_VUEXで呼び同期する

上記どちらかで対応できそうな気がします。手持ちが片付いたら対応しようと思いますが、もしその間に対応してくださる方がいれば大歓迎です 🙇

**Comment by Hiroshiba** [comment]
コメントありがとうございます！！とても参考になります！！
