### ISSUE TITLE
使い方のスクショ画像を入れ替える

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#853]
## 内容

使い方のスクショが一部古いままになっており、ちょっとわかりにくくなってしまっています。
スクショを入れ替えるのがこのissueの目的です。

### Pros 良くなる点

わかりやすくなる。

**Comment by yuriko0505** [comment]
この問題に取り組みます

**Comment by Hiroshiba** [comment]
@yuriko0505 ぜひぜひ！！！

**Comment by Jun-1Il** [comment]
yuriko0505と共同で取り組んでいます。
pushをしようとすると403が返るのですが、これは権限エラーでしょうか？

**Comment by sevenc-nanashi** [comment]
> pushをしようとすると403が返るのですが、これは権限エラーでしょうか？

voicevox/voicevoxへのpushなら：Pull Request経由でコード変更を行ってくださいー。（探せば資料はあるはずです）
Jun-1Il/voicevoxへyuriko0505さんからのpushなら：Jun-1Il/voicevoxの設定からCollaboratorを足せば行けると思います（要検証）。これも資料は探せばあるはず．

**Comment by Hiroshiba** [comment]
@yuriko0505 さんのおかげでこちらの課題は解決したと思われます！
ありがとうございました！！

また数年経てば結構変わる可能性もあるので、その時またissueを作ろうかなと思います！
