### ISSUE TITLE
現在アクティヴな文節が着色されない

### ISSUE THREAD

**Issue by Aspena2022** [VOICEVOX/voicevox#858]
## 内容

再生時に現在どの文節を読んでいるか知りたいのですが。
また、途中から再生したいときに特定の文節を選択するときもあります。

その際に問題なのは、現在アクティヴな文節が着色されないので、位置がよくわからないのです。
調べてみると、着色しないというよりも、白く塗っていました。

src\components\AudioDetail.vue の
mora-table-hover:hover の
background-color: colors.$active-point-focus-hover;
と
mora-table-focus の
background-color: colors.$active-point-focus !important;

ここで定義されている背景色は実質、真っ白な#FFFFFFですよね。
文節のマウスオーバー時と選択時で、白く塗っていますね。
試しにhoverのbackground-colorをコメントアウトして、focusのほうは
background-color: #CCFFCC と薄い緑にすると、うまくいきました。

着色したほうが自然だと思いますがいかがでしょうか？ それとも真っ白に固定しておきたい理由があるのでしょうか。

### Pros 良くなる点

どこが現在アクティヴなのかが明確になります。

### Cons 悪くなる点

文節を区切るSplitterの色が見えにくくなるかも。(自分は濃い青に直しました)

## VOICEVOXのバージョン

0.12.3

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

Windows 10 64bit

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！

あれ、再生中もアクティブ（選択）中もこうやって青色が着色されているはず･･･？
![image](https://user-images.githubusercontent.com/4987327/178891527-72bcfb84-aec2-4621-b65e-49fd4e82a47d.png)

**Comment by Aspena2022** [comment]
調べるとたしかに着色されていました。私の環境では薄くて白っぽく見えてしまったようで、勘違いでした。

色の詳細を知りたくて、ソース内を検索すると
\src\styles\colors.scss 
$active-point-focus-hover: var(--color-active-point-focus-hover);

こんな風になっていて、--color- ... の実体が掴めなかったです。
画面キャプチャして色を確かめると RGB(238,243,255) なので、16進数では #EEF3FF ですね。これではちょっと薄いので、私の環境では濃く定義し直しています。問題解決ということでCloseしたいです。

**Comment by Hiroshiba** [comment]
なるほどです！！

カラーコードで検索した感じ、こちらに定義されていそうでした。
https://github.com/VOICEVOX/voicevox/blob/91074545242423db3404161da4a38d85aa38fb36/public/themes/default.json#L1-L21

> これではちょっと薄いので、私の環境では濃く定義し直しています。

確かに環境によっては画面の関係で薄く見えるかもと感じました。

そういえば、カラーテーマを編集できる仕組みがVOICEVOXにもほしいなと思ったので、issueを作成してみました。
もしご興味あれば･･･！！

- https://github.com/VOICEVOX/voicevox/issues/865
