### ISSUE TITLE
冥鳴ひまりが低い声で「も」や「の」をうまく言えないときがある

### ISSUE THREAD

**Issue by Aspena2022** [VOICEVOX/voicevox#859]
## 内容

ひまりに「誰も彼もが、あれも、これも。でも。」をしゃべらせてみると、あれもが「あれを」になることがあります。でもは「でお」になってしまいます。
句読点の直前の「も」のイントネーション高さを5.30程度に下げるとその傾向が出てきます。

同様に、「そうなの。」の「の」を5.40以下にすると、やはり「お」っぽくなります。5.70だといいのですが。
句読点が影響して母音が発音しにくくなるのでしょうか？

### Pros 良くなる点

発音がよくなるといいですね。

### Cons 悪くなる点

たぶん、ないです。

## VOICEVOXのバージョン

0.12.3、0.11.4

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

Windows 10 64bit

## その他

めたんやつむぎは問題なさそうでした。ひまりのボイスデータに特徴的な問題だと思います。

**Comment by Hiroshiba** [comment]
音声ライブラリによって向き不向きがあるのは仕様になります。
