### ISSUE TITLE
【開発環境】 package-lock.jsonのlockVersionとenginesで指定しているnpmが使用するlockVersionがあべこべであるためにnpm ciで問題が生じている

### ISSUE THREAD

**Issue by yamachu** [VOICEVOX/voicevox#867]
## 不具合の内容

- .node-version に指定されているNodeは14.17.4で、defaultではnpm 6.14.14が入る
- package-lock.json のlockfileVersionが2
  - lockfileVersionが2になったのはnpm 7(Node 15 ~ Node 16.10.x)やnpm 8(Node 16.11.x ~)から
- package.json の engines を無視してnpm 7 or 8でnpm ciするとpackage-lock.jsonに入ってないパッケージが見つかる
  - 厳密にpackageのlockが行われていなそう
- CIはsetup-nodeでNodeのバージョンは固定しているが、npmのバージョンはアップデートしていないので厳密にlockが行われていないものでnode_modulesを展開している
  -   https://github.com/VOICEVOX/voicevox/blob/7e27b08654d2a7dba39c3bc8774b6b14d5de491f/.github/workflows/build.yml#L145

### 現象・ログ

<details>
    <summary><code>npm ci</code>した時のログ抜粋</summary>
<pre>
<code>
npm ERR! code EUSAGE
npm ERR! 
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! Invalid: lock file's electron@16.0.6 does not satisfy electron@19.0.6
npm ERR! Invalid: lock file's @electron/get@1.13.1 does not satisfy @electron/get@1.14.1
npm ERR! Invalid: lock file's @types/node@15.3.0 does not satisfy @types/node@16.11.45
npm ERR! Invalid: lock file's boolean@3.1.4 does not satisfy boolean@3.2.0
npm ERR! Invalid: lock file's postcss@7.0.35 does not satisfy postcss@8.4.14
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Invalid: lock file's nanoid@3.1.23 does not satisfy nanoid@3.3.4
npm ERR! Missing: picocolors@1.0.0 from lock file
npm ERR! Missing: source-map-js@1.0.2 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Invalid: lock file's globalthis@1.0.2 does not satisfy globalthis@1.0.3
npm ERR! Missing: postcss@7.0.39 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: picocolors@0.2.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! 
npm ERR! Clean install a project
npm ERR! 
npm ERR! Usage:
npm ERR! npm ci
npm ERR! 
npm ERR! Options:
npm ERR! [--no-audit] [--foreground-scripts] [--ignore-scripts]
npm ERR! [--script-shell <script-shell>]
npm ERR! 
npm ERR! aliases: clean-install, ic, install-clean, isntall-clean
npm ERR! 
npm ERR! Run "npm help ci" for more info
</code>
</pre>
</details>

### 再現手順

1. `package.json` の `engines` フィールドを消す
2. `lockVersion` に合わせて npm 7 or 8を使い `npm ci` を走らせる

### 期待動作

1. lockVersionが1のpackage-lock.jsonが使用される
2. npm 8を使用するように環境を強制し、package-lock.jsonファイルを正常に保つ

このいずれか

## VOICEVOXのバージョン

0.?.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

## その他

ref: https://github.com/VOICEVOX/voicevox/issues/464
ref: https://github.com/VOICEVOX/voicevox/issues/37

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！！！

> npm 6.14.14で npm i したものをマージする方向で進めるのはどうか

一旦こちらをするのが整理できて良いのかなと思いました！
