### ISSUE TITLE
CIにE2Eテストを追加する

### ISSUE THREAD

**Issue by so-c** [VOICEVOX/voicevox#869]
## 内容

#863 で導入したPlaywrightによるE2EテストをCI（GitHub Actions）でも動くようにする

### Pros 良くなる点

用意したテストの範囲でmainブランチへのエンバグを予防できる

### Cons 悪くなる点

テストがFlakyだと開発の妨げになるリスクがある

### 実現方法

[Continuous Integration | Playwright](https://playwright.dev/docs/ci#github-actions), [ヘッドレスCIシステムでのテスト (Travis CI, Jenkins) | Electron](https://www.electronjs.org/ja/docs/latest/tutorial/testing-on-headless-ci)を参考にGitHub Actionsに追加する

テストでのVOICEVOX_ENGINE, 音声ライブラリの扱いが難しそう。特に後者

## その他

このIssueでは仕組みの実現にしぼって、どんなE2Eテストを用意するかは別に考えた方がよさそう。 #182 も参照

**Comment by so-c** [comment]
so-c#19 で取り組み始めのご連絡。

**Comment by so-c** [comment]
CIで製品版のエンジンは使えないはずなので、`voicevox_engine`のモック `python run.py --enable_mock`をCIで立ち上げようとしています。しかし、現在の実装は、外からこの形に持っていけず `background.ts`の書き換えが必要です。

- `.env`で`"executionFilePath": "/Path/To/python.exe"`
- `background.ts` のengineProcessをspawnさせるところ。渡したい引数をハードコーディングすると
```typescript
  const engineProcess = spawn(enginePath, ["run.py", "--enable_mock"], {
    cwd: path.dirname(
      "/Path/to/voicevox_engine/run.py"
    ),
  });
```

直し方はまだ考えていないのですが、手を入れると #429 #609 に影響しそうなのでご相談。なおモックengineを起動するには
- enginPathとcwdが同じdirectoryにある前提を置いている
- argsが `const args = useGpu ? ["--use_gpu"] : [];` の2択
この2点を変える必要がありそうです。469行目～です

https://github.com/VOICEVOX/voicevox/blob/b35ddc8a248b71459046ed72a499314b9a0396d6/src/background.ts#L469

あるいはCIではexeを使う手もありそうですが、そうするとコアをどうするか問題に戻ってしまいます。

**Comment by Hiroshiba** [comment]
python経由で実行する場合に必要な箇所の洗い出し、ありがとうございます！
そちらの2箇所の変更、たしかに必要だと感じました。

まあでも、CIでexeを取ってきてしまっても良いのかなと思いました！！
どちらでも…！

**Comment by Hiroshiba** [comment]
VOICEVOXエディタ側に仕様変更が入ってテストしやすくなりました！！

`.env`で`executionEnabled: false`とすると、`run.exe`を起動しようとせずに始まります。
これを使えば`python run.py --enable_mock`で起動したモックエンジンを使えると思います！

**Comment by Hiroshiba** [comment]
* 設定などが保存されるuserDataDirは毎回空の方が良さそう
	* キャッシュは残してもいいけどconfig.jsonやvvpp-enginesは消したい
	* テスト時にtearDownで消す
	* あるいは環境変数などを用いてuserDataDirを外部から刺せるようにする

**Comment by Hiroshiba** [comment]
- https://github.com/VOICEVOX/voicevox/pull/1345

がマージされました 🎉 
e2eテストが書きやすくなったはず？

**Comment by Hiroshiba** [comment]
- https://github.com/VOICEVOX/voicevox/pull/1276

で解決されていたのでcloseします！
