### ISSUE TITLE
「最近開いたプロジェクト」メニュー

### ISSUE THREAD

**Issue by sevenc-nanashi** [VOICEVOX/voicevox#878]
## 内容

「ファイル」下に「最近開いたプロジェクト」のようなものがあると便利だと思いました。
![image](https://user-images.githubusercontent.com/59691627/182048570-0fe91d97-d8de-426c-80aa-41a7cbc0d5c4.png)

### Pros 良くなる点

編集が続けやすくなる

### Cons 悪くなる点

なし？

## VOICEVOXのバージョン

0.12.5

## OSの種類/ディストリ/バージョン

- [x] Windows 10 Pro 21H2, (19044.1766)
- [ ] macOS
- [ ] Linux

**Comment by Hiroshiba** [comment]
良い機能ですね！！！
あまり発想として出にくい機能だけど、結構需要がありそうだなと感じたので優先度を中にしてみました。
