### ISSUE TITLE
初回起動時のデフォルトスタイルID選択のとき、「ノーマル」を最初から選ばれている状態にする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#885]
## 内容

デフォルトスタイルを選択可能ですが、初回起動時にも出てきて、「必ずどれかのスタイルをクリックしないといけない」仕様になっています。
これは、キャラクターの声を必ず聞いてほしいという願いからでした。

キャラクターの声はかなり有名になり、数も増えてきたため、飛ばしたい人は飛ばせるようなUIに変更したいと思います。
なので、デフォルトスタイル選択時、最初からノーマルが選ばれているような実装に変更したいです。

### Pros 良くなる点

興味がない人は飛ばせるようになる

### Cons 悪くなる点

キャラクターの声が聞かれなくなる

## その他

スタイルがあるキャラクターだけが優遇されている状態なので、フラットにしたいという意図もあります。

**Comment by Hiroshiba** [comment]
こちら取り組みます！

**Comment by Hiroshiba** [comment]
@shirowanisan 
すみません、こちらのissueに関して、仕様変更がコエイロインクにも影響あることなのでちょっと相談させてください 🙏 

デフォルトスタイル選択に関して、複数スタイルあるキャラクターは最初にデフォルトスタイルを強制的に選んでもらうようなUIにしていました。
これを強制せず、最初から０番目のスタイルをデフォルトにする設計にしたいのですが、問題ありそうでしょうか･･･？ 👀

（そもそもなぜそんな仕様になっていたのかは、このissueの説明欄に書いています！）

**Comment by shirowanisan** [comment]
@Hiroshiba 

> これを強制せず、最初から０番目のスタイルをデフォルトにする設計にしたいのですが、問題ありそうでしょうか･･･？

COEIROINKとしては特に問題ありません。今後も基本的にVOICEVOXの方針を正として、COEIROINKはそれに合わせる形で大丈夫です！ご確認くださりありがとうございます！

**Comment by Hiroshiba** [comment]
ご返答ありがとうございます！！承知しました！

**Comment by Hiroshiba** [comment]
こちらのタスクですが、release 0.13に間に合わなそうなので、セルフアサイン外します。
