### ISSUE TITLE
キャラ選択メニューの一番上に現在のキャラを表示するようにする

### ISSUE THREAD

**Issue by sevenc-nanashi** [VOICEVOX/voicevox#897]
## 内容

画面が小さい場合、このように現在選択中のキャラが画面外に行ってしまい、スタイルを変えるときにスクロールする必要が出てきます。
![image](https://user-images.githubusercontent.com/59691627/184521881-753f3178-b156-46ba-b7c0-26d86b961a1f.png)

なので、このように現在選択中のキャラが入るような位置で開いて欲しいです。
![image](https://user-images.githubusercontent.com/59691627/184521906-eca55bdf-01d1-449d-bc77-199f4e49f798.png)

### Pros 良くなる点

スタイルを変えるときにスクロールする必要がなくなる

### Cons 悪くなる点

上のキャラが選択しにくくなる？

### 実現方法

https://quasar.dev/vue-components/scroll-area#scroll-position
ここらへんでスクロールさせる？

## VOICEVOXのバージョン

（開発版）

## OSの種類/ディストリ/バージョン

- [x] Windows 10 Pro
- [ ] macOS
- [ ] Linux

**Comment by Hiroshiba** [comment]
なるほど！！スタイル変更を容易にしたいという感じですね、たしかに！

スクロールする方法だと、たとえば一番下のキャラは結局遠いままになりそうです。
選択中のキャラだけ一番上に表示されるようにするのとかどうでしょう？👀

**Comment by sevenc-nanashi** [comment]
確かに、上にピンでも良さそうですね。

**Comment by Hiroshiba** [comment]
（メンテナ判断メモ）
「選択中のキャラが上に表示される」だと、次に選びたいキャラクターの位置が、直前のセルで操作していたキャラクターによって変わってしまう問題があるなと思いました。

たとえば１番２番３番のキャラで会話を作っているときに２番目のキャラを選ぼうとした場合、

1. １番目→２番目の場合は「上から２番めに表示」
2. ３番目→２番めの場合は「上から３番目に表示」

となります。
これは操作に支障を来すかもしれないと思ったのですが、[頂いてるPR](https://github.com/VOICEVOX/voicevox/pull/1176)で実際に試した感じは意外と大丈夫そうでした。

ただこれは僕はFPSゲームとかがそこそこ得意で、アイコンが表示されてからエイムを合わせてクリックすることにそこまでストレスを感じないためかもしれません。
もし実際試してみて微妙だと感じる方が多そうだったら再考したいかもです。

**Comment by Hiroshiba** [comment]
モーフィング側の順序が変わってしまう問題があったのでこちらで修正してみました！！

- https://github.com/VOICEVOX/voicevox/pull/1183

**Comment by sevenc-nanashi** [comment]
> もし実際試してみて微妙だと感じる方が多そうだったら再考したいかもです。

これで動画を作ってみてましたが、少し微妙でしたね...
選択中 -> q-splitter -> 全て、みたいな感じが1番丸いと思います。

**Comment by Hiroshiba** [comment]
@sevenc-nanashi なるほどです！！
ちなみに「全て」には「選択中」のキャラも含まれる想定でしょうか 👀 （じゃないと結局場所移動しちゃうな）

**Comment by sevenc-nanashi** [comment]
> ちなみに「全て」には「選択中」のキャラも含まれる想定でしょうか 👀 （じゃないと結局場所移動しちゃうな

ですね。

**Comment by Hiroshiba** [comment]
なるほどです、認識揃った気がします。
あるいは勝手にスクロールされて選択中のキャラがマウスカーソルの近くに表示される、とかもありかもと思いました。実装がかなり大変そう（というかquasarだったら無理）な気がしますが。

他の人の意見も聞けると嬉しそうなので、新しくissueを建てるのが良さそうです。
issue作成をお願いしてもよろしいでしょうか。（切り貼りで作った概念図などがあるとたぶんすごくイメージしやすいと思います）
お時間微妙であればこちらで作成します 🙏

**Comment by Hiroshiba** [comment]
@sevenc-nanashi すみません、こちら方針どうでしょう 👀 
（ご面倒であれば遠慮なく言っていただければ！！）

**Comment by sevenc-nanashi** [comment]
建てました（いい言葉が思いつかない…）

**Comment by Hiroshiba** [comment]
すみません、こちらの機能ですが、選択されたキャラクターが一番上に移動すると、複数のキャラクターが連続して会話するような時（キャラクターをコロコロ変えるとき）に想像している順番と違う順番でキャラクターが表示されることがある（今選んでいるキャラクターが誰かに依存して順番が変わるように感じる）ので、UXとして結構変わるという判断になりました。
なので一旦リリースからはrevertさせて頂こうと思います。

#1537 で議論されている通り、選択されているキャラクターを一番上に表示しつつ、キャラクターの順番もそのまま表示される形だったらいいのかな、という感じなのですが、その機能がまだ実装されていないので一旦revertという判断です。
申し訳ないです 🙇 
（cc @sevenc-nanashi @tunamaguro ）
