### ISSUE TITLE
アクセント欄で読みの調整を行うとメニューバーが消える

### ISSUE THREAD

**Issue by y-chan** [VOICEVOX/voicevox#901]
## 不具合の内容

題の通り

- 現在使用しているQuasar 2.7.3が原因のようです。 #846 以降発生するようになりました。
- 辞書UIの優先度機能で使っている機能はv2.4以上で使えるようになっており、Quasarを2.4.13までダウングレードしたところ、改善されましたが、他に改善手段がないか探したいかも...?

<img width="1327" alt="スクリーンショット 2022-08-18 11 49 25" src="https://user-images.githubusercontent.com/34832037/185355952-8bae61f0-247c-4683-98ff-bb2f21806637.png">

### 現象・ログ

適当な文字列を入力し、読みを修正しようとしたところ、メニューバーが消えてしまった

### 再現手順

テキストセルに適当な文字列を入力し、アクセント欄で読みを修正する

### 期待動作

メニューバーが消えない

## VOICEVOXのバージョン

0.13.0

## OSの種類/ディストリ/バージョン

- [x] Windows
- [x] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！！
リリース予定の0.13.1に、とりあえずダウングレードするの含めて良いかもですね…。

**Comment by k-chop** [comment]
なぜこういう挙動になるんだろう？と気になったのでちょっと調べてみました
今後再度Quasarのバージョンを上げたくなったときの参考になれば...

## まとめ
- Quasar 2.6.6まではこの問題が起こらないので安全に上げられる
- Quasar 2.7.0で入ったこのコミット https://github.com/quasarframework/quasar/commit/76a9cc4c4aae4800a4d56b3dbda96095aebfaae8 が原因
- Quasar最新版(2.7.7)に上げても、 `Home.vue` に以下の変更を加えればとりあえずこの問題は起きない
```diff
- <q-layout reveal elevated>
+ <q-layout reveal elevated :tabindex="undefined"> 
```

## 原因
- 前提1：QPopupEdit(内で使われているQMenu)には、非表示になったタイミングで [直前にfocusしていたElementを再focusする挙動](https://github.com/quasarframework/quasar/blob/3238300/ui/src/components/menu/QMenu.js#L244-L262) が存在
- 前提2：QLayoutは [min-heightをscreen.heightから計算](https://github.com/quasarframework/quasar/blob/e671563/ui/src/components/layout/QLayout.js#L48-L52) しているので、下部にメニューバー分の空白を持っている
    - `<body>` の `overflow: hidden` を外すとわかりやすい
- 上記コミットの `tabindex="-1"` によって、QLayoutのElementが再focusされるようになった（今までは `<body>` ）
- focusされたElementは [画面内に入るようにスクロールされる](https://developer.mozilla.org/ja/docs/Web/API/HTMLElement/focus) ため、下の空白が＼ｺﾝﾆﾁﾜ／する

## これまでとこれから
- 以前は `<body>` が再focusされていて、これはメニューバーを含み下の空白は含まないので問題なかった
- `:tabindex="undefined"` はtabindex指定を上書き消去する脳筋解決策です
- ちゃんとやるならそもそも下部の空白が作られないようにする対策が必要そう

**Comment by Hiroshiba** [comment]
調査＆詳細ありがとうございます！！（パズルみたいで面白いですね･･･！）

おっしゃる通り、最も良い解決策は空白ができないようにすることだろうなと思いました！
こんな感じ↓でheightをちゃんと計算してる？箇所もあるので同じようなコードでできるかもと思いました。
https://github.com/VOICEVOX/voicevox/blob/5af6ed3c3d42bce1c2fd50d95b6b0821e8ed7b0d/src/views/Home.vue#L744-L749

将来Quasarに更新が入ったときにこのバグを忘れて再発する気がしています。
もしこのあたりわかりましたら、よかったら修正PR作るのお願いしたいです 🙏

**Comment by k-chop** [comment]
風が吹けば桶屋が儲かるみたいな話でしたね・・・

参考コードありがとうございます！
軽く試してみたところ [containerized layout](https://quasar.dev/layout/layout#containerized-qlayout) にしてmin-height指定したらうまくいってそうな雰囲気なので、
挙動が変わった部分がないかの影響調査、他OSでも動作確認をして問題なさそうであればPR出します！
少々お待ちください 🙇 （今週中くらいには...）

**Comment by Hiroshiba** [comment]
おお！嬉しいです、ありがとうございます！！
