### ISSUE TITLE
リリースされているタグの場所がおかしい

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#904]
## 不具合の内容

例えば0.13.1のリリースは abff6c0 となっていますが、これはmainブランチであり、release-0.13ブランチではありません。
![image](https://user-images.githubusercontent.com/4987327/185748032-899452c9-db2d-4a45-974c-7778166d6309.png)

こちらのissueに関連していると思います。

https://github.com/svenstaro/upload-release-action/issues/63

**Comment by Hiroshiba** [comment]
こちらの課題に関して、[voicevox_blog](https://github.com/VOICEVOX/voicevox_blog)からタグ情報をもとに情報を引っ張っているコードに影響が出るので、優先度を上げたいと思います。
（release用Github Actions jobの依存先を変えれば解決しそうな気もするのですが、おすすめのものがあれば教えてほしいです･･･！）

**Comment by sevenc-nanashi** [comment]
https://github.com/softprops/action-gh-release だとブランチをtarget_commitishで指定できそう。

**Comment by Hiroshiba** [comment]
おー！！良いですね！！

**Comment by aoirint** [comment]
0.13.xからコード署名の切り替えのために、手動でReleaseを作らないようにしたんですね

- <https://github.com/VOICEVOX/voicevox/pull/852#issue-1295948908>

単純には、0.12.x以前のように <https://github.com/VOICEVOX/voicevox/issues/904#issuecomment-1221497933> などで、 [svenstaro/upload-release-action](https://github.com/svenstaro/upload-release-action) の実行前にGitHub Releaseをあらかじめ作成しておくようにすると、修正は少なく済みそうです。

もしくは、変更量は多めになりますが、アップロード部分もほかのActionに置き換えてしまってもよさそうです。
<https://github.com/VOICEVOX/voicevox/issues/904#issuecomment-1221497933> の [softprops/action-gh-release](https://github.com/softprops/action-gh-release) はRelease Assetアップロード機能があるみたいです。

**Comment by aoirint** [comment]
気になる点としては、自動でリリースが作成されたことをトリガーとして、手動のCIとは別に、自動でCIが走りそうなんですが、Action実行履歴を見る感じBuildについては走っていないような...？　どのあたりが影響して実行されていないのか個人的によくわかっていないです。。（自動作成Releaseだから？？）

- `release`イベントのドキュメント: <https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release>
- `event:release`のAction実行履歴: <https://github.com/VOICEVOX/voicevox/actions?query=event%3Arelease>

アップロード済みのRelease Asset（おそらくコード署名されている）は上書きしない設定になっている（`overwrite: false`）と思うので、リリース作成起因でBuildが走ってもまあ大きな問題はないと思いますが・・・。
GitHub ActionのCIはたまに失敗するので、一部のビルド成果物だけリリース作成起因でビルドされて、コード署名がない、のようなことにはなり得るのかもしれない・・・？

<https://github.com/VOICEVOX/voicevox/blob/0435703c3c9183a6c774f10e9c19a1ff12d32707/.github/workflows/build.yml#L7-L9>

**Comment by Hiroshiba** [comment]
> 自動でリリースが作成されたことをトリガーとして、手動のCIとは別に、自動でCIが走りそうなんですが、Action実行履歴を見る感じBuildについては走っていない

･･･････あれ！！たしかにそうですね。。。
ちょっと考えたのですが、よくわからないですね･･･。自動リリースだから･･･以外に考えられなさそうですが、うーん･･･。

仕様変更等が起こって、なにかしらの上書きがされるなどの問題が起こりうる気がします。
かといって対策も思いつかないですが･･････
（actionsをreleaseで起動するのはデバッグがやりやすいのでなるべく外したくない）

**Comment by aoirint** [comment]
- core 0.13.x: https://github.com/VOICEVOX/voicevox_core/pull/311
- core main (Rust版): https://github.com/VOICEVOX/voicevox_core/pull/315
- engine: https://github.com/VOICEVOX/voicevox_engine/pull/489
- editor: https://github.com/VOICEVOX/voicevox/pull/985

コード署名のためCIからリリースを作成するようになったリポジトリを修正したので、Closeします！
