### ISSUE TITLE
読み方&アクセント辞書に新規単語登録時、設定した単語優先度が保存されない

### ISSUE THREAD

**Issue by kantas-spike** [VOICEVOX/voicevox#907]
## 不具合の内容

読み方&アクセント辞書に単語を新規登録した時に、単語自体は新規作成されるが、単語優先度が保存されずデフォルトの5のままである。

### 現象・ログ

「純色」(じゅんしょく)という単語を、単語優先度で8で新規登録した。

![スクリーンショット 2022-08-21 6 36 01](https://user-images.githubusercontent.com/101532773/185767359-7e212153-3934-43a3-86fd-fb8739016033.png)

保存された単語の内容を編集ボタンを押して確認すると、「読み」や「アクセント」は設定されているが、単語優先度が5になっている。

![スクリーンショット 2022-08-21 6 37 07](https://user-images.githubusercontent.com/101532773/185767408-5adb9129-306b-4aed-a55e-a61bb89b55b4.png)

この現象は新規登録時のみです。編集からの保存時は、単語優先度が保存されます。

#### 検証

`store/dictionary.ts`の`ADD_WORD`処理部分で、`priority`の取得と、`addUserDictWordUserDictWordPost`への引き渡しが漏れていることが原因だと考えられます。

以下のブランチで修正して動作確認したところ、単語新規登録時に単語優先度が保存されることを確認しました。

https://github.com/kantas-spike/voicevox/tree/fix_missing_priority_when_add_word_in_dictionary

必要があればPull Requestを作成します。

### 再現手順

現象・ログに記載した手順で再現できます。一度登録した単語を削除し、再度新規登録した場合にも再現します。

### 期待動作

単語の新規登録時にも単語優先度を保存できること。

## VOICEVOXのバージョン

0.13.1

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [x] macOS
- [ ] Linux

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！！
ぜひプルリクエストを送って頂けると･･･！

こちらは結構重要度が高そうなので、hotfix版をリリースすることを検討しようと思います！

**Comment by Hiroshiba** [comment]
hotfixに関してですが、ユーザーの行動的には暫くの間は「初期値に設定して現れなかったら優先度を上げる」という方が多めだとすると、その方々はこの挙動に引っかからないはずです。
ということで、次のパッチバージョンアップデート（おそらくキャラ追加、１月以内？）のときに一緒にリリースしようかなとおもいます。
バグ報告が何件かあれば優先度を上げてhotfixリリースを出すこととします。

素早い修正ありがとうございました！！！

**Comment by kantas-spike** [comment]
ご対応ありがとうございました!!
