### ISSUE TITLE
オプションのヒントに表記揺れがある

### ISSUE THREAD

**Issue by sevenc-nanashi** [VOICEVOX/voicevox#908]
## 不具合の内容

タイトル通り。オプションのヒント（(?)アイコン）に表記揺れが発生しています。

### 現象・ログ

> GPU モードの利用には GPU が必要です。Linux は
NVIDIA&trade; 製 GPU のみ対応しています。

> 音声ファイルを設定したフォルダに書き出す

> 各UIの利用率などのデータを送信してVOICEVOXの改善に役立てます。テキストデータ・音声データは送信しません。

など、常態・敬体、`。`の有無が揺れています。

### 再現手順

（なし）

### 期待動作

表記が統一されている

## VOICEVOXのバージョン

0.13.1

## OSの種類/ディストリ/バージョン

- [x] Windows 10 Pro 64Bit
- [ ] macOS
- [ ] Linux

**Comment by Hiroshiba** [comment]
issueありがとうございます！
このあたりの表記ゆれは、ユーザーへの信頼感につながってくるのでぜひ統一したいです。

**Comment by Hiroshiba** [comment]
こちら多分解決したので、closeします！
ちなみに一方で縦幅のサイズとかが揺れているので、そっちはそっちで0.15前に調整しようと思います。
