### ISSUE TITLE
タスクトレイに格納できるようにして欲しい

### ISSUE THREAD

**Issue by minagiduki** [VOICEVOX/voicevox#911]
## 内容

ソフトを最小化した(もしくは閉じるボタンを押した)際にタスクトレイに格納できるようにして欲しい

#### 挙動イメージ
最小化で格納する場合：そのまま格納
閉じるで格納する場合：終了か格納かを設定で変更し、それに従う

### Pros 良くなる点

常駐時邪魔にならない

### Cons 悪くなる点

特になし

## VOICEVOXのバージョン

0.13.1

## OSの種類/ディストリ/バージョン

- [x] Windows

**Comment by minagiduki** [comment]
返答遅れすみません。
普通の最小化ではなく、通知領域への格納という意味です。
(Discordや棒読みちゃんのように)

**Comment by Hiroshiba** [comment]
なるほどです、理解しました！！

音声合成部分はVOICEVOX ENGINEが担っていて、エディタはUIを提供するものなので、常駐のことを考えていません。
ということでcloseさせていただこうと思います。

ただ、エンジン側にあるととても便利そうだなと感じました！
もしよかったら[エンジン側](https://github.com/VOICEVOX/voicevox_engine/issues)に同じissueを建てて頂ければと思います！

**Comment by raa0121** [comment]
http://www.vector.co.jp/soft/winnt/util/se317779.html
外部ツールを使用すれば、通知領域へ格納することができます。
必要であれば、使ってみてください。

**Comment by aoirint** [comment]
タスクトレイ常駐機能、エディタにちょっとほしいと思っていました。

以下のような使い方をするとき、VOICEVOXエディタを最小化したり、他のウインドウの後ろにおいたりして使っています。

- 生放送のコメント読み上げをさせる（SAPIForVOICEVOX＋棒読みちゃんほか）
- YMM4からエディタ同梱のVOICEVOXエンジンに繋ぎこむ

このときに、限られたタスクバーの幅を節約できる・必要な時にすばやくエディタ画面を呼び出せるのは便利な機能だと思います。

![image](https://user-images.githubusercontent.com/27213639/186585529-9befc416-dba6-43dd-b3a8-89044bd47170.png)

![image](https://user-images.githubusercontent.com/27213639/186592834-0aef3322-37a5-46fd-8fe2-f52f4feed0f0.png)

**Comment by aoirint** [comment]
実装面では、エディタ終了時に通常はエンジンの終了をする関係で、状態管理や分岐が複雑になるかなと思っていましたが、
ウインドウを隠す処理 `window.hide()` / `window.show()` をする程度であれば許容できるのかなと思いました。

タスクトレイ格納の挙動は、アプリケーションによってばらつきがあります。

- 最小化したとき、タスクバーに格納
- 最小化したとき、タスクトレイに格納
- ×ボタンを押したとき、タスクトレイに格納・タスクトレイから右クリックメニューで終了

![image](https://user-images.githubusercontent.com/27213639/186592423-ca1cb61f-fffa-416d-9a69-9f11b7bced30.png)

実装例

- <https://stackoverflow.com/questions/37828758/electron-js-how-to-minimize-close-window-to-system-tray-and-restore-window-back>

他のアプリケーションのタスクトレイ常駐設定欄の例

<details>
<summary>Discord (Electron製)</summary>

![image](https://user-images.githubusercontent.com/27213639/186591295-79f6583f-1560-4cbb-893b-2602936cdbef.png)

</details>

<details>
<summary>メモソフト Joplin (Electron製)</summary>

![image](https://user-images.githubusercontent.com/27213639/186584011-8dc6532b-3ad1-4a15-b77b-4a62d20491ce.png)

</details>

<details>
<summary>配信ソフト OBS Studio</summary>

![image](https://user-images.githubusercontent.com/27213639/186583832-ea5c6f42-a859-40e0-b4b4-e6bd1af71f8a.png)

</details>

（ちなみに、終了したはずのアプリケーションがアイコンだけタスクトレイになぜか残っている、ということは、アプリケーションの種類に関係なくよくあるのですが、そのあたりはおそらくWindowsの問題で、実害はないと思います...）

**Comment by Hiroshiba** [comment]
詳細な検討ありがとうございます！！

意見を受けて再考してみたのですが、やはりエディタの機能として必須だとは思わない感じでした。

たぶんやりたいことは、「音声合成ができるエンジンがバックグラウンドで動作し、かつタスクバーに表示されない」だと思うのですが、であればやはりエンジンにその機能を付けるのが最適解だと思います。

ただ、エンジン側はUIが無い＆pythonではない（electronではない）のでその実装が面倒なのかなとも思います。
であれば、エディタにその機能をとりあえず付けるというのは、納得できます。

が、やはりエディタのタスクではないと思います。
プルリクエストを頂ければマージしますが、issueとしてはcloseにしておく、という感じ行こうと思います！
