### ISSUE TITLE
Ubuntu 18.04のサポートを切り、バイナリビルドするOSをUbuntu 20.04に移行する

### ISSUE THREAD

**Issue by aoirint** [VOICEVOX/voicevox#913]
Ubuntu 18.04は、2023年4月にOSの標準サポート期限が切れます。

- <https://wiki.ubuntu.com/Releases>

GitHub Actionsでは、OSイメージ`ubuntu-18.04`が2022年12月1日に使えなくなる方針が示され、それまでの間、決まった時間帯にCIが失敗するようにして移行を促す形をとるみたいです。

- <https://github.com/actions/runner-images/issues/6002>

VOICEVOX Coreにも関連するPRが立っています。

- <https://github.com/VOICEVOX/voicevox_core/pull/252>

VOICEVOXのビルドはGitHub Actionsに依存しており、安定して開発を進めるためにも、各リポジトリでOSイメージ`ubuntu-20.04`に移行する作業が必要です。Dockerfileなどがあれば、そちらもUbuntu 20.04ベースに移行する形でよいと思います。
（VOICEVOX側でOSのバージョンを制御するため、基本的に`ubuntu-latest`ではなく`ubuntu-20.04`を使用する形がよいと思います）

また、VOICEVOXのLinux向けバイナリのOS互換性は、ビルドを行うOSのバージョン（に紐づいたglibcとlibstdc++のバージョン）に依存しています。

- ref <https://github.com/VOICEVOX/voicevox_engine/issues/106>
- ref <https://github.com/VOICEVOX/voicevox_core/pull/85>

ビルドを行うOSをUbuntu 20.04へ移行することによって、通常のUbuntu 18.04環境で動作しなくなり、Ubuntu 20.04以降でのみ動作するようになることが想定されます。
詳細には、`glibc >= 2.29`, `libstdc++ GLIBCXX_3.4.26`の環境で動作する想定です。

この結果VOICEVOXは、Ubuntu 18.04のサポートを切る形になると思います。
現状、動作環境としてUbuntu 18.04, Ubuntu 20.04の2バージョンを想定しているので、Ubuntu 20.04, Ubuntu 22.04の2バージョンにサポートを移す形で文面などを修正・アナウンスできるとよさそうです。

- Q&Aの動作環境の文面: <https://github.com/VOICEVOX/voicevox_blog/blob/1eadf67abbd60832acfed67c5226a3fd9dc111fd/src/markdowns/qAndA.md?plain=1#L11>

（関係するリポジトリが多そうなので）そこそこ作業量があって、全体的な方針に関係するので、ひとまずIssueを立てておいた方がいいだろうと思って立てました。

なにかご意見などがあれば！

**Comment by qwerty2501** [comment]
特に障害がなければCIで使用するUbuntuは22.04で良いのでは？

**Comment by Hiroshiba** [comment]
古いバージョンでビルドしたものは新しいバージョンでも使えることが多いので、できる限り古いものでビルドするのが良いのかなと思います！

**Comment by aoirint** [comment]
GitHub API関連、linter/formatter、testなど、ビルドに関係ないCIは、OSはなんでもいい気もします！
（testはテスト内容によりそうで、ちょっと迷いますが・・・）

**Comment by Hiroshiba** [comment]
あ、なるほどです。たしかにCIはどちらでも良さそうに思いました！

**Comment by aoirint** [comment]
こちら、2022-10-18（今日）の日本時間23:00-1:00に停止があります。

移行期限の方は、ユーザーの要望に応えてUbuntu 18.04のサポート終了日 2023-04-01 まで延長されたようです。

0.14か0.15あたりで移行できるとよさそう...?

**Comment by Hiroshiba** [comment]
なるほどです。停止時間を伸ばしていくの、面白い作戦ですね。
まあ、早めに移動しちゃいちゃいですね･･･。

**Comment by Hiroshiba** [comment]
こちら、4/1で期限が切れるので、優先度を高くする必要がありそうです。
ということで優先度：中にしたいと思います。

やることをまとめるとこうでしょうか。

* build.ymlのubuntu-18.04をubuntu-20.04に変更
* releaseを作成してみる（Actionsからできる）
* できあがったものを実行してみる

たぶん4/1以降ビルドが全部落ちちゃうので、早めに移行できると嬉しいかもです 😇

**Comment by Hiroshiba** [comment]
こちら手を付けてみようと思います.
