### ISSUE TITLE
エンジンAPIのエンドポイントの変更方法が分かりづらい

### ISSUE THREAD

**Issue by TOMOFUMI-KONDO** [VOICEVOX/voicevox#914]
## 内容

READMEを見てもエンジンAPIのエンドポイントの変更方法が分かりづらいため、READMEを修正したい。

「実行」のセクションに

> .env.productionをコピーして.envを作成し、DEFAULT_ENGINE_INFOS内のexecutionFilePathにvoicevox_engineがあるパスを指定します。 [製品版 VOICEVOX](https://voicevox.hiroshiba.jp/) のディレクトリのパスを指定すれば動きます。 Windowsの場合でもパスの区切り文字は\ではなく/なのでご注意ください。

とあるが、これだけではエンジンAPIの宛先エンドポイントをどうしたら変更できるのかが分からない。また、実際にはエンジンAPIのサーバさえ立っていればエディタ実行時にVOICEVOX.appのプロセスは起動しなくてもいいのだが、上記のREADMEの記述ではそれが分からない。
https://github.com/VOICEVOX/voicevox/pull/639 を見れば分かるとは思うが、そもそもここに辿り着くのが大変。

そのため、READMEの記述を若干修正することを提案する。

### Pros 良くなる点

- エンジンAPIの宛先エンドポイントの変更方法が分かりやすくなり、VOICEVOXを利用しやすくなる。

### Cons 悪くなる点

特になし

### 実現方法

READMEを以下のように修正する。

```diff
## 実行

`.env.production`をコピーして`.env`を作成し、`DEFAULT_ENGINE_INFOS`内の`executionFilePath`に`voicevox_engine`があるパスを指定します。
[製品版 VOICEVOX](https://voicevox.hiroshiba.jp/) のディレクトリのパスを指定すれば動きます。
Windowsの場合でもパスの区切り文字は`\`ではなく`/`なのでご注意ください。
+voicevoxエディタの実行とは別にエンジンAPIのサーバを立てている場合は`executionFilePath`を指定する必要はありません。

+また、エンジンAPIの宛先エンドポイントを変更する場合はDEFAULT_ENGINE_INFOS`内の`host`を変更してください。

npm run electron:serve

音声合成エンジンのリポジトリはこちらです <https://github.com/VOICEVOX/voicevox_engine>
```

## VOICEVOXのバージョン

0.?.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by Hiroshiba** [comment]
issueありがとうございます！！
たしかにREADMEに記載されていなかったので、修正ありがたいです！
