### ISSUE TITLE
【エンジンのプラグイン化/UI】エンジン再起動

### ISSUE THREAD

**Issue by raa0121** [VOICEVOX/voicevox#917]
## 内容
voicevox/voicevox_project#2 より細分化した issue です。
要件定義等ここで行います。

## VOICEVOXのバージョン

0.?.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by Hiroshiba** [comment]
あ！　再起動周りに関しては @sevenc-nanashi さんがPRまで作ってくださってます…！
https://github.com/VOICEVOX/voicevox/pull/884

タスクリストに反映しておくべきでした🙇‍♂️

**Comment by raa0121** [comment]
私も Discord にそんな書き込みあったなと思って、見返してました。
次の機能に手を付けたいとおもいます。

**Comment by Hiroshiba** [comment]
ありがとうございます！！

**Comment by raa0121** [comment]
#884 がマージされたので、こちらは閉じます
