### ISSUE TITLE
文単位での編集ロック機能

### ISSUE THREAD

**Issue by Appletigerv** [VOICEVOX/voicevox#924]
## 内容

ロック状態を示すアイコンを各文の横に表示し、クリックでロックと非ロック状態を切り替えられるようにする。
ロックされている文については、あらゆるパラメータの変更を禁止する。
ただし、パラメータを参照することはできる。

例えば、以下の画像で第1文がロックされており、第1文をユーザがクリックしたとき―
- 「ｲﾝﾄﾈｰｼｮﾝ」をクリックしてイントネーションの設定状況を確認することはできるが、イントネーションの設定値を変更することはできない。
- 「▶」をクリックして文を再生することはできる。
- 選択されているキャラクターを確認することはできるが、キャラクターの変更はできない。
- 話速、音高、抑揚、音量…も値の確認はできるが、変更はできない。
- ロックされている文は削除できない。
![image](https://user-images.githubusercontent.com/112878528/188656521-a6efbfd1-a0fb-4b36-800c-824dd350fc39.png)

編集ロックはあくまで意図しない編集を防ぐためのもので、再調整したくなった場合は簡単な操作でロック解除できるのが望ましいと考えます。

### Pros 良くなる点

音節やイントネーションをバッチリに調整した文をうっかり触ってしまい（何らかの余計な文字をタイプしてしまうのがありがち）、せっかく調整したものがリセットされてしまって残念な思いをすることがあります。編集ロックがあれば、調整済みの文を意図しない変更からガードでき、作業効率が向上します。

### Cons 悪くなる点

実現方法に記載の通りに実装すると、テキストの編集エリアが若干小さくなります。
小さいディスプレイでの作業性には影響があるかもしれません。

上記の提案に代えて、ロック状態はUIの表示をグレーアウトさせることで表現し、ロック/ロック解除ボタンは削除ボタンと同様にマウスカーソルが特定のエリアにあるときにだけ表示するという案もよいかと思います。これならテキストの編集エリアは小さくなりませんが、ロックの状態が分かりづらい、ロックの解除方法が分かりづらいというデメリットもあります。

### 実現方法

特に指定はありません。

## VOICEVOXのバージョン

0.13.1

## OSの種類/ディストリ/バージョン

特に指定なし。

- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by Hiroshiba** [comment]
提案ありがとうございます！

> せっかく調整したものがリセットされてしまって残念な思いをすることがあります

「やり直し」（ctrl+z）機能でリセット前に戻せます。

VOICEVOXのUIはシンプルを意識しています。
https://github.com/VOICEVOX/voicevox/blob/main/docs/UX%E3%83%BBUI%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3%E3%81%AE%E6%96%B9%E9%87%9D.md

おそらく、ロック機能を使うのはすごく少ない人数だと思います。
ロックUIによって得られる恩恵より、Consで書かれている「テキストの編集エリアが若干小さくなります」のネガティブをユーザー全員が受け持つデメリットが大きいのかなと感じました。

提案いただいた機能は申し訳ないのですが実装しない方針として、closeさせて頂きます。
もしご意見あればコメント頂ければ･･･！
