### ISSUE TITLE
マウスのないノートPCでの調整用に、キーボードの上下キーで調整可能にする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#935]
## 内容

MacBookなど、ノートPCではマウスカーソルがないことが多々あり、マウスホイールでの調整ができない環境があります。
トラックパッド同等のことはできるのですが、ものすごい感度が高くて流石に使いづらい印象です。

キーボードの上下キーで調整可能になれば便利そうです。

### Pros 良くなる点

ノートPCでも細かい調整ができる

### Cons 悪くなる点

とくにない

### 実現方法

「スライダーにマウスカーソルがあった場合、上下キーでそれを調整できる」というのがわかりやすそうではあります。
ただ、これをサクッと実現できるのかわかりません･･･。

↑が難しそうなら、「いったんクリックなどの何らかの方法でスライダーをアクティブにしたあと、上下キーで調整できる」が妥当だと思います。

「ctrl＋上下キーで細かく調整」も可能にできると嬉しそうです。

## その他

ちなみに実際今も調整可能？なのですが、上下が反転しているとのことです。
https://twitter.com/VJCLnxe65GPe1Ce/status/1569214151331053569

**Comment by madosuki** [comment]
上下反転問題はQSliderの実装の問題で、 https://github.com/quasarframework/quasar/commit/29be9f710340d5c6fab8c315d103ce0a2045a8b7 で修正されました。

**Comment by Hiroshiba** [comment]
なんと･･･！！

今試した感じ、クリックするとカーソルが当たるから上下キーで変更可能ですね！
quasarのバージョンアップでとりあえずこのissueは解決できるのかなと思いました！
