### ISSUE TITLE
辞書登録後にアプリを再起動すると辞書が反映されない

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#936]
## 不具合の内容

タイトルのとおりです

### 現象・ログ

特にエラーはありませんでした

### 再現手順

試しているのはmacOSです

1. 起動後、辞書登録（Vtuber→ブイチューバー）
2. テキストにVtuberと打ってブイチューバーになることを確認
3. アプリを消す
4. サイド起動してテキストにVtuberと打っても反映されない

### 期待動作

再起動後も正しく辞書が使える

## VOICEVOXのバージョン

0.13.1

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [x] macOS
- [ ] Linux

## その他

ツイッターで報告をいただいて気づきました
https://twitter.com/Hyssop22112/status/1570605545597571074

**Comment by PickledChair** [comment]
原因を調べてみたのですが、エンジンの方の問題に見えたため、修正 PR https://github.com/VOICEVOX/voicevox_engine/pull/473 を出しました！
