### ISSUE TITLE
無効化済みの機能のタブがショートカットキーで選択できてしまう

### ISSUE THREAD

**Issue by k-chop** [VOICEVOX/voicevox#938]
## 不具合の内容
クリックでは切り替えられないのですが、ショートカットキーでタブ切り替えできてしまうようです。

![Animation4](https://user-images.githubusercontent.com/241973/190633694-bb740134-6e6e-4b0a-9fa0-12f2f1fffb47.gif)

### 再現手順
1. .envの `executionFilePath` に製品版のVOICEVOXのパスを指定する、もしくは使ってるエンジンのengine_manifest.jsonを編集？してvoicevoxを起動
2. 「ｲﾝﾄﾈｰｼｮﾝ欄を表示」「長さを表示」のショートカットキー（デフォルトは2と3）でタブを切り替える

### 期待動作
無効化されていればショートカットキーでも切り替えられない

## VOICEVOXのバージョン

mainブランチ（現状の製品版では起きない）

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by sevenc-nanashi** [comment]
簡単に修正できそうだったので修正PRしました。

**Comment by Hiroshiba** [comment]
issueと関係ないのですが、右下にキー入力が書かれた動画とてもわかりやすいですね！
どうやって作られているのでしょう 👀

**Comment by k-chop** [comment]
修正ありがとうございます！！

[ScreenToGif](https://www.screentogif.com) というソフトで動画撮っています。
録画中のキーストロークを記録してくれているので、簡単に動画に反映できて便利です 👍 
ref: [https://zenn.dev/ctrlkeykoyubi/articles/how-to-screen-to-gif](https://zenn.dev/ctrlkeykoyubi/articles/how-to-screen-to-gif#5.4.-%E3%82%AD%E3%83%BC%E3%82%B9%E3%83%88%E3%83%AD%E3%83%BC%E3%82%AF%E3%82%92%E8%A1%A8%E7%A4%BA%E3%81%95%E3%81%9B%E3%82%8B)

**Comment by Hiroshiba** [comment]
おーー　ありがとうございます！！
