### ISSUE TITLE
electron:serve し、コードに変更を加えた後、Illegal operation on a directory. のエラーが出ることがある

### ISSUE THREAD

**Issue by raa0121** [VOICEVOX/voicevox#941]
## 不具合の内容

![image](https://user-images.githubusercontent.com/237271/190859126-78a61f00-5552-4e37-bc4a-f550f79c513a.png)

### 現象・ログ

上記のエラーダイアログがでる

### 再現手順
electron:serve し、コードに変更を加え、リビルドされる

## VOICEVOXのバージョン

0.?.0

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

## その他

https://live.nicovideo.jp/watch/lv338511382 中にヒホさんの手元で発生した

**Comment by Hiroshiba** [comment]
ちょっと調べたのか想像しただけなのか定かじゃないのですが、ホットリロードのタイミングでディレクトリが引数に渡る形でアプリが実行され、その引数をドラッグアンドドロップ時のプロジェクトファイルだと勘違いし、ファイルを読もうとしてこのエラーになっているのでは、とか思ってます。
