### ISSUE TITLE
キャラクター（正確にはスタイルごと）にデフォルトプリセットを割り当てる

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#956]
## 内容

プリセットはプロジェクトを新規作成するたびに毎回何かを適用する必要があります。
最初からスタイルごとに１つデフォルトプリセットが割り当たっていることにすると、例えばあとから一斉に調声を変更できたり、最初にプリセットを選ぶ手間が省けたりしていろいろ便利です。

このissueは、キャラクターのスタイルごとにデフォルトのプリセットを割り当てるissueです。

### Pros 良くなる点

不便さが１つ減る

### Cons 悪くなる点

実装がやや複雑かも

### 実現方法

スタイルごとの特別なプリセットというのをどうコード上に表現するかがやや難しいかも

## その他

このissue達成で解決できる要望は結構いろいろあるので、優先度を中にしています。
https://twitter.com/zyagachannel/status/1574439978272460801

**Comment by Hiroshiba** [comment]
こちらですが、最近見かける要望の大半はこれなので、優先度を最大にしたいと思います。
ご興味あれば･･････！！！

**Comment by k-chop** [comment]
手元でだいたい形になったので着手宣言しておきます 🙋 
コード手直しバグ修正動作確認が済んだらPR出します

方針としてはこんな感じになってます。
この時点で思ってたんと違うぞ等あれば軌道修正しますので教えてください

### 挙動
- voiceを切り替えたときに、対応するデフォルトプリセットを適用する
   - 既存の挙動は「現状のプリセットを引き継ぐ」なので、breaking changeです
- (＋)ボタンによるAudioItemの追加時は、デフォルトプリセットを適用しない
   - 既存の挙動が「直前のプリセットを引き継ぐ」なので変更なしです
   - AudioItem追加してvoiceを切り替えないなら、ユーザは直前のプリセットを引き継ぎたいはず
### データ周り
- デフォルトプリセットは、voiceを切り替えたときに存在しなければ新たに作成する 
- Voice型からuuidv5でpresetKeyを決定する
    - 将来styleIdがUUIDになる変更が入ったときはマイグレーションが必要
- Preset型に `isDefault: boolean` フィールドを追加
### UI
- プリセット管理・新規作成ダイアログでは、デフォルトプリセットは一切表示せず操作させない
- プリセット選択UIでは、デフォルトプリセットが必ず1番上に来るようにする
- プリセット選択UIでは、現在のvoice以外のデフォルトプリセットは表示しない

**Comment by Hiroshiba** [comment]
> voiceを切り替えたときに、対応するデフォルトプリセットを適用する

おおお･･････なるほどです、プリセットが必ず割りあたっているから、ということですよね･･･。
これはどうすべきか非常に難しいですね･･･。
例えばプリセットを使わない人が、全キャラで「前後の無音時間」を揃えたい場合、「なぜかキャラ変えるとパラメータが戻る」という挙動になるので･･･。

「変更時にデフォルトプリセットを適用する」というチェックボックスがあれば良い･･････？
（ここはかなり盲点でした、書いてくださってありがとうございます！！！）

ここに関して、一緒にプリセットの挙動で悩んだ @Oyaki122 さん・ @Segu-g さんもよかったらコメントもらえると心強いかもです 🙇‍♂️ 

> Voice型からuuidv5でpresetKeyを決定する

uuidv5を使うの面白いなと思いましたが、ランダムなuuidv4だとマイグレーションコストが将来減らせるかもと思いました！

> Preset型に isDefault?: boolean フィールドを追加

voiceごとにデフォルトのプリセットキーがどれかを持たせる方が、一意であることを保証できるので良さそうに思いました！
でもisDefaultをデータ構造に持たせたほうがコード書くのは簡単ですよね･･･。
そこまで大変じゃなさそうなら、voice→デフォルトプリセットキーのRecordなりMapなり持つのが良いのかなーと･･･！

この３点以外は方針として良いのかなと思いました！！
丁寧に進めてくださってほんとに助かります！！！

**Comment by k-chop** [comment]
> 例えばプリセットを使わない人が、全キャラで「前後の無音時間」を揃えたい場合、「なぜかキャラ変えるとパラメータが戻る」という挙動になる

！！！！考慮漏れでした。
デフォルトOFFだと機能の存在に気付いてくれないパターンが怖かったのですが、これは選べるようにしておかないと困りそうですね。設定画面にチェックボックスですかね・・・

> uuidv4
> voice→デフォルトプリセットキーのRecordなりMapなり持つのが良い

たしかに！ではこちらのパターンで行こうと思います。実装は全然大変ではないです！
ただ、MapやRecordなら、Voice型をkeyとして扱うために結局stringにserializeしないといけないので
voiceに含まれるstyleIdがnumber -> uuidに変わったときは結局migrationが必要な気はします。
でも変更箇所はkeyだけで済むのでこちらのが良いですね 👍 

（もしくはserializeせずにdefaultStyleIdsと同じような形で持った方が良い・・・？これでもmigrationは必要ですが）
```
"defaultStyleIds": [
   {
	"speakerUuid": "7ffcb7ce-00ec-4bdc-82cd-45a8889e43ff",
	"defaultStyleId": 2,
	"engineId": "074fc39e-678b-4c13-8916-ffca8d505d1d"
   }, ...
]
```

----

ありがとうございます！とりあえず方針問題ない部分のブラッシュアップから手をつけていきます～

**Comment by Hiroshiba** [comment]
defaultStyleIdはkeyがspeakerIdなので結構気軽にできるんですよね･･･。
Voiceをキーにする良い方法、ちょっと調べてみたけど見当たりませんでした。今のDefaultIdみたくしてもまあ仕方ないかなと思いました！

**Comment by k-chop** [comment]
```
defaultPresetMap: [
   { speakerUuid: "...", engineId: "...", styleId: "...", defaultPresetKey: "..." }
]
```
了解です！
そしたらとりあえず保存は上記のような感じで、
プログラムからはこんなインターフェースで扱えるようにしておこうと思います
`getDefaultPresetKey: (v: Voice) => string`
`setDefaultPresetKey: (v: Voice, uuid: string) => void`

**Comment by sevenc-nanashi** [comment]
>  Voiceをキーにする良い方法、ちょっと調べてみたけど見当たりませんでした。

`Voice`をクラスにしちゃって、`Voice#toString()`みたいなのがあると少しやりやすそう…？

**Comment by Hiroshiba** [comment]
あれ、意外とありかもですね。
流石にtoStringだとstring型になっていろいろ悲しそうだなと思いましたが、さらなるアイデアで、toStringしたらできる文字列を（[EngineId](https://github.com/VOICEVOX/voicevox/pull/1172)みたいに）ブランド型のVoiceIdにしちゃって、あとはVoiceIdをVoiceにするVoice関数作れば･･･？
うーん･･･できるのかな。まあ、この辺りのパズル解くのはとりあえずできてからでいいかもと思いました 😇

**Comment by sevenc-nanashi** [comment]
`engineId:speakerUuid:styleId`みたいな文字列にすれば相互変換もやりやすそう。（名前は`#key`とかの方が良いのかも）

まぁこれは後回しでも大丈夫そう

**Comment by k-chop** [comment]
昨日 defaultStyleIds 形式で書き換えてたら意外と使う側のコードが複雑になり、Mapの形で持てた方が断然楽だと気付きました・・・

> engineId:speakerUuid:styleIdみたいな文字列にすれば

おっなるほど！
各フィールド連結でserializeすればVoiceId <-> Voiceも簡単だし、
`{ [voiceId: VoiceId]: string }` でdefaultPresetKeysが保存できてシンプルになりますね。


sevenc-nanashiさんHiroshibaさんありがとうございます！！！！
では defaultStyleIds 形式はやめて `defaultPresetKeyMap: { [voiceId: VoiceId]: string }` で持てるようにしとこうと思います。
Branded Typesの導入も既存のマイグレーション要らないし、そんな大変ではないと思うので一緒にやっちゃいますね

**Comment by k-chop** [comment]
現時点の仕様のまとめ（PRから参照する用）

### 挙動
- `enableAutoApplyDefaultPreset` が
   - `true`のとき
      - voiceを切り替えたときに、対応するデフォルトプリセットを適用する
   - `false` のとき
      - voiceを切り替えたときはそれまで適用していたプリセットをそのまま継承
      - 既存の挙動と変更なし
- (＋)ボタンによるAudioItemの追加時は、デフォルトプリセットを適用しない
   - 既存の挙動が「直前のプリセットを引き継ぐ」なので変更なし
   - AudioItem追加してvoiceを切り替えないなら、ユーザは直前のプリセットを引き継ぎたいはず
### データ周り
- デフォルトプリセットは、以下のスタイルがデフォルトプリセットを持っていない場合に作成される
   - voiceを切り替えたときの、切り替え先のスタイル
   - 起動時、最初のAudioItemに設定されたスタイル
   - 新規プロジェクト作成時、最初のAudioItemに設定されたスタイル
- デフォルトプリセットについての補足
   - `enablePreset` と `enableAutoApplyDefaultPreset` の状態に関わらず作成する
   - プリセット機能がONならプリセット一覧から選べるようになる
- configに`defaultPresetKeyMap`を追加し、`Record<VoiceId, PresetKey>` の形でVoiceとそのデフォルトプリセットを関連付ける

### UI
- プリセット管理・新規作成ダイアログでは、デフォルトプリセットは一切表示せず操作させない
- プリセット選択UIでは、デフォルトプリセットが必ず1番上に来るようにする
- プリセット選択UIでは、現在のvoice以外のデフォルトプリセットは表示しない
