### ISSUE TITLE
TypeScriptのバージョンを上げたい

### ISSUE THREAD

**Issue by MT224244** [VOICEVOX/voicevox#957]
## 内容

このプロジェクトで使用されているTypeScriptのバージョンはかなり古く、使いたくても使えない機能が増えてきたので、そろそろ最新まで上げたい。

### Pros 良くなる点

v4.3以降に追加された新しい機能等を利用できる。

### Cons 悪くなる点

なし？

### 実現方法

TypeScriptのみをv4.8.3まで上げると、`vuex.ts`の極一部がエラー判定になる。(即修正可能レベル)
`electron:serve`すると、以下の警告が出る。

```
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.3.0

YOUR TYPESCRIPT VERSION: 4.8.3

Please only submit bug reports when using the officially supported version.
```

これを解決するためには`@typescript-eslint/parser`のバージョンを(最新まで？)上げる必要がある。

**Comment by y-chan** [comment]
私は上げてしまった方が今後の開発体験が良くなる可能性もあるので、とりあえずPR作ってしまって良いと思います...!

**Comment by Hiroshiba** [comment]
ぜひ上げてしまいたいですね！！

**Comment by MT224244** [comment]
PRしようと作業進めてたんですが、上で書いた条件だけだと`npm ci`でエラーになりました…。
これを上げるとあれがエラー吐いて…という感じで最終的にeslint関係の大半を上げないといけなくなりそうです😇

**Comment by Hiroshiba** [comment]
なるほどです！！
ちなみなeslint系を全部上げると解決しそうでしょうか…？👀

**Comment by MT224244** [comment]
結局色々バージョンを上げることになりましたが、インストールの問題は解決しました。
なんとかなりそうな感じになったのでとりあえずPR作ります…！
