### ISSUE TITLE
エンジンのログの文字化け対策に対応する

### ISSUE THREAD

**Issue by sabonerune** [VOICEVOX/voicevox#960]
## 内容

ログが文字化けしてしまう問題にエンジン側の修正がマージされましたがこれを有効にするには環境変数`VV_OUTPUT_UTF8=1`をセットする必要があります。
 - https://github.com/VOICEVOX/voicevox_engine/pull/478

### 実現方法

- `.env`に`VV_OUTPUT_UTF8=1`を追加する
- 複数エンジンのことも考えるとエンジンマニフェストに起動時に追加する環境変数や引数を追加することを検討する必要があるかも？

### Pros 良くなる点

ログの文字化けがなくなるためサポートがしやすくなる。

### Cons 悪くなる点

マニフェストの拡張について考慮する必要がある。

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

## その他

とりあえず`.env`に追加すればしばらくは十分だと思いますがビルド時にどのように`.env`が用意されるのか理解できないので自分では追加できそうもありません。

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！
とりあえずengine manifestは置いておいて、`VV_OUTPUT_UTF8=1`で起動するのが良いのかなと思いました！
