### ISSUE TITLE
音声書き出しの際の２つの問題点

### ISSUE THREAD

**Issue by Aspena2022** [VOICEVOX/voicevox#969]
## 内容

**１）設定の書き出しファイル名パターンに、プロジェクトファイル名を含められない**

タグ「$プロジェクト$」を追加したほうがいいです
utility.tsのreplaceTagIdToTagStringにprojectName: "プロジェクト" を追加したり、
DEFAULT_FILE_NAME_TEMPLATEやDEFAULT_FILE_NAME_VARIABLESの定数や、buildFileNameFromRawData関数も修正が必要です

**２）この書き出し設定が、MENUの「音声を繋げて書き出し」の際には反映されない**

ブロック１つずつ書き出すときのみ反映するのはしっくりきません
何のために書き出し設定をするのでしょうか
このときのファイル名にもやはりプロジェクトファイル名が使われないので、
Project.vvproj -> Project.wav のような単純明快な出力ができません

しかもファイル名生成には、プロジェクトを保存する際のutility.tsのbuildProjectFileName関数が呼ばれていて、headItemTextとtailItemTextをくっつけて文字列を作っていますが、
プロジェクトの１ブロック目と最終ブロックのテキストを利用しているようです
中身を確認するためとはいえ、あまりにも変な仕様ではないでしょうか
これでは超長い複雑なファイル名になるし、現実的ではないです
今まで保存の際には手動でいちいち手直ししていましたが、先ほどのように

Project.vvproj -> Project.wav

と素直にプロジェクト名で保存できるように修正したほうがいいと思います
VOICEOVOX派生系のCOEIROINKも同様な状態で、wav書き出しの際にひと手間かかります　積み重なるとけっこうストレスフルな現象です

こちらは少し古いバージョンで管理しているのでPull Requestはしません

### Pros 良くなる点

UIの操作性が改善

### Cons 悪くなる点

なし

## VOICEVOXのバージョン

0.12.0

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

Windows 10 64bit

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます。

@Aspena2022 さんの必要だと思われる機能と、それがないことの不満、そしてとても熱意のある意見を頂きました。
機能の必要性は仰るとおりですが、我々のモチベーションは様々であり、ボランティアでソフトウェアを作成しています。
VOICEVOXは他にもいろんな足りない機能があり、それらで忙しく、長い間、あるいはずっと手が回らないでしょう。

この機能を実装するのに最もふさわしい方は、この機能実装に対して熱意があり、問題性を完全に把握していて、かつその解決能力がある、 @Aspena2022 さん自身です。
ぜひプルリクエスト作成にチャレンジしてみてください。それがこの機能を必要とする方の喜びを最大化できる最適な方法です。

プルリクエストがマージされたあとは、VOICEVOXアプリ貢献してくださった方の一覧に @Aspena2022 さんが掲載されます。
不明な点があればなんでも聞いてください。私たちはあなたのプルリクエストを心待ちにしております。

**Comment by Hiroshiba** [comment]
こちらのissueは課題が２つに分岐しているので、解体して２つのissueにさせていただきます！

**Comment by Hiroshiba** [comment]
issueを作成しました！

- https://github.com/VOICEVOX/voicevox/issues/2075
- https://github.com/VOICEVOX/voicevox/issues/2076

@Aspena2022 さんの貢献もぜひお待ちしています！！
