### ISSUE TITLE
変換時に、入力中の行より上に行がある場合、変換候補の選択を矢印キーで行うと意図しない動作をする

### ISSUE THREAD

**Issue by KenchanPrfm** [VOICEVOX/voicevox#975]
## 不具合の内容
変換時に、入力中の行の上又は下に行がある場合、変換候補の選択を矢印キーで行うと意図しない動作をする。

### 現象・ログ
入力中の行の上又は下に行があり、変換候補を矢印キーで選択すると、変換候補ではなく、入力カーソル自体が上又は下の行に遷移してしまう。
その際に変換後の文字列が１行目に挿入される。
参考画像１：２行目入力中に変換を実施
![スクリーンショット 2022-10-10 18 32 42](https://user-images.githubusercontent.com/63098775/194838598-9e795ed6-6727-4915-8b9f-6bf4dd4d7aae.png)
参考画像２：入力カーソルが１行目に遷移
![スクリーンショット 2022-10-10 18 32 59](https://user-images.githubusercontent.com/63098775/194838991-93d578cf-cd8a-44b5-81da-103c9739affe.png)

### 再現手順

1. Google日本語入力をインストール
2. 入力行を２行以上用意する。
3. 文字入力を行い変換候補を表示させる。
4. 矢印キーで変換候補を選択する。

### 期待動作
行内で変換してほしい。

## VOICEVOXのバージョン
0.13.2

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [x] macOS
- [ ] Linux

*　macOS Monterey（12.6）
*　Google日本語入力（2.25.4030.1）

**Comment by Hiroshiba** [comment]
詳細なissueありがとうございます！！

（ただのメモなのですが、windowsで試したら意図したように動きました。）
