### ISSUE TITLE
[project-s] Scoreからのピアノロール表示

### ISSUE THREAD

**Issue by romot-co** [VOICEVOX/voicevox#986]
## 内容

ピアノロールの表示実装およびScoreからのノートの表示を追加します。
表示までとし、編集や操作は行わない予定です。

### ピアノロール

ピアノロールの表示・ズーム考慮

- [x] 鍵盤
- [x] Y軸の表示: 
  -  [x] キーごとのグリッド(黒鍵/白鍵で塗り分け)
  -  [x] オクターブごとのグリッド 
- [x] X軸の表示:
  - [x] 小節ごとのグリッド
  - [x] 拍ごとのグリッド

### ノート

ピアノロールに対しScoreからノートを表示できるようにする
歌詞なし・横ズーム考慮・縦幅固定

- [x] ピアノロールに対しノートをScoreから位置表示できるようにするX軸: キー(midi) / Y軸(tick)
- [x] ピアノロールに対しのノート長さを表示できるようにする(durationおよびX軸ズーム率より)

### 実現方法

- 現状ファイルから読み込めないため、先にダミーのScoreを用意 → すでに実装いただいたものを使う
- midiからキー(ピッチ)/オクターブ/黒・白鍵をマップする関数を用意
- 再描画に留意

## その他

作業がかぶらない・齟齬がないよう事前調整できればと思います！
https://github.com/VOICEVOX/voicevox/issues/981

**Comment by Patchethium** [comment]
An advice, I'd recommend [OpenUtau](https://github.com/stakira/OpenUtau). It's open source and cross platform, which means you can modify it to dock with voicevox engine, saving a lot of time from building the whole SVS UI from scratch.

**Comment by Hiroshiba** [comment]
Thanks for the advice, @Patchethium san!
We cannot reuse the OpenUtau code as we are motivated to implement this in Electron.

Please take a look here!
https://github.com/VOICEVOX/voicevox_project/issues/15

---

@Patchethium さん、アドバイスありがとうございます！
我々にはElectronで実装したいというモチベーションがあるため、OpenUtauのコードは流用できません。

こちらをご覧ください！
https://github.com/VOICEVOX/voicevox_project/issues/15

**Comment by Patchethium** [comment]
I mean, why do we have to build it ourselves on electron? I don't see the point in doing so, especially given such mature open source projects like openutau. Since the engine is separated from the editor, it can't be hard to use one for TTS, one for SVS, and it's obvious less time consuming.

**Comment by Hiroshiba** [comment]
What we can do is quite different!
In the case of Electron, the language is JavaScript (TypeScript). So we may be be able to run it on a browser or on a smartphone. Also, there are many engineers these days, so it will be easier to contribute and use.

Well, in any case, this discussion may be different from the purpose of this issue. Let's discuss it here if you need more!
https://github.com/VOICEVOX/voicevox_project/issues/15

---


できることがかなり違います！
Electronの場合、言語がJavaScript(TypeScript)です。なので、ブラウザ上やスマートフォンでも動かせるようになるかもしれません。また最近はエンジニアの数が多いので、貢献や利用がしやすいでしょう。

まあいずれにせよ、この議論はissueの目的と異なるかもしれません。続きが必要な場合はこちらで議論しましょう！
https://github.com/VOICEVOX/voicevox_project/issues/15

**Comment by Patchethium** [comment]
では[voicevox_projectのissue](https://github.com/VOICEVOX/voicevox_project/issues/15)に移ります、失礼しました。

**Comment by Hiroshiba** [comment]
project-s達成に従って解決されたと思われるのでcloseします！
お疲れ様でした！！
